### ISSUE TITLE
I suggest we start with the copy of OpenCensus SDK

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#1]

**Comment by gregkalapos** [comment]
Hey @SergeyKanzhelev,

I'd be very happy to contribute. Is there any plan on how to move forward? Do we have any "actionable" items for the .NET implementation?

Also to be not totally off topic:  👍 for starting with the copy of OpenCensus SDK.

**Comment by austinlparker** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
@gregkalapos, @austinlparker great! There are a few smaller items still hanging from OpenCensus repo. If you want to get started right away - find some inspiration in those issues.

I will start posting issues and later a plan. Plus will set up some weekly sync-ups. 

On the high level, I think we can scope September release to API updates to match OpenTelemetry specs and release quality implementation. Plus prod quality autocollectors for ASP.NET Core and System.Net.Http and exporters for Zipkin and Prometheus as a minimum.

**Comment by austinlparker** [comment]
sgtm - I think the OT bridge should be pretty straightforward as well.
