### ISSUE TITLE
Use IOptions<T> for DI options

### ISSUE THREAD

**Issue by AlexeiScherbakov** [open-telemetry/opentelemetry-dotnet#101]
For example StackExchangeRedisCallsCollectorOptions can be be injected as

```
var options=new StackExchangeRedisCallsCollectorOptions();
services.Configure<StackExchangeRedisCallsCollectorOptions>(options);
```

and StackExchangeRedisCallsCollector must have ctor with IOptions or IOptionsMonitor(for reloading options dynamically) for example:
```
public StackExchangeRedisCallsCollector(IOptions<StackExchangeRedisCallsCollectorOptions> options, ITracer tracer, ISampler sampler, IExportComponent exportComponent)
        {
...
        }
```

link: https://docs.microsoft.com/en-US/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2

**Comment by SergeyKanzhelev** [comment]
@pakrym do you have suggestion on how `IOptions` can be used alongside this style of configuring:

https://github.com/open-telemetry/opentelemetry-dotnet#configuration-with-microsoftextensionsdependencyinjection

Where the constructor of zipkin collector will get the options from?

```
services.AddOpenTelemetry(b => b
            .UseZipkin(o => o.ServiceName = "my-service")
```

I'm a bit lost in injections =)

**Comment by pakrym** [comment]
You can add a `T GetOptions<T>()` to `TracerBuilder` (with default implementation being just `new T()` and in `AddOpenTelemetry` extension method create a derived `TracerBuilder` that would implement `GetOptions` via `IOptions<>` resolution.


Then in UseZipkin method would become something like:
```
return builder.AddProcessorPipeline(b =>
            {
              var options  = b.GetOptions<ZipkinTraceExporterOptions>();

                b.SetExporter(new ZipkinTraceExporter(options  ));
                processorConfigure.Invoke(b);
            });
```

**Comment by SergeyKanzhelev** [comment]
I just realized that this will mean that all packages will have a reference to `IOptions` (Microsoft.Extensions.Options) from everywhere except `OpenTelemetry.Api`. It may not work for `net45`. And in general looks excessive. Is it by design or I'm missing something?

**Comment by pakrym** [comment]
I think you can design it in a way where only `OpenTelemetry.Hosting` would have a dependency on `IOptions`
