### ISSUE TITLE
High Quality Callstack

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1018]
Some of the LINQ and lambda code are hurting the callstack quality. This would make it hard to do postmortem debugging, profiling and large scale analysis (e.g. Dr. Watson callstack bucketization).

Here goes one example of a bad callstack:

![image](https://user-images.githubusercontent.com/17327289/89612922-e7ad9300-d835-11ea-9a19-c5585999a502.png)

**Comment by ness001** [comment]
Any ideas on building high-quality call stacks except for extracting the anonymous methods to named methods?
