### ISSUE TITLE
Remove tags added by gRPC library in favor of OpenTelemetry tags

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#1021]
[gRPC for .NET](https://github.com/grpc/grpc-dotnet/tree/master) is instrumented with DiagnosticSource and adds its own tags to an `Activity`. [Proposal](https://github.com/open-telemetry/opentelemetry-dotnet/issues/482#issuecomment-655753756) is to remove these tags now that OpenTelemetry adds its owns set of tags containing the same information.

The gRPC client adds [`grpc_method`](https://github.com/grpc/grpc-dotnet/blob/4daaf07a2675c60957e184d68d40da0270fa8786/src/Grpc.Net.Client/Internal/GrpcCall.cs#L680-L694) and [`grpc_status_code`](https://github.com/grpc/grpc-dotnet/blob/4daaf07a2675c60957e184d68d40da0270fa8786/src/Grpc.Net.Client/Internal/GrpcCall.cs#L723-L742) tags.

ASP.NET Core instrumentation also adds [`grpc_method`](https://github.com/grpc/grpc-dotnet/blob/9c294e0394388a96c17dd8b38ae0fbf5961c968c/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L362-L366) and [`grpc_status_code`](https://github.com/grpc/grpc-dotnet/blob/9c294e0394388a96c17dd8b38ae0fbf5961c968c/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L279-L283) tags.

Tags can be removed by setting the value to null: `activity.SetTag("grpc_method", null);`

**Question**

Is there any concern that anything other than OpenTelemetry may depend on the tags generated from the library itself?

@cijothomas @JamesNK

**Comment by cijothomas** [comment]
I don't see any concern here.
