### ISSUE TITLE
Contrib repo

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/opentelemetry-dotnet#1030]
In the last .NET SIG (08/04/2020), we discussed about the contrib repo and what should we do.

Below some questions that we must decide:
- are we going to maintain the contrib repo?
- who will be the maintainers? will you have time to maintain two repos?
- what the other languages doing? are they maintaining the contrib?
  - **don't have contrib**: java, cpp, php, rust, erlang, ruby, swift
  - **have contrib**: python (last merge 04/09), go (last merge (08/07), js (last merge 08/10)

cc: @reyang @SergeyKanzhelev @CodeBlanch @cijothomas

**Comment by reyang** [comment]
I think who wants to be the maintainer of the contrib repo should reply back here.
If we haven't got reply in a month, we probably should close this issue. Folks who want to take the responsibility later can always re-open the issue.

**Comment by eddynaka** [comment]
@reyang , should we list in the issue what a maintainer have to do, so the user who replies know what he/she will have to do?

**Comment by reyang** [comment]
> @reyang , should we list in the issue what a maintainer have to do, so the user who replies know what he/she will have to do?

Here goes the requirement https://github.com/open-telemetry/community/blob/master/community-membership.md#maintainer.

**Comment by CodeBlanch** [comment]
I think it's good to have the repo. It gives people one place to go to see all the community add-on stuff. Ultimately, that helps the project grow! I don't have a lot of time to spend on it, but I don't mind helping out. It's not like there is a ton of activity. Should we switch the package names to something like OpenTelemetry.Community.*?

**Comment by reyang** [comment]
I would vote for `OpenTelemetry.Contrib` since "community" might be misleading (OpenTelemetry .NET itself is also a community).

**Comment by reyang** [comment]
I think for the contrib repo we probably need to have the following things before proceeding further:
1. Have the initial process documented in the README.md and CONTRIBUTING.md. This would help people (maintainer/approver/user) to set the right expectation.
2. Explore federated model where each component/sub-folder could have individual owners / CI / release cadence. This needs clarification from the spec/TC.

**Comment by eddynaka** [comment]
For the first releases, we could do the same thing as we do in the main repo (one shoot release), so it will be less trouble for the maintainers.

I can help with that, but I think the main focus will be this repo

**Comment by eddynaka** [comment]
> I would vote for `OpenTelemetry.Contrib` since "community" might be misleading (OpenTelemetry .NET itself is also a community).

I will change that

**Comment by cijothomas** [comment]
Closing this issue as there is general consensus about the need for -contrib repo. We probably have to update readme.md in contrib repo and also explore per directory approver in that repo.
