### ISSUE TITLE
Rename "ot" to "otel"

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1042]
OpenTelemetry specification has officially recommended "otel" as the abbreviation rather than "ot" (which could be confusing as it is used for OpenTracing).

Need to find all `ot` names and update them to `otel` when appropriate: https://github.com/open-telemetry/opentelemetry-dotnet/search?q="ot."&unscoped_q="ot."

Reference: https://github.com/open-telemetry/opentelemetry-specification#acronym

**Comment by eddynaka** [comment]
Assign me. i will create a PR replacing the strings

**Comment by eddynaka** [comment]
@reyang , for the case of the extensions, where we have `ot.status_code`, are we going to change that as well?

Or just the comments?
Thanks.

**Comment by reyang** [comment]
Looks like it will be all the cases returned by the query https://github.com/open-telemetry/opentelemetry-dotnet/search?q="ot."&unscoped_q="ot.
