### ISSUE TITLE
MyGet publishing seems to be broken

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1050]
1. Recent merges to master failed to publish MyGet package.
2. I want to bring the topic again - should we simply remove the VSO pipeline and MyGet (and use Actions to publish packages  based on tags)? (I don't see many folks using MyGet packages - they give us maintenance cost without obvious benefit)

![image](https://user-images.githubusercontent.com/17327289/89969381-17301700-dc0b-11ea-81b6-759dde246f3c.png)

**Comment by reyang** [comment]
![image](https://user-images.githubusercontent.com/17327289/89969584-a4736b80-dc0b-11ea-81b5-dee96f69fc3e.png)

**Comment by cijothomas** [comment]
myget push build is broken in Azure Devops. 
Lets first bring it to GHActions. Asked @eddynaka s help to get it. I can setup the myget token as a GH Secret.
And then remove it and replace with nuget daily push.

**Comment by eddynaka** [comment]
@cijothomas let me know the token name so I can set up the variables. I will try some stuff later.

**Comment by eddynaka** [comment]
@reyang , with our latest pr, the myget is working again.

Now, we go back to the questions:
- should we keep pushing to myget every time?
- should we move to nightly push to nuget?

**Comment by reyang** [comment]
Ping back from #1063.
