### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#106]
https://github.com/open-telemetry/opentelemetry-dotnet#opentelemetry-quickstart-collecting-data

```cs
services.AddSingleton<ITracer>(Tracing.Tracer);
services.AddSingleton<ISampler>(Samplers.AlwaysSample);
services.AddSingleton<IPropagationComponent>(new DefaultPropagationComponent());
```

There is no Tracing.Tracer, IPropagationComponent or DefaultPropagationComponent

**Comment by SergeyKanzhelev** [comment]
@discostu105 as you working on samples can you please also update samples in readme?

**Comment by psibernetic** [comment]
Looks like Tracing.Tracer is back, so only thing to change is remove PropagationComponent.
