### ISSUE TITLE
ZipkinTraceExporter.Start does not error when it can't connect

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#107]
Your Zipkin sample code is this:

```cs
var exporter = new ZipkinTraceExporter(
      new ZipkinTraceExporterOptions()
      {
          Endpoint = new Uri("https://localhost:9411/api/v2/spans"),
          ServiceName = typeof(Program).Assembly.GetName().Name,
      },
      Tracing.ExportComponent);
exporter.Start();
```

My docker image did not have HTTPS enabled by default and nothing was captured by Zipkin. An indication should be given that the exporter is not going to work. For example, an exception.

**Comment by SergeyKanzhelev** [comment]
Do you suggest to make `Start` throw if it cannot connect? Ideally we need to get rid of `Start` and autostart. And in this case there will be no place to throw from.

How do you see an ideal configuration behavior?

**Comment by JamesNK** [comment]
How you do it is up to you. Exception, logging, etc. Failing silently is not good option.

**Comment by cijothomas** [comment]
@xiang17 Can you validate that the Zipkin is logging somethign to EventSource in this case? And eventually when we have self-diagnostics, it'll be captured and written to local file.

**Comment by cijothomas** [comment]
The usage is different now. There is no explicit start. In case of any issues faced by the exporter, it simply logs exception to EventSource and continue.
If something is not working as expected - the general guideline will - enable self-diagnostics (instructions to do that is pending in active PRs.)

Please reopen if we need to do more here.
