### ISSUE TITLE
The Jaeger Export should be configurable via the commonly used JAEGER_* environment variables

### ISSUE THREAD

**Issue by chgl** [open-telemetry/opentelemetry-dotnet#1071]
**Is your feature request related to a problem?**
I wanted to set the service name via the `JAEGER_SERVICE_NAME` environment variable. Unfortunately, this was ignored and the default value "Open Telemetry Exporter" was used.

**Describe the solution you'd like.**

If the service name is not explicitly set via JaegerExporterOptions.ServiceName, it should check the common JAEGER environment vars before falling back to the default. The same should happen for the other env vars specified in jaegertracing.io/docs/1.18/client-features/ under "Tracer configuration via environment variables".

**Describe alternatives you've considered.**

Manually reading the env vars and setting them to JaegerExporterOptions.

**Additional context.**

This could be implemented  in https://github.com/open-telemetry/opentelemetry-dotnet/blob/30f841b2eff8e47a3e680a7afbea3ab528faa5d2/src/OpenTelemetry.Exporter.Jaeger/JaegerExporterOptions.cs.

A quick:

```cs
public string ServiceName { get; set; } = Environment.GetEnvironmentVariable("JAEGER_SERVICE_NAME") ?? DefaultServiceName;
```

Could work, but does not handle cases where JAEGER_SERVICE_NAME exists but has no value set (ie calling `export JAEGER_SERVICE_NAME=`).

I'll gladly open a PR for this if the feature request is valid.

**Comment by cijothomas** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry-dotnet/issues/1453
