### ISSUE TITLE
Connection with dotnet/diagnostics tooling

### ISSUE THREAD

**Issue by hacst** [open-telemetry/opentelemetry-dotnet#109]
[dotnet 3.0 introduces tooling for internal metrics and tracing](https://devblogs.microsoft.com/dotnet/introducing-diagnostics-improvements-in-net-core-3-0/) in the form of [dotnet-counters](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-counters-instructions.md) and [dotnet-trace](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md).

I was wondering how this relates to opentelemetry-dotnet. Could there be any meaningful integration with these built-in features or do you see them as too different in use-case or approach?

**Comment by discostu105** [comment]
It raises the question which .NET versions we want to support at all. Is it specified yet @SergeyKanzhelev ?

IMHO, if we define some minimum .NET version (e.g. netstandard 1.5), we can only use the API's available in that version, nothing else.

If we want to utilize .NET Core 3.0 features, we'd have to release this as a separate package (or utilize reflection).

**Comment by SergeyKanzhelev** [comment]
we discussed .NET versions thing at last SIG meeting. [Form notes](https://docs.google.com/document/d/1yjjD6aBcLxlRazYrawukDgrhZMObwHARJbB9glWdHj8/edit?usp=sharing)

> .NET Core 3.0 new metrics API support? It will be an adaptor that only being linked with 3.0. 

So there should be no versioning problem there.

**Comment by cijothomas** [comment]
Closing as there is no action pending. Reopen or create new issue, if there are open questions.
