### ISSUE TITLE
Populate implementation/spec compliance matrix

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-dotnet#1114]
In order to have a better understanding of where we stand in terms of implementing OpenTelemetry specification in various language SDKs we would like to have a compliance matrix that shows which features are implemented in which languages.

This will show how much work is remaining and tell us far away are we from being ready for GA.

The matrix is located here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/spec-compliance-matrix.md

Please open a PR against specification repo and populate each cell in the column for ".Net" in **Traces** and **Exporters** tables with one of the following:

`+` means the feature is supported
`-` means it is not supported
`N/A` means the feature is not applicable to the particular language. If it is not self-explanatory why the feature is not applicable please add a numbered footnote below the table to clarify why, e.g. `N/A [7]`, then later `[7] - This feature makes no sense for language... because...`.

It is OK if you don't have the complete information, please leave the cells blank and come back and complete them later.

Please try to keep the duration that the PR stays open short to avoid merge conflicts when other languages also make changes to the same tables.

Once the initial round of updates to the matrix is done it will be great if language maintainers can periodically update the table as they implement features.

**Comment by reyang** [comment]
Initial PR has been merged https://github.com/open-telemetry/opentelemetry-specification/pull/904.

**Comment by cijothomas** [comment]
completed.
