### ISSUE TITLE
More renames from the spec

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1143]
The spec has changed, need to rename stuff (treated as a bug since we're literally not compliant with the latest spec):
* HTTPText propagator renamed to TextMap propagator (https://github.com/open-telemetry/opentelemetry-specification/pull/793)
* ProbabilitySampler renamed to TraceIdRatioBased (https://github.com/open-telemetry/opentelemetry-specification/pull/611)
* ParentOrElse renamed to ParentBased (https://github.com/open-telemetry/opentelemetry-specification/pull/610)

**Comment by cijothomas** [comment]
Tagging for the immediate beta as we can try to make as many breaking changes as earlier as possible.
