### ISSUE TITLE
Activity should not have public API to set kind

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1145]
We currently expose an extension method to Set Kind.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L84

This internally uses reflection. This is required for instrumentations which are dealing with "legacy" activities which has the default 'internal' kind, and must be changed to right one.

Kind is not something which is expected to be changed after creation, so we shouldn't encourage it by exposing this as public API. 

Options:
1. Remove this from public api. And have it only part of instrumentation projects. (can use shared file to avoid code duplication)
2. Keep public, but add warning stating this is only meant for authors of instrumentation projects which has to deal with legacy Activity creation using new Activity().

**Comment by eddynaka** [comment]
If we go for option (1), people that creates their own instrumentation and have legacy way will have a problem. Based on that, i would go to option (2), and add a remarks tag, so we can say when to use it.

**Comment by cijothomas** [comment]
Closing as this is already removed from public and made part of activitysourceadapter. https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/ActivitySourceAdapter.cs
