### ISSUE TITLE
Use TreatWarningsAsError

### ISSUE THREAD

**Issue by bruno-garcia** [open-telemetry/opentelemetry-dotnet#115]
Building the solution now triggers a ton of warnings
Suggest to turn on ` <TreatWarningsAsErrors>True</TreatWarningsAsErrors>` and clean up the current warnings.

**Comment by enzian** [comment]
I'd take this - it's going to be a huge changeset...!

Do we really want to prefix all local calls with `this`?

**Comment by bruno-garcia** [comment]
It'd be great to use `_` instead of `this`. I'd be glad to make the change if that's the blocker for changing it.

**Comment by enzian** [comment]
> It'd be great to use _ instead of this.

@bruno-garcia: I wish for a refactoring the does that directly ;-)

**Comment by enzian** [comment]
Do we want to force the explicit declaration of access modifiers throughout the codebase?

**Comment by enzian** [comment]
Since #131 is #137 is the follow up to this, can we close this one?
