### ISSUE TITLE
Span/Tracer Shim should be consistent with OTel spec.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1163]
The shim should follow the spec as such. Some notable missing:
TelemetrySpan should have get for Context, parent.
TelemetrySpan should not contain getters/setter for SpanKind. etc.

All the methods to add attributes/events should be noops unless IsRecording = true.

Compare with this doc:
https://github.com/open-telemetry/opentelemetry-dotnet/issues/947

**Comment by eddynaka** [comment]
@cijothomas , how are we going to set the `Context`? That one is only possible if we have the Activity with the correct Context, but it's an indirect set. What do you think?

**Comment by cijothomas** [comment]
My bad - only Get for Context. There is no way to set context after a Span has been started

**Comment by eddynaka** [comment]
@cijothomas , based on that, i think the PR is ready. Let me know what do u think.
