### ISSUE TITLE
Avoid spin entirely if running on a single core

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1169]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/1088#discussion_r471159257

**Comment by KonH** [comment]
Hello, is it actual issue?
As I see, when running code from Add/TryAdd methods on a single-core machine, we already never spinning.
Explanation:
- Single place which produces spinning exists: https://github.com/open-telemetry/opentelemetry-dotnet/blob/688ffd689a1f585f98d9390aea17aa6d6a32cdef/src/OpenTelemetry/Internal/CircularBuffer.cs#L102
- It rely on Interlocked.CompareExchange, and if the return value is not the same as we found before, the next step of spinning started, otherwise the method returns
- Single reason to get a different value - it was changed in another thread, which is not expected while running on a single-core machine
- TryAdd works in the same fashion

Maybe I missed something here?

**Comment by reyang** [comment]
> * Single reason to get a different value - it was changed in another thread, which is not expected while running on a single-core machine

I'm confused - how does a single core relate to single vs. multiple threads?

**Comment by KonH** [comment]
Thanks for your answer! My assumption was failed there. We can have multiple threads on a single-core machine, of course. So the explanation is wrong and CompareExchange can return different value regardless of core count.

I think we have two options for 'continue' replacement here:
1) Returns false in case of contention (but it breaks method contract?)
2) In the case of TryAdd only we can hard-limit maxSpinCount to 1

Or something else is expected here?

**Comment by reyang** [comment]
Since spin doesn't make sense on a single core, normally what people would do is to yield the thread quorum back to the OS scheduler.

**Comment by KonH** [comment]
I'm trying to implement that here - https://github.com/KonH/opentelemetry-dotnet/commit/9ba8df9457536e8f4ed81fe7b923cb76930b015a (no PR for now, before reaching confidence)
Am I understand you correctly?

Also, trying to make a silly benchmark to observe how it affects performance (sources - https://gist.github.com/KonH/a118fd408257d8c58182eec395b0ad64):
``` ini

BenchmarkDotNet=v0.12.1, OS=macOS Catalina 10.15.7 (19H2) [Darwin 19.6.0]
Intel Core i9-8950HK CPU 2.90GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.100-rc.1.20452.10
  [Host]     : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT
  DefaultJob : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT


```
|          Method | MaxDegreeOfParallelism | WithYields |      Mean |     Error |    StdDev |    Median |
|---------------- |----------------------- |----------- |----------:|----------:|----------:|----------:|
| **TryAddBenchmark** |                      **1** |      **False** |  **74.20 μs** |  **3.714 μs** | **10.353 μs** |  **69.86 μs** |
| **TryAddBenchmark** |                      **1** |       **True** |  **78.26 μs** |  **1.356 μs** |  **3.275 μs** |  **77.42 μs** |
| **TryAddBenchmark** |                      **5** |      **False** | **118.28 μs** | **11.450 μs** | **33.401 μs** | **113.96 μs** |
| **TryAddBenchmark** |                      **5** |       **True** | **128.25 μs** | **10.692 μs** | **30.677 μs** | **119.76 μs** |
| **TryAddBenchmark** |                     **10** |      **False** | **116.35 μs** | **11.112 μs** | **31.161 μs** | **109.25 μs** |
| **TryAddBenchmark** |                     **10** |       **True** | **131.77 μs** | **12.940 μs** | **36.919 μs** | **112.41 μs** |

Not sure about correctness, but it looks like gives a 3-10% performance decrease in some conditions.
To mitigate it, I can add additional initialization code related on [Environment.ProcessorCount](https://docs.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=netcore-3.1), if you like so.

**Comment by reyang** [comment]
> I'm trying to implement that here - [KonH@9ba8df9](https://github.com/KonH/opentelemetry-dotnet/commit/9ba8df9457536e8f4ed81fe7b923cb76930b015a) (no PR for now, before reaching confidence)
> Am I understand you correctly?

Yes, we would like to yield - but only when we're running on a single core machine.
Yield on multi-core machine would give higher throughput (since we're not burning CPU cycles), however it significantly affects the behavior of the target process (e.g. a critical path which expects no Context Switch now suffers).

**Comment by reyang** [comment]
> To mitigate it, I can add additional initialization code related on [Environment.ProcessorCount](https://docs.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=netcore-3.1), if you like so.

Yeah, that's exactly what we want, and we need to do the check efficiently (e.g. ideally not in a loop).

One thing to double click - is `Environment.ProcessorCount` going to change while the process is running or not. IIRC there might be platforms (e.g. NT Server) that allows hot-plug CPU. Probably and overkill at this moment.
One extra thing to consider, the actual consideration is around the available CPU cores from the process's perspective instead of from the kernel perspective. In this case it will be [affinity group](https://en.wikipedia.org/wiki/Processor_affinity).

**Comment by reyang** [comment]
@KonH FYI there is a small benchmark/stress tool which could be helpful - #1086.

**Comment by KonH** [comment]
Thanks for the details!

I add it and made a PR.

> One extra thing to consider, the actual consideration is around the available CPU cores from the process's perspective instead of from the kernel perspective. In this case, it will be [affinity group](https://en.wikipedia.org/wiki/Processor_affinity).

Interesting point. I've started to implement it, but not sure that we need to add complexity for such (rare?) cases.
Difficulties:
- It works on Windows only, where [Process.GetCurrentProcess().ProcessorAffinity](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processoraffinity?view=netcore-3.1) is available
- To detect the platform, one more method is required, handles all Windows-related entries in [Environment.OSVersion.Platform](https://docs.microsoft.com/en-us/dotnet/api/system.platformid?view=netcore-3.1)
- It requires bitwise magic to ensure that value represents more that one core considering maximum core count (such code always hard to maintain)

> @KonH FYI there is a small benchmark/stress tool which could be helpful - #1086.

It produces these Enqueue/s:
- Without yield: 6138814
- With yield: 4118300 (33% drop)

But it's not important considering conditional initialization.

**Comment by martinjt** [comment]
This has been iterated on a fair amount since this ticket has gone stale. So I'm going to close this, and if there is more to be done please reopen it.
