### ISSUE TITLE
Populating incoming  HTTP requests on activity custom properties

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#1177]
# Question

Is there a reason why incoming HTTP requests in ASP.NET and Core are not populated on custom Activity properties (similarly to outgoing http requests 
https://github.com/open-telemetry/opentelemetry-dotnet/blob/32fb7c12f1269147bea1080f04ea4ba489aa0f63/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs#L103

**What are you trying to achieve?**

Provide a processor that populates additional tags based on incoming requests headers.

## Additional Context

Processor may use `HttpContext.Current` (on ASP.NET)  or `IHttpContextAccessor` (on ASP.NET Core), however 
- on ASP.NET is works as long as processor runs syncronously with request (which is safe assumption)
- on ASP.NET Core. it requires registering `HttpContextAccessor`  on app level and complicates set-up.

So, even though my task is achievable without change on OTel, I wanted to hear community thoughts on registering custom properties for requests/responses and making it similar to outgoing requests.

We'll be happy to contribute if there is an agreement on this.

**Comment by cijothomas** [comment]
we do it now:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L105

**Comment by cijothomas** [comment]
will be part of the beta release happening this week.

**Comment by lmolkova** [comment]
Cool! Thanks for the info
