### ISSUE TITLE
ActivitySourceAdapter improvement

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1210]
ActivitySourceAdapter currently expose start and stop only, and internally calls GetSampling (equivalent) inside Start. Instead it must expose GetSampling, Start, Stop separately to aligh with the behaviour of actual ActivitySource. And to prevent issues like the one reported here: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1208

**Comment by reyang** [comment]
nit: imprvoement -> improvement

**Comment by cijothomas** [comment]
The current method/behavior of Start is aligned with ActivitySource, which has StartActivity - which does Sampler invocation, and depending on outcome, OnStart callback is called.
ActivitySourceAdapter exposes Start (which is equivalent of activitySource.StartActivity) - this does Sampler invocation, and invokes OnStart. So there is no need to any change here.
