### ISSUE TITLE
about .net461 OpenTelemetry.Instrumentation.SqlClient 

### ISSUE THREAD

**Issue by SmithSgq** [open-telemetry/opentelemetry-dotnet#1222]
this is my code
-----
  static void Main(string[] args)
        {
            var tracerProvider = Sdk.CreateTracerProviderBuilder()
               .AddHttpClientInstrumentation()
               .AddAspNetInstrumentation()
               .AddSqlClientInstrumentation(options =>
               {
                   options.SetTextCommandContent = true;

               })               
               .AddZipkinExporter(options1 =>
               {
                   options1.ServiceName = "testsql";
                   options1.Endpoint = new Uri("http://********/*******/api/v2/spans");
               })
               .Build();
            //执行sql        
            using (SqlConnection connection = new SqlConnection("server=127.0.0.1;database=demo;uid=sa;pwd=sa123"))
            {           
                try
                {
                   connection.Open(); 

                    var command = connection.CreateCommand();
                    command.CommandType = CommandType.Text;
                    command.CommandText = @"SELECT TOP (1000) [Id]
                        ,[ProjectType]
                        ,[Version]
                        ,[CreateTime]
                        ,[EditTime]
                    FROM VersionConfig";
                    var test = command.ExecuteScalar();
                }
                catch (System.Data.SqlClient.SqlException e)
                {

                    throw e;
                }
            }
            Console.ReadKey();
        }

-----
when   the code go to   “SqlEventSourceListener.netfx.cs“ L86
OnBeginExecute(EventWrittenEventArgs eventData){

Expected payload:
                [0] -> ObjectId
                [1] -> DataSource
                [2] -> Database
                [3] -> CommandText ([3] = CommandType == CommandType.StoredProcedure ? CommandText : string.Empty)
.......
 string commandText = (string)eventData.Payload[3]; 
........
}
commandText is null ..why? 
why? 
why?

**Comment by cijothomas** [comment]
@SmithSgq Thanks for reporting this. What you see is the expected behavior. In .NET Framework, SQLClient doesn't emit the command text. It only has StoredProcedure name. (unless you use Microsoft.Data.SqlClient, instead of System.Data.Sqlclient)

(We need it make it clear ... maybe conditionally have `SetTextCommandContent` only for .netstandard? ... Still need to deal with Microsoft.Data.SqlClient which works in both .net fx and .net core.) - let me comeback to this :)

**Comment by SmithSgq** [comment]
Thank you for your reply

We used azure monitor and application insights, which are products of Microsoft azure.

Azure Monitor： https://azure.microsoft.com/services/monitor/

The open source library address of application insights is  https://github.com/microsoft/ApplicationInsights-dotnet

I still use it system.data.sqlclient Can record SQL statements

So I suggest implementing this function

> @SmithSgq Thanks for reporting this. What you see is the expected behavior. In .NET Framework, SQLClient doesn't emit the command text. It only has StoredProcedure name. (unless you use Microsoft.Data.SqlClient, instead of System.Data.Sqlclient)
> 
> (We need it make it clear ... maybe conditionally have `SetTextCommandContent` only for .netstandard? ... Still need to deal with Microsoft.Data.SqlClient which works in both .net fx and .net core.) - let me comeback to this :)

**Comment by SmithSgq** [comment]
Thank you for your reply

Datadog is a monitoring tool that can monitor SQL. How can I associate with otel? I use two tools to monitor. This makes it more difficult for me to check and compare.

So I'm going to use it in this way. I'm looking forward to the following updates and features in the evening

**Comment by SmithSgq** [comment]
Thank you for your reply

Datadog is a monitoring tool that can monitor SQL. How can I associate with otel? I use two tools to monitor. This makes it more difficult for me to check and compare.

So I'm going to use it in this way. I'm looking forward to the following updates and features in the evening

**Comment by cijothomas** [comment]
@alanwest has made doc changes to clarify the options. This should avoid any confusion now.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.SqlClient#settextcommandcontent

**Comment by cijothomas** [comment]
> Thank you for your reply
> 
> Datadog is a monitoring tool that can monitor SQL. How can I associate with otel? I use two tools to monitor. This makes it more difficult for me to check and compare.
> 
> So I'm going to use it in this way. I'm looking forward to the following updates and features in the evening

Sorry, I cannot comment on Datadog part.
