### ISSUE TITLE
Replace AddTag with SetTag

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1226]
SetTag seems to be the way to go and we probably want to replace all `AddTag` calls in this repo?

https://github.com/open-telemetry/opentelemetry-dotnet/search?q=AddTag&unscoped_q=AddTag

**Comment by eddynaka** [comment]
@reyang , are u going to replace? or should I?

**Comment by reyang** [comment]
Feel free to take it.

**Comment by cijothomas** [comment]
@eddynaka Also check if we are retrieving Activity.Tags. It should be Activity.TagObjects
