### ISSUE TITLE
Release intermediate beta version mid September

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#1229]
This is a request to release an intermediate beta version mid September. Needed for app onboarding that hit the nasty concurrency bug: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1185

App is currently being validated with the MyGet version of the package. Once validation is OK we should be good to go as this was identified as the only blocking issue.

Proposed release date: 9/14/2020

Please comment if there are any concerns. Currently beta scheduled for the end of September.

CC: @humphrieslk

**Comment by cijothomas** [comment]
DiagnostciSource RC1 is expected to release on 9/14. So no objection to doing a release on 9/14 or a day after.

**Comment by SergeyKanzhelev** [comment]
Great. Thank you

**Comment by cijothomas** [comment]
https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/5.0.0-rc.1.20451.14
I can do a release tomorow as RC1 is available now.

**Comment by SergeyKanzhelev** [comment]
> https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/5.0.0-rc.1.20451.14
> I can do a release tomorow as RC1 is available now.

This would be great! Do you need my help?

**Comment by cijothomas** [comment]
pre-req done: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1265

I will do the release, and update the pending releaseing doc PR as well. So next time onwards, any one (maintainers) can do the release.

**Comment by SergeyKanzhelev** [comment]
this is done!!!
