### ISSUE TITLE
Make PropertyFetcher public and place it in OpenTelemetry.Api

### ISSUE THREAD

**Issue by AlexeiScherbakov** [open-telemetry/opentelemetry-dotnet#1231]
1. PropertyFetcher is used as copy-paste in many opentelemetry projects:

- https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/PropertyFetcher.cs
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/PropertyFetcher.cs
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.SqlClient/Implementation/PropertyFetcher.cs

2. It very usefull for other Diagnostics.

I think that it should be public and located in OpenTelemetry.Api assembly. Perhaps it should be placed in the .NET Core framework code?

**Comment by cijothomas** [comment]
We can make it public and move it to https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry/Instrumentation, and have all instrumentation get it from the common place.

**Comment by cijothomas** [comment]
Currently these instrumentations depend on SDK project, instead of the API project, as it has to do some conversion from legacy to new activity, which requires ActivitySourceAdapter, which is in SDK...
