### ISSUE TITLE
Jaeger/Zipkin remote endpoint cache improvements

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#1235]
Zipkin had a remote endpoint cache to reduce allocations:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/465fc093203b309836f0443740c72114e3afe7ed/src/OpenTelemetry.Exporter.Zipkin/Implementation/ZipkinActivityConversionExtensions.cs#L109-L117

Jaeger does not have a cache. @CodeBlanch and I discussed (https://github.com/open-telemetry/opentelemetry-dotnet/pull/1195#discussion_r479502331) making one.

I've also raised a concern regarding the potential for unbounded memory growth of Zipkin's cache: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1168#discussion_r477573287

At a minimum, we should add a cache for Jaeger, but we may also want to consider a cache expiration or size limit for both Jaeger and Zipkin.

**Comment by martinjt** [comment]
Work has been done here, please reopen if you think there is more to be done however, these exporters are being thought about, separately, as candidates to move into contrib.
