### ISSUE TITLE
How to serialize Activity object and store in local storage to prevent data lost

### ISSUE THREAD

**Issue by Goxiaoy** [open-telemetry/opentelemetry-dotnet#1246]
# Question
I want to use opentelemetry in my client side app, and store telemeties in some kind of local storage and then send it to server to import to existing exporter like Jaeger. I have seen relative design in ApplicationInsights. It's really useful when telemetries produced in client side

**Describe your environment.**

.net core 3 console app

**What are you trying to achieve?**

What I am going to implement is  an exporter named `WithLocalStorage`. It owns a local file storage buffer, the activity data will be stored in local file when the next exporter fails to send data to the server. Later when the client is back online, the `WithLocalStorage` will dequeue the data in local storage and queue into the next exporter. 

But then I notice that it's hard to serialize and deserialize current `Activity` object to transfer it to file or network
So I have to create a new class 'ActivitySerializable', which copies the `Activity` data, and then store it into file and send it to server. But it makes hard to reuse existing exporter like Jaeger on the server side again.

- what I want to implement
   client Activity ====> file Activity ====>  server Activity ====>Jaeger 

-  current implemented
   client Activity ====> file ActivitySerializable ====>  server ActivitySerializable  ==X==> server Activity ====>Jaeger 

## Additional Context

Sometimes server side telemetry may need this feature too, for example to prevent data lost when exporter server down

**Comment by cijothomas** [comment]
Improving reliability by making LocalStorage is in the plan and was discussed few times. (Don't think an issue was created to track this). The goal is provide this facility in the Processor itself, so *every* exporter can leverage it.
Agree we need to address the serializability of Activity. (We'll probably need to create something like ExportActivity or similar.)

If you want to contribute this feature, we can have more detailed discussions soon. OR we can discuss this in the next SIG meeting.

**Comment by Goxiaoy** [comment]
So is this a dotnet only issue or open-telemetry spec issue? Cause I can not find any relative  information about LocalStorage in the whole opentelemetry-specification.

BTW
My case is more complicated then just LocalStorage. Because I have to send the temetry data from client side to server side, and deal with some cases to prevent DDOS like attack from clients in different places.  Most of my current implementation is inspired by [ApplicationInsights-dotnet](https://github.com/microsoft/ApplicationInsights-dotnet)

And for the SIG meeting, I am really not good an speaking English and afraid of not attending.
Thank you

**Comment by cijothomas** [comment]
Making this part of spec - not likely this year.
We are trying to address this specific to dotnet only now. Will share more details as we start working on it. 
You can also chat Gitter channel, if you cannot attend sig meeting.

**Comment by AlexeiScherbakov** [comment]
I think this is a reinvention of the wheel because in production environment it must be an Agent feature, not an instrumentation library. Storage must be 1 per container or 1 per physical host. If you look at Jaeger architecture - ideal place for local storage is a Jaeger Agent, not a client library
1. https://www.jaegertracing.io/docs/1.19/architecture/
2. https://www.jaegertracing.io/docs/1.19/performance-tuning/

**Comment by cijothomas** [comment]
> I think this is a reinvention of the wheel because in production environment it must be an Agent feature, not an instrumentation library. Storage must be 1 per container or 1 per physical host. If you look at Jaeger architecture - ideal place for local storage is a Jaeger Agent, not a client library
> 
> 1. https://www.jaegertracing.io/docs/1.19/architecture/
> 2. https://www.jaegertracing.io/docs/1.19/performance-tuning/

Agree it could be better handled in agent, but we need to handle the following scenarios too:
1. Scenarios where running an agent is not possible. (PaaS service like Azure Web Apps, where its not easy to *install* agent)
2. The Agent itself is down due to whatever reason. The SDK has to have some mechanism to store the telemetry until agent comes back.

**Comment by reyang** [comment]
Ping back from #1278

**Comment by cijothomas** [comment]
Closing as we can track this in #1278
