### ISSUE TITLE
Inconsistent SamplingDecision Names

### ISSUE THREAD

**Issue by ejsmith** [open-telemetry/opentelemetry-dotnet#1255]
- `NotRecord`
- `Record`
- `RecordAndSampled`

Seems like we should pick between present tense or past tense and make it consistent. Either `Recorded` / `RecordedAndSampled` or `Record` / `RecordAndSample`.

`NotRecord` doesn't make sense. It's not correct English. Maybe just `Skip` or `DontRecord`. Personally I like just `Skip` better. It's already in an enum so it's always going to be qualified like `SamplingDecision.Skip`.

My vote:
- `SamplingDecision.Skip`
- `SamplingDecision.Record`
- `SamplingDecision.RecordAndSample`

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/SamplingDecision.cs

**Comment by cijothomas** [comment]
The names were borrowed from the spec.
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#sampler
Agree its not consistent.

We should try to change the spec naming as well.

**Comment by ejsmith** [comment]
Ahh, yeah, I was thinking that was probably the case. Seems unlikely that we would get the spec to change, right? Consistency across the implementations/spec is much more important than the individual names.

**Comment by cijothomas** [comment]
Small renamings are likely not controversial and you can try submitting a PR to the spec repo :)

**Comment by cijothomas** [comment]
This is done. Thank @ejsmith for making the fix in the spec itself :)
