### ISSUE TITLE
Add support for Datadog as an exporter

### ISSUE THREAD

**Issue by tylergohl** [open-telemetry/opentelemetry-dotnet#1259]
# Feature Request

Add support for Datadog as an exporter for `opentelemetry-dotnet`

**Is your feature request related to a problem?**

No

**Describe the solution you'd like:**

Be able to select Datadog as an exporter

**Describe alternatives you've considered.**

Only alternative I'm aware of is using the Datadog's native implementation

## Additional Context

N/A

**Comment by cijothomas** [comment]
The general guidance is - this repo will only be hosting exporters for Prometheus/Jaeger/Zipkin/OTLP. Vendor specific exports should live elsewhere.
(We had originally hosted some vendor specific exporters here, but they got moved out to vendors own github repo)

**Comment by tylergohl** [comment]
Thanks!
