### ISSUE TITLE
Make docker tests run on NetCoreApp 2.1

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet#1264]
There are 3 test projects that use docker (search for `dockerfile` in https://github.com/open-telemetry/opentelemetry-dotnet/find/master), all of which only run on NetCoreApp 3.1.

They need to be updated to run tests on NetCoreApp 2.1 as well according to supported .NET versions: https://github.com/open-telemetry/opentelemetry-dotnet#supported-net-versions

**Comment by eddynaka** [comment]
@xiang17 , just to let you know I was trying to do something "automatic" using matrix from GH Actions to inject the dotnet version to docker-compose which would pass to dockerfile.

Tried some stuff using env, env-file, but yet couldn't accomplish. I'm studying and checking if that's possible with docker-compose up option.

**Comment by eddynaka** [comment]
@xiang17 , just to let you know, I found a way to do that with:
- one docker file
- 1 compose
- 2 compose override

With that, if we need to enable it to net5, we should just add another compose override.

**Comment by eddynaka** [comment]
@CodeBlanch @cijothomas , we can close this issue. I forgot go mark the pr that closed this.
