### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by dstoreng** [open-telemetry/opentelemetry-dotnet#1275]
AspNetCoreInstrumentation currently captures query parameters from the request url. 

These often contain sensitive information, should it really be the default?

**Comment by eddynaka** [comment]
@dstoreng , looking at the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes), it's saying that we should save it in the span.

What you can do to avoid that is:
1. create your own processor: https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/docs/trace/extending-the-sdk#processor
2. remove or update the tag from the activity

Let us know what do you think?

**Comment by dstoreng** [comment]
I removed the query by creating a processor, which is fair enough i guess. 

I just feel like this attribute in particular deserves a spot in the instrumentation options which prevented it from being captured in the first place.

**Comment by eddynaka** [comment]
@dstoreng , i'm closing this issue since we have a way to do that.
Let us know if you face any other issue
