### ISSUE TITLE
Record gRPC message events

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#1276]
The OpenTelemetry spec for gRPC has been updated with details about the events captured as messages are messages are sent. See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/rpc.md#events

First step is to figure out how to do this. Currently no diagnostic source method is called or event added to the current activity in [grpc-dotnet](https://github.com/grpc/grpc-dotnet) when a message is sent or received. I suspect support for events will need changes in grpc-dotnet.

Does support for events in opentelemetry-dotnet come from `Activity.Events`? Is it just a matter of adding `Activity.AddEvent` in grpc-dotnet with the appropriate detail?

**Comment by cijothomas** [comment]
> Does support for events in opentelemetry-dotnet come from Activity.Events? Is it just a matter of adding Activity.AddEvent in grpc-dotnet with the appropriate detail? 

Yes. (grpc-dotnet must update to DiagnosticSource version 5.* to leverage Activity.AddEvent though)

**Comment by JamesNK** [comment]
Is there a concern about long running streams that send and receive many messages, and `Activity.Events` acting as a memory leak?

See https://github.com/dotnet/runtime/issues/42347

**Comment by cijothomas** [comment]
closing as no action required in this repo.
