### ISSUE TITLE
gRPC call metadata not added in nested calls

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#1280]
# Bug Report

I have an OpenTelemetry sample that has a client that makes a gRPC call to a service, and the service then calls itself.

The first call is detected as gRPC and gRPC specific metadata is present in Zipkin:

![image](https://user-images.githubusercontent.com/303201/93406403-b10e7200-f8e3-11ea-8242-d087022491de.png)

The nested call is not:

![image](https://user-images.githubusercontent.com/303201/93406419-b9ff4380-f8e3-11ea-8a24-dea6e2bd9e9c.png)

## Symptom

I investigated why and found it is caused by [HttpInListener.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7863cee67a7efc62bb57cd20ceb7351d8757f884/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L81-L103) replacing that activity with a new activity: `ActivityCreatedByHttpInListener`. [Grpc.AspNetCore.Server](https://github.com/grpc/grpc-dotnet/blob/11a7146c9ece6b63bfbb2366db862d9a51dceaf6/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L393-L409) looks for `Microsoft.AspNetCore.Hosting.HttpRequestIn` because that is where gRPC tags should be added, but it is not there.

Why is this happening - there are no comments in HttpInListener.cs about why it is doing what it is doing - and what is the fix here?

## Additional Context

.NET 5 RC1 and OT 0.6.0-beta.1.

**Comment by cijothomas** [comment]
Not closing as we have to validate if the #1286 issue fixes this issue. @alanwest has volunteered to help validation.

**Comment by alanwest** [comment]
I've created a similar set up using the Aggregator example. #1286 appears to have resolved the issue

<img width="1673" alt="Screen Shot 2020-09-17 at 5 32 08 PM" src="https://user-images.githubusercontent.com/3676547/93541653-e0d17000-f90b-11ea-9f58-4a83a866cabd.png">
