### ISSUE TITLE
How to add activities to AspNetCore traces?

### ISSUE THREAD

**Issue by GiorgioG** [open-telemetry/opentelemetry-dotnet#1283]
# Question
After configuring OpenTelemetry for use with ASP.NET Core (3.1), how do I include my own instrumentation of activities/spans/events?  For example, say I have an EmailService and I want to instrument the SendAsync method.  

Here's how I've configured OpenTelemetry in my Startup class:
```csharp      
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOpenTelemetryTracing(
                (builder) =>
                {
                    builder
                        .AddAspNetCoreInstrumentation(options => { })
                        .AddHttpClientInstrumentation(options => { })
                        .AddJaegerExporter(options => { options.ServiceName = "My App"; });
                });
```

**Describe your environment.**
ASP.NET Core 3.1 Web API project

**What are you trying to achieve?**
I would like to add my own instrumentation to the current request's activity/tracer (sorry for the incorrect terminology I'm still trying to wrap my head around this.) I've searched the documentation, experimented with a bunch of things but I'm clearly not using the correct magic incantation to achieve my end goal.  Thanks in advance!

**Comment by cijothomas** [comment]
You can wrap the EmailService.SendAsync inside `using (var activityEmailSend = activitySource.StartActivity(...))`

Check the following example which shows how to generate own Activities.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/examples/Console/TestConsoleExporter.cs#L43-L47

**Comment by GiorgioG** [comment]
Thank you @cijothomas! Sorry for the delayed response I didn't seem to get a notification (or it wound up in my spam folder.)
