### ISSUE TITLE
Connect to port 14250 collector

### ISSUE THREAD

**Issue by phat1234** [open-telemetry/opentelemetry-dotnet#1284]
- Im using 0.6.0-beta.1 to send data to the collector with port 14250. but got something wrong
sample code here:
services.AddOpenTelemetryTracing((builder) => builder
                    .AddHttpClientInstrumentation()
                    .AddAspNetCoreInstrumentation()
                    .AddGrpcClientInstrumentation()
                    .AddOtlpExporter(options =>
                    {
                        options.Endpoint = "18.141.234.27:14250";
                    }));

Somebody plz help me check the code?
Thanks

**Comment by cijothomas** [comment]
Code looks correct. Should have worked.
Can you explain what is the issue you are seeing?

**Comment by phat1234** [comment]
thanks ur reply @cijothomas 
- I'm no idea to trace how it doesn't works. becoz i tried to do on .net frame 4.7.1 and i was working.
that's why i quite sure something wrong with the code.

**Comment by phat1234** [comment]
Mightbe im missing service name there?

**Comment by cijothomas** [comment]
Closing old issues. Please try the newest releases, and reopen if you have issues still.
