### ISSUE TITLE
Attempting to configure ASP.NET Core app with OTel Collector

### ISSUE THREAD

**Issue by ejsmith** [open-telemetry/opentelemetry-dotnet#1287]
# Bug Report

OpenTelemetry 0.6.0-beta.1

I've got the OpenTelementry Collector demo working inside of docker-compose. Now outside of docker I am attempting to get my ASP.NET Core app configured to report traces to the collector. I attempted to use the Jaeger exporter, but it's not working and I don't have any idea how to trouble shoot it. I also configured a console exporter and that is working fine. Do you have any tips for trying to figure out what is going on? Should I be using the opencensus or jaeger receiver? What is the opentelementryprotocol exporter for?

**Comment by ejsmith** [comment]
Seems like maybe this is some sort of issue with being able to report data from outside of docker. The demo emitter's work insider of docker just fine. I tried telling docker-compose to expose the port as UDP for Jaeger, but it still didn't work.

**Comment by cijothomas** [comment]
otlp exporter is to be used if you have OpenTelemetry collector running. (https://github.com/open-telemetry/opentelemetry-collector) Its best to ask troubleshooting guide for collector in that repo.

**Comment by ejsmith** [comment]
In general, I'm just trying to figure out how to troubleshoot this library though. It doesn't seem like there is any feedback on what is happening and whether or not things are working. Maybe I just have a simple config issue, but I can't tell if the library is trying to send data and failing or it thinks it's successful. So I was more looking for troubleshooting information for this specific library first.

**Comment by cijothomas** [comment]
The best option currently: Use perfview and look for OpenTelemetry-* sources.
In future, https://github.com/open-telemetry/opentelemetry-dotnet/issues/1258 this issue should make this more easy.

Please try perfview and see if you see any logs which explains the behavior.

**Comment by mat-rumian** [comment]
@ejsmith I was running OpenTelemetry-Collector in docker and applications outside and for `OTLP exporter` everything was fine. But for TestHttpClient ASP.NET app (the one from examples) with Jaeger exporter it doesn't work. 

Console exporter log:

```
Activity.Id:          00-553d7639f775344ebaf44aa4072cae78-345363249cfaf044-01
Activity.ParentId:    00-553d7639f775344ebaf44aa4072cae78-0000000000000000-00
Activity.DisplayName: incoming request
Activity.Kind:        Client
Activity.StartTime:   2020-10-01T21:49:39.7216890Z
Activity.Duration:    00:00:00.1222098
```

In the ConsoleExporter log there're now resources like `span.name` and `service.instance.id`. Looks like it waits for something or hangs.

@ejsmith Also please remember about expose of the ports in `docker-compose` :)

**Comment by CodeBlanch** [comment]
I was trying to get this working the other day as well. I don't think the OtlpAgent/JaegerReceiver supports the Apache Thrift Compact UDP protocol our JaegerExporter is sending, or it is bugged.

Check out...

https://github.com/open-telemetry/opentelemetry-collector/blob/1e65674799c8a543e1bc216b8e71de24a374991d/receiver/jaegerreceiver/config.go#L38

The definition there is TCP. I think it should actually be a `NetAddr` structure with `Transport = "udp"`:

https://github.com/open-telemetry/opentelemetry-collector/blob/1e65674799c8a543e1bc216b8e71de24a374991d/config/confignet/confignet.go#L22-L33

:shrug:

/cc @bogdandrutu

**Comment by Sebosek** [comment]
Hi,

I had a similar issue, in my case, I've copied Collector configuration from notes to the yaml file, but there were some white spaces a it causes, for some reason, the collector doesn't process incomming OTLp requests.
Check your configuration.

**Comment by cijothomas** [comment]
Closing old inactive issues. Please reopen if the issue is repro-ed in the newest versions.
