### ISSUE TITLE
OpenTelemetry incompatible with EfCore System.Collections.Immutable

### ISSUE THREAD

**Issue by sergeyshaykhullin** [open-telemetry/opentelemetry-dotnet#1292]
# Bug Report

* **OpenTelemetry 0.6.0-beta.1**
* **net5.0**

## Symptom

I can't install **OpenTelemetry** with **Microsoft.EntityFrameworkCore** because of version conflicts

**What is the expected behavior?**
No errors

**What is the actual behavior?**
```
[Notification][Install] Install failed (project: AppAny.Template, package: Npgsql.EntityFrameworkCore.PostgreSQL v5.0.0-rc1)
Package restore failed. Rolling back package changes for 'AppAny.Template'.
Version conflict detected for System.Collections.Immutable. Install/reference System.Collections.Immutable 5.0.0-rc.1.20451.14 directly to project AppAny.Template to resolve this issue. 
 AppAny.Template -> Npgsql.EntityFrameworkCore.PostgreSQL 5.0.0-rc1 -> Microsoft.EntityFrameworkCore 5.0.0-rc.1.20451.13 -> System.Collections.Immutable (>= 5.0.0-rc.1.20451.14) 
 AppAny.Template -> OpenTelemetry 0.6.0-beta.1 -> System.Collections.Immutable (>= 1.4.0 && < 2.0.0).
```

## Reproduce
Install **OpenTelemetry 0.6.0-beta.1** and then install **Microsoft.EntityFrameworkCore 5.0.0-rc.1.20451.13**

## Additional Context

This is because OpenTelemetry depends on System.Collections.Immutable (>= 1.4.0 && < 2.0.0)

**Comment by eddynaka** [comment]
@sergeyshaykhullin , do you have a repro project? I changed locally and added an upper bound. If i open a PR, can you download and test it?

**Comment by sergeyshaykhullin** [comment]
@eddynaka Just add both packages

```xml
<ItemGroup Label="Broken">
  <PackageReference Include="OpenTelemetry" Version="0.6.0-beta.1" />
  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.0-rc1" />
</ItemGroup>
```

**Comment by eddynaka** [comment]
Hi @sergeyshaykhullin , just added and the solution is compiling.

Will enable the PR to be reviewed. After the merge, you can test using the MyGet source.

**Comment by eddynaka** [comment]
@sergeyshaykhullin , the pr got merged. tomorrow the package will be available at myget.
