### ISSUE TITLE
Modify samplers to take ActivityCreationOptions instead of SamplingParameters

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1296]
SamplingParameters are created from ActivityCreationOptions.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/TracerProviderSdk.cs#L219-L227

Proposing to use the ActivityCreationOptions directly in the samplers, to achieve highest performance, considering this is the hot path for trace creation.

**Comment by kevinmckinley** [comment]
@cijothomas 
The TraceProviderSdk can easily pass the ActivityCreationOptions to `sampler.ShouldSample()`.

The ActivitySourceAdapter is trickier. In it's `RunGetRequestedDataOtherSampler(Activity activity)` method, it doesn't have an ActivityCreationOptions object so it is currently creating a SamplingParameters object directly. The readonly struct ActivityCreationOptions can't be instantiated with values. 

Updating ShouldSample() to take in individual parameters would resolve this but obviously breaks the encapsulation of the input parameter.

Suggestions for handling ActivityCreationOptions usage of ShouldSample()?


for ref: https://github.com/open-telemetry/opentelemetry-dotnet/blob/e24dccbe9f392b9d720121b714ebd9e44fd9563b/src/OpenTelemetry/Trace/ActivitySourceAdapter.cs#L157

**Comment by kevinmckinley** [comment]
I was curious what the performance would look like when not creating instances of SamplingParameters so I made a branch where `ShouldSample` accepts parameters for each SamplingParameters property.
I ran test benchmarks (`dotnet run --framework netcoreapp3.1 --configuration Release --filter *TraceBenchmarks*`) before and after. The results varied.

Here is the BEFORE test results using SamplingParameters:
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.630 (2004/?/20H1)
Intel Core i5 CPU 750 2.67GHz (Nehalem), 1 CPU, 4 logical and 4 physical cores
.NET Core SDK=5.0.100
  [Host]     : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT
  DefaultJob : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT


```
```
Run 1
```
|                    Method |        Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------------:|----------:|----------:|-------:|------:|------:|----------:|
|                NoListener |    75.78 ns |  1.555 ns |  1.454 ns |      - |     - |     - |         - |
|    PropagationDataListner | 2,464.27 ns | 49.171 ns | 89.912 ns | 0.1602 |     - |     - |     680 B |
|            AllDataListner | 2,452.78 ns | 48.090 ns | 76.276 ns | 0.1602 |     - |     - |     680 B |
| AllDataAndRecordedListner | 2,483.52 ns | 49.471 ns | 98.799 ns | 0.1602 |     - |     - |     680 B |
|              OneProcessor | 2,593.34 ns | 51.181 ns | 89.639 ns | 0.1602 |     - |     - |     680 B |
|             TwoProcessors | 2,529.52 ns | 49.926 ns | 93.773 ns | 0.1602 |     - |     - |     680 B |
|           ThreeProcessors | 2,543.53 ns | 50.574 ns | 85.879 ns | 0.1602 |     - |     - |     680 B |

```
Run 2
```
|                    Method |        Mean |     Error |     StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------------:|----------:|-----------:|-------:|------:|------:|----------:|
|                NoListener |    60.38 ns |  0.103 ns |   0.091 ns |      - |     - |     - |         - |
|    PropagationDataListner | 1,802.72 ns | 11.010 ns |   9.760 ns | 0.1621 |     - |     - |     680 B |
|            AllDataListner | 1,960.04 ns | 39.044 ns |  53.443 ns | 0.1621 |     - |     - |     680 B |
| AllDataAndRecordedListner | 1,952.37 ns | 36.394 ns |  37.374 ns | 0.1602 |     - |     - |     680 B |
|              OneProcessor | 2,190.29 ns | 43.605 ns |  97.528 ns | 0.1602 |     - |     - |     680 B |
|             TwoProcessors | 2,318.20 ns | 46.153 ns | 111.466 ns | 0.1602 |     - |     - |     680 B |
|           ThreeProcessors | 2,440.13 ns | 48.672 ns | 104.771 ns | 0.1602 |     - |     - |     680 B |

```
Run 3
```
|                    Method |        Mean |     Error |     StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------------:|----------:|-----------:|-------:|------:|------:|----------:|
|                NoListener |    71.70 ns |  1.471 ns |   1.511 ns |      - |     - |     - |         - |
|    PropagationDataListner | 2,287.44 ns | 45.063 ns |  75.290 ns | 0.1602 |     - |     - |     680 B |
|            AllDataListner | 2,383.10 ns | 47.613 ns |  88.254 ns | 0.1602 |     - |     - |     680 B |
| AllDataAndRecordedListner | 2,494.48 ns | 49.660 ns | 118.023 ns | 0.1602 |     - |     - |     680 B |
|              OneProcessor | 2,514.77 ns | 48.679 ns | 121.227 ns | 0.1602 |     - |     - |     680 B |
|             TwoProcessors | 2,581.17 ns | 51.454 ns | 106.261 ns | 0.1602 |     - |     - |     680 B |
|           ThreeProcessors | 2,555.66 ns | 51.128 ns | 111.149 ns | 0.1602 |     - |     - |     680 B |

```
Run 4
```
|                    Method |        Mean |     Error |     StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------------:|----------:|-----------:|-------:|------:|------:|----------:|
|                NoListener |    66.53 ns |  1.315 ns |   1.515 ns |      - |     - |     - |         - |
|    PropagationDataListner | 2,166.35 ns | 43.372 ns | 103.917 ns | 0.1602 |     - |     - |     680 B |
|            AllDataListner | 2,138.01 ns | 27.120 ns |  24.041 ns | 0.1602 |     - |     - |     680 B |
| AllDataAndRecordedListner | 2,205.19 ns | 37.461 ns |  35.041 ns | 0.1602 |     - |     - |     680 B |
|              OneProcessor | 2,308.33 ns | 44.779 ns |  53.306 ns | 0.1602 |     - |     - |     680 B |
|             TwoProcessors | 2,339.47 ns | 35.116 ns |  32.848 ns | 0.1602 |     - |     - |     680 B |
|           ThreeProcessors | 2,399.40 ns | 40.504 ns |  35.905 ns | 0.1602 |     - |     - |     680 B |


Here is the AFTER test results passing each unencapsulated parameter to ShouldSample():
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.630 (2004/?/20H1)
Intel Core i5 CPU 750 2.67GHz (Nehalem), 1 CPU, 4 logical and 4 physical cores
.NET Core SDK=5.0.100
  [Host]     : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT
  DefaultJob : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT


```
```
Run 1
```
|                    Method |        Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------------:|----------:|----------:|-------:|------:|------:|----------:|
|                NoListener |    76.07 ns |  1.575 ns |  3.649 ns |      - |     - |     - |         - |
|    PropagationDataListner | 2,294.54 ns | 45.753 ns | 87.050 ns | 0.1602 |     - |     - |     680 B |
|            AllDataListner | 2,243.71 ns | 40.492 ns | 51.209 ns | 0.1602 |     - |     - |     680 B |
| AllDataAndRecordedListner | 2,552.38 ns | 50.311 ns | 89.427 ns | 0.1602 |     - |     - |     680 B |
|              OneProcessor | 2,482.78 ns | 45.997 ns | 96.013 ns | 0.1602 |     - |     - |     680 B |
|             TwoProcessors | 2,496.44 ns | 45.525 ns | 62.315 ns | 0.1602 |     - |     - |     680 B |
|           ThreeProcessors | 2,457.67 ns | 46.623 ns | 38.932 ns | 0.1602 |     - |     - |     680 B |

```
Run 2
```
|                    Method |        Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------------:|----------:|----------:|-------:|------:|------:|----------:|
|                NoListener |    67.57 ns |  1.367 ns |  2.088 ns |      - |     - |     - |         - |
|    PropagationDataListner | 2,106.96 ns | 41.751 ns | 61.198 ns | 0.1602 |     - |     - |     680 B |
|            AllDataListner | 2,146.04 ns | 41.292 ns | 45.896 ns | 0.1602 |     - |     - |     680 B |
| AllDataAndRecordedListner | 2,216.38 ns | 43.372 ns | 64.918 ns | 0.1602 |     - |     - |     680 B |
|              OneProcessor | 2,368.39 ns | 43.732 ns | 38.767 ns | 0.1602 |     - |     - |     680 B |
|             TwoProcessors | 2,459.77 ns | 48.236 ns | 90.598 ns | 0.1602 |     - |     - |     680 B |
|           ThreeProcessors | 2,451.20 ns | 45.332 ns | 42.404 ns | 0.1602 |     - |     - |     680 B |

```
Run 3
```
|                    Method |        Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------------:|----------:|----------:|-------:|------:|------:|----------:|
|                NoListener |    60.68 ns |  0.283 ns |  0.251 ns |      - |     - |     - |         - |
|    PropagationDataListner | 1,890.62 ns | 21.723 ns | 18.140 ns | 0.1602 |     - |     - |     680 B |
|            AllDataListner | 1,947.96 ns | 22.611 ns | 21.151 ns | 0.1621 |     - |     - |     680 B |
| AllDataAndRecordedListner | 2,001.93 ns | 23.043 ns | 19.242 ns | 0.1602 |     - |     - |     680 B |
|              OneProcessor | 2,197.21 ns | 43.819 ns | 55.417 ns | 0.1602 |     - |     - |     680 B |
|             TwoProcessors | 2,290.76 ns | 39.711 ns | 35.203 ns | 0.1602 |     - |     - |     680 B |
|           ThreeProcessors | 2,267.29 ns | 25.460 ns | 23.815 ns | 0.1602 |     - |     - |     680 B |

```
Run 4
```
|                    Method |        Mean |     Error |     StdDev |      Median |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------------:|----------:|-----------:|------------:|-------:|------:|------:|----------:|
|                NoListener |    75.73 ns |  1.318 ns |   2.202 ns |    75.35 ns |      - |     - |     - |         - |
|    PropagationDataListner | 2,306.84 ns | 45.059 ns |  48.213 ns | 2,303.12 ns | 0.1602 |     - |     - |     680 B |
|            AllDataListner | 2,359.36 ns | 47.293 ns |  50.603 ns | 2,367.32 ns | 0.1602 |     - |     - |     680 B |
| AllDataAndRecordedListner | 2,269.94 ns | 42.848 ns |  40.080 ns | 2,280.62 ns | 0.1602 |     - |     - |     680 B |
|              OneProcessor | 2,482.49 ns | 49.409 ns |  56.899 ns | 2,478.51 ns | 0.1602 |     - |     - |     680 B |
|             TwoProcessors | 2,449.61 ns | 40.508 ns |  37.891 ns | 2,445.02 ns | 0.1602 |     - |     - |     680 B |
|           ThreeProcessors | 2,537.45 ns | 50.444 ns | 122.788 ns | 2,485.03 ns | 0.1602 |     - |     - |     680 B |

**Comment by cijothomas** [comment]
Given we had GA and is now not possible to change public API, closing this issue.
