### ISSUE TITLE
Accept `X-B3-Sampled` header to equal `true`

### ISSUE THREAD

**Issue by christopher-taormina-zocdoc** [open-telemetry/opentelemetry-dotnet#1299]
# Feature Request

Right now when you use the `B3Propagator` for the AspNet/AspNetCore instrumentations, the incoming request needs to set the `X-B3-Sampled` header to `1` for the request to be sampled. As mentioned in the [open zipkin repo](https://github.com/openzipkin/b3-propagation#sampling-state-1) some tracer implementations may have set this header to the value `true` instead of `1`. 

Can the B3Propagator be made to be lenient and accept this value as well? This would put much less burden on anyone moving to the open-telemetry instrumentation when services may have this older implementation.

**Comment by reyang** [comment]
@vishweshbankwar this looks like a good first issue for you.

**Comment by christopher-taormina-zocdoc** [comment]
@reyang just opened a PR for this
