### ISSUE TITLE
Versioning based on GIT history

### ISSUE THREAD

**Issue by enzian** [open-telemetry/opentelemetry-dotnet#130]
Hi, I noticed, that this project uses a `Version.props` file. I have worked with [MinVer](https://github.com/adamralph/minver) for some time now.

With MinVer we could derive versioning info (Maj, Min, Patch + Pre) from tags set in the git history!

If that is something that would make sense here, I'd like to contribute!

**Comment by enzian** [comment]
The functionality has been merged in #131 and I think we should consider this one done, whenever we build and release the next prerelease version that was successfully versioned using MinVer!

Any other/different opinions?

**Comment by SergeyKanzhelev** [comment]
need to delete all the packages with the version 0.1.0 from myget. As packages are now prodiuced with the versioning like `0.0.0-alpha.0.48`.

As for NuGet releases - do we need a way to produce versions without the patch number. Can you add a build definition or a small instruction on how to do it?

**Comment by enzian** [comment]
@SergeyKanzhelev there is no need to delete existing packages, we just need to push tags on the commits that we released and minver will infer the next versions and offsets.

The workflow for a release is quite simple: tag (and sign) the commit you want to release, then make azure devops (or any other CI tool) build the tag. Be sure not to do a shallow fetch, since minver needs the ability to iterate the history in order to find semver tags. Invoking `dotnet pack` will infer the version as well and all that necessary now is to push the package...

Did I get what you were asking for?

**Comment by lmolkova** [comment]
I believe it has been fixed in #131
