### ISSUE TITLE
OpenTelemetry.Instrumentation.StackExchangeRedis seems to have thread racing condition in 0.6.0-beta1

### ISSUE THREAD

**Issue by foresterLV** [open-telemetry/opentelemetry-dotnet#1301]
# Bug Report

OpenTelemetry.Exporter.Jaeger 0.6.0-beta.1
OpenTelemetry.Extensions.Hosting 0.6.0-beta.1
OpenTelemetry.Instrumentation.AspNetCore 0.6.0-beta.1
OpenTelemetry.Instrumentation.Http 0.6.0-beta.1
OpenTelemetry.Instrumentation.StackExchangeRedis 0.6.0.-beta1
System.Diagnostics.DiagnosticSource 5.0.0-rc.1.20451.14
StackExchange.Redis 2.1.58

netcoreapp3.1 running on mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim docker (linux)

## Symptom

After upgrading my test project to OpenTelemetry dot net 0.6.0-beta1 I have noticed random problems (these occur with some probability but not always) with Redis entries in the traces when viewing them in Jaeger. Jaeger reports warnings like "duplicate SpanIds", displays calls in wrong order or sometimes previus activity entries are reported as Redis ones while actual Redis calls occur later. 

Downgrading OpenTelemetry.Instrumentation.StackExchangeRedis to 0.5.0-beta2 seems to remove that problem, or at least makes it much lower probability to occur. I am continueing to monitor tracing entries right now with 0.5.0-beta2.

Application that gets this behavior is using async functions for business logic and Redis async APIs, problem seems to occur when there are multiple async functions running in parallel which do tracing with Redis async calls happening in parallel too. 

**What is the expected behavior?**

Redis entries added by OpenTelemetry.Instrumentation.StackExchangeRedis should not affect trace entries around, generate Jaeger SpanID warnings and trace change ordering.

## Reproduce

It will take some considerable time for me to extract Redis logic out of the application and combine it with some async trace logic so test app is omitted right now (but I could add it later when time allows). Basically I want to add observation as it looks like Redis instrumentation have some kind of racing condition on 0.6.0 when used in async-heavy code which disappears when downgrading it to 0.5.0 (keeping all other components at 0.6.0 level).

**Comment by mberginbh** [comment]
We're also experiencing duplicate span IDs in Jaeger. Some cursory testing indicates the activities are being generated correctly but something in JaegerExporter is causing duplicates. I'm interested to see whether #1262 has fixed this.

**Comment by mberginbh** [comment]
Downgrading to 0.5.0 beta2 fixed this for us too.

**Comment by cijothomas** [comment]
Thanks for reporting this.
This will be investigate and fixed *after* .7 release, which is happening today.

**Comment by eddynaka** [comment]
@mberginbh , can you check if the newest version still contains the issue?

**Comment by mberginbh** [comment]
@eddynaka 0.7 seems to have fixed it - thanks!

**Comment by eddynaka** [comment]
@mberginbh , nice to know! Based on that, we will close this issue!
Thank you!
