### ISSUE TITLE
Constructor with parameters SpanAttributes has missed attributes initialized   

### ISSUE THREAD

**Issue by niksanla2** [open-telemetry/opentelemetry-dotnet#1303]
# Bug Report

*OpenTelemetry 0.6.0-beta.1
*OpenTelemetry.Trace. 0.6.0-beta.1

Runtime version netcoreapp3.1

## Symptom

When I call SpanAttributes  with parameters I get the NullRefException:
```
 var spanAttributes= new SpanAttributes(
                new List<KeyValuePair<string, object>>()
                {
                    new KeyValuePair<string, object>("Span attribute int", 1),
                    new KeyValuePair<string, object>("Span attribute string", "str"),
                });
        }
```

Expected: It shouldn't throw exception

Actual: It does

## Reproduce

Run this code
```
 var spanAttributes= new SpanAttributes(
                new List<KeyValuePair<string, object>>()
                {
                    new KeyValuePair<string, object>("Span attribute int", 1),
                    new KeyValuePair<string, object>("Span attribute string", "str"),
                });
        }
```

## Additional Context

It looks like this code is not called
            `this.Attributes = new ActivityTagsCollection();`

**Comment by eddynaka** [comment]
@niksanla2 , thanks! i will open a PR to solve this issue

**Comment by eddynaka** [comment]
@niksanla2 , we have merged the solution. If you want to test early, you can wait the MyGet package that is publish nightly. Otherwise, wait the next beta version.

**Comment by niksanla2** [comment]
@eddynaka, thx. I will be wait the next beta version
