### ISSUE TITLE
Update Status to meet with the latest specification

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1311]
The OpenTelemetry specification has been changed to reduce the complexity of Span Status https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#status.

Need to take this breaking change and update the https://github.com/open-telemetry/opentelemetry-dotnet/blob/6633dc846e20c72460ae478f86e7225e32110717/src/OpenTelemetry.Api/Trace/Status.cs#L22 file.

**Comment by eddynaka** [comment]
I'll take a look today/tomorrow

**Comment by eddynaka** [comment]
Should we change the `StatusCanonicalCode` as well? https://github.com/open-telemetry/opentelemetry-dotnet/blob/6633dc846e20c72460ae478f86e7225e32110717/src/OpenTelemetry.Api/Trace/StatusCanonicalCode.cs#L26

It contains the same list from the Status.

**Comment by reyang** [comment]
> Should we change the `StatusCanonicalCode` as well?
> 
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/6633dc846e20c72460ae478f86e7225e32110717/src/OpenTelemetry.Api/Trace/StatusCanonicalCode.cs#L26
> 
> It contains the same list from the Status.

Yes.

**Comment by eddynaka** [comment]
> > Should we change the `StatusCanonicalCode` as well?
> > https://github.com/open-telemetry/opentelemetry-dotnet/blob/6633dc846e20c72460ae478f86e7225e32110717/src/OpenTelemetry.Api/Trace/StatusCanonicalCode.cs#L26
> > 
> > It contains the same list from the Status.
> 
> Yes, and we probably can have 1 class instead of two.

I started to look at this and we might have a problem. Grpc uses the `StatusCanonicalCode`. With that, it's mapped to the `Status` itself.
I'm opening a draft PR to get other comments.

**Comment by eddynaka** [comment]
> > Should we change the `StatusCanonicalCode` as well?
> > https://github.com/open-telemetry/opentelemetry-dotnet/blob/6633dc846e20c72460ae478f86e7225e32110717/src/OpenTelemetry.Api/Trace/StatusCanonicalCode.cs#L26
> > 
> > It contains the same list from the Status.
> 
> Yes, and we probably can have 1 class instead of two.

I started to look at this and we might have a problem. Grpc uses the `StatusCanonicalCode`. With that, it's mapped to the `Status` itself.
I'm opening a draft PR to get other comments.

**Comment by eddynaka** [comment]
FYI, opened an issue in the spec: https://github.com/open-telemetry/opentelemetry-specification/issues/1044

Problems: we don't have a current map from the rpc status code to otel status code.

The current mapping in the PR is based on assumptions...
