### ISSUE TITLE
Consistent ArgumentOutOfRangeException message

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1316]
This was brought up in a [PR comment](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1315#discussion_r497176966) by @ThomsonTan.

Currently we don't have a consistent message, here are the options:
1. {VariableName} should be {description of the constraint}.
2. {VariableName} should be {description of the constraint}, the actual value is {ActualValue}.

Please suggest which one you like, or any other options.
Personally I would vote for option 2, and use the following ctor:
```csharp
public ArgumentOutOfRangeException (string paramName, object actualValue, string message);
```

**Comment by TopSwagCode** [comment]
Hi. I wrote gitter and would love to help with this issue :)

**Comment by Austin-Tan** [comment]
Hi @TopSwagCode, @reyang , is there a reason why the PR addressing this was closed? Looks like it follows pretty closely with Reiley's Option number 2 in fixing it, and I could not find any discussion on PR #1369 after approval. Thanks.

**Comment by TopSwagCode** [comment]
> Hi @TopSwagCode, @reyang , is there a reason why the PR addressing this was closed? Looks like it follows pretty closely with Reiley's Option number 2 in fixing it, and I could not find any discussion on PR #1369 after approval. Thanks.

Hi. I wrote on Gitter why I didn't want to go on. I have another branch that was approved, but bot blocked PR. Made new branch and got bot to approve PR. But now I get another reviewer which get issue sidetracked. If messages should end with "." Or not. Error messages not allowed to contain values even though other messages in repo does. 

Ended Up spending several hours om this small fix. I dont feel like that is something for me. There should be started a new issues for unrelated stuff. 

That said feel free to reopen and merge if you want to use the code. I Will look for another project to spend my time on.

**Comment by Austin-Tan** [comment]
Gotcha, thanks for the explanation, I see the Gitter messages now and will take a look. Good luck!
