### ISSUE TITLE
How to publish 3rd party Exporter packages?

### ISSUE THREAD

**Issue by TimothyMothra** [open-telemetry/opentelemetry-dotnet#1336]
Hello Community,
We're ready to publish the first beta of our [Azure Monitor Exporter](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/monitor/OpenTelemetry.Exporter.AzureMonitor).
When trying to publish, we ran into the error that this name is already reserved:

> ##[error]The nuget command failed with exit code(1) and error(Response status code does not indicate success: 409 (This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.).

How do we get access to [this namespace](https://www.nuget.org/packages?q=OpenTelemetry.Exporter)? :)
Is there a formal process we need to follow or does this community intend to allow anyone to publish under the namespace "OpenTelemetry.Exporter.*" ?

- Package Name: "OpenTelemetry.Exporter.AzureMonitor"
- Organization Name: https://www.nuget.org/profiles/azure-sdk

@SergeyKanzhelev, @cijothomas, @reyang, @pakrym

**Comment by reyang** [comment]
Why do we want to publish 3rd party nuget to the OpenTelemetry namespace?
I think Azure Monitor Exporter should publish to Azure SDK namespace.
