### ISSUE TITLE
NullReferenceException in HttpInListener

### ISSUE THREAD

**Issue by twenzel** [open-telemetry/opentelemetry-dotnet#1349]
# Bug Report

OpenTelemetry.Extensions.Hosting" Version="0.6.0-beta.1"
OpenTelemetry.Instrumentation.AspNetCore" Version="0.6.0-beta.1"
OpenTelemetry.Instrumentation.Http" Version="0.6.0-beta.1" 

Runtime version netcoreapp3.1

## Symptom

When calling a site in our Asp.Net core application a NullReferenceException ocurrs within the HttpInListener (see screenshot)
![error_httpInListener](https://user-images.githubusercontent.com/500376/96005349-a4c2f980-0e3c-11eb-96e8-7ba370cbe6b2.png)
)

Callstack:
![image](https://user-images.githubusercontent.com/500376/96006283-9cb78980-0e3d-11eb-975e-015ef5d908a0.png)

Repro project is attached.
[MVCAppWithTracing.zip](https://github.com/open-telemetry/opentelemetry-dotnet/files/5379084/MVCAppWithTracing.zip)

The call is executed without problems, I guess the exception will be catched somewhere.

**Comment by eddynaka** [comment]
Hi @twenzel , thanks for providing the repro. Just created a PR solving the null reference exception!
