### ISSUE TITLE
Is OpenTelemetry supporting W3C Trace Context?

### ISSUE THREAD

**Issue by thangchung** [open-telemetry/opentelemetry-dotnet#135]
We have a little bit concern that if OpenTelemetry is supporting [Trace Context](https://www.w3.org/TR/trace-context/#trace-id) or not? I have searched around in this repository but no clue about Trace Context implemented with standard from W3C. Due to the built-in with Trace Context feature in the next .NET Core 3.0, could you shed the light on Trace Context in OpenTelemetry for us a little bit as well?

/cc @davidfowl @thiennn

**Comment by lmolkova** [comment]
Yes, it does support trace-context. Here is an implementation: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Abstractions/Context/Propagation/TraceContextFormat.cs

Here is how it is used (It will change significantly very soon as .NET Core stack now supports W3C trace-context natively):
- incoming requests: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Collector.AspNetCore/Implementation/HttpInListener.cs#L55

- outgoing requests https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Collector.Dependencies/Implementation/HttpHandlerDiagnosticListener.cs#L59
