### ISSUE TITLE
Release process automation

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1364]
The release process is listed here.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/RELEASING.md
We can automate everything (tag, changelog, release, nuget/myget push) with GHActions including push to nuget. (maintainers can store the nuget token as a secret, similar to how its done for myget).

**Comment by stevejgordon** [comment]
@cijothomas, looking through the current actions, I see that this appears to be in place with an automated workflow. Do you think this issue can be closed?
