### ISSUE TITLE
Reennable CS1591

### ISSUE THREAD

**Issue by enzian** [open-telemetry/opentelemetry-dotnet#137]
In order to treat warnings as errors (#115), it was decided, to disable CS1591 which enforces documentation on all public members of an assembly. (see #131)

This rule should actually be enabled. Since so many APIs do not follow this rule, reenabling it should happen in two steps:

1. Reenable it for `OpenTelemetry` and `OpenTelemetry.Abstractions`
2. Reenable it for all Contrib-Projects.

**Comment by noamarbel** [comment]
Hi, I am new to the project, and would like to start working on this ticket. Some questions:
1. Does it make sense as a starting point?
2. Is the point to enable the warnings, and put comments on all API methods?
3. Do we need meaningful method and params messages, of just placeholders that make sense? How deeply do I need to understand the API to document it?

Would appreciate some guidance.

Thanks.

**Comment by SergeyKanzhelev** [comment]
this issue is a great opportunity to learn the codebase. It might be a bit challenging if PR will be getting too big, but I can prioritize merging of it. Also, you can split it into small chunks.

Please, no placeholders. It will be hard to untangle later.

**Comment by enzian** [comment]
go file by file, commit frequently (at least after every file you touch) and regularly rebase on master to keep eventual merges small!

**Comment by noamarbel** [comment]
Got it. Will start working on it.

Do I need to assign this to myself somehow? Call dibs?

**Comment by SergeyKanzhelev** [comment]
consider it's yours. GH only allows assigning to the members of the org =(

**Comment by cijothomas** [comment]
@noamarbel This is still an open issue- Do you want to work on it?

**Comment by cijothomas** [comment]
@eddynaka If you want to take it!

**Comment by eddynaka** [comment]
I started to enable some parts, but, there are things that i don't know the proper words or the usage...., so it's being hard :(

**Comment by alanwest** [comment]
@eddynaka I'd be happy to be available for brainstorming wording. I may struggle as well, as there are still many aspects of the APIs I'm still learning about, but I'm ok with struggling 😄.

**Comment by eddynaka** [comment]
> @eddynaka I'd be happy to be available for brainstorming wording. I may struggle as well, as there are still many aspects of the APIs I'm still learning about, but I'm ok with struggling 😄.

Nice to know! i will start a PR and mark as week and ping u on gitter, so we can discuss there :)
