### ISSUE TITLE
SpanContext to SpanReference in API

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1377]
See:
https://github.com/open-telemetry/opentelemetry-specification/pull/1075

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/Trace/SpanContext.cs

**Comment by eddynaka** [comment]
@cijothomas , are we just going to rename it or should we do something else?

**Comment by cijothomas** [comment]
Lets start with renaming.

**Comment by eddynaka** [comment]
@cijothomas , they reveretd the change from SpanReference to SpanContext (https://github.com/open-telemetry/opentelemetry-specification/issues/1126). With that in mind, i will close this issue as well.
