### ISSUE TITLE
Extracting Vendor Specific Sources

### ISSUE THREAD

**Issue by enzian** [open-telemetry/opentelemetry-dotnet#138]
I sifted through some of the issues and PRs that introduced Exporters and Collector. I noticed also while cleaning up the code, that the code quality, architecture and general style differ noticeably.

This is why I would like to propose a segregation of 'Contribution/Vendorspecific' collectors and exporters into their own repos. This would have a few advantages:

* it moves the burden of maintenance for vendor specific code from the OpenTelemetry team to the contributors. This also means, that they are free to build their collectors & exporters as they see fit. The OT maintainers on the other hand are free from having to review and maintain code of systems that are foreign to them.
* The lifecycle of vendored components can be independent of the OpenTelemetry repos: The cloud-native world gives birth to many things that die a quick death or are replaced quickly and abandoned. Having this code in the OpenTelemetry repos places the burden of maintaining code on the OT maintainers and thus sticks around for probably far too long if not forever.
* It would decouple the versioning and therefore make the API compatibility guarantees easier to handle: If the OT-dotnet API changes, all vendored libraries have to change simultaneously. This approach does not scale. If there comes the point where we have dozens of vendor specific libraries in the OT-dotnet codebase, changing things becomes harder then it should be. Having Vendored libraries separated would diffuse this issue and afford the maintainers of the vendor-specific libraries more time to adopt API/architectural changes into their codebases and release them.
* there are quite a few smaller benefits but for the sake of brevity...

There are also some Cons, for example the increased complexity of the ecosystem and the user of the libraries. I consider these factors to be outweighed by the Pros since their negative effects can be diffused with good documentation.

Any thoughts?

**Comment by austinlparker** [comment]
FWIW I'm generally in favor of moving everything that isn't the API and SDK out of this repository once it becomes more stable. I think there's slightly more short-term benefits to keeping everything together until we've got at least the API nailed down (which should be happening in the next few months, as the spec finalizes). Once that's happened, though, we should absolutely migrate the exporters and adapters and whatnot out into their own repositories.
