### ISSUE TITLE
Adding more attributes in Http and Sql span

### ISSUE THREAD

**Issue by lupengamzn** [open-telemetry/opentelemetry-dotnet#1382]
**Is your feature request related to a problem?**

AWS X-Ray would need more details from Asp.Net Core & Asp.Net, Http and Sql span to give our customers a better observability to the application. 

**What do you want to happen instead? What is the expected behavior?**

We would like to add support for recording 1)client ip address, http response content length in incoming&outgoing Http span and 2)connection string, user id in Sql span.

We can submit the PR for you to review if this is feasible.

**Comment by cijothomas** [comment]
@lupengamzn `ActivityProcessor` is the recommended way to add any additional attributes to an `Activity`. Most instrumentations also offer `Enrich` to achieve this.

 We don't need to change the existing instrumentations, unless the current instrumentations are not populating **required** fields as per specification conventions https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes

Or were you proposing to make more options to the instrumentation, to populate optional fields as well based on opt-in setting?

**Comment by srprash** [comment]
Hi @cijothomas 
I believe that the `http.client_ip` and `http.response_content_length` are common attributes (not vendor specific) which other vendors too may come to use in the future. Having these tags set as part of the instrumentation itself would avoid the need for a user to add an extra processor (AWS specific processor in this case).

**Comment by cijothomas** [comment]
@srprash Yes. These are both defined in semantic conventions and marked optional . So we can make it part of the instrumentation (with an option to turn on/off)

**Comment by cijothomas** [comment]
Closing, as separate issues exist to make instrumentations updated to latest spec.
