### ISSUE TITLE
Remove ExportComponent from SDK layer

### ISSUE THREAD

**Issue by trwegner** [open-telemetry/opentelemetry-dotnet#139]
ExportComponent is not included in [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification) so should be removed.  This was pointed out in PR [111](https://github.com/open-telemetry/opentelemetry-dotnet/pull/111) comments for issue #18 by @lmolkova on [Tracing.cs](https://github.com/open-telemetry/opentelemetry-dotnet/pull/111/files/26d60453a046e9a8d70a3492aaf672bcb3da4c55#diff-8e4d912aaf6494545836744ced57ab70).

**Comment by lmolkova** [comment]
@trwegner do you think you'll be able to take it over?

**Comment by trwegner** [comment]
Yes, happy to take it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lmolkova** [comment]
Sorry, already removed span stores in #147, they were very annoying :)

**Comment by lmolkova** [comment]
fixed in #139
