### ISSUE TITLE
AddOpenTelemetryTracing should be re-entrant

### ISSUE THREAD

**Issue by tekian** [open-telemetry/opentelemetry-dotnet#1394]
**Is your feature request related to a problem?**

As a service stack developer, I'd like to set up trace pipeline (exporters, samplers, processors, etc.) separately from
adding instrumentation libraries. Service developer should be able to add any instrumentation library he needs based on the workload type, preserving an initial setup of the pipeline. 

Current implementation assumes service developer is able to define full tracing pipeline including instrumentation libraries in one go, making it impossible to define one without defining the other.

Our current workaround is not to use `AddOpenTelemetryTracing` directly but instead, manage Tracer Sdk lifecycle ourselves. 
We examine DI for `IEnumeration<Action<TracerProviderBuilder>>` and apply any such action before `TraceProvider` is built.

**Describe the solution you'd like:**

`AddOpenTelemetryTracing` would realize there is an underlying builder already in a DI, and wouldn't create new one, or it would use DI to pick up all the different instrumentation implementations before it would `Build` tracer provider.

**Comment by cijothomas** [comment]
related issues: https://github.com/open-telemetry/opentelemetry-dotnet/issues/831
https://github.com/open-telemetry/opentelemetry-dotnet/issues/1215

**Comment by cijothomas** [comment]
Can be closed now, as ext.hosting is now stable, and takes care to prevent multiple providers being unintentionally added!
