### ISSUE TITLE
Support resource information via OTEL_RESOURCE_ATTRIBUTES env variable

### ISSUE THREAD

**Issue by srprash** [open-telemetry/opentelemetry-dotnet#1400]
# Feature Request

This feature is required by the OTel [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable)

### Problem

Currently, the only way to specify the service name for the traced application is through `tracerBuilder.SetResource(Resources.CreateServiceResource("MyApp"))`. This would overwrite any other resource set in the tracer.
A customer should be able to specify the service name (and other application-wide attributes) using the OTEL_RESOURCE_ATTRIBUTES environment variable with something like `service.name=MyApp` as the value.

### Proposed solution

Building the tracer provider using a default resource. This default resource can be created from the OTEL_RESOURCE_ATTRIBUTES env var and can also include [`telemetry.sdk`](https://github.com/open-telemetry/opentelemetry-specification/blob/a2758014f408f64ff84728918d671ee3fdab2225/specification/resource/semantic_conventions/README.md#telemetry-sdk) which is also required by the spec.

Ref OTel Java default resource: https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java#L57

**Comment by cijothomas** [comment]
@srprash Are you planning to do a PR for this?
Thanks in advance.,
