### ISSUE TITLE
Zipkin exporter must export Resource as zipkin tags

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1410]
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/zipkin.md#attribute

**Comment by CodeBlanch** [comment]
@cijothomas There's https://github.com/open-telemetry/opentelemetry-dotnet/pull/1385 is there more to be done on this?

**Comment by cijothomas** [comment]
My bad! 
Validated with build from master and looks good!
