### ISSUE TITLE
ISampler.ShouldSample must return a Decision, not a bool

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#144]

**Comment by austinlparker** [comment]
Spec decision is WIP on this.

**Comment by lmolkova** [comment]
@austinlparker, it seems spec has been finalized. Can I remove the `waiting-for-spec` label?

https://github.com/open-telemetry/oteps/blob/master/text/0006-sampling.md
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-sampling.md

From the .NET side: `Decision` must be value type to avoid extra allocation
