### ISSUE TITLE
Dependencies in OpenTelemetry Project

### ISSUE THREAD

**Issue by rymeskar** [open-telemetry/opentelemetry-dotnet#1442]
# Question
Does it make sense to rely on non-abstraction libraries because of [one extension method](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Logs/OpenTelemetryLoggingExtensions.cs)? I believe that without this method, the package could only rely on Microsoft.Extensions.Logging.Abstractions instead of Microsoft.Extensions.Logging.Configuration and Microsoft.Extensions.Logging.

**What are you trying to achieve?**
In complex legacy projects, I have always appreciated when the amount of package dependencies is small.

**Comment by cijothomas** [comment]
Closing this old issue. 
In general, we keep the dependencies to the minimal. 
In case of OTel SDK, it has preferrentially treated ILogger for Logging, and the Ms.Ext.Logging dependency is inevitable.

**Comment by cijothomas** [comment]
I don't think this issue needs reopening. Issue #4126 needs to be solved (or decide to not solve it), separately from this.
