### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1444]
Go through the steps as documented [here](https://docs.google.com/document/d/1rXT2eEAniVM7r8KiikzgJJ-r36shOg_twZP6GPzNvao/edit) and provide feedback.

**Comment by cijothomas** [comment]
@reyang to try this first.

**Comment by luizhlelis** [comment]
I answered and the submitted the form :telescope:. Feel free to consider only what make sense.
[Research doc](https://docs.google.com/document/d/1XSinUhGZ8-WsrrZYCm3vmMzmdHqqLnTOS8frugc6a8Y/edit?usp=sharing)
[GitHub handle](https://github.com/luizhlelis/open-telemetry-dotnet-user-research)

**Comment by martinjt** [comment]
This is obsolete now that we have the GA release.
