### ISSUE TITLE
Define API to create span from the current Activity

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#145]
In auto-collectors Activity is created by the library (HTTP client or web framework or anything else). We need to create Span that represents the same Activity - not create a child of it.

In #140  it looks like this

```csharp
ISpan span = this.Tracer.SpanBuilder(path)
  .SetSpanKind(SpanKind.Server)
  .SetCreateChild(false)
  .StartSpan();
```

`SetCreateChild(false)` does the trick, but does not seem to be good choice. We need to revisit this API and find better name/place We are going to work more on this integration and should have better ideas.

Any ideas are welcome

**Comment by austinlparker** [comment]
What about something that chains off of `Activity`? So you'd have something like `ISpan span = Activity.Current.ToSpan()`, and we can hide the details in there.

**Comment by lmolkova** [comment]
Yeah, the problem is that we still need tracer to participate. The Activity does not know about configured sampler, exporter, config. So this would look like Activity.ToSpan(tracer) or Activity.ToSpan(SpanBuilder).

I wish we made this API accessible through the same builder as anything else.  At the end of the day, this just builds Span from some external context - all other SpanBuilder methods do the same. Only difference it - this is not a parent context.

I guess a lot of issues come from the fact that Span and Activity are parallel concepts that represent the same thing. Which is bad. The next step for me is trying to see how we can avoid it. maybe this naming issue will just go away

**Comment by pcwiese** [comment]
Any progress on this topic? I'm running into an issue building the OpenTracing shim where I **think** I need to know the shim is called from a collector which isn't appropriate for this layer.

The OpenTracing class that is listening for the event "Microsoft.AspNetCore.Hosting.HttpRequestIn.Start" is doing this:

https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/AspNetCore/HostingEventProcessor.cs#L56

```csharp

IScope scope = _tracer.BuildSpan(operationName)
  .AsChildOf(extractedSpanContext)
  .WithTag(Tags.Component, _options.ComponentName)
  .WithTag(Tags.SpanKind, Tags.SpanKindServer)
  .WithTag(Tags.HttpMethod, request.Method)
  .WithTag(Tags.HttpUrl, GetDisplayUrl(request))
  .StartActive();

```

The OpenTelemetry replacement class that listens for the same event is here:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Collector.AspNetCore/Implementation/HttpInListener.cs#L73

**That** class is making use of the SetCreateChild API on the ISpanBuilder.

I just don't have the context (not spancontext) inside the SpanBuilderShim to be able to set that same OpenTelemetry builder option.

**Comment by lmolkova** [comment]
you always have Activity.Current that is 1st class citizen in Microsoft.AspNetCore.Hosting.HttpRequestIn.Start

We are working on defining Span vs Activity relationship with .NET folks. So this is in progress.

My suggestion for OTracing auto-collectors to simply configure similar OTelemetry auto-collectors and never actually run. Unless there is some feature/mismatches in behavior and produced result.

**Comment by pcwiese** [comment]
Are you suggesting that we change opentracing-contrib/csharp-netcore to use the OpenTelemetry collector directly?

**Comment by lmolkova** [comment]
nope, but opentracing shim might be able to know when auto-collectors are started and stard OTelemetry ones instead.

**Comment by pcwiese** [comment]
Does that satisfy the backwards compatibility promise that the shim is supposed to provide? On one hand you have working/tested/battle-hardened OpenTracing sets of collectors. On the other, brand new (and effectively untested collectors) based on OpenTelemetry. Even if it were possible to do that from a generic shim layer, I don't think we should.  This shim would be active for any OpenTracing contrib* package that somebody added. Feels like special casing at the wrong layer to me

**Comment by lmolkova** [comment]
I'm in no position to advise what to do for OTracing for back-compat.  You decide how it's going to work.  I'm only trying to give you options and minimize engineering effort needed for soon-to-be-legacy product to keep working.

**Comment by pcwiese** [comment]
Ok. I think I can put something in place that utilizes Activity.Current. That Activity has an operation name that would tell me which auto collector is trying to start a span, e.g. Microsoft.AspNetCore.Hosting.HttpRequestIn.
