### ISSUE TITLE
SQLClient instrumentation doc is incomplete

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1481]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.SqlClient/README.md
Is missing information about Enrich option. Also need to explicitly note the situations where Enrich is available. (similar to SetTextCommandContent)

**Comment by cijothomas** [comment]
@vishweshbankwar please take this.

**Comment by cijothomas** [comment]
@mbakalov Are you doing this?

**Comment by mbakalov** [comment]
@cijothomas - yes, please assign to me, I will take care!
