### ISSUE TITLE
ActivityTraceId & ActivitySpanId's are limiting for non-hex based IDs

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#1484]
While trying to create a custom Sampler implementation I found [SamplingParameters](https://github.com/open-telemetry/opentelemetry-dotnet/blob/c7429d25c9d6a11d8ed152742ff7efa8c3e350fe/src/OpenTelemetry/Trace/SamplingParameters.cs#L64) use a ActivityTraceId struct for the TraceId property. However, this struct is limited only allowing base16 hex characters and throws an exception if a non-hex character is used.

This is limiting because not all systems will generated pure hexadecimal based trace IDs. This will likely have even further reaching issues as trace propagation will likely fail when receiving a trace ID ActivityTraceId is unable to parse.

Trace and span IDs should always be handled as raw strings to support opaque values and not parsed into the ActivityTraceId / ActivitySpanId. This is likely going to be a significant change as these two classes are deeply embedded with the project. However, without this change, the OpenTelemetry SDK _cannot_ support non-W3C generated trace & span IDs.

Other OpenTelemetry SDKs use strings or byte arrays to represent trace and span IDS:
Java's [SpanBuilder](https://github.com/open-telemetry/opentelemetry-java/blob/f20e72440559002d1693d667cac2e0a732eb4ce4/sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java#L180) uses a String
Go's [TraceId](https://github.com/open-telemetry/opentelemetry-go/blob/e22a48de5a1353fb5450783ca9bb5edf651e9849/trace.go#L54) & [SpanId](https://github.com/open-telemetry/opentelemetry-go/blob/e22a48de5a1353fb5450783ca9bb5edf651e9849/trace.go#L77)'s are []byte

**Comment by reyang** [comment]
`ActivityTraceId` is the equivalent of [`SpanContext.TraceId`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#spancontext).
We are not supposed to support a trace id value that does not fit into W3C TraceContext parent-id.

**Comment by MikeGoldsmith** [comment]
If TraceID and Span ID must conform to the W3C, how would you expect trace propagation to work between process boundaries where the trace Id is generated from a non-W3C compliant process?

I'll raise the issue on the spec repo. Without opaque values, forcing W3C compliant Trace & Span IDs is a severely limiting factor.
