### ISSUE TITLE
GA preparation: Review all components. Sign up to help out!

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#1487]
An effort is underway to closely review all components prior to GA. This issue lists the components that need review, the individual(s) reviewing each component, and links to any issues created during the review.

### We need volunteers!

If there's a component you're not very familiar with, you might be the perfect person to volunteer to review it! **No need to be a developer.** We need people to try their hand learning to use each component by following its documentation.

**Find the docs confusing or find a bug?** Please submit an issue (or better yet a PR!) for any problems you encounter.

We also need developers to closely review the code of each component. Looking for things like remaining TODOs and bugs.

**Please comment on this issue to volunteer to participate.**

Please specify:

1. Which component you would like to review
2. Which of the following item(s) you will review for the component:
    * documentation
    * functionality
    * code

We will place your GitHub handle next to the component you volunteer for and the type(s) of review you will perform.

### API & SDK

- [ ] [OpenTelemetry.Api](../tree/master/src/OpenTelemetry.Api)
    - [ ] Documentation @ank3it
    - [ ] Functionality
    - [ ] Code review
- [ ] [OpenTelemetry](../tree/master/src/OpenTelemetry)
    - [ ] Documentation @ank3it
    - [ ] Functionality
    - [ ] Code review

### Exporters

- [ ] [OpenTelemetry.Exporter.Console](../tree/master/src/OpenTelemetry.Exporter.Console)
    - [ ] Documentation @srprash 
    - [ ] Functionality @srprash 
    - [ ] Code review @srprash 
- [ ] [OpenTelemetry.Exporter.InMemory](../tree/master/src/OpenTelemetry.Exporter.InMemory)
    - [ ] Documentation
    - [ ] Functionality
    - [ ] Code review
- [ ] [OpenTelemetry.Exporter.Jaeger](../tree/master/src/OpenTelemetry.Exporter.Jaeger)
    - [ ] Documentation @kyle-lt
    - [ ] Functionality @kyle-lt
    - [ ] Code review @kyle-lt
- [ ] [OpenTelemetry.Exporter.OpenTelemetryProtocol](../tree/master/src/OpenTelemetry.Exporter.OpenTelemetryProtocol)
    - [ ] Documentation @alanwest
    - [ ] Functionality @alanwest
    - [ ] Code review @alanwest
- [ ] [OpenTelemetry.Exporter.Prometheus](../tree/master/src/OpenTelemetry.Prometheus)
    - [ ] Documentation
    - [ ] Functionality
    - [ ] Code review
- [ ] [OpenTelemetry.Exporter.ZPages](../tree/master/src/OpenTelemetry.ZPages)
    - [ ] Documentation
    - [ ] Functionality
    - [ ] Code review
- [ ] [OpenTelemetry.Exporter.Zipkin](../tree/master/src/OpenTelemetry.Zipkin)
    - [ ] Documentation @kevinmckinley
    - [ ] Functionality
    - [ ] Code review

### Instrumentation

- [ ] [OpenTelemetry.Instrumentation.AspNet](../tree/master/src/OpenTelemetry.Instrumentation.AspNet)
    - [ ] Documentation @alanwest
    - [ ] Functionality @alanwest
    - [ ] Code review @alanwest
- [ ] [OpenTelemetry.Instrumentation.AspNetCore](../tree/master/src/OpenTelemetry.Instrumentation.AspNetCore)
    - [ ] Documentation @kevinmckinley
    - [ ] Functionality
    - [ ] Code review
- [ ] [OpenTelemetry.Instrumentation.GrpcNetClient](../tree/master/src/OpenTelemetry.Instrumentation.GrpcNetClient)
    - [ ] Documentation @xiang17 
    - [ ] Functionality @xiang17 
    - [ ] Code review @xiang17 
- [ ] [OpenTelemetry.Instrumentation.Http](../tree/master/src/OpenTelemetry.Instrumentation.Http)
    - [ ] Documentation @evilpilaf
    - [ ] Functionality @evilpilaf
    - [ ] Code review @evilpilaf
- [ ] [OpenTelemetry.Instrumentation.SqlClient](../tree/master/src/OpenTelemetry.SqlClient)
    - [ ] Documentation @mbakalov
    - [ ] Functionality @mbakalov
    - [ ] Code review @mbakalov
- [ ] [OpenTelemetry.Instrumentation.StackExchangeRedis](../tree/master/src/OpenTelemetry.StackExchangeRedis)
    - [ ] Documentation @evilpilaf (Done)
    - [ ] Functionality @evilpilaf (Done)
    - [ ] Code review @evilpilaf (Done)

### Other

- [ ] [OpenTelemetry.Extensions.Hosting](../tree/master/src/OpenTelemetry.Extensions.Hosting)
    - [ ] Documentation
    - [ ] Functionality
    - [ ] Code review
- [ ] [OpenTelemetry.Shared](../tree/master/src/OpenTelemetry.Shared)
    - [ ] Documentation
    - [ ] Functionality
    - [ ] Code review
- [ ] [OpenTelemetry.Shims.OpenTracing](../tree/master/src/OpenTelemetry.Shims.OpenTracing)
    - [ ] Documentation @alanwest
    - [ ] Functionality @alanwest
    - [ ] Code review @alanwest

**Comment by cijothomas** [comment]
The above includes review of all public APIs (https://github.com/open-telemetry/opentelemetry-dotnet/issues/898) and flag the ones which are not required. And making sure enough APIs are exposed to allow extensibility, as required by the spec.

**Comment by ank3it** [comment]
I can do documentation review for OpenTelemetry.API and OpenTelemetry

**Comment by mbakalov** [comment]
I'll take OpenTelemetry.Instrumentation.SqlClient!

**Comment by kevinmckinley** [comment]
I'll start with docs for OpenTelemetry.Exporter.Zipkin and OpenTelemetry.Instrumentation.AspNetCore

**Comment by evilpilaf** [comment]
I can take any part you'd like me to, I'm up for reviewing documentation and code as well :)

**Comment by cijothomas** [comment]
@evilpilaf Thanks! Can you take OpenTelemetry.Instrumentation.Http, and OpenTelemetry.Instrumentation.RedisClient? Let me know if you are comfortable with something else either

**Comment by evilpilaf** [comment]
> @evilpilaf Thanks! Can you take OpenTelemetry.Instrumentation.Http, and OpenTelemetry.Instrumentation.RedisClient? Let me know if you are comfortable with something else or don't like the above 2 :)

@cijothomas perfect I'll start with those two this weekend

**Comment by srprash** [comment]
I can take up the OpenTelemetry.Exporter.Console to review the docs and the code!

**Comment by cijothomas** [comment]
As discussed in today sig:
We still have many components left - if you are looking to contribute, please sign up. Its okay to have multiple people taking the same component.

For those who signed up already and started filing issues/PRs - thanks! Please post a comment here to let us know you are finished.

**Comment by xiang17** [comment]
I can take the GrpcNetClient, the last one in Instrumentation.

**Comment by evilpilaf** [comment]
Finished reviewing the StackExchangeRedis Instrumentation

**Comment by kyle-lt** [comment]
If you are still looking for volunteers, I'll take OpenTelemetry.Exporter.Jaeger.

**Comment by cijothomas** [comment]
> If you are still looking for volunteers, I'll take OpenTelemetry.Exporter.Jaeger.

Thanks. We haven't GA-ed yet, so thanks for your help!

**Comment by kennethlong** [comment]
Hi, I'm running this live in our on prim, OpenShift environment.  I would be happy to review what ever you guys need.  I will have time over Christmas break!

**Comment by surenderssm** [comment]
Happen to visit this repo while exploring opentelemetry exporter for azure monitor.
Please let me know area which I can start exploring to contribute. Open for code/samples/review/documentation.

**Comment by surenderssm** [comment]
I have created this https://github.com/open-telemetry/opentelemetry-dotnet/issues/1682 , Let me know if this adds value, I will be happy to pick it up.

**Comment by cijothomas** [comment]
> I would be happy to review what ever you guys need. I will have time over Christmas break!

Thanks for volunteering! Sorry we couldn't responde earlier. If you are still up for it, please take OpenTelemetry SDK project https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry

**Comment by cijothomas** [comment]
> Happen to visit this repo while exploring opentelemetry exporter for azure monitor.
> Please let me know area which I can start exploring to contribute. Open for code/samples/review/documentation.

Thanks for offering to help! You could take a look into the OpenTelemetry.API project. 
https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Api

Thanks in advance.

**Comment by kennethlong** [comment]
@cijothomas Ok, I will start on OpenTelemetry SDK project tonight.

**Comment by surenderssm** [comment]
@cijothomas Thank you, I will start on OpenTelemetry.API project.

**Comment by cijothomas** [comment]
> @cijothomas Ok, I will start on OpenTelemetry SDK project tonight. I'll look at Docs, Functionality and Code. I assume we can ignore the Metrics stuff for now? Should we flag code that is missing tests? Also, do you want me to create separate issues for each TODO comment found, or put those all on one ticket?

I missed to reply here.
Yes for ignoring metric code. You can open one combined issue or seaparate.

**Comment by kennethlong** [comment]
> 
> I missed to reply here.
> Yes for ignoring metric code. You can open one combined issue or seaparate.
Got it!  I already made a first pass.  I will start entering tickets later this week.

**Comment by kennethlong** [comment]
Got it!  I made a full pass through last weekend.  I will start entering tickets later this week.

**Comment by cijothomas** [comment]
Thanks everyone who helped with this effort. We are ready to release 1.0 of the following packages
API, SDK, Exporters (Console, InMemory, OTLP, Jaeger, Zipkin).

Closing this issue as 1.0 is about to be released. Please continue to open issues with any components as before. 
Will open a similar issue to address the remaining components alone - namely instrumentation, and hosting packages, which will go 1.0 sometime in the future.
