### ISSUE TITLE
HttpClient instrumentation is not invoked when using Grpc.Net.Client on .NET 5.0

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#1490]
Configure OpenTelemetry with both GrpcNetClient and HttpClient instrumentation:

```csharp
using (Sdk.CreateTracerProviderBuilder()
        .AddGrpcClientInstrumentation()
        .AddHttpClientInstrumentation()
        .Build())
{
    using var channel = GrpcChannel.ForAddress(uri);
    var client = new Greeter.GreeterClient(channel);
    var response = client.SayHello(new HelloRequest());
}
```

When run from a `netcoreapp3.1` application, this code will generate two spans. One for the gRPC call and another for the underlying HTTP call. When run from a `net5.0` application, the code will only generate a span for the gRPC call. That is, the HttpClient instrumentation does not get invoked.

`GrpcChannel` defaults to using `HttpMessageInvoker` instead of `HttpClient` (see  https://github.com/grpc/grpc-dotnet/pull/896). However, this alone is not the root of the issue. It appears that for .NET 5 the way the `HttpMessageInvoker` is instantiated differs from prior versions of .NET https://github.com/grpc/grpc-dotnet/blob/cc7b97f6da723f86d6153f1cd618bc2d223ae082/src/Grpc.Net.Client/GrpcChannel.cs#L107-L109. This difference seems to cause no DiagnosticSource events to be written that the OpenTelemetry HTTP instrumentation relies on.

One way to override this default behavior is to supply an HttpClient instance via `GrpcChannelOptions`. Configuring the `GrpcChannel` in this way will cause both gRPC and HTTP spans to be generated from a `net5.0` application:

```csharp
using var channel = GrpcChannel.ForAddress(uri, new GrpcChannelOptions()
{
    HttpClient = new HttpClient(),
});
```

One affect this has is that OpenTelemetry will not propagate context (e.g., baggage) if HttpClient instrumentation does not get invoked. We may need to figure if we can safely always propagate context from the Grpc.Net.Client instrumentation. Related issue: #1441.

**Comment by martinjt** [comment]
Is this still an issue @alanwest I've not hit this.
