### ISSUE TITLE
Reduce time spans spent in memory

### ISSUE THREAD

**Issue by christopher-taormina-zocdoc** [open-telemetry/opentelemetry-dotnet#1491]
# Question
I have an aspnet core service up with opentelemetry using the aspnetcore instrumentation and a zipkin exporter. It seems that at times it can takes 5 seconds or more before a span is sent to the zipkin endpoint. Is there some setting to reduce this time? We're working on tail-sampling and want to be as sure as possible that all spans of a trace will make it to the collector in time.

**Describe your environment.**
aspnet core

Describe any aspect of your environment relevant to the question.

**What are you trying to achieve?**
Looking for a way to configure how long a span spends in memory.

What did you expect to see?
Some configuration option to the SDK or the exporter to lower the amount of time a span can be in memory.

**Comment by cijothomas** [comment]
If using BatchProcessor, change the default interval from 5 sec to lower value.
Or use SimpleProcessor.

**Comment by christopher-taormina-zocdoc** [comment]
Oh nice I'll add the batch processor into my pipeline. Is one set up by default that the spans currently take 5 seconds?

**Comment by cijothomas** [comment]
Yes. 5 sec is what the spec says to pick as default.

(I'll keep this issue open to document the "how to configure Provider" part, which should have answered your question.)

**Comment by cijothomas** [comment]
Btw - just realized that this is not yet supported. Its a "TODO" in the exporter. Please watch for an update here soon.

**Comment by cijothomas** [comment]
Fixed for zipkin.
