### ISSUE TITLE
[Flacky test] GrpcPropagatesContextWithSuppressInstrumentation

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/opentelemetry-dotnet#1492]
Recently, many pr's started to fail because of this.

This happens sometimes, where the expected output is 8 but, the current count of activities ais 7.

Still couldn't reproduce and for now, we disabled it.

**Comment by cijothomas** [comment]
@alanwest can you help investigate this?

**Comment by alanwest** [comment]
Yes I'm currently looking at this. Will provide update today.
