### ISSUE TITLE
Extract package versions to common place.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1509]
There are many packages required by product/test. We have some of them moved to a central place, but still many are left in individual projects. This issue is to track moving all the versions to a centralized place, so its easy to update when a need arises.
eg: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1506#discussion_r521170961

**Comment by cijothomas** [comment]
@Austin-Tan Please take this

**Comment by Austin-Tan** [comment]
Acknowledged, please assign me. Thanks!

**Comment by Austin-Tan** [comment]
Not totally understanding this issue's relation to the PR and comment @cijothomas linked. Is this issue looking for some sort of central config file that prescribes versions for all the dependent projects?

**Comment by cijothomas** [comment]
The ask is to make sure all package version are maintained in the common.*.props file, instead of directly specifying version in individual .csproj.

**Comment by cijothomas** [comment]
The props file already exists: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/build/Common.props#L26 and most packages are handled this way. We just need to make sure there are no package versions still directly specified in individual project.

**Comment by Austin-Tan** [comment]
PR is up, here are three files that I didn't change but was not sure about:
[Benchmarks.csproj](https://github.com/open-telemetry/opentelemetry-dotnet/blob/2823db731f1a8790c39d39a440b69593fdb67b20/test/Benchmarks/Benchmarks.csproj)
[OpenTelemetry.Instrumentation.HttpTests.csproj](https://github.com/open-telemetry/opentelemetry-dotnet/blob/052ecc44b231b4abb93e0a80b97d2a4344b8620f/test/OpenTelemetry.Instrumentation.Http.Tests/OpenTelemetry.Instrumentation.Http.Tests.csproj)
[OpenTelemetry.Instrumentation.SqlClient.Tests.csproj](https://github.com/open-telemetry/opentelemetry-dotnet/blob/052ecc44b231b4abb93e0a80b97d2a4344b8620f/test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj)
Each of them have the packages being included based on a conditional version of a framework. However, I feel like they are not version-sensitive and it might be worth linking them to the common.props anyway. Thoughts @cijothomas ?
