### ISSUE TITLE
Zipkin Exporter send service.namespace as Zipkin tag

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1511]
As per [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/zipkin.md#service-name), `service.namespace` resource should be sent as a Zipkin tag, and not as service name.

Zipkin exporter currently concats the namespace with service name, and is not sending namespace as a Zipkin tag.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Exporter.Zipkin/ZipkinExporter.cs#L140-L142

**Comment by eddynaka** [comment]
For zipkin, we have two endpoints:
1. localendpoint: the servicename is equal some name that you specified, for example, `Zipkin Exporter`
2. remoteendpoint: the servicename is equal to the url.

If we switch to tags, what should be translated? the `zipkiin exporter` or the url?
And, when we convert to json, we have two properties, local and remote endpoint. Should we remove the servicename from those? If yes, RemoteEndpoint will be blank.
