### ISSUE TITLE
How to create my custom Handler Inherit from ListenerHandler?

### ISSUE THREAD

**Issue by zjfeiye** [open-telemetry/opentelemetry-dotnet#1518]
# Question

**v0.8.0**

in 0.8.0 ListenerHandler made internal.
so, how can i create custom Handler Inherit from ListenerHandler?

i create cutom handler for Orleans , NServiceBus, and some my own projects

thank you

**Comment by cijothomas** [comment]
Please see this: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1437
All those helper classes were made internal. You should be able to write instrumentation without that. Let us know if you need help.
Also see documentation here: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/docs/trace/extending-the-sdk/README.md#instrumentation-library

**Comment by kirillta** [comment]
@cijothomas there are two example instrumentations in the doc: _Redis_ uses custom profiler and _SqlClient_ uses internal `DiagnosticSourceSubscriber`. Could you give me another example? 

Like, if I have an instrumented target library and an an instrumentation library. How can I place tracing logic in the second one if `ActivitySource` must be placed in the first one? I don't see any options without using listener handlers

**Comment by cijothomas** [comment]
Here's the SqlClient (.NET Framework) code: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
It does not use ListenerHandler. Same with Redis.

Not sure why you need another example. Anything in particular which is not clear, I can try to help.

If you have a instrumented library "A", and you are writing instrumentation library for it,then ActivitySource.StartActivity must be in the instrumentation library. How to subscribe to events from "A" - it depends on "A".
SqlClient (.NET Framework) fires EventSource events, which was leveraged.
Redis allows profiler sessions, and it was leveraged.
HttpWebRequest allowed none - so reflection was used to get to it....

**Comment by kirillta** [comment]
> It does not use ListenerHandler

What do you mean? I see it uses [this](https://github.com/open-telemetry/opentelemetry-dotnet/blob/48ea77fd1be2978ccf1857461057dc1be34cf846/src/OpenTelemetry.Instrumentation.SqlClient/SqlClientInstrumentation.cs#L29) internal dependency


> How to subscribe to events from "A" - it depends on "A".

So basically I need put all trace handling in "A" as well? Sounds wrong. 
Excuse me, if the question is naive, I'm not into the tracing topic.

**Comment by cijothomas** [comment]
> So basically I need put all trace handling in "A" as well? Sounds wrong.
I am not sure I understood what this statement means.

**Comment by cijothomas** [comment]
> What do you mean? I see it uses this internal dependency

You are looking at the SqlClient for .NET Core, which uses the internal class. The link I shared above is for SQlClient .Net Framework.

**Comment by kirillta** [comment]
I see, but do you have an example for netcore or net5?

> I am not sure I understood what this statement means.

Previously I had the library "A", which emitted events by `DiagnosticSource` and the library "B", which caught them with `DiagnosticSourceSubscriber`. Now "A" uses `ActivitySource` as it described [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/README.md#instrumenting-a-libraryapplication-with-net-activity-api), but I don't understand how can I catch traces in "B"

**Comment by cijothomas** [comment]
> I see, but do you have an example for netcore or net5?
> 
> > I am not sure I understood what this statement means.
> 
> Previously I had the library "A", which emitted events by `DiagnosticSource` and the library "B", which caught them with `DiagnosticSourceSubscriber`. Now "A" uses `ActivitySource` as it described [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/README.md#instrumenting-a-libraryapplication-with-net-activity-api), but I don't understand how can I catch traces in "B"

I am still confused by this statement -> _"Now "A" uses ActivitySource as it described here"_
If A is already using ActivitySource and emitting activities, then there is no need of writing an instrumentation library.

Please follow the instructions here : https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/docs/trace/extending-the-sdk/README.md#instrumentation-library
If your target library emits events by using DiagnosticSource, then the correct of writing instrumentation library for it is by subscribing to DiagnosticSource Events, and in turn create Activity.StartActivity. This is mentioned in the above doc.

**Comment by kirillta** [comment]
> If A is already using ActivitySource and emitting activities, then there is no need of writing an instrumentation library

I meant, I'm in process of porting. Speaking in terms of this article, I need no hijacking if I use ActivitySource API, I only need to add `AddSource` in "B" with a name of the source. 
Thanks

**Comment by kirillta** [comment]
I'm here since 0.2.0 but documentation still hazy enough
