### ISSUE TITLE
Consider creating one more release prior 1.0.0-RC to include support for .net 5

### ISSUE THREAD

**Issue by techgeek03** [open-telemetry/opentelemetry-dotnet#1520]
# Question

Can we have one more release before the 1.0.0-RC of the SDK that includes the improvements done for support of .net 5 particularly for referenced NuGet packages. Right now the current version `0.8.0-beta` can't use recently released .Net 5 framework NuGet packages such as `Microsoft.Extensions.Hosting.Abstractions` because `0.8.0-beta`  was using variables in this range [2.1.1,5.0) https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/build/Common.props#L28 which is fixed in master now.

**Comment by eddynaka** [comment]
@techgeek03 , based on our milestone calendar (https://github.com/open-telemetry/opentelemetry-dotnet/milestones), we will try to release a new version in the next few days, which will include this changes that you added.

I think, that will work for you, right?

**Comment by techgeek03** [comment]
Yes that would work, thank you! I saw the milestones page but I have missed the release date :) because there are lot of open issues.
