### ISSUE TITLE
REQUEST: New membership for utpilla

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet#1532]
### GitHub Username
@utpilla 

### Organization you are requesting membership in
@open-telemetry/opentelemetry-dotnet

### Requirements
- [x]  I have reviewed the community membership guidelines (https://github.com/open-telemetry/community/blob/master/community-membership.md)
- [x]  I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the Gitter channel
- [x]  I am actively contributing to 1 or more OpenTelemetry subprojects
- [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cijothomas 
- @alanwest 

### List of contributions to the OpenTelemetry project

- PRs authored
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/1389 Removed Activity.ParentId from the example output
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/1411 Update OpenTelemetry.API README.md to add Initial Tags using AcitivtyTagsCollection
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/1438 Extend ConsoleExporter to add support for Logs
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/1452 Add extension method to add ConsoleExporter for logs
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/1489 Implement TracerProvider Shutdown
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/1504 Added Exporter type to Zipkin exporter options
  - https://github.com/open-telemetry/opentelemetry-dotnet/pull/1514 Update AddInMemoryExporter extension method signature

- Issues responded to
  - https://github.com/open-telemetry/opentelemetry-dotnet/issues/1373 Generalize ConsoleExporter
  - https://github.com/open-telemetry/opentelemetry-dotnet/issues/1451 implement TracerProvider shutdown 
  - https://github.com/open-telemetry/opentelemetry-dotnet/issues/1493 ZipkinExporter to expose settings to control ExportingProcessor
  - https://github.com/open-telemetry/opentelemetry-dotnet/issues/1505 Ensure that TracerProviderSdk ActivityListener.Dispose is not call multiple times

- SIG projects I am involved with
  - https://github.com/open-telemetry/opentelemetry-dotnet

**Comment by alanwest** [comment]
Hey @utpilla, welcome! You actually want to open this issue in https://github.com/open-telemetry/community.

**Comment by cijothomas** [comment]
Please open in the community repo.
