### ISSUE TITLE
Allow filtering HTTP auto instrumentation request errors

### ISSUE THREAD

**Issue by tiagonapoli** [open-telemetry/opentelemetry-dotnet#1535]
# Feature Request

**Is your feature request related to a problem?**

We're using HTTP auto instrumentation in our applications and we would like to be able to change some "false" errors in order to get a better visualization on the UI, for example: A request to AWS/S3 to get a file which returns a 404, most of the time this is used by us to check if the file exists (it's not an error per se, in this context).

I think this subject is controversial, but I would like to know the contributors opinion on that. My company has just started to instrument applications with distributed tracing so it would be nice to know if others had problems like this as well in their instrumentation, opinions on the matter and any workarounds.

**Describe the solution you'd like:**

Maybe the HTTP auto instrumentation initialization could have a parameter just like the `Filter` one, which will be called to decide whether a finished HTTP activity should be tagged with `Status.Ok` or `Status.Error`.

Which alternative solutions or features have you considered?

We tried to `.SetStatus(Status.Ok)` using the `Enrich` feature - It didn't work though. As a workaround we enriched the activity with an `error=false` attribute (on our specific tracing backend this worked, but it seems to be a unreliable workaround).

**Comment by cijothomas** [comment]
You shouldn't have to do any workaround. Enrich should have worked. Or write custom processor should have worked as well. If they are not working as expected, then its a bug.

**Comment by eddynaka** [comment]
@tiagonapoli , when you used the `Enrich`, did you filter by a method or you are setting Ok every time it triggers?

**Comment by cijothomas** [comment]
I think there is a bug in Enrich. The order is incorrect - we are now calling Enrich, and then SetStatus, so any SetStatus done in Enrich will be overridden.

@tiagonapoli Wait for us to fix this bug, and you should be able to set status using Enrich or Processor without any issues. Allowing end users ability to override any Activity property, including Status is a *key* requirement, so this will be a p1 bug.

**Comment by tiagonapoli** [comment]
@eddynaka Sorry for the delay. It seems @cijothomas already found what the issue was, but just for the record the enrich used was:
```cs
(activity, eventName, rawObject) =>
{
    if (eventName.Equals("OnStartActivity"))
    {
        if (rawObject is HttpRequestMessage request)
        {
            if(request.Content.Headers.ContentLength != null)
            {
                activity.SetTag("http.content_length", request.Content.Headers.ContentLength);
            }
        }
    }
    else if (eventName.Equals("OnStopActivity"))
    {
        if (rawObject is HttpResponseMessage response)
        {
            // ...
            if (response.RequestMessage.RequestUri.Host.EndsWith("s3.amazonaws.com", StringComparison.OrdinalIgnoreCase) &&
                response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                activity.SetStatus(OpenTelemetry.Trace.Status.Ok);
            }
        }
    }
};
```

**Comment by cijothomas** [comment]
Fix for AspNet: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1537
HttpClient is coming next.

**Comment by eddynaka** [comment]
@cijothomas , just created a PR solving the remaining ones
