### ISSUE TITLE
Allow customization of Otlp exporter

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1542]
Similar to https://github.com/open-telemetry/opentelemetry-dotnet/issues/1493

**Comment by cijothomas** [comment]
@Austin-Tan

**Comment by cijothomas** [comment]
@Austin-Tan can you confirm if this was done?

**Comment by Austin-Tan** [comment]
Looks like it was done and merged in #1587 . We had a duplicate issue open as #1494  which is why I didn't see this one.

**Comment by cijothomas** [comment]
Thanks! Closing this one.
