### ISSUE TITLE
Create unit tests for Enrich calls

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/opentelemetry-dotnet#1549]
After the merge of this PR: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1548

We should create more unit tests just like https://github.com/open-telemetry/opentelemetry-dotnet/pull/1537 to validate the full behavior.

**Comment by Austin-Tan** [comment]
The hyperlinks link directly to the location in tests where we currently have calls to ActivityEnrichment
- [SQL Library](https://github.com/open-telemetry/opentelemetry-dotnet/blob/a25741030f05c60c85be102ce7c33f3899290d49/test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs#L390): Tests have a check within the passed Enrich delegate to assert that the correct Command is passed, but no checks exist to actually assert that Enrich is called or that it affects the activity correctly (or that it overrides, as per #1548).
- [ASP .NET Core Library](https://github.com/open-telemetry/opentelemetry-dotnet/blob/a25741030f05c60c85be102ce7c33f3899290d49/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs#L595): Same as above, although the Enrich delegate has switches for both OnStart and OnStop cases. We could verify that the correct one is called, in addition to the propsed SQL verifications of checking that it overrides.
- [GRPC Library](https://github.com/open-telemetry/opentelemetry-dotnet/blob/a25741030f05c60c85be102ce7c33f3899290d49/test/OpenTelemetry.Instrumentation.Grpc.Tests/GrpcTests.client.cs#L445): Identical to ASP .NET Core instrumentation.
- HTTP Library, [Enrich delegate within HttpClientInstrumentationOptions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/12da9a05b5e216a999fc9eb28e388202ea9b5618/src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentationOptions.cs#L53): Not mentioned in tests at all

In each case, I think having a test SetTag("Override", "OverrideValue") and then having the Enrich call override that tag by writing ("Override", "NewValue") and then asserting the existence of that tag would be a straightforward resolution. I'll get to work on that @eddynaka if you think that's worthwhile.
