### ISSUE TITLE
StackExchange.Redis instrumentation not working when using ConfigureServices(IServiceCollection services)

### ISSUE THREAD

**Issue by matthughes404** [open-telemetry/opentelemetry-dotnet#1554]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

* OpenTelemetry 0.8.0-beta.1
* OpenTelemetry.Exporter.Console 0.8.0-beta.1
* OpenTelemetry.Extensions.Hosting 0.8.0-beta.1
* OpenTelemetry.Instrumentation.AspNetCore 0.8.0-beta.1
* OpenTelemetry.Instrumentation.Http 0.8.0-beta.1
* OpenTelemetry.Instrumentation.StackExchangeRedis 0.8.0-beta.1

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc. You can find this information from the `*.csproj` file):

* netcoreapp3.1

## Symptom

When setting up StackExchange.Redis telemetry in `ConfigureServices(IServiceCollection services)`, telemetry messages are not created for the StackExchange.Redis calls.

What did you expect to see?

When calling an API route that contains Redis logic, I expected to see StackExchange.Redis telemetry messages in the console output. 

What did you see instead?

No StackExchange.Redis telemetry messages are written to the console output. 
A different route using the Http instrumentation writes System.Net.HttpClient telemetry to the console, so there seems to be a bug in the StackExchange.Redis instrumentation. 

## Reproduce

https://github.com/matthughes404/opentelemetry-redis-testing

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

I first identified this problem testing out [Lightstep](https://opentelemetry.lightstep.com/csharp/setup-and-installation/), when I did not see the Redis traces show up in their UI. The AspNetCore traces showed up fine in Lightstep, however. To make sure that Lightstep was not the cause, I built a local-only project to reproduce the problem.

**Comment by austinlparker** [comment]
I don't think this is a bug, but maybe the documentation is unclear. In your repro case, you're getting a new connection multiplexer in your controller. The Redis instrumentation binds itself to the connection pool that you pass to it, so if you change your `ConfigureServices` to look like this...

```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            var connection = ConnectionMultiplexer.Connect("localhost:6379");
            services.AddSingleton<IConnectionMultiplexer>(connection);

            services.AddOpenTelemetryTracing(builder => builder
                .AddAspNetCoreInstrumentation()
                .AddHttpClientInstrumentation()
                .AddRedisInstrumentation(connection, opt => opt.FlushInterval = TimeSpan.FromSeconds(1))
                .AddConsoleExporter());
        }
```

And your RedisController to look like this...

```
public class RedisController : ControllerBase
    {
        private readonly ILogger<RedisController> _logger;
        private readonly IConnectionMultiplexer _connectionMultiplexer;

        public RedisController(ILogger<RedisController> logger, IConnectionMultiplexer multiplexer)
        {
            _logger = logger;
            _connectionMultiplexer = multiplexer;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var redis = _connectionMultiplexer.GetDatabase();

            var msg = redis.StringGet("testKey01");
            _logger.LogInformation(msg);

            return Ok(msg.ToString());
        }
    }
```

You should see Redis spans in the Console output.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/1638 made a small doc fix to hopefully clarify this.

**Comment by matthughes404** [comment]
Thanks a lot... this worked!
