### ISSUE TITLE
AspNet,AspNetCore should extractparent context even when Filter is applied

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1564]
Similar to: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1561

Irrespective of a filter being applied, Asp.Net/Asp.Net Core instrumentation must still extract the propagation context and set to current Activity, Baggage.

**Comment by utpilla** [comment]
Added unit tests for both AspNet and AspNet Core instrumentation to ensure this behavior:

**ASP .NET**

- https://github.com/open-telemetry/opentelemetry-dotnet/blob/efe2d96c3c46449310cb8a3c698f84131b101aee/test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs#L344

- https://github.com/open-telemetry/opentelemetry-dotnet/blob/efe2d96c3c46449310cb8a3c698f84131b101aee/test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs#L389

**ASP.NET Core**
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/efe2d96c3c46449310cb8a3c698f84131b101aee/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs#L401

- https://github.com/open-telemetry/opentelemetry-dotnet/blob/efe2d96c3c46449310cb8a3c698f84131b101aee/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs#L459

**Comment by cijothomas** [comment]
Closed as this is completed by @utpilla
