### ISSUE TITLE
Introduce FilteringProcessor

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1578]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/1559 shows how a user can write their own FilteringProcessor. It has the following limitations:
1. Requires Exporter to expose public constructor, which require additional document to warn customers of the potential side effects of using the same Exporter instance in multiple providers.
2. As seen in the PR, its non-trivial to write Filtering processor.

Considering the fact that Filtering will be a common scenario, proposing to introduce a standard FilteringProcessor which can filter out any activities. (https://github.com/open-telemetry/opentelemetry-dotnet/pull/1559#discussion_r524907251)

**Comment by cijothomas** [comment]
Removing from 1.1 milestone, to see if this would come from spec in the future.

**Comment by martinjt** [comment]
It doesn't look like we're planning on doing this as a public change so I'm closing this as Not Planned.
