### ISSUE TITLE
Perf improvements for LogRecord

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#1582]
LogRecord is implemented as a class (allocated on the GC heap) instead of a struct (allocated on the stack).
This avoids copy for batch exporting scenario, and also helps on getting a better alignment with tracing part (where Activity is a class) which simplifies the code. However it could potentially punish perf for non-batch scenario (e.g. piping logs to ETW or LTTng).

One possible solution is to have a pre-allocated collection of LogRecord objects, and keep using them. This could be done either using thread local storage or a global collection (array or something else).

**Comment by ndrwrbgs** [comment]
In performance profiles today I notice similar concern for `AnyValue` and `Span` - the grpc types. Unfortunately I don't see a way in protobuf to use the .proto files to generate C# structs, and I worry about the complexity added if we try to utilize some of the existing `Return` calls to pool objects or arrays.

Is there any goal or effort under which such concerns about GC would be best compiled and invested in? I think some of the fixes may be rather large so warrant planning discussion.
