### ISSUE TITLE
Status - doc fix

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1588]
This PR https://github.com/open-telemetry/opentelemetry-dotnet/pull/1579 updates Status to match the spec. This doc (https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/README.md#setting-status) is out-of-date. Need to update the doc to match the changes above.

**Comment by cijothomas** [comment]
@Austin-Tan please take this.

**Comment by Austin-Tan** [comment]
Looking into this, please assign me! RC2 is expected Monday?
