### ISSUE TITLE
Self-diagnostics write a single line to top of file

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1589]
When self-diagnostics is enabled for a particular level, the .log file will be empty until 1st log entry is captured. This may confuse users, who won't know if the setting got picked up or not.

Could we write an 1 line entry to the top of the file when self-diagnostic module detects config?

**Comment by cijothomas** [comment]
@xiang17

**Comment by xiang17** [comment]
Sounds good. I'll take this.
