### ISSUE TITLE
SqlClient instrumentation doesn't work for Microsoft.Data.SqlClient under .NET Framework

### ISSUE THREAD

**Issue by mbakalov** [open-telemetry/opentelemetry-dotnet#1597]
Using latest opentelemetry-dotnet, target net461 and use Microsoft.Data.SqlClient nuget package.

SQL activities are not captured.

*EDIT*: when submitting this issue I first incorrectly assumed the netfx Sql instrumentation relied on DiagnosticSource events, but that is not the case.

`Microsoft.Data.SqlClient` on netfx uses the `WriteBeginExecuteEvent`/`WriteEndExecuteEvent` methods that operate on the `EventSource`, similar to the `System.Data.SqlClient` on netfx.

The reason our instrumentation doesn't pick it up is because in `Microsoft.Data.SqlClient` this event source is named "Microsoft.Data.SqlClient.EventSource", but the instrumentation only listens to the "Microsoft-AdoNet-SystemData".

Note that we have [tests](https://github.com/open-telemetry/opentelemetry-dotnet/blob/5066600110b0c312cd6c9c75f8afa43252f4fba7/test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs#L77) for `Microsoft.Data.SqlClient` and when running against a docker instance of SQL Server on net461 they do actually fail.

cc @CodeBlanch

**Comment by mbakalov** [comment]
Ah, looks like this is because the EventSource was actually renamed in `Microsoft.Data.SqlClient`, which was done in https://github.com/dotnet/SqlClient/pull/399

So now it makes sense at least, means we need to support both EventSources.

**Comment by CodeBlanch** [comment]
Thanks @mbakalov! I have noticed the net461 tests failing recently but haven't had a chance to look into it. Are you going to submit a PR?

**Comment by mbakalov** [comment]
@CodeBlanch  - yes, will try to do it tomorrow am!
