### ISSUE TITLE
Remove MessageEvent and make Event extensible

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#16]
https://github.com/open-telemetry/opentelemetry-java/pull/81

**Comment by trwegner** [comment]
Also check out open-telemetry/opentelemetry-java#13 and open-telemetry/opentelemetry-java#141

**Comment by trwegner** [comment]
Working on this

**Comment by trwegner** [comment]
Addressed by PR #38
