### ISSUE TITLE
ResourceBuilder Attribute Value is lost when using int value

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [open-telemetry/opentelemetry-dotnet#1606]
# Bug Report

```xml
      <PackageReference Include="OpenTelemetry.Api" Version="1.0.0-rc1.1" />
      <PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.0.0-rc1.1" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc1.1" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc1.1" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc1.1" />
```

* Runtime version: `netcoreapp3.1`

## Symptom

When adding Attributes to `ResourceBuilder`, `AddAttributes` accepts `IEnumerable<KeyValuePair<string, object>>`.
**However, when adding a tag with value as `int`, the value is discarded / `null` in jaeger.**
When using a `string` or calling `ToString()` the value is used.

**What is the expected behavior?**

Since the parameter is of type `object` the int value should work.

**What is the actual behavior?**

The integer value is lost.

## Reproduce

```csharp
BackendServiceResource = ResourceBuilder.CreateDefault()
	.AddService(serviceName:ServiceName, serviceInstanceId:ServiceInstanceId, serviceNamespace:ServiceNamespace, serviceVersion:ServiceVersion)
	.AddAttributes(new []
	{
		new KeyValuePair<string, object>("my.foobar1", 1), // will get lost
		new KeyValuePair<string, object>("my.foobar2", "2"),
		new KeyValuePair<string, object>("my.foobar3", 3.ToString()),
	});

// ...

builder.SetResourceBuilder(BackendServiceResource)
//...
```

Result in jaeger `1.21.0`:

![grafik](https://user-images.githubusercontent.com/33002073/99907112-3bf05c00-2cdb-11eb-8357-30e1f0fae334.png)

**Comment by cijothomas** [comment]
Thanks @Mario-Hofstaetter for reporting.
The attributes are currently only supporting bool, long, double, string. We need to make it same as the Tags in activity. I'll make a bug fix.
