### ISSUE TITLE
Do not label packages v1.0

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-dotnet#1610]
The is @tedsuo from the governance committee.

We have not finished defining versioning concepts, but one major agreement is that nothing will be released as v1.0 until the specification reaches v1.0. 

The latest release v1.0.0-rc1 violates this agreement. Please immediately roll back this release, and relabel it v0.9. 

Please have representatives attend the Maintainer meeting. The .NET SIG is invited to participate in defining the version and support guarantees for OpenTelemetry. But you are not allowed to invent your own versioning scheme or announce a v1.0 separate from the rest of the project.

Thank you.
-Ted

**Comment by tedsuo** [comment]
@cijothomas @reyang @MikeGoldsmith @CodeBlanch @SergeyKanzhelev

**Comment by reyang** [comment]
@tedsuo I was in the maintainers meeting representing C++ (I'm not a maintainer for C#) but happy to help here.

I might be confused here - the .NET way of saying something is close to `1.0.0` is `1.0.0-rc1` (`1.0.0-rc1` < `1.0.0`), which is based on the freeze version of the API spec.

Which agreement were you specifically referring to?

**Comment by tedsuo** [comment]
Thank you for your quick response. I am not worried about a release candidate on its own, I am asking that we finish defining what v1.0 means before labeling anything related to that term. Currently, terms like "GA" and "v1.0" are not defined in concrete enough terms, so it is risky. What if, over the next two weeks, v1.0 comes to mean something different? 

To clarify: a freeze is a backlog action, it means that new feature requests will be not processed at this time. The current definition of v1.0 and "GA" has actually been the completion of both tracing and metrics. So a v1.0-rc1 would be impossible right now, under that current definition. Hence my surprise. :)

I actually would prefer a definition that allows us to release a tracing-only v1.0, as the metrics work is on a slightly longer timeline. But the sooner we create a v1.0, the sooner we need to clarify what support and compatibility guarantees actually come with that. 

The [current draft](https://docs.google.com/document/d/1QHlPsMqwrBm7-IIPef9czuM8KFiLbEDMzGhPrmHcppA/edit#) was proposed this morning and is open to suggestion. We welcome your input and experience. The next step will be an OTEP to make it official.

In the meantime, please kindly hold up on the v1.0 bit.

**Comment by reyang** [comment]
Thanks for the explanation.

Totally agree that "GA" and "v1.0" have to be clearly defined across the board, and we should hold up on the 1.0 GA release until we have a clear definition in the spec.
