### ISSUE TITLE
AddOtlpExporter seems to be causing a crash?

### ISSUE THREAD

**Issue by atrauzzi** [open-telemetry/opentelemetry-dotnet#1616]
# Bug Report

```
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc1.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc1.1" />
        <PackageReference Include="OpenTelemetry" Version="1.0.0-rc1.1" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.0.0-rc1.1" />
```

Running on `net5.0`

## Symptom

It seems like when I use the following in my ASP.net Core project:

```csharp
            services.AddOpenTelemetryTracing((builder) =>
            {
                builder
                    .AddSource(projectName)
                    .SetSampler(new AlwaysOnSampler())
                    .AddAspNetCoreInstrumentation()
                    .AddOtlpExporter();
            });
```

I get a segfault with the message: `Process finished with exit code 139.`

Note: If I remove `AddOtlpExporter()` everything boots fine.

**What is the expected behavior?**
Normal application bootup.

**What is the actual behavior?**
The segfault.

**Comment by cijothomas** [comment]
Can you share the runtime information as well? which OS, whether collector was running etc. I couldn't repo in my windows environment. I *did not* have OT Collector running, so exporter keeps hitting exception, but its handled, and no app crash..

**Comment by atrauzzi** [comment]
Running on linux, collector is running as a container: 

```
telemetry          /otelcontribcol --config=/ ...   Up      55679/tcp, 0.0.0.0:55680->55680/tcp, 0.0.0.0:9411->9411/tcp
```

I've had this working prior to upgrading to the latest RC version.

**Comment by cijothomas** [comment]
Ok i couldn't repro in windows.
Will try Linux.

**Comment by atrauzzi** [comment]
Sounds good, thanks for looking into it.  Also, I'm running on Ubuntu using the latest snap package.

I'm trying to think of any other variances, but this is happening so early in the application boot and without any way of debugging it as the app just crashes out... :sweat_smile:

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs#L49 - There is no try..catch. We can try to catch the exception and see if it helps?

**Comment by atrauzzi** [comment]
If there was an exception, wouldn't I be seeing it instead of a hard-crash?

**Comment by cijothomas** [comment]
mm. Let me try if this is repro ing. and suggest next steps.

**Comment by cijothomas** [comment]
> If there was an exception, wouldn't I be seeing it instead of a hard-crash?

Right. it shouldn't have crashed.

**Comment by edubsi** [comment]
Sadly we just ran into the same problem. Added unhandled Task & App Exception Handling to maybe catch & log the exceptions which did not help.
For us it looks like the crash happens when the first trace/log/metric is exported.

**Comment by edubsi** [comment]
Could it be these lines? All other Exporters (Zipkin, Jaeger ...) catch the general Exception and not an specific one 
https://github.com/open-telemetry/opentelemetry-dotnet/blob/0e3081731a32ed13baf0b1114ac7a85318292d4e/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter.cs#L78-L91
and ensure that no Exception is thrown in the new Exporter Thread
https://github.com/open-telemetry/opentelemetry-dotnet/blob/b247b3d70e8059fb1f661a941ac056085740822a/src/OpenTelemetry/BatchExportProcessor.cs#L87

**Comment by alanwest** [comment]
@atrauzzi are you running your application in an alpine linux container? If so, I suspect this may be the problem you're running into #1251.

@cijothomas it does not seem that the work in #1634 prevents the crash in #1251... not sure we can catch this exception.

**Comment by atrauzzi** [comment]
@alanwest - Nope, bare on an ubuntu/pop!_os machine.

**Comment by alanwest** [comment]
Ah, yes, sorry I had missed your previous statement regarding Ubuntu.

**Comment by cijothomas** [comment]
@alanwest Do you know if this issue is fixed with daily build containing your PR for using diff grpc client lib for netstd21?

**Comment by alanwest** [comment]
> Do you know if this issue is fixed with daily build containing your PR for using diff grpc client lib for netstd21?

My hope is yes based on the testing that I've done. @atrauzzi would you be able to validate using the daily build in your environment? The change in #1662 may help assuming your application is .NET Core 3.0 or higher.

Daily builds are available from this MyGet source https://www.myget.org/F/opentelemetry/api/v3/index.json. You should be able to use `dotnet new nugetconfig` to generate a nuget.config file in the root of your project, and then add the following to it:

```xml
<add key="otel" value="https://www.myget.org/F/opentelemetry/api/v3/index.json" />
```

**Comment by atrauzzi** [comment]
I might be able to get a look in a couple of weeks, just wrestling with a deadline at the moment, that alright?

**Comment by alanwest** [comment]
I've validated that this is resolved for .NET Core 3.0 and higher apps running on Ubuntu.
