### ISSUE TITLE
Optimize Self-Diagnostics module to be zero-allocation

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet#1621]
# Feature Request

Optimally, the Self-Diagnostics module should be zero-allocation (except during construction and other one-time allocations) and zero GC. However there are 2 sources of memory allocation.

### 1. DateTime.UtcNow.ToString

`SelfDiagnosticsEventListener.WriteEvent` records a timestamp in the beginning of a log message. The `DateTime.UtcNow.ToString` method would incur memory allocation.

### 2. EventWrittenEventArgs

The only other memory allocation is for `EventWrittenEventArgs ` object of `SelfDiagnosticsEventListener.OnEventWritten(EventWrittenEventArgs eventData)` method, which comes from [EventListener](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener?view=netcore-3.1) class of EventSource library.

But it can't be optimized away as long as EventSource is used, because according to [a discussion from dotnet/runtime](https://github.com/dotnet/runtime/issues/13357#issuecomment-527682163):

> EventWrittenEventArgs is a managed object so it won't be cleaned up unless there is a GC that happens.

**Comment by martinjt** [comment]
Work has been merged on this, if there is more specifics needed, please reopen.
