### ISSUE TITLE
Could not add custom instrumentation

### ISSUE THREAD

**Issue by twenzel** [open-telemetry/opentelemetry-dotnet#1623]
With the change of https://github.com/open-telemetry/opentelemetry-dotnet/pull/1454 the `AddInstrumentation`method was renamed to `AddDiagnosticSourceInstrumentation` and marked as internal.

How can third-party libraries (e.g for MessageBus/NServiceBus) add their instrumentations to the tracer?
See https://github.com/jbogard/NServiceBus.Extensions.Diagnostics.OpenTelemetry/blob/master/src/NServiceBus.Extensions.Diagnostics.OpenTelemetry/TracerProviderBuilderExtensions.cs

**Comment by twenzel** [comment]
`DiagnosticSourceSubscriber` and `ListenerHandler` are now internal... how can I implement and add a Listener like https://github.com/jbogard/NServiceBus.Extensions.Diagnostics.OpenTelemetry/blob/master/src/NServiceBus.Extensions.Diagnostics.OpenTelemetry/Implementation/SendMessageListener.cs ?

**Comment by twenzel** [comment]
Or should this be implemented like https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/examples/MicroserviceExample ?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/docs/trace/extending-the-sdk#instrumentation-library Please follow this guide.

There is an open issue about ActivitySourceAdapter not yet addressed : https://github.com/open-telemetry/opentelemetry-dotnet/issues/1580
