### ISSUE TITLE
OpenTelemetryServicesExtensions Location

### ISSUE THREAD

**Issue by lawrence-laz** [open-telemetry/opentelemetry-dotnet#1642]
# Question

Currently `OpenTelemetryServicesExtensions` class is located in `OpenTelemetry.Extensions.Hosting` package. This is a bit unusual, as other packages tend to have `ServiceCollection` extensions in a package postfixed with `Extensions.DependencyInjection` or `Extensions.Microsoft.DependencyInjection`. For example:
- Autofac.Extensions.DependencyInjection 
- AutoMapper.Extensions.Microsoft.DependencyInjection
- MediatR.Extensions.Microsoft.DependencyInjection
- MassTransit.Extensions.DependencyInjection

This doesn't cause any functional problems (as far as I see), but I found it confusing and so might other users. Was `OpenTelemetry.Extensions.DependencyInjection` considered?

**Comment by cijothomas** [comment]
The naming was discussed a while ago : https://github.com/open-telemetry/opentelemetry-dotnet/pull/623#issuecomment-619222535

Please take a look, and see if that makes sense, or do you think we should revisit the name?

**Comment by lawrence-laz** [comment]
Hm, I guess it makes sense once you look into it.

The confusion comes from the fact that hosting service is opaque to the consumer. I wouldn't have thought that there is a hosted service being registered just to kick-start tracing provider. Hence why my instinct was to look for `DependencyInjection` and not `Hosting` package.

I don't have a solution here, but I bet I will not be the last one confused
