### ISSUE TITLE
Allow arrays of primitives in Resource Attribute Values

### ISSUE THREAD

**Issue by Austin-Tan** [open-telemetry/opentelemetry-dotnet#1652]
# Feature Request

Follow up to #1647 , where it was pointed out that arrays of primitives [should be allowed as the value in KV pairs as per spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md#attributes).

**Describe the solution you'd like:**

Our current behavior will throw an exception (post #1647) if invalid data types are used as the values.

**Describe alternatives you've considered.**

We have an obligation to the spec to support this, right? I'm not sure about the extent to which we currently achieve everything the spec prescribes.

## Additional Context

Add any other context about the feature request here.

**Comment by Austin-Tan** [comment]
Current issue in OTel specification:
https://github.com/open-telemetry/opentelemetry-specification/issues/1184
Don't want to work on this until this is confirmed.

**Comment by cijothomas** [comment]
@Austin-Tan the spec issue is ready to be closed. We can address this now.

**Comment by Austin-Tan** [comment]
Sounds good, feel free to assign this to me. I'll work on this today.
