### ISSUE TITLE
JaegerExporter does not seem to export to Jaeger collector in .NET core 3.1

### ISSUE THREAD

**Issue by isaac-j-miller** [open-telemetry/opentelemetry-dotnet#1660]
In my Program.cs, I have:
```c#
using System.Diagnostics;
using OpenTelemetry.Resources;
using OpenTelemetry;
using OpenTelemetry.Trace;
using OpenTelemetry.Exporter.Jaeger;

(...)


public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddOpenTelemetryTracing((builder) => 
                        {
                            builder
                            .SetSampler(new AlwaysOnSampler())
                            .AddSource("test-source")
                            .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("test-source"))
                            .AddConsoleExporter()
                            .AddJaegerExporter(jaegerOptions => {
                                var endpoint = hostContext.Configuration.GetValue<string>("JaegerEndpoint");
                                Uri uri = new Uri(endpoint);
                                jaegerOptions.AgentHost = uri.Host;
                                jaegerOptions.AgentPort = uri.Port;
                             })
                            .Build();
                        }   
                    );
               (...other config)
    }
```
In the environment where I've been developing, the Jaeger endpoint is http://localhost:14268/api/traces; although this program is configured to run in several environments, where the endpoint might not have an explicit port. 
I can verify that the tracing is working properly by watching the output of the console exporter. I am using System.Diagnostics Activity for tracing. However, none of the traces that are displayed by the console exporter appear in the Jaeger UI. I know that the Jaeger collector is functioning because a few services written in Typescript which use OpenTelemetry are all able to successfully export data to Jaeger and I can see those traces in the Jaeger UI. The app is being run in a docker container based on the mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim image

**Comment by Jacob-Ortiz** [comment]
Saw this same issue on 3.1 as well

**Comment by isaac-j-miller** [comment]
This was a docker issue

**Comment by flashrider** [comment]
And what was the issue with docker and how to correct it?

**Comment by isaac-j-miller** [comment]
I did not realize that the exporter was only communicating via udp and I
was using an http Jaeger collector docker container. Once I set up a udp
Jaeger collector, everything worked. After there currently plans to
implement an http Jaeger exporter?
