### ISSUE TITLE
What's the correct way to set Service/Resource Name in an ASP.NET Core Application?

### ISSUE THREAD

**Issue by hannahchan** [open-telemetry/opentelemetry-dotnet#1665]
I'm currently trying out OpenTelemetry in an ASP.NET Core application built using .NET 5. I found it very easy to instrument and export traces to Jaeger using only the following libraries.

```xml
<PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.0.0-rc1.1" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc1.1" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc1.1" />
```

And by adding the following to my `Startup.cs` class.

```C#
services.AddOpenTelemetryTracing(builder => builder
    .AddAspNetCoreInstrumentation()
    .AddJaegerExporter());
```

However when viewing my traces in Jaeger (running on my localhost), all my traces come from a service called `OpenTelemetry Exporter`.

![Screen Shot 2020-12-19 at 3 05 30 pm](https://user-images.githubusercontent.com/22674140/102680386-b7c2c300-420b-11eb-8aea-40e9363f573a.png)

What is the correct way to change this name? I can't seem to figure it out from looking at the docs in this repository. Are there any best practices for this as well?

**Comment by cijothomas** [comment]
Use Resource to set the service name in Jaeger: https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry#resource

**Comment by hannahchan** [comment]
Thanks @cijothomas. May I ask why do I need to import the SDK and create a Tracer Provider when the extension method `.AddOpenTelemetryTracing()` already does that for me. Is there a way to configure the one that's being created by that extension method?

Or am I misunderstanding something about the concept of a Tracer Provider?

I know it doesn't say it explicitly but [this documentation](https://opentelemetry.io/docs/net/getting-started/) makes it look like it's a different way to create Tracer Provider depending on whether it's a console application or an ASP.NET Core application.

**Comment by hannahchan** [comment]
I think I found my answer here.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/94c2755724ecd7aaee9d05807a3f789e9e0d973f/examples/AspNetCore/Startup.cs#L63

**Comment by selombanybah** [comment]
Perfect! it works for me too
