### ISSUE TITLE
Documentation Around Activity.IsAllDataRequested

### ISSUE THREAD

**Issue by RehanSaeed** [open-telemetry/opentelemetry-dotnet#1670]
# Question

**Describe your environment.**

Jaeger with an ASP.NET Core API.

**What are you trying to achieve?**

I'm trying to understand how `Activity.IsAllDataRequested` works. If it's possible to request more data, that suggests there is some way to do that. Do tools like Jaeger have some way to ask for extra data? What sets this value to true/false? Are there any docs around how this feature works?

**Comment by cijothomas** [comment]
`IsAllDataRequested` is same as `Span.IsRecording` from the Tracing Spec - https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#isrecording
https://github.com/open-telemetry/opentelemetry-dotnet/issues/947

Its meant to be used by instrumentation, to determine if there is any interested parties in the Span being created, and depending  on that , it can chose to keep populating the span with more attributes.
