### ISSUE TITLE
LogRecordTest.CheckStateForStrucutredLogWithGeneralType fails when run in locale with comma as decimal separator

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-dotnet#1678]
Test failure:

```
 OpenTelemetry.Tests.Logs.LogRecordTest.CheckStateForStrucutredLogWithGeneralType
   Source: LogRecordTest.cs line 193
   Duration: 5 ms

  Message: 
    Assert.Equal() Failure
                                     ↓ (pos 28)
    Expected: ···ruffle], [Price, 299.99]
    Actual:   ···ruffle], [Price, 299,99]
                                     ↑ (pos 28)
  Stack Trace: 
    LogRecordTest.CheckStateForStrucutredLogWithGeneralType() line 216
```

It seems to fail in all frameworks.

**Comment by eddynaka** [comment]
@Oberon00 , I think we could fix that adding the following in the test:  `ToString(CultureInfo.InvariantCulture))`.

That might solve the issue.

**Comment by Oberon00** [comment]
I tried around a bit. The mentioned ToString overload does not exist for `IReadOnlyList`. Also, using `string.Format(CultureInfo.InvariantCulture, "{0}", state)` has no effect unfortunately (probably because `state` does not implement `IFormatable`). What does work but is quite cumbersome is

```c#
            var prevCulture = CultureInfo.CurrentCulture;
            CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
            try
            {
                Assert.Equal("[Name, truffle], [Price, 299.99]", string.Format(CultureInfo.InvariantCulture, "{0}", state));
            } finally
            {
                CultureInfo.CurrentCulture = prevCulture;
            }
```

But at this point it may be better to make the test not rely on `ToString`.

**Comment by eddynaka** [comment]
We could iterate the state and compare the value/key. If that is too cumbersome. Both would work.
