### ISSUE TITLE
Move to PackageReference instead of ProjectReference in examples

### ISSUE THREAD

**Issue by surenderssm** [open-telemetry/opentelemetry-dotnet#1682]
# Feature Request

Generally one refers examples/samples to explore on the usage of the library.
Currently examples are taking project dependencies instead of package dependencies.

**Describe the solution you'd like:**

For a Least resistant and better experience (consistent with other repo samples), How about changing move to package reference instead of project reference.

For example in examples/AspNetCore/Examples.AspNetCore.csproj
Current State

    <ProjectReference Include="$(RepoRoot)\src\OpenTelemetry.Exporter.Console\OpenTelemetry.Exporter.Console.csproj" />

Proposed State

    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.0.0-rc1.1" />

**Describe alternatives you've considered.**

Currently one has to clone the full repo in order to run the samples.

## Additional Context

At least before going GA we should consider fixing this.

**Comment by cijothomas** [comment]
The examples can be kept current by referring projects directly. If we move to packageref, then we'll not be able to update samples except when we publish something to nuget. right? (sorry if I may have misunderstood your ask)

**Comment by surenderssm** [comment]
@cijothomas you got the ask right. Yes if we move to pacakgeref we won't be able to update examples till we publish the nuget.
Given the current state sticking to projectref might be solving the purpose.

Generally examples are for customer (dev) to consume and get familiar with API with least resistant to run on local.

For example : 
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj

If not now someday we have to see how to give the seamless experience to the dev.
Alternative strategy can be to have a separate location like samples which has no reference to projects.

Any thoughts ?

**Comment by cijothomas** [comment]
@surenderssm The linked azure-cosmos-dotnet example - its able to use package reference because the packages are shipped from elsewhere. (We do the same approach here for external packages).

> Alternative strategy can be to have a separate location like samples which has no reference to projects.

This is the long term plan. After the initial releases, we'll try to move the examples to a separate place.  Some place like https://github.com/dotnet-architecture/eShopOnContainers (which is currently adding ApplicationInsights, but we need to convince them to use OpenTelemetry. This requires us to GA first.)

**Comment by surenderssm** [comment]
@cijothomas Sounds like a plan, we can close or keep this hanging around till we go for GA.

However in the given azure-cosmos-dotnet example, package are shipped from the same repo and is used in samples via package reference.
For example :
`    <PackageReference Include="Microsoft.Azure.Cosmos" Version="*" />
`
Source : https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos/src
Example : 
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj

> The linked azure-cosmos-dotnet example - its able to use package reference because the packages are shipped from elsewhere. (We do the same approach here for external packages).

**Comment by cijothomas** [comment]
Closing old issues. The examples in this repo will be on project reference to keep updated all the time. OpenTelemetry.io has docs where the packageversion is shown. (Agree the docs needs to converge, that has not happened yet)
