### ISSUE TITLE
Enable .net5.0 for integration tests

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet#1686]
# Feature Request

The [integration tests](https://github.com/open-telemetry/opentelemetry-dotnet/blob/e2a908e08945a13bfc912696b5fb17927bf59a1a/.github/workflows/integration.yml#L19) are not working on .net5.0 yet, even though .net5.0 has been enabled for all unit tests in #1486.

**Comment by xiang17** [comment]
I'm working on this. (Don't have the permission to assign this to myself.)

**Comment by eddynaka** [comment]
> I'm working on this. (Don't have the permission to assign this issue to myself.)

just updated!
