### ISSUE TITLE
Grpc -> Exception Details viewable in jaeger

### ISSUE THREAD

**Issue by Ed-Hill** [open-telemetry/opentelemetry-dotnet#1687]
# Question
Should the details of an exception using grpc and the jaeger exporter appear in jaegur by default or is there a setting?

**Describe your environment.**
Windows 10 Pro with .net sdk 3.1 
A git clone of the repo, modify GreeterService.cs in the examples folder to:

```
        public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
        {
            throw new RpcException(new Status(StatusCode.PermissionDenied, "Permission denied"));
        }
```
and set the app setting to export to jaegur

run it and call SayHello from a client

**What are you trying to achieve?**

I'd like to see the exception details in jaeger in this scenario

What did you expect to see?

I'm not quite sure, where the exception details should be but I was expecting them to be visible when I search jaeger for that trace and view it's details

## Additional Context

I tried setting detailed errors on grpc but this didn't help 
```
options.EnableDetailedErrors = true;
```

The only way I could get to see this was to add an interceptor that calls RecordException
 
Modify StartUp.cs
```
            services.AddGrpc(options => 
            {
                 options.Interceptors.Add<ExceptionInterceptor>();
            });

```
Add the interceptor class:
```
namespace Examples.GrpcService
{

    public class ExceptionInterceptor : Interceptor
    {
        private readonly ILogger<ExceptionInterceptor> _logger;

        public ExceptionInterceptor(ILogger<ExceptionInterceptor> logger)
        {
            _logger = logger;
        }

        public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(
            TRequest request,
            ServerCallContext context,
            UnaryServerMethod<TRequest, TResponse> continuation)
        {
            try
            {
                return await continuation(request, context);
            }
            catch (Exception ex)
            {
                Tracer.CurrentSpan.RecordException(ex);
                throw;
            }
        }
    }
}
```
This then gives me a Logs(1) in Jaeger with the exception event 

Is this by design? Is this what I'm supposed to do? Have I just done a dirty hack?

**Comment by Ed-Hill** [comment]
I'm sure it was running on 3.1 but just to make it a bit cleaner I repeated this on an environment with just 3.1 and the behaviour is the same

**Comment by cijothomas** [comment]
Grpc instrumentation currently doesn't record exception. We can check if its feasible to add.

**Comment by cijothomas** [comment]
@xiang17 Can you check if Grpc has access to exception and if yes, have it record exception.

**Comment by ovidiubuligan** [comment]
What is the status of this issue ? We really need it .

**Comment by cijothomas** [comment]
This is not yet done, and is tracked by https://github.com/open-telemetry/opentelemetry-dotnet/issues/2070.
Closing as duplicate.
