### ISSUE TITLE
SelfDiagnosticsModule doesn't filter out logs of lower severity level as configured

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet#1689]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

* All that has Self Diagnostics modules

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):

* All .NET Frameworks has this issue. (All versions of .NET Core are free of this issue.)

## Symptom

Create a file "OTEL_DIAGNOSTICS.json" with content in folder "docs/trace/getting-started":

```json
{
    "LogDirectory": ".",
    "FileSize": 1024,
    "LogLevel": "Error"
}
```

Run command in the same folder: `dotnet run --configuration Release --framework net472 --project getting-started.csproj`

### Bug#1

A file would be generated with content:

```
Successfully opened file.2021-01-09T05:57:36.7394837Z:Activity started. OperationName = '{0}', Id = '{1}'.{Foo}{00-f02701bfe384804ea468f9f4770c6d2e-13c2dca1b5ebc549-01}
2021-01-09T05:57:36.7764812Z:Activity started. OperationName = '{0}', Id = '{1}'.{Bar}{00-f02701bfe384804ea468f9f4770c6d2e-7f5b345dbb1b624a-01}
2021-01-09T05:57:36.7774818Z:Activity started. OperationName = '{0}', Id = '{1}'.{Baz}{00-f02701bfe384804ea468f9f4770c6d2e-74abb7d3cce3f944-01}
2021-01-09T05:57:36.7954830Z:Activity stopped. OperationName = '{0}', Id = '{1}'.{Baz}{00-f02701bfe384804ea468f9f4770c6d2e-74abb7d3cce3f944-01}
2021-01-09T05:57:36.8824836Z:Activity stopped. OperationName = '{0}', Id = '{1}'.{Bar}{00-f02701bfe384804ea468f9f4770c6d2e-7f5b345dbb1b624a-01}
2021-01-09T05:57:36.8834843Z:Activity stopped. OperationName = '{0}', Id = '{1}'.{Foo}{00-f02701bfe384804ea468f9f4770c6d2e-13c2dca1b5ebc549-01}
```

### Bug#2

There is also a separate issue that this file cannot be opened (even in read-only mode) by text editor when the program is running.

![Untitled - Notepad 1_12_2021 4_49_57 PM](https://user-images.githubusercontent.com/9310587/104392220-7e256500-54f6-11eb-9b97-6dda660a3fd0.png)

**What is the expected behavior?**

The issues don't happen for .NET Core: Run command `dotnet run --configuration Release --framework netcoreapp3.1 --project getting-started.csproj`:

A file should be generated with content:

```
Successfully opened file.
```

[Activity started/stopped events](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Internal/OpenTelemetrySdkEventSource.cs#L260-L270) are `Verbose` level. They should be omitted by self diagnostics module when LogLevel is set to Error, according to [EventListener.EnableEvents](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener.enableevents?view=net-5.0) and [EventLevel](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlevel?view=net-5.0) documentation.

The file should be able to be opened, at least in read-only mode.

What did you expect to see?

See above. Running in .NET Frameworks should be the same as in result of .NET Core.

**What is the actual behavior?**

See above.

What did you see instead?

See above.

**Comment by cijothomas** [comment]
@xiang17 Please confirm if this is already fixed and can be closed.

**Comment by xiang17** [comment]
Yes it's already fixed.
