### ISSUE TITLE
Separate OT classes and serialization from OTLP exporter

### ISSUE THREAD

**Issue by voltcode** [open-telemetry/opentelemetry-dotnet#1698]
**Is your feature request related to a problem?**

While writing a new Exporter that should export data in OT format but the destination is not the Collector, but database and some other services.

There is already some logic in ActivityExtensions.cs in OpenTelemetry.Exporter.OpenTelemetryProtocol but it is marked internal. 
Proto files are a good starting point but are not sufficient for serialization from Activity that does the heavylifting.

**Describe the solution you'd like:**

Please make serialization to OT format (C# classes generated from OT proto) separate from OTLP exporter. 
It should not depend on grpc (grpc is not available in NET FX for example) or be netcore only. 

**Describe alternatives you've considered.**

Copy entire code from ActivityExtensions.cs seems like a bad practice, and against OT idea - the format should be easy to reuse.

**Comment by mladjan-gadzic** [comment]
hi @cijothomas! i am new to otel and this is something that i find lacking. do you know whether there was movement to bridge this gap in any other issues or ways?

**Comment by mladjan-gadzic** [comment]
@voltcode i am interested in your approach on how did you do serialization yourself. could you please clarify what did you mean by this? 

> Copy entire code from ActivityExtensions.cs

this issue was raised quite a while ago and project might have evolved since then.
