### ISSUE TITLE
Remove hasdParent from SpanData

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#17]
https://github.com/open-telemetry/opentelemetry-java/pull/90

**Comment by trwegner** [comment]
Working on this

**Comment by trwegner** [comment]
Would like to clarify if this change extends to all occurences of hasRemoteParent or actually just those in SpanData.  Referencing the Java implementation, the concept of a remote parent appears to be addressed by use of SpanContext to specifiy a parent.  To strictly follow this pattern, the changes extend well beyond SpanData.

**Comment by SergeyKanzhelev** [comment]
I believe the concept of separate variable to track the informaiton on whether the parent is remote or now was removed all together. Including proto files.

**Comment by SergeyKanzhelev** [comment]
SpanContext was always used to indicate the parent. `hasRemoteParent` gave additional information that parent is NOT local, meaning from the different process. Mostly used to indicate that clock may be un-synchronized

**Comment by SergeyKanzhelev** [comment]
fixed via #55
