### ISSUE TITLE
Add more depth to OpenTelemetry?

### ISSUE THREAD

**Issue by wmoecke** [open-telemetry/opentelemetry-dotnet#1703]
# Question

**Describe your environment.**

1) ASP .NET Core 5.0 Web API with endpoints (controller);
- Requests made to these endpoints are formatted and re-routed to another API (external) for processing; it then provides appropriate responses which are then parsed and handed back to clients.

2) ASP. NET Core 5.0 Web API configured as API Gateway (Ocelot), with telemetry sent to ZipKin.

**What are you trying to achieve?**

Ideally, project (2) would be able to see and record telemetry up to the point where the second HTTP request is made to the external endpoint. Basically, when looking at the "Dependencies" tab (Zipkin UI) we'd like to see 2 "routes":
- API Gateway (2) to Web API (1);
- Web API (1) to external API endpoint

And additionally, see metrics for all the requests from the point they are caught by the API Gateway (2) up to the requests made to the second API (external).

## Additional Context

In recent experiments, we could achieve this result by adding OpenTelemetry to the Web API (1) project, exporting telemetry data to the same Zipkin endpoint as configured in the API Gateway (2) project. When opening Zipkin UI, the result is exactly as explained above. We'd like to not have to do this in order to keep the Web API (1) completely decoupled.

**Comment by martinjt** [comment]
I think this is actually a misunderstanding of how tracing works. Each application is independent, only context is transmitted between the applications as headers. That's a fundamental part of Distributed Tracing, and therefore not something that any OpenTelemetry SDK or application could fix.

If I've misunderstood the request, and you can provide more context, please reopen this issue.
