### ISSUE TITLE
Support for proxying calls

### ISSUE THREAD

**Issue by jcarres-mdsol** [open-telemetry/opentelemetry-dotnet#1704]
# Feature Request

This is half question but I suspect the answer is no. So it becomes a feature request.

Is it possible to send the traces to the collector specifying a particular proxy host and port for those POST request (sending http OTLP format) ?
We have a complex network topology with some very unique security measures and this is a must for us to be able to reach the collector.

**Comment by johnduhart** [comment]
@jcarres-mdsol I think we can close this now, the `ZipkinExporter` is publicly exposed and we can configure the `HttpClient` it uses with the needed proxy.

**Comment by cijothomas** [comment]
Thanks John for responding. Closing now.
