### ISSUE TITLE
Reverse priority for Resource.Merge

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1712]
Spec reversed the order of priority. The incoming resource take precedence in case of collision.
https://github.com/open-telemetry/opentelemetry-specification/pull/1345/files

**Comment by Austin-Tan** [comment]
When referring to the two resources, using "old" and "updating" instead of "current" and "other", as they use in the spec.

**Comment by Austin-Tan** [comment]
Actually keeping the phrasing "other" since it's used as the parameter name and is generally convention in methods passed an "other" object for comparison or manipulation.
