### ISSUE TITLE
How come I get a null reference exception on non empty path base?

### ISSUE THREAD

**Issue by philipbawn** [open-telemetry/opentelemetry-dotnet#1713]
I get null reference on activity if I trigger my api that I want to instrument using OpenTelemetry by
POST "/myservice/service/v1/MyMethod" as opposed to POST "/service/v1/MyMethod"

I have a .NET 5 openapi project with swagger, have package references to these versions:

    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.0.0-rc1.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.0.0-rc1.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Zipkin" Version="1.0.0-rc1.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc1.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc1.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc1.1" />

I am using app.UsePathBase("/myservice"); as the first statement in the Configure method of startup.cs, before UseRouting() and then UseSwagger()
Finally I have:

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(name: "default",
                pattern: "{controller=ServiceController}/");
                endpoints.MapHealthChecks("/healthz");
            });
On my controller method (in ServiceController which inherits from Microsoft.AspNetCore.Mvc.Controller I have decorated my method
[Route("service/v1/MyMethod")]

such that post to either
https://localhost:5010/myservice/service/v1/MyMethod
https://localhost:5010/service/v1/MyMethod

do work or record telemetry.

However if I try to access "activity" in the below method of 
SomeCustomService (which is a singleton registered in the service collection and injected into the controller via the constructor)

        public void Add(string number, List<MyCustomObjects> myCustomObjects)
        {
            string key = "added_" + number;

            using (var activitySource = new ActivitySource(nameof(SomeCustomService)))
            {
                using (var activity = activitySource.StartActivity("SET " + key, ActivityKind.Client))
                {
                    activity.AddTag("net.peer.name", "other host here");

I get null reference on activity if I trigger the activity by POST "/myservice/service/v1/MyMethod" as opposed to POST "/service/v1/MyMethod".

In Startup.ConfigureServices I have (at the very bottom of the method):

            services.AddOpenTelemetryTracing(builder => builder
            .AddAspNetCoreInstrumentation((options) =>
            options.Enrich
            = (activity, eventName, rawObject) =>
            {
                if (eventName.Equals("OnStartActivity"))
                {
                    if (rawObject is HttpRequest httpRequest)
                    {
                        activity.SetTag("requestProtocol", httpRequest.Protocol);
                    }
                }
                else if (eventName.Equals("OnStopActivity"))
                {
                    if (rawObject is HttpResponse httpResponse)
                    {
                        activity.SetTag("responseLength", httpResponse.ContentLength);
                    }
                }
            })
            .AddSqlClientInstrumentation(opt => opt.SetTextCommandContent = true)
            .AddSource(nameof(SomeCustomService))
            .AddJaegerExporter()
            .AddZipkinExporter(c =>
            {
                c.ServiceName = "MyService";
                c.Endpoint = new Uri(Environment.GetEnvironmentVariable("ZIPKIN_ENDPOINT"));
                c.ExportProcessorType = ExportProcessorType.Simple;
            })
            );

**Comment by cijothomas** [comment]
Activity could be null if sampling decision is unfavourable. This is something which may be changed based on this bug: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1709

To confirm if this is indeed the issue you are hitting, please change sampler to AlwaysOnSampler, instead of default sampler.

**Comment by philipbawn** [comment]
> Activity could be null if sampling decision is unfavourable. This is something which may be changed based on this bug: #1709
> 
> To confirm if this is indeed the issue you are hitting, please change sampler to AlwaysOnSampler, instead of default sampler.

That was the problem. Thank you Cijo.

**Comment by philipbawn** [comment]
Added             .SetSampler(new AlwaysOnSampler()) to method chain solved my question.
