### ISSUE TITLE
SDK does not output logs for ASP.Net Application

### ISSUE THREAD

**Issue by Howard-Joshua-R** [open-telemetry/opentelemetry-dotnet#1714]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

OpenTelemetry 1.0.0-rc1.1
OpenTelemetry.Instrumentation.AspNet 1.0.0-rc1.1
OpenTelemetry.Instrumentation.Http 1.0.0-rc1.1

*

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):

.NET Framework 4.8

*

## Symptom

Following the documentation to output SDK logs, but no log output is being created. I've properly setup the OTEL_DIAGNOSTICS.json configuration and have placed it in multiple paths with multiple variations on the 'LogDirectory' parameter but have had no luck. 

Cijo Thomas recommended I open this issue.

**What is the expected behavior?**

Expected to see a log file with SDK logging info.

**What is the actual behavior?**

Nothing...

## Reproduce

I've got an example project here: https://github.com/Howard-Joshua-R/OpenTelemASPNet

## Additional Context

Worked with Cijo Thomas on a related issue but we were not able to produce SDK Logs.

**Comment by cijothomas** [comment]
@xiang17 Please take a look.

**Comment by tbolon** [comment]
[SelfDiagnosticsParser](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Internal/SelfDiagnosticsConfigParser.cs) uses Environment.CurrentDirectory, which by default is `c:\windows\system32\inetsrv` when using IIS.

So you should put temporary your OTEL_DIAGNOSTICS.json file in this folder as a workaround.

**Comment by tbolon** [comment]
A good fix could be to use [AppContext.BaseDirectory](https://stackoverflow.com/a/6041505) to determine the application location,
