### ISSUE TITLE
Define API as C# Interface instead of abstract classes

### ISSUE THREAD

**Issue by victlu** [open-telemetry/opentelemetry-dotnet#1716]
# Feature Request

Given a strong separation between API and SDK, it would make sense to define the API as C# Interfaces (lacks implementation) rather than abstract classes (a specific implementation).  Using C# Interface will convey the shape and meaning of the intended usage without providing any opinionated implementation.  The implementation of said Interfaces is best left to the SDK portion.

## Example

Below is an example of how the metric API can be define with C# Interfaces

```
    public interface IMetricProvider
    {
        IMeter GetMeter(string name, string version);
    }

    public interface IMeter
    {
        ICounter<T> NewCounter<T>(string name);

        IBatchBuilder RecordBatch(ILabelSet labelSet);
    }

    public interface ICounter<T>
    {
        void Add(T increment, ILabelSet labels);

        IBoundCounter<T> Bind(ILabelSet labels);
    }

    public interface IBoundCounter<T>
    {
        void Add(T increment);

        void Unbind();
    }

    public interface IBatchBuilder
    {
        IBatchBuilder Add<T>(ICounter<T> counter, T value);

        void Record();
    }

    public interface ILabelSet
    {
        IDictionary<string,string> GetLabels();
    }
```

Also, we do need one concrete starting location...

```
    static public class MetricProvider
    {
        static IMetricProvider provider = new NoOpMetricProvider();

        static public IMetricProvider GetProvider()
        {
            return provider;
        }

        static public IMetricProvider SetProvider(IMetricProvider provider)
        {
            return Interlocked.Exchange(ref MetricProvider.provider, provider);
        }
    }
```

## Considerations

1. There may be concerns that Interface design may lead to overhead in call performance.  AFAIK, and simple google search seems to indicate these concerns are minor and/or debatable.  And instead, one should focus on design patterns, usability, and readability.  However, maybe more comments can be provided here by our community.

2. We still need to include a "No-Op" implementation for when no SDK (including standard OTel) is attached.  This implementation may be packaged separately (or included in API for convenience).

### Example No-Op Implementation of API Interfaces

```
    public class NoOpMetricProvider : IMetricProvider
    {
        public IMeter GetMeter(string name, string version)
        {
            return new NoOpMeter(name, version);
        }
    }

    public class NoOpMeter : IMeter
    {
        public NoOpMeter(string name, string version)
        {
        }

        public ICounter<T> NewCounter<T>(string name)
        {
            return new NoOpCounter<T>(name);
        }

        public IBatchBuilder RecordBatch(ILabelSet labels)
        {
            return new NoOpBatchBulder(labels);
        }
    }

    public class NoOpCounter<T> : ICounter<T>
    {
        public NoOpCounter(string name)
        {
        }

        public void Add(T increment, ILabelSet labels)
        {
            // NOOP
        }

        public IBoundCounter<T> Bind(ILabelSet labels)
        {
            return new NoOpBoundCounter<T>(this, labels);
        }
    }

    public class NoOpBoundCounter<T> : IBoundCounter<T>
    {
        ICounter<T> counter;
        ILabelSet labels;

        public NoOpBoundCounter(ICounter<T> counter, ILabelSet labels)
        {
            this.counter = counter;
            this.labels = labels;
        }

        public void Add(T increment)
        {
            counter.Add(increment, labels);
        }

        public void Unbind()
        {
            // NOOP
        }
    }

    public class NoOpBatchBulder : IBatchBuilder
    {
        private ILabelSet labels;

        ConcurrentQueue<Action<ILabelSet>> actions = new();

        public NoOpBatchBulder(ILabelSet labels)
        {
            this.labels = labels;
        }

        public IBatchBuilder Add<T>(ICounter<T> counter, T value)
        {
            actions.Enqueue((ls) => counter.Add(value, ls));
            return this;
        }

        public void Record()
        {
            var oldActions = Interlocked.Exchange(ref actions, new ConcurrentQueue<Action<ILabelSet>>());

            foreach (var act in oldActions)
            {
                act(labels);
            }

            oldActions.Clear();
        }
    }
```

**Comment by noahfalk** [comment]
For the tracing part of the API, the BCL review team recommended against using the interfaces, at least as the public facing API that  most .NET developers would invoke. There is no iron-clad rule but the usual concerns are devs find factory+interface less discoverable and a little more complex to comprehend than new + concrete types. Another concern is that interfaces are very challenging to evolve over time because adding new members is very often a breaking change.

I had also proposed that for the .NET API we'd like to ensure that if there are multiple components listening then we want a guarantee coming from .NET that all listener callbacks will be invoked. This means the initial implementation that user code is calling into is some runtime provided facade that dispatches to listeners. There would be little value having an interface at that layer if .NET's implementation is fixed. There still might an interface like this between .NET's facade and whatever implementation the SDK wants to provide.

Related comment: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1723#discussion_r564212900

**Comment by victlu** [comment]
In my example, we still need to "ground" the whole API with a concrete class.  In this case we have a MetricProvider class that acts like a factory to create IMeter.  But based on your comment, the Dev will need to potentially call "new MetricProvider()) first.  That can be our concrete class.

Separately, we can discuss if MetricProvider should be the starting point, or maybe a concrete new Meter(..) should be used instead?

**Comment by martinjt** [comment]
We made the decision to not abstract these and leave that to the runtime teams, therefore this should be discussed in the dotnet/runtime issues repo.
