### ISSUE TITLE
The Tacer starting point  parentspanid is not null

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#173]
Normally,the Tacer starting point parentspanid is null ,but when tacer start, the ParentSpanID not null。

[{
    "traceId": "915663aeb043944fa796b504c5dd3a6b",
    **"parentId": "41f7ead7eda5754a",**
    "id": "c2141c5ba55e3c49",
    "kind": "SERVER",
    "name": "/Login/Login",
    "timestamp": 1564539176486000,
    "duration": 1316000,
    "localEndpoint": {
        "serviceName": "OpenTelemetry_Login_Service",
        "ipv4": "192.168.56.1",
        "ipv6": "fe80::dccf:35b2:d054:27eb",
        "port": 0
    },
    "remoteEndpoint": null,
    "annotations": null,
    "tags": {
        "http.host": "localhost:44318",
        "http.method": "POST",
        "http.path": "/Login/Login",
        "http.user_agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
        "http.url": "http://localhost:44318/Login/Login",
        "http.status_code": "200",
        "census.status_code": "Ok"
    },
    "debug": false,
    "shared": false
}]

**Comment by lmolkova** [comment]
Is this still a problem with latest nighly build from myget? If it is, please provide the repro app/code snippet

**Comment by SergeyKanzhelev** [comment]
Seems to be fixed. Please re-open if issue persists
