### ISSUE TITLE
JaegerExporter Resource mapping is not spec compliant.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#1730]
The JaegerExporter currently uses a workaround to make the Jaeger UI look better. This, while makes UI appear better, is not in compliance with the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/jaeger.md#resource

Proposing to modify JaegerExporter to be spec compliant before 1.0.0 release.
And pursue changes to the spec itself or jaeger product after the release.

Related: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1498

**Comment by CodeBlanch** [comment]
Also related to #1388.
