### ISSUE TITLE
Implement standards for Otlp gRPC exporter config used in Java and Python

### ISSUE THREAD

**Issue by markfink-splunk** [open-telemetry/opentelemetry-dotnet#1741]
# Feature Request

- For insecure Otlp gRPC transport, with the .NET SDK today, I need to prepend http:// to the endpoint.  Other languages use the OTEL_EXPORTER_OTLP_INSECURE env variable and you still specify the endpoint as "hostname:4317".  I mostly just want to see a standard implemented consistently on this across languages.
- Java/Python automatically look at the OTEL_EXPORTER_OTLP_ENDPOINT env variable to configure the Otlp endpoint.  This is convenient and it would be good to follow suit on that.

**Describe alternatives you've considered.**

At the moment, I add a line to check the OTEL_EXPORTER_OTLP_ENDPOINT variable.  I shouldn't have to do that.  And I prepend the endpoint with http:// for insecure transport.

In general though, it would be ideal if the SDK implementation would honor all env variables that are used in other languages like Java and Python.  The above happen to be the ones I look for first.  Then we could create a single page for standard env variables that apply to all languages and not have to document it per language.

**Comment by johnduhart** [comment]
> Then we could create a single page for standard env variables that apply to all languages and not have to document it per language.

You mean like https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md ?

**Comment by cijothomas** [comment]
Spec for ENV variable already exist, but its not marked stable yet. (some renaming discussion going on actively).

**Comment by markfink-splunk** [comment]
Who has time to read the manual?!  :).  Learning as I go here.  Thanks for your attention and keep up great work!

**Comment by markfink-splunk** [comment]
On this note, Java just released 0.15.0 in which they stopped using the OTLP_INSECURE variable and are using http:// instead.  So you were ahead of the curve!  I see now that this really is in a state of flux.  Never mind me!

**Comment by cijothomas** [comment]
Closing in favor of uber item tracking all env variable : https://github.com/open-telemetry/opentelemetry-dotnet/issues/1453
