### ISSUE TITLE
Provide automatic propagator config based on OTEL_PROPAGATORS variable

### ISSUE THREAD

**Issue by markfink-splunk** [open-telemetry/opentelemetry-dotnet#1742]
# Feature Request

Similar to Java, read the OTEL_PROPAGATORS variable to configure propagation.

**Comment by cijothomas** [comment]
We'll be adding support for all Environment variables required by the spec after 1.0.0 release. The spec for env variable is not yet marked stable.

**Comment by cijothomas** [comment]
Closing in favor of uber item tracking all env variable : https://github.com/open-telemetry/opentelemetry-dotnet/issues/1453
