### ISSUE TITLE
Jaeger exporter not working under .NET Core 2 (System.TypeLoadException: 'Could not load type 'Thrift.Protocols.TAbstractBase')

### ISSUE THREAD

**Issue by AlexeiScherbakov** [open-telemetry/opentelemetry-dotnet#175]
Throws exception on jaegerExporter.Start();
`System.TypeLoadException: 'Could not load type 'Thrift.Protocols.TAbstractBase' from assembly 'Thrift, Version=0.6.0.39067, Culture=neutral, PublicKeyToken=null'.'`

Manually adding Thrift package don't help. Version - 0.2.0-alpha.5

**Comment by AlexeiScherbakov** [comment]
0.2.0-alpha.9 - same issue

**Comment by AlexeiScherbakov** [comment]
It can be easy fixed by renaming Thrift package

**Comment by mwinkler** [comment]
Same issue here.

It seems `Thrift` `0.2.0-alpha.16` is missing in `www.myget.org/F/opentelemetry` nuget feed. 
Latest available version is `0.2.0-alpha.7`

When i switch back to `0.2.0-alpha.7` of `OpenTelemetry.Exporter.Jaeger` it works.

**Comment by lmolkova** [comment]
Ok, so it seems this was broken when I made thrift unpackable. And this is final as we are not going to publish it. So Jaeger exporter should be changed to compile thrift and include the liib rather than use projectreference

**Comment by pcwiese** [comment]
I've got a PR out to address this:
[https://github.com/open-telemetry/opentelemetry-dotnet/pull/193](https://github.com/open-telemetry/opentelemetry-dotnet/pull/193)

**Comment by AlexeiScherbakov** [comment]
Actually I found 2 problems:
1. Not working exporter (Thrift conflicts with existing package)
2. Not working solution with test service which have 2 exporter to 2 jaeger
all-in-one containers (Opentracing to jaeger-allinone-1 and OpenTelemetry
to jaeger-allinone-2).

For solving second case OpenTelemetry assembly 'Thrift.dll' must be
renamed, because 'Jaeger' from OpenTracing also comes with 'Thrift.dll'

You can decide publish or not publish Thrift.dll as NuGet, but I think that
it must be renamed to resolve conflict with already existing package
'Thrift'

чт, 22 авг. 2019 г., 20:13 Peter Wiese <notifications@github.com>:

**Comment by pcwiese** [comment]
A good point. However, are you using the Jaeger C# client library in addition to the OpenTelemetry Jaeger exporter? When I look at the C# Jaeger OpenTracing library it takes a dependency on Jaeger.Thrift.dll, not on Thrift.dll, so there is no name collision here (in this setup anyway).

**Comment by AlexeiScherbakov** [comment]
Yes, you are right! That was part of my service. It is sending 'pings' via
thrift  + grpc + http + rabbit, for testing span generation

чт, 22 авг. 2019 г., 21:55 Peter Wiese <notifications@github.com>:

**Comment by psibernetic** [comment]
This is fixed in .23 confirmed.
