### ISSUE TITLE
ConsoleExporterOptions in wrong namespace

### ISSUE THREAD

**Issue by simhgd** [open-telemetry/opentelemetry-dotnet#1766]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

* OpenTelemetry.Exporter.Console 1.0.0-rc2

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):

* net5.0

## Symptom

**What is the expected behavior?**

`OpenTelemetry.Exporter.Console.ConsoleExporterOptions`

**What is the actual behavior?**

`OpenTelemetry.Exporter.ConsoleExporterOptions`

## Reproduce

```csharp
    public class OpenTelemetryOptionsWrapper
    {
        public OpenTelemetry.Instrumentation.AspNetCore.AspNetCoreInstrumentationOptions AspNetCore { get; set; }
        public OpenTelemetry.Instrumentation.Http.HttpClientInstrumentationOptions HttpClient { get; set; }
        public OpenTelemetry.Instrumentation.GrpcNetClient.GrpcClientInstrumentationOptions GrpcClient { get; set; }
        public OpenTelemetry.Instrumentation.SqlClient.SqlClientInstrumentationOptions SqlClient { get; set; }
        public OpenTelemetry.Exporter.Zipkin.ZipkinExporterOptions Zipkin { get; set; }
        public OpenTelemetry.Exporter.ConsoleExporterOptions Console { get; set; }
    }
```
We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/1332 @utpilla is working to make this consistent.

**Comment by cijothomas** [comment]
@simhgd 

> What is the expected behavior?
> 
> OpenTelemetry.Exporter.Console.ConsoleExporterOptions
> 
> What is the actual behavior?
> 
> OpenTelemetry.Exporter.ConsoleExporterOptions

This behaviour is by design. OpenTelemetry.Exporter.ConsoleExporterOptions is preferred over OpenTelemetry.Exporter.Console.ConsoleExporterOptions as https://github.com/open-telemetry/opentelemetry-dotnet/pull/1332.
