### ISSUE TITLE
Appetite for ASMX and WCF support in .NET Framework??

### ISSUE THREAD

**Issue by notcool11** [open-telemetry/opentelemetry-dotnet#1784]
Sorry if _issue_ is not the right place for this, happy to move it if needed.

Searching through the repo I didn't see any mention of ASMX and only a couple comments on WCF. We have apps that are still heavily using these older technologies, but still wish to participate in tracing. Most importantly we don't want traces to die because they flow through one of these systems.

I've built out a Jaeger based tracing framework to both honor the tracing data passed in to ASMX and WCF services as well as context propagate when clients call to these older frameworks.

The WCF solution is Endpoint Behavior based, meaning implementation can be done easily through .config files for both inbound and outbound context propagation.

ASMX inbound is just a Web Request so HttpModules work fine there. Howerver, the outbound propagation is a bit trickier because that technology was built before Dependency Injection was a thing. I'm using partial classes to extend ASMX Web References to get access to the GetWebResponse method. It's annoying depending on how many ASMX references you have, but I couldn't find a better way.

Because .NET 3.5 is still supported on Server 2019, I don't see ASMX or WCF going away any time soon. I'd like to see support for WCF and ASMX published, but before bothering with a PR I wanted to see if this is even something that would be appreciated. Thanks.

-Tyler

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/38 There is an active PR (draft) in contrib repo for WCF instrumentation. We are likely to maintain all the instrumentations in the -contrib repo, and its best to open an issue in that repo, and PRs for any new instrumentation.

OpenTelemetry .NET is built on top of DiagnosticSource package version 5.0. (https://www.nuget.org/packages/system.diagnostics.diagnosticsource) That package's minimum support is .NET45, so I don't think its possible to support .NET 3.5 apps

**Comment by notcool11** [comment]
Right on, thanks for pointing to the other other repo and the specific PR.
