### ISSUE TITLE
Http Client instrumentation does not invoke the Enricher on Framework 4.7.2

### ISSUE THREAD

**Issue by naphta** [open-telemetry/opentelemetry-dotnet#1787]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

* OpenTelemetry 1.0.0-rc2

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file): 

* net472

## Symptom
When setting an enricher on the HttpClient instrumentation the Enrich function doesn't get invoked.

**What is the expected behavior?**

What did you expect to see?
That the code path is hit (we were using a breakpoint to determine if the enricher was being hit.

**What is the actual behavior?**
What did you see instead?
The breakpoint set on the enricher function was never hit.

## Reproduce

Create a self-contained project using the template of your choice, apply the
minimum required code to result in the issue you're observing.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context
I don't have a reproduced example to hand but the code we were using is below, and we were seeing traces from the HttpClient for the requests as expected, just that the enricher wasn't itself being hit.

```
options.Enrich = (activity, eventName, rawObject) =>
{
    <breakpoint> if (rawObject is HttpRequestMessage request)
    {
        activity.SetTag("requestVersion", request.Version);
    }
};
```

**Comment by cijothomas** [comment]
Please share the versions of the package you are using, and your TracerProvider setup code as well.

**Comment by naphta** [comment]
Oh sorry! Slipped my mind to add that.

We're using v1.0.0-rc2, and the whole block of implementation is:

```
            Sdk.CreateTracerProviderBuilder()
                .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("name"))
                .AddJaegerExporter(options =>
                {
                    options.AgentHost = Environment.TracingHost;
                    options.AgentPort = Environment.TracingPort;
                    options.MaxPayloadSizeInBytes = 65000; // https://github.com/jaegertracing/jaeger/issues/2638

                    options.BatchExportProcessorOptions = new BatchExportProcessorOptions<Activity>
                    {
                        MaxExportBatchSize = 256
                    };
                })
                .AddAspNetInstrumentation(options =>
                {
                    options.Enrich = (activity, eventName, rawObject) =>
                    {
                        activity.SetTag("alias", Environment.Alias);
                    };
                })
                .AddHttpClientInstrumentation(options =>
                {
                    options.SetHttpFlavor = true;
                    options.Enrich = (activity, eventName, rawObject) =>
                    {
                        if (rawObject is HttpRequestMessage request)
                        {
                            activity.SetTag("requestVersion", request.Version);
                        }
                    };
                })
                .AddSqlClientInstrumentation(
                    options =>
                        {
                            options.EnableConnectionLevelAttributes = true;
                            options.SetDbStatement = true;
                        })
                .Build();

            // The propagate is a composite of B3, W3C and Baggage, favoring B3 on extraction
            Sdk.SetDefaultTextMapPropagator(
                new CompositeTextMapPropagator(new List<TextMapPropagator>
                {
                    new B3Propagator(),
                    new TraceContextPropagator(),
                    new BaggagePropagator()
                }));
```

**Comment by cijothomas** [comment]
Since you said the repro is not consistent, we want to rule out sampling.

When the Enrich is not triggered, are you seeing telemetry for that httpclient call? Or you are seeing the telemetry for HttpClient call, but Enrich is not hit?

(To easily rule out sampling, please set AlwaysOnSampler and retry)

**Comment by naphta** [comment]
@cijothomas The enrich is consistently not being hit, and we're consistently seeing the trace from the HTTP client, sorry for not making that clear.

**Comment by cijothomas** [comment]
The following should unblock you. The 1st argument is for HttpClient, and the 2nd argument for HttpWebRequest. Its a bit confusing, and have scope of improvement.

```
.AddHttpClientInstrumentation(null, options =>
                 {
                     options.SetHttpFlavor = true;
                     options.Enrich = (activity, eventName, rawObject) =>
                     {
                         if (rawObject is HttpRequestMessage request)
                         {
                             activity.SetTag("requestVersion", request.Version);
                         }
                     };
                 })
```
