### ISSUE TITLE
Why is Processor.OnStart not called in OpenTelemetryLogger's Log method?

### ISSUE THREAD

**Issue by evgenyfedorov2** [open-telemetry/opentelemetry-dotnet#1796]
Hello,

Why is in the Log method
https://github.com/open-telemetry/opentelemetry-dotnet/blob/7687edc35064cbc0d36fd7aaaee7eef346fbabf4/src/OpenTelemetry/Logs/OpenTelemetryLogger.cs#L38

there is only a call to `this.provider.Processor?.OnEnd(record);` but no calls to  `this.provider.Processor?.OnStart()` (possibly before creating the LogRecord)?

I mean, [here ](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#processor )the following is declared:
_Processors can be used for enriching the telemetry and exporting the telemetry to an exporter. For enriching purposes, one must write a custom processor, and override the OnStart method with logic to enrich the telemetry._ 

I cannot find where OnStart method is actually called in the OTel Logger

**Comment by cijothomas** [comment]
Start/End makes sense for Traces, which has a logical start and stop (and hence, a duration as well). For logs, there is no equivalent concept.
If you can explain a bit more on what you are trying to achieve, we can try to find alternates. There is no ability to enrich the logs using Processor today. (This'll likely come as OpenTelemetry finalizes logging spec. Or Ilogger itself provides a way to enrich logs, independent of OpenTelemetry).

**Comment by reyang** [comment]
It seems we've removed `sealed` for `LoggerProcessor.OnStart()`.
`Sealed` was introduced in #1322 ([code](https://github.com/open-telemetry/opentelemetry-dotnet/blob/30f011456eceecaabea24c911ae61e4141285df6/src/OpenTelemetry/Logs/LogProcessor.cs#L26)) to prevent folks from implementing `OnStart` which is not being called. Maybe we should add it back?

**Comment by reyang** [comment]
Closing this issue since the original question has been answered by @cijothomas.
