### ISSUE TITLE
Replacement of "ProcessTags" with "Resource Attributes" in 1.0.0-rc3

### ISSUE THREAD

**Issue by secana** [open-telemetry/opentelemetry-dotnet#1797]
# How to replace "ProcessTags" with "Resource Attributes"

The release of 1.0.0-rc3 states: "Removed ProcessTags from JaegerExporterOptions. The alternate option is
to use Resource attributes."

Currently we get a list of all process tags like this:
```csharp
var dictionary = options.ProcessTags?.ToDictionary(pair => pair.Key, pair => pair.Value) ?? new Dictionary<string, object>();
```

I have no idea how to use the resource attribute here. Could you point me to a direction?

Best regards!

**Comment by cijothomas** [comment]
Any attributes added to Resource will automatically be added as process tags in Jaeger.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#resource

Agree there is scope for improving jaeger readme file to make this clear. @Austin-Tan could you see if you can add an example and modify readme to indicate how Jaeger treats Resource?

**Comment by Austin-Tan** [comment]
Sounds good, does that make sense @secana ? I’ll update the doc by the end of today.

**Comment by secana** [comment]
@Austin-Tan @cijothomas thx for the fast reply. I'll see if I get it working.

**Comment by cijothomas** [comment]
We did not modify any docs, but simply added a section to point to OTel spec - it already talks about Jaeger conversion, so didn't want to duplicate it in readme as well.
If there is additional feedback, feel free to re-open

**Comment by Sawmi** [comment]
![1619688002718](https://user-images.githubusercontent.com/83381906/116592945-c7d17880-a94a-11eb-84f3-238593ea4c9b.png)

**Comment by Sawmi** [comment]
Thanks you
