### ISSUE TITLE
W3C Format Check for JaegerExporter Improvement

### ISSUE THREAD

**Issue by kyle-lt** [open-telemetry/opentelemetry-dotnet#1799]
Working on #1487 trying to handle any TODOs in the Jaeger Exporter code, I came across this one regarding checking for W3C format in [`JaegerActivityExtensions:ToJaegerSpan`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/e0bcc80f33a31e3ddecccea566a0c207e9283cb2/src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerActivityExtensions.cs#L113).

It looks like the current behavior is to check each span for W3C format, and if it's W3C, set some `JaegerSpan` properties.  If the span is not W3C, these properties end up just keeping `Empty` values, and the JaegerSpan is returned anyway.

This method is called by [`JaegerExporter:Export`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7687edc35064cbc0d36fd7aaaee7eef346fbabf4/src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs#L81) when processing a batch of spans.

What is the recommended behavior?

Should we check for W3C format in the `Export` method's [`foreach`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7687edc35064cbc0d36fd7aaaee7eef346fbabf4/src/OpenTelemetry.Exporter.Jaeger/JaegerExporter.cs#L79) loop, and if not W3C, discard the batch and log a message, and return a `Failure`? It seems that the [opentelemetry-spec for ExportBatch](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#exportbatch) would expect that type of behavior.

Just looking for some direction on what the ideal implementation should be and then happy to work on it.

**Comment by martinjt** [comment]
The Jaeger exporter has moved to the contrib repo now. However, since Jaeger now supports OpenTelemetry Protocol ingest, the recommendation is to use the OTLP exporter.

If think this should still be addressed, please add a ticket to contrib.

**Comment by cijothomas** [comment]
> The Jaeger exporter has moved to the contrib repo now

Its actually not moved anywhere. Its removed completely from the repo.
