### ISSUE TITLE
Inconsistency between Link and Event

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-dotnet#1806]
Currently there is a Link class but not an Event class, I think would be good to have them consistent and either go with classes or just APIs (like Event) to record these things.

**Comment by cijothomas** [comment]
Runtime exposes both ActivityEvent and ActivityLink as dedicated structs.
In Otel.API, we did not explicitly provide ActivityEvent wrapper, as span.AddEvent() was sufficient to cover the scenario. (Wrapper for ActivityLink was provided, as Links can only be provided at StartSpan() call)

Not blocking 1.0, additive change can be added anytime after.
