### ISSUE TITLE
ZPages is currently marked as experimental in the specification. 

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-dotnet#1807]
Is there a easy way to have this marked as experimental in this repo, so if breaking changes are added to that will not force a major version bump?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/VERSIONING.md#core-components Only the core components are ready to go 1.0.0
Zpages is not in the list of 1.0.0 release and will remain pre-release.
