### ISSUE TITLE
In the specs we say that it is better to use the Key/Slot when retrieving values from context

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-dotnet#1809]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Context/RuntimeContext.cs#L128

See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/context.md#get-value

**Comment by cijothomas** [comment]
For this issue and related one https://github.com/open-telemetry/opentelemetry-dotnet/issues/1810, we have triaged this to be addressed post 1.0
Agree its a bug, but making last minute changes to 1.0 is less appealing.

**Comment by martinjt** [comment]
It looks like this has been addressed now.
