### ISSUE TITLE
B3Propagator should not be in the API

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-dotnet#1812]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/044ba3ecd6332001fdff43237c7ea9e96aa87c12/src/OpenTelemetry.Api/Context/Propagation/B3Propagator.cs

See specs
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution

**Comment by cijothomas** [comment]
Thanks for catching this bug.
As decided in the Otel.NET Sig meeting on Feb9, we will address this post 1.0. As this propagator was part of the main package for all the rc releases, and we want to avoid breaking users.

**Comment by alanwest** [comment]
Closing as B3 propagator has been marked obsolete in the API package and we have a new issue for reminding us to remove it in the next major version #3259
