### ISSUE TITLE
Consider to remove withSpan from Tracer, no helper, same one line call Span.Activate()

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-dotnet#1813]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/044ba3ecd6332001fdff43237c7ea9e96aa87c12/src/OpenTelemetry.Api/Trace/Tracer.cs#L63

**Comment by martinjt** [comment]
Needs more context if we're going to action this.
