### ISSUE TITLE
Consider having a TelemetrySpan.Current() instead of Tracer.CurrentSpan()

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-dotnet#1814]
Specs do not require anymore having CurrentSpan/WithSpan on the tracer, and the API can be improved and have the same look and feel as the Activity by moving this to the TelemetrySpan -> `TelemetrySpan.Current()` and `TelemetrySpan.Activate()`

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Trace/Tracer.cs#L41

**Comment by martinjt** [comment]
The API has changed a lot in the last 2 and half years and is now GA, I'm closing this, but if you feel strongly it should be reconsidered, feel free to reopen it.
