### ISSUE TITLE
Will instrumentation code be released as "stable" at 1.0?

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-dotnet#1815]
I don't know how your build/release process works, but I see instrumentation code side-by-side with API code in this repository, which makes me think that everything in here might get the same version number at release. At the moment, OpenTelemetry isn't providing any stability guarantees around semantic conventions, so you need to make sure that instrumentation code isn't released as "stable" until that happens.

If you're not releasing instrumentation with stability guarantees at 1.0, then 👍  and you may ignore me. :)

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/VERSIONING.md#core-components Only core componets are going 1.0
Instrumentation's remains pre-release, until spec marks semantic conventions as stable.

**Comment by cijothomas** [comment]
Incase you are curious, the tool we use is MinVer https://github.com/adamralph/minver, and this PR marked core components separately from others: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1774

**Comment by jkwatson** [comment]
Cool, thanks!
