### ISSUE TITLE
Baggage propagation quesiton

### ISSUE THREAD

**Issue by ajsaclayan** [open-telemetry/opentelemetry-dotnet#1816]
# Question
Hi all,
I'm new to the OpenTelemetry community. I'm trying to understand how context gets propagated across different systems.

**Describe your environment.**
I'm running this [example](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/MicroserviceExample)  locally in docker.
Describe any aspect of your environment relevant to the question.

**What are you trying to achieve?**
 I've been playing around with the Microservices example, and I'm unable to propagate baggage to the consumer.
In the producer activity, I added some arbitrary baggage that I would expect to get injected into the RabbitMQ message. https://github.com/ajsaclayan/opentelemetry-dotnet/commit/d6d8cfbce2418b672728c1fc4e94417348a8caae
What did you expect to see?
I don't see baggage on the exporter end
![image](https://user-images.githubusercontent.com/55757302/107287947-50193f00-6a28-11eb-97cf-4e37402c6b1f.png)
## Additional Context

I also viewed the traces in the console exporter, and I do see the baggage on the producer side, but it is not being propagated to the receiver.

**Comment by cijothomas** [comment]
> I don't see baggage on the exporter end

Could you clarify this a bit more? were you expecting to see Baggage tags inside the Activity itself, and exported? Baggage is not added to `Activity` by default.

**Comment by ajsaclayan** [comment]
Hi @cijothomas,

I added a Baggage property on the Activity that captures sending the message to the queue [here](https://github.com/ajsaclayan/opentelemetry-dotnet/commit/d6d8cfbce2418b672728c1fc4e94417348a8caae). 

It looks like baggage gets injected to the message in this [line](https://github.com/ajsaclayan/opentelemetry-dotnet/blob/d6d8cfbce2418b672728c1fc4e94417348a8caae/examples/MicroserviceExample/Utils/Messaging/MessageSender.cs#L80).

I would expect the receiver to extract the baggage, and it would be visible in the Zipkin exporter. This isn't the case though.

I've tried this similar [logic](https://github.com/ajsaclayan/opentelemetry-dotnet/blob/d6d8cfbce2418b672728c1fc4e94417348a8caae/examples/MicroserviceExample/Utils/Messaging/MessageReceiver.cs#L61-L62)in a console application, but the Activity on line 68 doesn't contain any baggage. Are you saying I need to add the baggage from `parentContext.Baggage` within the Activity?

**Comment by utpilla** [comment]
Hi @ajsaclayan,

The exporters won't display Baggage information as Baggage is not tied to an activity. ConsoleExporter is incorrectly showing Baggage information. You can access the Baggage information in the `OnStart` and `OnEnd` methods of the processors. So you could add a [custom processor](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#processor) which can access the Baggage information that was propagated. You could read the Baggage information using `Baggage.Current`.

`Activity.AddBaggage` is not the right way to add Baggage. The correct way to add Baggage is by using `AddBaggage` method on `Baggage.Current` which holds the current baggage information to be propagated. For e.g.: 
```
Baggage.Current.SetBaggage("AppName", "MyApp");
```

**Comment by cijothomas** [comment]
Closing as the above comment should clarify the original questions.
See related: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1842

**Comment by bmcclory** [comment]
I think the relationship between Activity.Baggage and OTEL Baggage needs some improvement.

I understand that "Baggage is not tied to an Activity" in OTEL, which is evidently why OTEL .NET felt it necessary to establish a standalone Baggage API and discourage use of Activity.Baggage.

But there's existing machinery in the runtime -- legacy diagnostics stuff in ASP.NET Core and HttpClient -- that propagate W3C baggage headers via Activity.Baggage. Without OTEL in the picture, applications can do `Activity.AddBaggage` and `Activity.GetBaggageItem` and it just works.

When OTEL enters the picture things get super confusing.  On the receiving side in an ASP.NET Core app, both  Activity.GetBaggageItem or Baggage.GetBaggage work, whether I'm using OTEL Tracing or not.  

On the sending side, I can use Activity.AddBaggage and propagation works... as long as the OTEL Baggage is empty? As soon as I add a single Baggage item -- either directly in instrumented app, or automatically using something like OTEL's AspNetCoreInstrumentation -- then the HttpClientInstrumentation will ignore the Activity.Baggage and favor OTEL Baggage. 

I don't know the solution here, but lost Baggage sucks (insert airline jokes here). Maybe OTEL's Baggage API should at least sync its contents into Activity.Baggage?

**Comment by MithunChopda** [comment]
Hi @ajsaclayan,
But that still doesn't address the problem. Using Baggage API also adds the Baggage to Activity.Baggage. But the Baggage values are not appearing in Console and OTLP Exporter both. I am using the Aspire dashboard.
