### ISSUE TITLE
Consider removing StartActiveSpan

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-dotnet#1818]
In a block like this, it becomes easy _not_ to report errors, in a similar fashion to how it happens for Java:

```cs
using (var span = tracer.StartActiveSpan(...)) {
  // span fails, there's no way to report errors on it,
  // even though the span is deactivated properly.
}
```

Even if this is something that proves to be useful, it can be added later on.

**Comment by martinjt** [comment]
The API is now GA, so we can't remove things really, I'm going to close this for now, feel free to reopen if you feel it's important enough to consider for a V2.
