### ISSUE TITLE
Feedback request: adding engine definition to semantic conventions - beneficial to .NET community?

### ISSUE THREAD

**Issue by ivomagi** [open-telemetry/opentelemetry-dotnet#1839]
# Question

As the author of the PR https://github.com/open-telemetry/opentelemetry-specification/pull/1293 I am reaching out to .NET community to get feedback about whether or not the concept of `engine` introduced in the PR will or will not add value to .NET tracing. So if you take a look at the usecases described in the PR and comment about if and how this would also apply to .NET world. 

**What are you trying to achieve?**

Based on the feedback from other communities, a decision will be made whether the concept of `engine` is applicable as a generic semantic convention or it will be specific to Java.  

## Additional Context

The original PR clearly benefits the JVM community, which relies heavily on different Java EE application servers.  The question is asked to see where the .NET community stands in regards of the value of the information being exposed.

**Comment by carlosalberto** [comment]
Ping @open-telemetry/dotnet-approvers

**Comment by CodeBlanch** [comment]
I put my thoughts on the spec PR here: https://github.com/open-telemetry/opentelemetry-specification/pull/1293#issuecomment-771102424

Summary: IMO I don't think trying to capture the webserver is worthwhile for .NET, might not even be possible in all cases, but pushing the runtime version as `engine` I could see as being useful to some users.

**Comment by cijothomas** [comment]
Closing. The related spec PR has since merged.
