### ISSUE TITLE
Baggage API vs Activity.Baggage

### ISSUE THREAD

**Issue by roederja2** [open-telemetry/opentelemetry-dotnet#1842]
# Question
It's not clear to me what exactly the relationship is between Activity.Baggage and the *new* Baggage API. It seems initially OpenTelemetry Baggage was implemented using Activity.Baggage and then it was changed again. I'm adding OpenTelemetry support to my RPC library and I'm wondering why/if I need to pass around activities and baggage when activity seems to contain baggage.

**Comment by cijothomas** [comment]
`Activity.Baggage` does not conform to the OpenTelemetry concept of `Baggage`. (it existed even before OpenTelemetry).
If you are interested in using `Baggage` as per OpenTelemetry, then use the `Baggage` API from `OpenTelemetry.API` package.
