### ISSUE TITLE
Setting Activity tag with a String Array which contains a null crashes the application.

### ISSUE THREAD

**Issue by bera-josh-jewell** [open-telemetry/opentelemetry-dotnet#1843]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

* OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation
** Pulled the latest code on 2/22/2021 

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):
* netcoreapp3.1

## Symptom

The Open Telemetry Library is crashing our application. Bad serialization brings down the whole process.

**What is the expected behavior?**

The application should not crash

**What is the actual behavior?**

the application crashes

## Reproduce

Just including code since I think it's a straightforward error to create.
`var crashingArrayExample = new string[1]{ null };
using var activity = new ActivitySource(_activitySourceName).StartActivity("ProcessQuery");
activity?.SetTag("filterTables", crashingArrayExample);`

This code expects item to not be null:
`case string[] stringArray:
                        foreach (var item in stringArray)
                        {
                            PooledList<OtlpCommon.KeyValue>.Add(ref this.Tags, CreateOtlpKeyValue(key, new OtlpCommon.AnyValue { StringValue = item }));
                        }`

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by cijothomas** [comment]
@Austin-Tan Can you take a look at this?

**Comment by Austin-Tan** [comment]
Resolving this by aligning our restrictions on [Attribute values with the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md). Only making the change for OTLP and only for string[] since the primitive arrays check for null at compile time whereas this doesn't.
In accordance with spec, we will change null strings to the empty string.

**Comment by Austin-Tan** [comment]
Addendum to last comment, we can allow null values to be exported in OTLP for all supported array types.
