### ISSUE TITLE
Unable to create dependency graph file for project

### ISSUE THREAD

**Issue by Awawdi** [open-telemetry/opentelemetry-dotnet#1861]
# Question

**Describe your environment.**
.NET Framework 4.7.2

Describe any aspect of your environment relevant to the question.

**What are you trying to achieve?**
dotnet add package OpenTelemetry.Instrumentation.AspNet

What did you expect to see?

dotnet add package OpenTelemetry.Instrumentation.AspNet
C:\Users\a_aor\source\repos\WebApplication2\WebApplication2\WebApplication2.csproj(89,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\5.0.102\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\5.0.102\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.
Unable to create dependency graph file for project 'C:\Users\a_aor\source\repos\WebApplication2\WebApplication2\WebApplication2.csproj'. Cannot add package reference.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>

Arguments:
  <PROJECT>        The project file to operate on. If a file is not specified, the command will search the current directory for one.
  <PACKAGE_NAME>   The package reference to add.

Options:
  -h, --help                          Show command line help.
  -v, --version <VERSION>             The version of the package to add.
  -f, --framework <FRAMEWORK>         Add the reference only when targeting a specific framework.
  -n, --no-restore                    Add the reference without performing restore preview and compatibility check.
  -s, --source <SOURCE>               The NuGet package source to use during the restore.
  --package-directory <PACKAGE_DIR>   The directory to restore packages to.
  --interactive                       Allows the command to stop and wait for user input or action (for example to complete authentication).
  --prerelease                        Allows prerelease packages to be installed.

## Additional Context

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.

**Comment by martinjt** [comment]
The command there is missing `--prerelease`, but other other than I think this has been addressed as we've had no recent reports of it. If it persists, please reopen the issue!
