### ISSUE TITLE
Limiting baggage propagation to external services

### ISSUE THREAD

**Issue by rgmills** [open-telemetry/opentelemetry-dotnet#1866]
# Question

**Describe your environment.**

In our environment, we communicate with both internal and external vendor APIs (AWS and integration partners).

**What are you trying to achieve?**

What I'd like to be able to do is ensure Baggage is not included when communicating to external vendor APIs.  I'm curious what the best practice is for doing this.  I see two potential options (and there very well may be more, but I'm still new to this area).

1. Implement a derived class of `BaggagePropagator` and override `Inject<T>`.  One can test `T` for `HttpRequestMessage` and choose not to call `base.Inject` if it doesn't meet some criteria.
2. When configuring HttpClientInstrumentation, remove the `Baggage` header in a supplied `Filter` implementation.  Definitely goes against the intent of `Filter`

## Additional Context

Didn't really find anything else.

**Comment by cijothomas** [comment]
Option1 is doable and don't see anything wrong with that. If you have trouble implementing this, let us know here.
You may want to ask for guidance from the spec repo as well, as this is not just a .NET specific issue.

**Comment by rgmills** [comment]
Thanks, @cijothomas
