### ISSUE TITLE
SelfDiagnostic does not emit output with EventLevel.LogAlways

### ISSUE THREAD

**Issue by tbolon** [open-telemetry/opentelemetry-dotnet#1868]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

* main 7da935e237fafdd93d49de27888ca96863a5dc24

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):

* net48

## Symptom

I enabled self diagnostic and set the LogLevel to `LogAlways` because I was debbuging some internal bahavior and wanted all events.

**What is the expected behavior?**

The app should log all events.

**What is the actual behavior?**

No events are logged.

## Reproduce

1) Create a self diagnostic config with LogLevel to LogAlways
2) Start the app
3) Open the log files : only the `Successfully opened file.` is shown

## Additional Context

The problem resides in [SelfDiagnosticsConfigRefresher](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Internal/SelfDiagnosticsConfigRefresher.cs#L162): the code only enable log if level is different from previous.

The problem is that the current level field `logEventLevel` is initialized with [default enum value](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Internal/SelfDiagnosticsConfigRefresher.cs#L61) which is 0, and is mapped to LogAlways.

A possible fix could be to initialize the `logEventLevel` with an incorrect value (-1) so the first check will always be true.

**Comment by reyang** [comment]
@xiang17
