### ISSUE TITLE
Run benchmark tests for using activity.CustomProperty vs activity.TagObjects to keep track of activity created by ASP.NET and ASP.NET Core instrumentations

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet#1887]
We need to run benchmark tests to ensure that we are using the most performant approach to keep track of whether the activity in the listener is created by instrumentation or not.

ASP.NET / ASP.NET Core instrumentations create a new activity in the `OnStartActivity` method and use activity.CustomProperty to keep track of it. The CustomProperty is later looked up in the `OnStopActivity` method of the listener to stop the activity.

This could also be achieved using Tags instead of CustomProperties. We need to run benchmark tests to know which is the more performant approach.

**Comment by vishweshbankwar** [comment]
We switched to SetTag(not able to find the PR, assuming it was done after running benchmark). Closing this issue.
