### ISSUE TITLE
Extending the OpenTelemetry not possible, due to classes marked as "internal"

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [open-telemetry/opentelemetry-dotnet#1898]
I am trying to extend the OpenTelemetry by building my own Instrumentation library.

Currently, this is not easy to do, as some of the necessary classes I need to use/extend such as ListenerHandler, ActivitySourceAdapter, DiagnosticSourceSubscriber, DiagnosticSourceListener are marked as internal, so I cannot use/inherit from these.

If possible, can these building block type classes, etc, be marked as public, to make the library more extensible?

**Comment by cijothomas** [comment]
Please take a look at this: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#writing-own-instrumentation-library

(a lot has changed in this area in the last few weeks, I hope the above doc make it easy for you. If not, we could use some feedback to improve)
