### ISSUE TITLE
Support OpenTelemetry protocol and agent exporter

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#19]
Find protos here: https://github.com/open-telemetry/opentelemetry-java/tree/master/sdk/src/main/proto

**Comment by trwegner** [comment]
Also should update src\OpenTelemetry.Exporter.Ocagent\Implementation\SpanDataExtentions.cs#39 with producer and consumer span types in the new protos

**Comment by austinlparker** [comment]
fyi the protos are in https://github.com/open-telemetry/opentelemetry-proto now

**Comment by austinlparker** [comment]
One thing I've wondered, would it make sense to publish the generated proto code out of that repo rather than importing it to this one as a submodule or so forth?

**Comment by SergeyKanzhelev** [comment]
I have very little experience with submodules. Every time I tried it was not a streamline thing. It always took more time to fix tooling than simple copying of rarely updated files take. And shipping a hotfix that only addresses a single issue and only need one of many changes is impossible.

If you have good examples where this approach worked just fine - I'm happy to try again and learn.

**Comment by austinlparker** [comment]
I've found submodules to be unwieldy as well - we can just copy files around for now I reckon.

**Comment by pcwiese** [comment]
Have feelings changed about how to proceed with these .proto files? At the very least a reference to a commit from the proto repo is necessary. We could copy the .proto files over and generate as part of the build of this project I think. No need to check-in the intermediate g.cs files.

**Comment by SergeyKanzhelev** [comment]
Java went submodule way: https://github.com/open-telemetry/opentelemetry-java/tree/master/proto/src/main We can try the same

**Comment by SergeyKanzhelev** [comment]
I don't have strong feelings

**Comment by pcwiese** [comment]
Ugh. submodules sounds nice in principle and a bit nasty in practice. I'll make a copy of the files.

**Comment by SergeyKanzhelev** [comment]
As discussed on Gitter, @pjanotti assigning this to you

**Comment by cijothomas** [comment]
This should be complete now. @pjanotti Can you confirm and close this?

**Comment by pcwiese** [comment]
We are still missing the instrumentation library in the exports...

**Comment by cijothomas** [comment]
@eddynaka please check if the instrumentationlibrary info is missing in the otlp exporter.

**Comment by cijothomas** [comment]
> We are still missing the instrumentation library in the exports...

This is because ActivitySource is blank for those DiagnosticSourceInstrumentation activities. One proposed fix would be to modify the legacy activity with correct ActivitySource.

**Comment by cijothomas** [comment]
This work is complete. The lack of InstrumentationLibrary info is a bug in the instrumentations, not an exporter. Closing this.
