### ISSUE TITLE
Creating child spans

### ISSUE THREAD

**Issue by satishviswanathan** [open-telemetry/opentelemetry-dotnet#1918]
# Question

**How to add a child span?**

**Environment**

Web API developed in Dotnet 5 
Background service developed in Dotnet 5

**Trying to connect a WebApi request with a background service process**
**I have a Web API request which drops in a message to queue like RabbitMQ and this message will be picked up by the background service and process it. So basically i'm trying to see if there is a way to connect both the API and background request and the backround service request should be a child span of the main Api request. As a first step I have the OnStartActivity event implemented which captures the trace id and will be part of the message send to the background service. Now I'm trying to find a way how the background service create a new child span using the trace id**

What did you expect to see?

**Background service request needs to be shown as a child span of the API request**

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/MicroserviceExample/Utils/Messaging/MessageReceiver.cs Please check this example

**Comment by satishviswanathan** [comment]
Thank you @cijothomas  for sharing the example. 

When I try to start an Activity from where I publish by message I see the Activity is always null. I was checking the documentation and found the below.

"If there are no listeners interested in this activity, the activity above will be null. This happens when the final application does not enable OpenTelemetry (or other ActivityListeners), or when OpenTelemetry samplers chose not to sample this activity. Ensure that all subsequent calls using this activity are protected with a null check."

Not sure what I'm missing. Currently for me the send message and receive message is not being captured.

**Comment by cijothomas** [comment]
1. Make sure ActivitySource you are using for creating Activity is added to TracerProvider (`AddSource()`)
2. Set Sampler to AlwaysOn() to rule out anything related to sampling.

**Comment by satishviswanathan** [comment]
Thank you @cijothomas that worked. Appreciate your help.
