### ISSUE TITLE
"Signed 64 bit integer" Attribute is interpreted as Int rather than long in OTLP

### ISSUE THREAD

**Issue by Austin-Tan** [open-telemetry/opentelemetry-dotnet#1931]
The fix (if necessary) should be accomplishable with a short PR but creating an issue to track in case.

# Question

The [spec on attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md) asks for "A primitive type: string, boolean, double precision floating point (IEEE 754-1985) or signed 64 bit integer." or array of such primitive. 

Looking at [how we process tags in spans for OTLP](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs) we are looking instead at the types string, boolean, double, and Int (which in .NET is 32 bit instead of 64) instead of long. There's a small switch case to convert longs into ints and accessible from "IntValue", but I think it gives the impression that 32-bit ints are the natively supported type instead of 64 bits, and loses precision.

## Additional Context

Need to check if other exporters similarly use int over long.
Am currently working on a PR #1919  specifically about nullable types here to address issue #1843  but a follow up one after seems meaningful to me.

**Comment by cijothomas** [comment]
int_value is int64 in proto, and it'd be long in the generated classes as well.
https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L33

**Comment by Austin-Tan** [comment]
#1919 was merged which fixes this
