### ISSUE TITLE
OpenTelemetry.Instrumentation.StackExchangeRedis memory leak on _cache

### ISSUE THREAD

**Issue by jessica-mottner-cko** [open-telemetry/opentelemetry-dotnet#1943]
# Bug Report

Nuget Packages:
* `OpenTelemetry.Api 1.1.0-beta1`
* `OpenTelemetry.Instrumentation.StackExchangeRedis 1.0.0-rc3`

Runtime version: `netcoreapp3.1`

## Symptom

It looks like there is a memory leak on the `OpenTelemetry.Instrumentation.StackExchangeRedis` library where the cache would not flush properly: [StackExchangeRedisCallsInstrumentation Flush Method](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentation.cs#L128-L143)

![image](https://user-images.githubusercontent.com/45169343/112835692-8753b600-9091-11eb-99ce-d549e545d95b.png)

I am wondering if it's just a matter of removing the entry from the cache after draining the profiling session. 

## Reproduce

I created this [Sample API](https://github.com/jessica-mottner-cko/test-redis-instrumentation) to reproduce the issue.

## Additional Context

I could not reproduce the issue in a single-threaded context: the _bucket would not show any items.

**Comment by austinlparker** [comment]
I wonder if I ran into the issue you ran into - trying to run your repro case didn't give me any extra allocations(although zipkin did die with an OOM error after about a minute). Only real difference I can think of would be .NET version, as I've got .NET 5 installed?

**Comment by jessica-mottner-cko** [comment]
Could it not be that the `_cache` needs cleaning after the DrainSession instruction? As far as I could see, we add entries but we never remove them? 
```csharp
this.cache.TryRemove((entry.Key.TraceId, entry.Key.SpanId), out _);
```
If this is what is missing, both single and multi-threading would be impacted, it was just more visible for the latter during my tests.

**Comment by eddynaka** [comment]
@jessica-mottner-cko , adding that might fix the behavior that you are seeing. Pls, open a PR and make a test checking the this.cache if that is empty after disposing/flushing.

**Comment by carlosalberto** [comment]
I definitely think entries are not being removed at all from `cache` (which is a private field *and* I see no reference to it anyway from any other component). 

As @eddynaka suggested, it's worth cooking a PR with the aforementioned change (`TryRemove()`, etc)

**Comment by JM89** [comment]
Thanks all for your answers, the [PR](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1960) has been reviewed and is awaiting merge.

**Comment by cijothomas** [comment]
Closing as the PR associated is merged. The changes are available in myget feed already, and will be doing nuget release along with rest of packages this week.
