### ISSUE TITLE
Treatment of unsupported attribute values -- ToString() vs Don't Accept

### ISSUE THREAD

**Issue by Austin-Tan** [open-telemetry/opentelemetry-dotnet#1946]
# Context

The [specification for Resource attributes and Span tags](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes) name only string and primitive arrays and variables as valid for export. 

In Otlp, we currently call [ToString()](https://github.com/open-telemetry/opentelemetry-dotnet/blob/efe2d96c3c46449310cb8a3c698f84131b101aee/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs#L232) on values that don't fall within an accepted type.

Relying on the system's .ToString() calls may also lack clarity for users, such as in how this nullable long array (unsupported) is shown here:
![image](https://user-images.githubusercontent.com/29290481/112965579-3e861680-90fe-11eb-9865-92aa57145003.png)

# Question
@cijothomas and I discussed this previously but am interested in hearing further thoughts before a PR. We could throw an exception or silently discard the attribute.

**Comment by cijothomas** [comment]
It'd be correct to ignore any tags whose value is not in one of the supported list.
(FYI: the root of the issue is `activitySetTag(string, obj value)` allowing object as the value.)
