### ISSUE TITLE
Relationship with Prometheus.NET and Serilog

### ISSUE THREAD

**Issue by dropsonic** [open-telemetry/opentelemetry-dotnet#1955]
# Question
What is the relationship between OpenTelemetry and a typical configuration with Prometheus.NET + Prometheus/Grafana for metrics and Serilog + ELK stack for logging, where Serilog is configured to be used with `Microsoft.Extensions.Logging`?
Should I use one over the other or in some combination?

**Comment by ElectricVampire** [comment]
I am also looking for answer of above question. I am using Serilog for logging - I enrich all the logs with TraceID and SpanID of Http Request. I am using Prometheus.NET to collect metrics.
How do I leverage OpenTelemetry.NET in this setup?

I also have one more problem- 
I receive messages from Third Party MF system to my kafka queue. Each message has its own unique id. There is .Net core kafka message processor which reads message from Queue and call a multiple Web Apis.
How do I assign unique Id of message to System.Diagnostics.Activity.TraceID in Kafak .Net processor, so any HttpClient call made from this exe to any API get that copied over via request headers.

Alternatively please also let me know if I am approaching the problem in wrong way and there is already a standard solution for this kind of problem.

**Comment by clarkezone** [comment]
I'm interested in the related question of how i can use opentelemetry.net with Loki for logs

**Comment by queil** [comment]
@clarkezone As for Loki, OpenTelemetry.NET, and Serilog (unless you've already figured it out). I think the desired solution would be to have an OpenTelemetry-Collector endpoint that Serilog pushes logs to via a compatible serilog sink (from what I could see there is no open-source package that would do that). Then you can have a Loki exporter configured in your OpenTelemetry-Collector.

**Comment by cijothomas** [comment]
> relationship between OpenTelemetry and a typical configuration with Prometheus.NET + Prometheus/Grafana

OpenTelemetry Metrics API (for .NET, it is packed into System.Diagnostics.DiagnosticSource package from runtime itself), is vendor/backend neutral. You may export to Prometheus or any other backends, without changing instrumentation code.

On the other hand, using Prometheus .NET, ties you to Prometheus backend.

You can still use Grafana in either approach, but OpenTelemetry approach is more neutral, and hence we (obviously!) recommend this route :)

**Comment by cijothomas** [comment]
1. One of the OpenTelemetry's mission to provide vendor/backend agnostics instumentation API. So if you use OTel API - then you can switch backends without changing instrumentation side.
2. OpenTelemetry is still evolving, so may not have all the features as other existing solutions have.
3. If there are more questions about OpenTelemetry, please open specific issues, to get guidance from others.

Closing this issue, as the original question has been answered. Please consider opening a new discussion thread, for more clarifications, if needed.

**Comment by liammclennan** [comment]
In case anyone else finds this thread, please note that Serilog does have an OpenTelemetry sink that can send logs to any OTLP logging backend.

**Comment by liammclennan** [comment]
There is also [work underway](https://github.com/serilog-tracing/serilog-tracing) to add hierarchical, distributed tracing to Serilog.
