### ISSUE TITLE
Is it possible to use OpenTelemetry in NET Framework based applications?

### ISSUE THREAD

**Issue by Oleg26Dev** [open-telemetry/opentelemetry-dotnet#1956]
I'd like to use the OpenTelemetry in my WCF Service, WinForms applications. All of them are NET F 4.5 based.
Is it possible to use? What are restrictions and limitations?

**Comment by cijothomas** [comment]
If the app is using a supported versions of .NET (https://github.com/open-telemetry/opentelemetry-dotnet#supported-net-versions), then it is possible to use. For .NET Framework, the minimum supported version is .NET452, so i your app is .NET45, then its not supported.

**Comment by cijothomas** [comment]
There is an instrumentation for WCF in the contrib repo, which would be helpful, (but only if app is running .net452 minimum)
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Instrumentation.Wcf

**Comment by Oleg26Dev** [comment]
Ok, thank you. It is not a problem  for me to rebuild my apps with NET 4.6
