### ISSUE TITLE
Can OpenTelemetry be replacement  for Log4net?

### ISSUE THREAD

**Issue by Oleg26Dev** [open-telemetry/opentelemetry-dotnet#1957]
I use log4net in my WCF and WinForms applications for logging. 
Can I replace log4net with OpenTelemetry for logging and also use it for tracing?

**Comment by cijothomas** [comment]
There is no Logging API in OpenTelemetry yet. (it may never come as well).
Instead this repo provides a ILogger provider, which can work *if* you use `ILogger` API. Indirectly this means, Otel .NET recommends using `ILogger` from .NET itself as the logging API.

To the question, yes Otel can be used for collecting logs and traces, provided you use the ILogger and Activity API respectively/

**Comment by sit-md** [comment]
I think instead of replacing log4net a better approach might be to write an appender for OpenTelemetry. That would also have the advantage that all the other scenarios other appenders cover continue to work.

**Comment by vmandic** [comment]
> I think instead of replacing log4net a better approach might be to write an appender for OpenTelemetry. That would also have the advantage that all the other scenarios other appenders cover continue to work.

Id second on this as I am trying to figure out if there is a way to generate TraceId (and other W3C standard telemetry data like traceparent, tracestate) and push it to log4net context somehow. If anyone has an idea that'd be great.

**Comment by HaroonSaid** [comment]
@vmandic - have you tried injecting `System.Diagnostics.Activity.Current` into `log4net.LogicalThreadContext` ?

**Comment by vmandic** [comment]
> @vmandic - have you tried injecting `SpanId` or 'TraceId`into `log4net.LogicalThreadContext` ?
> 
> ```
> logicalThreadContext.Properties["spanid"] = SpanId;
> ```

Yup, that would be it literally. I've actually opted for the full solution with a HttpModule to do this. Sample is here: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/AspNet
