### ISSUE TITLE
When is OpenTelemetry.Extensions.Hosting 1.0.1 release date?

### ISSUE THREAD

**Issue by guitarrapc** [open-telemetry/opentelemetry-dotnet#1959]
# Question

**What are you trying to achieve?**

I want to use OpenTelemetry.Extensions.Hosting but it is still 1.0.0-rc3, therefore could not mix with OpenTelemetry.XXXX 1.0.1 packages.
Any release plan date is appreciated.

**Comment by cijothomas** [comment]
We don't have an ETA yet. It's received some improvements recently, will allow some time to bake the new features.
Will update when we have an ETA for it.
(Unlike instrumentations, which is dependent on the spec being stable, Ext.hosting has no external dependency. So only blocker is fixing known issues, and giving enough bake time before making stable release) Thanks for your patience.

**Comment by cijothomas** [comment]
Just realized that we didn't release this package with the new capabilities :D.
Will do a release of it soon. (like an rc4, not stable.)

**Comment by guitarrapc** [comment]
Sounds very nice, waiting for rc4.

**Comment by lukasz-pyrzyk** [comment]
@cijothomas do you have any plans for creating a stable release of the non-core components? Is it somehow related to the metrics 1.2.0 release?

**Comment by lukasz-pyrzyk** [comment]
Sorry, I got the nomenclature wrong. By mentioning `Collectors` I wanted to say `Instrumentation` libraries, like `Instrumentation.AspNetCore` or `Instrumentation.Http`. It looks like these are the last packages that are not yet stable in any version, what is a blocker for us. Can we expect a stable release sometime soon or do we need to wait for https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace/semantic_conventions#trace-semantic-conventions to become `Stable`?

**Comment by cijothomas** [comment]
> Sorry, I got the nomenclature wrong. By mentioning `Collectors` I wanted to say `Instrumentation` libraries, like `Instrumentation.AspNetCore` or `Instrumentation.Http`. It looks like these are the last packages that are not yet stable in any version, what is a blocker for us. Can we expect a stable release sometime soon or do we need to wait for https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace/semantic_conventions#trace-semantic-conventions to become `Stable`?

They won't be released as stable until semantic conventions get declared stable.
