### ISSUE TITLE
`Baggage` header should be lowercase

### ISSUE THREAD

**Issue by Rast1234** [open-telemetry/opentelemetry-dotnet#1967]
# Bug Report

Currently `BaggagePropagator` [works with header called `Baggage`:](https://github.com/open-telemetry/opentelemetry-dotnet/blob/0e8b423bef99f846f0a4412dc37532bce610dfdd/src/OpenTelemetry.Api/Context/Propagation/BaggagePropagator.cs#L31)

```
        internal const string BaggageHeaderName = "Baggage";
```

[Specification explicitly states](https://w3c.github.io/baggage/#header-name) that header name is `baggage` (all lowercase).

Currently propagator works for HTTP since headers are case-insensitive, but it can not be used as-is for, say, RabbitMQ. We have to do `.ToLower()` when getting or setting the value.

**Comment by kipwoker** [comment]
There was also a similar conversation: https://github.com/dotnet/aspnetcore/pull/28328

**Comment by cijothomas** [comment]
Fixing this *might* be considered breaking behavior, but this can be treated as a bug in original release, and hence can be fixed.

**Comment by cijothomas** [comment]
Will do 1.1.0 release addressing this. (and not 1.0.1 hotfix)
