### ISSUE TITLE
Getting Baggage in a custom exporter

### ISSUE THREAD

**Issue by BadriL** [open-telemetry/opentelemetry-dotnet#1968]
# Question
How do I access the Baggage from the `Export` method of the class deriving from `BaseExporter<Activity>`? The export method receives `Batch<Activity>` but I want to be able to access the baggage corresponding to the activity. Obvioulsy, I'm not adding the baggage items to the activity since "OpenTelemetry users should not use the method AddBaggage on Activity.".

The workaround I'm thinking is to have a custom processor (deriving from `BaseProcessor<Activity>`) that overrides OnEnd to take baggage items from `Baggage.Current` and adding them to the activity so that I can get the baggage items from the activity in the `Export` method.

**Describe your environment.**
Windows 10, VS 2017. Creating the custom exporter as .NET std lib.

Describe any aspect of your environment relevant to the question.
None

**Comment by utpilla** [comment]
@BadriL You could use `Baggage.Current` inside of the `Export` method too.

**Comment by BadriL** [comment]
Thanks for the reply. I'm just curious. When the 'Export' method gets called, we get a bunch of activities passed in. Would we get activities (spans) across different traces in one call or is it guaranteed that the activities we receive in a single call will always be part of a single trace? If former, looking at `Baggage.Current` may not make sense? Anyways, `Baggage.Current` is always null for me inside the `Export` method. However, in the `OnEnd` overridden method of my custom processor, `Baggage.Current` does have the correct key value pairs.

**Comment by cijothomas** [comment]
Baggage.Current must be only used inside a custom Processor, (and NOT inside exporter as depending on the actual exporting processor, the context may not be current).
Anything you require from Baggage, copy it into Activity.SetTag.

**Comment by cijothomas** [comment]
> The workaround I'm thinking is to have a custom processor (deriving from BaseProcessor<Activity>) that overrides OnEnd to take baggage items from Baggage.Current and adding them to the activity so that I can get the baggage items from the activity in the Export method.

This is right.

**Comment by utpilla** [comment]
> @BadriL You could use `Baggage.Current` inside of the `Export` method too.

My apologies. As @cijothomas mentioned, this depends on the ExportProcessor. If the ExportProcessor exports the activities in a different async flow then you would have a different Baggage context in the `Export` method.

**Comment by BadriL** [comment]
Thank you @cijothomas and @utpilla. I was not expecting the baggage items to be flown through to the exporter anyways and it probably may not make sense also, since export could potentially happen a bit later. Glad I got the custom processor right. Thanks for the confirmation.
