### ISSUE TITLE
Any NET Framework example for SQL Client?

### ISSUE THREAD

**Issue by Oleg26Dev** [open-telemetry/opentelemetry-dotnet#1969]
Where can I find the example how to use OT SQL Client Exporter in NET Framework application? 
Thanx!

**Comment by cijothomas** [comment]
Could you clarify if you are looking for
1. Exporting telemetry to SQL Server?
OR
2. Getting telemetry about your sqlclient calls?

If 1,
There is no exporter to SQL server in this repo. Docs on how to write one - https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#exporter

If 2,
The instrumentation for SqlClient is already in this repo.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.SqlClient/README.md
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#instrumentation-library
