### ISSUE TITLE
Keep structured state in the LoggingProvider for Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by EricStG** [open-telemetry/opentelemetry-dotnet#1970]
# Feature Request

Before opening a feature request against this repo, consider whether the feature
should/could be implemented in the [other OpenTelemetry client
libraries](https://github.com/open-telemetry/). If so, please [open an issue on
opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new)
first.

**Is your feature request related to a problem?**
The state from log events is currently being flattened, so if we're using structured logging, we're losing the contextual data.

Here's an example of the JSON formatter output:
```json
{
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "OtelLogs.Program",
  "Message": "Hello from tomato 2.99.",
  "State": {
    "Message": "Hello from tomato 2.99.",
    "name": "tomato",
    "price": 2.99,
    "{OriginalFormat}": "Hello from {name} {price}."
  }
}
```
Compared to the console exporter output:
```
LogRecord.TraceId:            00000000000000000000000000000000
LogRecord.SpanId:             0000000000000000
LogRecord.Timestamp:          2021-04-08T21:23:06.2545086Z
LogRecord.EventId:            0
LogRecord.CategoryName:       OtelLogs.Program
LogRecord.LogLevel:           Information
LogRecord.TraceFlags:         None
LogRecord.State:              Hello from tomato 2.99.
```

**Describe the solution you'd like:**

The key/value pairs in the state should be maintained, possibly as attributes (if I read the spec properly)

**Describe alternatives you've considered.**

We're currently relying on external tools (ex: Fluent Bit) to export logs without losing information

## Additional Context

Repro code:

```csharp
using var loggerFactory = LoggerFactory.Create(builder =>
{
    builder
        .AddJsonConsole()
        .AddOpenTelemetry(options => options.AddConsoleExporter());
});
var logger = loggerFactory.CreateLogger<Program>();
logger.LogInformation("Hello from {name} {price}.", "tomato", 2.99);
```

**Comment by utpilla** [comment]
@EricStG ConsoleExporter is only meant for quick and easy investigation of the logs. You could use the `InMemoryExporter` to export the logs to a collection of `LogRecord` which will have all the key/value pairs of the `state`.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.InMemory/README.md
