### ISSUE TITLE
StartActivity returns null

### ISSUE THREAD

**Issue by Oleg26Dev** [open-telemetry/opentelemetry-dotnet#1977]
I research the 
opentelemetry-dotnet/examples/Examples.Console.
I get the example code and use in my Winforms app (NET Framework)

When I run it I do not see any traces in Zipkin, then I have detected childSpan == null:

`using (var childSpan = source.StartActivity("ReadStream", ActivityKind.Consumer))`

What need to fix and how to run the example for Zipkin Exporter?

**Comment by cijothomas** [comment]
The instructions for running examples is in the code file as comments:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/Console/TestZipkinExporter.cs#L28

Also check the getting started doc : https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/getting-started

If you still have trouble getting spans/activity, please share the full code snippet you are using to create Activity and setup TracerProvider.
