### ISSUE TITLE
Where are any Log exporters?

### ISSUE THREAD

**Issue by Oleg26Dev** [open-telemetry/opentelemetry-dotnet#1980]
Do any Log exporters exist like
export log to file, rolling file, to database, to network via UDP etc?

**Comment by cijothomas** [comment]
None exists now except Console.
OTLP Exporter is in the works, but we don't have an ETA when it'll be ready for stable consumption.
You may write own exporter following the doc https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/extending-the-sdk/README.md.
