### ISSUE TITLE
No instrumentation for SocketsHttpHandler

### ISSUE THREAD

**Issue by wazzamatazz** [open-telemetry/opentelemetry-dotnet#1990]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

* `OpenTelemetry.Instrumentation.Http 1.0.0-rc3`

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):

* `net5.0`

## Symptom

`traceparent` and `tracestate` headers are not being added to outgoing HTTP requests when `SocketsHttpHandler` is used in an `HttpClient`.

**What is the expected behavior?**

`traceparent` and `tracestate` headers should be added to outgoing HTTP requests regardless of which primary `HttpMessageHandler` is used.

**What is the actual behavior?**

Headers are correctly added if the primary message handler for an `HttpClient` is `HttpClientHandler`, but not when the primary message handler is `SocketsHttpHandler`.

## Reproduce

See [SocketsHttpHandlerInstrumentationIssue.zip](https://github.com/open-telemetry/opentelemetry-dotnet/files/6324663/SocketsHttpHandlerInstrumentationIssue.zip) for a simple solution demonstrating the problem.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/773 Seems like duplicate. 
See linked issue and reopen if this is separate.

**Comment by wazzamatazz** [comment]
You're correct - it does seem to be a duplicate. The fact that you can't use a non-default `HttpMessageHandler` should probably be mentioned in the documentation if it isn't already.
