### ISSUE TITLE
Where OT can write Logs, Metrics, Traces?

### ISSUE THREAD

**Issue by Oleg26Dev** [open-telemetry/opentelemetry-dotnet#1991]
It may be Off-topic, sorry but: 
I see that I can write traces to Zipkin server, it is ok.
What can I use to write logs and metrics like this: free, opensource, dockerized etc?

**Comment by cijothomas** [comment]
For metrics, this repo will ship a Prometheus exporter. (along with OTLP exporter), as required by the spec.
For traces, will ship Zipkin/Jaeger/OTLP - as required by the spec.
For logs this repo only ships a Console Exporter and will eventually add OTLP as well.

Exporters to anything else - you need to either write manually or check if one is available in contrib repo or in some vendor specific repos.

**Comment by Oleg26Dev** [comment]
Thank you! 
I have tested Zipkin for traces, it works fine. 
Prometheus - OK!
But the question left about server for logs. What can be used even without existing Exporters?
Where logs can be saved?
