### ISSUE TITLE
Instrumentation.StackExchangeRedis Should Resolve IConnectionMultiplexer from DI

### ISSUE THREAD

**Issue by RehanSaeed** [open-telemetry/opentelemetry-dotnet#2011]
# Feature Request

I have registered `IConnectionMultiplexer` in my DI container for health checks, a Redis implementation of `IDistributedCache` and other reasons. It would be nice if `OpenTelemetry.Instrumentation.StackExchangeRedis` contained an overload for the `AddRedisInstrumentation` function that allows you to resolve `IConnectionMultiplexer` from DI:

```cs
public static TracerProviderBuilder AddRedisInstrumentation(
    this TracerProviderBuilder builder,
    Func<IConnectionMultiplexer, IServiceBuilder> getConnection,
    Action<StackExchangeRedisCallsInstrumentationOptions> configureOptions = null);
```

Another overload that assumes that `IConnectionMultiplexer` is registered in DI would also be helpful:

```cs
public static TracerProviderBuilder AddRedisInstrumentation(
    this TracerProviderBuilder builder,
    Action<StackExchangeRedisCallsInstrumentationOptions> configureOptions = null);
```

**Is your feature request related to a problem?**

I have to create a new connection specifically for Open Telemetry.

**Describe the solution you'd like:**

I would like to reuse the connection I'm using elsewhere.

**Comment by dgarciarubio** [comment]
I think this is related to https://github.com/dotnet/aspnetcore/issues/28379
Someone found a workaround to obtain the multiplexer, through reflection, altough it is quite ugly: https://github.com/dotnet/aspnetcore/issues/28379#issuecomment-536659503

**Comment by evilpilaf** [comment]
There's an overload for the `AddOpenTelemetry` extension method which has as an argument a `Func<IServiceProvider, TraceProviderBuilder>` so you can do:

```csharp
services.AddOpenTelemetry((provider, builder) =>
{
  var connectionMultiplexer = provider.GetRequiredService<IConnectionMultiplexer>();
  builder.AddRedisInstrumentation(connectionMultiplexer);
}```

**Comment by trejjam** [comment]
@evilpilaf this is no longer possible with 1.0.0-rc4, see https://github.com/open-telemetry/opentelemetry-dotnet/issues/2018

**Comment by evilpilaf** [comment]
@trejjam it's still possible, just a bit different, for rc4 you can do this:

```csharp
services.AddOpenTelemetryTracing(builder => {
    builder.Configure((provider, b) => {
        var connectionMultiplexer = provider.GetRequiredService<IConnectionMultiplexer>();
        b.AddRedisInstrumentation(connectionMultiplexer);
    });
});
```
Though I agree it's a bit more cumbersome and the previous approach was better.

**Comment by CodeBlanch** [comment]
We're trying to do something here! It is tricky because we're supporting .NET Framework where `IServiceCollection` probably isn't being used. The reason the API changed is we introduced this thing called `IDeferredTracerProviderBuilder`. Right now it is part of SDK. We're trying to figure out how to get it into API. Once it is there, it should be possible to add an extension like this in OpenTelemetry.Instrumentation.StackExchangeRedis:

```csharp
        public static TracerProviderBuilder AddRedisInstrumentation(
            this TracerProviderBuilder builder,
            Action<StackExchangeRedisCallsInstrumentationOptions> configureOptions = null)
        {
            if (!(builder is IDeferredTracerProviderBuilder deferredTracerProviderBuilder))
            {
                throw new NotSupportedException("IConnectionMultiplexer could not be resolved automatically.");
            }

            return deferredTracerProviderBuilder.Configure((sp, builder) =>
            {
                StackExchangeRedisCallsInstrumentationOptions options = sp.GetOptions<StackExchangeRedisCallsInstrumentationOptions>();
                configureOptions?.Invoke(options);

                builder
                    .AddInstrumentation(() => new StackExchangeRedisCallsInstrumentation(
                        sp.GetService<IConnectionMultiplexer>() ?? throw new InvalidOperationException("IConnectionMultiplexer could not be found on IServiceProvider."),
                        options))
                    .AddSource(StackExchangeRedisCallsInstrumentation.ActivitySourceName);
            });
        }
```

That would allow it to automatically resolve `IConnectionMultiplexer` (& options) automatically through the `IServiceProvider` and users won't need to use the more cumbersome syntax shown above!
