### ISSUE TITLE
Use IServiceProvider in AddOpenTelemetryTracing

### ISSUE THREAD

**Issue by dgarciarubio** [open-telemetry/opentelemetry-dotnet#2018]
# Question

I am using the 1.0.0-rc4 of OpenTelemetry.Extensions.Hosting. I'm trying to add redis instrumentation, but for that I need an instance of `IConnectionMultiplexer`. In some examples, I have seen that it can be resolved from the service provider by using the following overload of `AddOpenTelemetryTracing`:

```
services.AddOpenTelemetryTracing((serviceProvider, builder) =>
{
    builder.AddRedisInstrumentation(serviceProvider.GetRequiredService<IConnectionMultiplexer>());
}
```

However, this overload has disappeared in rc-4, while it was present in rc-3. 

- Is this planned to be available in the final release?
- If not, is there any other recommended way we can solve this use case?

**Comment by dgarciarubio** [comment]
Maybe this can be solved with #2011

**Comment by dgarciarubio** [comment]
I see that this overload was dropped in #1889 in favor of 

```
services.AddOpenTelemetryTracing(builder =>
{
    builder.configure((serviceProvider, builder) => 
    {
        //Use the service provider here to add additional configuration to the builder
    });
});
```

Personally, I find the previous overload of `AddOpenTelemetryTracing` useful, and more easily discoverable.
Anyway, if this is the new way to go, it would be useful to add examples of how to achieve this in the documentation.

**Comment by CodeBlanch** [comment]
@dgarciarubio I added some documentation in the README on #2080 please check it out and let me know what you think. I agree with you in this case it was nicer before but if we start with the `IServiceProvider` then `TracerProviderBuilder` extensions can't register anything with the `IServiceCollection`. Basically, the "Building Extension Methods" section in the README was impossible before the change.

**Comment by CodeBlanch** [comment]
README updates are now live: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Extensions.Hosting/README.md

I'm going to close this but feel free to re-open.
