### ISSUE TITLE
Stable release of telemetry packages

### ISSUE THREAD

**Issue by techgeek03** [open-telemetry/opentelemetry-dotnet#2023]
# Question

Hello,
I'm wondering when can we expect an stable release of the NuGet packages for
- OpenTelemetry.Extensions.Hosting
- OpenTelemetry.Instrumentation.GrpcNetClient
- OpenTelemetry.Instrumentation.AspNetCore

as well as other packages that don't have stable release. They are still in RC. 
We have internal packages that depend on them and for almost a year we are forced to release them in beta that poses some unnecessary maintenance challenges for us in our development flow.

**Comment by cijothomas** [comment]
Instrumentations cannot be released as stable unless spec marks semantic conventions as stable. Spec team is working on it, but I don't have ETA.

Hosting package needs to address some feedbacks, so we are working on it. (No ETA, there are some active proposals and discussions, its likely to take months before stable). 
As a reminder - this package is *NOT* required (though very useful). You can create TracerProvider and add it to DI yourself, and everything would work the same.

Thanks for your patience!
