### ISSUE TITLE
How to create Log Exporter?

### ISSUE THREAD

**Issue by Oleg26Dev** [open-telemetry/opentelemetry-dotnet#2024]
What are step by step? Required methods?
For example, 
I'd like to export logs to GrayLog. I need connect to the server and export.
What are minimal Log Exporter?
What can be get as a template for this Log Exporter?

**Comment by reyang** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/extending-the-sdk#exporter
