### ISSUE TITLE
Problem with Jaeger span hierarchy when using istio/kubernetes

### ISSUE THREAD

**Issue by SVronskiy** [open-telemetry/opentelemetry-dotnet#2025]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using:
"OpenTelemetry.Exporter.Console" Version="1.1.0-beta1" />
"OpenTelemetry.Exporter.Jaeger" Version="1.0.1" />
"OpenTelemetry.Exporter.Zipkin" Version="1.0.1" />
"OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc4" />
"OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc4" />
"OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc4" />
"OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc4" />

Runtime version netcoreapp2.2

## Symptom

I'm not able to  get correct hierarchy of trace spans in Jaeger when using opentelemetry in .net core 2.2 application running under kubernetes 1.18 with istio 1.9.2. 

I'm requesting content service Index outside of the kubernetes cluster via external address, then it requests context service Line2 via httpclient internal address.

**What is the expected behavior?**

What did you expect to see?
I expect to get picture like this:
![image](https://user-images.githubusercontent.com/18757475/116682410-6821ae80-a9d8-11eb-876b-5cebe0e8eec0.png)

![image](https://user-images.githubusercontent.com/18757475/116796840-e2058500-ab09-11eb-8e0c-3f0b016690b0.png)

**What is the actual behavior?**

![image](https://user-images.githubusercontent.com/18757475/116796851-f8abdc00-ab09-11eb-8c13-20a8c3301d2b.png)

![image](https://user-images.githubusercontent.com/18757475/116796831-ca2e0100-ab09-11eb-988e-f87935c9a4bd.png)

## Reproduce

Here is a code:

DevTestController.cs:
```
[Produces("application/json")]
[CustomJsonFormatter("camel")]
[Route("[controller]")]
[ApiController]
public class DevTestController : ControllerBase
{

    HttpClient _httpClient;
    private readonly IHttpClientFactory _clientFactory;

    public DevTestController(IHttpClientFactory clientFactory)
    {
            _clientFactory = clientFactory;
    }


    [HttpGet]
    [ProducesResponseType((int)HttpStatusCode.OK)]
    public async Task<IActionResult> Index()
    {
        _httpClient = _clientFactory.CreateClient("content");
        string headersRequest = String.Empty;
        string result = "";
        try
        {
            var response = await _httpClient.GetAsync("http://content/devtest/line2");

            if (response.IsSuccessStatusCode)
            {
                result = await response.Content.ReadAsStringAsync();
            }

        }
        catch (Exception ex)
        {
        };

        foreach (var header in Request.Headers)
        {
            headersRequest +=  $"[{header.Key}: {header.Value}], <br> ";
        }

        return Ok(headersRequest + result);
    }


    [HttpGet("line2")]
    [ProducesResponseType((int)HttpStatusCode.OK)]
    public async Task<IActionResult> Line2()
    {
        return Ok(Request.Headers.ToList());
    }
}
```

Startup.cs:
```
            services.AddHttpClient("content", c =>
            {
                c.DefaultRequestHeaders.Add("HttpFactory", "Test header propagated successfully");
            });

            services.AddOpenTelemetryTracing((builder) => builder
                .AddAspNetCoreInstrumentation()
                .AddHttpClientInstrumentation()
                .AddConsoleExporter()
                .AddSqlClientInstrumentation()
                );

            OpenTelemetry.Sdk.SetDefaultTextMapPropagator(
                new CompositeTextMapPropagator(new List<TextMapPropagator>
                {
                    new B3Propagator(false)
                }));

```

## Additional Context

My experiments show, that manual propogation of the following three B3 headers resolves the problem (problem is somehow related with them):
```
            ArrayList list = new ArrayList()
            {
                "x-b3-spanid", "x-b3-parentspanid", "x-b3-traceid"
            };

            foreach (string item in list)
            {
                _httpClient.DefaultRequestHeaders.TryAddWithoutValidation(item, Request.Headers[item].ToString());
            }
```

In my opinion, problem symptoms look similar to [#1376 Fixed a couple bugs in AspNet instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1376)

**Comment by PiyushBhatewara** [comment]
Hi @SVronskiy 

We are trying to achieve same but we are not getting spans in b3 headers at all, could you please provide us more complete code examples.

Also wanted to get details about where you wrote this code to propagate the b3 headers - 

```
 ArrayList list = new ArrayList()
            {
                "x-b3-spanid", "x-b3-parentspanid", "x-b3-traceid"
            };

            foreach (string item in list)
            {
                _httpClient.DefaultRequestHeaders.TryAddWithoutValidation(item, Request.Headers[item].ToString());
            }
```


Thanks for help.

**Comment by MortalFlesh** [comment]
It might be caused by missing `x-b3-parentspanid` header in `B3Propagator`.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Context/Propagation/B3Propagator.cs#L146-L151
