### ISSUE TITLE
LogRecord and IncludeFormattedMessage default.

### ISSUE THREAD

**Issue by jviau** [open-telemetry/opentelemetry-dotnet#2042]
# Question

I am confused by the default behavior to _not_ include the formatted log message. It is my understanding that this _is_ the value to log when using `Microsoft.Extensions.Logging`. It is the base functionality they demonstrate in their [example provider ](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider). Enumerating the logs state, and scope state are additional (and optional) enhancements to your `ILoggerProvider`. But calling the `format` function provided to `.Log` is mandatory (from my understanding). Not even calling `ToString()` on the provided state is correct - you must use the format callback.

So my question is, why is this default false? Or even configurable? I feel like it is giving exporters the wrong idea on what they should log. I understand if you can't break that behavior in 1.\*, but is it planned or aware of for 2.\*?

Describe any aspect of your environment relevant to the question.

**What are you trying to achieve?**

Ensuring correct log messages are recorded in exporters.

## Additional Context

https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider

**Comment by cijothomas** [comment]
Taking the basic example, using the extension method:
logger.LogInformation("Hello from {food} {price}.", "apple", 3.99);

OpenTelemetry (or any other provider) has the following information:
The original format, following https://messagetemplates.org/ standard - "Hello from {food} {price}." 
key/values pairs:
food:"apple"
price:3.99

Enabling `IncludeFormattedMessage` will give the following:
"Hello from apple 3.99."

The formatted message is technically reconstructable from the original format+k/v pairs. So we want to give an option to users to store the formatted message *only* if they really need that. If a Visualizing UI has the ability to construct the formatted message "on the fly", then storing FormattedMessage is wasted cost.

Hope the explanation makes sense.
(Docs from ILogger is just example, not necessarily reflecting the best practices.)
