### ISSUE TITLE
Use DOTNET_ENVIRONMENT and ASPNETCORE_ENVIRONMENT as default "deployment.environment"

### ISSUE THREAD

**Issue by DR9885** [open-telemetry/opentelemetry-dotnet#2046]
# Feature Request

**Is your feature request related to a problem?**

currently you have to manually set environment by setting attribute "deployment.environment"

**Describe the solution you'd like:**

It should just pull from the environment variables from dotnet "DOTNET_ENVIRONMENT" and "ASPNETCORE_ENVIRONMENT"

**Describe alternatives you've considered.**

currently I'm manually setting the value myself.

## Additional Context
Example 1: set attributes with builder... (optionally add to default builder)
```
        public static ResourceBuilder AddEnvironment(this ResourceBuilder resourceBuilder)
        {
            var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ??
                      Environment.GetEnvironmentVariable("DOTNETCORE_ENVIRONMENT");

            var attr = new Dictionary<string, object>();
            attr.Add("deployment.environment", env);

            resourceBuilder.AddAttributes(attr.Select(x => x).ToArray());

            return resourceBuilder;
        }
```

**Comment by swythan** [comment]
This still seems reasonable to me.

**Comment by TimothyMothra** [comment]
"deployment.environment" is not part of the OTel Semantic Convention.
"deployment.environment.name" is still experimental and until it's stabilized, it won't be added here.

https://opentelemetry.io/docs/specs/semconv/attributes-registry/deployment/#deployment-attributes

**Comment by swythan** [comment]
Good point. I guess this is something to consider once the convention is stable.
