### ISSUE TITLE
exporter/stackdriver: LastValue aggregation converts to Gauge with invalid time range

### ISSUE THREAD

**Issue by jacostro** [open-telemetry/opentelemetry-dotnet#205]
A view with `LastValue` aggregation converts to Stackdriver's `GAUGE` preserving its own time range, which is invalid:
> Status(StatusCode=InvalidArgument, Detail="Field timeSeries[1].points[0].interval.start_time had an invalid value of "2019-09-16T05:10:44.758225-07:00": The start time must be equal to the end time (2019-09-16T05:11:45.551259-07:00) for the gauge metric 'custom.googleapis.com/opencensus/sample_190816/views/data_size_changes'.")

Seems that correct way is to set start time to the value of end time.

**Comment by cijothomas** [comment]
Closong as StackDrive is removed from this repo. The old metric api is also removed.
