### ISSUE TITLE
Do we have thrift http exporter for Jeager exporter?

### ISSUE THREAD

**Issue by ElectricVampire** [open-telemetry/opentelemetry-dotnet#2054]
# Question

I am moving from using JeagerTracing to dot net OpenTelemetry Library to generate traces. We have a Jeager http end point for collector(JAEGER_ENDPOINT | http://jaeger-collector:14268/api/traces) and I want to send my trace to that endpoint.

Current [jaegerexporter ](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/jaegerexporter/README.md) only supports communication over UDP to agent but its blocked in our firewall hence I need an option to send my traces to JAEGER_ENDPOINT. Even option to set GRPC endpoint will work for me.

Please help.
Thanks for your time.

**Comment by cijothomas** [comment]
You are right that we currently only support UDP. Adding support for new protocol is a feature request - this is not in the current plan.

**Comment by rwkarg** [comment]
This is preventing us from moving from OpenTracing -> OpenTelemetry.

**Comment by cijothomas** [comment]
Closing as no new features should be added to Jaeger Exporter given its upcoming deprecation. https://github.com/open-telemetry/opentelemetry-dotnet/pull/4270
