### ISSUE TITLE
Add a badge for CI status

### ISSUE THREAD

**Issue by KKelvinLo** [open-telemetry/opentelemetry-dotnet#2055]
**Is your feature request related to a problem?**
Most of the existing OpenTelemetry repositories display a badge for CI status. In an effort to have the dotnet SDK repository to be up to date and consistent with the other established SDKs and repositories, there should be a CI status badge in the main README.md file.

**Describe the solution you'd like.**
As a developer contributing to OpenTelemetry, I recommend adding a CI status badge at the top of the README document of the dotnet repo. CI status badges are a common feature of many modern open source projects, which improves readability and convenience to developers. By adding a CI status badge to the README.md, with a quick scan, any observer will be able to know the status of the repository.

cc: @alolita

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/1757
