### ISSUE TITLE
Duplicate tag "peer.service" warning on jeager UI with Zipkin exporter

### ISSUE THREAD

**Issue by ElectricVampire** [open-telemetry/opentelemetry-dotnet#2059]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 0.4.0-beta.2`):

"OpenTelemetry.Exporter.Jaeger" Version="1.0.1" />
"OpenTelemetry.Exporter.Zipkin" Version="1.0.1" />
"OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc4" />

Runtime version (e.g. `net461`, `net48`, `netcoreapp2.1`, `netcoreapp3.1`, etc.
You can find this information from the `*.csproj` file):

.Net Core 3.1

## Symptom

Getting warning on JeagerUI showing "peer.service" tag is duplicate

**What is the expected behavior?**

This warning should not be there

**What is the actual behavior?**

Getting warning on JeagerUI showing "peer.service" tag is duplicate

## Reproduce
Below line of code should reproduce it.

services.AddOpenTelemetryTracing((builder) => builder
    .AddAspNetCoreInstrumentation()
    .AddHttpClientInstrumentation()
    .AddSqlClientInstrumentation()
    .AddZipkinExporter(options =>
    {
        options.Endpoint = new Uri("localhost:9411/api/v2/spans");
    })
    );

**Comment by luizhlelis** [comment]
Hello @ElectricVampire, take a look at [this issue comment](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2027#issuecomment-881794016) 😃

**Comment by vishweshbankwar** [comment]
closing this as duplicate of #2027
