### ISSUE TITLE
Metrics tags should use IList instead of Array

### ISSUE THREAD

**Issue by victlu** [open-telemetry/opentelemetry-dotnet#2062]
Should we use IList<KeyValuePair<string, object>> instead of KeyValuePair<string, object>[] ?

Comment from PR #2053

https://github.com/open-telemetry/opentelemetry-dotnet/pull/2053#discussion_r637439512

**Comment by victlu** [comment]
@CodeBlanch FYI

**Comment by cijothomas** [comment]
The current MetricPoint exposes Keys and Values and string[] and object[]. This was done to re-use the string[], object[] from the ThreadLocal/AggregatorStore lookup. But this restrics us from making changes to this in the future.

Might be good to consider making them IEnumerable or maybe Batch of keys, values..

**Comment by tomkerkhove** [comment]
`IEnumerable` sounds like a great approach imo.

**Comment by CodeBlanch** [comment]
Only issue with `IEnumerable` is in exporters we will have to `foreach` that and pay for an allocation each time. `IList` we could avoid that. Or we could make a minimal data structure that exposes a `struct` enumerator so we can swap out the implementation (if needed) while avoiding the allocation.
