### ISSUE TITLE
Ensure OpenTelemetry continues to work with .NET 6

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2064]
Opening an issue to track the work of making sure that this SDK continues to work well with .NET 6 as well. We have dependency on DiagnosticSource and Logging package from .NET runtime, and they are not expected to contain any breaking changes. However, it must be tested to make sure this is the case.

We need to try PRs (eg: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2057) with .NET 6 preview bits and see if there are CI failures. If there are behaviour change from .NET 6, it must be investigated and raised in .NET runtime repo.

Once we reach ~Sep-Oct timeframe when .NET 6 is nearing stable release, we can have the main branch release a preview of Otel , which refers the preview .NET 6 bits. (or we may piggyback on metrics branch which will always have .NET 6 dependency)

**Comment by cijothomas** [comment]
FYI @vishweshbankwar

**Comment by vishweshbankwar** [comment]
For reference: one of the behavior changes is noted here - https://github.com/dotnet/runtime/issues/53375

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/OpenTelemetry.Instrumentation.AspNetCore.csproj#L3 Need to confirm if this continues to work in .NET6.

**Comment by joshongithub** [comment]
Hi, is this the best Issue to watch to confirm compatibility with .NET 6? .NET 6 RC1 was released week, which is a stable production supported pre-release.

**Comment by cijothomas** [comment]
> Hi, is this the best Issue to watch to confirm compatibility with .NET 6? .NET 6 RC1 was released week, which is a stable production supported pre-release.

Yes. As mentioned in the description, our dependencies are on runtime packages, which are *not* expected to contain any backward incompatible changes. This issue is to mostly keep track of testing, (and also to leverage some new capabilities in .NET 6).
Please use this issue to report any issues you faced with .NET 6.
