### ISSUE TITLE
OTLP dose not export otel.status_code

### ISSUE THREAD

**Issue by glucaci** [open-telemetry/opentelemetry-dotnet#2074]
# Question

Why otel.status_code is not exported over OTLP ?

**What are you trying to achieve?**

In GraphQL the reuqest returns always `HTTP 200` dosen't matter if it's a client error, server error or it's a success request and I think the `otel.status_code` is more descriptive about what happend with the request: `Ok` or `Error`.

## Additional Context

I started to write a `GraphQL` instrumentation library for [HotChocolate](https://github.com/chillicream/hotchocolate) and triying to integrate it with Elastic APM Server over OTLP.

**Comment by alanwest** [comment]
The purpose of the `otel.*` attributes are meant for use with [non-OTLP data formats](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#mappings).

`Span.Status` is a top-level field of a span in the OTLP data format, so there is no need to capture it separately as a span attribute. See the [protobuf definition](https://github.com/open-telemetry/opentelemetry-proto/blob/bacfe08d84e21fb2a779e302d12e8dfeb67e7b86/opentelemetry/proto/trace/v1/trace.proto#L232-L234).

For contrast, the Zipkin span data format does not have a top-level status field, so the specification for Zipkin exporters require mapping the status to the `otel.status_code` attribute. See the [Zipkin spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md#status).
