### ISSUE TITLE
ApiCompat improvements

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2081]
Copied from https://github.com/open-telemetry/opentelemetry-dotnet/issues/1711#issuecomment-860815199

.NET Team is moving this tool into a separate package, along with other compact check tools. We'll need to adjust accordingly as it happens. - @utpilla

Only enabled for core packages now, as only core packages have ever released stable package. Need to update this once non-core components also release stable. - @cijothomas

The check is part of a non-mandatory CI now, as the tool itself is new and we don't want to break existing CI if the tool has issues. Once the tool is stable, (expected by .NET 6 release time), we can make this CI check mandatory. @cijothomas

The CI check is failing today. @utpilla has investigated this and opened dotnet/arcade#7511, as this is likely a tooling issue. @utpilla

Need to update the release process, so that every stable release updates the "base or contract" version to check compat against. @cijothomas

**Comment by cijothomas** [comment]
The new tool and instructions are here, so we can try to onboard to the new tool.
https://devblogs.microsoft.com/dotnet/package-validation/

**Comment by mfogliatto** [comment]
Thanks @ViktorHofer ! I'm going to work on this one so I might reach out to you with some questions :)

**Comment by ViktorHofer** [comment]
For a high level summary on how to enable the feature, see https://github.com/Azure/azure-sdk-for-net/pull/36965#issuecomment-1665855629

**Comment by mfogliatto** [comment]
Thank you so much @ViktorHofer for your guidance and support!

 It is a pleasure to work with someone with such a first-hand and quality knowledge on the .NET internals :)

**Comment by ViktorHofer** [comment]
Of course, it was my pleasure.
