### ISSUE TITLE
Linux CI Task Badge

### ISSUE THREAD

**Issue by TimHess** [open-telemetry/opentelemetry-dotnet#2083]
As mentioned on the SIG call today, the Linux badge indicates the task is failing, but it isn't immediately clear why. I think that the problem is that the Linux task isn't actually running when PRs merge. If you click on the ❌ or ✔️ on [any given commit](https://github.com/open-telemetry/opentelemetry-dotnet/commits/main), you'll see the status of 14 tasks, compared to 28 or 29 on a PR.

I haven't been watching the badge so I don't know the case, but if it is occasionally ✔️ and not always ❌ then I would speculate we're seeing the general status of the last run rather than any specific task.

The solution is likely to update the triggers on the task definitions - note the difference between [linux-ci](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/.github/workflows/linux-ci.yml#L3) and [integration](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/.github/workflows/integration.yml#L3). I can submit a PR for this change if you specify whether the change should apply to all tasks or just a subset

**Comment by cijothomas** [comment]
Thanks @TimHess for exploring! What puzzles me is that the Windows-CI is showing correct status. It has same trigger as Linux-CI - both are triggered on PRs, but not on merge to main.

**Comment by TimHess** [comment]
> Thanks @TimHess for exploring! What puzzles me is that the Windows-CI is showing correct status. It has same trigger as Linux-CI - both are triggered on PRs, but not on merge to main.

Yeah, that part is a bit of a puzzle, maybe once upon a time (the last run on that branch?) it failed on Linux but passed on Windows and it just hasn't been right since? Regardless of the reason for current badge status, as it stands today, neither task actually runs when changes are pushed to main.

**Comment by cijothomas** [comment]
Yes. Could you submit PR to trigger these actions to be triggered for push to main,metrics as well.
