### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by valeraf23** [open-telemetry/opentelemetry-dotnet#2091]
# Bug Report

    <PackageReference Include="OpenTelemetry" Version="1.1.0-beta4" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.1.0-beta4" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.1.0-beta4" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.1.0-beta4" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc5" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc5" />

## Symptom

```
            services.AddOpenTelemetryTracing(builder =>
            {
                builder.Configure(
                    (sp, b) => b.AddAspNetCoreInstrumentation());
            });

            var tracerFactory = serviceProvider.GetRequiredService<TracerProvider>();
```
occurred exception 
System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'

The reason that AddAspNetCoreInstrumentation method also executes builder. Configure method. But for my point of view if I can call AddAspNetCoreInstrumentation from the builder. Configure there are should not be exceptions

**Comment by CodeBlanch** [comment]
Should be fixed with #2080
