### ISSUE TITLE
Add Resource to SpanData and allow to create Resource using pure API

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#21]

**Comment by SergeyKanzhelev** [comment]
Resource is now in specs: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resources-api.md and https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/tracing-api.md#constructing-spandata

Need to move abstract class to API, get rid of interface and add Resource to the `SpanData`.

**Comment by SergeyKanzhelev** [comment]
@trwegner do you want to take it?

**Comment by trwegner** [comment]
Sure!  I'll start this afternoon.

**Comment by trwegner** [comment]
@SergeyKanzhelev and @lmolkova - to move Resource abstract class requires also moving Tag, TagKey and TagValue.  Any objection to removing the corresponding Tag* interfaces along the the Resource one?

**Comment by SergeyKanzhelev** [comment]
yep. This is fine: https://github.com/open-telemetry/opentelemetry-java/blob/4172855fcdefc5d11cf52a974aeaf8de572c9f96/api/src/main/java/io/opentelemetry/tags/Tag.java#L30

**Comment by trwegner** [comment]
Great! Thanks Sergey.

**Comment by SergeyKanzhelev** [comment]
Closed via #97
