### ISSUE TITLE
Instrumentation + Hosting Release Schedule

### ISSUE THREAD

**Issue by tl-david-hayden** [open-telemetry/opentelemetry-dotnet#2104]
The [project milestones](https://github.com/open-telemetry/opentelemetry-dotnet/milestones) don't explicitly mention the instrumentation packages, or `OpenTelemetry.Extensions.Hosting`.

What is the expected timeline for stable versions of these packages being released?

**Comment by cijothomas** [comment]
I added a new milestone for instrumentation, as a lot of people have asked similar questions. https://github.com/open-telemetry/opentelemetry-dotnet/milestone/23
Instrumentation stable release is blocked on spec.

`OpenTelemetry.Extensions.Hosting` - we'll share an ETA for 1.0.0 soon. This is not blocked by spec.

**Comment by tl-david-hayden** [comment]
Thanks for the update.
Is the spec that the instrumentations are blocked on the [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/README.md)?

**Comment by cijothomas** [comment]
Yes, blocked on semantic conventions.

**Comment by tl-david-hayden** [comment]
> `OpenTelemetry.Extensions.Hosting` - we'll share an ETA for 1.0.0 soon. This is not blocked by spec.

Hey, just checking if there is an update on this?

**Comment by tl-david-hayden** [comment]
> `OpenTelemetry.Extensions.Hosting` - we'll share an ETA for 1.0.0 soon. This is not blocked by spec.

@cijothomas Is there an ETA for this yet?
