### ISSUE TITLE
Updating / changing the root span name

### ISSUE THREAD

**Issue by nover** [open-telemetry/opentelemetry-dotnet#2105]
# Renaming the root span

We have rolled out OpenTelemetry tracing on a fleet of asp.net core 3.1 web-applications, where most of them are using GraphQL.
We've added the `AddHttpClientInstrumentation` and `AddAspNetCoreInstrumentation` to the stack.

With graphql services _all_ request are made to `POST /graphql` and thus the default naming in the `AddAspNetCoreInstrumentation` using verb + route becomes pretty useless.
We already have code in place to start a subspan that labels it correctly based off data in the query/mutation, however, I would like to ask, if there is a way to "rename" the root span? 

So that, in the code we have were we start a sub-span, I would actually rather get ahold of the root-span instead and give it a new name.
Or a way to "inject my self" into the root span naming.

**Comment by nover** [comment]
Looking a bit deeper in the documentation I found the `Enrich` property on the options for `AddAspNetCoreInstrumentation` so this is what I have come up with so far:
```
.AddAspNetCoreInstrumentation(options =>
                    {
                        options.Enrich = async (activity, eventName, rawObject) =>
                        {
                            if (eventName.Equals("OnStartActivity"))
                            {
                                if (rawObject is HttpRequest {Path: {Value: "/graphql"}})
                                {
                                    var httpRequest = rawObject as HttpRequest;
                                    httpRequest.EnableBuffering();
                                    var body = await httpRequest.Body.ReadToEndAsync();
                                    var gqlOperation = graphQlOpName.Handle(body);
                                    activity.DisplayName = $"GQL {gqlOperation.Operation}";
                                    activity.SetTag("gql.op", gqlOperation.Operation);
                                    activity.SetTag("gql.op-type", gqlOperation.OperationType.ToString());
                                }
                            }
                        };
                     };
                  })
```

Is there a more elegant way to achieve this or is this the only way at the moment?

**Comment by utpilla** [comment]
@nover Using the `Enrich` option is best way to do update the Activity display name set by AspNetCore.

**Comment by nover** [comment]
Ok thanks @utpilla - I guess "case closed" :)
