### ISSUE TITLE
Correct way to access ParentSpanId in Propagator

### ISSUE THREAD

**Issue by notcool11** [open-telemetry/opentelemetry-dotnet#2106]
# Question
Looking for guidance on the right way to access the ParentSpanId while inside a Propagator. [This issue](https://github.com/open-telemetry/opentelemetry-dotnet/issues/1881) mentioned that there is not support for Jaeger yet, but if I build one I'll need access to the ParentSpanId. What is the best way to do this??

**Describe your environment.**
n/a

Describe any aspect of your environment relevant to the question.

**What are you trying to achieve?**
Build a propagator for Jaeger.

**What did you expect to see?**
The [Jaeger Header](https://www.jaegertracing.io/docs/1.23/client-libraries/#value) follows this format:
```
{trace-id}:{span-id}:{parent-span-id}:{flags}
```

In the Propagator Inject method I have this API:
```
public override void Inject<T>(PropagationContext context, T carrier, Action<T, string, string> setter)
```

There is no access to the ParentSpanId in the PropagationContext.ActivityContext, only the TraceId and SpanId.

I can get around this by using the Current Activity like this:
```
Activity.Current.ParentSpanId.ToHexString()
```

But that feels a bit wonky to be pulling the TraceId and SpanId from a different object than the ParentSpanId. Would it be possible to add the ParentSpanId to the ActivityContext?? That seems like the cleanest solution, but not sure what the impact of that would be. Thanks.

## Additional Context

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.

**Comment by cijothomas** [comment]
Accessing the current span from propagator is what Python implementation currently does : https://github.com/open-telemetry/opentelemetry-python/blob/main/propagator/opentelemetry-propagator-jaeger/src/opentelemetry/propagators/jaeger/__init__.py#L80

**Comment by cijothomas** [comment]
> Would it be possible to add the ParentSpanId to the ActivityContext

Not likely as its a spec defined item. Also the python implementation shared above works without it.

**Comment by notcool11** [comment]
Funny that they are doing the same thing for the same reason but we can't just update the spec to include it. ;)

No worries, I'll proceed as is and make sure to comment the code. Thanks!!

**Comment by cijothomas** [comment]
okay!
(you may ask this in spec repo, but i doubt spec will entertain adding a new field to support a legacy propagation format!)
