### ISSUE TITLE
Incoming Context Propagation Ignored

### ISSUE THREAD

**Issue by ppathard** [open-telemetry/opentelemetry-dotnet#2113]
Integrated OpenTelemetry Tracing in dotnet core 3.1 application as below

```
services.AddOpenTelemetryTracing((builder) => builder
                                    .AddSource("test")
                                    .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("test"))
                                    .AddAspNetCoreInstrumentation()
                                    .AddHttpClientInstrumentation()
                                    .AddZipkinExporter().SetSampler(new AlwaysOnSampler()));
```

I am able to see the traces/spans in Jaeger UI but calls from other services(java services - Spring Sleuth with Brave) are not recognized. They are not part of single trace. Every call to test service from other service is creating new traceId.

Any thing i need to configure ?

**Comment by utpilla** [comment]
@ppathard What kind of propagation are those other services that call your test service inject into their request? By default, W3C TraceContextPropagation is enabled in OTel SDK. If those other services use a different Propagator you'll have to configure the SDK accordingly.

**Comment by ppathard** [comment]
@utpilla how do we configure sdk to use B3 propagation?

**Comment by utpilla** [comment]
@ppathard If you only want to use `B3Propragator` use this: `Sdk.SetDefaultTextMapPropagator(new B3Propagator());`.

If you want to use `B3Propagator` along with the W3C Baggage Propagator use:
```
Sdk.SetDefaultTextMapPropagator(new CompositeTextMapPropagator(new TextMapPropagator[]
                {
                    new B3Propagator(),
                    new BaggagePropagator(),
                }));
```

**Comment by ppathard** [comment]
@utpilla  This worked. Thank you

**Comment by mrmartan** [comment]
This should be mentioned somewhere in the readmes or added as an option to the AddAspNetCoreInstrumentation(). I am running services as part of an Istio mesh and was struggling with getting the propagation to work.
