### ISSUE TITLE
Demo program.cs has an error

### ISSUE THREAD

**Issue by sniperwrb** [open-telemetry/opentelemetry-dotnet#2114]
docs/trace/getting-started/Program.cs

When pasted into C#, it says

'TracerProviderBuilder' does not contain a definition for 'AddConsoleExporter' and no accessible extension method 'AddConsoleExporter' accepting a first argument of type 'TracerProviderBuilder' could be found (are you missing a using directive or an assembly reference?)

Even after installing opentelemetry the error still exists.

**Comment by cijothomas** [comment]
the docs code is part of CI checks, so its always compilable. You may clone the repo and run the program as-is.

Please double check you added the nuget packages, and imported namespaces?
