### ISSUE TITLE
Question: Multiple TracerProviders per host & instrumentation filtering

### ISSUE THREAD

**Issue by buvinghausen** [open-telemetry/opentelemetry-dotnet#2115]
**Describe your environment.**

.NET 5.0.7 on Windows

**What are you trying to achieve?**

We run 7 services on a single web host.  In order to get the service.name set correctly we have to spin up 7 instances of TracerProvider because you have a 1:1 relationship between TracerProvider & the SetResourceBuilder function (last one wins).  When I define a filter operation on AddAspNetCoreInstrumentation my filter function is called 7 times but will short circuit at the first time it returns false.  This means I either get the trace 7 times across all services if it always returns true or it doesn't happen at all if any of the 7 calls return false.  What I'm looking for is the ability to have one service return back true and only that single TracerProvider perform the instrumentation. Is such a thing even possible?

## Additional Context

Did not follow any documentation because all the examples show a 1:1 physical host to instrumentation implementation.

**Comment by buvinghausen** [comment]
Just for additional context I rolled in a custom sampler on all the TracerProviderBuilder calls and a similar behavior occurs which is if any one of the SamplingResults comes back to Drop then no instrumentation occurs though it does seem to loop over all the instances even after it gets a Drop.

**Comment by cijothomas** [comment]
> What I'm looking for is the ability to have one service return back true and only that single TracerProvider perform the instrumentation

If you are creating multiple TracerProviders, but only want instrumentation to happen from one of them - then you need to call AddAspNetCoreInstrumentation on only one, not all of them. Adding instrumentation more than once, is bad for perf , even if you filter/short circuit.

**Comment by buvinghausen** [comment]
@cijothomas the core issue is all the services have controllers, use http clients, etc.   So perhaps I should ask the root question.  Is there a way to resolve which service should be used as a resource?  AFAIK you only allow one Resource per TracerProvider and once it's built you get what you've got.  It would be helpful if there was a mechanism for each root instrumentation to expose a configuration function similar to the filter function which would yield back the desired target resource to allocate the span against.  Then we'd have only one TracerProvider and I would still get the granularity of reporting within the services which is ultimately what I'd like to get to.

**Comment by cijothomas** [comment]
Are you asking for ability to dynamically change the Resource, after the provider is built?

**Comment by buvinghausen** [comment]
@cijothomas I'm asking for the ability to instrument multiple services in a single hosted environment where each of those services use similar tech that needs to be instrumented.   How that happens isn't important to me. What is important to me is when you hit an API controller from my billing service that the service.* values reflect the Billing.Web origin and similarly when you hit an API controller from my quote service that service values show Quote.Web.  As it stands today I'm only allowed to have one service name which is far from desirable.  Yes I can enrich the activity and tag it with a custom service tag but that's not nearly as helpful from a visualization perspective as having the correct service attributes populated.  Is there currently a way to do this that I'm just not seeing?

**Comment by cijothomas** [comment]
The service name is populated from Resource (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md#service-name). 

Also, Resource must be associated with a provider at provider creation time, and that cannot be changed afterwards.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#resource-sdk

Not sure if I understood your scenario fully, but it looks to me like both are by-design of the spec. (If above is right, then this would be the same in all other languages as well.)

**Comment by buvinghausen** [comment]
@cijothomas thank you for following up and I'm sorry for the late response here.  My understanding of the specification was what led me down the path of trying to sort out multiple tracer providers so each service could have it's properly assigned resource. Unfortunately the filtering works as I described in the OP which is to say it doesn't work at all irrespective of the performance implications not to mention every instrumentation would have to have a filtering mechanism which is not 100% the case.

It's disappointing to me that hosting multiple services in a single host process is a use case the open telemetry group just whiffed on completely.  Not sure what can be done to triage at this point but I'm open to ideas or being a part of a spike to illustrate the desired operation.

In that arena having a single tracer provider from a performance perspective would be ideal but it also then would mean I only need to determine the resource to use is at the parent activity level.  All child activities would simply be under the parent activity's resource.  The only way to cross service barriers in my app is publish a event to a queue at which time the handling of that message from the queue becomes the parent activity with the traceparent header.  Realistically the only ways for my services to instantiate a parent activity currently is the ASP.NET Core instrumentation (hubs/controllers/etc) and Jimmy Bogard's NServiceBus instrumentation so the ability to provide a function that takes the incoming message context and resolves back to a resource would be great and would solve the conundrum I'm facing.
