### ISSUE TITLE
Suggestion for documentation about ActivitySource and background services

### ISSUE THREAD

**Issue by JoeMarkov** [open-telemetry/opentelemetry-dotnet#2116]
# Question

I am creating ASP.NET Core (.NET 5) service or web application.

What did you expect to see?

I would like to see some better guidance and recommendations in the documentation about the creation and management of the ActivitySource within my application.

Should I use the built in ActivitySource created by ASP.NET Core, using something like:

```
using (var activity = Activity.Current.Source?.StartActivity("DoStuff"))
{
    //Do stuff
}

```
(is this a good approach?)

Or should I create one global ActivitySource that I use when I create my own activities?

Should I have one ActivitySource for my entire application or should I create one per class? Or when should I create multiple sources?

For background jobs, what is the best practice to tie a new activity to an existing trace?

Is this a good approach? (I guess I need to have the "isremote" set to true) or are there a better way of assigning the trace parent to an activity in a different process?

```
                var traceid = evnt.MetaData["traceid"];
                var spanid = evnt.MetaData["spanid"];

                parentContext = new ActivityContext(
                        ActivityTraceId.CreateFromString(traceid),
                        ActivitySpanId.CreateFromString(spanid),
                        ActivityTraceFlags.Recorded,
                        isRemote:true);

            using (var activity = activitySource.StartActivity("ProjectionService.HandleEvent", ActivityKind.Consumer, parentContext))
           {  }

```

I think this could also be better documented:

**Comment by joaopgrassi** [comment]
> Or should I create one global ActivitySource that I use when I create my own activities?

> Should I have one ActivitySource for my entire application or should I create one per class? Or when should I create multiple sources?

I believe you should create the `ActivitySource` once, with the name/version of your app, like instructed here: [Instrumenting a library/application with .NET Activity API](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#instrumenting-a-libraryapplication-with-net-activity-api) and re-use it across your app to create new activities.

> For background jobs, what is the best practice to tie a new activity to an existing trace?

I also believe that starting a new activity should already populate the parent with the current activity, but you can override this as you did by using the overload that accepts the `ActivityContext`, as in here: [Activity creation options](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#activity-creation-options).

Not sure that helps much?

**Comment by JoeMarkov** [comment]
Thanks, I eventually figured that out about the strategies for ActivitySoruce.

For the documentation I still think a "best practices/does and don'ts would be useful as it is a bit confusing from time to time on how to architecture OTEL in a larger app.
