### ISSUE TITLE
Question: Improve documentation about Baggage

### ISSUE THREAD

**Issue by JoeMarkov** [open-telemetry/opentelemetry-dotnet#2117]
# Question

What did you expect to see?

I am trying to understand the concept of Baggage and I find the documentation here and in other places is very lacking and confusing.  What I would like to see included is:

1. Some more real-life example use-cases of actual baggage data that is sent between services (like 5-10 use-cases) 
2. Better mentioned that Baggage is not tied to spans/activities,.
3. The baggage lifecycle. Are baggage by default "global/static" that is passed on every request? 
4. How do I create baggage data that is passed across services that are request dependent, like UserID or tokens? (using Processor?)
5. Better and clearer mention that Baggage data is not passed to the collector backend.

ps, keep up the good work!

**Comment by prasadbhagwat93** [comment]
These are the information I have gathered so far, this could help someone. 

1. Baggage API is different from Activitiy.Baggage. In Otel Baggage Api is not tied to signals (traces, metrics, baggage are signal in Otel specification). Actitivity.Baggage is tied to "trace" signal
2. Otel sdk is shipped with baggagepropagator and is enabled by default but we have to propagate manually or have someone call it. Available instrumentation (Asp.netcore, http) etc does the propagation including baggage. 
3. Baggage's are not global or static. They are tied to the context (asynclocal). So every request has own Baggage
4. and obviously baggage data wont be shown in traces unless you explicitly set as tags

**Comment by cijothomas** [comment]
I think this is already covered in https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api#baggage-api. If something is missing, please re-open or better - send a PR improving the wording. Thanks!
