### ISSUE TITLE
How can I set a custom HttpMessageHandler for the underlying gRPC request on OtlpTraceExporter (netstandard2.1)

### ISSUE THREAD

**Issue by alexbrina** [open-telemetry/opentelemetry-dotnet#2120]
Hi, I have setup an on-prem Elastic stack (elasticsearch + apm-server + kibana) and configured secure communication between elastic services. For convenience all server certificates are self-signed and were create using Elastic utility scripts.

Now for my application to communicate with this apm-server I need to define a custom HttpMessageHandler so I can bypass CA verification, as I won't be able to install the generated CA.crt as Trusted Root Certificate in all deployment servers.

I see that gRPC itself have an option for passing custom handler but I couldn't find a way to set it through oltp exporter options. Is it possible? Any sugestion on how to overcome this limitation?

**Comment by cijothomas** [comment]
This is currently not supported in the Otlp Exporter.
