### ISSUE TITLE
Accessing services in filters/enrichers

### ISSUE THREAD

**Issue by Code-Grump** [open-telemetry/opentelemetry-dotnet#2121]
# How do you use services registered in the application service provider from filters and enrichers?

I'm trying to write a filter for HTTP messages being sent by a client. The filter wants to consider information available in services which are registered in the application's service provider. 

I was hoping to find something like an overload on `AddHttpClientInstrumentation` which accepts a delegate of `Action< IServiceProvider, HttpClientInstrumentationOptions>` or the `HttpClientInstrumentationOptions.Filter` delegate to pass an `IServiceProvider` along with the request, but so far I've not seen a way to include registered services in these extension-points.

**Comment by tillig** [comment]
[PR to fix `AddHttpClientInstrumentation`](https://github.com/open-telemetry/opentelemetry-dotnet/pull/3051)
