### ISSUE TITLE
Support using gRPC to Jaeger Collector from Jaeger Exporter

### ISSUE THREAD

**Issue by js8080** [open-telemetry/opentelemetry-dotnet#2122]
# Feature Request

**Is your feature request related to a problem?**
The current Jaeger Exporter only allows communicating to a Jaeger Agent and therefore requires use of UDP. UDP has size limitations so if someone wants to record Spans that exceed the relatively small UDP size limit, they are stuck.

In the Jaeger C# Client, one can use the HTTP Sender or gRPC Sender to bypass the Jaeger Agent and go straight to the Jaeger Collector with HTTP or gRPC which have higher limits on maximum Span size.

Also see similar related issue #2054

**Describe the solution you'd like:**

The Open Telemetry Jaeger Exporter should have the same support to bypass the Jaeger Agent and send straight to the Jaeger Collector. I personally prefer gRPC but supporting both gRPC and HTTP would be useful for others I am sure.

**Describe alternatives you've considered.**

If one wants to use Open Telemetry, I am not aware of any alternatives at the moment.

**Comment by cijothomas** [comment]
Closing as no new features should be added to Jaeger Exporter given its upcoming deprecation. https://github.com/open-telemetry/opentelemetry-dotnet/pull/4270
