### ISSUE TITLE
How can I Listen diagnostics event using OTel?

### ISSUE THREAD

**Issue by mehdihadeli** [open-telemetry/opentelemetry-dotnet#2140]
Hi, 
I want to listen to my diagnostics event with using Otel, I think in previous version you had a `ListenerHandler` for doing this purpose but in last version this class has been private.
 [This article](https://jimmybogard.com/building-end-to-end-diagnostics-opentelemetry-integration/) used this approach, but in newer version don't work.

**Comment by cijothomas** [comment]
Check the doc here (https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#writing-own-instrumentation-library) if you are looking to write a new instrumentation library.

`ListenerHandle` was not a OpenTelemetry concept and was removed from public API. You may copy the code for your project, or if you are hosting the instrumentation library in the -contrib repo, you can leverage it as a shared file (as done by many instrumentations in the contrib repo)
