### ISSUE TITLE
Remove .NET Core 2.1 support

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2156]
Similar to https://github.com/open-telemetry/opentelemetry-dotnet/issues/2138, we can cut .NET Core 2.1 from support matrix, as .NET Core 2.1 is end of life next month (https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/).

Since most of the projects list NETSTANDARD2.0 as the supported one, and not .NETCore2.1, the changes may be minimal, and mostly restricted to CI/Tests.

**Comment by joaopgrassi** [comment]
Is there still work to be done for this @cijothomas? I'd be happy to help if there's something left to remove.

**Comment by cijothomas** [comment]
This can be closed now. Not aware of anything pending for this. Thanks for checking!
