### ISSUE TITLE
[Proposal] Remove builders/factories

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#217]
Builders came into OpenCensus/OpenTelemtery .NET as literal a result of the translation from Java.

In .NET
- builders are not typical: ctor arguments are. Patterns like `SpanContext.Create` are also not typical and ctor arguments are preferrable
- builders require allocation and allocation on the hot path increases GC pressure. So builders are bad for perf.
- When creating something (like span) is complicated, some kind of options, or fluid patterns are a better option.

I propose to consistently remove builders/factor methods when they are used for simple things and decide on a case-by-case basis what to do with complicated stuff (SpanBuilder)

**Comment by SergeyKanzhelev** [comment]
I think this is done. Please re-open otherwise
