### ISSUE TITLE
Please provide a sample/documentation for using Prometheus

### ISSUE THREAD

**Issue by alexanderjung-sdxag** [open-telemetry/opentelemetry-dotnet#2170]
# Question

I have successfully set up exporting to Zipkin, Jaeger and used Grafana with Jaeger as data source. 
But I wasn't able to use Prometheus. The exporter that was once there is gone since earlier this year.

Could you please provide some sample/introduction on how to use Prometheus, perhaps through some collector?

Thanks.

**Comment by cijothomas** [comment]
metrics is WIP. A very basic prometheus example is here : https://github.com/open-telemetry/opentelemetry-dotnet/blob/metrics/examples/Console/TestPrometheusExporter.cs

(Metrics work is occuring in metrics branch. We haven't published any packages to nuget.org yet which support metric. its beginning to happen starting this week.)
