### ISSUE TITLE
Build on local machine 

### ISSUE THREAD

**Issue by bnayae** [open-telemetry/opentelemetry-dotnet#2195]
# Question

**Describe your environment.**

Visual Studio 2019 on windows.

**What are you trying to achieve?**

Build the solution on local machine.

## Additional Context

What do I need in order to build the solution on local machine?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md#development-environment Please see if this helps! Its been a while since we updated this section, so do let us know if you face issues!
