### ISSUE TITLE
Unexpected traceparent header (parent span ID) when using HttpClient

### ISSUE THREAD

**Issue by josh-endries** [open-telemetry/opentelemetry-dotnet#2245]
I am manually instrumenting an Azure Function using .NET 5 and I'm seeing some behavior I don't understand. Within the Function invocation, my `Activity.Current` is correct. When I make an HTTP call via `HttpClient`, however, the current activity's ID is not propagated--however the trace and baggage are. Somewhere a new span or ID is being created.

This is my Activity.Current in the Function method during invocation:

![image](https://user-images.githubusercontent.com/1500571/128909480-1e2cd610-7142-43a0-a052-182f9dedf361.png)

These are the headers I receive in my HTTP service (from the next line in the above screenshot):

![image](https://user-images.githubusercontent.com/1500571/128909540-5a30968b-f020-4174-8ef7-c88cbdee881f.png)

I would expect the traceparent header to contain "2d3f..." but instead it contains "4b9c..." instead.

In my console, I see one span during this process, for the Function invocation, which has the correct values in it for Activity.Id and Activity.ParentId.

The trigger for this Function doesn't include tracing info so I manually created some middleware to create Activity.Current from the trigger data:

    using (var activitySource = new ActivitySource(activitySourceName, "1.0"))
    {
        var traceId = traceInfo.TraceId;
        var parentSpanId = traceInfo.SpanId;

        var activityContext = new ActivityContext(
            traceId: ActivityTraceId.CreateFromString(traceId),
            spanId: ActivitySpanId.CreateFromString(parentSpanId),
            traceFlags: ActivityTraceFlags.Recorded,
            traceState: traceInfo.State,
            isRemote: false
        );

        using (var activity = activitySource.StartActivity($"Azure Function invocation", ActivityKind.Server, activityContext))
        {
            // activity can be null here if there are no listeners.
            if (activity != null)
            {
                foreach (var baggage in traceInfo.Baggage) activity.AddBaggage(baggage.Key, baggage.Value);
                Activity.Current = activity;
            }

            try
            {
                await next(context);
            }
            catch (Exception e)
            {
                throw;
            }
        }
    }

This is how I create the trace provider:

    var openTelemetryTraceProvider = Sdk.CreateTracerProviderBuilder()
        .AddSource($"{functionInfo.MethodInfo.DeclaringType.FullName}.{functionInfo.MethodInfo.Name}")
        .SetResourceBuilder(resourceBuilder)
        .AddHttpClientInstrumentation()
        //.SetSampler(new AlwaysOnSampler())
        .AddConsoleExporter()
        .AddOtlpExporter(opt => opt.Endpoint = new Uri(endpoint))
        .Build()
        ;

From reading other things online I learned that there may be "hidden" client spans created by HttpClient, but I am not seeing those in my console. I'm not sure what else would be doing this. It seems odd that the trace ID and baggage work but the ID is replaced, so it definitely seems to know about the trace info, just not using the span info I was expecting.

**Comment by josh-endries** [comment]
I added all the applicable OT projects to my solution to trace through what's happening. `HttpHandlerDiagnosticListener.OnStartActivity` receives an activity with a different span ID but its parent ID is set to my `Activity.Current.SpanId`.

So the flow is:

1. Event comes in, trigger fires.
2. I assign parent and trace ID to `Activity.Current` based on (mock) data in the event and create a new span ID.
    a. Id: "00-00000000111111110000000011111111-85b78a676cca774f-01"
    b. ParentId: "00-00000000111111110000000011111111-2222333322223333-00"
3. Function executes, same `Activity.Current`.
4. Function calls `HttpClient.SendAsync`.
5. `OnStartActivity` is called
    a. Id: "00-00000000111111110000000011111111-86aa962ccf200b47-01"
    b. ParentId: "00-00000000111111110000000011111111-85b78a676cca774f-01"
5. `OnStartActivity` is called (again)
    a. Id: "00-00000000111111110000000011111111-86aa962ccf200b47-01"
    b. ParentId: "00-00000000111111110000000011111111-85b78a676cca774f-01"
6. My web server receives header "traceparent: 00-00000000111111110000000011111111-86aa962ccf200b47-01"
7. `OnStopActivity` is called
    a. Id: "00-00000000111111110000000011111111-86aa962ccf200b47-01"
    b. ParentId "00-00000000111111110000000011111111-85b78a676cca774f-01"
7. `OnStopActivity` is called (again)
    a. Id: "00-00000000111111110000000011111111-86aa962ccf200b47-01"
    b. ParentId "00-00000000111111110000000011111111-85b78a676cca774f-01"
Web request completes and Function continues, completes.
My middleware disposes my `activity` object.
The console exporter exports my `activity`.

Other than the odd double OnStart/Stop calls, this seems correct, however the intermediate span (86aa962ccf200b47) is never exported.

**Comment by josh-endries** [comment]
I think I figured it out by starting over with an empty console app and reimplementing things until something broke.

Originally I was creating multiple TraceProviderBuilder objects, one for each Function within the Function App. I did it that way because each builder requires a single resource which maps to a single "service". It seemed intuitive that each Function seems like a service, with multiple types of spans inside it, and the Function App being the service namespace. I basically created a separate ResourceBuilder, TracerProviderBuilder and TracerProvider for each Function within my Function App, each of which had HTTP instrumentation and console export added, and held on to them throughout the life of the application. When I refactored to use a single resource and builder, I started seeing both spans in the console export. However, it seems as though one cannot have multiple builders or providers, or exporters or...something.

So my question then is how is the service name/namespace split intended in this situation? If the process is the service, meaning the Function App, and it needs to be a singleton/global (even though it isn't implemented that way), how should the individual Functions themselves be represented?

**Comment by josh-endries** [comment]
I ended up making a Function v3 middleware component and just did everything in there (activity & telemetry), except adding the source to the tracer builder. I just added "azure.function.*" attributes to identify the Function and invocation, which will work well enough for now...

**Comment by nosalan** [comment]
It seems that creation of those unexpected extra spans in HttpClient was made configurable https://github.com/dotnet/runtime/issues/41072#issuecomment-879395715
