### ISSUE TITLE
`OtlpMetricsExporter` should not reference `BatchExportProcessorOptions<Activity>`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet#2246]
Currently the `OtlpMetricsExporter` has a `OtlpExporterOptions` field which contains a `BatchExportProcessorOptions<Activity>` field.

`OtlpMetricsExporter` should not reference `BatchExportProcessorOptions<Activity>` as it is intended for tracing.

It can be fixed e.g. by adding another generic parameter to `BaseOtlpExporter` for the option type could differ for `OtlpMetricsExporter` and `OtlpTraceExporter`.

Found when working on https://github.com/open-telemetry/opentelemetry-dotnet/pull/2219

**Comment by vishweshbankwar** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/4527 will handle this.
