### ISSUE TITLE
Implement multi-processor registration on Tracer 

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#226]
https://github.com/open-telemetry/opentelemetry-specification/blob/7d7c3aa74f706b7b5e5c632e475ccbc2289c106f/specification/sdk-span-processors.md

>Span processors can be registered directly on SDK Tracer and they are invoked in the same order as they were registered.

**Comment by z1c0** [comment]
Depends on https://github.com/open-telemetry/opentelemetry-specification/issues/304
