### ISSUE TITLE
Generate NuGet package for types defined in opentelemetry-proto?

### ISSUE THREAD

**Issue by yhvicey** [open-telemetry/opentelemetry-dotnet#2271]
# Feature Request

**Is your feature request related to a problem?**

No

**Describe the solution you'd like:**

As the OTLP uses [open-telemetry/opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto) to define types used by OTLP, and [OpenTelemetry.Exporter.OpenTelemetryProtocol](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol) also used proto files defined there, is there any plan to add this repo as this repo's submodule and publish corresponding NuGet package as well?

**Comment by Kielek** [comment]
There is no plan for this. Closing per https://github.com/open-telemetry/opentelemetry-dotnet/discussions/5794#discussioncomment-10456639
