### ISSUE TITLE
When does Opentlemetry.NET SDK support  EntityframeworkCore tracing Collector?

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#229]

**Comment by lmolkova** [comment]
For the next several months we are focusing on shipping production-ready stable version of core components. We'll be looking into extending auto-collectors after that.

**Comment by cijothomas** [comment]
Duplicate of: https://github.com/open-telemetry/opentelemetry-dotnet/issues/79

**Comment by lmolkova** [comment]
Closing as duplicate
