### ISSUE TITLE
OTLP Exporter for metrics sending Delta Metrics despite setting IsDelta to False

### ISSUE THREAD

**Issue by jammiemil** [open-telemetry/opentelemetry-dotnet#2290]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 1.0.2`):
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/Console/TestMetrics.cs
1.2.0-alpha2

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can
find this information from the `*.csproj` file):

netcoreapp3.1

## Symptom

Using sample code before we start instrumenting our application and the OTLP Exporter is sending out Delta metrics rather than cumulative despite setting IsDelta to False, We are using the [Telegraf OTLP input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/opentelemetry) to pull receive these metrics and it currently only supports cumulative metrics, all Delta metrics are dropped. Issue occurs with Counter metrics, Gauge metrics are retrieves successfully as they don't have Delta's

**What is the expected behavior?**
Outputs have been captured using the [otel collector](https://github.com/open-telemetry/opentelemetry-collector) in debug mode
```
Metric #2
Descriptor:
     -> Name: counter
     -> Description: A count of things
     -> Unit: things
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE 
NumberDataPoints #0
Data point attributes:
     -> tag1: STRING(value2)
     -> tag2: STRING(value2)
StartTimestamp: 2021-08-26 20:08:32.8528978 +0000 UTC
Timestamp: 2021-08-26 20:08:33.8846376 +0000 UTC
Value: 179742600
```

**What is the actual behavior?**

```
Metric #2
Descriptor:
     -> Name: counter
     -> Description: A count of things
     -> Unit: things
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_DELTA
NumberDataPoints #0
Data point attributes:
     -> tag1: STRING(value2)
     -> tag2: STRING(value2)
StartTimestamp: 2021-08-26 20:08:32.8528978 +0000 UTC
Timestamp: 2021-08-26 20:08:33.8846376 +0000 UTC
Value: 179742600
```

## Reproduce

Recreated using:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/Console/TestMetrics.cs

with flags:
Examples.Console.exe metrics --runtime 600000 --g true --useExporter otlp --defaultCollection 1000 --d false --c true --u false

## Additional Context

This is our second attempt at exporting metrics on the 1.2 alpha, When we couldnt resolve our issues with the prometheus exporter we tried the OTLP Exporter.

We are just starting to Instrument this application and whilst the OpenTelemetry-dotnet package doesn't have mainstream metrics support yet we are hoping to be able to use one package for metrics/logs/traces to avoid bloat so looking to be early adopters of this functionality!

**Comment by jammiemil** [comment]
Hmm ok thats odd that you didnt have the same experience. I will revert back and see if we have an issue with the .net package we were using, although to be honest at this point we probably wont dwell on it too much as we can use the prometheus exporter in line with other apps we are monitoring once the #type issue is resolved.

Thanks for your help!

**Comment by cijothomas** [comment]
> Hmm ok thats odd that you didnt have the same experience. I will revert back and see if we have an issue with the .net package we were using, although to be honest at this point we probably wont dwell on it too much as we can use the prometheus exporter in line with other apps we are monitoring once the #type issue is resolved.
> 
> Thanks for your help!

Okay! Will have the fixed prometheus ready this friday.
