### ISSUE TITLE
Spans with ends and branching?

### ISSUE THREAD

**Issue by SebastianStehle** [open-telemetry/opentelemetry-dotnet#2304]
# Question

**Describe your environment.**

My use case is an IOT application. It has a list of various steps until a signal from the sensor arrives at the client:

1. Proxy (transforms incoming messages)
2. Kafka
3. RuleServer (applies)
4. Kafka
5. Notifo (handles notifications)
6. Queues, queues, queues
7. Notifications to various channels.

The problem I struggle most to understand is step 7, because a single IOT message could create several notifications for multiple users and multiple channels (SMS, Email, WebPush, MobilePush, WhatsApp)

**What are you trying to achieve?**

I would like to track the full message flow from end to beginning. My problem is that I do not know what the end is. In a normal use case with a single user and a single channel, I could argue that the end is when the notification has been sent to the user or has arrived, but I do not know this in this context.

In this case it is too difficult to track when all notifications have been sent to all users or have been failed.

From what I understand, in OpenTelemetry a Span always has an end and a beginning. But I do not understand what happens when a span has no end (because it cannot be measured) or how to "fan out" a span (for my different channels).

**Comment by reyang** [comment]
@SebastianStehle these are great general questions, not specific to .NET.

Currently the OpenTelemetry community is working on the semantic convention which will give clarity on how these async messaging/notification scenario would work, and how to handle batching/retry. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md

There is also "Instrumentation: Semantics" SIG which you can join https://github.com/open-telemetry/community#special-interest-groups.
