### ISSUE TITLE
OtlpExporter<LogRecord>?

### ISSUE THREAD

**Issue by pengweiqhca** [open-telemetry/opentelemetry-dotnet#2315]
Is still no way to export logs through OpenTelemetryProtocol now?

**Comment by cijothomas** [comment]
None. The OTLP Log Exporter is WIP https://github.com/open-telemetry/opentelemetry-dotnet/pull/1964 . We are focusing primarily on metrics till it gets stable (~Nov 2021), and anything related to logs is coming *after* Metric Stable only.
