### ISSUE TITLE
Not found OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule package from nuget

### ISSUE THREAD

**Issue by carldai0106** [open-telemetry/opentelemetry-dotnet#2318]
# Feature Request

I am using .net framework 4.6.2 and Asp.net WebApi and integrate OpenTelemetry;
When I run my webapi to get a error; OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule  dll is missing.
Then I want to get OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule package from nuget, but it is not exists on nuget.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2259#issuecomment-905917754

**Comment by cijothomas** [comment]
Duplicate of @2259
