### ISSUE TITLE
HttpClient instrumentation does not work if a HttpClient call is made before configuring OpenTelemetry

### ISSUE THREAD

**Issue by cabadam** [open-telemetry/opentelemetry-dotnet#2324]
# Bug Report

NuGet Package: https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http/1.0.0-rc7

Runtime version: net471

## Symptom

The HTTP client instrumentation does not work if an HttpClient call has been made prior to telemetry being configured.

**What is the expected behavior?**

Calls to HttpClient after should emit traces after OpenTelemetry is configured.

**What is the actual behavior?**

No traces were generated.

## Reproduce

https://github.com/cabadam/otel-http/blob/master/otel-http/Program.cs

## Additional Context

As in source control above, the console will print the Activity that gets created for the PostAsync at the last line of the program.  However, if line 15 is uncommented (so, a call on HttpClient is made BEFORE configuring open telemetry), then the second HttpClient call stops generating an activity.

We have tried disposing of the current HttpClient object and creating a new one after configuring open telemetry, but that did not change behavior.

**Comment by cijothomas** [comment]
@utpilla Could you take a look at this?

**Comment by cabadam** [comment]
As an additional data point, I ran the exact same Program.cs as .NET Core 3.1, and that seems to behave as I expected (logging an Activity even when both HttpClient calls are present).

**Comment by utpilla** [comment]
I have it repro-ed locally. This is specific to HttpClient instrumentation for .NET Framework only.

**Comment by CodeBlanch** [comment]
I would say this is working as designed but there might be something we can do to support it, or perhaps throw an error if we detect the invalid state when the tracer provider is being configured? I'll also take a look.

**Comment by CodeBlanch** [comment]
OK just to level set on this issue.

* This works fine (1 span written out to Console):

```csharp
        static async Task Main(string[] args)
        {
            HttpClient client = new HttpClient();

            ////await client.PostAsync($"http://localhost/", new StringContent("dummy data")).ConfigureAwait(false);

            var tracerProvider = Sdk.CreateTracerProviderBuilder()
                .AddSource(Assembly.GetExecutingAssembly().GetName().Name)
                .AddHttpClientInstrumentation()
                .AddConsoleExporter()
                .Build();

            await client.PostAsync($"http://localhost/", new StringContent("dummy data")).ConfigureAwait(false);
        }
```

* This does not work (0 spans written out to Console):

```csharp
        static async Task Main(string[] args)
        {
            HttpClient client = new HttpClient();

            await client.PostAsync($"http://localhost/", new StringContent("dummy data")).ConfigureAwait(false);

            var tracerProvider = Sdk.CreateTracerProviderBuilder()
                .AddSource(Assembly.GetExecutingAssembly().GetName().Name)
                .AddHttpClientInstrumentation()
                .AddConsoleExporter()
                .Build();

            await client.PostAsync($"http://localhost/", new StringContent("dummy data")).ConfigureAwait(false);
        }
```

The reason for that is a bit convoluted:

* `HttpClient` on .NET Framework wraps `HttpWebRequest`
* `HttpWebRequest` has a field [_ServicePoint](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System/net/System/Net/HttpWebRequest.cs#L166)
* `_ServicePoint` is [initialized once and then reused](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System/net/System/Net/HttpWebRequest.cs#L3303)
* [ServicePointManager.FindServicePoint](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System/net/System/Net/ServicePointManager.cs#L794) uses static [s_ServicePointTable](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System/net/System/Net/ServicePointManager.cs#L64) field which is where we hook our instrumentation during [PerformInjection()](https://github.com/open-telemetry/opentelemetry-dotnet/blob/34d8332a809b6258f481fdd07deea1b52b5b080d/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs#L456)

So if an HttpClient instance initializes and gets a `ServicePoint` before our hook we won't trap any of its calls.

It was an easy enough change to hook anything existing when starting up so I opened a PR (#2364).
