### ISSUE TITLE
CompositeTextMapPropagator.Fields are always empty

### ISSUE THREAD

**Issue by wite27** [open-telemetry/opentelemetry-dotnet#2328]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.0.2`):

```
OpenTelemetry 1.1.0
OpenTelemetry.Api 1.1.0
OpenTelemetry.Extensions.Hosting 1.0.0-rc7
```

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can find this information from the `*.csproj` file):

 `net5.0` 

## Symptom

Using [CompositeTextMapPropagator](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Context/Propagation/CompositeTextMapPropagator.cs) results in empty Fields, so i'm unable to properly clear carrier object before reusing (as described in [Fields spec](https://github.com/open-telemetry/opentelemetry-specification/blob/7891a4216116d460591ef15437d0fe7d35309c2c/specification/context/api-propagators.md#fields)).

**What is the expected behavior?**

CompositeTextMapPropagator.Fields returns union of underlying propagators' fields

**What is the actual behavior?**

CompositeTextMapPropagator.Fields always returns empty set

## Reproduce

See https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Context/Propagation/CompositeTextMapPropagator.cs#L41

## Additional information

I faced this issue when implementing tracing on top of Confluent.Kafka. After error on consume, i'm sending message to the delayed retry topic, and after delay this message is produced to original topic again. I want to clear previously set tracing headers and properly set new ones (but preserve other headers from original message). For now, it's impossible, because i couldn't differ tracing headers from application-defined headers.

**Comment by stevejgordon** [comment]
@open-telemetry/dotnet-maintainers From my understanding after reading the spec and reviewing the existing propagators, this looks like a legitimate bug with a fairly simple fix. If you agree with the expectations here, it looks like a good issue for me to pick up.
