### ISSUE TITLE
Publish the docs to readthedocs.io

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#2333]
# Feature Request

**Is your feature request related to a problem?**

The current markdown docs in the GitHub repo might not be very user friendly / consumable.

**Describe the solution you'd like:**

Publish the docs to readthedocs.io, similar like what OpenTelemetry C++ is doing https://opentelemetry-cpp.readthedocs.io/en/latest/api/Overview.html.

**Comment by mic-max** [comment]
Working on it 👍
https://opentelemetry-dotnet.readthedocs.io/en/latest/

**Comment by cartermp** [comment]
Worth noting that the otel website docs are much more complete now: https://opentelemetry.io/docs/instrumentation/net/

With additional docs content from this repo (modified a bit) in PR: https://github.com/open-telemetry/opentelemetry.io/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+.NET

**Comment by tomkerkhove** [comment]
This is super helpful, thank you!

**Comment by mic-max** [comment]
> Worth noting that the otel website docs are much more complete now: https://opentelemetry.io/docs/instrumentation/net/
> 
> With additional docs content from this repo (modified a bit) in PR: https://github.com/open-telemetry/opentelemetry.io/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+.NET

Thanks for pointing this out! I am new to the space and didn't know about the docs on this website. I will move changed I made in some (now closed) PRs that I linked to this issue in the opentelemetry.io repository instead!

**Comment by cijothomas** [comment]
@mic-max We'll need to discuss this more. The docs and associated projects must be in the same repo as source code, to ensure they are always accurate. I am not sure how easy is it to achieve this when docs/projects are elsewhere. Maybe we can learn from what other languages (C++, Python) are doing - it looks to me like they have whole docs in the same repo as product. But will need to learn more.

**Comment by mic-max** [comment]
> they have whole docs in the same repo as product. But will need to learn more.

Agreed. It looks like there's two ways SIGs are publishing docs to opentelemetry.io.
- Using [git-submodules](https://github.com/open-telemetry/opentelemetry.io/tree/main/content-modules): Go, PHP, Python, Ruby, Specification
- Using the [opentelemetry.io repository content/en/docs/instrumentation](https://github.com/open-telemetry/opentelemetry.io/tree/main/content/en/docs/instrumentation) directory: C++, Erlang, Java, JavaScript, .NET, Rust, Swift

**Comment by cartermp** [comment]
Relevant conversation here: https://github.com/open-telemetry/opentelemetry.io/issues/989
