### ISSUE TITLE
Should the Meter's version include revision?

### ISSUE THREAD

**Issue by verdie-g** [open-telemetry/opentelemetry-dotnet#2341]
In the [OpenTelemetry spec](https://github.com/open-telemetry/opentelemetry-specification/blob/09944db81a980b40e25b3d1bfd247b30596272da/specification/metrics/api.md#get-a-meter) it states
> version (optional): Specifies the version of the instrumentation library (e.g. 1.0.0).

It seems like the format of the version is not strict, there is only an example with contain major.minor.build (1.0.0).

In .NET, `Assembly.GetName().Version.ToString()` is used which return major.minor.build.revision.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/6b7f2dd77cf9d37260a853fcc95f7b77e296065d/src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentation.cs#L36
https://github.com/open-telemetry/opentelemetry-dotnet/blob/67b6a83932392d39553e06471f837bae1c463c95/src/OpenTelemetry.Instrumentation.Http/HttpClientMetrics.cs#L31
https://github.com/open-telemetry/opentelemetry-dotnet/blob/7c611c8537d4d2c780dbc5fa999a3b3b7fd0d12d/src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreMetrics.cs#L31

So should the version include revision and what does it change?

**Comment by cijothomas** [comment]
This is not strictly defined in the spec and no validation is done in the SDK. From SDK perspective, version is just a "string". As of today, there is no ability to turn on/off an instrumentation (Meter/ActivitySource) based on its version.
