### ISSUE TITLE
How to implement .net agent in .net framework 

### ISSUE THREAD

**Issue by Saipavan018** [open-telemetry/opentelemetry-dotnet#2343]
Hi

Actually instrumented .net framework application using opentelemtry
 How to implement .net custom agent for .net framework using opentelemtry

**Comment by cijothomas** [comment]
Sorry, the question is not clear.. There is no "agent" shipped from this repo.
"Agent" term is defined in Otel Collector  - https://github.com/open-telemetry/opentelemetry-collector, I suppose you meant to ask about this?

Please reopen with clarification, if you intended to ask something about this repo.
