### ISSUE TITLE
Support for Metric Views

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2359]
Opening an issue to track overall feature - [Metric Views](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view).
Sub issues:
1. Ability to drop selected instruments. (At present we allow select/ignore per Meter) - this will allow user to pick selected instruments within a Meter, and drop others.
2. Ability to select a subset of Tags(Attributes) for aggregation.
3. Ability to change default aggregation 
   3.a Ability to provide options to Histogram (i.e custom bounds)
4. Ability to add additional dimensions from Context/Baggage.

**Comment by timmydo** [comment]
3a-custom histogram bounds is a required go-live feature for us. thanks

**Comment by cijothomas** [comment]
> 3a-custom histogram bounds is a required go-live feature for us. thanks

ack. This is asked by other customers as well. So expect us to treat it highest priority :) Will share timelines/milestones by next SIG meeting (tuesday)

**Comment by sudeepagarwal** [comment]
Do we have an ETA for custom histogram bounds feature?

**Comment by cijothomas** [comment]
The ability to change histogram bounds is now part of main branch (https://github.com/open-telemetry/opentelemetry-dotnet/pull/2432).
It'd be part of the coming release, which I am trying to release tomorrow to nuget. If not, you can still use the daily build from myget which would contain this feature as well.

**Comment by cijothomas** [comment]
1.2.0-beta1 added support for views and hence 1,2,3a is considered done now.

**Comment by cijothomas** [comment]
Closing this issue in favor of specific ones opened for each subitem.
