### ISSUE TITLE
Imposible to add trace source with empty name

### ISSUE THREAD

**Issue by AndreyTretyak** [open-telemetry/opentelemetry-dotnet#2366]
# Bug Report

I'm using `OpenTelemetry 1.0.2` and `OpenTelemetry 1.2.0-alpha2`
Runtime version `net5.0` and `net6.0`.

## Symptom
Not sure if it's a problem with .NET runtime or in this library, but .NET runtime heavily use the default `ActivitySource` with an empty name and version, for the activities that are created without explicit `ActivitySource` and they are unlikely to change this since it would be a breaking change. Here some explanation from the team: https://github.com/dotnet/runtime/issues/48533#issuecomment-782402559

This default `ActivitySource` is even used for activities that wrap web requests in Kestrel, which would be the activity that most people are interested in. 
Activity creating in Kestrel could be found here https://github.com/dotnet/aspnetcore/blob/d0465d864e6c3900b8316ec81311558b994a961c/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L277

**What is the actual behavior?**

So it's logical that we need a way of listening for those events, but when you do something like this:
```CSharp
OpenTelemetry.Sdk.CreateTracerProviderBuilder()
  .SetSampler(new AlwaysOnSampler())
  .AddSource(string.Empty)
  ...
```
It would throw `ArgumentException` because of this check:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/073ce6cedceb4e9cd1aa946afe7c5e388011c166/src/OpenTelemetry/Trace/TracerProviderBuilderBase.cs#L69

**What is the expected behavior?**

I think this check should be replaced with the following code:
```CSharp
if (name == null)
{
  throw new ArgumentNullException($"{nameof(names)} contains null string.");
}
```
To allow listening for sources with empty names.

## Reproduce

For example, both this code:
```CSharp
using System.Diagnostics;

var listener = new ActivityListener();
listener.ShouldListenTo += source => 
{
	Console.WriteLine("Listening source with name '{0}' and version '{1}'", source.Name, source.Version);
	return true;
};

ActivitySource.AddActivityListener(listener);

var activity = new Activity("Test");
activity.Start();
activity.Stop();
```
and this code:
```CSharp
using System.Diagnostics;

var listener = new ActivityListener();
listener.ShouldListenTo += source => 
{
	Console.WriteLine("Listening source with name '{0}' and version '{1}'", source.Name, source.Version);
	return true;
};

ActivitySource.AddActivityListener(listener);

var diagnosticListener = new DiagnosticListener("TestDiagnosticListener");
var activity = new Activity("DiagnosticListenerActivity");
diagnosticListener.StartActivity(activity, null);
diagnosticListener.StopActivity(activity, null);
```

Produces the following output:
```
Listening source with name '' and version ''
```
## Additional Context
I'm fine to make this change if you are agree that it's reasonable.

**Comment by cijothomas** [comment]
The string.IsNulllOrWhiteSpace check is intentional, as subscribing to "legacy" activities by using AddSource won't yield the same result. (as ShouldSample callback is not triggered for them).

The alternate is to use `AddLegacySource`. Its used by many existing instrumentations as shown below:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/TracerProviderBuilderExtensions.cs#L58-L59 See this example on how to add support for legacy Activities (i.e the ones created without ActivitySource).

doc:
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#special-case--instrumentation-for-libraries-producing-legacy-activity

**Comment by AndreyTretyak** [comment]
Great, thank you Cijo, I'm sorry for missing this.
