### ISSUE TITLE
Baggage Enrich in AddHttpClientInstrumentation does not work

### ISSUE THREAD

**Issue by narcis-sy** [open-telemetry/opentelemetry-dotnet#2368]
Versions tried: 1.0.0-rc7/core-1.2.0-alpha3 
Runtime version .net 4.8

Sample

```
 using var tracerProvider = Sdk.CreateTracerProviderBuilder()
                .SetSampler(new AlwaysOnSampler())
                .AddSource(ReceiptsStore.TelemetrySource.Name)
                .AddHttpClientInstrumentation(
                    (options) =>
                    {
                        options.SetHttpFlavor = true;
                        options.Enrich
                            = (activity, eventName, rawObject) =>
                            {
                                var terminalId = TerminalData.TerminalId.ToString();
                                 
                                activity.AddBaggage("terminalId", terminalId);
                                Baggage.SetBaggage("terminalId", terminalId);
                                Baggage.SetBaggage("ssssss", terminalId);
                            };
                    })
                .Build();
```
Trying to enrich the Baggage via Erich does not work. The element gets added in baggage, but it is not sent out.

The only way this works is if I add it after activity start. 

Probably has something to do with how the Baggage flows between async operations. It behaves as if `HttpWebRequestActivitySource` is using an older version of Baggage.

**Comment by cijothomas** [comment]
activity.AddBaggage("terminalId", terminalId); ---> This is incorrect usage of Baggage API. Activity class already had a concept of Baggage, which is slightly different from OTel concept of Baggage.
