### ISSUE TITLE
Implement "Named Tracers and Meters"

### ISSUE THREAD

**Issue by z1c0** [open-telemetry/opentelemetry-dotnet#237]
The "Named Tracers and Meters" RFC (https://github.com/open-telemetry/oteps/blob/master/text/0016-named-tracers.md) has been approved and the subsequent spec changes are also close to approval (https://github.com/open-telemetry/opentelemetry-specification/pull/264).

OpenTelemetry language repositories now need to implement this mechanisms.

**Comment by z1c0** [comment]
Named Tracers implemented in #239.
Named Meters still TBD.

**Comment by SergeyKanzhelev** [comment]
this seems to be implemented: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/Metrics/MeterFactoryBase.cs

@cijothomas please confirm. Assigning to you to close

**Comment by cijothomas** [comment]
This is done.
