### ISSUE TITLE
Metric AggregatorStore improvements

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2374]
Opening an issue to track future improvements.

The current AggStore uses 2 data structures to find the `MetricPoint`. One is an pre-allocated array of `MetricPoint`, where the actual points are stored, and then a concurrentdictionary (2 level), to find the index within the array for a given keys/values combinations.

1. The current design requires Sorting based on keys. Based on benchmarking, this is the biggest contributor to the hot path. One potential way to improve this is to add 2 entries to the dictionary  - one with the 1st seen order of keys, and another with sorted order. If subsequent recordings are with same order as initial, it can be looked up without sort. If lookup fails, then need to sort and do *another* lookup. This might be good improvement, if user keeps providing the keys in same order.
2. Replace the inner concurrent dictionary with hashtable to avoid dual lock on writes - https://github.com/open-telemetry/opentelemetry-dotnet/pull/2339#discussion_r706997727
3. Design a totally new data structure specialized for the purpose.
4. Special case 0 tags - see discussion : https://github.com/open-telemetry/opentelemetry-dotnet/pull/2339#discussion_r711217242

Given this is purely internal implementation without any public API, this can be addressed after other high priority asks.

**Comment by cijothomas** [comment]
@utpilla is looking at implementing the item 1 to avoid sorting costs.

**Comment by cijothomas** [comment]
The most critical improvements are already shipped as part of 1.2 itself. 
Removing this from 1.3 milestone, as it can occur anytime. (1.3 is releasing in May 2022 with other improvements)

**Comment by stevejgordon** [comment]
@cijothomas Do you think there's anything left to do here, or could this be closed now?

**Comment by cijothomas** [comment]
Nothing very specific is remaining so okay to close.
(There is still some improvements for the aggregation logic for better throughput, but I'll open separate issue with specifics.)
