### ISSUE TITLE
Example of Prometheus Exporter using AspNetCore

### ISSUE THREAD

**Issue by jammiemil** [open-telemetry/opentelemetry-dotnet#2397]
# Question

Current Example for AspNetCore does not show how to set up a Prometheus Exporter for Metrics, Is it possible for one to be added?

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/AspNetCore/Startup.cs

**Comment by cijothomas** [comment]
Need to confirm if Prometheus's middleware part is working, and then modify this. We can take it around beta1-2 timelines.

**Comment by cijothomas** [comment]
Closing as this example now has prometheus example.
