### ISSUE TITLE
Support multiple MetricReaders

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2398]
We currently only allow one MetricReader (i.e one exporter allowed at same time). Spec requires adding any number of readers/exporters.

Opening this issue to track adding the multi-reader support. (Internally we may simply duplicate the whole pipeline for each reader.)

Treating this as lower priority compared to other features - Views., as most practical scenarios call for one exporter at a time.

**Comment by tomkerkhove** [comment]
+ 💯
