### ISSUE TITLE
Update OpenTracing bridge to target newest OT C# lib

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-dotnet#240]
OpenTracing 0.12.1 has been published so the OT bridge needs to be updated as well.

**Comment by bruno-garcia** [comment]
I've Opened a PR for it, but the OT change log says:

* Binary header propagation support (for Envoy)
* Improved thread-safety in GlobalTracer.IsRegistered
* Adds a boolean value to manage if a tracer has been registered in the GlobalTracer.

I'm not sure there's any code change required on the OTel side.
Could you please confirm?

**Comment by austinlparker** [comment]
@bruno-garcia Inject/Extract (see https://github.com/open-telemetry/opentelemetry-dotnet/blob/cc41648685ca5e7d4db905e463398d5050b2fc5a/src/OpenTelemetry.Shims.OpenTracing/TracerShim.cs#L61) need to be updated for binary headers. I don't believe either of the GlobalTracer changes affect the shim.

**Comment by SergeyKanzhelev** [comment]
My understanding it is closed via https://github.com/open-telemetry/opentelemetry-dotnet/pull/296 @austinlparker please reopen otherwise
