### ISSUE TITLE
Instrument name validation

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2424]
Instrument name has to be validated as per the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument). The .NET API itself does not validate this, so the SDK has to validate the instrument name (upon instrument creation), and ignore the instrument (after logging that we are ignoring an instrument due to ... reason).

For Views, which provide new name for the Metric, the validation can be done in the `AddView` itself and can throw/fail fast on AddView.

**Comment by joaopgrassi** [comment]
Hey, if no one is working on this I could take it. Seems small enough to get started with Metrics :)
