### ISSUE TITLE
ASP.NET Telemetry HttpModule for OpenTelemetry: missing from NuGet.org

### ISSUE THREAD

**Issue by MDerrickGlass** [open-telemetry/opentelemetry-dotnet#2427]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 1.0.2`):

```XML
    <PackageReference Include="OpenTelemetry">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Api">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Exporter.Console">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Exporter.Zipkin">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting">
      <Version>1.0.0-rc7</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNet">
      <Version>1.0.0-rc6</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Instrumentation.Http">
      <Version>1.0.0-rc7</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient">
      <Version>1.0.0-rc7</Version>
    </PackageReference>
```

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can
find this information from the `*.csproj` file):

ASP.NET, Framework 4.8

## Symptom

After following the [instructions for enabling OpenTelemetry in my legacy ASP.NET project](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNet/README.md), there is an unhandled application error when running the root web page (and all others, I assume).

**What is the expected behavior?**

I expect to see my normal root web page.

**What is the actual behavior?**

> Server Error in '/' Application.
> Could not load file or assembly 'OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule' or one of its dependencies. The system cannot find the file specified.

## Reproduce

As this issue is reported recently in several forums, the trick is to run any "legacy" _ASP.NET_ app (4.6.1) following the instructions in the link above.

## Additional Context

The `README.md` file contains this instruction, which is a bit ambiguous:

> OpenTelemetry.Instrumentation.AspNet requires adding an additional HttpModule to your web server. This additional HttpModule is shipped as part of OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule which is implicitly brought by OpenTelemetry.Instrumentation.AspNet.

That sounds like the module is part of the `OpenTelemetry.Instrumentation.AspNet` _NuGet_ package, but it does not appear. The continuing instructions for manually modifying the `web.config` file imply there should be a `OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.dll` file, but none is installed. If you check _NuGet_ for the package it returns a 404; indeed, [the GitHub page](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/README.md) for the `TelemetryHttpModule` source shows `package not found` next to the _NuGet_ tag.

So, it's not clear if there should be an additional _NuGet_ package for the `TelemetryHttpModule` or if it's intended to be included in the `OpenTelemetry.Instrumentation.AspNet` package. If I remove the `web.config` entry, my project "works fine" and I actually get telemetry for the _SQL_ instrumentation, just nothing for _ASP.NET_.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/1.0.0-rc7/src/OpenTelemetry.Instrumentation.AspNet/README.md please follow the instructions from 1.0.0-rc7.

The latest main has upcoming changes, that are not yet released to nuget.

**Comment by MDerrickGlass** [comment]
I confirm this fixed the issue. For anyone looking for the answer, the [new instructions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/1.0.0-rc7/src/OpenTelemetry.Instrumentation.AspNet/README.md#step-2-modify-webconfig) show the following change to `web.config`:

> OpenTelemetry.Instrumentation.AspNet requires adding an additional HttpModule to your web server. This additional HttpModule is shipped as part of Microsoft.AspNet.TelemetryCorrelation which is implicitly brought by OpenTelemetry.Instrumentation.AspNet. The following shows changes required to your Web.config when using IIS web server.

```XML
<system.webServer>
    <modules>
        <add name="TelemetryCorrelationHttpModule"
            type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule,
                Microsoft.AspNet.TelemetryCorrelation"
            preCondition="integratedMode,managedHandler" />
    </modules>
</system.webServer>
```
Thanks for the quick response!
