### ISSUE TITLE
Implement Meter

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-dotnet#2428]
# Feature Request
[Meter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#meter) has not yet been implemented. It's required per the spec to create the various instruments

Relates to #1501

**Comment by cijothomas** [comment]
The API components are part of .NET runtime through the System.Diagnostics.DiagnosticSource package. So Meter, Instruments and friends will not be part of this repo.

**Comment by cijothomas** [comment]
Please see getting started doc here: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/getting-started

**Comment by hdost** [comment]
So I saw that before, but I wasn't sure that it would work with before .NET 6 😓 . Looks like it does just fine 👍🏼
