### ISSUE TITLE
[Feature] Add export for apache skywalking

### ISSUE THREAD

**Issue by congzhangzh** [open-telemetry/opentelemetry-dotnet#2430]
# Feature Request

**Is your feature request related to a problem?**

No

**Describe the solution you'd like:**

Native support export to skywalking like support for zipkin.

**Describe alternatives you've considered.**

Skywalking add native support for otlp trace receiver

## Additional Context

I add an issue to skywalking too, https://github.com/apache/skywalking/issues/7848

**Comment by cijothomas** [comment]
For anything not required by the Otel specification, please use https://github.com/open-telemetry/opentelemetry-dotnet-contrib repo. Or you can open it in the collector contrib repo, depending on if you want direct exporter or not.

Doc showing how to write custom exporters:
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#exporter
