### ISSUE TITLE
How do you access Infrastructure Attributes from Activity.Current?

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-dotnet#2431]
# Question

I'd like to see all the tags added to my spans, including the infrastructure tags we add during startup.  I thought I would be able to do it via Activity.Current.TagObjects, but I only see the tag objects from the Enrich methods, but not the infrastructure tags set via AddAttributes

**Describe your environment.**

NET Core 3.1, Net Standard 2.0.3

**What are you trying to achieve?**

What did you expect to see?

We expected to see every tag that is being added to the span.

**Comment by TylerHelmuth** [comment]
> Its not clear what do you mean by "infrastructure tags.". Adding tags to Activity.Current, will add it to that activity. If you are looking to add some information to every telemetry, then Resource API is likely the answer - https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#resource

Ya I think its the Resource API that the method uses behind the scenes.  During service setup we are using the AddAttribute function of the SetResourceBuild to set some tags on every span:

```C#
service.AddOpenTelemetryTracing((builder) => builder
                .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("some string").AddAttributes(infrastructureTags))
```

When spans are sent to the OTEL Collector they include all the "default" tags in the `infrastructureTags` list that we passed to `AddAttributes`,  as well as any tags added later.  But strangely if I put a breakpoint in a controller and peak at `Activity.Current`, none of those tags appear.

**Comment by cijothomas** [comment]
Resource attributes are never made part of Activity. Resource is available to the exporter, and OTLP does use them.
