### ISSUE TITLE
Doc feedbacks

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2446]
Some feedbacks received offline while working with some customers:
1. Its not obvious from doc that .NET Meter is created directly (using ctor) without going through MeterProvider.
2. Its not obvious that there is need to AddSource every Meters

**Comment by cijothomas** [comment]
Another:
It must be clearly called out that an instrument must be created once, and re-used for all the measurements. Creating the instrument over and over (with same name) is incorrect and would result in telemetry drop from anything but the 1st instrument.

**Comment by findmyway** [comment]
> Some feedbacks received offline while working with some customers:
> 
> 1. Its not obvious from doc that .NET Meter is created directly (using ctor) without going through MeterProvider.
> 2. Its not obvious that there is need to AddSource every Meters

Same here. I only figure this out after searching in the source code:

https://github.com/dotnet/runtime/blob/3649506d45ad221a067d2945b212625b321de78f/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/Meter.cs#L45

**Comment by findmyway** [comment]
I'd suggest adding another short example like the one provided in [Metrics APIs Design](https://github.com/dotnet/designs/blob/main/accepted/2021/System.Diagnostics/Metrics-Design.md#library-measurement-recording-example) in the [getting started page](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/metrics/getting-started/README.md) explain the Metrics APIs first. It would be easier for first-time users (like me) to understand how SDK is built on top of APIs.

**Comment by cijothomas** [comment]
One more, very important and very common issue: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4117

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics This doc now covers this! Closing. 
Happy to get more specific feedbacks that can be added to the docs.
