### ISSUE TITLE
Prometheus - Counting endpoint calls with AspNetCoreInstrumentation

### ISSUE THREAD

**Issue by BenjaminKeffer** [open-telemetry/opentelemetry-dotnet#2480]
# Question
Hey all!
Thanks for this fantastic library. While I'm implementing the latest changes, the question came up:

Is there a simple way (e.g. using attributes) to count the total calls per endpoint in an Asp.Net Core project using AspNetCoreInstrumentation and Prometheus? By default I can't see any counters in the Prometheus output.

Thanks and best regards,
Benjamin

**Comment by BenjaminKeffer** [comment]
Thanks for your answer!
Could you explain what I need to do to count all calls per endpoint in different controllers?
So that at the end I have an overview of what is called how often?

**Comment by cijothomas** [comment]
> Thanks for your answer! Could you explain what I need to do to count all calls per endpoint in different controllers? So that at the end I have an overview of what is called how often?

Until the instrumentation libraries cover your needs, you need to create counter and increment it manually, in each controller, and provide controller name/end point/whatever things you need as tags/attributes to counter.Add() calls.
