### ISSUE TITLE
OTLP LogExporter fixes and improvements

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2482]
Opening an issue to track overall OTLP LogExporter. An initial version is ready from https://github.com/open-telemetry/opentelemetry-dotnet/pull/1964 is released as https://www.nuget.org/packages/OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs/1.0.0-rc8

Populate Body : https://github.com/open-telemetry/opentelemetry-dotnet/pull/3182
Populate Severity: https://github.com/open-telemetry/opentelemetry-dotnet/pull/3177
Severity Mapping: https://github.com/open-telemetry/opentelemetry-dotnet/issues/2888
Support Scopes:  https://github.com/open-telemetry/opentelemetry-dotnet/pull/3218, Follow up on https://github.com/open-telemetry/opentelemetry-dotnet/pull/3843#discussion_r1009642058
Map LoggerCategory: https://github.com/open-telemetry/opentelemetry-dotnet/pull/3221 --> Update (8/30) (To be tracked on #3491)
Add Example - https://github.com/open-telemetry/opentelemetry-dotnet/pull/2481 added basic example
Support Http/Protobuf - https://github.com/open-telemetry/opentelemetry-dotnet/pull/3225
Add docs #4747
Add Tests #4610 #4578 #4733
Add Benchmarks #4807

State vs StateValues - Resolved for now, but need a revisit: https://github.com/open-telemetry/opentelemetry-dotnet/pull/3186#issuecomment-1104642714 --> Update(8/30) {This is resolved as part of #4334)

**Comment by TimothyMothra** [comment]
@cijothomas I'm interested in working on this. 
I'll fully review the previous PRs before getting started.
