### ISSUE TITLE
Prometheus - "INVALID" is not a valid start token

### ISSUE THREAD

**Issue by MackNext** [open-telemetry/opentelemetry-dotnet#2487]
# Bug Report

Hi all!

When using prometheus I get the error 
`... target=http://172.28.8.168:80/metrics msg="Append failed" err="\"INVALID\" is not a valid start token"`

Then I tried to check the output with the promtool 
`curl -s http://localhost:5002/metrics | ./promtool check metrics`

Response:
`error while linting: text format parsing error in line 1: invalid metric name`

The strange thing is when I copy the content into a local text file and execute the following, the check is successful:
`cat test.txt | ./promtool check metrics`

So it seems like the content has invalid characters or a wrong charset?

## Reproduce

With the asp.net sample

**Comment by marcusjsford** [comment]
Hi @MackNext which version of the Prometheus Exporter are you using?
I have the same issue using `PackageReference Include="OpenTelemetry.Exporter.Prometheus" Version="1.2.0-beta1"`  inside a Net5.0 project using the middleware. The html being sent back to me was UTF8-BOM encoded for some reason. 

When I use the `httplistener` Prometheus endpoint the formatting is UTF8 and promtool can read it successfully.

**Comment by VCuzmin** [comment]
Greetings! I have the same problem! Any fix here? Thanks!

**Comment by asleire** [comment]
I experienced the same problem in `1.2.0-beta1`. According to the source code at the time, the response was being written with BOM. This is no longer the case in `1.2.0-beta2.1`

**Comment by cijothomas** [comment]
Closing older issues, as Prometheus Exporter has been improved a lot since this issue was originally opened.
Please open a new issue, if you still have the same problem, after upgrading to the newest available version of prometheus exporter.
