### ISSUE TITLE
SetParentId() not working once the activity has a ParentId.

### ISSUE THREAD

**Issue by Nelladel** [open-telemetry/opentelemetry-dotnet#2489]
# Bug Report

## Packages
- `opentelemetry 1.1.0`

## Frameworks
- `TargetFramework`: `netcoreapp3.1`

## Symptom

Once an activity has a `ParentId`, this cannot be modified using `activity.SetParentId(id)`. This does not happen if the activity still has no `ParentId`.

**What is the expected behavior?**

The `ParentId` of the activity should change to the `SetParentId()`'s `parentId` parameter value. 

**What is the actual behavior?**

If the activity is completely new (no previous `ParentId`), the method `SetParentId()` works as inteded. Once this method has been called (or the activity brings in a `ParentId` from a context, it will not change. 

## Reproduce

Just copy+paste this code into a new `dotnet new console` application's `Program.cs` file, run `dotnet restore` and `dotnet run`. 

```csharp
using System;
using System.Diagnostics;
using OpenTelemetry;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

namespace opentelemetrybug
{
    class Program
    {
        static void Main(string[] args)
        {
            using var tracerProvider = Sdk
                .CreateTracerProviderBuilder()
                .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("opentelemetry.test"))
                .AddSource("opentelemetry.test")
                .Build();
            
            var activitySource = new ActivitySource("opentelemetry.test");
            
            using var activity = activitySource.StartActivity("opentelemetry.test.parent_id_test");

            Console.WriteLine($"- New Activity's 'ParentID': {activity.ParentId}");

            // Simulate a W3C OTel traceparent header
            var traceparentHeader = "00-0cd0a691ff149486b760983a42aabdc2-265c29f871634bff-01";
            var parentId = traceparentHeader.Split("-")[2];
            activity.SetParentId(parentId);

            Console.WriteLine($"- Activity's 'ParentID' with ID from 'traceparent' header: {activity.ParentId}");

            var newParentId = "0123456789abcdef";
            activity.SetParentId(newParentId);

            Console.WriteLine($"- Activity's 'ParentID' with hardcoded ID: {activity.ParentId}");
        }
    }
}
```
Expected Output: 
```
- New Activity's 'ParentID': 
- Activity's 'ParentID' with ID from 'traceparent' header: 265c29f871634bff
- Activity's 'ParentID' with hardcoded ID: 0123456789abcdef
```
Real Output:
```
- New Activity's 'ParentID': 
- Activity's 'ParentID' with ID from 'traceparent' header: 265c29f871634bff
- Activity's 'ParentID' with hardcoded ID: 265c29f871634bff <-- Unchanged!
```

**Comment by cijothomas** [comment]
`activity.SetParentId(parentId);` existed in Activity API before OpenTelemetry.

OpenTelemetry has no such notion of updating the parentid, and hence this API is not expected to be used for OpenTelemetry scenarios.
