### ISSUE TITLE
Consistent input check

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#2495]
This is a follow up to #1043.

I guess we probably want to:
1. Use `Debug.Assert` for input validation on non-public APIs.
2. Use `Guard` for input validation on public APIs.

For example, the following method is `internal`, so we don't expect any invocation from the user, which is a perfect use case for `Debug.Assert`.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/6f3f7e5766612d5f6e71389d053ab3992051811b/src/OpenTelemetry/Batch.cs#L38-L40

**Comment by evanm-msft** [comment]
@reyang is there more work to be done with this issue? Thanks.

**Comment by reyang** [comment]
@mic-max I guess this is done?

**Comment by CodeBlanch** [comment]
I'm always finding these (eg #5789). I'm going to close the issue though. It is going to just be an ongoing effort forever I don't think we really need to keep the issue open indefinitely. Ideally an analyzer would catch these but I think the effort to build one would be much larger than the benefit.
