### ISSUE TITLE
OTLP: Span.Status is not populated from Activity.Status

### ISSUE THREAD

**Issue by zakimaksyutov** [open-telemetry/opentelemetry-dotnet#2503]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 1.0.2`):

```
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.2.0-alpha1" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.2.0-beta1" />
```

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can
find this information from the `*.csproj` file):

`net5.0`

## Symptom

Activity.SetStatus is not propagated into Span.Status.

```
using (var activity = MyActivitySource.StartActivity("MyActivity", ActivityKind.Producer))
{
  activity?.SetStatus(ActivityStatusCode.Error);
}
```

![image](https://user-images.githubusercontent.com/15914532/138206824-23de9f6e-35cf-4ca2-87ef-a48dde002338.png)

**What is the expected behavior?**

Span.Status contains information from Activity (success/failure + [optional] message)

**What is the actual behavior?**

Span.Status is always null

**Comment by cijothomas** [comment]
Closing as duplicate, as this is tracked in https://github.com/open-telemetry/opentelemetry-dotnet/issues/2569
