### ISSUE TITLE
Consider removing TestExporter

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#2534]
`InMemoryExporter` is designed for unit test purpose.

If OpenTelemetry .NET unit tests have some common need that cannot be achieved by `InMemoryExporter`, we would want to fix it in `InMemoryExporter` rather than inventing another exporter for tests.

The ask is to evaluate whether it is possible to get rid of https://github.com/open-telemetry/opentelemetry-dotnet/blob/0c93744d4ba51676b61ab1be38f7764190cfcec0/test/OpenTelemetry.Tests/Shared/TestExporter.cs and use `InMemoryExporter`.

**Comment by mic-max** [comment]
The above PR doesn't completely remove the `TestExporter` class, there were 5 uses that I didn't have a good way to replace
