### ISSUE TITLE
OTLP exporter flattens array attribute to multiple key value pairs with the same key name

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-dotnet#2547]
# Bug Report

The current OTLP exporter below flattens nested array in Span.Atttributes (Activity.Tags in .NET) into a list of key value pairs with the same key for all these kv pairs. For example, `activity.SetTag('arraykey', new int [] {1, 2, 3}` is converted to JSON like list `{{'arraykey': 1}, {'arraykey': 2}, {'arraykey': 3}}` in OTLP. This could cause problem if the OTLP listener would like to process Span.Attributes as dictionary, or store them into table like data structure, because it requires inventing some new rules to handle the duplicated key names.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/ce46d001d5ed08d91e7750b4859410330d57e7a7/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs#L413-L417

Instead of flatting the array into the top level of Span.Attributes, I tried below change which keeps the type of array in the Span.Attributes field, when then will be serialized to [ArrayValue](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L43) in OTLP and no longer producing duplicated keys. Please let me know if this will work and I'll make PR to fix all the nested arrays in Span.Attributes.

```csharp
                    case int[] intArray:
                        var anyValue = new OtlpCommon.AnyValue { ArrayValue = new OtlpCommon.ArrayValue { } };
                        anyValue.ArrayValue.Values.Add(intArray.Select(item => new OtlpCommon.AnyValue { IntValue = item }));
                        PooledList<OtlpCommon.KeyValue>.Add(ref this.Tags, CreateOtlpKeyValue(key, anyValue));

                        break;
```

**Comment by alanwest** [comment]
Fixed in #3262
