### ISSUE TITLE
Self-diagnostics log file has strange content

### ISSUE THREAD

**Issue by mkotsabiuk** [open-telemetry/opentelemetry-dotnet#2548]
# Bug Report

I am using OpenTelemetry 1.1.0 (commit `ce46d001d5ed08d91e7750b4859410330d57e7a7`). Running [AspNetCore example] (https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/AspNetCore) with target framework `netcoreapp3.1`, release configurations and `OTEL_DIAGNOSTICS.json` config file:

```
{
    "LogDirectory": ".",
    "FileSize": 1024,
    "LogLevel": "LogAlways"
}
```

After some requests to https://localhost:5001/WeatherForecast/ the log file `Examples.AspNetCore.exe.41136.log` was created.

[Examples.AspNetCore.exe.41136.log](https://github.com/open-telemetry/opentelemetry-dotnet/files/7441237/Examples.AspNetCore.exe.41136.log)

When I open .log file in Notepad++ I see there internal events generated by OpenTelemetry (logs) with some unsupported symbols:

![image](https://user-images.githubusercontent.com/24542102/139420886-86de9b9f-320d-40ab-ad47-d4b6ec01effc.png)

But I am expecting to see there **only** logs.

**Comment by mkotsabiuk** [comment]
Thanks, @cijothomas, for assigning @xiang17 to check it.

**Comment by xiang17** [comment]
It is expected behavior. It was never intended to be a proper text format. The log is written in a fixed-size file in a circular way. Once reached to the end, it will even overwrite itself from beginning.

The reason is described in #1258: The self-diagnostics module is designed to have minimal overhead and bounded resource usage to make it production-ready and developers worry-free from ever-growing log file(s).

**Comment by mkotsabiuk** [comment]
Thank you, @xiang17, for explaining. I think it worth it to add this behavior into [Remarks](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#remarks) section because it was unexpected for me and I thought that I am doing something in the wrong way.

Does fixing it and making the log file to be in a proper text format will require a big overhead to SDK itself?

**Comment by mkotsabiuk** [comment]
Hi @xiang17,

Any updates on this issue?

cc: @cijothomas @reyang

**Comment by Oberon00** [comment]
I would also like to have that documented.

> The reason is described in #1258: The self-diagnostics module is designed to have minimal overhead and bounded resource usage to make it production-ready and developers worry-free from ever-growing log file(s).

This will lead to even stranger content when the file starts again from the beginning, especially if this happens mid-stacktrace and you get something that looks like a normally formatted stack trace with impossible content.

I don't think "minimal-overhead" in that extreme sense is a desirable feature. I'd rather want a developer-friendly debug feature by default.

**Comment by Oberon00** [comment]
@xiang17

> The file was never intended to be in a proper text format. 

What is the expected way to use this file then?
