### ISSUE TITLE
Attributes on Logs

### ISSUE THREAD

**Issue by ndrwrbgs** [open-telemetry/opentelemetry-dotnet#2551]
# Question
The [OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-attributes) defines `Attributes` on Log Messages, but I'm not able to reproduce support for that using the .NET APIs.

**Describe your environment.**
OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs 1.0.0-rc8
Opentelemetry.Exporter.OpenTelemetryProtocol 1.1.0
Microsoft.Extensions.Logging 5.0.0

**What are you trying to achieve?**
Producing `labels` in Loki with ingestion via `OpenTelemetry Collector` `exporter` for Loki which can map `Attributes` to `labels`. (Another issue was created against the `exporter` for it not supporting the particular fields I want as first-class, but the lack of support for auxiliary fields would remain in .NET due to the consumption expecting the production to match the standard).

What did you expect to see?
A way to emit the documented `Attributes` using OpenTelemetry in .NET ecosystem.

## Additional Context

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.

link: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/getting-started/Program.cs

**Comment by ndrwrbgs** [comment]
I think, perhaps, [LogRecord.StateValues](https://github.com/open-telemetry/opentelemetry-dotnet/blob/54d46d80a03acfa0813021e5875a00a7ef423274/src/OpenTelemetry/Logs/LogRecord.cs#L98) in the DotNet object model should be translated to [Attributes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/405bbda121e1e64e06daf3ba673bcebc425c57fc/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/opentelemetry/proto/logs/v1/logs.proto#L119) on the Spec?

I think [this method ToOtlpLog](https://github.com/open-telemetry/opentelemetry-dotnet/blob/1074311765435d42bdbf3285ec4a885daa039723/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/LogRecordExtensions.cs#L64)?

**Comment by cijothomas** [comment]
> I think, perhaps, [LogRecord.StateValues](https://github.com/open-telemetry/opentelemetry-dotnet/blob/54d46d80a03acfa0813021e5875a00a7ef423274/src/OpenTelemetry/Logs/LogRecord.cs#L98) in the DotNet object model should be translated to [Attributes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/405bbda121e1e64e06daf3ba673bcebc425c57fc/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/opentelemetry/proto/logs/v1/logs.proto#L119) on the Spec?
> 
> I think [this method ToOtlpLog](https://github.com/open-telemetry/opentelemetry-dotnet/blob/1074311765435d42bdbf3285ec4a885daa039723/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/LogRecordExtensions.cs#L64)?

Yes. The OTLP Log exporter does not do there yet.

Tracking issue for OTLP Log Exporter fixes : https://github.com/open-telemetry/opentelemetry-dotnet/issues/2482

**Comment by ndrwrbgs** [comment]
Are you taking this or do you want me to try to make the change?

**Comment by cijothomas** [comment]
> Are you taking this or do you want me to try to make the change?

You can take it.
