### ISSUE TITLE
ExporterOptions should not control the pipeline

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2552]
Currently, the ExporterOptions( eg: OTLPExporterOptions etc), contains setting which are about the pipeline, but not about the exporter itself. (like whether to use BatchingProcessor or not, should use Metrics in delta vs cumulative mode etc). These are not really an Exporter setting, but they are now passed to Exporter ctor(). This is described in detail here, along with a possible mitigation. (since we are already stable for traces, we cannot break the API, so have to mitigate this only)
See : https://github.com/open-telemetry/opentelemetry-dotnet/pull/2541#discussion_r738746063

**Comment by alanwest** [comment]
Another idea… maybe there’s value in peeling apart the exporter options from the metric reader options - so the extension method might look like

```csharp
public static MeterProviderBuilder AddOtlpExporter(this MeterProviderBuilder builder, Action<OtlpExporterOptions> configure, Action<OtlpMetricReaderOptions> configureMetricReader)
```

`OtlpMetricReaderOptions` would hold `Temporality`, `MetricReaderType`, and `PeriodicExportingMetricReaderOptions`.

We could do the same thing with traces

```csharp
public static TraceProviderBuilder AddOtlpExporter(this TraceProviderBuilder builder, Action<OtlpExporterOptions> configure, Action<OtlpSpanProcessorOptions> configureSpanProcessor)
```

**Comment by CodeBlanch** [comment]
[Talked about this on the SIG today, figured I would drop a comment here as well.]

RE: This design...

```csharp
public static TraceProviderBuilder AddOtlpExporter(
    this TraceProviderBuilder builder,
    Action<OtlpExporterOptions> configure = null,
    Action<OtlpSpanProcessorOptions> configureSpanProcessor = null) { ... }
```

That works well but I think it has a couple of issues:

* It is a bit intimidating for new users. Thinking most do not understand (or care) about processor/reader options, defaults are fine.
* If you have other options classes (think serialization, transport, etc.) it might lead to a lot of delegates/overloads which is very confusing and hard to document.

For [OneCollectorExporter](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/f9528610ac99eb67f730cbe3ba810026b446b840/src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorOpenTelemetryLoggerOptionsExtensions.cs#L37-L44) I introduced a builder class `OneCollectorLogExportProcessorBuilder` for the extension to use.

It allows you to do things like this...

```csharp
builder.AddOneCollectorExporter(configure => configure
   .SetConnectionString("InstrumentationKey=hello world")
   .ConfigureBatchOptions(o => o.ScheduledDelayMilliseconds = 1000)
   .ConfigureTransportOptions(o => o.Endpoint = new("http://localhost")));
```

Also plays nice with `IConfiguration` and Options API (all the bells and whistles) 🤣

**Comment by TimothyMothra** [comment]
Spoke with Blanch and decided to close this.
This is related to #4527.
My understanding is that a fix is in place for Logs and Metrics. Traces is outstanding.
