### ISSUE TITLE
Metric instrumentation for Asp.Net

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2556]
Similar to: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs

**Comment by alirizaadiyahsi** [comment]
We are exporting metrics to New Relic and we can handle request counts, durations, failed request counts, successful request counts. But we can group them by url. For example we want to group by `user/login` and `user/register`. My question is: Is there any estimation about this issue? 

At least may be you can add http attributes like request url or path?

Thanks.
