### ISSUE TITLE
Histogram aggregation should support Min Max

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2560]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation
It should be collected by default, with the ability to turn off.

**Comment by mic-max** [comment]
I'm interested in helping with this item with some guidance 🙂

**Comment by cijothomas** [comment]
Sure. I wanted to wait till https://github.com/open-telemetry/opentelemetry-proto/pull/279 is merged. But we don't have to wait really for that.

**Comment by cijothomas** [comment]
Removing this from 1.3.0 milestone and moving to 1.4.0.
1.3.0 is releasing shortly, and want to allow bake time for the new feature.

**Comment by WenheLI** [comment]
Hi, the previous PR seems to be closed due to inactivity.
I am just wondering if I could take that over?

**Comment by cijothomas** [comment]
> Hi, the previous PR seems to be closed due to inactivity. I am just wondering if I could take that over?

If @mic-max is not planning to work on it, then yes. @mic-max could you respond here?

**Comment by mic-max** [comment]
> > Hi, the previous PR seems to be closed due to inactivity. I am just wondering if I could take that over?
> 
> If @mic-max is not planning to work on it, then yes. @mic-max could you respond here?

Yes, I plan to work on it this week, sorry I missed this notification. It should be a fairly simple *fingers crossed* rebase and touch up to the existing PR :)

**Comment by cijothomas** [comment]
> Are there any docs on how to make this work with the PrometheusExporter? I can't figure out if there is anything special to do here or the exporter. The `Metric.CreateHistogram<T>` has no settings for buckets or inclusion of min/max.

MinMax is not supported for PrometheusExporter. The spec does not mention how to convert Min/Max for Prometheus.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#histograms-1

**Comment by YarekTyshchenko** [comment]
Thanks for clarification @cijothomas. Do you have any advice on how to proceed? I'm used to using Histogram data type for gauge type metrics like "latency" or "delay" where max data is important. The data itself is a gauge, but missing all the data in between the sampling points is undesirable.

It looks like with OpenTelemetry there's no datatype that would give me this data

**Comment by cijothomas** [comment]
I don't fully understand the issue you are facing. If the issue is Prometheus Exporter missing min/max, then this is just a matter of OTel spec clarifying how to map Min/Max to Prometheus model (likely a Prometheus Gauge). Please open an issue in the spec repo for this.

If it is something else, could you elaborate/clarify the exact ask?
