### ISSUE TITLE
Histogram bounds must be validated

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2566]
Similar to instrument/view name, we need to validate the custom bounds (no duplicates, increasing order etc.), if provided.
If we can fail-fast, do that. - done in #2573 
Else log and move on.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/3117 and https://github.com/open-telemetry/opentelemetry-dotnet/pull/3120 addressed the "log and move-on" part.

**Comment by cijothomas** [comment]
Closing as this is handled. If there are follow up, @mic-max please share here.

**Comment by mic-max** [comment]
> Closing as this is handled. If there are follow up, @mic-max please share here.

https://github.com/open-telemetry/opentelemetry-dotnet/pull/3117/files#r849928032 Just this one case where `double.NaN` could be used as a boundary. I'll make a PR adding some tests extracted from #2592 to this as well since they should still be beneficial
