### ISSUE TITLE
.NET monitor integration?

### ISSUE THREAD

**Issue by dominikjeske** [open-telemetry/opentelemetry-dotnet#2567]
I'm wondering about integration with dotnet monitor. Is there a way to show metrics from opentelemetry in this tool or this is completely separate topic?

**Comment by cijothomas** [comment]
Not sure of dotnet monitor, but dotnet counters tool supports the new metric API.
It does not show "metrics from opentelemetry", instead it shows metrics when metrics are emitted with Metrics API, without any OpenTelemetry involvement.

There is an open PR in .NET repo adding docs:
https://github.com/dotnet/docs/pull/25312

**Comment by noahfalk** [comment]
For dotnet-monitor support/discussion there is also a GitHub repo: https://github.com/dotnet/dotnet-monitor
