### ISSUE TITLE
Support Status and StatusDescription from Activity class

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#2569]
Starting version 6.0.0 in System.Diagnostic.DiagnosticSource, there are two new properties added to [Activity](https://docs.microsoft.com/dotnet/api/system.diagnostics.activity?view=net-6.0) class - [Status](https://docs.microsoft.com/dotnet/api/system.diagnostics.activity.status?view=net-6.0) and [StatusDescription](https://docs.microsoft.com/dotnet/api/system.diagnostics.activity.statusdescription?view=net-6.0).

With this change in Activity class there are 3 possible ways status can be set on Activity:

1. _activity.SetTag("otel.status_code", "StatusCode"), _activity.SetTag("otel.status_description", "Error description")
2. _activity.SetStatus(StatusCode) using [ActivityExtensions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs)
3. _activity.SetStatus(ActivityStatusCode, desc) using [Activity](https://docs.microsoft.com/dotnet/api/system.diagnostics.activity.setstatus?view=net-6.0) api.

**Goal**
Support new changes in exporters while maintaining backward compatibility.

**Proposal**
1. Going forward, have [SetStatus(ActivityStatusCode, String)](https://docs.microsoft.com/dotnet/api/system.diagnostics.activity.setstatus?view=net-6.0) as the recommended way for setting status on activity.
2. Set `Status` and `StatusDescription` on activity using tags `otel.status_code` and `otel.status_description` respectively in SDK. This can be done in `OnEnd()` call of `BaseExportProcessor`. The feature will be turned on by default and can be disabled using a switch. Users already migrated to new Api will be recommended to turn off this feature.
3. Update exporters shipped from this repo to look up `Status` and `StatusDescription` to export activity status details. As the feature noted in 2) is on by default, anyone using _activity.SetStatus(StatusCode) via [ActivityExtensions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs) or setting status tags directly will not be impacted.
4. Update SetStatus(StatusCode) in [ActivityExtensions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs) to also set `Status` and `StatusDescription`.
5. Update the instrumentation libraries to use [SetStatus(ActivityStatusCode, String)](https://docs.microsoft.com/dotnet/api/system.diagnostics.activity.setstatus?view=net-6.0) as the libraries are still in rc phase.
6. Update docs to reflect these new changes.

**Comment by tnovacik** [comment]
This issue is closed but in the version of OpenTelemetry 1.0.0-beta2 call of the method SetStatus, doesn't propagate tag otel.status_code to ERROR. I am using it in the .net 6.0 project.

**Comment by cijothomas** [comment]
This issue is not fixed, and this issue is, hence, not closed.

**Comment by Yun-Ting** [comment]
Meeting notes from 2/8/2022 SIG meeting:
ActivityStatus migration
@cijothomas - prefers to let every Exporters deal with it than handling it in SDK
Modify all core exporters from this repo to handle this
Modify “Write own exporter” doc to talk about things changing between each .NET versions.

The pros of supporting setting status with native Status in all the Exporters are:
1. Prevent perf penalty in enumerating all the activity tags in the core SDK.
2. Less maintenance/migration effort when the time comes on stop supporting setting status via activity tags.
