### ISSUE TITLE
Add a Logger Exporter that exports data using ILogger

### ISSUE THREAD

**Issue by almostchristian** [open-telemetry/opentelemetry-dotnet#2570]
We have applications that want to have distributed tracing, but don't have a service like Jaeger. I figured that if there was an exporter similar to the Console exporter that wrote to an ILogger and uses structured logging, we can use Serilog to write the data to a DB sink. I wrote one such exporter myself, but I think it would make sense to have this as default exporter similar to the ConsoleExporter. The default aspnetcore template includes a logger implementation that writes to the console so this can replace the ConsoleExporter in AspNetCore examples.

**Comment by cijothomas** [comment]
Its not clear what is the ask/enhancement here. Could you clarify the specific ask?

> The default aspnetcore template includes a logger implementation that writes to the console so this can replace the ConsoleExporter in AspNetCore examples.

The default provider in Asp.Net Core template is the `Microsoft.Extensions.Logging.Console`, and it has no connection to OpenTelemetry. That console exporter is just like any other LoggerProvider. OpenTelemetry is another provider. As *this* is OpenTelemetry repo, the examples in this repo should only show OpenTelemetry provide example, and nothing else.
Let me know if this makes sense, I admit I haven't fully understood the original ask.

**Comment by almostchristian** [comment]
I do see from the examples that it is using a logging provider in the Program.cs. However, if Serilog is used, it [ignores all other logging providers](https://stackoverflow.com/a/56227367) and assumes all logging providers are added via Serilog This prevents any logs written by the OpenTelemetry logging provider from being written into the sinks configured in Serilog.

If there was an exporter that logs to an ILogger, this will enable the exporter to write to any Serilog configured sink, which can be to console, a file, ElasticSearch, SqlServer, or any other configured sink. If Serilog was not added, this will just log to the console.

Below is an exporter I played around with, which is based on the ConsoleExporter. I tested this with Serilog with a console and file sink, but I intend to use this with a Db sink so that the trace info are written to a database.

```csharp
public class LoggerActivityExporter : BaseExporter<Activity>
{
    private readonly ILogger logger;
    private readonly LoggerExporterOptions options;
    private const string DefaultMessageFormat = @"Trace Activity Details:
Id:           {Id}
ParentId:     {ParentId}
SpanId:       {SpanId}
TraceId:      {TraceId}
OperationName:{OperationName}
SourceName:   {SourceName}
DisplayName:  {DisplayName}
Kind:         {Kind}
StartTime:    {StartTime}
Duration:     {Duration}
TagObjects:   {@TagObjects}
Events:       {@Events}";

    public LoggerActivityExporter(ILoggerFactory loggerFactory, IOptions<LoggerExporterOptions> options)
    {
        this.options = options.Value;
        logger = loggerFactory.CreateLogger(this.options.LogCategory);
    }

    public override ExportResult Export(in Batch<Activity> batch)
    {
        foreach (var activity in batch)
        {
            var messageFormat = DefaultMessageFormat;
            var arguments = new List<object?>
            {
                activity.Id,
                activity.ParentId,
                activity.SpanId,
                activity.TraceId,
                activity.OperationName,
                activity.Source.Name,
                activity.DisplayName,
                activity.Kind,
                activity.StartTimeUtc,
                activity.Duration,
                activity.TagObjects.ToDictionary(x => x.Key, x => x.Value),
                activity.Events.Select(x => new { x.Name, x.Timestamp, x.Tags }),
            };

            var resource = ParentProvider.GetResource();
            if (resource != Resource.Empty)
            {
                messageFormat += @"
Resource:    {@Resource}";
                arguments.Add(resource.Attributes.ToDictionary(x => x.Key, x => x.Value));
            }

            Log(messageFormat, arguments.ToArray());
        }

        return ExportResult.Success;
    }

    protected void Log(string message, params object?[] args)
    {
        logger.Log(options.Level, message, args);
    }
}
```

Using LoggerActivityExporter With Serilog and Console sink:
![image](https://user-images.githubusercontent.com/2035340/140785630-a9126f16-938e-44ff-b65e-9393ca4a5a6d.png)

Using LoggerActitivityExporter Without Serilog and default logger:
![image](https://user-images.githubusercontent.com/2035340/140785966-3a1f2273-a6de-43f8-8cf3-04479844e1c9.png)

**Comment by cijothomas** [comment]
I see that you are trying to export `Activity` via ILogger, something like an "tracing -> logging" conversion. This is not a core scenario, and likely it won't be part of this repo. The best recommendation would be to contribute this to the https://github.com/open-telemetry/opentelemetry-dotnet-contrib repo, and you may include examples there.

**Comment by cijothomas** [comment]
One example: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Preview this has one similar feature - converting Logs to ActivityEvents.

**Comment by reyang** [comment]
Closing this issue now as it has moved to the contrib repo.
