### ISSUE TITLE
Any plans to use GitHub Discussions?

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry-dotnet#2576]
# Question

**Describe your environment.**

N/A

**What are you trying to achieve?**

Provide a more structured way for asking questions & help without polluting the project's backlog.
https://docs.github.com/en/discussions

**Comment by reyang** [comment]
+1, it seems Discussions is a better place for questions/announcements.

**Comment by tomkerkhove** [comment]
Yes, you'll need a `config.yml` similar to how we do it on KEDA - https://github.com/kedacore/keda/blob/main/.github/ISSUE_TEMPLATE/config.yml#L3-L5

**Comment by tomkerkhove** [comment]
Any thoughts on this @cijothomas ?

**Comment by cijothomas** [comment]
Yes. 
Will discuss this in next SIG meeting and enable.

**Comment by cijothomas** [comment]
Will be enabling this over the next few days.

**Comment by tomkerkhove** [comment]
Great, thanks @cijothomas!

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2942
