### ISSUE TITLE
Provide guidance on using gauges

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry-dotnet#2588]
# Question

**Describe your environment.**

N/A

**What are you trying to achieve?**

I'm trying to use gauges but it's not super clear from the docs how to use them.

Are there plans to provide docs?

## Additional Context

N/A

**Comment by cijothomas** [comment]
All instruments are described in spec : https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-gauge

We are unlikely to copy all the spec wordings into our doc. There are sample apps here : https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/metrics/learning-more-instruments/Program.cs 
Please let us know how to improve the examples.

**Comment by reyang** [comment]
You can find some high level guidance from https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/supplementary-guidelines.md.

The API document is supposed to be covered by .NET official API doc.

**Comment by tomkerkhove** [comment]
Seems like I have looked over the sample with the gauge, my bad.

From the looks of it, observable gauges are the only way and no further plans to add other ones - Is that correct?

If so, thanks and happy to close this issue.

**Comment by reyang** [comment]
> From the looks of it, observable gauges are the only way and no further plans to add other ones - Is that correct?

Yes, at least for the initial metrics release. If you find a common need of introducing a new instrument API, please file issue in the specification repo - we might consider it after the initial release. https://github.com/open-telemetry/opentelemetry-specification/milestone/17
