### ISSUE TITLE
Meter filters with .* are not working when using AddOpenTelemetryMetrics

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry-dotnet#2615]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 1.0.2`):

* `OpenTelemetry.Extensions.Hosting`: 1.0.0-rc8
* `OpenTelemetry.Instrumentation.AspNetCore`: 1.0.0-rc8
* `OpenTelemetry.Exporter.OpenTelemetryProtocol`: 1.2.0-beta1

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can
find this information from the `*.csproj` file):

* `netcoreapp3.1`

## Symptom

When using meter name wildcards, the information is not emitted.

**What is the expected behavior?**

Meter information should be available

**What is the actual behavior?**

Meter information is *not* available

## Reproduce

```
services.AddOpenTelemetryMetrics(metricsBuilder =>
{
    metricsBuilder.AddAspNetCoreInstrumentation()
        // Uncomment this, and it won't work
        //.AddMeter("App.OpenTelemetry.*")
        // This approach, however, does work
        .AddMeter("App.Http")
        .AddMeter("App.Weather")
        .AddOtlpExporter();
});
```

## Additional Context

I saw there are tests for this in `MeterSourcesWildcardSupportMatchTest` but it does not use the ASP.NET Core extension so will see if it's related to that.

Or it is related to the OTLP exporter.

**Comment by cijothomas** [comment]
Wilcard support is part of unleased. It just missed the beta1, so it'll be part of the next release.

**Comment by cijothomas** [comment]
If you use daily myget build, then you should get it. Or wait for beta2 release (coming tonight/tomorrow)

**Comment by tomkerkhove** [comment]
Great, thank you!
