### ISSUE TITLE
View - Additional tags from Baggage

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2619]
Child of overall [Views feature](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2359)
This is to track supporting providing additional tags from Baggage using Views.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/2215 This is removed from spec itself, for initial stable release, to be added later.

**Comment by rbell517** [comment]
Hi @cijothomas I've been looking for a way to do exactly this. In our case it is to stash a customer ID in the baggage then retrieve it and add it to metrics we gather automatically to help inform things like throttling or billing. We'd like to take advantage of metrics generated by instrumentation libraries but we have no way to add in this extra data. Does this align with the intended use case for this feature? Can you comment on whether this feature is confirmed for the 1.4.0 milestone or if this is just tentative?

**Comment by cijothomas** [comment]
It won't be part of 1.4.0. The spec still does not have it unfortunately.

**Comment by cijothomas** [comment]
Closing as there is no spec for this yet. Once a spec change is there, we can open a new issue.
