### ISSUE TITLE
Allow configurable maximum metrics limit in MeterProviderSdk

### ISSUE THREAD

**Issue by wazzamatazz** [open-telemetry/opentelemetry-dotnet#2626]
# Feature Request

The maximum number of metrics that `MeterProviderSdk` can observe is currently limited to 1000 using a constant limit value. While this is a sensible default limit, it would be great if this limit could be set via the `MeterProviderSdk` constructor if required, to allow a little bit more flexibility in situations where you know that you will be working with larger numbers of instruments.

An example of where this would be useful would be when integrating with industrial process systems. It might be necessary to interface with hundreds of individual systems via various different protocols (Modbus, MQTT, OPC UA, MTConnect, various vendor-specific protocols, and so on), with each individual connection having associated telemetry information that is desirable to observe.

**Comment by cijothomas** [comment]
Thanks for raising this. We are aware of this, and want to allow users to set this limit.
This is tracked here : https://github.com/open-telemetry/opentelemetry-dotnet/issues/2358
closing as duplicate.
