### ISSUE TITLE
Instrument name collisions for different Meters

### ISSUE THREAD

**Issue by pirgeo** [open-telemetry/opentelemetry-dotnet#2627]
Opening this as a tracking issue for the bug where `Instrument`s that have the same name are dropped, even if they come from separate `Meter`s. From the [API spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument): 

> Different Meters MUST be treated as separate namespaces. The names of the Instruments under one Meter SHOULD NOT interfere with Instruments under another Meter.

This issue does **only** cover the fact that duplicate instrument elimination in the .NET SDK implementation does not take into account the `Meter` name, but only the `Instrument` name. It does **not** cover downstream implications (such as how to deal with Prometheus export in such a case, which has extensively been discussed and resolved (?) [elsewhere](https://github.com/open-telemetry/opentelemetry-specification/pull/2035#issuecomment-965540896)).

While this should occur only rarely, I think its important that this is addressed. As more and more libraries adopt OpenTelemetry, such situations are likely to appear more often. OTLP is able to transport these data streams, so it seems counter-intuitive to drop them.

## Additional Context:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument

https://github.com/open-telemetry/opentelemetry-specification/issues/2064
[Code where instruments are dropped when using Views](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Metrics/MeterProviderSdk.cs#L169-L175)
[Code where instruments are dropped without Views](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Metrics/MeterProviderSdk.cs#L252)

**Comment by pirgeo** [comment]
Potentially relevant for #2621

**Comment by cijothomas** [comment]
Thanks! The fix would be small one, so adding to 1.2 milestone for now.
@joaopgrassi who initially raised the concern.
