### ISSUE TITLE
Multiple Tracers and Orphan Spans

### ISSUE THREAD

**Issue by alexeypukhov** [open-telemetry/opentelemetry-dotnet#2662]
Hi all. Couldn't find any existing ticket about this but please let me know if my question has already been answered.

I'm trying to understand what happens if multiple tracers are configured in one application? Especially if their configurations are different. Docs doesn't say there should be just one tracer but neither it specifies what should happen if multiple tracers are configured.
To my mind this situation may lead to nasty issues like breaking span chains and producing orphan spans but please let me know if I'm missing something

My example. I have two tracers with different samplings, different sources for tracking and different exporters. Basically two independent tracers
```
var tracer1 = Sdk.CreateTracerProviderBuilder()
                    // configure sampling,
                    ...
                    // add certain sources
                    .AddSource("SourceA")
                    .AddSource("SourceC")
                    // set certain exporters
                    ...
                    .Build();

var tracer2 = Sdk.CreateTracerProviderBuilder()
                    // configure sampling,
                    ...
                    // add certain sources
                    .AddSource("SourceB")
                    // set certain exporters
                    ...
                    .Build();
```

Then in my application I'm creating a chain of spans: `spanA` -> `spanB` -> `spanC` for sources `SourceA`, `SourceB`, `SourceC` respectively

```
void DoWorkA()
{
    using var _ = new ActivitySource("SourceA").StartActivity("DoWorkA");
    DoWorkB();
    ...
}

void DoWorkB()
{
    using var _ = new ActivitySource("SourceB").StartActivity("DoWorkB");
    DoWorkC();
    ...
}

void DoWorkC()
{
    using var _ = new ActivitySource("SourceC").StartActivity("DoWorkC");
    ...
}
```

As a result `spanA` and `spanC` will go to one place and `spanB` - to another. `spanC` will have `spanB` as a parent span but since `spanB` didn't go to the same location, the `spanC` will become orphan and doesn't show any connection to the `spanA`. :(

This example may look artificial but I had few real use cases in mind
1) what if I want to reference a third party library which may already configure an OpenTelemetry SDK tracer but I don't want their spans to affect my spans? I don't know if and how their library is configured so I don't even understand how I should go about it?
2) it may be challenging for the on-the-fly APM solutions (meaning, an APM instrumentation that does not require any updates to the target application code) in case both my application and their APM solution configure separate tracers. One or another tracer may very easily produce orphan spans, the situation that doesn't happen if only one tracer is configured.

So I'm just thinking loud, could SDK prevent from creating multiple tracers? That would avoid situations like that. Maybe one global tracer (singleton) be a better option?
Or if multiple tracers are ok is it reasonable to expect that each tracer should track the integrity of the spans chain that it is tracking? In other words if there is a span in between that this tracer is not configured to track than the next span should reference the last "visible" span instead of referencing an unexpected span and therefore hanging it in the air?

Please let me know what are your thoughts, is there any plans for that or am I completely missing the point?

Thanks

**Comment by puhovalexey** [comment]
It's been a while I haven't heard anything about this issue. Any updates on this? Thanks
