### ISSUE TITLE
Any way to control buckets for histogram?

### ISSUE THREAD

**Issue by MichaelLogutov** [open-telemetry/opentelemetry-dotnet#2678]
Hello.
I'm using `OpenTelemetry.Exporter.Prometheus` `1.2.0-beta2.1` with NET 6 `System.Diagnostics`.

I use `Histogram<int>` to record timings of operations (in milliseconds) and when I record just a single point of 1000+ msec operation I see in `/metrics` endpoint that it goes to `+Inf` bucket.

Is there a way to specify buckets for `Histogram` ?

**Comment by reyang** [comment]
Read https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk.

**Comment by MichaelLogutov** [comment]
Thank you for such quick response.
I swear I look up everything including codebase, searched the tickets but found nothing.

**Comment by reyang** [comment]
No worries, the metrics work is still in-progress, many things are still changing at this moment.
