### ISSUE TITLE
Change TraceFactory Internal Locking Method

### ISSUE THREAD

**Issue by vkozyrev0** [open-telemetry/opentelemetry-dotnet#269]
TraceFactory currently used old-style locking mechanism

`private read-only object lck = new object();`

This can lead to deadlocks when the async/await pattern is used. The recommended change is to use this 

`private readonly SemphoreSlim lck = new SemphoreSlim(1,1);`
`...`
`try{`
`   await lck.WaitAsync(cancellationToken).ConfigureAwait(false);`
`   //or`
`   lck.Wait();`
`}`
`finally {`
`   lck.Release();`
`}`

This might have to be useful to update other places in the code to make them async/await compatible.

**Comment by pcwiese** [comment]
I'm failing to see the issue here. There is no awaiting anything in this class. Isn't the problem when you attempt to await _inside_ a lock statement?

**Comment by lmolkova** [comment]
TraceFactory from my expectations is not going to have a lot of concurrent requests. During setup it is accessed to create all tracers (may be handful of times?) and accessed rarely as everyone supposedly will cache tracer.

So, there is not much concurrency there and also as @pcwiese mentioned - there is no async code inside the lock. I'm closing the issue for now, feel free to reopen if we missed something.
