### ISSUE TITLE
Must be possible to provide multiple SpanProcessors

### ISSUE THREAD

**Issue by z1c0** [open-telemetry/opentelemetry-dotnet#270]
Currently, only a single instance of `SpanProcessor` can be provided at `TracerFactory` (hence, also `Tracer`) creation.

According to the specification (https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#span-processor), it must be possible to provide multiple `SpanProcessors` which are are invoked in the same order as they were registered.

Specification issue https://github.com/open-telemetry/opentelemetry-specification/issues/304 needs to be clarified, before this can be implemented.

**Comment by lmolkova** [comment]
Is it dup of #226?

**Comment by z1c0** [comment]
I missed that one. Thanks
