### ISSUE TITLE
OpenTelemetry Console Exporter .NET Framework Compatibility

### ISSUE THREAD

**Issue by jixox** [open-telemetry/opentelemetry-dotnet#2701]
# Question

Hello!

Just a quick question. I am currently developing a project using .NET Framework v 4.6.2 and looking to use OpenTelemetry's console exporter. Is there any documentation that someone could point me to that describes using this exporter with .NET Framework? The github documentation I could find solely uses .NET Core.

Thanks!

**Comment by alanwest** [comment]
The console exporter is compatible with .NET Framework 4.6.1+. There's an example ASP.NET application that can be configured and run using the console exporter https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/AspNet/Global.asax.cs#L62-L64.
