### ISSUE TITLE
"error: Value cannot be null. (Parameter 'path1')" when installing OpenTelemetry via NuGet

### ISSUE THREAD

**Issue by yooakim** [open-telemetry/opentelemetry-dotnet#2709]
# Bug Report

Here's my empty csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

It is a new `console` project created as follows:

```
dotnet new console -o opentelemetry
```

Trying to add the OpenTelemtry NuGet package then generates the error:
```
 dotnet add package OpenTelemetry --version 1.1.0
  Determining projects to restore...
  Writing C:\Users\<username>\AppData\Local\Temp\tmp18AD.tmp
info : Adding PackageReference for package 'OpenTelemetry' into project 'C:\Users\<username>\source\sandbox\opentelemetry\opentelemetry.csproj'.
info : Restoring packages for C:\Users\yooak\source\sandbox\opentelemetry\opentelemetry.csproj...
error: NU1108: Cycle detected.
error:   opentelemetry -> OpenTelemetry (>= 1.1.0).
info : Package 'OpenTelemetry' is compatible with all the specified frameworks in project 'C:\Users\<username>\source\sandbox\opentelemetry\opentelemetry.csproj'.
error: Value cannot be null. (Parameter 'path1')
```

## Symptom

**What is the expected behavior?**
I expect the NuGet package to be added to my csproj file. 

**What is the actual behavior?**

`error: Value cannot be null. (Parameter 'path1')`

## Reproduce

```
dotnet new console -o opentelemetry
cd opentelemetry
dotnet add package OpenTelemetry --version 1.1.0
```

## Additional Context

I am not sure if this is OpenTelemetry or NuGet. I suspect the issue is related to the name I picked for the project. I named it _opentelemetry_ 

I then did a new test naming the project simply _ote_ and then tit works adding the package. 

So not sure if this is rleated to the OpenTelemetry package or if this is a bug/feature of NuGet?

**Comment by eddynaka** [comment]
Hi @yooakim ,

Pls, rename your console project to opentelemetry2.
NuGet cannot differentiate your project name from the package name, generating the cycle exception.

I just changed your script to the following:
```
dotnet new console -o opentelemetry2
cd opentelemetry2
dotnet add package OpenTelemetry --version 1.1.0
```

And it worked normally.
