### ISSUE TITLE
Out of the box Baggage propagation

### ISSUE THREAD

**Issue by lhidalgo89** [open-telemetry/opentelemetry-dotnet#2724]
# Question
Documentation is a bit unclear on how baggage propagation works out of the box (if at all). If I were to add baggage using the Baggage API, I would expect the receiving application to extract said baggage. 

Tried adding baggage both via Baggage API and through Activity (I am aware that documentation specifies to use Baggage API instead). When I add baggage via Activity I can at least see baggage in the header. With Baggage API, I can confirm they are added successfully before the outbound call, but it is not propagated to the receiving application. Confirmed this while debugging the receiving app and checking the contents of Baggage.Current (Same app different environment, same instrumentation).

Reading #1816 it seems to imply we can access Baggage.Current within the OnStart method of a custom processor. Is this implying we need to write our own Custom processor to extract baggage info? Some references in the doc also imply that there is a BaggagePropagator that is enabled by default (see below). Any clarification on this and in the docs' Baggage API section would be greatly appreciated:

_Baggage API allows users to add context to metric, traces, and logs. Baggage can be propagated out of proc using Propagators. OpenTelemetry SDK ships a BaggagePropagator and enables it by default._

**Comment by alanwest** [comment]
Can you provide a repro of what you're seeing?

Also, take a look at #2298 - it changed some behavior of `Baggage.Current` which may be affecting you depending on how you're using it.

**Comment by lhidalgo89** [comment]
@alanwest After looking into it a bit more, I confirmed that baggage is in fact propagated as expected out of process. I created a custom processor that let's me see the contents of baggage as expected during the OnStart() method. So my original statement of propagation not working out of the box was incorrect.

That being said is there a suggested/preferred place to put baggage data so it can be collected and visualized? (I'm using the Splunk Otel collector, in my case) Or is adding it to Activity.Tags.Current via a custom processor about the only way to do this?

**Comment by cijothomas** [comment]
There is no "suggested/preferred" place. The only place available in tracing is by using Activity.SetTag().
For other signals like logging and metrics, it'd be similar - one has to manually read Baggage, and set it.

**Comment by cijothomas** [comment]
For metrics, there is a feature by which SDK automatically reads Baggage and use it Metric attribute/tags, but the spec for the same is being discussed and not yet stable. (OTel .NET doesnt have that feature yet anyway).

**Comment by lhidalgo89** [comment]
@cijothomas Thanks for the quick response.
