### ISSUE TITLE
Counter injection

### ISSUE THREAD

**Issue by Bohdan555** [open-telemetry/opentelemetry-dotnet#2728]
Is it possible to inject Counter via constructor and use it when needed or it should be created right before using it

**Comment by cijothomas** [comment]
Counters (and any instruments in general) should be created once and reused throughout. You may create them and store in static fields as shown here https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/metrics/getting-started/Program.cs#L24

OpenTelemetry SDK doesn't inject any instrument to DI - but you may do so yourself.
