### ISSUE TITLE
How to build solution

### ISSUE THREAD

**Issue by sumit84mca** [open-telemetry/opentelemetry-dotnet#2729]
I cloned the repository but getting a lot of errors. I spent hours to resolve them. Now I am having these errors and dont know how to resolve these.
![image](https://user-images.githubusercontent.com/18229166/145035587-ee23c6c7-c97b-4d92-be15-bf76c4f06828.png)

**Describe your environment.**
I am using Visual Studio 2019 on Window 10 Professional

**What are you trying to achieve?**

The solution/project file should get build. 
If there is any guide to build the solution/project please let me know.

**Comment by tomkerkhove** [comment]
Did you check if you've met the prerequisites?

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md#development-environment

**Comment by sumit84mca** [comment]
> Did you check if you've met the prerequisites?
> 
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md#development-environment

Yes I have all the prerequisite.
![image](https://user-images.githubusercontent.com/18229166/145045983-17ded9c2-900a-4f6e-a717-6468d7a329c3.png)
![image](https://user-images.githubusercontent.com/18229166/145049272-82d63856-c7a7-4dd5-82f5-bd2b41abb740.png)

**Comment by tomkerkhove** [comment]
Looks like you don't have .NET 4.6.x installed, can you add that please?

**Comment by sumit84mca** [comment]
I have it
![image](https://user-images.githubusercontent.com/18229166/145076602-764d8316-fa3b-41ef-8b72-ed8557ead759.png)

**Comment by cijothomas** [comment]
The contributing guide may be outdated. If you are using Visual Studio, could you try with Visual Studio 2022? 2019 don't support .net 6.0 I believe.

**Comment by sumit84mca** [comment]
Its failing in VS2022 as well.
