### ISSUE TITLE
Sampling API needs to be revisited 

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#273]
https://github.com/open-telemetry/oteps/blob/master/text/0006-sampling.md

**Comment by lmolkova** [comment]
this was accidentally closed via PR. There are more changes coming through OTEP, so let's keep it open.

Also, spec now asks to have [extra config](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#built-in-samplers) for  probability sampler 

> The default behavior is to apply the sampling probability only for Spans that are root spans (no parent) and Spans with remote parent. However there should be configuration to change this to "root spans only", or "all spans".

**Comment by CodeBlanch** [comment]
@cijothomas @rajkumar-rangaraj FYI I'm working on bringing us up to spec as it is right now with regard to Probability & ParentOrElse sampler. Should have a PR up soon, just working on tests.

#### Probability

* The `ProbabilitySampler` MUST ignore the parent `SampledFlag`.
  To respect the parent `SampledFlag`, the `ProbabilitySampler` should be used as a delegate of the `ParentOrElse` sampler specified below.
* Description MUST be `ProbabilitySampler{0.000100}`.

TODO: Add details about how the `ProbabilitySampler` is implemented as a function
of the `TraceID`.

#### ParentOrElse

* This is a composite sampler. `ParentOrElse(delegateSampler)` either respects the parent span's sampling decision or delegates to  `delegateSampler` for root spans.
* If parent exists:
  * If parent's `SampledFlag` is set to `true` returns `RECORD_AND_SAMPLED`
  * If parent's `SampledFlag` is set to `false` returns `NOT_RECORD`
* If no parent (root span) exists returns the result of the `delegateSampler`.
* Description MUST be `ParentOrElse{delegateSampler.getDescription()}`.

|Parent|`ParentOrElse(delegateSampler)`
|--|--|
|Exists and `SampledFlag` is `true`|`RECORD_AND_SAMPLED`|
|Exists and `SampledFlag` is `false`|`NOT_RECORD`|
|No parent(root spans)|Result of `delegateSampler()`|

**Comment by alanwest** [comment]
I asked Mom and she said, "LGTM." (looks good to mom)

**Comment by cijothomas** [comment]
Closing in favor of: https://github.com/open-telemetry/opentelemetry-dotnet/issues/941
