### ISSUE TITLE
Export .net event counters through OpenTelemetry

### ISSUE THREAD

**Issue by MichaelLogutov** [open-telemetry/opentelemetry-dotnet#2730]
Hello.
I use OpenTelemetry with Prometheus exporter to export my custom metrics and it's working great.
I would love to be able to export also some of the [.net event counters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/available-counters) as well. For example, GC related. Currently I can only see them with [dotnet-counters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection#view-metrics-with-dotnet-counters).

Is there a way to do this?

**Comment by cijothomas** [comment]
Once https://github.com/open-telemetry/opentelemetry-dotnet/issues/2521 lands, this would be easier. For now, you'll have to write own event counter listener, and in turn, convert them to the new Metrics API.

**Comment by MichaelLogutov** [comment]
Thanks! Looking forward to it.
