### ISSUE TITLE
Counters are disabled

### ISSUE THREAD

**Issue by Bohdan555** [open-telemetry/opentelemetry-dotnet#2734]
Hello,
I am trying to use Counters in .net web api project.
To do it i created singleton of Meter and then injected to a class were i wanted to use it.
Then i created instance of Counter using meter object which i registered and counter gets disabled from the start. 
Maybe i am missing something when register instance of Meter?

**Comment by cijothomas** [comment]
Without seeing code snippets, its not easy to tell if anything is wrong.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/metrics/getting-started/Program.cs The getting started doc has runnable examples for reference. Please check them and see if you can fix the issue by following them.
