### ISSUE TITLE
CONTRIBUTING.md - actually explain how to generate `.publicApi` files from Intellisense

### ISSUE THREAD

**Issue by Aaronontheweb** [open-telemetry/opentelemetry-dotnet#2739]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md#public-api 

> Use [IntelliSense](https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2022) to update the publicApi files.

There is nothing in the referenced VS documentation that explains how to create one of these files in the correct format expected by the project. I'd love to be able to contribute to the public API and resolve issues such as https://github.com/open-telemetry/opentelemetry-dotnet/issues/2733 but this is a blocking issue for that type of work.

**Comment by tomkerkhove** [comment]
I've had the same struggle.

**Comment by cijothomas** [comment]
Would you be able to send a PR to improve the contributing.md doc to clarify this? (Assuming you figured it out already.)
(I personally use Visual Studio and its tool tip action to achieve this. And copy the generated changes to all target frameworks as VS only does it for 1st target framework only)

![image](https://user-images.githubusercontent.com/5232798/145837106-221417da-b05e-45b9-a0bb-49c01ed78623.png)


@eddynaka Do you know of any alternate to make this easier?

**Comment by tomkerkhove** [comment]
Huh, I didn't have that option, but it might be because of me.

**Comment by eddynaka** [comment]
Hi @cijothomas , I'm not aware of any other way to do that.
There is a proposal to use dotnet-format to fix it, but that isn't completed yet:
https://github.com/dotnet/roslyn-analyzers/issues/5130

**Comment by cijothomas** [comment]
Thanks @eddynaka 

At the minimum, we can update the guide to indicate which one from (shipped, unshipped) should be used when submitting PRs. 
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2740#discussion_r767848138

**Comment by mic-max** [comment]
I have also only used the Visual Studio way but I didn't know I had to manually copy the suggested change to the other targeted framework(s). It did `netstandard2.0` and I copied the file to `net461`

**Comment by alanwest** [comment]
If you're using 

> (I personally use Visual Studio and its tool tip action to achieve this. And copy the generated changes to all target frameworks as VS only does it for 1st target framework only)

In Visual Studio, there is a drop down in the upper right that allows you to change the target framework. You can cycle through each of the target frameworks and apply the tool tip action to each. Not great, but it's a little better than copying and pasting.

**Comment by TimothyMothra** [comment]
How would the community feel about adding screenshots to the Contributing guide to demonstrate how to generate the PublicApi files?
Someone would just need to delete the files locally and take screenshots while recreating them.
Something like this: https://github.com/dotnet/roslyn-analyzers/issues/3322#issuecomment-591031429

**Comment by Aaronontheweb** [comment]
@TimothyMothra I think that would be a good idea

**Comment by cijothomas** [comment]
> How would the community feel about adding screenshots to the Contributing guide to demonstrate how to generate the PublicApi files? Someone would just need to delete the files locally and take screenshots while recreating them. Something like this: [dotnet/roslyn-analyzers#3322 (comment)](https://github.com/dotnet/roslyn-analyzers/issues/3322#issuecomment-591031429)

to avoid making the contributing guide too big (esp. with screenshots), and scare contributors, might be good to extract the Public API part to own file. Only subset of contributors who make public api change need to worry about it.
