### ISSUE TITLE
How to extend the opentelemtry things with own stuff

### ISSUE THREAD

**Issue by paule96** [open-telemetry/opentelemetry-dotnet#2741]
# Question

I currently try to add the ability to see a bit more inside the MVC logic that happens if a request hits the server and goes there way until it reaches the controller, with the correct action.
The implementation for this is basically ready to ship, for example, the contrib repository. But I hit a big problem while developing that makes me a bit fearful for the future:
Everything that should be used to extend the functionality is declared as internal. For example, `DiagnosticSourceSubscriber` that is used to register a new `ListenerHandler` can't be used outside of the open telemetry project.
The same count's for defined strings from the specifications that are currently in `SemanticConventions`. This is marked too as internal and can't be used to extend the framework.
Is there a way to make this library a bit more open for other developers to use in their libraries? It would be for some parts really helpful if just some random person can implement somewhere a piece of code to enhance his open telemetry experience, without doing all the hard basement work you already did.

**What are you trying to achieve?**

Developing and instrumentation (aka `ListenerHandler`) that has currently not its home here in the project.
And I expect to do this as easily as possible.

## Additional Context

Here is a list that would be cool in my opinion to make public:

- `DiagnosticSourceSubscriber`
- `ListenerHandler`
- `ActivityInstrumentationHelper`
- `SemanticConventions`

Nice to have because it is super cool and easy to use:
- `PropertyFetcher`

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md#public-api We only expose APIs publicly if there is a need. Helpers like the one asked above won't be exposed from this repo. ListenerHandler, DiagnosticSourceSubscribes etc are helpers we use internally, and are not specific to OpenTelemetry.

SemanticConventions is a spec requirement, it'll be exposed in the future. (the semantic conventions themselves are still experimental today)

**Comment by dv42** [comment]
Is there a plan to support some sort of extensibility for existing instrumentations?

For example, ASP.NET Core metrics currently defines duration histogram with 4 tags [(HttpInMetricsListener implementation)](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs)

I have a business case under which I need to add 1 more tag. At this moment there seems to be no option to add extra tag.
One way to implement more custom functionality is by extending HttpInMetricsListener or writing custom metrics. However, HttpInMetricsListener is internal so it's not an option and as you mentioned, helpers such as ListenerHandler, DiagnosticSourceSubscriber won't be a part of the public API so it's not possible to write a custom Listener and rely on heavy lifting that is done inside this internal helpers.

**Comment by cijothomas** [comment]
> Is there a plan to support some sort of extensibility for existing instrumentations?

Most of the instrumentations for tracing already allows this using Enrich. For those instrumentations which do not offer Enrich/equivalent, the spec allows enriching Activity/Span by adding ActivityProcessor/SpanProcessor.

The instrumentations for metrics are in very early stage now and has no customization capabilities, but will be enhanced in the future. (Note that the Metric spec, as of today, **does not allow adding new tags** via MetricProcessor/equivalent. Only the ability to remove a tag from Metric is currently allowed per spec. Once the specs cover these requirements, and OTel .NET supports them, extending Metrics would be possible.)
