### ISSUE TITLE
No sql query tag using net4.8 and SetDbStatement to true

### ISSUE THREAD

**Issue by dzediar** [open-telemetry/opentelemetry-dotnet#2743]
Hello,

I don't have the sql queries in the activity tags under .net 4.8. 

By copying the code from SqlEventSourceListener and running it I have indeed noticed that the payload[3] received by the eventlistener is empty whereas it is supposed to contain the sql request. 

Also, I can see that the "Enrich" action is never executed in the code of the SqlEventSourceListener. 

Is there a way to have sql query in activities with .net 4.8 ?

Thx.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2738 duplicate
