### ISSUE TITLE
Prometheus Exporter Tests Should Cover for Async Counter (CounterObserver) Metrics

### ISSUE THREAD

**Issue by rltoSD** [open-telemetry/opentelemetry-dotnet#2757]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/test/OpenTelemetry.Exporter.Prometheus.Tests/PrometheusSerializerTests.cs

While verifying the existence of tests in the repository, I noticed that Async Counter metrics were not being tested for. I believe for even better coverage that this test should be added

**Comment by cijothomas** [comment]
@TimothyMothra

**Comment by TimothyMothra** [comment]
Hello @rltoSD,
Hello @erichsueh3
I'm looking for some clarification on this ask.

Regarding the PrometheusSerializer unit tests,
The code paths for Counter and Async Counter are the same and the serializer's output is nearly identical.
Both Instrument Types are testing the same "Sum Aggregation". 

I think this issue can be closed, but I wanted to get your input.

Java SDK had an identical ask and a decision was made to NOT add additional unit tests.
https://github.com/open-telemetry/opentelemetry-java/issues/4031

**Comment by cijothomas** [comment]
Closing as no need for testing Counter and Async Counter separately. From exporter standpoint, it does not know if Metrics was recorded using sync or async instruments, and hence it is not a concern of the Exporter to test.
