### ISSUE TITLE
Consider having TracerBuilderExtensions classes use the same namespace

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#276]
Consider making all the `TracerBuilderExtensions` live in the `OpenTelemetry.Trace.Configuration` namespace. A common namespace that is probably already imported will help them show up in intellisense when the NuGet package is referenced. Note that if you do this then you should make the extension method class names unique: 

* Before - `OpenTelemetry.Exporter.ApplicationInsights.TracerBuilderExtensions`
* After - `OpenTelemetry.Trace.Configuration.ApplicationInsightsTracerBuilderExtensions`

We do this in ASP.NET Core for DI extension methods. Methods that extend `IServiceCollection` are always in `Microsoft.Extensions.DependencyInjection` namespace.

**Comment by lmolkova** [comment]
Good point, I'll fix ot
