### ISSUE TITLE
Batch export vs periodic exporting with OLTP exporter

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry-dotnet#2767]
# Question

**Describe your environment.**

We are using the OTLP exporter with the default settings:

```csharp
var configuredMetricProvider = Sdk.CreateMeterProviderBuilder()
                .AddMeter("Sample.*")
                .AddOtlpExporter(options => { options.Endpoint = new Uri(collectorUri); })
```

**What are you trying to achieve?**

We are using the OTLP exporter and want to understand what the interval is in which metrics will be flushed.

However, I'm not sure how `options.BatchExportProcessorOptions.ScheduledDelayMilliseconds` & `options.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds` relate with each other.

I had the impression that one or the other is being used, but based on the default values they should both be used. (based on reading the code):

https://github.com/open-telemetry/opentelemetry-dotnet/blob/1191a2a3da7be8deae7aa94083b5981cb7610080/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L115-L130

## Additional Context

N/A

**Comment by alanwest** [comment]
This is admittedly a little confusing at the moment.

`ExportProcessorType` and `BatchExportProcessorOptions` is only used for trace data at the moment.

`MetricReaderType` and `PeriodicExportingMetricReaderOptions` are used for metric data.

So, that's to say that `options.BatchExportProcessorOptions.ScheduledDelayMilliseconds` and `options.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds` do not relate to each other. First one is used by the OTLP trace exporter and the second one used by the OTLP metrics exporter.

There's some works in progress exploring some different concepts for making the exporter's configuration more intuitive. (#2717 and #2721).

**Comment by tomkerkhove** [comment]
Thanks for explaining! Would it make sense if I send a PR to update the XML docs with this info? (trace vs metric)

**Comment by alanwest** [comment]
You might wait just a bit. We'll settle on an approach in one of the PRs in progress soon. What we do there may influence how to best document things. I agree we need to make this more clear.

**Comment by tomkerkhove** [comment]
Sounds good to me and thanks for the help.

Will close the issue for now.
