### ISSUE TITLE
dotnet add package OpenTelemetry.Extensions.Hosting not getting installed

### ISSUE THREAD

**Issue by rahulsahay19** [open-telemetry/opentelemetry-dotnet#2773]
# Bug Report
This command ```dotnet add package OpenTelemetry.Extensions.Hosting ``` while issuing from the package manager console not working. Also, its not taking from Manage nuget package. While searching itself, its not coming. and if manually, put package as 

```<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc7" />```

Then, it comes, but then it start giving package version conflict with the namespace ```using Microsoft.Extensions.Hosting;```
Not sure why. Currently, I am in .Net 5 version.

* Runtime version

Runtime version  `net5.0` 

* OS
## Macbook Pro

I am also using rider and there is parallels also installed. Hence, already tried with rider and VS2019. But, I don't think this is anything to do with OS.

**What is the expected behavior?**
It should compile as expected.

What did you expect to see?
Its failing with version conflict.

In case if you need repo url. Let me know, I can provide that as well. 

Thanks,
Rahul

**Comment by tomkerkhove** [comment]
I have not tried this, but can you try using `dotnet add package OpenTelemetry.Extensions.Hosting --prerelease`?

My guess is that installation is failing because all packages are still in preview and there is no stable package to install.

**Comment by cijothomas** [comment]
> Its failing with version conflict.

Might be something already fixed? Could you update to the newest version of all packages? If the issue persists, please re-open and share minimal repro project.
