### ISSUE TITLE
The default listening port for Prometheus Exporter

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#2780]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry.Exporter.Prometheus 1.2.0-rc1

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can
find this information from the `*.csproj` file):

* net6.0

## Symptom

PrometheusExporter by default listens on `*:80` which gives two concerns - security / attack surface, 80 is a well known port and it requires privilege on certain operating systems.

**What is the expected behavior?**

1. the exporter should listen on localhost by default
2. the exporter should use a port that is greater than 1024 by default

**What is the actual behavior?**

The exporter is listening on `*:80` by default

## Additional Context

It seems some existing Prometheus components are using `9100` and `9091` by default https://prometheus.io/docs/guides/node-exporter/.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/18d73c59f021b1c7a9bd433ea703e6f2c22a0b90/src/OpenTelemetry.Exporter.Prometheus/PrometheusExporterOptions.cs#L51

**Comment by Yun-Ting** [comment]
There's a issue opened on adding authentication on the Prometheus middleware endpoint lately: #2776

**Comment by Yun-Ting** [comment]
Note: The PR is merged and this issue can be closed. (I'm not authorized to do that.)

**Comment by mic-max** [comment]
Should we automate the removal of the `Stale` tag on merged pull requests?
