### ISSUE TITLE
Refine the default resource service.name

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet#2781]
Ideally, the SDK should try the name of the entry assembly first and only if that fails fallback to the process name. This way it gets better default names for applications started via `dotnet MySvc.dll` which is currently resolves `dotnet` as the process name.

Do you see any problem with such a change?

_Originally posted by @pjanotti in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/312#discussion_r782478960_

**Comment by cijothomas** [comment]
This sounds reasonable change.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service

**Comment by pellared** [comment]
> If the value was not specified, SDKs MUST fallback to `unknown_service:` concatenated with [`process.executable.name`](process.md#process), e.g. `unknown_service:bash`

As far as I understand we would first need to propose a change in the specification to allow different values than ``process.executable.name` such as "name of the executing assembly". Can you confirm, please?

**Comment by cijothomas** [comment]
mm. Yes it feels some change to spec would be needed, given its a "MUST" in the spec.

**Comment by julealgon** [comment]
Was there any further discussions on this since January? This default is so bad that it basically enforces every application to change it otherwise telemetry info becomes nearly impossible to follow.

Seeing stuff like `unknown_service_w3wp` or `unknown_service_dotnet` is completely useless as it basically conflates every single application if they do not set a value manually.

**Comment by pellared** [comment]
@julealgon None that I am aware of. Feel free to create a PR/issue in [OTel specification](https://github.com/open-telemetry/opentelemetry-specification) or join their SIG meeting (more info [here](https://github.com/open-telemetry/community#specification-sigs)).

**Comment by Kronos11** [comment]
This would be a really great change in my mind as well. Having better defaults or a way to change this on a per application basis is going to be the only viable solution here.

**Comment by Kronos11** [comment]
@cijothomas what we talked about last night in the SIG, maybe I didn't do the request justice.

**Comment by pellared** [comment]
Per https://github.com/open-telemetry/opentelemetry-specification/issues/3210 we could simply create a new resource detector that sets the service.name resource based on the name of the entry assembly.

**Comment by pellared** [comment]
FYI here is a code that we have in .NET Automatic Instrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/42c51e6273df04cfe54e08ae073939cf515c2e93/src/OpenTelemetry.AutoInstrumentation/Configurations/ResourceConfigurator.cs#L51
