### ISSUE TITLE
Create an OpenTracing Bridge

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-dotnet#28]
See https://github.com/open-telemetry/opentelemetry-java/tree/master/opentracing-shim/src/main/java/io/opentelemetry/opentracingshim for the Java implementation

**Comment by trwegner** [comment]
Refactoring src\OpenTelemetry.Exporter.ApplicationInsights\Implementation\TraceExporterHandler.cs#ExportAsync should be included with this work as well.  Current implementation has explicit handling for OpenTracing Standard Span Tags, https://github.com/opentracing/specification/blob/master/semantic_conventions.md

**Comment by pcwiese** [comment]
Is anyone actively working on this issue?

**Comment by austinlparker** [comment]
Not currently, it's up for grabs. Are you interested in it?

**Comment by pcwiese** [comment]
Yes. Happy to take a stab at it.

**Comment by austinlparker** [comment]
All yours! Feel free to reach out if you have any questions.

**Comment by pcwiese** [comment]
What is the current plan for OpenTracing Baggage items? I read here https://lightstep.com/blog/building-a-bridge-connecting-opentracing-with-opentelemetry/ that it corresponds to OpenTelemetry's Tag (the current name from what I gather) but then I come across issues and specs for DistributedContext. It sounds like DistributedContext is meant to replace Tags in the API but renaming has not happened yet?

**Comment by austinlparker** [comment]
That's correct - there's some stuff in the works to nail down DistributedContext because I don't think it's been completely specced out/people aren't fully happy with it and baggage would eventually go in there.

**Comment by pcwiese** [comment]
@austinlparker I'm working my way through the context propagator stuff. I see code in the java shim's propagator looking for binary injection formats, and I do see references to a binary format here
https://github.com/opentracing/opentracing-csharp/blob/master/src/OpenTracing/Propagation/BuiltinFormats.cs

However, that looks to be recently added and is not part of the latest NuGet package that I am referencing. Given that, do I need to add support for a binary format at all in the propagation shim?

**Comment by austinlparker** [comment]
Binary propagation is in the most recent OpenTracing prerelease (https://www.nuget.org/packages/OpenTracing/0.12.1-rc4), which should go to full release within the next couple weeks.

**Comment by pcwiese** [comment]
In that case this shim would only support the last release (probably) of OpenTracing (in C#).

**Comment by austinlparker** [comment]
That's fine.

**Comment by pcwiese** [comment]
I'm a little confused about the intended behavior of OpenTracing IScopeManager Active property. Activate seems clear enough to me; mark the current Span as Active and give back an IDisposable that will end the Span when disposed (assuming finishOnDispose is true). Is the intent of the Active property to return the current Span as a disposable also? And that disposing is essentially a no-op if that Span was Activated with finishOnDispose = true? 

If my understanding is correct, I just don't see any way to propagate that boolean flag down through to OpenTelemetry with the public SDK. My original thought was to pass something thin that wraps the OpenTelemetry ISpan and augments with this boolean flag. However, the OpenTelemetry implementation of WithSpan is assumes that the Span implementation getting passed down is the actual OpenTelemetry Span, otherwise the Span -> Activity housekeeping isn't done. The Span class is also sealed, so I can't subclass that either.

It seems to me without some kind of change to the OpenTelemetry SDK we cannot implement the IScopeManager shim properly.

@austinlparker @lmolkova  for comments specifically.

**Comment by austinlparker** [comment]
Spans aren't disposable, but Scopes are - the idea is that when you call `Dispose` on an `IScope` then the span that's scoped to it will get finished. Both `Active` and `Activate` return a `IScope`, but the idea behind `Activate` is to allow someone to janitor their spans manually while benefitting from the scope manager (see https://github.com/opentracing/opentracing-csharp/blob/master/test/OpenTracing.Tests/Util/AsyncLocalScopeTests.cs#L18 for an example), which... I'm not sure how many people actually use it.

My gut feeling would be to add a deprecation warning to `finishSpanOnDispose` in the shim for now, and we can do some research on the OpenTracing side to see how useful it is.

**Comment by pcwiese** [comment]
I can mark that flag as deprecated however I'm still confused on how to adapt these two interfaces together. As is, it just won't work I think.

```csharp
// Please check my understanding of this sequence here
using (var foo = tracer.Activate(span, true))
{
  using (var bar = tracer.Active)
  {
  }

  // At this point bar is disposed and the underlying span for both the foo and bar scopes should be ended right?
}
```

Now if I try to map that understanding to OpenTelemetry API to achieve that I get something like:
- A call to ITracer.WithSpan(span) which returns an OpenTel IScope (which has no span information).
- To satisfy OpenTracing IScope, I can return a ScopeAdapter which takes that OpenTel scope and also exposes the span which was passed to it. This is ok.
- For the call to tracer.Active I have to map that to OpenTel ITracer.CurrentSpan which returns an ISpan implementation (not an OpenTel IScope implementation). At this point we just don't know which scope the current span belongs to and there is no way to get it. At best here, disposing of bar would be a no-op which won't be correct.

**Comment by austinlparker** [comment]
`Active` wouldn't give you a new scope, it'd give you back the same scope, so your example would result in a runtime error if you tried to interact with the span in the outer `using`, like so -

```
using(var scope = tracer.Activate(span, true))
{
    using(var sameScope = tracer.Active)
    {
        sameScope.Span.Log("hi");
    }
 scope.Span.Log("will throw here as i'm logging on a finished span")
}
```

If I pass `false` to `finishSpanOnDispose` then it will not be an error (although I'll have to manually finish the span). 

I'm don't think that answers your question though. Let me look at the OTel code a bit.

**Comment by pcwiese** [comment]
Right. I'm assuming Active would give me the same scope as the outer scope. That example is still valid though. My point is that disposing the inner scope should be effectively the same as disposing the outer scope. That is not possible with the current OpenTel code.

**Comment by austinlparker** [comment]
Looking at `WithSpan`...

```
        public IScope WithSpan(ISpan span)
        {
            if (span == null)
            {
                throw new ArgumentNullException(nameof(span));
            }

            return CurrentSpanUtils.WithSpan(span, true);
        }
```

Why not just change the signature of `WithSpan` to `WithSpan(ISpan span, finishOnDispose = true)`, then we can pass the OT flag through as-is?

**Comment by lmolkova** [comment]
I was looking into Java impl and OT Java took approach of always explicit scope and span end. I.e. you *always* dispose scope and end span independently. disposing scope *never* results in ending span. I was thinking about doing the same rather than having inconsistent behavior and flag.

**Comment by pcwiese** [comment]
Even if we did that, that doesn't address the problem I outlined above. OpenTel CurrentSpan returns the span, not a scope. There is no way to correlate that returned span with the active scope created by a call to WithSpan.

**Comment by lmolkova** [comment]
Scope can have an API to retrieve a Span

**Comment by pcwiese** [comment]
So IScope becomes?:

```csharp
public interface IScope : IDisposable
{
  public ISpan Span { get; }
}
```csharp

If we return IScope from ITracer::CurrentSpan instead of ISpan that would work.

**Comment by austinlparker** [comment]
Yeah, that'd work.

**Comment by austinlparker** [comment]
I tried it out locally and it's pretty straightforward - 

```
diff --git a/src/OpenTelemetry.Abstractions/Context/IScope.cs b/src/OpenTelemetry.Abstractions/Context/IScope.cs
index 4d0ef63..7bf44b7 100644
--- a/src/OpenTelemetry.Abstractions/Context/IScope.cs
+++ b/src/OpenTelemetry.Abstractions/Context/IScope.cs
@@ -17,6 +17,7 @@
 namespace OpenTelemetry.Context
 {
     using System;
+    using OpenTelemetry.Trace;

     /// <summary>
     /// Scope marker. Used as a syntactic sugar in methods like StartScopedSpan so it can be
@@ -24,5 +25,6 @@ namespace OpenTelemetry.Context
     /// </summary>
     public interface IScope : IDisposable
     {
+        ISpan Span { get; }
     }
 }
```

```
diff --git a/src/OpenTelemetry/Trace/CurrentSpanUtils.cs b/src/OpenTelemetry/Trace/CurrentSpanUtils.cs
index b3e1b21..4eecb44 100644
--- a/src/OpenTelemetry/Trace/CurrentSpanUtils.cs
+++ b/src/OpenTelemetry/Trace/CurrentSpanUtils.cs
@@ -75,6 +75,8 @@ namespace OpenTelemetry.Trace
             private readonly ISpan span;
             private readonly bool endSpan;

+            ISpan IScope.Span => span;
+
             public ScopeInSpan(ISpan span, bool endSpan)
             {
                 this.span = span;
```

**Comment by austinlparker** [comment]
`tracer.Active` should return an `IScope` however, then you'd read the span from that scope instance?

**Comment by pcwiese** [comment]
I suppose so. This would be a rippling change

**Comment by austinlparker** [comment]
That's a better option, agreed.

**Comment by pcwiese** [comment]
Something like this maintains the current behavior and augments with additional functionality for me to use in the shim. Existing tests don't need modification although it muddy's the public API a bit.

https://github.com/open-telemetry/opentelemetry-dotnet/pull/192

I added the following additional API methods to ITracer
```csharp
        /// <summary>
        /// Gets the current scope from the context.
        /// </summary>
        ISpanScope CurrentScope { get; }

        /// <summary>
        /// Associates the span with the current context.
        /// </summary>
        /// <param name="span">Span to associate with the current context.</param>
        /// <param name="endOnDispose">If true, the span will end when the returned scope is disposed.</param>
        /// <returns>Scope object to control span to current context association.</returns>
        ISpanScope WithSpan(ISpan span, bool endOnDispose);
```

**Comment by pcwiese** [comment]
With these changes applied from the unpublished PR above, I was able to get my shim functional for an ASP.NET Core 3 app.

**Comment by pcwiese** [comment]
A question for @lmolkova regarding this block:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/5c5f2fc191c8a5b1a5b419bbe2b530fee1a567f4/src/OpenTelemetry/Trace/Span.cs#L301

Should it be just?
```csharp

if (this.OwnsActivity)
{
    this.Activity.Stop();
}

```

The reason being if you start a Span **without** making it active, and then stop it via End, the span has no end timestamp because its Activity was never stopped. If this spans owns its Activity, shouldn't we always stop it regardless of whether it is the current activity?

**Comment by lmolkova** [comment]
span should not stop the Activity it does not own.  If someone attempts to stop span in the scope of some other Activity, we should set timestamps on the span and stop it, but never touch Activity that is not ours.

**Comment by pcwiese** [comment]
Right. In this case though, calling span end is not stopping the activity that it does own. The span’s activity was never made current via a call to WithSpan

**Comment by austinlparker** [comment]
This was completed in #197, we'll make new issues as they come up.
