### ISSUE TITLE
No tracing when using Dapper

### ISSUE THREAD

**Issue by bend** [open-telemetry/opentelemetry-dotnet#2804]
# Question

**Describe your environment.**

.Net5

**What are you trying to achieve?**

I would like to see some tracing related to Sql queries & Dapper

## Additional Context
I tried to setup SqlInstrumentation using the .AddSqlClientInstrumentation() extension method, however, I don't see any trace related to SQL when dapper is called.
I see the other traces related to Grpc or Masstransit

**Comment by reyang** [comment]
Closing, please use https://github.com/open-telemetry/opentelemetry-dotnet/discussions for questions.
BTW what is Dapper?

**Comment by GuttormAndreas** [comment]
What is Dapper ? You got to be kidding
