### ISSUE TITLE
Add net.peer attributes to HttpClient traces

### ISSUE THREAD

**Issue by Code-Grump** [open-telemetry/opentelemetry-dotnet#2811]
# Feature Request

**Is your feature request related to a problem?**

Currently the spans produced for `HttpClient` do not include `net.*` attributes, which causes some consumers to fail to identify the external system being called.

**Describe the solution you'd like:**

Spans generated for `HttpClient` should also include these `net.*` attributes:
- `net.peer.ip`
- `net.peer.name`
- `net.peer.port`

These are included in the [HTTP Common Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes) and seem relatively trivial to add. These attributes are expected by some consumers to correctly identify the external system.

**Describe alternatives you've considered.**

I am looking at adding my own enrichment to these events, using the `HttpClientInstrumentationOptions.Enrich` property.

## Additional Context

None at this time.

**Comment by vishweshbankwar** [comment]
Spec has changed and these attributes are no longer there.
