### ISSUE TITLE
Unnecessary bump to 6.0.0.0 version of System.Diagnostics.DiagnosticSource in net5.0 project

### ISSUE THREAD

**Issue by Matiszak** [open-telemetry/opentelemetry-dotnet#2824]
# Bug Report

Nuget:
- OpenTelemetry.Api, Version=1.2.0-beta2.1
- (it might include more packages since version of System.Diagnostics.DiagnosticSource is defined in CommonProps)

Runtime version: net5.0

## Symptom

When adding OpenTelemetry.Api nuget reference to net5.0 project it forces upgrade of System.Diagnostics.DiagnosticSource library to version 6.0.0.0 which is shipped with net6.0 framework. Beside that there might be breaking changes for code which is already compiled against 5.0.0 we also have issue with ElasticApm which is doing some stuff based on this library version and assuming .net 6 runtime. It might not be the best but I think more of the fault lies on OpenTelemetry.Api package.

Expected behaviour:

Solution should still use default 5.0.0.0 version of System.Diagnostics.DiagnosticsSource. Underneath if should 'if net5.0' and for that environment use 5.0.0.0 package (similarily like in AspNet packages). For example here:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/OpenTelemetry.Instrumentation.AspNetCore.csproj
```
  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

**What is the actual behavior?**

- System.Diagnostics.DiagnosticSource with version 6.0.0.0 is added to output folder after compilation
- This shows version 6.0.0.0 of library: AppDomain.CurrentDomain.GetAssemblies() .Where(a => a.GetName().Name.Equals("System.Diagnostics.DiagnosticSource", StringComparison.Ordinal)).ToList();

## Reproduce

Two solutions created with net5.0, one of them having version upgraded: https://github.com/Matiszak/opentelemetry_repro

Output:
```
With open telemetry nuget:
Assemblies loaded:
System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Without open telemetry nuget:
Assemblies loaded:
System.Diagnostics.DiagnosticSource, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
```

**Comment by cijothomas** [comment]
`System.Diagnostics.DiagnosticSource` 6.0 is *required* (and not unnecessary as whole OTel is built on top of DiagnosticSource) and is the minimum version required for OpenTelemetry. Otel depends on features from 6.0 of the package. Its independent of the .NET runtime, so the above is needed in net461 and higher, netcoreapp3.1 and higher, net5 and higher etc.
