### ISSUE TITLE
Dead link in source code

### ISSUE THREAD

**Issue by nmbro** [open-telemetry/opentelemetry-dotnet#283]
The line 
https://github.com/open-telemetry/opentelemetry-dotnet/blob/e299734f807aaa5a4b6be5439bfe471ce6d4b629/src/OpenTelemetry.Collector.AspNetCore/Implementation/HttpInListener.cs#L54

Points to a dead link: https://github.com/open-telemetry/OpenTelemetry-specs/blob/master/trace/HTTP.md

I have no idea what the right url is suppose to be

**Comment by lmolkova** [comment]
there is a PR for it - https://github.com/open-telemetry/opentelemetry-specification/pull/263. Once it's merged, we should update the link.

**Comment by Oberon00** [comment]
Related: open-telemetry/opentelemetry-specification#311
