### ISSUE TITLE
Prometheus Histogram and Summary types?

### ISSUE THREAD

**Issue by Rast1234** [open-telemetry/opentelemetry-dotnet#2834]
# Question

**What are you trying to achieve?**

Currently i use [AppMetrics](https://github.com/AppMetrics/AppMetrics). I'm trying to switch to opentelemetry metrics. Have a couple of questions regarding metric types and how to configure them.

## Histogram

**Prometheus** has [Histogram](https://prometheus.io/docs/concepts/metric_types/#histogram) metric type which places reported values in buckets.

**OpenTelemetry** defines [Histogram](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#histogram) with buckets.

**AppMetrics** calls this **BucketHistogram** and allows configuring buckets on each metric created:

```
var metric = new App.Metrics.BucketHistogram.BucketHistogramOptions { Buckets = new double[] { 1, 10, 100 } };
App.Metrics.Metrics.Instance.Measure.BucketHistogram.Update(metric, 42);
```

So how do i specify buckets for a histogram with opentelemetry-dotnet?

```
var metric = new Meter("name").CreateHistogram<int>("metric", ???);
```

I've tried looking in sources and found [DefaultHistogramBounds](https://github.com/open-telemetry/opentelemetry-dotnet/blob/cf3b119edd83effdab774ef6f3a33baab1834dfc/src/OpenTelemetry/Metrics/Metric.cs#L25) but have no idea how to pass them from user code.

## Summary

**Prometheus** has [Summary](https://prometheus.io/docs/concepts/metric_types/#summary) metric type which calculates quantiles.

**OpenTelemetry** defines [Summary](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#summary-legacy) as legacy for some reason.

**AppMetrics** calls this **Histogram** (yeah, confusing, i know). While it doesn't allow to configure quantiles/percentiles, user can specify sampling algorithm: uniform, exponentially decaying and sliding window.

```
var metric = new App.Metrics.Histogram.HistogramOptions() { Reservoir = () => new App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir(1024, 0.015) };
```

I've seen mentions of `Summary` type in prometheus serializer but can't find any metric that uses it. Is it unsupported? Are there any plans on this?

## Gauge

Currently existing ObservableGauge requires boilerplate code to maintain a counter and increase/decrease it. Are there any plans to make convenient extensions/wrappers/helpers to simplify its usage? Like a Counter but with .Increase/.Decrease methods maybe?

**Comment by cijothomas** [comment]
Histogram custom bounds: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk#specify-custom-boundaries-for-histogram

Summary : Not supported in SDK/no plans unless spec requires this. (It currently only exist in OTLP protos i think to support metrics from external sources.)

Gauge - Not a wrapper, but there'll be dedicated UpDownCounter and its observable counterpart. https://github.com/open-telemetry/opentelemetry-dotnet/issues/2362 This won't be part of 1st stable release, but would come in the next version.

**Comment by Rast1234** [comment]
Thanks!
