### ISSUE TITLE
HttpListenerPrefixes other than localhost

### ISSUE THREAD

**Issue by GuglielmoFrigerio** [open-telemetry/opentelemetry-dotnet#2840]
Does anyone tried to configure the exporter to publish on every network interface the host provide?
I've tried the following prefixes

- http://0.0.0.0:9184
- http://+:9184
- http://*:9184
- http://{_an-existing-network-interface-ip_}:9184
 
Nothing seems to work.

I've tried under Windows 11 & DotNet 6.

I wanted to test a scenario where the Prometheus server is remote respect to the application.

**Comment by Yun-Ting** [comment]
Hi @GuglielmoFrigerio, 
Could you share the code on how you configure the Prometheus server please?
Thank you.

**Comment by GuglielmoFrigerio** [comment]
Hi @Yun-Ting this is how I configure Prometheus in the Startup.cs:

            var prometheusConfigSection = Configuration.GetSection("Prometheus");
            var prefixes = prometheusConfigSection.GetSection("prefixes").Get<string[]>();
            _meterProvider = Sdk.CreateMeterProviderBuilder()
                .AddMeter("SessionControl")
                .AddPrometheusExporter(opt =>
                {
                    opt.StartHttpListener = true;
                    opt.HttpListenerPrefixes = prefixes;
                })
                .Build();

This is the app settings:

 ```
  "Prometheus": {
    "prefixes": [
      "http://localhost:9174/"
    ]
  }

```

**Comment by 8** [comment]
Hi,

I stumbled over the same bug, which makes exposing the metrics interface on all interfaces impossible.

After taking a look at the source code, I came up with the following workaround until the bug is fixed, by setting the private backing field directly using reflection, thereby sidestepping the buggy validation:
```cs
...
.AddPrometheusExporter(options =>
    {
      options.StartHttpListener = true;

      options.GetType()
        ?.GetField("httpListenerPrefixes", BindingFlags.NonPublic | BindingFlags.Instance)
        ?.SetValue(options, new[] { "http://*:9464" });
    });
```

Take care,
Martin
