### ISSUE TITLE
Follow-ups for Metric AggregatorStore refactoring and optimization

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet#2843]
Follow-ups for Metric AggregatorStore refactoring and optimization after #2805 is merged:
- Explore possible refactoring for checking if there are any MetricPoint indices available https://github.com/open-telemetry/opentelemetry-dotnet/pull/2805#issuecomment-1024737687
- Use dedicated lock to add entries to `tagsToMetricPointDictionary` https://github.com/open-telemetry/opentelemetry-dotnet/pull/2805#discussion_r795260108
- `SpinWait` instead of a `lock`? https://github.com/open-telemetry/opentelemetry-dotnet/pull/2805#discussion_r795260619
- `AggressiveInlining` for `Tags.GetHashCode` https://github.com/open-telemetry/opentelemetry-dotnet/pull/2805#discussion_r795260821

**Comment by stevejgordon** [comment]
@martinjt, it looks like all items are completed, and this can be closed.
