### ISSUE TITLE
OTLP/HTTP exporters should default to port 4318

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#2857]
Currently, the endpoint for OTLP exporters defaults to `http://localhost:4317` for both HTTP and gRPC export.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/2c9501fcd54aa52f18b1b98e90ce9004a890a89b/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L89-L94

OTLP/HTTP should default to `http://localhost:4318`: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options

**Comment by Kielek** [comment]
@alanwest, it will be great to cover two scenarios for updating Url
1) Env. variable
2) By the ``Protocol` setter. This Api is publicly available and it could make .net autoinstrumenation configuration much easier.

**Comment by alanwest** [comment]
> 1. Env. variable

Setting the endpoint by the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable is supported already (though, not yet the signal specific versions - e.g., `OTEL_EXPORTER_OLTP_TRACES_ENDPOINT`).

> 2. By the ``Protocol` setter. This Api is publicly available and it could make .net autoinstrumenation configuration much easier.

If I'm understanding you correctly, you want the endpoint to get set correctly when changing the protocol. So, for example 

```csharp
// The following should set the endpoint to http://localhost:4318
// assuming it was not otherwise explicitly set by the user
options.Protocol = OtlpExportProtocol.HttpProtobuf;
```

If this is what you meant, then yes this was my thought as well.

**Comment by Kielek** [comment]
Just to clarify my expectation to the behavior.,

Either, if you set  `OTEL_EXPORTER_OTLP_PROTOCOL` to `http/protobuf` 
or ```options.Protocol = OtlpExportProtocol.HttpProtobuf; ``` it changes port to 4318.

Thanks!
