### ISSUE TITLE
Baggage Type and Span Initial Attributes Type Differ

### ISSUE THREAD

**Issue by omamoo** [open-telemetry/opentelemetry-dotnet#2867]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and
version that you are using (e.g. `OpenTelemetry 1.0.2`):

OpenTelemetry.Api 1.2.0-beta1

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can
find this information from the `*.csproj` file):

Dotnet 5

## Symptom

While creating new span, the initial attributes parameter type is `SpanAttributes`. The constructor of this type expecting `IEnumerable<KeyValuePair<string, object>>`. 
However `Baggage.GetBaggage()` return type is `IReadOnlyDictionary<string, string>`.

Therefore the following line results in compile error:
`new SpanAttributes(Baggage.GetBaggage())`. And should be casted? to:
 `new SpanAttributes((IEnumerable<KeyValuePair<string, object>>)Baggage.GetBaggage())`

**What is the expected behavior?**
No need to cast when initializing new span with tags from baggage. 

**What is the actual behavior?**
Need to be casted explicitly.

## Reproduce
Just copy and paste the code described.

**Comment by cijothomas** [comment]
Baggage only allows string values, span attributes allows more types than string. This is expected behavior.

**Comment by ofirmamo** [comment]
@cijothomas, thanks for fast response. This is by the spec, can you share with me why this is the expected behaviour?

**Comment by omamoo** [comment]
@cijothomas You are right, after reviewing the spec again.

Thanks for the help.
