### ISSUE TITLE
Application crash when EventId contains null-message (after update to rc2/rc9)

### ISSUE THREAD

**Issue by DennisGlindhart** [open-telemetry/opentelemetry-dotnet#2870]
# Bug Report

ASP.NET (net6.0) with following packages
```
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.2.0-rc2" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.2.0-rc2" />   
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.0.0-rc9" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9" />
```
Enabling logging to Console and Otlp
```
logging.AddOpenTelemetry(n =>
    {
        n.AddConsoleExporter();
        n.AddOtlpExporter(options => options.Endpoint = new Uri("http://localhost:4317"));
    });
```

## Symptom

When logging is enabled the and exporting to Otlp (call to AddOtlpExporter()) is activated, app crashes hard a few seconds after starting.

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Opentelemetry.Proto.Common.V1.AnyValue.set_StringValue(String value)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.LogRecordExtensions.AddStringAttribute(RepeatedField`1 repeatedField, String key, String value)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.LogRecordExtensions.AddBatch(ExportLogsServiceRequest request, Resource processResource, Batch`1& logRecordBatch)
   at OpenTelemetry.Exporter.OtlpLogExporter.Export(Batch`1& logRecordBatch)
   at OpenTelemetry.BatchExportProcessor`1.ExporterProc()
   at System.Threading.Thread.StartCallback() in /builddir/build/BUILD/dotnet-9e8b04bbff820c93c142f99a507a46b976f5c14c/src/runtime.4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
```
It works with only Console-logger enabled.

## Cause

Debugging the issue I found that eventId parameter contains **Id: 0** and **Message: null** for a log entry when entering the Logger implementation ( https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/OpenTelemetryLogger.cs#L41 )

The log in question is **"Application started. Press Ctrl+C to shut down"**

![image](https://user-images.githubusercontent.com/2487368/152835588-88ff9865-2855-4573-bf4c-6064ceaadee4.png)

When that logEntry, a few seconds later, is send via the OTPL-expoter, it fails because of the Message-property being null (exception above).

## Additional Context

I think this bug might be introduced in this commit recently https://github.com/open-telemetry/opentelemetry-dotnet/commit/aad309b9445e19c437f05df150af92227e1b9eb3

It works with previous versions of the packages

 ```
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.2.0-rc1" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.2.0-rc1" />   
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.0.0-rc8" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc8" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc8" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc8" />
```

**Comment by cijothomas** [comment]
Thank for reporting the bug.
While this bug itself is small one with easy fix, this actually exposed something more serious - OTLP exporter (and likely other exporters), are not catching Exceptions in Exporter method, and this can cause app to crash (as in this issue.)

Related issue: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1627

Immediate action item: Review all official exporters shipped from this repo to make sure they don't throw from .Export.
