### ISSUE TITLE
OTLPLogExporter tests

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2873]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2871 - A very basic test is added here. Opening an issue to track adding more tests to OTLP Log Exporter. The exporter itself is not fully ready and is tracked here - https://github.com/open-telemetry/opentelemetry-dotnet/issues/2482

**Comment by dbgoytia** [comment]
Hi @cijothomas! I'd like to contribute to this repo. Do you know if this is still active? I'm new to the codebase but pretty excited to get started!

**Comment by cijothomas** [comment]
Yes! This issue is still open. You can start by looking at the existing tests and identify gaps. The issue description has a link to PR adding basic tests.

**Comment by moonbox3** [comment]
Hi @dbgoytia and @cijothomas. I am wondering if this issue is still open and needing help? Please let me know. Thanks.

**Comment by cijothomas** [comment]
@moonbox3 This is still open! Sorry for getting back very late.

**Comment by mfogliatto** [comment]
@cijothomas I see that additional unit tests were added since you first introduced `OtlpLogExporterTests` in #2871. In fact, the "TODO" comment no longer exists and seems there are unit tests asserting all `Attributes`, `Severity`, `TraceId` and `SpanId`.

Do you think there's still any case missing that I could add?

**Comment by cijothomas** [comment]
Scopes are missing from the tests. It may no longer be a "good first issue" to add coverage for that, as testing Scopes might be non-trivial. Do you want to explore?

**Comment by mfogliatto** [comment]
> Scopes are missing from the tests. It may no longer be a "good first issue" to add coverage for that, as testing Scopes might be non-trivial. Do you want to explore?

Sure sounds good! I'll give it a try. In the meantime I have introduced in the PR above some basic tests to increase code coverage in a related class.

**Comment by cijothomas** [comment]
Reopening as Scopes are not yet part of the tests
