### ISSUE TITLE
Make some fields in `LogRecord` mutable for consistency with `Activity`.

### ISSUE THREAD

**Issue by Yun-Ting** [open-telemetry/opentelemetry-dotnet#2877]
# Feature Request
Currently, in `Activity`, there are methods that allowed users to modify the fields. For example: `public Activity SetTag(string key, object? value)`.

I'm proposing to introduce methods that allow some fields in `LogRecord` to be mutable - for better consistency with `Activity`. Also, with this, use cases like redaction or fault-injection in Processor or Exporter could be achieved.

**Describe the solution you'd like:**

Introduce setter methods to `FormattedMessage`, `State`, and `StateValues`.
```
OpenTelemetry.Logs.LogRecord.SetFormattedMessage(string formattedMessage) -> void
OpenTelemetry.Logs.LogRecord.SetState(object state) -> void
OpenTelemetry.Logs.LogRecord.SetStateValues(System.Collections.Generic.IReadOnlyList<System.Collections.Generic.KeyValuePair<string, object>> stateValues) -> void
```

**Describe alternatives you've considered.**

Making the constructor public to provide users the ability to copy/update fields of their liking. 
I think the public setters solution above has better encapsulation based on the OOP principles.
And for use cases like redaction or fault-injection, initialization is not mandatory for modifying a `LogRecord`.

**Comment by dpk83** [comment]
+1 to this ask. We have a similar requirement where we are able to perform redaction for traces because Activity supports mutability but same isn't possible with logs.

**Comment by noblejacob-kubra** [comment]
**+1** to this ask. 
Similar to this we have a requirement to do custom scrubbing in logs to mask or remove sensitive information.
But was not able to implement because of having no provision to update the State/ StateValues/ FormattedMessage.
Can we add this feature so that it will be consistent with Activity.
