### ISSUE TITLE
Provide a way to use AddRedisInstrumentations without exceptions

### ISSUE THREAD

**Issue by ImoutoChan** [open-telemetry/opentelemetry-dotnet#2883]
# Feature Request

[AddRedisInstrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/blob/b1d57e9b0e0eec31767c2e28cc524ebdb9573f3d/src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs#L65)

I would like to have an option to not throw here.

**Is your feature request related to a problem?**

I'm configuring instrumentations for many services and some of them wouldn't have Redis. Unfortunately, right now AddRedisInstrumentation throws if my service doesn't have configured Redis. 

Other instrumentation libraries don't throw when a service doesn't have its sources. Look at SqlClient or Http, for example.

**Describe the solution you'd like:**

I think we can add an option to StackExchangeRedisCallsInstrumentationOptions class. When the option is set the behaviour should be like this:

```csharp
return deferredTracerProviderBuilder.Configure((sp, builder) =>
{
    if (connection == null)
    {
        connection = (IConnectionMultiplexer)sp.GetService(typeof(IConnectionMultiplexer));
        if (connection == null )
        {
            return;
        }
    }

    AddRedisInstrumentation(
        builder,
        connection,
        sp.GetOptions<StackExchangeRedisCallsInstrumentationOptions>(),
        configure);
});
```

**Describe alternatives you've considered.**

We can not throw at all to be consistent with other instrumentation libraries.

## Additional Context

The current workaround is to copy the entire redis instrumentation library and some other internal classes and modify this behavior. StackExchangeRedisCallsInstrumentation is internal so I can't just write my own TracerProviderBuilder extensions.

**Comment by niemyjski** [comment]
I just upgraded to 1.5 and ran across this.

```System.ArgumentNullException: Must not be null (Parameter 'connection')\n   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.AddRedisInstrumentation(TracerProviderBuilder builder, IConnectionMultiplexer connection, Action`1 configure)\n   at OpenTelemetry.ApmExtensions.<>c__DisplayClass0_0.<AddApm>b__2(TracerProviderBuilder b) ```

**Comment by niemyjski** [comment]
I solved it, had to do with new extensions that were introduced which changed setting name to null to connection.

**Comment by Kielek** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md#100-rc99 and newer.
