### ISSUE TITLE
OtlpLogExporter should set SeverityNumber from LogLevel value

### ISSUE THREAD

**Issue by paulturner-pg** [open-telemetry/opentelemetry-dotnet#2888]
# Feature Request

**Is your feature request related to a problem?**

Currently, when viewing exported logs, I can see there is no `SeverityNumber` specified, only a `SeverityText` (which is seemingly not respected by the NewRelic importer).

**Describe the solution you'd like:**

Based on the documentation regarding [Mapping of SeverityNumber](https://opentelemetry.io/docs/reference/specification/logs/data-model/#mapping-of-severitynumber) this should be an easy value to map and include in the logged attributes.

The mapping of the public `LogRecord` type to the internal type appears to be performed in `LogRecordExtensions` and there is even [a comment regarding this behaviour](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7ce2e4ca2308e7805c54181e61458de24c0c7907/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/LogRecordExtensions.cs#L69).

**Describe alternatives you've considered.**

I've looked at adding this myself, but there is currently no extension point for the attributes of a log record (such as using a processor).

**Comment by cijothomas** [comment]
Closing in favor of the parent item, which is updated to include this.
