### ISSUE TITLE
MeterProvider and dependency injection

### ISSUE THREAD

**Issue by exelsior** [open-telemetry/opentelemetry-dotnet#2895]
Hello.
I just started my immersion into the wonderful world of OpenTelemetry, so, sorry for dumb question.
I tried to add OTMetrics to Programm.cs by this:
`builder.Services.AddOpenTelemetryMetrics(builder =>
    {
        builder.AddHttpClientInstrumentation();
        builder.AddAspNetCoreInstrumentation();
        builder.AddMeter("MyApplicationMetrics");
        builder.AddOtlpExporter(options => options.Endpoint = new Uri("http://localhost:4317"));
    });`
I can get MeterProvider from DI in my other class, but i can't get from provider Meter instance. MeterProvider doesn't have GetMeter method.
Is that possible to get MeterInstance from di or i should create new meter every time? I want single entry point for metrics in my application.

**Comment by cijothomas** [comment]
Can i get this meter from di in different class?
-You need to add it to DI yourself. The `AddOpenTelemetryMetrics` doesn't add anything but the provider to DI.

You'd typically create one Meter, and create as many instruments as you want **at the beginning** of the application, and re-use it throughtout the application.

**Comment by exelsior** [comment]
I guess, i got it. I guess. i'll try again to add it to DI, but when i tried first time it couldn't resolve. Thank you for your answers. Stay safe=)
