### ISSUE TITLE
Propagator.Extract not fetching the baggage

### ISSUE THREAD

**Issue by RohitRanjanMS** [open-telemetry/opentelemetry-dotnet#2898]
Hi,

I am trying to fetch baggage from the headers using Propagator.Extract. I do get the traceParent but the parentContext.Baggage is empty. I am using RabbitMQ and I am including the baggage before posting the message. I can see the baggage in the header as well, attached screeshot.

This is the sample that I am refering to https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/MicroserviceExample/Utils/Messaging/MessageReceiver.cs#:~:text=Baggage.Current%20%3D%20parentContext.Baggage%3B

<img width="547" alt="image" src="https://user-images.githubusercontent.com/90008725/153984711-577fedcc-42ce-4784-9bb4-daa653ac8957.png">

I am expecting the baggage to be passed over to the worker service.
This is how I am setting the baggage in the MessageSender:
Baggage.SetBaggage("OtelBaggage", "OTelBaggageValue");

**Comment by RohitRanjanMS** [comment]
@utpilla @cijothomas FYI

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#troubleshooting Please use this guide and see if SDK/other components hit any internal exceptions.

We'll need to see a minimal repro app to confirm if this is a bug, or simply incorrect usage in the examples.
