### ISSUE TITLE
[Prometheus] expose prometheus with auth 

### ISSUE THREAD

**Issue by steinarox** [open-telemetry/opentelemetry-dotnet#2899]
# Feature Request
**Is your feature request related to a problem?**

Exposing Metrics is not desirable in most cases. If Prometheus is hosted on another machine it would be nice to support authentication in the metrics endpoint. Prometheus supports scraping with basic auth, tls certs or oauth https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

**Describe the solution you'd like:**

Adding one or more of the authentication modes when exposing the metrics endpoint would make it safe to expose the metrics where the Prometheus instance is hosted elsewhere

similar issues:
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2504 (otel basic aut)
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2009 (otel cert auth)

**Comment by tillig** [comment]
Related: #2776
