### ISSUE TITLE
Disallow `LogRecord` options to be updated after initialization.

### ISSUE THREAD

**Issue by Yun-Ting** [open-telemetry/opentelemetry-dotnet#2902]
# Bug Report
Currently, the SDK allows `LogRecord` options to be changed after the object was being built by the LoggerFactory.
This could introduce unnecessary complexity toward different states (before/after options got updated) and making it harder to maintain.

Discussion: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2891#discussion_r805084530

**What is the expected behavior?**
Remove existing test code on changing the `LogRecord` options after the object was being built by the LoggerFactory in `LogRecordTest.cs and `OtlpLogExporterTests.cs`.

(To be discussed)
Explicitly disallow `LogRecord` options to be tweaked after instantiation.

**Comment by cijothomas** [comment]
I would treat it as a bug that current LoggingProvider respected changes after building the factory. We need to "snapshot" the options, and not respect changes done after that. Only exception is adding processors, which is a documented/supported feature for traces, and we share same pipeline for logs as well, so need to keep it that for consistency.

**Comment by cijothomas** [comment]
> I would treat it as a bug that current LoggingProvider respected changes after building the factory. We need to "snapshot" the options, and not respect changes done after that. Only exception is adding processors, which is a documented/supported feature for traces, and we share same pipeline for logs as well, so need to keep it that for consistency.

^Correction to above. As of today, there is no ability to add processors after building the factory. This is different from tracing.
