### ISSUE TITLE
SetResourceBuilder is overly restrictive, no way to cooperatively initialize Resources

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-dotnet#2909]
# Feature Request

## Problem

When initializing a TracerProviderBuilder, some instrumentations might want to add resources (e.g. by interpreting environment variables), e.g. in their `AddFooInstrumentation(this TracerProviderBuilder builder)` method. Currently the only API for this is `SetResourceBuilder`, which *overwrites* all resources that might already exist.

## Proposed solution

One nice way would be an AddResourceBuilder API that merges the resources into existing ones. Another option would be to provide a GetResourceBuilder API on the TracerProviderBuilder.

## Alternatives considered (currently possible workarounds)

Currently, I can see two ways for any package to work around this:

1. Provide two separate functions for initialization. `AddFooInstrumentation(this TracerProviderBuilder builder)` which sets up everything *except* resources, and a separate `AddFooResources(this ResourceBuilder builder)` which adds *just* the resources. That makes initialization more complicated as now the user has to call two functions (four if you add the construction of ResourceBuilder and SetResourceBuilder which now the user also has to do themselves) instead of one. It works with multiple cooperating packages though.
2. Allow an additional Resource or ResourceBuilder to be passed as argument to the AddFooInstrumentation function. This is simple, but does not work across multiple packages that all want to add resources.

## Additional Context

Note that this is *not* about adding resources *after initialization*, but just to have a less awkward API to add resources from multiple sources during initialization to the TracerProviderBuilder.

**Comment by julealgon** [comment]
@cijothomas when will this change be released as a NuGet package update? When is 1.4.0 scheduled to come out?

I'm designing a set of extension methods and would like to have this particular API in place.
