### ISSUE TITLE
What should the default MetricReaderType be?

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#2921]
Can we settle on a universal default for `MetricReaderType` (manual vs. periodic), or should the default vary based on the type of exporter used (OTLP, Console, etc)? This question was [raised here](https://github.com/open-telemetry/opentelemetry-dotnet/pull/2717#discussion_r810253911).

#2717 moved the notion of `MetricReaderType` to the SDK for configuring whether to use the periodic metric reader or the "manual" one.

Currently, we do not have a universal default. For instance, when using the helper extension methods `AddConsoleExporter` and `AddOtlpExporter` the defaults are `MetricReaderType.Manual` and `MetricReaderType.Periodic`, respectively.

A [prior conversation](https://github.com/open-telemetry/opentelemetry-dotnet/pull/2648#discussion_r753697344) posed the question of whether the Console exporter should default to `MetricReaderType.Periodic`.

**Comment by cijothomas** [comment]
ConsoleExporter spec (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/stdout.md) says it is a [push metric exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#push-metric-exporter), which says it receives metrics from a paired [periodic exporting reader](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#periodic-exporting-metricreader), which says metrics are passed based on a user-configurable time interval, with default as 60,000msec... Same for OTLP too. 

Unless I mis understood the spec intent..

**Comment by cijothomas** [comment]
Closing, as there is no MetricReaderType anymore.
The defaults are covered by spec and being implemented in the SDK/Exporters.
