### ISSUE TITLE
Can .NET 6 Runtime Metrics Export Automatically? 

### ISSUE THREAD

**Issue by omamoo** [open-telemetry/opentelemetry-dotnet#2924]
# Question
.NET 6 Web Application, latest open telemetry NuGets.

**What are you trying to achieve?**
I'm trying to export .NET runtime metrics [System.Runtime](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs) to OTel collector, using the OpenTelemetry Protocol.

## Additional Context
Can you please assist with how should I export runtime metrics to open telemetry collector? As far as I understand I should listen to `System.Runtime` `EventSource`, but there is any extension method to the MeterProvider that will do it automatically? 

Like tracing when I can use `AddAspNetCoreInstrumentation`. 

Thanks.

**Comment by reyang** [comment]
Dup https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/204.
