### ISSUE TITLE
AddOpenTelemetryMetrics - Not returning all information

### ISSUE THREAD

**Issue by thecoolworld** [open-telemetry/opentelemetry-dotnet#2928]
Hello All,
I am new to Open Telemetry and am trying to use AddOpenTelemetryMetrics in my .Net core Service. I noticed that only the below attributes are returned. I would also need http.target & http.url so I can have those information too.. This will help in identifying the target and the URL. AddOpenTelemetryTracing gives this information my default. Is there anyway to get this information. Do you have plans to add this in future.

"attributes": [
{
"key": "http.flavor",
"value": {
"stringValue": "HTTP/2"
}
},
{
"key": "http.method",
"value": {
"stringValue": "GET"
}
},
{
"key": "http.scheme",
"value": {
"stringValue": "https"
}
},
{
"key": "http.status_code",
"value": {
"intValue": "302"
}
}
],

**Comment by cijothomas** [comment]
Closing old issue without activity. Reopen/open a new one, if this is still an issue with latest version of the packages.
