### ISSUE TITLE
Add Enrich to OnCustom in HttpInListener

### ISSUE THREAD

**Issue by Tornhoof** [open-telemetry/opentelemetry-dotnet#2948]
# Feature Request
All the main HttpInListener methods call the Enrich functor to add additional data to the activity, e.g. OnStartActivity, OnStopActivity, OnException. Only OnCustom does not. 
I suggest adding to:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/13e721d8fb6a89fb2e4072e97643394e55d6243f/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L244-L264

```csharp
try
{
    this.options.Enrich?.Invoke(activity, "OnCustom", payload);
}
catch (Exception ex)
{
    AspNetCoreInstrumentationEventSource.Log.EnrichmentException(ex);
}
```
This would allow adding more data from the payload, including additional information from the Action, e.g. other attributes or different routeData information.
Example: I use an extended version of the routing attributes to match incoming routes based on extra headers, similar to the concepts described in [5 levels of Hypermedia](http://byterot.blogspot.com/2012/12/5-levels-of-media-type-rest-csds.html) and the extra information would be useful as tag data.

**Comment by vishweshbankwar** [comment]
PR removes this event subscription: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5026
