### ISSUE TITLE
OTLP/HTTP does not use OTEL_EXPORTER_OTLP_ENDPOINT as a base URL correctly.

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-dotnet#2968]
# Bug Report

## Symptom

`OTEL_EXPORTER_OTLP_ENDPOINT` is not being treated as a base url in the OTLP HTTP exporter as [per the OTLP/HTTP spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp). Instead, the signal endpoint is being appended only if it is not already present. Method in question is [AppendPathIfNotPresent](https://github.com/open-telemetry/opentelemetry-dotnet/blob/778052f67f58b945be7c046bb57a8f3dc3be57c1/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs#L177).

**What is the expected behavior?**

No matter what `OTEL_EXPORTER_OTLP_ENDPOINT` is, the signal endpoint should be appended using slashes appropriately.  For example, if `OTEL_EXPORTER_OTLP_ENDPOINT` is `http://localhost:4318/v1/traces/`, then the resulting url should be `http://localhost:4318/v1/traces/v1/traces` for traces.

**What is the actual behavior?**

The signal endpoint is only appended if it is not already present.  For example, if `OTEL_EXPORTER_OTLP_ENDPOINT` is `http://localhost:4318/v1/traces/` the signal endpoint is not appended.  

## Reproduce

Set `OTEL_EXPORTER_OTLP_ENDPOINT` to be `http://localhost:4318/v1/traces/`.
Observer that traces are send to `http://localhost:4318/v1/traces` instead of  `http://localhost:4318/v1/traces/v1/traces`.

## Additional Context

I realize this is a pretty silly issue. Maybe the spec needs updated?  Definitely open that discussion.

**Comment by kedare** [comment]
+1 on this, this is quite critical, it's the only implementation I found that doesn't respect this specification.

**Comment by MeijerM1** [comment]
Is there any update on this? It seems like quite a big issue that the OTLP exporter is simply not respecting the spec when using OTLP/HTTP.
