### ISSUE TITLE
Metrics are no longer flushed automatically

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry-dotnet#2979]
# Bug Report

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.0.2`):

* `OpenTelemetry.Exporter.Console`: 1.2.0-rc3
* `OpenTelemetry.Exporter.InMemory`: 1.2.0-rc3
* `OpenTelemetry.Exporter.OpenTelemetryProtocol`: 1.2.0-rc3
* `OpenTelemetry.Extensions.Hosting`: 1.0.0-rc10

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc. You can
find this information from the `*.csproj` file):

* `net6.0`

## Symptom

**What is the expected behavior?**

Metrics being flushed automatically every 1 minute

**What is the actual behavior?**

Metrics were not being flushed and diagnostic logs don't provide any entries other than null.

However, as mitigation, I need to call `ForceFlush` to emit the metrics.

## Reproduce

When constructing a meter provider as following, it used to automatically flush metrics:
```csharp
var configuredMetricProvider = Sdk.CreateMeterProviderBuilder()
                .AddMeter("Example.*")
                .AddConsoleExporter()
                .AddOtlpExporter(options =>
                {
                    options.Endpoint = new Uri(collectorUri);
                })
                // We can only register global histogram buckets, not per histogram (for now)
                // See https://github.com/open-telemetry/opentelemetry-dotnet/issues/2755
                .AddView("*", new ExplicitBucketHistogramConfiguration { Boundaries = histogramBuckets })
                .Build();
```

**Comment by tomkerkhove** [comment]
Hm but this used to work. Is this an undocumented breaking change then?

**Comment by cijothomas** [comment]
> Hm but this used to work. Is this an undocumented breaking change then?

Yes agree.
Its "documented" in changelog https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md#120-rc3 , but not very obvious, and I think unintentional as well. @alanwest may be we could do a changelog update for now, warning about the breaking change to mitigate temporarily. (once the spec PR lands, we can do a quick follow-up by releasing rc4).

**Comment by tomkerkhove** [comment]
Thanks, I'll just wait for the new RC to show up then.

> @alanwest may be we could do a changelog update for now, warning about the breaking change to mitigate temporarily. (once the spec PR lands, we can do a quick follow-up by releasing rc4).

This would be super helpful indeed, thank you!
