### ISSUE TITLE
New NuGet package version scheme

### ISSUE THREAD

**Issue by bruno-garcia** [open-telemetry/opentelemetry-dotnet#298]
I'd like to propose a new versioning format for the `OpenTelemetry` NuGet packages.

Currently, IMHO there are a couple of problems, e.g:

![image](https://user-images.githubusercontent.com/1633368/67253615-92d79200-f446-11e9-9eed-b92728ea97bb.png)

1. Given the two versions we have out, it's a bit confusing which one is the latest. I understand it's  semver recommendation but right now we have two versions out, 5 and 40 which is a bit odd.
2. `0.0.0` as per SemVer is _initial development_ and the prefix is _pre-release_. I'd suggest we move over to _1.0.0-alpha/beta/preview_. Coincidentally [Jon Skeet wrote a blog](https://codeblog.jonskeet.uk/2019/10/20/why-i-dont-start-versions-at-0-x-any-more/) about this yesterday.
3. I don't believe we'll ever release `0.0.0` (without a prefix) which the NuGet client shows without the preview filter. So we'll anyway eventually jump from `0.0.0-beta` to `1.0.0-beta`.

I would suggest for the next releases moving to:

* 1.0.0-alpha01
* 1.0.0-beta01
* 1.0.0

We could also unlist the current two alphas to keep only only the consist versions listed.

**Comment by SergeyKanzhelev** [comment]
as discussed at the last SIG meeting, this proposal looks great. We also need to align (loosely) with the specification versioning. 

So if you can make it work - it will be great!

**Comment by bruno-garcia** [comment]
The library mentioned by Ludmila which controls the version is: [MinVer](https://github.com/adamralph/minver).

It's added here:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/0c3b1102d9ed3911a45566a9ffd6bfdfc69d4045/build/Common.prod.props#L5

The TLDR of the lib is:

It will version the package as the exact value of a git tag, if building a tag.
Otherwise it'll look up the git tree for the last tag, which in our case at this time is:
[0.2.0-alpha](https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/0.2.0-alpha).

From that it'll create the version. I guess the .40 was just because we had 40 commits to master in between versions.

The property used to control the pre-release _string_ is:
`<MinVerDefaultPreReleasePhase>`. By default it uses `alpha`. When the time comes to release a beta, we'd add:
`<MinVerDefaultPreReleasePhase>beta</MinVerDefaultPreReleasePhase>`.

I believe the ideal way to deal with this is to use **git tags to control the releases** and versions.

Adding a tag and pushing it would trigger the build resulting in artifacts versioned exactly like the tag name. Also, GitHub release can be created from the tag and the result NuGet packages can be uploaded to the GitHub release. That's a nice to have IMO, I hope no one download NuGet packages from GitHub :)

What about we could start pushing a tag: `1.0.0-alpha01` ?

**Comment by SergeyKanzhelev** [comment]
So what's the action item here? Create a tag `1.0.0-alpha01`?

**Comment by bruno-garcia** [comment]
@SergeyKanzhelev I would suggest that, yes.

**Comment by bruno-garcia** [comment]
I believe there's a lot going on already and this issue won't add that much value at this point.
Feel free to reopen if make sense.
