### ISSUE TITLE
Consider changing RC versioning pattern

### ISSUE THREAD

**Issue by glucaci** [open-telemetry/opentelemetry-dotnet#2991]
With the current versioning pattern in nuget.org is not listed the latest released package.

e.g.
`OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs`
- listed as latest: [1.0.0-rc9](https://www.nuget.org/packages/OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs/1.0.0-rc9)
- really latest: [1.0.0-rc10](https://www.nuget.org/packages/OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs/1.0.0-rc10)

![image](https://user-images.githubusercontent.com/13761704/157188992-2769ad15-98fc-47d3-9883-d80262670a15.png)

This can be fixed with the following pattern: `1.0.0-rc.10`
This is the same pattern already used for `beta` releases.

Thanks!

**Comment by tomkerkhove** [comment]
Bumped into this yesterday myself and agreed it would be nicer. VS also didn't consider `1.0.0-rc10` to be an update for `1.0.0-rc9`.

**Comment by cijothomas** [comment]
For the instrumentation packages, we can now start using 1.0.0-rc9.1,1.0.0-rc9.2,... etc.
1.0.0-rc10 can be unlisted from nuget as it'll be misleading.

**1.2 Release**
for core packages, we can continue with the current pattern for 1.2 release (i.e 1.2.0-rc1,...1.2.0-rc7 etc The 1.2 stable is coming soon and we dont anticipate rc count to hit 10).

**Post 1.2 Release**
for core packages, starting with 1.3, we can do 1.3.0-alpha.1, 1.3.0-beta.1, 1.3.0-beta.2, 1.3.0-rc.1, 1.3.0-rc.2, ...1.3.0-rc.11, ... 1.3.0

**Comment by cijothomas** [comment]
> For the instrumentation packages, we can now start using 1.0.0-rc9.1,1.0.0-rc9.2,... etc. 1.0.0-rc10 can be unlisted from nuget as it'll be misleading.
> 
> **1.2 Release** for core packages, we can continue with the current pattern for 1.2 release (i.e 1.2.0-rc1,...1.2.0-rc7 etc The 1.2 stable is coming soon and we dont anticipate rc count to hit 10).
> 
> **Post 1.2 Release** for core packages, starting with 1.3, we can do 1.3.0-alpha.1, 1.3.0-beta.1, 1.3.0-beta.2, 1.3.0-rc.1, 1.3.0-rc.2, ...1.3.0-rc.11, ... 1.3.0

This is done.
1.2.0-rc4 of core packages released.
1.0.0-rc9.1 of non core packages released.
1.0.0-rc10 of non packages unlisted from nuget.

Closing this issue - if any further issues, please open a new one.

**Comment by paule96** [comment]
@cijothomas this release looks a bit unstable. I get with the new packages in my `Programm.cs` the following error:
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/11291885/161404632-95c147da-0672-4e6c-9e5f-e9c17192881f.png">


It complains this on that lines:

```csharp
builder.Services.AddOpenTelemetryMetrics(builder =>
{
    builder.AddAspNetCoreInstrumentation();
    builder.AddHttpClientInstrumentation();
    builder.AddOtlpExporter(options =>
    {
        options.Endpoint = new Uri("http://otel-collector:4317");
    });
});
```

**Comment by glucaci** [comment]
There is no `1.9` or `1.9.1` version, it's only `1.0.0-rc9.1` for non-core packages and `1.2.0-rc4` for core packages.

Make sure that you update all the packages. Seams that is a version incompatibility.
`MetricReaderType` was removed in `1.2.0-rc4` https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/core-1.2.0-rc4
