### ISSUE TITLE
Allow modification of ActivityListener during program execution

### ISSUE THREAD

**Issue by pitming** [open-telemetry/opentelemetry-dotnet#2993]
# Feature Request

I would like to be able to change the listener in the Traceprovider. A little bit like when I change the loglevel of my application while it's running. for the moment, if I want to change this, I need to restart my program. Is this intended and why ?

**Is your feature request related to a problem?**
I would like to be able to enable/disable the instrumentation of the database while trying to monitor performance problem on my app.

**Describe the solution you'd like:**

If ActivityListener become a public property of TraceProvider, I could have it injected in a controller and allow some change on the trace detail with http api call

**Describe alternatives you've considered.**

I encapsulated all my activitySource.StartActivity in my own class where I have my own filters to return null instead of the activity. This class get's a TracingContext where I have some specific filter like enableDB, enableHttp, ... This is a singleton that is modified with a controller. But this seems over engeneering as I good directly modify the activitylistener instead if I wich to

## Additional Context

Add any other context about the feature request here.

**Comment by cijothomas** [comment]
> If ActivityListener become a public property of TraceProvider

This is an internal implementation detail of the provider and won't be exposed to public.

Samplers are the recommended solution, or you can run FilteringProcessor.(less efficient compared to sampling)

**Comment by pitming** [comment]
could you give me some info (links ?) on how to use the sampler ?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#sampler

**Comment by stevejgordon** [comment]
@cijothomas - I'm just going through some older issues and looking to help clean up. This looks to be asked and answered, so could it be closed?
