### ISSUE TITLE
Make metrics collection independent of tracing in instrumentation libraries

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#2994]
To emit `http.server.duration` metric,  ASP.NET Core and ASP.NET (with #2985 ) metrics instrumentation library makes use of `Activity.Duration` property of the activity created during each request. This creates a dependency between `metric` and `trace` signals which is undesirable as shutting down one signal should have no impact on other. 

Instead of relying on activity, we need some other mechanism to collect the required metrics. Opening this issue to discuss alternate solutions.

**Comment by pellared** [comment]
I see is as a bug. Here is an issue we got in auto-instrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1379

**Comment by vishweshbankwar** [comment]
> I see it as a bug. Here is an issue we got in auto-instrumentation: [open-telemetry/opentelemetry-dotnet-instrumentation#1379](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1379)

@pellared - For ASP.NET Core it is by design we rely on `activity.duration`. To get metric dimension values we need to subscribe to diagnostic source events which results in activity creation by ASP.NET Core library itself. It is not possible to prevent activity creation in this case even if we don't rely on `activity.duration`. 

ASP.NET is a separate issue and needs to be fixed.

**Comment by spanglerco** [comment]
Something else that's odd is that when both metrics and tracing is enabled for ASP.NET Core, the two refer to a different activity when reporting duration. The tracing part [creates its own activity](https://github.com/open-telemetry/opentelemetry-dotnet/blob/2e9a2042439d2403861a7a1d0f23700c9686e319/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L146) that "replaces" the HttpRequestIn activity created by ASP.NET Core. But the metrics part ends up using the original HttpRequestIn activity (via [Activity.Current](https://github.com/open-telemetry/opentelemetry-dotnet/blob/2e9a2042439d2403861a7a1d0f23700c9686e319/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs#L113)) to report the `http.server.duration` metric.

The result is that the metric that is supposed to represent the duration of requests and the duration of the span that represents a request have different values (with the metric being the larger of the two).

**Comment by cijothomas** [comment]
^ is true. However, it is only true when using a different propagator than W3C. So in the default case, its still the same activity.

**Comment by spanglerco** [comment]
Actually, that may be a separate issue. The default isn't `TraceContextPropagator` that [the code](https://github.com/open-telemetry/opentelemetry-dotnet/blob/2e9a2042439d2403861a7a1d0f23700c9686e319/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L133) is expecting, it's [a CompositeTextMapPropagator](https://github.com/open-telemetry/opentelemetry-dotnet/blob/9836d3addba4706e28624d59eb9da649470b0a82/src/OpenTelemetry/Sdk.cs#L34). I'm seeing the separate activities in a default configuration.

**Comment by cijothomas** [comment]
> Actually, that may be a separate issue. The default isn't `TraceContextPropagator` that [the code](https://github.com/open-telemetry/opentelemetry-dotnet/blob/2e9a2042439d2403861a7a1d0f23700c9686e319/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L133) is expecting, it's [a CompositeTextMapPropagator](https://github.com/open-telemetry/opentelemetry-dotnet/blob/9836d3addba4706e28624d59eb9da649470b0a82/src/OpenTelemetry/Sdk.cs#L34). I'm seeing the separate activities in a default configuration.

See https://github.com/open-telemetry/opentelemetry-dotnet/issues/1242#issuecomment-691697778

**Comment by vishweshbankwar** [comment]
> > See [#1242 (comment)](https://github.com/open-telemetry/opentelemetry-dotnet/issues/1242#issuecomment-691697778)
> 
> Thanks. I still see a second activity get created, but I think it's because I'm using ASP.NET Core 6.0. The TraceId of the HttpRequestIn activity is incorrect, so the instrumentation makes a new one. Specifically, [dotnet/aspnetcore#37471](https://github.com/dotnet/aspnetcore/issues/37471).

The issue should not impact instrumentation library. We do not enable the activity source listener for .NET6.0.

**Comment by vishweshbankwar** [comment]
This is taken care of .NET8.0 onwards. For lower versions, we will continue to rely on activity.
