### ISSUE TITLE
How to configure ILogger & OpenTelemetryLoggerProvider (Doc Proposal)

### ISSUE THREAD

**Issue by TimothyMothra** [open-telemetry/opentelemetry-dotnet#2999]
I'm seeing a documentation gap around configuration options for using OpenTelemetry with ILogger.
I'm volunteering to work on this (it's a great way to learn more about the SDK!) and I'm using this issue to identify the scope of what should be included in a "customizing-the-sdk" document and example project.

Document: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/customizing-the-sdk

## Scope

- Intro #3035
- Filtering #3034
   The class name or alias must be known to configure filtering.
    - via appinsights.json: uses the alias `OpenTelemetry`.
    - via code: AddFilter() uses the class name `OpenTelemetryLoggerProvider`
 - [OpenTelemetryLoggerOptions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/d7afc1bcb0092a56ac1ea55bfbcf5a9430c72cf9/src/OpenTelemetry/Logs/OpenTelemetryLoggerOptions.cs)
    - IncludeScopes #3155
    - IncludeFormattedMessage #3158
    - ParseStateValues #3169
    - AddProcessor #3042
    - SetResourceBuilder #3043

### Todo
- [ ] First PR introduced several TODOs. I expect each of these to be resolved before closing this issue.
- [x] Address additional comments from #3034

**Comment by cijothomas** [comment]
IncludeScopes
IncludeFormattedMessage
ParseStateValues
AddProcessor
SetResourceBuilder

^ all of above sounds good to be documented in the repo. You can look at tracing and metrics docs to get some idea on how to organize this.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#getting-started-with-tracing

https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk
