### ISSUE TITLE
Update EditorConfig for new language rules

### ISSUE THREAD

**Issue by tillig** [open-telemetry/opentelemetry-dotnet#3001]
# Feature Request

When working in VS Code, OmniSharp will show a lot of info messages based on the defaults for the latest language features.

<img width="725" alt="Example of OmniSharp analysis messages for style" src="https://user-images.githubusercontent.com/1156571/157487410-a88b31b7-0e0f-40e2-9438-aafcbbf1f5e0.png">

It is unclear whether the style for the project matches these or whether a PR would be accepted if they were cleaned up.

The primary missing rules appear to be:

- [IDE0017 `dotnet_style_object_initializer`](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0017) - use object initializers like `var x = new X { Foo = true }` instead of `var x = new X(); x.Foo = true;`
- [IDE0063 `csharp_prefer_simple_using_statement`](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0063) - prefer inline `using var x` over `using(...){...}`
- [IDE0071 `dotnet_style_prefer_simplified_interpolation`](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0071) - simplify/optimize string interpolation expressions
- [IDE0090 `csharp_style_implicit_object_creation_when_type_is_apparent`](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0090) - using target-typed `new()` style expressions

Just those four constitute about 250 or so info messages about style. Having them defined in `.editorconfig` would not only help folks adhere to the desired style of the project, it would make it easy to do a quick "fix all" and submit a PR to clean up all the style at once.

Note there are actually a lot of other things that might be valuable to define, too, like a [pattern matching preferences](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/pattern-matching-preferences). I have used the [`.editorconfig` in the `dotnet/runtime` repo](https://github.com/dotnet/runtime/blob/main/.editorconfig) in the past as a guide to the bajillion preferences you can supply. It's easier than [combing the documentation](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/categories).

**Is your feature request related to a problem?**

When developing in VS Code there is a lot of noise in the "Problems" window, particularly about potential style violations. Having the rules declared could help in guiding PRs to fix up the style issues so actual important problems won't be accidentally overlooked. It's hard to "separate the wheat from the chaff" in there right now.

**Describe the solution you'd like:**

I'd like to see the complete set of project preferences expressed in the .editorconfig, or at least the four largest/noisiest ones to start.

**Describe alternatives you've considered.**

You can filter out the view by errors/warnings/info in VS Code, and you already have to filter out `!**/AspNet/**` when on Mac to remove the .NET 4.6.1 analysis failures. However, more filtering means more opportunity to accidentally miss something that's actually a problem, so resolving the issues would be preferable.

**Comment by cijothomas** [comment]
Happy to accept PRs to include this in editorconfig. (Please do it one style at a time... to avoid large PRs.)

**Comment by tillig** [comment]
Do you have preferences around any of these?

My _personal_ preferences are basically the defaults - where all of these are set `true` to encourage some of the more recent things like target-typed `new()` sorts of things.

One PR at a time seems totally reasonable. It could get crazy otherwise.

**Comment by tillig** [comment]
It may also be interesting to update the order of the directives to match the `dotnet/runtime` one so it's easier to find/diff for new directives as they come up. They're already mostly grouped (though I do see `[*.cs]` is actually declared twice, so that could also get fixed.)
