### ISSUE TITLE
Package versions do not follow semantic versioning

### ISSUE THREAD

**Issue by ejsmith** [open-telemetry/opentelemetry-dotnet#3020]
`Identifiers with letters or hyphens are compared lexically in ASCII sort order` - https://semver.org/#spec-item-11

As shown in the screenshot, rc9 > rc10 which is obviously not what you want since rc10 is newer.

![image](https://user-images.githubusercontent.com/282584/157790387-e6f1433d-a8d8-4b70-a25f-f734018cb66a.png)

**Comment by jacostro** [comment]
This is true. To make precedence right, a dot is needed - 1.0.0-rc.9 precedes 1.0.0-rc.10.

**Comment by cijothomas** [comment]
Thanks for reporting this. We'll address this in the next release onwards.
Closing this as we are tracking it here : https://github.com/open-telemetry/opentelemetry-dotnet/issues/2991
