### ISSUE TITLE
[Docs] ResourceDetector should not be tied to tracing

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#3027]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#resource-detector
Resource is not a concept tied to tracing, but the doc is under the tracing section. The issue is opened to track moving Resource to its own section, and have trace/metric/logs link to it.

**Comment by cartermp** [comment]
Could this maybe be closed now that we have a dedicated resource doc here? https://opentelemetry.io/docs/instrumentation/net/resources/

Although the code sample does show tracing, it's not written in a way that ties it intrinsically to tracing.

**Comment by cijothomas** [comment]
Not really. This is specifically for the docs maintained in this repo.
(We haven't yet reached the desired state of having a single place for docs)
