### ISSUE TITLE
DB2 Database instrumentation support

### ISSUE THREAD

**Issue by venkatramanchandirasekaran** [open-telemetry/opentelemetry-dotnet#3070]
# Question
Does the Open Telemetry Dotnet SDK support any other databases other than SQL server ? . 

Looking at the SDK code there is only an instrumentation support for SQL Server via [OpenTelemetry.Instrumentation.SqlClient](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.SqlClient).  

If there is no support for DB2 at this time, are there plans to add support for DB2 and if so what are the timelines ?

**Comment by reyang** [comment]
Closing, please use https://github.com/open-telemetry/opentelemetry-dotnet/discussions.

**Comment by venkatramanchandirasekaran** [comment]
Thanks. I started a discussion about this https://github.com/open-telemetry/opentelemetry-dotnet/discussions/3165
