### ISSUE TITLE
Improve ASP.NET Core metrics instrumentation attribute compliance

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#3083]
Today our AspNetCore metrics instrumentation captures a small subset...

https://github.com/open-telemetry/opentelemetry-dotnet/blob/96b043e35fcf407147a9ad9c4fae2b6915f3a9ab/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs#L58-L61

...of the attributes defined in the [spec semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#attributes). Notably `http.target` (route template) and `http.host` are missing which are probably high-value/nice-to-have.

If anyone would like to take this on I am available to provide guidance.

Relates to #1269

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2994 related
