### ISSUE TITLE
PeriodicExportingMetricReader not exporting metrics

### ISSUE THREAD

**Issue by edenbd36** [open-telemetry/opentelemetry-dotnet#3096]
# Bug Report

Nugets:

```
        <PackageReference Include="OpenTelemetry" Version="1.2.0-rc3" />
        <PackageReference Include="OpenTelemetry.Api" Version="1.2.0-rc3" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.2.0-rc3" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.2.0-rc3" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9" />
```

Runtime version (e.g. `net461`, `net48`, `netcoreapp3.1`, `net5.0` etc :
`.NET 6`

## Symptom

Metrics are not exported unless I invoke MeterProvider.ForceFlush

**What is the expected behavior?**

Periodically export metrics

**What is the actual behavior?**

No metrics are exported

## Reproduce
Use Microsoft .NET6 WebApi template.
Program.cs:
```
builder.Services.AddOpenTelemetryMetrics(mBuilder =>
{
    mBuilder.AddMeter("MyService").SetResourceBuilder(ResourceBuilder.CreateDefault().AddAttributes(new[]
    {
        new KeyValuePair<string, object>("Environment", "Test")
    })).AddConsoleExporter().AddOtlpExporter((options, readOptions) =>
    {
        options.Protocol = OtlpExportProtocol.HttpProtobuf;
        options.Endpoint = new Uri("http://localhost:4318/v1/metrics");
        readOptions.MetricReaderType = MetricReaderType.Periodic;
        readOptions.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = 5000;
    });
});
```

Controller (used for testing):
```
        var c = new Meter("MyService").CreateCounter<int>("test_ot");

        c.Add(add, new []{ new KeyValuePair<string, object?>("Result", "Success")});
        //_meterProvider.ForceFlush(); 
        _logger.LogInformation("Dumped");
        return Ok();
```

## Additional Context

I have taken a look into [PeriodicExportingMetricReader](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Metrics/PeriodicExportingMetricReader.cs) and there is nothing that sets the `exportTrigger` AutoResetEvent which eventually should start the exporting process.
Am I missing something?

**Comment by bthharper** [comment]
I am seeing similar behaviour, the AspNetCore metrics are only exported when the app is closed.  

```csharp
b.AddOtlpExporter((otlpOptions, reader) => {
    otlpOptions.Endpoint = otlpEndpoint;
    otlpOptions.Protocol = OtlpExportProtocol.Grpc;

    reader.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = 1000;
});
```

**Comment by bthharper** [comment]
@edenbd36  - can you let me know what you did to fix this in your case?

**Comment by cijothomas** [comment]
Upgrade to latest version of all packages, and you should be good.

**Comment by bthharper** [comment]
@cijothomas  - thanks for the update.  

I assume the packages labelled rc10 aren't the latest but should be rc9.1?

**Comment by cijothomas** [comment]
> @cijothomas - thanks for the update.
> 
> I assume the packages labelled rc10 aren't the latest but should be rc9.1?

thats right. We fixed out issue with versioning, so you can now trust nuget to pick the latest correctly :)
