### ISSUE TITLE
Span.Kind: Unspecified -> Internal

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#31]
See https://github.com/open-telemetry/opentelemetry-java/blob/3cc0af53af6a50837cb4ffdc880ce56f837c8538/api/src/main/java/io/opentelemetry/trace/Span.java#L44

**Comment by trwegner** [comment]
Working on this

**Comment by SergeyKanzhelev** [comment]
closed via #36
