### ISSUE TITLE
Instrumentation Libraries to leverage Activity Status

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#3118]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/3112 As a follow up to this, we can now modify the instrumentation libraries to leverage the new Status field on Activity.

**Comment by Yun-Ting** [comment]
Migration on AspNetCore, Http, GrpcNetClient, ASP.NET and SqlClient were done.
