### ISSUE TITLE
Should I be able to get trace for functions started from service worker / not started from the controller thread?

### ISSUE THREAD

**Issue by qkhanhpro** [open-telemetry/opentelemetry-dotnet#3145]
# Question

My project is using a queue - dequeue system in which items are enqueued from controller and dequeued through an external library ( which I guess is using service worker )
I can see the traces from controller calling methods (enqueue) but not traces from the actual dequeue process. Should I be able to see all the traces? If not, is there any configuration I can try to support it? 

```
 services.AddOpenTelemetryTracing((builder) => builder
                .AddAspNetCoreInstrumentation()
                .AddJaegerExporter( c => { c.Endpoint = new System.Uri("http://...");
                c.Protocol = OpenTelemetry.Exporter.JaegerExportProtocol.HttpBinaryThrift;
                })
            );

```

**Comment by reyang** [comment]
Check this example https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/MicroserviceExample.

**Comment by reyang** [comment]
Closing, please use https://github.com/open-telemetry/opentelemetry-dotnet/discussions.
