### ISSUE TITLE
Stop supporting .NET 5 after 8th May 2022

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#3147]
.NET 5.0 will reach end of support on May 08, 2022.
https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/

Should we remove .NET 5.0 support?

**Comment by Oberon00** [comment]
I think it will still be supported e.g. in Azure Functions, won't it?

**Comment by cijothomas** [comment]
> I think it will still be supported e.g. in Azure Functions, won't it? https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=in-process%2Cv4&pivots=programming-language-csharp#languages

Azure follows different lifecycles I think. It should not affect this repo.

Regd. .NET5 - there aren't many .NET 5 specific code, so it'd be mostly removing test targets. (saves some CI time.).

**Comment by reyang** [comment]
> Azure follows different lifecycles I think. It should not affect this repo.

OpenTelemetry .NET lifecycle is not tight to any cloud providers / vendors. I think in general we try to align with .NET runtime. https://github.com/open-telemetry/opentelemetry-dotnet#supported-net-versions
