### ISSUE TITLE
B3 propagator is not case insensitive

### ISSUE THREAD

**Issue by purkhusid** [open-telemetry/opentelemetry-dotnet#3149]
# Bug Report
If you use the B3 propagator with e.g. the Grpc.Core instrumentation then it fails to connect the parent spans to the new server spans because gRPC headers are always lower case.

The issue is that the B3 propagator does not store the headers as lower case and then this line in the Grpc.Core instrumentation does not do case-insensitive comparison: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/f45edd73341c4ae35c417ffb98c23aabbc11081a/src/OpenTelemetry.Instrumentation.GrpcCore/ServerTracingInterceptor.cs#L166

There are two ways to fix this: 
* Fix this in the B3 propagator by also handling lower case variants of the headers
* Do a case-insensitive comparison in the Grpc.Core instrumentation

I wasn't sure which approach would be favoured here but I can implement the one that sounds good to the maintainers.

**Comment by notcool11** [comment]
eee, this seems like it would be an issue across the board. working on a Jaeger propagator and i've seen some clients encode the header so the `:` goes to `%3A`. sounds like i gotta strip the encoding AND do a `.ToLower()` to make things work. good catch!!

**Comment by xyq175com** [comment]
I can work this particular one if no one fix this.

**Comment by xyq175com** [comment]
The issue has been fixed, can you close this issue?
