### ISSUE TITLE
Auto flush activity processor.

### ISSUE THREAD

**Issue by rypdal** [open-telemetry/opentelemetry-dotnet#3166]
# Feature Request

Activity processor that flushes its containing [`ParentProvider`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/BaseProcessor.cs#L34) if an ended activity matches a predicate. `ParentProvider` should have [`TracerProvider`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Trace/TracerProvider.cs) type.

**Solution**

New class initialised with a predicate and derived from the [`BaseProcessor<Activity>`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/BaseProcessor.cs) that overrides the `OnEnd(Activity activity)` method that flushes (with timeout) [`ParentProvider`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/BaseProcessor.cs#L34) if the activity matches a predicate.

**Comment by reyang** [comment]
@rypdal this seems to be a nice-to-have thing for the contrib repo https://github.com/open-telemetry/opentelemetry-dotnet-contrib.

**Comment by rypdal** [comment]
> @rypdal this seems to be a nice-to-have thing for the contrib repo https://github.com/open-telemetry/opentelemetry-dotnet-contrib.

Yes, seems https://github.com/open-telemetry/opentelemetry-dotnet-contrib is more appropriate repository for this contribution. The new issue has been created: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/296. This issue can be closed.
