### ISSUE TITLE
trace need cookies

### ISSUE THREAD

**Issue by mahaisong** [open-telemetry/opentelemetry-dotnet#3185]
I used Opentelemetry Instrumentation. AspNetCore、 OpenTelemetry. Extensions. Hosting.

want to generate a trace that can contain **cookies.**

But the whole warehouse source code can't find cookies.

**Comment by cijothomas** [comment]
Please open a discussion thread, with more details and specific asks. It is not clear what exactly is the question here.

**Comment by mahaisong** [comment]
success //写入日志：Cookie 
                            activity.SetTag(HeaderNames.Cookie, JsonConvert.SerializeObject(httpRequest.Cookies));
