### ISSUE TITLE
(REQUEST) README: Identify lvl of back-compatibility, note incompatible changes from ancestor project

### ISSUE THREAD

**Issue by Dwood15** [open-telemetry/opentelemetry-dotnet#319]
As a user of the old opencensus project, I'm not sure whether the exported tracing is 100% compatible with your typical stackdriver (or other) tracing provider/exporting. 

If I do a ctrl + f on the readme, I don't find any mentions of opencensus or what degree or level of intent there is for back-compat.

I understand the prior project never left Alpha, and this is also alpha, and therefore offers no levels of guarantees for the SDK. I would at least enjoy a statement on the top of the readme addressing this, and indicating intent.

**Comment by SergeyKanzhelev** [comment]
I'm sorry, but we made a decision not to support a bridge from OpenCensus to OpenTelemetry in C# as OpenCensus SDK was in such an early alpha stage. You'd need to re-instrument your app. Sorry again
