### ISSUE TITLE
Rename OcAgent to something more natural for OpenTelemetry

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#32]
Rename this project:
https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Exporter.Ocagent

Into something like `OpenTelemetry.Exporter.Grpc`. Maybe an alternative can be `OpenTelemetry.Exporter.OpenTelemetryService` or `OpenTelemetry.Exporter.OpenTelemetryExporter`

**Comment by lmolkova** [comment]
Ocagent exporter was removed. Closing and tracking ot agent support in #19
