### ISSUE TITLE
Manual Instrumentation not working without needing to add AspnetCoreInstrumentation

### ISSUE THREAD

**Issue by evhfla** [open-telemetry/opentelemetry-dotnet#3210]
# Bug Report

OpenTelemetry 1.2.0
OpenTelemetry.Exporter.Jaeger (1.2.0)
OpenTelemetry.Extensions.Hosting (1.0.0-rc9.2)
OpenTelemetry.Instrumentation.Http (1.0.0-rc9.2)

.net 5
Kubernetes v1.22.4

## Symptom

No Trace data is being sent to Jaeger if AddAspNetCoreInstrumentation is not added.  My desire is to only to do manual instrumentation.  Both Jaeger and the dotnet application are running in a Kubernetes Cluster.

## Reproduce

Startup
 services.AddOpenTelemetryTracing(b =>
            {
                b
                .AddHttpClientInstrumentation()
                .AddSource(TelemetryConstants.ServiceName)
                .SetResourceBuilder(
                    ResourceBuilder.CreateDefault()
                        .AddService(serviceName: TelemetryConstants.ServiceName, serviceVersion: TelemetryConstants.ServiceVersion))
                .AddJaegerExporter(o =>
                {
                    o.Endpoint = new Uri(Environment.GetEnvironmentVariable("TelemetryConfiguration_JaegerEndpoint"));
                    o.ExportProcessorType = ExportProcessorType.Simple;
                    o.Protocol = JaegerExportProtocol.HttpBinaryThrift;
                });
            });

**Comment by cijothomas** [comment]
Without seeing a minimal repro application, its hard to say what might be wrong.
Few possibilities:
1. No Sampler is set, so the default is applied, and it might be dropping activities.
2. Make sure the ActivitySource used to create Activity, matches the one added using `AddSource`.

I'd suggest to use ConsoleExporter for verification purposes, instead of Jaeger, to quickly isolate the issue further.

**Comment by evhfla** [comment]
Can you please elaborate what do you mean by no sampler is set?  By the way to be clear, once I add the .AspnetCoreInstrumetration to the startup configuration.  I see both the Automated and manual instrumentations in Jaeger.  Adding the ConsoleExporter now to see if that is working properly when looking a the logs for my service in Kubernetes.

Lastly, it should not matter that I am using the collector endpoint (ie. http://colector-endpoint:14268/api/traces) instead of agent and host correct?

**Comment by evhfla** [comment]
Thank you....so that is required?  Wouldn't that default to 1 (i.e. 100%) if no sampler is set?

**Comment by cijothomas** [comment]
I think this is same as https://github.com/open-telemetry/opentelemetry-dotnet/issues/1217

**Comment by evhfla** [comment]
That looks to be the same issue indeed.  Let me see if adding the sample will fix it.

**Comment by evhfla** [comment]
Would this be correct or do I need to switch all the way to use the SDK?

` using var tracerProvider = Sdk.CreateTracerProviderBuilder()
            .SetSampler(new TraceIdRatioBasedSampler(1))
            .Build();

            // Added Jaeger Tracing
            services.AddOpenTelemetryTracing(b =>
            {
                b.AddConsoleExporter()
                .AddHttpClientInstrumentation()
                .AddSource(TelemetryConstants.ServiceName)
                .SetResourceBuilder(
                    ResourceBuilder.CreateDefault()
                        .AddService(serviceName: TelemetryConstants.ServiceName, serviceVersion: TelemetryConstants.ServiceVersion))
                .AddJaegerExporter(o =>
                {
                    o.Endpoint = new Uri(Environment.GetEnvironmentVariable("TelemetryConfiguration_JaegerEndpoint"));
                    o.ExportProcessorType = ExportProcessorType.Simple;
                    o.Protocol = JaegerExportProtocol.HttpBinaryThrift;
                });
            });`

**Comment by evhfla** [comment]
Got it working. Thanks a million for your help!

**Comment by cijothomas** [comment]
Closing as duplicate.

Could you post the final version of code snippet you have, to help future readers.

**Comment by evhfla** [comment]
Working Code as requested:
` services.AddOpenTelemetryTracing(b =>
            {
                b.AddConsoleExporter()
                .SetSampler(new TraceIdRatioBasedSampler(1.00))
                .AddHttpClientInstrumentation()
                .AddSource(TelemetryConstants.ServiceName)
                .SetResourceBuilder(
                    ResourceBuilder.CreateDefault()
                        .AddService(serviceName: TelemetryConstants.ServiceName, serviceVersion: TelemetryConstants.ServiceVersion))
                .AddJaegerExporter(o =>
                {
                    o.Endpoint = new Uri(Environment.GetEnvironmentVariable("TelemetryConfiguration_JaegerEndpoint"));
                    o.ExportProcessorType = ExportProcessorType.Simple;
                    o.Protocol = JaegerExportProtocol.HttpBinaryThrift;
                });
            });`
