### ISSUE TITLE
`process.command_args` serializes as `System.String[]`

### ISSUE THREAD

**Issue by tillig** [open-telemetry/opentelemetry-dotnet#3229]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

- OpenTelemetry.Exporter.Console: 1.3.0-beta.1
- OpenTelemetry.Exporter.Jaeger: 1.3.0-beta.1
- OpenTelemetry.Exporter.OpenTelemetryProtocol: 1.3.0-beta.1
- OpenTelemetry.Exporter.Prometheus: 1.3.0-beta.1
- OpenTelemetry.Extensions.Hosting: 1.0.0-rc9.3
- OpenTelemetry.Instrumentation.AspNetCore: 1.0.0-rc9.3
- OpenTelemetry.Instrumentation.Http: 1.0.0-rc9.3

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net6.0

## Symptom

I'm adding the `process.command_args` metadata to a trace resource and when it is serialized to a trace span it appears as `System.String[]` instead of the actual array of values. I see this in both the Console exporter as well as using OpenTelemetry Collector.

**What is the expected behavior?**

I expect the array of arguments to be kept as an array of strings [as defined in the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/process.md#process).

**What is the actual behavior?**

The value is rendered like `.ToString()` was called on the array, so it's `System.String[]` instead of the values.

## Reproduce

Create a resource detector like this:

```c#
using System.Runtime.InteropServices;
using OpenTelemetry.Resources;

namespace MyNamespace;

public class RuntimeResourceDetector : IResourceDetector
{
    public Resource Detect()
    {
        var process = Process.GetCurrentProcess();
        var filename = process.MainModule.FileName;

        // Command line args requires the executable per OpenTelemetry spec.
        var arguments = Environment.GetCommandLineArgs().Prepend(filename).ToArray();
        var resourceData = new Dictionary<string, object>()
        {
          { OpenTelemetrySemanticResourceKey.ProcessCommandArgs, arguments }
        };

        return new Resource(resourceData);
    }
}
```

Add that to your resource when you wire up trace.

```c#
var resourceBuilder = ResourceBuilder
  .CreateEmpty()
  .Add(new RuntimeResourceDetector());
services.AddOpenTelemetryTracing(builder =>
  builder
    .SetResourceBuilder(resourceBuilder)
    .AddConsoleExporter());
```

Detection runs totally fine, and if you debug it, you can see that the proper array of arguments is getting added to the resource. However, when it serializes, you'll see...

```text
Resource associated with Activity:
    process.command_args: System.String[]
```

## Additional Context

I noticed a similar issue about array serialization but it was for span attributes, not resource attributes. I _think_ this is happening [in this `ToOtlpAttribute()` method](https://github.com/open-telemetry/opentelemetry-dotnet/blob/660ed691c5043f0c3b91c2d8a5972595a06f2fe2/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs#L205), at least for the OpenTelemetry exporter, but I haven't really figured out how it's happening for the console exporter yet. Admittedly I haven't super dug in; I just noticed it and was puzzled.

**Comment by cijothomas** [comment]
Digging up an old, but I think related to this https://github.com/open-telemetry/opentelemetry-dotnet/pull/1973

**Comment by alanwest** [comment]
Hmm, this is probably not completely resolved yet, so reopening... I think the Console exporter requires a little work - should be easy, I'll take a look. Will look at Prometheus too.
