### ISSUE TITLE
What exactly do I need for collecting and exporting traces to Azure Application Insights?

### ISSUE THREAD

**Issue by verdysh** [open-telemetry/opentelemetry-dotnet#3234]
I have asp .net core app built on .NET 6.

I want to have traces in Application insights. Currently this view is enough for me: https://ibb.co/k1D1z0W  . I see there http and sql calls. 

Start version of my app which shown to me traces as above was the next:

```
builder.Services.AddOpenTelemetryTracing(builder =>
{
    builder.AddConsoleExporter();
    builder.AddAspNetCoreInstrumentation();
    builder.AddHttpClientInstrumentation();
    builder.AddEntityFrameworkCoreInstrumentation(opt => 
    {
        opt.SetDbStatementForText = true;
    });
    builder.AddSqlClientInstrumentation(opt =>
    {
        opt.SetDbStatementForText = true;
    });
});

builder.Services.AddApplicationInsightsTelemetry();
```

Then I tried to figure out what doing every line of code. I ended up removing whole call builder.Services.AddOpenTelemetryTracing(...) and leave just call to builder.Services.AddApplicationInsightsTelemetry().

As a result I have exactly the same traces in Application Insights. I see the same total results in "Transaction search" and the same view in "End-to-end transaction details" both with and without call to AddOpenTelemetryTracing(...).

My questions are what do calls to:
1. builder.Services.AddOpenTelemetryTracing(...)
2. builder.AddAspNetCoreInstrumentation()
3. builder.AddHttpClientInstrumentation()
4. builder.AddEntityFrameworkCoreInstrumentation()
5. builder.AddSqlClientInstrumentation()

**Comment by reyang** [comment]
@verdysh there are two ways and you need to pick one (not two):

1. Use ApplicationInsights .NET SDK - follow this document https://docs.microsoft.com/azure/azure-monitor/app/asp-net-core. This is recommended for production use, before the OpenTelemetry .NET path is reaching GA.
2. Use OpenTelemetry .NET - follow this document https://docs.microsoft.com/azure/azure-monitor/app/opentelemetry-enable?tabs=net, be aware that the exporter is still in preview so I won't suggest that you use it in production.

From the example you provided, it seems you ended up mixing them up.

Closing the issue, if you have questions, please follow the instructions and use Discussions instead.
