### ISSUE TITLE
When bumping from 1.2.0-rc1 to 1.2.0 Activity becomes null

### ISSUE THREAD

**Issue by 3schwartz** [open-telemetry/opentelemetry-dotnet#3254]
# Bug Report

Hi

When bumping `OpenTelemetry.Exporter.Jaeger` from `1.2.0-rc1` to `1.2.0` the Activity becomes null, when wrapped into a docker file and deployed. Locally it works. When changing back to `1.2.0-rc1` everything works.

Other telemetry libraries

    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc8" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc8" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc8" />

Docker image: `bitnami/aspnet-core:5.0.11-debian-10-r6`

Target framework `net5.0`.

**Comment by Kielek** [comment]
@3schwartz, I am making some cleanup with old issues. Closing this one.

Please reopen, if you are able to reproduce the problem with the latest versions. In addition, please provide [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
