### ISSUE TITLE
Better Dev Experience for UseOpenTelemetryPrometheusScrapingEndpoint() Extension Method

### ISSUE THREAD

**Issue by hannahchan** [open-telemetry/opentelemetry-dotnet#3267]
In the Prometheus exporter, the current `.UseOpenTelemetryPrometheusScrapingEndpoint()` extension method under the hood branches the middleware pipeline by using the `.Map()` and `.MapWhen()` methods. It may be more appropriate to rename this method to `.MapOpenTelemetryPrometheusScrapingEndpoint()` or just `MapPrometheusScrapingEndpoint()`.

In addition, it might better to update the signature of that method from;

```C#
public static IApplicationBuilder UseOpenTelemetryPrometheusScrapingEndpoint(this IApplicationBuilder app, string path)
```

to;

```C#
public static IEndpointConventionBuilder MapPrometheusScrapingEndpoint(this IEndpointRouteBuilder builder, string path)
```

These changes would make the extension method more consistent with other **_Endpoint Enabled_** middleware that branch the middleware pipeline such as the [ASP.NET Core HealthCheck middleware](https://docs.microsoft.com/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0) `.MapHealthChecks()` extension method or even the out of the box `.MapControllers()` method. Returning an `IEndpointConventionBuilder` would allow the caller to configure the endpoint further. For example;

```C#
app.MapPrometheusScrapingEndpoint("/metrics").RequireHost("*:9090");
```

I'm happy to make the changes myself and submit a PR if someone is willing to accept my contribution. As long as there is an agreement that this is important enough to get fixed.

**Comment by cijothomas** [comment]
tagging @CodeBlanch @tillig to get thoughts, who previously worked on improvements to Prometheus exporter.

**Comment by tillig** [comment]
My use case was basically that exact thing - `app.MapPrometheusScrapingEndpoint("/metrics").RequireHost("*:9090");` - but I also have something that's basically `app.MapHealthChecks("/healthz").RequireHost("*:9090");` and getting the two to work together in the previous incarnation of the extensions was challenging. The new ones have a lot of flexibility that fixed it up for me.

I noticed that, given the health checks example, it actually supports _both ways_:

- [Using IEndpointRouteBuilder](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HealthChecks/src/Builder/HealthCheckEndpointRouteBuilderExtensions.cs)
- [Using IApplicationBuilder](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HealthChecks/src/Builder/HealthCheckApplicationBuilderExtensions.cs)

I think if the extensions proposed could be additive, such that we could actually have it both ways - just like the health checks middleware - it'd be the best of both worlds.

**Comment by hannahchan** [comment]
This is literally the extension method I am thinking of adding. Before I do is there any concerns or anything else you think should be covered. This extensions is additive of course.

```C#
/// <summary>
/// Adds OpenTelemetry Prometheus scraping endpoint middleware to an
/// <see cref="IEndpointRouteBuilder"/> instance.
/// </summary>
/// <param name="endpoints">The <see cref="IEndpointRouteBuilder"/> to add
/// middleware to.</param>
/// <param name="path">Optional path to use for the branched pipeline.</param>
/// <param name="meterProvider">Optional <see cref="MeterProvider"/>
/// containing a <see cref="PrometheusExporter"/> otherwise the primary
/// SDK provider will be resolved using application services.</param>
/// <param name="configureBranchedPipeline">Optional callback to
/// configure the branched pipeline. Called before registration of the
/// Prometheus middleware.</param>
/// <returns>A convention routes for the Prometheus scraping endpoint.</returns>
public static IEndpointConventionBuilder MapPrometheusScrapingEndpoint(
    this IEndpointRouteBuilder endpoints,
    string path = null,
    MeterProvider meterProvider = null,
    Action<IApplicationBuilder> configureBranchedPipeline = null)
{
    var builder = endpoints.CreateApplicationBuilder();

    // Note: Order is important here. MeterProvider is accessed before
    // GetOptions<PrometheusExporterOptions> so that any changes made to
    // PrometheusExporterOptions in deferred AddPrometheusExporter
    // configure actions are reflected.
    meterProvider ??= builder.ApplicationServices.GetRequiredService<MeterProvider>();

    if (path == null)
    {
        var options = builder.ApplicationServices.GetOptions<PrometheusExporterOptions>();
        path = options.ScrapeEndpointPath ?? PrometheusExporterOptions.DefaultScrapeEndpointPath;
    }

    if (!path.StartsWith("/"))
    {
        path = $"/{path}";
    }

    configureBranchedPipeline?.Invoke(builder);

    builder.UseMiddleware<PrometheusExporterMiddleware>(meterProvider);

    return endpoints.Map(new PathString(path), builder.Build());
}
```

**Comment by CodeBlanch** [comment]
I'm good with adding this new extension if it will be helpful. I noticed when I was working on these extensions that [Prometheus .NET](https://github.com/prometheus-net/prometheus-net/blob/ff337560e66af5dd45070014d6e554febb599f16/Prometheus.AspNetCore/MetricServerMiddlewareExtensions.cs#L20-L41) also has a "Use" and a "Map" extension. We just weren't sure why and figured we could add it if anyone asked for it 🤣

**Comment by hannahchan** [comment]
Hi all,

Sorry for the delayed response. Life got busy. I've never contributed to this repo before but just opened a PR for my change. Please let me know if anything is missing. I'm keen to be a more regular contributor.

**Comment by Alexander-Bartosh** [comment]
This also fixes https://github.com/open-telemetry/opentelemetry-dotnet/issues/2869. Any chance this will be merged/released in the new future ? 
This is a blocker for all people who do not want to expose metric endpoints publicly and are using ASP .net core

**Comment by tillig** [comment]
@Alexander-Bartosh I'm on my mobile and on holiday, so maybe give it a shot yourself first. That's literally the exact use case I have, too, which is why it's there. Use the overload that takes a lambda, that's where you can map path and port. Put it before you put your authentication middleware so it will be anonymous. It's just like any other app.MapWhen sort of thing, there's no magic.

**Comment by tillig** [comment]
@Alexander-Bartosh Check out [comments line this one](https://github.com/open-telemetry/opentelemetry-dotnet/pull/3029#issuecomment-1072678222) from the PR that added the overloads - I think this will give you the idea.

**Comment by Alexander-Bartosh** [comment]
@tillig Thx. I was missing those methods because was using beta1 for some strange reason. 
After updating to Beta2 I see the method you have mentioned. 
Still I would prefer registering an endpoint instead of adding another Middleware to reach request.
