### ISSUE TITLE
Remote IP Address - NULL reference exception

### ISSUE THREAD

**Issue by barry-tormey-imprivata** [open-telemetry/opentelemetry-dotnet#3276]
# Bug Report

[OpenTelemetry.Instrumentation.AspNetCore](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore) - v1.0.0-rc9.3

Runtime version: `net6.0`

## Symptom

`NullReferernceException` thrown when `HttpContext.Connection.RemoteIpAddress` is `null` due to a `.toString()` call in [`HttpInListener.AddGrpcAttributes`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L361)

**What is the expected behavior?**

The `AttributeNetPeerIp` should not be added to the activity when the `RemoteIpAddress` property is NULL

**What is the actual behavior?**

Unhandled `NullReferenceException`

## Reproduce

See [RemoteIpAddress]( https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connectioninfo.remoteipaddress?view=aspnetcore-6.0) documentation indicating the property can be null.

**Comment by a602500** [comment]
I will work on this and submit PR later.

**Comment by nayang7** [comment]
> I will work on this and submit PR later.

I will work on this and submit PR later. Since I changed my account and deleted the before one.
