### ISSUE TITLE
Ability to enrich log with context data

### ISSUE THREAD

**Issue by Juniorlimaivd** [open-telemetry/opentelemetry-dotnet#3294]
Hi, I'm looking for a way to enrich log calls with context data (such as processId, threadId, fileName, etc). Ideally, i would like to be able to attach enrichers during logger initialization, similar to how it is done in Serilog https://github.com/serilog/serilog/wiki/Enrichment

**Comment by reyang** [comment]
For process ID, given it won't change during the process lifecycle, it might be better to model it as a Resource.

**Comment by CodeBlanch** [comment]
@Juniorlimaivd ASP.NET Core? Check out this [discussion](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/3275#discussioncomment-2741476). You can create middleware which opens a scope with the contextual information and then it will push onto your logs automatically if you have scopes turned on.

> Ideally, i would like to be able to attach enrichers during logger initialization, similar to how it is done in Serilog

I agree with this. The middleware/scope approach is a lot of code, kind of hard to do. I'm currently working on a proposal to bring to the ILogger team seeking to add support for a global registration mechanism on `ILoggingBuilder` 😄

**Comment by luizfbicalho** [comment]
Is there any movement in this area?

**Comment by evgenyfedorov2** [comment]
@Juniorlimaivd @luizfbicalho .NET provides it already, see 

- https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.diagnostics.enrichment.ilogenricher?view=net-9.0-pp
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.diagnostics.enrichment.istaticlogenricher?view=net-9.0-pp
- https://andrewlock.net/customising-the-new-telemetry-logging-source-generator/#adding-properties-to-all-logs-using-enrichment

Is this what you have been looking for?
