### ISSUE TITLE
Ability to set a maximum attribute length

### ISSUE THREAD

**Issue by ejsmith** [open-telemetry/opentelemetry-dotnet#3297]
# Feature Request

NewRelic limits their attribute length to 4096 characters and if an attribute is larger than that, it will drop the data. It would be nice to have an option in the client that truncates any attribute values that are longer than a given size.

**Comment by alanwest** [comment]
@ejsmith I'll be working on a solution to this soon.

I started some work in #3231 experimenting with doing truncation in the shim API. I also proposed it in the .NET activity API (https://github.com/dotnet/runtime/issues/68528), but at this time there's a desire to solve this in the SDK. Specifically in exporters per this comment https://github.com/open-telemetry/opentelemetry-dotnet/pull/3231#issuecomment-1110076892.

I've been wrapping up some work to handle attributes uniformly across all exporters and intend to circle back and address these length limits.

**Comment by AlexandruRus23** [comment]
@alanwest 

Sorry to highjack this. I would need this functionality, but I'm still targeting .net 6 and it seems like this is only included in 1.4.1-beta that ultimately references system.diagnostics 7.0 preview. Is there any chance this will get included in a stable package of the exporter, like 1.3.2 or similar?

Thanks!

**Comment by pellared** [comment]
@alanwest Sorry to comment on a closed issue but I just want to double-check before opening an issue. Are the attribute limits supported for metrics?

**Comment by pellared** [comment]
I created https://github.com/open-telemetry/opentelemetry-dotnet/issues/3949

**Comment by alanwest** [comment]
> Am I correct that it is working only for OTLP exporter and it is not documented?

@pellared The attribute limit configuration is supported by all the exporters provided by this repo: OTLP (traces and logs), Jaeger, and Zipkin. Metric and resource attributes are not subject to the limits per the spec.
