### ISSUE TITLE
When will the OTLP Exporter become stable for logs?

### ISSUE THREAD

**Issue by jan-nemo** [open-telemetry/opentelemetry-dotnet#3331]
Hello!

Are there any plans in the near future to make the OTLP Exporter for logs stable and add it to the `OpenTelemetry.Exporter.OpenTelemetryProtocol` project?
I'm asking this because [OTLP log data model](https://github.com/open-telemetry/opentelemetry-proto#maturity-level) seems to be stable right now. Please correct me if I'm wrong.

**Comment by cijothomas** [comment]
No firm dates for the stable release yet. But its definitely in the near future - i.e in year 2022 itself.
There are active issues that needs to be addressed before we can stable release the OTLP Log Exporter.

**Comment by jan-nemo** [comment]
Thanks for your reply!
