### ISSUE TITLE
Pass API-Key in code, instead of collector.yaml

### ISSUE THREAD

**Issue by netDeveloper3** [open-telemetry/opentelemetry-dotnet#3343]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).

Hi, following the tutorial in [Trace your .NET Lambda functions with New Relic and OpenTelemetry](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/opentelemetry/lambda-opentelemetry-dotnet/#instrument) we're setting up the New Relic api-key in collector.yaml and it's working fine. 
The issue is that our New Relic key is shared between test and prod environment and we would like to decrypt the key and pass the value through code. 

In the code we're passing the api-key like (it just reads from env variable for testing now):

```
         TracerProvider = Sdk.CreateTracerProviderBuilder()
                    .AddAWSInstrumentation()
                    .AddOtlpExporter(options => options.Headers = $"api-key={Environment.GetEnvironmentVariable("NR_LICENSE_KEY")}")
                    .AddAWSLambdaConfigurations()
                    .Build()
```

But this results in: 
`Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "name": "otlp", "error": "Permanent error: rpc error: code = Internal desc = unexpected HTTP status code received from server: 400 (Bad Request)", "dropped_items": 1}", `

**Comment by cijothomas** [comment]
Closing as this is not something owned by this repo. (I'd recommend asking NewRelic/Lamba repos)
