### ISSUE TITLE
OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs no stable version

### ISSUE THREAD

**Issue by glucaci** [open-telemetry/opentelemetry-dotnet#3348]
Seams that `OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs` has no 1.3.0 nuget package

https://www.nuget.org/packages/OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs

![image](https://user-images.githubusercontent.com/13761704/172407814-d65a54b0-30ff-4c7a-90c9-89451e9efe85.png)

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol#otlp-logs

Log Exporter is not yet ready for stable. Some active work is going on which would be another step towards stabilizing them. no firm ETA today.
