### ISSUE TITLE
Confusion around collector name

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#335]
[Collector](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md#collector) according to spec is something that forwards telemetry in OTel format over OTLP to intermediate components/backends.

We have API `AddCollector` on `TracerBuilder` which is something that generates spans (e.g. HTTP in or out ). Spec suggests calling them 'adapters' but does not insist on it.

For the sake of common terminology, I propose to rename `AddCollector` to `AddAdapter` and use 'collector'  only in the sense spec uses it (service/daemon/agent)

**Comment by damonbarry** [comment]
Is it safe to say that pretty much _all_ instances of the word "collector" in the current master branch should be "adapter"?

**Comment by SergeyKanzhelev** [comment]
@damonbarry yes. We need to find time for a massive rename =). Right now there is a PR in flight that introduces a new collector. Maybe right after it.

**Comment by longility** [comment]
@SergeyKanzhelev do you know if that PR for new collector is in? I don’t see one.

Also, who is planning to do this work?

I have done plenty of refactoring before, and I can help out. I’m still new to this codebase. Not sure if first issue for me with this is okay, but willing to help out.

**Comment by longility** [comment]
I went ahead and did the work.
