### ISSUE TITLE
.NET Core 6 - SQL Instrumentation - App Crashed 

### ISSUE THREAD

**Issue by Tusharknath1** [open-telemetry/opentelemetry-dotnet#3354]
**nuget PACKAGES -** 
"OpenTelemetry" Version="1.3.0" />
"OpenTelemetry.Contrib.Instrumentation.MySqlData" Version="1.0.0-beta1" />
"OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.3.0" />
"OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.4" />
"OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.4" />
"OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.4" />
"OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc9.4" />
"MongoDB.Driver.Core.Extensions.OpenTelemetry" Version="1.0.0" />
"MongoDB.Driver.Core.Extensions.DiagnosticSources" Version="1.1.0" />
"System.Data.SqlClient" Version="4.8.3" />

**ERROR Before crashed -** 
{"EventName":"NullActivity","EventId":2,"ActivityId":"00000000-0000-0000-0000-000000000000","RelatedActivityId":"00000000-0000-0000-0000-000000000000","Payload":["System.Data.SqlClient.WriteCommandAfter"],"PayloadNames":["eventName"],"EventSource":{"Name":"OpenTelemetry-Instrumentation-SqlClient","Guid":"2eaa0ac9-db58-5211-9e9b-13d597f991d9","Settings":4,"ConstructionException":null},"Keywords":263882790666240,"Opcode":0,"Task":65532,"Tags":0,"Message":"Current Activity is NULL in the \u0027{0}\u0027 callback. Span will not be recorded.","Channel":0,"Version":0,"Level":3,"OSThreadId":26,"TimeStamp":"2022-06-08T00:06:21.7956936Z"}

**Startup.cs** - Code -> **NOT Using Microsoft.Data.SqlLClient** 
services.AddOpenTelemetryTracing(tracerProviderBuilder =>
                {
                    // Step 1. Declare the resource to be used by this tracer provider.
                    tracerProviderBuilder
                            .SetResourceBuilder(resourceBuilder);

                    // Step 2. Configure the SDK to listen to the following auto-instrumentation
                    tracerProviderBuilder
                            .AddAspNetCoreInstrumentation(options =>
                            {
                                options.RecordException = true;
                            })
                            .AddHttpClientInstrumentation()
                            .AddSqlClientInstrumentation(options =>
                            {
                                options.SetDbStatementForStoredProcedure = true;
                                options.SetDbStatementForText = true;
                                options.RecordException = true;
                            })
                            .AddMongoDBInstrumentation()
                            //.AddRedisInstrumentation()
                            ;

                    tracerProviderBuilder
                        .AddOtlpExporter(options =>
                        {
                            options.Endpoint = new Uri($"{Environment.GetEnvironmentVariable("OTEL_EXPORTER_OTLP_ENDPOINT")}");
                            //options.Headers = Environment.GetEnvironmentVariable("OTEL_EXPORTER_OTLP_HEADERS");
                            // options.Protocol = OtlpExportProtocol.Grpc;
                            // options.Protocol = OtlpExportProtocol.HttpProtobuf;
                        });
                });

**Comment by cijothomas** [comment]
@vishweshbankwar can you check this?

**Comment by vishweshbankwar** [comment]
@Tusharknath1 - I am not able to repro this on my end. Could you please share your repro app? 

`Create a self-contained project using the template of your choice, apply the
minimum required code to result in the issue you're observing.`

**Comment by Kielek** [comment]
Closing as non-reproducible. Lack of any comments from the author by almost 2 years.
