### ISSUE TITLE
OpenTelemetryProtocol exporter SpanListPool holds spans, which shows up as a possible leak memory.

### ISSUE THREAD

**Issue by cg110** [open-telemetry/opentelemetry-dotnet#3356]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):
OpenTelemetry.Exporter.OpenTelemetryProtol 1.2.0-rc2

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):
net472 target, running on net48

## Symptom

While examining memory dumps for a memory leak I found that the OpenTelemetry Exporter Is holding ~5MB of memory for ~6,500 spans, with 16 InstrumentationLibrarySpans objects held in a pool.

These are rooted from the ActivityExtentions SpanPoolList.  It appears that each InstrumentationLibrarySpans object contains an array, which has the Span objects.  I suspect this array needs to be cleared to allow GC to remove the objects from memory.

## Reproduce

I'm not sure on the best way, these are long running services which may have generated a lot of spans over time, however, comparing 2 dumps ~16 hours apart shows a growth of ~2,000 spans being rooted from the InstrumentationLibrarySpans, suggesting that the arrays may have gown, and then been filled with spans.

## Additional Context

It's a small memory leak, but it would be nice to tidy up and release the references to spans that aren't needed, so GC can clean them up.

**Comment by cg110** [comment]
I suspect this line:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs#L88
perhaps should have just called Clear() on the RepeatableField to release everything.  By dynamically messing with RepeatableField to set Count to 0 the array is never cleared out.

**Comment by lnaie** [comment]
We are seeing this issue as well, in less than 24h.
![ot-image](https://user-images.githubusercontent.com/1276077/227493780-555e8ce9-0bef-4f7b-b9da-1c8bcc88ead0.png)

**Comment by cg110** [comment]
I suspect this was fixed by https://github.com/open-telemetry/opentelemetry-dotnet/commit/f7f535866b3c4cfef19661c4e97b41cf3a2091df
I think it was in otel 1.4

**Comment by lnaie** [comment]
Great, but it was pushed into an alpha release: 1.5.0-alpha.1. 🗡️
