### ISSUE TITLE
Add Processor on Metrics

### ISSUE THREAD

**Issue by WenheLI** [open-telemetry/opentelemetry-dotnet#3358]
# Question

Hi, I noticed that there is no AddProcessor API for Metrics.
Does this mean the Metrics data could not apply any processor?
In this case, if I want to add any additional information on the metrics data, what would be the best practice?

Thanks

**Comment by cijothomas** [comment]
As of current implementation, you need to modify the calling site (like histogram.Record, Counter.Add etc) itself to have any additional tags/dimensions. 
If the dimension is static, recommendation is to use the Resource API for that.

(There is no Metric spec about a MetricProcessor (SpanProcessor equivalent), so we wont be adding that capability without spec).

There was some spec about using Views concept to add additional tags (from Baggage/ etc), but that part was not part of the current stable spec. Until it gets added back (and .NET implements the spec), there is no workaround unfortunately.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view
