### ISSUE TITLE
http.flavor is not following the spec for metrics in the OpenTelemetry.Instrumentation.AspNetCore

### ISSUE THREAD

**Issue by xavirec** [open-telemetry/opentelemetry-dotnet#3363]
# Bug Report
`OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.4` Runtime version: `net6.0`

`http.flavor` is not following de [specs for metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#http-server)

In the [`HttpInMetricsListener`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs) the value of the `http.flavor` is set to the value of the HttpContext.Request.Protocol which is either HTTP/1.1, HTTP/2, etc.

**What is the expected behavior?**
`http.flavor` should be the kind of HTTP protocol used: "1.0", "1.1", "2", "SPDY" or "QUIC".

**Comment by cijothomas** [comment]
Thanks for reporting the issue.

Will fix this once https://github.com/open-telemetry/opentelemetry-dotnet/pull/3372 is accepted.
