### ISSUE TITLE
Capture tracing header for incoming requests

### ISSUE THREAD

**Issue by mwinkler** [open-telemetry/opentelemetry-dotnet#337]
Hi

If my webserver receives a request with tracing http headers (for example 'Uber-Trace-Id' (jaeger) or w3c trace context headers) from a other system (eg. traefik),
how do i attach this tracing context/id, that the current span (in the request) acts like a child of the given tracing id from the header.

Is there some interception when the request collector creates the current span for the request, where i can inject these tracing ids?

Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
            services.AddOpenTelemetry(builder => builder
                .SetSampler(Samplers.AlwaysSample)
                .AddRequestCollector()
                .AddProcessorPipeline(c =>
                    c.SetExporter(new JaegerTraceExporter(
                        new JaegerExporterOptions
                        {
                            AgentHost = "jaeger",
                            ServiceName = "product-api",
                            AgentPort = 6831
                        }))));
}
```

**Comment by MikeGoldsmith** [comment]
Hi @mwinkler 

The process of carrying trace information between systems, eg via HTTP headers, is propagation. Propagators have two functions:
1) Inject - given a `SpanContext`, creates a known structure that can be passed between desperate systems (eg via HTTP headers, TextMap, etc)
2) Extract - given a known structure, create a `SpanContext` that includes TraceId and ParentSpanId that be used as the parent span context when creating new spans.

Propagators are configured as part of the Tracer, and can be configured within `AddOpenTelemetry` by setting the TracerFactory.

**Comment by mwinkler** [comment]
Hi @MikeGoldsmith
Thank you for the hint.

So i build this class:
```csharp
public class JaegerFormat : ITextFormat
{
    internal static readonly string JeagerHeaderName = "Uber-Trace-Id";

    private static readonly HashSet<string> AllFields = new HashSet<string>() { JeagerHeaderName };

    public ISet<string> Fields => AllFields;

    public SpanContext Extract<T>(T carrier, Func<T, string, IEnumerable<string>> getter)
    {
        // example: 5e9866b886052faf:23f04737ce3da38e:5e9866b886052faf:1
        //              {trace-id}  :   {span-id}    :{parent-span-id}:{flags}
        var traceIdStr = getter(carrier, JeagerHeaderName)?.FirstOrDefault();
        
        Console.WriteLine($"Jaeger header ({JeagerHeaderName}) value: {traceIdStr}");

        if (traceIdStr != null)
        {
            var parts = traceIdStr.Split(':');
            var traceId = ActivityTraceId.CreateFromString((new string('0', 32 - parts[0].Length) + parts[0]).AsSpan());
            var spanId = ActivitySpanId.CreateFromString((new string('0', 16 - parts[1].Length) + parts[1]).AsSpan());
            
            return new SpanContext(traceId, spanId, ActivityTraceFlags.Recorded);
        }

        return SpanContext.Blank;
    }

    public void Inject<T>(SpanContext spanContext, T carrier, Action<T, string, string> setter)
    { }
}
```

and register it at `startup.cs`
```csharp
services.AddOpenTelemetry(builder => builder
    .SetSampler(Samplers.AlwaysSample)
    .AddRequestCollector()
    .AddProcessorPipeline(c =>c.SetExporter(new JaegerTraceExporter(new JaegerExporterOptions{ ... })))
    .SetTextFormat(new JaegerFormat())
);
```

The problem is, that the `Extract()` method of `JaegerFormat` never gets called.

I try to analyze why, found the this code in `OnStartActivity()` at `OpenTelemetry.Collector.AspNetCore.Implementation.HttpListener`

```csharp
if (this.hostingSupportsW3C)
{
    this.Tracer.StartActiveSpanFromActivity(path, Activity.Current, SpanKind.Server, out span);
}
else
{
    var ctx = this.Tracer.TextFormat.Extract<HttpRequest>(
        request,
        (r, name) => r.Headers[name]);

    this.Tracer.StartActiveSpan(path, ctx, SpanKind.Server, out span);
}
```
It seems that the `this.hostingSupportsW3C` flag is set to `true` if you use .NET Core 3 (what i using).
Currently i see no way to set this flag to `false` so that the `this.Tracer.TextFormat.Extract()` gets called.
Do I miss something?

**Comment by SergeyKanzhelev** [comment]
Similar to https://github.com/open-telemetry/opentelemetry-dotnet/issues/346. assigning to the current milestone

**Comment by cijothomas** [comment]
closing old issue.
There is Propagators API now available to do inject/extract *any* propagation format for propagating Context/Baggage.

**Comment by saborrie** [comment]
I found myself here after trying to do this with Traefik, which can only send jaeger or zipkin formatted propagation.

I don't really understand what is being referred to here as the "Propagators API" - if there is an idiomatic way to handle custom tracing propagation then either an example or a link to an example would be appreciated.

In case it helps anyone else who ends up here, I managed to get the effects I wanted by overriding the default IHttpContextFactory in ASP.NET Core, I don't know if this is a recommended thing to do or not!

Here is an example transforming the B3 formatted headers into a traceparent header:
```cs
using System;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;

...

    public class CustomHttpContextFactory : IHttpContextFactory
    {
        private readonly DefaultHttpContextFactory defaultHttpContextFactory;

        public CustomHttpContextFactory(IServiceProvider serviceProvider)
        {
            this.defaultHttpContextFactory = new DefaultHttpContextFactory(serviceProvider);
        }

        public HttpContext Create(IFeatureCollection featureCollection)
        {
            var httpContext = this.defaultHttpContextFactory.Create(featureCollection);

            if (httpContext.Request.Headers.TryGetValue("X-B3-TraceId", out var traceId) &&
                httpContext.Request.Headers.TryGetValue("X-B3-SpanId", out var parentId) &&
                httpContext.Request.Headers.TryGetValue("X-B3-Sampled", out var sampled))
            {
                httpContext.Request.Headers.Add("traceparent", $"00-{traceId}:{parentId}-{(sampled == "1" ? "01" : "00")}");
            }

            return httpContext;
        }

        public void Dispose(HttpContext httpContext)
        {
            this.defaultHttpContextFactory.Dispose(httpContext);
        }
    }
```

This can be installed in a ConfigureServices like so:

```cs
    services.AddSingleton<IHttpContextFactory>(sp => new CustomHttpContextFactory(sp));
```
