### ISSUE TITLE
Update instrumentation libraries with latest semantic convention spec

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#3373]
Most of the instrumentation libraries were written when semantic conventions were in early stages, and a lot changes have occurred since then. Opening an issue to track updating instrumentation libraries in this repo (httpclients,aspnetcore,sqlclient,grpc), to match the latest spec.

An open question, which is to be discussed: How much control these instrumentations offer to user for turning on/off individual tags? Do we want a turn on/off flag for each tag? Like https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentationOptions.cs#L34.

or a set of tags? What is the criteria to make that decision (perf/security/privacy/spec-recommendedvsrequiresvsoption)

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0 Might be able to borrow some ideas from this, regd. what tags gets populated / not.

**Comment by vishweshbankwar** [comment]
closing this as the changes are tracked with https://github.com/open-telemetry/opentelemetry-dotnet/issues/4484
