### ISSUE TITLE
OpenTelemetry.Instrumentation.AspNetCore: Allow for enrichment of Activity from payload regardless of sampling decision

### ISSUE THREAD

**Issue by stschenk** [open-telemetry/opentelemetry-dotnet#3401]
We are looking to be able to implement metrics off of the Server activities.  These metrics would depend on the activity being fully enriched to provide for all the metric tags we would like to use.  And we would want metrics for all activities, not just the sampled ones.

Is it possible to add a configuration to the HttpInListener that would enable the enrichment of activities regardless of the sampling decision?

**Comment by cijothomas** [comment]
You may use AlwaysOnSampler(), so every activity will be sampled.

(In general, using traces to derive metrics is tricky, precisely due to the sampling issue you already know.)

**Comment by cijothomas** [comment]
The best bet to have all spans populated (so you can metrics on top), but not exports the spans themselves would be to use a Sampler which always return `RECORD_ONLY` from https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shouldsample

Using Metrics API for Metrics would be the ideal solution, but the above can be a temp. workaround if you really want to rely on Activity/Spans.
