### ISSUE TITLE
Remove class level member variable 'tracerprovider' from TracerTest class.

### ISSUE THREAD

**Issue by Serenyrddraig** [open-telemetry/opentelemetry-dotnet#3404]
# Feature Request
OpenTelemetry.Trace.Tests.TracerTest has a private readonly member 'tracerprovider' that is initialized in the constructor, Disposed , but otherwise never used.  

**Is your feature request related to a problem?**
Not operationally. 

If so, provide a concise description of the problem.
Where TracerProvider has relevance in each test, it is instantiated in the scope of a using with a local name identical the class level member name. While the tests remain the principal documentation on usage, this is confusing.

**Describe the solution you'd like:**
Remove the member variable.

What do you want to happen instead? What is the expected behavior?
n/a
**Describe alternatives you've considered.**
n/a
Which alternative solutions or features have you considered?
n/a
## Additional Context
n/a
Add any other context about the feature request here.

**Comment by xyq175com** [comment]
If no one fix this yet, i can drop a PR for this later.
