### ISSUE TITLE
Use `Grpc.Net.Client` with `netstandard2.0` for `OpenTelemetry.Exporter.OpenTelemetryProtocol`

### ISSUE THREAD

**Issue by ismaelhamed** [open-telemetry/opentelemetry-dotnet#3421]
# Feature Request

**Is your feature request related to a problem?**

The old `Grpc` package copies `libgrpc_csharp_ext.x64.dylib` and `libgrpc_csharp_ext.x86.so` all over the place. That's ~17MB of unnecessary libs being copied to all of our the services that references `OpenTelemetry.Exporter.OpenTelemetryProtocol` in our solution. 

**Describe the solution you'd like:**

It should be possible to use `Grpc.Net.Client` with `netstandard2.0` instead. In fact, in theory, any `net462` or greater app should be able to reference `netstandard2.0`.

**Comment by Yun-Ting** [comment]
I've chatted with @alanwest, and we are currently thinking to split the existing OTLP package into 2:
1. OpenTelemetry.Exporter.OpenTelemetryProtocol.Grpc, and
2. OpenTelemetry.Exporter.OpenTelemetryProtocol.Http

Please refer to the comment for more details:
https://github.com/open-telemetry/opentelemetry-dotnet/pull/3885#discussion_r1018557835
