### ISSUE TITLE
[Proposal] Improve tests quality

### ISSUE THREAD

**Issue by TimothyMothra** [open-telemetry/opentelemetry-dotnet#3425]
I want to improve current tests to improve both reliability and coverage.
The goal is to empower developers to make necessary changes and have high confidence that use cases aren't being broken.

To accomplish this, I'm proposing making investments in the following areas:

1. **Code Coverage** as measured by [CodeCov](https://app.codecov.io/gh/open-telemetry/opentelemetry-dotnet).
    As of 2022-07-01, There are 16 libraries. Overall code coverage is 86.21%. 11 libraries have less than 90% coverage. 2 are less than 80%.
    See also open-telemetry/opentelemetry-dotnet#3353
    - 1a. Most Important libraries (OpenTelemetry, OTLP Exporter).
      These libraries are deemed important because they are depended on by several other libraries or is the core to the overall OpenTelemetry project.
      Goal is to get these closer to 100% coverage, regardless of the triviality of those tests.
      TODO: Need to confirm this list.
    - 1b. Everything else. 
      Goal is to get these tests to 90%, prioritizing meaningful tests.
    - 1c. Integration Tests.
      Not certain if these are currently reported as part of overall code coverage.
      These should be used where appropriate to avoid excessive mocking.
2. **Reliability**
    Flaky tests impact both devs and reviewers when the CI can't be trusted.
    To accomplish this, Flaky tests need to be reported/collected in an issue(s) for further review.
    See also open-telemetry/opentelemetry-dotnet#3292, open-telemetry/opentelemetry-dotnet-contrib#1752

**Comment by TimothyMothra** [comment]
Discussed in Community Meeting (2022-07-05).
No objections. :)

**Comment by reyang** [comment]
What's the update?
