### ISSUE TITLE
Not exporting to jaeger

### ISSUE THREAD

**Issue by OldWarrior3000** [open-telemetry/opentelemetry-dotnet#3442]
# Bug Report

"OpenTelemetry" Version="1.3.0-beta.1
"OpenTelemetry.Api" Version="1.3.0-beta.1
"OpenTelemetry.Exporter.Jaeger" Version="1.3.0-beta.1
"OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.3
"OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.3
"OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.3

Runtime version net6.0

## Symptom

Hi,
we have a strange issue when exporting spans to Jaeger. We are running a .net 6 micro service in a Kubernetes cluster together with jaeger with elastic backend. In most of the environments the export works fine but we recently had an issue that it was not exporting the spans to Jaeger. None of the spans are stored in Jaeger.

As a professional I restarted all the services :smile:  and suddenly the export to Jaeger started to work. I could follow this issue on 2 separate environments. After a restart the issue is gone and spans appear correctly in Jaeger.

I am not sure why this is happening and wanted to inquiry if this is a know issue or something that was fixed already in another issue. 

Thanks in advance!

**What is the expected behavior?**
Spans are exported to Jaeger as a service is started.

**What is the actual behavior?**

Spans are not exported to Jaeger but a restart fixes the issue.

## Reproduce

Unfortunately I cannot reproduce the issue with a local docker compose. This issue is uniquely appearing on our Kubernetes cluster. 

## Additional Context

Code used to configure Jaeger in the services

```csharp
public static void AddJaegerTracing(this IServiceCollection services, string apiName,
	Action<JaegerExporterOptions> jaegerOptions, params string[] sources)
{
	if (string.IsNullOrEmpty(apiName)) throw new ArgumentNullException(nameof(apiName));
	if (jaegerOptions == null) throw new ArgumentNullException(nameof(jaegerOptions));
	if (sources == null) throw new ArgumentNullException(nameof(sources));

	SetupTracingEnricher(services);
	services.AddOpenTelemetryTracing(builder => builder
		.SetSampler(new AlwaysOnSampler())
		.AddSource(sources)
		.SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(apiName))
		.AddAspNetCoreInstrumentation((options) => options.Filter = httpContext =>
		{
#if (NET5_0 || NET6_0)
			// netstandard does not support GetEncodedUrl or any similar methods on context
			var encodedUrl = httpContext.Request.GetEncodedUrl();
			return !_ignoredPaths.Any(path => encodedUrl.EndsWith(path, StringComparison.InvariantCultureIgnoreCase));
#else
			return true;
#endif
		})
		.AddHttpClientInstrumentation(options => options.Filter = filter =>
			!_ignoredPaths.Any(path => filter.RequestUri.AbsoluteUri.EndsWith(path, StringComparison.InvariantCultureIgnoreCase)))
		.AddJaegerExporter(jaegerOptions));
}

public static void AddJaegerTracing(this IServiceCollection services, string apiName,
	IConfiguration configuration, params string[] sources)
{
	if (string.IsNullOrEmpty(apiName)) throw new ArgumentNullException(nameof(apiName));
	if (sources == null) throw new ArgumentNullException(nameof(sources));

	var jaegerConfiguration = GetJaegerConfiguration(configuration);
	services.AddJaegerTracing(apiName, o =>
	{
		o.AgentHost = jaegerConfiguration.Host;
		o.AgentPort = jaegerConfiguration.Port;
		o.MaxPayloadSizeInBytes = jaegerConfiguration.MaxPayloadSizeInBytes;
		o.ExportProcessorType = ExportProcessorType.Batch;

		o.BatchExportProcessorOptions = new BatchExportProcessorOptions<Activity>
		{
			MaxQueueSize = jaegerConfiguration.MaxQueueSize,
			ScheduledDelayMilliseconds = jaegerConfiguration.ScheduledDelayMilliseconds,
			ExporterTimeoutMilliseconds = jaegerConfiguration.ExporterTimeoutMilliseconds,
			MaxExportBatchSize = jaegerConfiguration.MaxExportBatchSize
		};
	}, sources);
}
// In Startup.cs
services.AddJaegerTracing(ApiName, Configuration, _tracingSources);
```

In configuration we are using

```json
"Jaeger": {
  "Host": "jaeger-agent.observability.svc.cluster.local",
  "Port": 6831
},
```

If you need any additional context, please let me know.

**Comment by psavoldelli** [comment]
Hello, 
do you have the problem on the inbound or outbound traces? 
I have similar issues with outbound traces using httpclient only running on k8s. No issue in localhost.

As a workaround, I have a specific delegates handler on my httpclient to remove traceparent and tracespan for the header before processing the request. 

```
protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{
    // Clean up http client request for OTEL to work
    request.Headers.Remove("traceparent");
    request.Headers.Remove("tracestate");


    return base.SendAsync(request, cancellationToken);
}
```

```
services.AddRefitClient<IOutboundApi>()
        .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
        {
            UseCookies = false
        })
        .ConfigureHttpClient((c) =>
        {
            c.BaseAddress = new Uri("");
            c.DefaultRequestHeaders.UserAgent.ParseAdd("custom...");
            c.Timeout = TimeSpan.FromSeconds(10);
        })
        .AddHttpMessageHandler<OtelHeaderWorkaroundHandler>()
        AddHttpMessageHandler<OtherDelegateHandler>();
```

**Comment by OldWarrior3000** [comment]
Hey @psavoldelli , 

thank you for your answer I managed to resolve the issue in the meanwhile. 

For me re- creating the Jaeger containers in k8s fixed the issue. 

Feel free to close the ticket.
