### ISSUE TITLE
How to know AddOtlpExporter Endpoint is working or successful?

### ISSUE THREAD

**Issue by codingkondi** [open-telemetry/opentelemetry-dotnet#3447]
when we add endpoint for Opentelemetry
how to know the url is working or other way notice us?

``` csharp
 tracerProvider.AddOtlpExporter(opts =>
                {
                    opts.Protocol = OtlpExportProtocol.Grpc;
                    //how could I know the endpoint is work?
                    opts.Endpoint = new Uri(openTelemetrySetting.ServerUrl);
                });
```

**Comment by alanwest** [comment]
For troubleshooting SDK components like the OTLP exporter you can enable diagnostic logs. Instructions here https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#self-diagnostics.

**Comment by codingkondi** [comment]
> For troubleshooting SDK components like the OTLP exporter you can enable diagnostic logs. Instructions here https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#self-diagnostics.

Thanks!
However, after I tested this feature, I wanna know could it add Ilogger pattern for logging? 
I wanna replace generating log file with sending log by Ilogger.

**Comment by pellared** [comment]
I think you could create your own `EventListener` for `"OpenTelemetry-Exporter-OpenTelemetryProtocol"` EventSource.

Here is an example of how OTel .NET AutoInstr captures OTel .NET SDK events for logging purposes: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/ac0ddf9a71d3883b736a60ac14bd258cff6ebf41/src/OpenTelemetry.AutoInstrumentation/Diagnostics/SdkSelfDiagnosticsEventListener.cs (I think it is a little easier to understand than the one `SdkSelfDiagnosticsEventListener.cs` in OTel .NET SDK)

**Comment by cijothomas** [comment]
Closing old issues with no new activity. https://github.com/open-telemetry/opentelemetry-dotnet/issues/3447#issuecomment-1185329104 is tracked via #3881
