### ISSUE TITLE
Metric silently fails to log if any of the tag values are null

### ISSUE THREAD

**Issue by tgrieger-sf** [open-telemetry/opentelemetry-dotnet#3451]
# Bug Report

OpenTelemetry 1.3.0
OpenTelemetry.Extensions.Hosting 1.0.0-rc9.4

* TBD

net5.0

* TBD

## Symptom

When a null object is passed in as a value of a tag when recording a metric, the metric will fail to log.

**What is the expected behavior?**

The metric should be logged and use an empty string for that value.

**What is the actual behavior?**

A null reference exception is thrown in OpenTelemetry.Metrics.Tags:GetHashCode(). It iterates over the keys and values and tries to get the hash code of each. If any of the values are null, it will throw a null reference exception.

## Reproduce

```
Meter meter = new Meter("meter");
IHost host = Host
    .CreateDefaultBuilder()
    .ConfigureServices(sc =>
    {
        sc.AddOpenTelemetryMetrics(mpb =>
        {
            mpb.AddPrometheusExporter();

            mpb.AddMeter(meter.Name);
        });
    })
    .Build();
host.StartAsync();
Counter<int> counter = meter.CreateCounter<int>("counter");
counter.Add(1, new KeyValuePair<string, object?>("key", null));
```

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/CHANGELOG.md#unreleased fixed in the unreleased version. You can try the daily myget build now, or wait for the next release (which should be happening as early as next week)
