### ISSUE TITLE
Observable instrument unregistration

### ISSUE THREAD

**Issue by mihi-atti** [open-telemetry/opentelemetry-dotnet#3460]
Opentelemetry spec says:

"For callback functions registered after an asynchronous instrument is created, the API is required to support a mechanism for unregistration."

Once the ObservableGauge is created there is no way to unregister it later. 
This feature is missing from .NET implementation.

**Comment by cijothomas** [comment]
> For callback functions registered after an asynchronous instrument is created

In .NET, callback is to be provided when creating the instrument itself, and does not have a "register" capability later, hence "unregister" is not required.

**Comment by cijothomas** [comment]
There is no ability to unregister an individual instrument.
`Meter` implements `IDisposable`, so you can do it at the Meter level (all instruments from that meter would be unregistered)

**Comment by mihi-atti** [comment]
@cijothomas Thanks for the answer. Have a nice day!

**Comment by basshacker** [comment]
If one calls Meter.Dispose() in an attempt to exert this kind of control over the reported metrics, what facility might they use to bring the Meter and its Instruments back online if needed? As far as I am able to tell, yes, I can stop reporting by calling Dispose() but there's no means to bring the instruments (or, indeed, the meter) back without restarting the containing process.

**Comment by cijothomas** [comment]
@basshacker There is no ability to dispose and reactivate. You can new up another Meter itself anytime, and that'll be picked up by SDK (if configured to do so).

Another option is to report empty measurements from callback, if there is no desire to report anything. (this wont clean up any resource like memory though.)
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs#L134

**Comment by mihi-atti** [comment]
@cijothomas @basshacker 
Hi all, in case I reported nothing in the callback, the last value was still exported to the collector.
So, when you would like to suspend exporting an instrument for a specific time you can override the Exporter export method and filter the items which you don't want to export to the collector. This worked for me.
