### ISSUE TITLE
Can I use .net core runtime metrics as OpenTelemetry .NET metrics out of the box?

### ISSUE THREAD

**Issue by verdysh** [open-telemetry/opentelemetry-dotnet#3487]
Hi!
We have some metrics/telemetry which are produced by .net core runtime: something about GC, Thread pool and some others.
I may be wrong, I think all these metrics can be consumed through DiagnosticListeners API.
If I want to convert these metrics to OpenTelemetry metrics should I create appropriate DiagnosticListeners and manually write data from them into Counters, Histogrames, etc or all these have already implemented in OpenTelemetry SDK? If so, where can I look for examples?
Thanks!

**Comment by cijothomas** [comment]
You may be looking for this https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime

**Comment by cijothomas** [comment]
> I think all these metrics can be consumed through DiagnosticListeners API

Not really... Probably you are referring to some runtime metrics being published via EventCounters? For that, yes you can write your own EventListener, and pipe to new API from System.Diagnostics.Meter., but you may want to wait until https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.EventCounters is ready for consumption.

**Comment by verdysh** [comment]
@cijothomas, maybe it's a stupid question, but what's the difference between EventCounters and Runtime packages? They contain different metrics?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime is to get specific metrics published by .NET Runtime components (like GC, JIT etc)

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.EventCounters is for subscribing to *any* EventCounters. Could be custom event counters, or even the ones published by the Runtime components itself! A good list can be found here : https://docs.microsoft.com/en-us/dotnet/core/diagnostics/available-counters
