### ISSUE TITLE
Is there an exporter for Azure ApplicationInsights?

### ISSUE THREAD

**Issue by verdysh** [open-telemetry/opentelemetry-dotnet#3488]
Hi!
I host my app in Azure.
I've being using Microsoft.ApplicationInsights.AspNetCore for writing traces and log to Azure.
I want to try OpenTelemetry .NET. But I didn't find exporter for Azure.
Does such exporter exist? If so could somebody give me the link to it?

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-overview
