### ISSUE TITLE
Instrumentation libraries improvements

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#3495]
# Instrumentation libraries improvements

## Subscribing to DiagnosticSource events

Instrumentation libraries subscribe to the diagnostic source events by looking at event names
that ends with Start, Stop, Exception etc [ref](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6f2b1a0b3412f2860d065c81b058441977927584/src/OpenTelemetry/DiagnosticSourceInstrumentation/DiagnosticSourceListener.cs#L52-L67). This could result in subscribing to events which we did not
intend to. One such example is #3475.

**Discussion**: Should we match with explicit names rather than pattern matching?

## Relying on `Activity.Current`

When the diagnostic source events are written by the respective framework libraries. Usually the activity is 
not part of the payload or activity itself is not started by the framework e.g. SQL instrumentation. In order
to enrich/modify activities instrumentation libraries rely on `Activity.Current` [ref](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6f2b1a0b3412f2860d065c81b058441977927584/src/OpenTelemetry/DiagnosticSourceInstrumentation/DiagnosticSourceListener.cs#L52-L67) which may cause issues e.g. #3490. 

**Action** : Review any more cases like the one shown in example.

## Documentation

We do not have a detailed inventory of events that the instrumentation libraries in this
repo subscribes to. Having this documented for each instrumentation would help provide more clarity to users. Also, this would help us analyze and make decision on whether we need to support more events or update any existing ones. 

**Action**: Update `Readme` documents for each instrumentation library with the event names it subscribes to.

## Avoid reflection (ASP.NET Core)

Reflection is used to extract properties from events payload ([e.g.](https://github.com/open-telemetry/opentelemetry-dotnet/blob/44ac86cb741544b4e5b5ff043bb71454b6f9d8ae/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L251-L255)). This was done in order to avoid nuget reference. Now that we have FrameworkReference `Microsoft.AspNetCore.App`, could we avoid reflection?

**Comment by vishweshbankwar** [comment]
@cijothomas @alanwest - let me know if I missed something or need to add more details.

**Comment by Kielek** [comment]
@vishweshbankwar, on the AutoInstrumentation side also for DevOps scenarios it will be great to have possibility to reconfigure all instrumentation libraries by the environmental variables. 

Please check https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/519

**Comment by vishweshbankwar** [comment]
> @vishweshbankwar, on the AutoInstrumentation side also for DevOps scenarios it will be great to have possibility to reconfigure all instrumentation libraries by the environmental variables.
> 
> Please check [open-telemetry/opentelemetry-dotnet-contrib#519](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/519)

@Kielek - Could you please open a new issue to track this which can be used for discussion as well.

**Comment by Kielek** [comment]
@vishweshbankwar, as I know @CodeBlanch is doing a lot of changes to make as closer to this goal.

@CodeBlanch, do you need a separate task for now?

**Comment by vishweshbankwar** [comment]
Marking this complete. All the PRs related to this are linked above.
