### ISSUE TITLE
Is there instrumentation for Azure Service Bus?

### ISSUE THREAD

**Issue by verdysh** [open-telemetry/opentelemetry-dotnet#3501]
Hi!
I host my apps in Azure.
I use ServiceBus for communication between applications.
ApplicationInsights is used for storing applications telemetry.

I managed to achieve that I see incoming/outgoing http calls and SQL calls. As I have ServiceBus in my infrastructure, I want to see sends and receives to/from it. I didn't find any instrumentation for that neither in https://github.com/open-telemetry/opentelemetry-dotnet/ nor https://github.com/open-telemetry/opentelemetry-dotnet-contrib.

Is there some ready to use packages?

**Comment by cijothomas** [comment]
As you already found, OpenTelemetry repos do not have any Service Bus instrumentation. You'll need to ask Azure Service Bus repo. 

Also see this https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/

**Comment by kiro1993** [comment]
@cijothomas is it still the same case? no support for azure service bus in open telemetry? given that i'm not using azure monitor exporter

**Comment by cijothomas** [comment]
@kiro1993 I suggest asking this in the ServiceBus repo.
