### ISSUE TITLE
CreateObservableGauge measurements continue to be reported even if not returned in callback

### ISSUE THREAD

**Issue by KnicKnic** [open-telemetry/opentelemetry-dotnet#3508]
# Bug Report

OpenTelemetry 1.3.0-rc.2
OpenTelemetry.Exporter.Prometheus 1.3.0-rc.2
OpenTelemetry.Api 1.3.0-rc.2

 `net6.0`

## Symptom

I expose prometheus metric endpoint and hit it. This runs the callback I register in 
``` csharp

ObservableGauge<int> onTheShelfGauge = s_meter.CreateObservableGauge<int>(name: "on-the-shelf",
                                                            unit: "Items",
                                                            observeValues: GetMeasurements,
                                                            description: "Things on the shelves")
```
If I emit measurements in the first callback of 
``` csharp
new Measurement<int>(5, new[] { new KeyValuePair<string, object?>("item", "keyboards") });
```

and then on the second invocation of the callback I emit
``` csharp
new Measurement<int>(3, new[] { new KeyValuePair<string, object?>("item", "mice") });
```

**What is the expected behavior?**
What did you expect to see?

Iterations
1. 5 keyboards
2. 3 mice

**What is the actual behavior?**
What did you see instead?

Iterations
1. 5 keyboards
2. 5 keyboards, 3 mice

## Reproduce

Not provided

## Additional Context

To "fix" this I am keeping a map of measurements I have made in the past and their keyvaluepairs, and then reporting them as zero if they don't exist anymore. This complicates the code a lot. I would prefer to only have to track what I know about now, not everything I have potentially logged in the past.

**Comment by cijothomas** [comment]
This is the expected behavior in Prometheus (or any cumulative exporters).
See https://github.com/open-telemetry/opentelemetry-dotnet/issues/2524#issuecomment-971881437
