### ISSUE TITLE
Exception handled in ExceptionHandler middleware is recorded by ASP.NET Core instrumentation

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#3514]
If the exception thrown during request processing is handled using Exception Handler middleware, the exception is currently recorded by the instrumentation. However, this does not match with the definition of [RecordException](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore#recordexception) which calls out `Unhandled` exceptions specifically. The issue occurs due to the following reason:

The diagnostic source event name that is written in case of handled exception by handler is `Microsoft.AspNetCore.Diagnostics.HandledException` and in case of unhandled exception is `Microsoft.AspNetCore.Diagnostics.UnhandledException`. However, due to the [pattern matching](https://github.com/open-telemetry/opentelemetry-dotnet/blob/0187a2a77a9a397b4de31d52d9ca42035c250ffd/src/OpenTelemetry/DiagnosticSourceInstrumentation/DiagnosticSourceListener.cs#L60) both handled and unhandled exceptions are recorded. 

Related issue #3495.

**Comment by cijothomas** [comment]
We should remove pattern matching and rely on exact names!

**Comment by vishweshbankwar** [comment]
@cijothomas @alanwest - one of the ways we can achieve this
https://github.com/open-telemetry/opentelemetry-dotnet/pull/3519

open to comments / other ideas.

**Comment by cijothomas** [comment]
Closed via #3519
