### ISSUE TITLE
The stats  of distribution  may  not be correct.

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#353]
I use the distribution to aggregations:

        private static readonly IViewManager ViewManager = Stats.ViewManager;
        private static readonly IStatsRecorder StatsRecorder = Stats.StatsRecorder;
        private const string TagUrl = "url";
        private const string TagMethod = "method";
        private const string TagStatus = "status";
        private static readonly ITagContext TagContext = new TagContext(new Dictionary<string, string>
        {
            { TagUrl ,"http://test.url"},
            {TagMethod ,"POST"},
            { TagStatus,"200" },

        });
        private static readonly double[] ResponseTimeBoundaries= new double[] { 0.01, 0.5, 1, 2};
        private static readonly List<string> TagKeys = new List<string> { TagUrl, TagMethod, TagStatus };
        private static readonly IMeasureDouble MeasureResponseTimeBucket = MeasureDouble.Create(
            "http_response_time_seconds",
            " histogram test",
            "s");

        private static readonly IView ResponseTimeBucketView = View.Create(
            ViewName.Create("http_response_time_seconds"),
            " histogram test",
            MeasureResponseTimeBucket,
            Distribution.Create(BucketBoundaries.Create(ResponseTimeBoundaries)),
            TagKeys);
        static void Main(string[] args)
        {
            ViewManager.RegisterView(ResponseTimeBucketView);

            StatsRecorder.NewMeasureMap().Put(MeasureResponseTimeBucket,0.1).Record(TagContext);
            StatsRecorder.NewMeasureMap().Put(MeasureResponseTimeBucket, 0.9).Record(TagContext);
            StatsRecorder.NewMeasureMap().Put(MeasureResponseTimeBucket, 1.6).Record(TagContext);
            StatsRecorder.NewMeasureMap().Put(MeasureResponseTimeBucket, 1.9).Record(TagContext);
            StatsRecorder.NewMeasureMap().Put(MeasureResponseTimeBucket, 8).Record(TagContext);
            var view = ViewManager.GetView(ResponseTimeBucketView.Name);
            var distributionData=(DistributionData)view.AggregationMap.First().Value;
            foreach (var item in distributionData.BucketCounts)
            {
                Console.WriteLine(item);
            }
        }

The bucket was:  [ 0.01, 0.5, 1, 2 ]
The Test data was :[0.1, 0.9, 1.6, 1.9, 8 ]
The aggregation result was: [ 0, 1, 1, 2, 1]

If this distribution is same with Prometheus Metric type of Histogram, the aggregation result should be [0, 1, 2, 4, 5], Because as long as this value is less than the upper bound, it will be counted.

But,OpenTelemetry  distribution  was needs to be counted in an interval.

**Comment by SergeyKanzhelev** [comment]
Stats API is deprecated. Sorry for confusion. Closing the issue
