### ISSUE TITLE
exporter/Prometheus:the metric type of distribution format is not  consistent with Prometheus metric type of  histogram

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#354]
When I used Prometheus Export to export metrics, I found that the format of distribution metrics was wrong.
`# HELP http_response_time_seconds_bucket Bucket of time needed to handle requests
http_response_time_seconds_bucket{metrickind="Server",url="https://localhost:44386/api/HttpIn",method="GET",status="404"} 0.0022608 1574682841307
http_response_time_seconds_bucket{metrickind="Client",url="http://www.baidu.com",method="GET",status="200"} 0.1055391 1574682841307
http_response_time_seconds_bucket{metrickind="Server",url="https://localhost:44386/v1/Values/Mongo",method="GET",status="200"} 0.0139832 1574682841307
http_response_time_seconds_bucket{metrickind="Client",url="http://localhost:9411/api/v2/spans",method="POST",status="202"} 0.00504516666666667 1574682841307
http_response_time_seconds_bucket{metrickind="Server",url="https://localhost:44386/api/values",method="GET",status="200"} 1.4024115 1574682841307
http_response_time_seconds_bucket{metrickind="Server",url="https://localhost:44386/v1/Httpout",method="GET",status="404"} 0.0003646 1574682841307
http_response_time_seconds_bucket{metrickind="Server",url="https://localhost:44386/favicon.ico",method="GET",status="0"} 0.0003492 1574682841307`

The correct format should be.:
http_response_time_sum{.....} value
http_response_time_count{......} 4
http_response_time_seconds_bucket{....,le="0.01"}   0
http_response_time_seconds_bucket{....,le="0.1"}    1
http_response_time_seconds_bucket{....,le="1"}   2
http_response_time_seconds_bucket{....,le="4"}  4
http_response_time_seconds_bucket{....,le="+Inf"}  4

**Comment by thangchung** [comment]
Which version of OTel you used? I'm struggling to use it with .NET gRPC Hosting on `0.2.0-alpha.123` :(

**Comment by czs1993** [comment]
I used  OpenTelemetry.Exporter.Prometheus on 0.2.0-alpha.100

**Comment by cijothomas** [comment]
There is no API/Aggregator for Histogram yet. Summary (min,max,sum,count) is the only one available, and it is correctly exported to Prometheus with #608 

Please close this.
