### ISSUE TITLE
Microsoft.Extensions.Configuration.dll has wrong modified date

### ISSUE THREAD

**Issue by sunmijiang** [open-telemetry/opentelemetry-dotnet#3540]
# Bug Report

OpenTelemetry 1.3.0

Runtime version .net framework 4.7.2

## Symptom

Create a new C# project and add reference opentelemetry 1.3.0, build project, then you will see the following dlls have wrong modified date in the bin folder.
![image](https://user-images.githubusercontent.com/110593895/182792138-26e469ee-654d-4603-a395-3f23e3839523.png)

**Comment by cijothomas** [comment]
This repo does not own Microsoft.Extensions.Configuration. Please report it this at the .NET runtime repo.
