### ISSUE TITLE
Extend Metric and MetricPoint classes to allow users modify already created metric data in pipelines

### ISSUE THREAD

**Issue by Ilia-work** [open-telemetry/opentelemetry-dotnet#3541]
Hello, 

the properties of [LogRecord](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/LogRecord.cs) class were made settable to unblock users who want to scrub data or otherwise modify it in their pipelines (https://github.com/open-telemetry/opentelemetry-dotnet/pull/3378).

It would be very useful to have similar possibilities in [Metric](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Metrics/Metric.cs) and [MetricPoint](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Metrics/MetricPoint.cs) classes. For example, set a custom StartTime/EndTime for MetricPoint.

Do you plan to make changes in Metric and MetricPoint classes to allow users modify already created metric data in pipelines?

**Comment by cijothomas** [comment]
Can you describe a bit more about what is the end goal? Is start/end time the only thing required and why?

**Comment by Ilia-work** [comment]
Hello,

A couple of years ago we have built our own diagnostics data collector and now would like to integrate OpenTelemetry into it. Our collector receives json data through REST calls and we would like to adjust our collector to make it possible to convert diagnostics data from our custom format into the OTLP format and then send it to the OTLP collector.

You have already made all properties of [LogRecord](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/LogRecord.cs) settable (https://github.com/open-telemetry/opentelemetry-dotnet/pull/3378) which allowed us to create custom LogRecords and it would be very useful to have the same capabilities for [Metric](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Metrics/Metric.cs)/[MetricPoint](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Metrics/MetricPoint.cs).

The ability to specify Metrics/MetricPoint properties could help us and other users to integrate your solution into existing diagnostic data collectors and could make usage scenarios of the OTLP .NET more flexible.

Thank you in advance.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/2951/files Some spec work occurring, which might be what you are looking for.

**Comment by Ilia-work** [comment]
Hello Cijo, thank you for the answer. 

Yes, it looks like that the planned changes can be useful for us.

Currently these changes are only for the specification. Do you have any issue opened or document/roadmap where this feature mentioned and we can track the progress of it in the opentelemetry-dotnet repo?

**Comment by goldenc** [comment]
+1
