### ISSUE TITLE
Exporters in OT repo

### ISSUE THREAD

**Issue by mgodse** [open-telemetry/opentelemetry-dotnet#356]
We are building a TraceExporter and see that other vendors have added Exporters in the OT repo. We had heard from Java OT implementation that vendor specific Exporters should be in separate repos. Any guidance here would be helpful, so we can think through our packaging story. 

Thanks

**Comment by austinlparker** [comment]
In general, vendor-specific exporters should be kept outside of the API/SDK repository. The current exporters in this repository will be migrated out once we've hit beta (or around then).

**Comment by mgodse** [comment]
Thanks for your response, is there a specific repo where Exporters are collectively kept, or vendors can choose to host them in their respective github orgs?

**Comment by austinlparker** [comment]
In the vendors GitHub org, yeah.
