### ISSUE TITLE
Dj

### ISSUE THREAD

**Issue by deejaybanban** [open-telemetry/opentelemetry-dotnet#3564]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* TBD

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* TBD

## Symptom

**What is the expected behavior?**

What did you expect to see?

**What is the actual behavior?**

What did you see instead?

## Reproduce

Create a self-contained project using the template of your choice, apply the
minimum required code to result in the issue you're observing.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by utpilla** [comment]
No useful information provided.
