### ISSUE TITLE
OpenTelemetry solution doesn't build

### ISSUE THREAD

**Issue by gunnicus** [open-telemetry/opentelemetry-dotnet#3566]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* latest

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* .net6.0

## Symptom

**What is the expected behavior?**
Solution doesn't build
![image](https://user-images.githubusercontent.com/4023477/183561646-883a9d27-f894-4c89-9c75-e91d7cbbbd32.png)

What did you expect to see?
Solution to build
**What is the actual behavior?**

What did you see instead?

## Reproduce

1.Download opentelemetry-donet-main.zip from github
2.unzip
3.open global.json file under opentelemetry-dotnet-main folder
4.change verstion from 7-preview to  "version": "6.0.000" then save
![image](https://user-images.githubusercontent.com/4023477/183562068-838c9e45-bfbd-40b8-a46e-a55b060efa54.png)

5.open OpenTelemetry.sln in visual studio 2022
6.click build solution
7.got 1368 errors complians about .net version etc screenshot attached above. I only have .net6 installed, don't have .net7 preview.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by vishweshbankwar** [comment]
@gunnicus - Please refer to updated [requirements](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/CONTRIBUTING.md#development-environment). .NET7.0 is needed due to projects referencing .NET7.0.
