### ISSUE TITLE
Gauge metrics - Any future plans to support it?

### ISSUE THREAD

**Issue by edenbd36** [open-telemetry/opentelemetry-dotnet#3571]
I am considering migrating to Open Telemetry but I'm missing the ability to send a one-time Gauge (rather than an observable Gauge).
Any plans to add support for it?

**Comment by cijothomas** [comment]
Please open the issue in the specification repo, describing the need for a non-observable gauge. As adding new instruments must come with specification first.

There were some discussions about in the spec repo, you can search for it.
