### ISSUE TITLE
Prometheus exporter should return empty body with 200 code not 204 when no metrics

### ISSUE THREAD

**Issue by kriswuollett** [open-telemetry/opentelemetry-dotnet#3582]
# Bug Report

Not sure if exactly the same as mentioned in #2400 since that mentions a part of the system not being ready, but I think I encountered the 204 issue when simply no metrics had been populated yet. If this is the same issue, IMO keeping this one to track this specific issue outside of a catch-all would be nice.

For the case when there are no metrics, the Prometheus export should return an empty body with 200 status code, not "204 Empty Content", [because the Prometheus scraper will think it is an error](https://github.com/prometheus/prometheus/blob/b8af4632be96081f60d280971d7ddc298d27a006/scrape/scrape.go#L789). 

After I hit my health check endpoint it caused a counter to be modified which resulted in the metrics export returning content finally:

![image](https://user-images.githubusercontent.com/1834192/185229120-5dca0888-7721-43b4-be1a-f93409ff4a90.png)

```
    <PackageReference Include="OpenTelemetry" Version="1.3.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.3.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.3.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus" Version="1.3.0-rc.2" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.4" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.4" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.4" />
```

```
Microsoft.AspNetCore.App 6.0.5
Microsoft.NETCore.App 6.0.5
```

**Comment by CodeBlanch** [comment]
@Yun-Ting You want to tackle this? We looked for something documented about what the status code should be for success-no-data case but couldn't find anything so we went with 204. The code above shows the scraper behavior I think that is valid enough documentation to switch it to 200.

/cc @reyang
