### ISSUE TITLE
Spans handled by BatchingSpanProcessor.Worker may get lost on Shutdown

### ISSUE THREAD

**Issue by oliverroer** [open-telemetry/opentelemetry-dotnet#360]
Consider the following scenario:

- You've [configured the Jaeger exporter](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/README.md#using-the-jaeger-exporter).
- You dispose your TracerFactory
```
using (TracerFactory tracerFactory = ...) {
   ...
} // Dispose is called at this point.
```

The Dispose sets off a chain of events, one of which is a call to [`Dispose` on the `BatchingSpanProcessor`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L150), which calls [`ShutdownAsync`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L122).
Separately, the [`worker`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L94) task is executing the [`Worker`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L201) method.
In some cases, the worker may be in the middle of executing [`ExportBatchAsync`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L158), and may have [may be about to call the `exporter`s `ExportAsync` method](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L185).

If [`ShutdownAsync`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L122) finishes executing in the meantime, the following will have happened:
- The thread executing shutdown will [empty the `exportQueue` on the `BatchingSpanProcessor` into the `JaegerTraceExporter`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L136) and then call [`ShutdownAsync`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L139) on the exporter, flushing all it's contents.
- The worker thread resumes, holding some spans, which it will then try to export, but they will just queue up in the `JaegerTraceExporter`, which will not flush it - in other words, the spans will not end up anywhere.

**Comment by MikeGoldsmith** [comment]
Hi @oliverroer 

We have seen this behaviour before in other background worker style implementations and agree it's not ideal. If the worker is actively exporting spans, it should block shutdown until it has completed, or a shutdown delay has been reached to prevent indefinite blocking.

**Comment by cijothomas** [comment]
This must be handled now. If there are more issues, we can revisit. closing now.
