### ISSUE TITLE
Prometheus scraping endpoint returns invalid hostname when using different port and Prometheus running in Docker

### ISSUE THREAD

**Issue by MonocleKelso** [open-telemetry/opentelemetry-dotnet#3608]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):
`OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.4`
`OpenTelemetry.Exporter.Prometheus 1.3.0-rc.2`
`OpenTelemetry.Extensions.Hosting 1.0.0-rc9.4`

Runtime version
net6.0

## Symptom
For local development we're using Prometheus and Jaeger in Docker so developers don't have to separately install these. When configuring the scraping endpoint to use a different port than what the app is serving on all requests to get metrics return a 400 Bad Request, Hostname is invalid. I've also tried running only Ubuntu in a container and `curl`ing the endpoint and the result is the same. Removing the predicate from the extension method and using the same port for metrics works as expected.

## Reproduce
Metrics configuration:
```csharp
services.AddOpenTelemetryMetrics(config =>
{
    config
        .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("service"))
        .AddAspNetCoreInstrumentation()
        .AddPrometheusExporter(options =>
        {
            options.HttpListenerPrefixes = new[] { "http://localhost:1234/" };
            options.StartHttpListener = true;
        });
}
```
Endpoint configuration:
```csharp
app.UseOpenTelemetryPrometheusScrapingEndpoint(context => context.Connection.LocalPort == 1234);
```
Dockerfile for running Prometheus
```
FROM prom/prometheus
ADD prometheus.yml /etc/prometheus/
```
prometheus.yml
```
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: service
    static_configs:
      - targets: ["host.docker.internal:1234"]
```
Going to localhost:1234 in a browser shows the metrics correctly, however Prometheus gets a 400 Bad Request, Hostname invalid response and says the endpoint is down.

Spinning up a new container with only Ubuntu `docker run -it ubuntu` and running
```
curl http://host.docker.internal:1234
```
also shows the HTTP 400 response.

Changing the endpoint config to not use a predicate and changing prometheus.yml to use the port the app is served on resolves the issue.

Running Docker version 20.10.17, build 100c701 on Windows

**Comment by REscobar** [comment]
I think this might be related to #2840, that is if you bind the Prometheus exporter to something else than localhost it should work, see https://github.com/open-telemetry/opentelemetry-dotnet/issues/2840#issuecomment-1072977042 and try to bind to `http://*:1234` and repeat your test

**Comment by reyang** [comment]
> I think this might be related to #2840, that is if you bind the Prometheus exporter to something else than localhost it should work, you may need to see [#2840 (comment)](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2840#issuecomment-1072977042) and try to bind to `http://*:1234` and repeat your test.

+1

@MonocleKelso I _think_ you want to try the latest version of https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.Prometheus.AspNetCore, I believe the separation of HttpListener and ASP.NET Core binding for Prometheus Exporter removed the confusion.

I'll mark this issue as resolved for now, if somehow you found it not working, feel free to reply back here and we can reopen it.

**Comment by MonocleKelso** [comment]
@reyang Thanks. Updating to the new package did not solve the issue as there doesn't appear to be a way to configure the scraping endpoint to run on a different port.
```csharp
config
    .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(configuration.ServiceName))
    .AddAspNetCoreInstrumentation()
    .AddPrometheusExporter();
```
```csharp
app.UseOpenTelemetryPrometheusScrapingEndpoint();
```
The above exposes the `/metrics` endpoint on the same port as the app. This seems not ideal as you could inadvertently expose metrics to the world. The following doesn't expose the metrics endpoint anywhere I could find it (app port, 9464, the port I have configured, etc)
```csharp
app.UseOpenTelemetryPrometheusScrapingEndpoint(context => context.Connection.LocalPort == configuration.PrometheusScrapePort);
```

**Comment by reyang** [comment]
> @reyang Thanks. Updating to the new package did not solve the issue as there doesn't appear to be a way to configure the scraping endpoint to run on a different port.

Since the hosting is managed by ASP.NET Core, I guess the endpoint has to be managed by ASP.NET Core?
@MonocleKelso how would you write an ASP.NET Core application binding on different endpoints for different RESTful APIs? I guess the solution would be the same (I'm not good at ASP.NET/Core).

**Comment by MonocleKelso** [comment]
The other concern about this endpoint being a part of the app's routing is if you have request logging and/or tracing the call to `/metrics` every X seconds is going to add noise that has to be filtered out.

@reyang I guess maybe I'm confused on the correct way to configure this?

If the default is metrics should be served on port 9464 then I would expect this configuration to do that but it does not
```csharp
config
    .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(configuration.ServiceName))
    .AddAspNetCoreInstrumentation()
    .AddPrometheusExporter();
```
The below configuration _does_ work in the browser but does not work when running Prometheus in Docker and pointing it to `host.docker.internal:9464`. (And if this works, then why is the default false?)
```csharp
config
    .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(configuration.ServiceName))
    .AddAspNetCoreInstrumentation()
    .AddPrometheusExporter(config => config.StartHttpListener = true);
```
Taking the above configuration and adding
```csharp
applicationBuilder.UseOpenTelemetryPrometheusScrapingEndpoint();
```
exposes metrics on both 9464 and the port the app is running on. Updating Prometheus to point to `host.docker.internal:AppPort` works

If I combine `AddPrometheusExporter()` with `UseOpenTelemetryPrometheusScrapingEndpoint()` (no arguments passed to either) then I get metrics only on the port the app is served on (not 9464).

Changing the exporting config to explicitly define a port for the listener and adding a predicate to the scraping endpoint
```csharp
.AddPrometheusExporter(options =>
    {
        options.HttpListenerPrefixes = new[] { $"http://localhost:{configuration.PrometheusScrapePort}/" };
        options.StartHttpListener = true;
    });

applicationBuilder.UseOpenTelemetryPrometheusScrapingEndpoint(context => context.Connection.LocalPort == configuration.PrometheusScrapePort);
```
serves metrics only on the port configured in each method (not 9464 and not the app's port), but this does not work in Docker Prometheus.

I'm a little unclear because these 2 config methods seem to either be redundant, contradictory, or cooperative depending on how you call them. It also seems like the only way to get `host.docker.internal` to work is if ASP.NET handles the request.

**Comment by cijothomas** [comment]
@MonocleKelso I am not sure if I can follow the issue. It looks like you are using the old Prometheus Exporter. 
`.AddPrometheusExporter(config => config.StartHttpListener = true);`  --> inside as asp.net core app is not the right approach.

We recently split the Exporter for Prometheus into two - one standalone exporter using HttpListener, and one as a Asp.Net Core middleware. Since you seem to be using an asp.net core app, please follow the instructions from https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.Prometheus.AspNetCore. 

There is no "default port of 9464" in this case. PrometheusExporter is added as middleware to your existing asp.net core app, so whatever ports the asp.net core host is going to listen on, will work for prometheus middleware too. (or you can restrict to specific ones using the UseOpenTelemetryPrometheusScrapingEndpoint overloads.

Let me know if this makes sense. If the latest one also does not help, please share the repro with full code used to enable PrometheusExporter, so we can help. (maybe that'll also help make sure we are all talking about same thing.)

**Comment by MonocleKelso** [comment]
@cijothomas Thanks for clarifying. I think part of my issue is the AspNetCore exporter was released while I was experimenting with this. 😄 

With that said -
> (or you can restrict to specific ones using the UseOpenTelemetryPrometheusScrapingEndpoint overloads.

I don't think this is working? Or I'm misunderstanding. Is the expectation that the following would put metrics on `localhost:9464/metrics`?

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddOpenTelemetryMetrics(config =>
    config.AddAspNetCoreInstrumentation().AddPrometheusExporter()
);

var app = builder.Build();
app.UseOpenTelemetryPrometheusScrapingEndpoint(context => context.Connection.LocalPort == 9464);

app.MapGet("/", () => "Hello World!");

app.Run();
```

**Comment by cijothomas** [comment]
> Is the expectation that the following would put metrics on localhost:9464/metrics?

^ no. The ports are controlled by your Asp.Net Core host. Prometheus metrics is simply the same ports as your asp.net core host, OR a *subset* of all the ports asp.net core host supports.

You can configure asp.net core with say portA, portB, portC.
And you can configure the prometheus to support all of the above.
Or you can configure that prometheus is only supported on portA.

in short - prometheus exporter won't enable any additional ports than that is already exposed by your asp.net core host.

**Comment by MonocleKelso** [comment]
@cijothomas Got it! I just took took the minimal repro posted above and adjusted launchsettings.json to
```
"applicationUrl": "http://localhost:9464;http://localhost:5137"
```
and it works exactly as I would expect it to. (GET to `5137` returns Hello World, GET to `5137/metrics` returns 404, GET to `9464/metrics` returns metrics)

Thanks so much for clearing this up for me!

**Comment by reyang** [comment]
Sounds like the mystery got solved.

**Comment by aristotelos** [comment]
I've tried to document the solution [here](https://github.com/open-telemetry/opentelemetry-dotnet/pull/3704).
