### ISSUE TITLE
Error when using AutoFac and Prometheus Exporter

### ISSUE THREAD

**Issue by Avto9711** [open-telemetry/opentelemetry-dotnet#3612]
# Bug Report

List of packages:
* OpenTelemetry 1.4.0-alpha.2
* OpenTelemetry.Exporter.Prometheus 1.3.0-rc.2
* OpenTelemetry.Extensions.Hoisting 1.0.0-rc9.6
* Autofac.Extensions.DependencyInjection 7.2.0 (Just for info)

Runtime version : .NET 6.0

## Symptom

Exception at the moment of register ` app.UseOpenTelemetryPrometheusScrapingEndpoint();` 

Exception Message:
`Autofac.Core.DependencyResolutionException: 'An exception was thrown while activating λ:OpenTelemetry.Metrics.MeterProvider`

Inner Exception:
`MethodAccessException: Attempt by method 'OpenTelemetry.Metrics.PrometheusExporterMeterProviderBuilderExtensions+<>c__DisplayClass0_0.<AddPrometheusExporter>b__0(System.IServiceProvider, OpenTelemetry.Metrics.MeterProviderBuilder)' to access method 'System.ServiceProviderExtensions.GetOptions<OpenTelemetry.Exporter.PrometheusExporterOptions>(System.IServiceProvider)' failed.`

**What is the expected behavior?**
The Prometheus endpoint should register successfully. 
**What did you expect to see?**
No error when registering Prometheus export endpoint 
**What is the actual behavior?**
An Error is thrown when registering the middleware (`UseOpenTelemetryPrometheusScrapingEndpoint()`)
**What did you see instead?**
Error during startup
## Reproduce
[Project to reproduce](https://github.com/Avto9711/AutofacOpenTelemetry)

In startup.cs

```  C#          
services.AddOpenTelemetryMetrics(builder =>
            {
                builder.AddMeter("just.to.test");
                builder.AddPrometheusExporter();
            });
....
...

app.UseOpenTelemetryPrometheusScrapingEndpoint();
```

in program.cs

``` C#
var builder = Host.CreateDefaultBuilder(args)
    .UseServiceProviderFactory(new AutofacServiceProviderFactory())
    .ConfigureWebHostDefaults(webHostBuilder => {
        webHostBuilder
            .UseStartup<Startup>();
    })
    .Build();
```
            
            
## Additional Context

I think this is due because when we are calling `AddPrometheusExporter` in the startup,  in runtime `PrometheusExporterMeterProviderBuilderExtensions` is using  https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/ServiceProviderExtensions.cs instead of https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Internal/ServiceProviderExtensions.cs and that's why is not able to invoke `GetOptions()` method. I'm not sure if it's that or why is doing that, it's just a hunch

**Comment by Avto9711** [comment]
I think this issue is related to this one  #3591

**Comment by cijothomas** [comment]
@Avto9711 the linked issue can be fixed by moving to the newest version of the exporter (it has been renamed to OTel.Exporter.Prometheus.AspNetCore)

**Comment by Avto9711** [comment]
Yeah, it worked thank you so much @cijothomas .
