### ISSUE TITLE
Signs of IO operation with metric Record

### ISSUE THREAD

**Issue by mrblonde91** [open-telemetry/opentelemetry-dotnet#3616]
So we've been using Meter.CreateHistogram to track the performance of requests. However the record operation appears to take a prolonged length of time at times. Eg up to 60ms. Basically we've put it in a task to handle it. Is there any ideas on what cause is and how to avoid?

**Comment by cijothomas** [comment]
Are you doing Meter.CreateHistogram in the hot path? Or just histogram.Record in the hot path, and that is taking long time? 
Can you share the meterprovider config? (i.e do you have custom histogram bounds, or just the default).
And share the version of the OpenTelemetry package being used.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/test/Benchmarks/Metrics/HistogramBenchmarks.cs#L34 Benchmarks show we are in the nanosecond world... milliseconds is *very very* concerning for this!

**Comment by mrblonde91** [comment]
Yep assumed as much, I'll grab all the above info in morning.

**Comment by mrblonde91** [comment]
@cijothomas 
 
It was being created in the hot path so I'm guessing that is possibly what's responsible for the Ms.

     var histogram = SharedTelemetryUtilities.Meter.CreateHistogram<double(TelemetryProperties.ErsRequestMeter);
                    histogram.Record(watchSLAElapsedMilliseconds);

We do have specified boundaries too.

        public static double[] HistogramDurationBoundaries = { 50, 75, 100, 250, 500, 1000, 2000, 5000, 10000 };

**Comment by mrblonde91** [comment]
![image](https://user-images.githubusercontent.com/5879863/187721406-dc9d35ef-d907-4d9d-a879-f7124100e654.png)
Much happier with it now, does seem to enter the ms range for a fraction of calls but overall rather happy with it.

**Comment by mrblonde91** [comment]
Closing this as I'm pretty happy with the resolution.
