### ISSUE TITLE
Memory leak in application causing slowdown

### ISSUE THREAD

**Issue by ejsmith** [open-telemetry/opentelemetry-dotnet#3625]
# Bug Report

## Packages
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0-alpha.2" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.4.0-alpha.2" />
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0-alpha.2" />
<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.4.0-alpha.2" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.6" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.6" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.6" />
<PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.0.0-rc9.7" />
<PackageReference Include="OpenTelemetry.Instrumentation.ElasticsearchClient" Version="1.0.0-beta.3" />
<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.0.0" />

Runtime: `net6.0`

## Symptom

I'm seeing what appears to be memory leaks in the OTel libraries that are slowly bringing my app to a crawl.

**What is the expected behavior?**

Memory usage to stay stable and not affect app performance in noticeable ways.

## Additional Context

Memory usages soon after app startup:
![image](https://user-images.githubusercontent.com/282584/188292968-a9e46c2b-1a84-412d-8a7f-07910b6759d9.png)

Memory dump from the application after running for a while:
![image](https://user-images.githubusercontent.com/282584/188292955-304e3ad3-121c-491e-b6e8-7c3b3c95c81c.png)

Code to setup OTel:
https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Web/ApmExtensions.cs

Code I'm using to do dynamic metric names:
https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Core/Utility/AppDiagnostics.cs

Metric names are not unbounded, but there are probably 30ish of them. I could figure out all of them and add static instruments, but this was just a way to make it easier to migrate from an old library. I don't really see why the code would cause problems, but I also can't imagine that this library has memory leaks and thinking it's got to be my fault somehow.

**Comment by ejsmith** [comment]
I updated my app to disable logs and traces just to try and isolate more and the problem persists. I have just disabled metrics completely to see if it continues.

I was hoping I might get some feedback and possibly ideas before, but I guess my next step will be to try and create some small repro app.

**Comment by ejsmith** [comment]
@cijothomas no, it re-uses the same instances from the concurrent dictionary and just calls `.Add(10)` on an existing instance.

**Comment by cijothomas** [comment]
The screenshots show ~62K histogram instruments, and then it got to ~880K..

**Comment by ejsmith** [comment]
Ugh. I looked at that code multiple times and didn't see that the GetOrAdd calls were not using a lambda so the new expression was running every time and creating new instances. Sorry for wasting your time.

**Comment by cijothomas** [comment]
Glad you found the root cause!
