### ISSUE TITLE
Add attributes for ActivitySource 

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#3636]
See spec: https://github.com/open-telemetry/opentelemetry-specification/pull/2579/files

meter, activitysource are part of runtime, so need changes there to support this.

**Comment by CodeBlanch** [comment]
Meter was done in .NET 8 and will be supported in OTel with #4563.

We need a similar .NET update for ActivitySource.

**Comment by CodeBlanch** [comment]
API added in .NET 9: https://learn.microsoft.com/dotnet/api/system.diagnostics.activitysource.tags

Work to support that in exporters is being tracked here: #5701
