### ISSUE TITLE
Update log component naming to reflect changes to the spec

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-dotnet#3637]
The spec [PR #2676](https://github.com/open-telemetry/opentelemetry-specification/pull/2676) to add a log API and the followup [PR #2768](https://github.com/open-telemetry/opentelemetry-specification/pull/2768) to align log API / SDK component naming impacts SDKs which have been prototyping the log SDK, including dotnet. The changes include:

* LogEmitterProvider -> LoggerProvider
* LogEmitter -> Logger
* LogProcessor -> LogRecordProcessor
* LogExporter -> LogRecordExporter

SDKs are encouraged to update component names to reflect the specification changes. 

[PR #2768](https://github.com/open-telemetry/opentelemetry-specification/pull/2768) resets the log section of the spec compliance matrix to reflect the changes.

**Comment by reyang** [comment]
OpenTelemetry .NET is using Generic (e.g. `BaseExporter<LogRecord>` and `BaseProcessor<LogRecord>`) across the logs/metrics/traces.

LogEmitterProvider/LogEmitter need to be changed @CodeBlanch.

**Comment by CodeBlanch** [comment]
`LoggerProvider` work is done. Promoting it to public is covered by #5442.
`Logger` work is done. Promoting it to public is covered by #4433.

Nothing was done for...

```
LogProcessor -> LogRecordProcessor
LogExporter -> LogRecordExporter
```

...as those never existed, we just have base classes.
