### ISSUE TITLE
[Tracing] Improve internal logging of TracerProvider configuration

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#3644]
The [MeterProvider does a really good job of logging its state](https://github.com/open-telemetry/opentelemetry-dotnet/blob/872a52f5291804c7af19e90307b5cc097b2da709/src/OpenTelemetry/Metrics/MeterProviderSdk.cs#L96) when it is constructed. We should do the same in the TracerProvider[Sdk]. The idea is this will help troubleshoot configuration issues.

**Comment by blouflashdb** [comment]
I would also like to work on this now that I worked on #3645 I could do the same here.

**Comment by ggoel** [comment]
@CodeBlanch I have raised a PR for this issue
