### ISSUE TITLE
[Logs] Improve internal logging of LoggerProvider configuration

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#3645]
The [MeterProvider does a really good job of logging its state](https://github.com/open-telemetry/opentelemetry-dotnet/blob/872a52f5291804c7af19e90307b5cc097b2da709/src/OpenTelemetry/Metrics/MeterProviderSdk.cs#L96) when it is constructed. We should do the same in the [OpenTelemetry]LoggerProvider. The idea is this will help troubleshoot configuration issues.

**Comment by blouflashdb** [comment]
I would like to work on this.

**Comment by CodeBlanch** [comment]
Thanks @blouflashdb it's all yours! 🥂
