### ISSUE TITLE
Prometheus exporter isn't working on gRPC Hosting

### ISSUE THREAD

**Issue by thangchung** [open-telemetry/opentelemetry-dotnet#365]
Currently, I have tried to integrate Prometheus exporter to gRPC Hosting which run on Kestrel server, and actually it isn't work well when HttpListener in Prometheus Exporter used at https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Exporter.Prometheus/Implementation/MetricsHttpServer.cs#L30

Could we use HttpListener on Kestrel Server evenly? As far as I know, HttpListener is quite old, and might we need to implement a middleware or an interceptor on top of ASP.NET Core or gRPC Host to collect and generate the metrics which shall be fed to Prometheus server. Could anyone in the team show me how to make it work with current implementation?

I used OTel `0.2.0-alpha.123`, and the code I put at https://github.com/thangchung/meteorite-station-demo on Meteorite-service at https://github.com/thangchung/meteorite-station-demo/blob/master/src/MeteoriteService/Program.cs

**Comment by SergeyKanzhelev** [comment]
Similar to this: https://github.com/open-telemetry/opentelemetry-dotnet/issues/65

**Comment by MikeGoldsmith** [comment]
@SergeyKanzhelev I'm working on this, but don't have access to self-assign.
