### ISSUE TITLE
What is the difference between AddHttpClientInstrumentation and AddAspNetCoreInstrumentation

### ISSUE THREAD

**Issue by candrewtemenoscom** [open-telemetry/opentelemetry-dotnet#3672]
To support OpenTelemetry tracing, in asp.net core, to provide auto trace instrumentation, we can do the followings.

services.AddOpenTelemetryTracing(providerBuilder =>
{
providerBuilder
.AddSource("TemenosInsightDataService")
.SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("InsightDataService"))
.AddHttpClientInstrumentation()
.AddAspNetCoreInstrumentation()
.AddSqlClientInstrumentation()
.AddConsoleExporter()});

After reading the limited documentation on github, I still quite not understand the purpose and difference between them. It seems to me their main purpose is to allow Enrich function to be called to add additional information to activity. I can do that on both AddHttpClientInstrumentation() and AddAspNetCoreInstrumentation() which will both add to trace context. How to choose which one to use?

Brennan Conroy suggested that AddHttpClientInstrumentation adds tracing for HttpClient only, so if your app makes external requests via the HttpClient class. And AddAspNetCoreInstrumentation would likely add tracing for the server app, meaning incoming requests and responses.

So it sounds like that those methods are used allow me to add additional info to activities that I am interested and show up in trace. However, if I am a web API service (micro-service) application, I would like to enable tracing information for other applications that would like to put trace on me. Which one method that I need to use? or I do not need to do anything?

**Comment by pellared** [comment]
1. Can you say what is missing in the documentation? See: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http and https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore.
2. You can always use both of them. `AddAspNetCoreInstrumentation` is instrumenting inbound HTTP connections and `AddHttpClientInstrumentation` is instrumenting outbound HTTP connections.

**Comment by candrewtemenoscom** [comment]
Thank you for your info. The locations of the 2 documents are not easily discoverable from google and Microsoft doc. I have another question regarding the ActivitySource concept. In my sample project, the WeatherForecastController, I had the following code in the Get.

var activitySource = new ActivitySource("MyDataService");
var activityListener = new ActivityListener
            {
                ShouldListenTo = s => true,
                SampleUsingParentId = (ref ActivityCreationOptions<string> activityOptions) => ActivitySamplingResult.AllData,
                Sample = (ref ActivityCreationOptions<ActivityContext> activityOptions) => ActivitySamplingResult.AllData
            };
            ActivitySource.AddActivityListener(activityListener);
using var activity = activitySource.StartActivity("WeatherGet");
activity?.SetTag("testtag", "test");

However, in the output, I cannot see the "testtag" was added, and the activitySource name is OpenTelemetry.Instrumentation.AspNetCore instead of "MyDataService". May I know if my concept on how to use activitySource and activity is wrong?

**Comment by pellared** [comment]
This is another issue (take look at the examples and notice `AddSource()` method usage). Closing.
