### ISSUE TITLE
Update the default explicit histogram buckets to meet with the latest spec

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#3687]
The spec is updated https://github.com/open-telemetry/opentelemetry-specification/pull/2770, need to adjust the SDK behavior accordingly and update the docs.

**Comment by schoder-moreno** [comment]
@reyang  I'll grab this one if no one is working on it! :)

**Comment by reyang** [comment]
@schoder-moreno Cool! I've assigned this issue to you 👍
