### ISSUE TITLE
FormatException is thrown when an invalid env var value is set

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet#3690]
According the [OTel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/sdk-environment-variables.md?plain=1#L24):

> For variables accepting an enum value, if the user provides a value the SDK does not recognize, the SDK MUST generate a warning and gracefully ignore the setting.

This is not what is done in multiple places like [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/74412f0b1956d7afd62796753a2989314f808e0b/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L78). 

Moreover, because of this, it won't be easy to set defaults for these values in .NET Automatic Instrumentation. 

Can/do we want to address this? Won't it be seen as a breaking change?

Reference: https://github.com/open-telemetry/opentelemetry-specification/pull/2766

CC @reyang @cijothomas @CodeBlanch

**Comment by reyang** [comment]
> This is not what is done in multiple places like [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/74412f0b1956d7afd62796753a2989314f808e0b/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporter).

The link is broken?
 
> Moreover, because of this, it won't be easy to set defaults for these values in .NET Automatic Instrumentation.
> 
> Can/do we want to address this? Won't it be seen as a breaking change?

This looks like an implementation bug to me. Guess the fix should be swallow the exception and fallback to a default value. Doesn't sound like a breaking change.

**Comment by evanm-msft** [comment]
I see in the example code you linked to @pellared, the `Protocol` property has a default value (OtlpExportProtocol.Grpc):

`
public OtlpExportProtocol Protocol { get; set; } = DefaultOtlpExportProtocol;
`

Based on @reyang's comment to swallow the exception and fallback to a default value would mean we can essentially remove the else block where the FormatException is thrown, correct? Thus, the code would attempt to parse the proper protocol, and if it can't, the fallback value will be that default value of OtlpExportProtocol.Grpc.

I'm new to the project and if my understanding is incorrect, please let me know. If my understanding is correct, I can work on the fix. Thanks!

**Comment by evanm-msft** [comment]
@pellared I've been looking through the code and it looks like this issue has been handled in the following PRs: 

- https://github.com/open-telemetry/opentelemetry-dotnet/pull/3720
- https://github.com/open-telemetry/opentelemetry-dotnet/pull/3760

I've done a more thorough search for any remaining clean-up that may be needed and I am not finding anything. It feels safe to close this issue.

**Comment by pellared** [comment]
@moonbox3 Reopening; see:
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/39283c7327435b1d3ca9702387363030226b45a6/src/OpenTelemetry/Internal/ConfigurationExtensions.cs#L71
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/39283c7327435b1d3ca9702387363030226b45a6/src/OpenTelemetry/Internal/ConfigurationExtensions.cs#L90

Also the docs are not updated (find: `FormatException`)

There are even some tests which checks if `FormatException` is thrown.

**Comment by TimothyMothra** [comment]
Hi, I'm interested in working on this. 
Seems pretty straightforward, I found the tests and the related docs.
