### ISSUE TITLE
Why customized metrics not collected using OpenTelemetry.Exporter.Prometheus.AspnetCore ( 1.4.0-alpha.2 )

### ISSUE THREAD

**Issue by FantasticGithubUser** [open-telemetry/opentelemetry-dotnet#3693]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).

I'm trying to export the existing Metrics in another project which is referenced by the asp net core web API project. 
Here is my configuration:
![image](https://user-images.githubusercontent.com/37826451/191895243-4bf25d8b-4995-4e75-abef-ea65096d46ab.png)
The meter "requestMeter" works fine and it stays in the ActionFilter in the web API project.
But the other one is not ( which stays in the referenced project, meter created inside that project using the passed meter name ).
When I get the counter, I can see the counter's Enabled property is false, which means it's not listened to by the exporter.

Please help me why this will happen.

**Comment by cijothomas** [comment]
Please share a minimal repro describing the issue. Its hard to say anything without seeing a repro.

**Comment by FantasticGithubUser** [comment]
Hi @cijothomas , thanks for your feedback. I think the actual question I want to ask is:
Can the AddMeter correctly detect all the meters with the right name, no matter when or where the meter is really created?
Here, in my problem, I registered the configuration["RedisConfiguration:MeterName"] with the AddMeter method.
And later on, I passed the configuration to another project ( referenced by the current project ) and create the meter there.

**Comment by FantasticGithubUser** [comment]
Like, I passed the meterName into another project: 
![image](https://user-images.githubusercontent.com/37826451/199939143-656f6c31-ca46-4bb8-b6ba-a0252fcfa774.png)

And the meter is not created unless there is a request comes in.

**Comment by FantasticGithubUser** [comment]
And then, 
![image](https://user-images.githubusercontent.com/37826451/199939475-e6d478a4-b2de-4cfd-8c27-2b4459d1a065.png)
When we need to log the times the Redis got visited, we'll get the counter from that meter and stash that for later use.

**Comment by FantasticGithubUser** [comment]
When it's run, 
![image](https://user-images.githubusercontent.com/37826451/199941769-412e4db3-5174-451f-9c9e-5a54ffe6be59.png)
the Enabled is not set to true, which I think, means no Listener is currently listening on it, so it'll not be exported to Prometheus.

**Comment by cijothomas** [comment]
> Can the AddMeter correctly detect all the meters with the right name, no matter when or where the meter is really created?

Yes.

**Comment by FantasticGithubUser** [comment]
I tried another way to do this:
I`using SpyfallApi;
using SpyfallApi.Controllers;
using SpyfallApi.Hubs;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

var corsPolicy = "myCorsPolicy";

builder.Services.AddCors(options =>
{
	options.AddPolicy(name: corsPolicy, policy =>
	{
		policy.SetIsOriginAllowed(origin => true)
		.AllowAnyHeader()
		.AllowCredentials();
	});
});

builder.Services.ConfigSecurity(builder.Configuration);
builder.Services.ConfigSwagger(builder.Configuration);
builder.Services.ConfigSignalR(builder.Configuration);
builder.Services.ConfigRedis(builder.Configuration);
builder.Services.ConfigServices(builder.Configuration);
builder.Services.ConfigTelemetry(builder.Configuration);

builder.Services.AddControllers( option =>
{
	option.Filters.Add<AsyncActionFilter>();
});
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
	app.UseSwagger();
	app.UseSwaggerUI();
}

app.UseCors(corsPolicy);

app.UseOpenTelemetryPrometheusScrapingEndpoint(context =>
	context.Request.Path == builder.Configuration["Monitor:PathForScrap"]
);

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.MapHub<SpyFallHub>("/spyfallhub");
app.MapHub<ChatHub>("/chathub");

app.Run();`

Above is the config codes,

**Comment by FantasticGithubUser** [comment]
![Uploading image.png…]()
I configure Telemetry like this.

**Comment by FantasticGithubUser** [comment]
![Uploading Capture.PNG…]()

**Comment by FantasticGithubUser** [comment]
![Uploading Capture2.PNG…]()

**Comment by FantasticGithubUser** [comment]
Then I configure the Telemetry like this:
`services.AddOpenTelemetryMetrics(builder =>
			{
				builder.AddPrometheusExporter(options =>
			   {
				   options.ScrapeResponseCacheDurationMilliseconds = int.Parse(configuration["Monitor:CacheIntervalForScrap"]);
				   options.ScrapeEndpointPath = configuration["Monitor:PathForScrap"];
			   })
				.AddMeter(configuration["RedisConfiguration:MeterName"])
				.AddMeter("requestMeter")
				.AddMeter("testMeter");
			});`

**Comment by FantasticGithubUser** [comment]
But when I try to configure Redis the same way and test the Meter named "testMeter", I got the same problem.

**Comment by FantasticGithubUser** [comment]
The counter is still not enabled.

`var redisConfig = configuration.GetSection("RedisConfiguration");
			var timeout = TimeSpan.FromSeconds(int.Parse(redisConfig["Timeout"]));

			RedisContext.Initialize(redisConfig["ConnectionString"], int.Parse(redisConfig["DataDb"]), int.Parse(redisConfig
				["LockDb"]), redisConfig["MeterName"], timeout);

			var meter = new Meter("testMeter");
			var counter = meter.CreateCounter<long>("counter");
			counter.Add(10);`

**Comment by FantasticGithubUser** [comment]
Based on your feedback, It should have the Exporter listen to it. But it's not.

**Comment by FantasticGithubUser** [comment]
I believe there must exist some issues here.
![image](https://user-images.githubusercontent.com/37826451/200408349-1485a78e-71fb-4d77-9554-ce834900678f.png)
The same code works in UT but can not run in a normal Controller. ( here the activity will get null due to no listener )

**Comment by FantasticGithubUser** [comment]
> Hi, @cijothomas This kind of problem has troubled me for many days. I believe there must exist some issues here, due to both Metric and Trace can not get a proper Listener from OpenTelemetry. ![image](https://user-images.githubusercontent.com/37826451/200408349-1485a78e-71fb-4d77-9554-ce834900678f.png) The same code works in UT but can not run in a normal Controller. ( here the activity will get null due to no listener )

I think it's proper to add another BUG label for this question.

**Comment by cijothomas** [comment]
Its hard to say anything, without a *minimal* repro app. There are example apps in this repo - you can start with that (as-is) and confirm it is working. And then add your custom Meter, and see if works. If not share that minimal repro app.

**Comment by FantasticGithubUser** [comment]
Finally found the issue: The Meter.CreateCounter<long>( ) can not take a counter name with special characters ( in my test, it's [ , ] and space ). This caused the listener failed to listen on that. ( not sure why ).

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-naming-rule
