### ISSUE TITLE
AddApplicationInsight and AddOpenTelemetry

### ISSUE THREAD

**Issue by candrewtemenoscom** [open-telemetry/opentelemetry-dotnet#3712]
I have 2 questions.

1. I have the following code to set the activity source name in my openTelemetry trace.

services.AddOpenTelemetryTracing(providerBuilder =>
            {
                providerBuilder
                    .AddSource("AnalyticsApplication")                    .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("AnalyticsDataService"))
                    .AddHttpClientInstrumentation()
                    .AddAspNetCoreInstrumentation(
                        options =>
                        {
                            options.Enrich = Enrich;
                            options.RecordException = true;
                        }
                    )
                    .AddSqlClientInstrumentation()
                    .AddConsoleExporter();}

However, I could not see the Activity.ActivitySourceName = "AnalyticsApplication" in any of the traces. But it only shows Activity.ActivitySourceName: OpenTelemetry.Instrumentation.AspNetCore. Why is that?

2. When I AddApplicationInsight and AddOpenTelemetry together in my startup.cs, I found the activitySourceName will become OpenTelemetry.Instrumentation.Http.HttpClient. If I do not addApplicationInsight, the activitySourceName will be OpenTelemetry.Instrumentation.AspNetCore. Is it there is some of conflict between AddApplicationInsight and AddOpenTelemetry?

![image](https://user-images.githubusercontent.com/6600394/193158721-962b5eed-f833-409d-a596-feb5e80967f9.png)

**Comment by vishweshbankwar** [comment]
@candrewtemenoscom 

For Question-1: Could you confirm if you are creating any activities using `AnalyticsApplication` ActivitySource. ActivitySource denotes the source creating the activity.

For Question-2: ` I found the activitySourceName will become OpenTelemetry.Instrumentation.Http.HttpClient. If I do not addApplicationInsight, the activitySourceName will be OpenTelemetry.Instrumentation.AspNetCore`  ---> This sounds odd. In general you would not need to add both OpenTelemetry and ApplicationInsights. Is there a particular reason you are doing that?

**Comment by candrewtemenoscom** [comment]
1. No I did not create any activity with AnalyticsApplication. Then, how can I change all the activity source to "AnalyticsApplication"?
2. I had both AddApplicationInsight and AddOpenTelemetryTracing because I want to use AddApplicationInsight to be able to allow Azure Monitor to store the metrics, logs and traces. This is a preparation step. If the application is not hosted in Azure, there is no harm done right? I used AddOpenTelemetryTracing to allow the application to export the traces to other collectors. Does it mean the AddApplicationInsight and AddOpenTelemetryTracing are mutually exclusive? You can either use AddApplicationInsight or AddOpenTelemetryTracing but not both.
