### ISSUE TITLE
Prometheus Exporter HttpListener is unreliable on non-Windows OSes

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet#3728]
This issue was found when I was taking another look at the unstable integration tests for Prometheus Exporter (HttpListener) in OTel .NET AutoInstrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1363

It occurs that there is a bug that the `HttpListener` can crash when the HTTP requests are sent before it is fully operational. The issue was already reported and closed without a fix: https://github.com/dotnet/runtime/issues/28658.

I suggest that at minimum the docs should say that the Prometheus Exporter HttpListener uses an unmaintained legacy .NET component and it should not be used in production. For this reason, I also propose to move its source code to contrib repo or even remove it completely. One can always use OTLP exporter + OTel collector with Prometheus exporter for debugging. This is our default "dev env setup" in OTel .NET AutoInstrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/dev/otel-config.yaml

CC @reyang @Kielek

**Comment by reyang** [comment]
> I suggest that at minimum the docs should say that the Prometheus Exporter HttpListener uses an unmaintained legacy .NET component and it should not be used in production. For this reason, I also propose to move its source code to contrib repo or even remove it completely. One can always use OTLP exporter + OTel collector with Prometheus exporter for debugging. This is our default "dev env setup" in OTel .NET AutoInstrumentation: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/dev/otel-config.yaml

+1 on clarifying that Prometheus Exporter HttpListener  is currently a dev-inner-loop offering (until we can actually make it production ready) https://github.com/open-telemetry/opentelemetry-dotnet/pull/3694#pullrequestreview-1119318575. I don't have strong opinion whether it should move to the contrib repo or not.

**Comment by pellared** [comment]
Related https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1363#issuecomment-1268554357

**Comment by cijothomas** [comment]
I did some basic search to find if there is any official guidance about httplistener being prod-grade, now [this](https://github.com/dotnet/runtime/issues/28658#issuecomment-462062760) is a good reason to call out that this component is not meant for production scenarios.

**Comment by pellared** [comment]
A quick note before I go asleep and forget (the note may not be the best quality but better than nothing)

I think that an exception could be thrown from here: 

https://github.com/open-telemetry/opentelemetry-dotnet/blob/e826f9d2337978cdcd6d5f623216c40d17e5b649/src/OpenTelemetry.Exporter.Prometheus.HttpListener/PrometheusHttpListener.cs#L125-L127

which would lead to the `HttpListener` shutdown.
