### ISSUE TITLE
Are logs now stable to export to OLTP?

### ISSUE THREAD

**Issue by sashastri** [open-telemetry/opentelemetry-dotnet#3734]
" This package currently only supports exporting traces and metrics. Once the [OTLP log data model](https://github.com/open-telemetry/opentelemetry-proto#maturity-level) is deemed stable, the OTLP log exporter will be folded into this package. "

Has this changed and is log exporter now available, because here - [https://github.com/open-telemetry/opentelemetry-proto#maturity-level](https://github.com/open-telemetry/opentelemetry-proto#maturity-level) - I see that logs are marked stable?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/milestone/35 Please use this milestone to track it. 
OTLP LogExporter is not yet stable.
