### ISSUE TITLE
Rename Resource.labels to Resource.attributes

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#375]
Recent spec change calls into renaming labels to attributes. Also in proto file we allow the same data types for values. I believe the same must be allowed in API

**Comment by bruno-garcia** [comment]
More context in this PR: https://github.com/open-telemetry/opentelemetry-specification/pull/344

**Comment by lmolkova** [comment]
Hey, @bruno-garcia I accidentally did it along with validation changes. Sorry, I didn't know we have issue for it. Will send PR on Monday

**Comment by bruno-garcia** [comment]
@lmolkova Little race condition. Just thought a string replace was something I could fit on a weekend to do some work here ;)

I've opened the PR already. if it's going to conflict, feel free to close it and unassing me here.

**Comment by lmolkova** [comment]
no problem :) it happens. I'll have a look at your PR and will do validation on top of it.
