### ISSUE TITLE
Missing Activity in Exporter class .NET core 3.1

### ISSUE THREAD

**Issue by kicaj29** [open-telemetry/opentelemetry-dotnet#3754]
# Question

I have created a simple `AuditExporter`  which inherits form `BaseExporter<Activity>` .
It is rest api service so when a request comes I create my own activity by calling `ActivitySource.StartActivity`.

When I run it locally on Win10 then this custom activity is available in method `public override ExportResult Export(in Batch<Activity> batch)` in the exporter class - it works fine.

When I run it on windows container `dotnet/sdk:3.1` then this activity is missing in the exporter class. I have no idea why.

What could be a reason of missing activities in the exporter class?

**Comment by cijothomas** [comment]
Please share a minimal repro along with a description of what is the expected behavior vs actual. Its hard to understand what is the issue, without more details.

**Comment by kicaj29** [comment]
We upgraded to .net 6 and will check if the problem occurs also there. You can close this ticket.
