### ISSUE TITLE
http data collection - align with the updated spec

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#376]
Make sure SDK collects properties according to the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-http.md

**Comment by lmolkova** [comment]
I believe this was done in https://github.com/open-telemetry/opentelemetry-dotnet/pull/358. What's missing?

**Comment by alexvaluyskiy** [comment]
I have aligned with the specification only for a http client. We have to do the dame for http server too.

**Comment by cijothomas** [comment]
This is addressed and merged. Closing.
