### ISSUE TITLE
Add OTLP/HTTP JSON trace exporter for .NET 

### ISSUE THREAD

**Issue by rui-wang-imprivata** [open-telemetry/opentelemetry-dotnet#3768]
# Question

Hi Team,

Looks like the current available protocols for OTLP exporters in .Net are grpc and http/protobuf.  According to open telemetry [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md), 
protocol could be one of: grpc, http/protobuf, http/json, is there a plan to add http/json implementation for .Net OTLP exporter?

Thanks

**Comment by YohanSciubukgian** [comment]
I'm also interested in the http/json format for its flexibility.
