### ISSUE TITLE
Reconcile http.status_code type

### ISSUE THREAD

**Issue by dnelson-relativity** [open-telemetry/opentelemetry-dotnet#3777]
As described in https://github.com/open-telemetry/opentelemetry-specification/issues/2855, the `http.status_code` type is inconsistent between Metrics and Traces. Opening this issue per discussion in the 2022-10-11 SIG as it is assumed that the type mismatch is unintentional and should be addressed pending the outcome of that issue.

**Comment by ddiaz-relativity** [comment]
🥇
