### ISSUE TITLE
Allow registering processor by type for logging retrieved by dependency injection.

### ISSUE THREAD

**Issue by vasililiev** [open-telemetry/opentelemetry-dotnet#3823]
# Feature Request

There's a discrepancy in the way processors are registered between tracing and logging.
When adding a processor for logging, it requires an instance. Whereas for tracing, registering a type is enough as the actual instance is supplied by the dependency container.

**Is your feature request related to a problem?**

Our telemetry processor rely on dependency injection to inject certain dependency. When registering OpenTelemetry it's not possible to resolve this dependency and pass it to the options.

**Describe the solution you'd like:**

Aligning the API for adding processor between logging and tracing.
```csharp
  loggingBuilder.AddOpenTelemetry(config =>
  {
      config.AddProcessor<MyProcessor>();
  });
```

**Describe alternatives you've considered.**

N/A
There are no alternatives

## Additional Context

N/A

**Comment by CodeBlanch** [comment]
We added `LoggerProviderBuilder` in `1.9.0` which gives logging the same parity w.r.t. dependency injection as metrics & tracing. This can now be achieved using `WithLogging` style or via `ConfigureOpenTelemetryLoggerProvider`.

* Using `OpenTelemetry.Extensions.Hosting`:

   ```csharp
   builder.Services.AddOpenTelemetry()
       .ConfigureResource(r => r.AddService(builder.Environment.ApplicationName))
       .WithLogging(logging => logging
           .AddProcessor<MyProcessor>());
   ```

* Using `OpenTelemetrySdk.Create` (1.10.0):

   ```csharp
   using var sdk = OpenTelemetrySdk.Create(builder => builder
       .WithLogging(logging => logging
           .AddProcessor<MyProcessor>()));
   ```

* Using `LoggerFactory.Create`:

```csharp
   using var loggerFactory = LoggerFactory.Create(builder =>
   {
       builder.Services.ConfigureOpenTelemetryLoggerProvider(logging => logging
           .AddProcessor<MyProcessor>());

       builder.AddOpenTelemetry();
   });
```
