### ISSUE TITLE
Expose the `IServiceCollection` on the `TracerProviderBuilder`

### ISSUE THREAD

**Issue by eben-roux** [open-telemetry/opentelemetry-dotnet#3844]
# Feature Request

Expose the `IServiceCollection` on the `TracerProviderBuilder`.

**Is your feature request related to a problem?**

I am implementing OpenTelemetry for my open-source service bus and I need to register some dependencies.  Since the `TracerProviderBuilder` does not expose the `IServiceCollection` I need to perform two calls to wire up everything:

```
// Add the source here, since I need a source.
// But I cannot register my dependencies :(
services.AddOpenTelemetryTracing(
    builder => builder
        .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("Shuttle.Access.Server"))
        .AddServiceBusSource()
        .AddJaegerExporter());

// Register the dependencies
services.AddServiceBusInstrumentation(builder =>
    {
        configuration.GetSection(OpenTelemetryOptions.SectionName).Bind(builder.Options);
    });
```

**Describe the solution you'd like:**
```
// Within my `AddServiceBusInstrumentation` I'd like to have access to the
// IServiceCollection in order to register any dependencies
services.AddOpenTelemetryTracing(
    builder => builder
        .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("Shuttle.Access.Server"))
        .AddServiceBusInstrumentation(serviceBusBuilder => {
            configuration.GetSection(OpenTelemetryOptions.SectionName).Bind(serviceBusBuilder.Options);
        })
        .AddJaegerExporter());
```

**Describe alternatives you've considered.**

I considered registering the source using a dependecy on `TracerProviderBuilder` when registering my options:

```
services.AddOptions<OpenTelemetryOptions>().Configure<TracerProviderBuilder>((options, tracerProviderBuilder) => {
    // Cannot resolve TracerProviderBuilder as it was never registered
});
```

However, since the `TracerProviderBuilder` isn't registered in the `IServiceCollection` it cannot be resolved.  I'm guessing it wouldn't make any sense to register `TracerProviderBuilder` since it would be too late in the process to add a source.

## Additional Context

The code in question may be viewed [here](https://github.com/Shuttle/Shuttle.Esb.OpenTelemetry/blob/master/Shuttle.Esb.OpenTelemetry/ServiceCollectionExtensions.cs).  As can be seen in my [OpenTelemetryBuilder](https://github.com/Shuttle/Shuttle.Esb.OpenTelemetry/blob/master/Shuttle.Esb.OpenTelemetry/OpenTelemetryBuilder.cs) class I expose the current `IServiceCollection` that is being used to build the dependencies/options.

**Comment by CodeBlanch** [comment]
@eben-roux What version are you using?

* If you want to try out the latest 1.4.0 beta, there should now be a [TracerProviderBuilder.ConfigureServices extension](https://github.com/open-telemetry/opentelemetry-dotnet/blob/399fbcfaab63dde05678dc2df65e2dbfe4181915/src/OpenTelemetry/Trace/Builder/TracerProviderBuilderExtensions.cs#L303-L313) you can use to do this. It should always work (going forward).

* For 1.3.1 you can try the [TracerProviderBuilder.GetServices extension](https://github.com/open-telemetry/opentelemetry-dotnet/blob/c9052ef7655b8c9b210500f48ac2a521acf63d66/src/OpenTelemetry.Extensions.Hosting/Trace/TracerProviderBuilderExtensions.cs#L107-L115). This only works when using the `services.AddOpenTelemetryTracing` extension but your code above has that so it might help you.

Going to close this but feel free to reopen if this doesn't work for you for some reason.
