### ISSUE TITLE
Counters with null tag values stay at value 1

### ISSUE THREAD

**Issue by aristotelos** [open-telemetry/opentelemetry-dotnet#3846]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using:

* `OpenTelemetry 1.4.0-beta.2`
* `OpenTelemetry.Exporter.Prometheus.AspNetCore 1.4.0-beta.2`

Runtime version:

* `net6.0`

## Symptom

Counters of `int` or `long` stay at the value of `1` forever if one of the values for the tags passed is `null`.

**What is the expected behavior?**

The counter should increase to `2` in the Prometheus scraping endpoint after two `Add` calls to the counter, even if one of the tag values are `null`. If tag values of `null` are not supported, I would expect that to be documented somewhere and a clear `ArgumentNullException` on calling `Add`.

**What is the actual behavior?**

The counter keeps the value `1` in the Prometheus scraping endpoint.

## Reproduce

```
        // This test passes correctly.
        [Fact]
        public void CounterWithTags()
        {
            var aggregatorStore = new AggregatorStore("test", AggregationType.LongSumIncomingDelta, AggregationTemporality.Cumulative, 1024, Metric.DefaultHistogramBounds);
            aggregatorStore.Update(1, new ReadOnlySpan<KeyValuePair<string, object>>(new[] {
                new KeyValuePair<string, object>("foo", "junk"),
                new KeyValuePair<string, object>("bar", "other"),
            }));
            aggregatorStore.Update(1, new ReadOnlySpan<KeyValuePair<string, object>>(new[] {
                new KeyValuePair<string, object>("foo", "junk"),
                new KeyValuePair<string, object>("bar", "other"),
            }));

            aggregatorStore.Snapshot();

            var metricPoints = new List<MetricPoint>();
            foreach (var metricPoint in aggregatorStore.GetMetricPoints())
            {
                metricPoints.Add(metricPoint);
            }

            Assert.Single(metricPoints);
            Assert.Equal(2, metricPoints[0].GetSumLong());
        }

        // This test fails. It should pass as well.
        [Fact]
        public void CounterWithNullTags()
        {
            var aggregatorStore = new AggregatorStore("test", AggregationType.LongSumIncomingDelta, AggregationTemporality.Cumulative, 1024, Metric.DefaultHistogramBounds);
            aggregatorStore.Update(1, new ReadOnlySpan<KeyValuePair<string, object>>(new[] {
                new KeyValuePair<string, object>("foo", "junk"),
                new KeyValuePair<string, object>("bar", null),
            }));
            aggregatorStore.Update(1, new ReadOnlySpan<KeyValuePair<string, object>>(new[] {
                new KeyValuePair<string, object>("foo", "junk"),
                new KeyValuePair<string, object>("bar", null),
            }));

            aggregatorStore.Snapshot();

            var metricPoints = new List<MetricPoint>();
            foreach (var metricPoint in aggregatorStore.GetMetricPoints())
            {
                metricPoints.Add(metricPoint);
            }

            Assert.Single(metricPoints);
            Assert.Equal(2, metricPoints[0].GetSumLong());
        }
```

**Comment by cijothomas** [comment]
`null` value behavior is undefined.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute

**Comment by aristotelos** [comment]
Ah. Didn't know that. In that case, shouldn't the API throw an `ArgumentNullException` when attempting to add `null` values for attributes?

**Comment by cijothomas** [comment]
Not really. None of the APIs can throw. At best, it can emit an internal log.

**Comment by aristotelos** [comment]
I agree that a failing metric should probably not throw. I tried to find out the problem with the suggestions at https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#self-diagnostics, but I could not see any error log line about this. So it was hard to find it out. Is there any way to read those internal logs?

I think in the end the .NET API should not allow `null` for the tag values.

**Comment by utpilla** [comment]
This issue does not exist starting 1.4.0 version of the SDK.
