### ISSUE TITLE
Nuget JaegerExporter reference missing TracerBuilderExtensions

### ISSUE THREAD

**Issue by keepgoing147** [open-telemetry/opentelemetry-dotnet#386]
Hi, 
I am trying to add [JaegerExporter](https://www.nuget.org/packages/OpenTelemetry.Exporter.Jaeger/0.2.0-alpha.100) thru Nuget, and I encountered an error:

![image](https://user-images.githubusercontent.com/4708600/70601456-03bc4e80-1c2d-11ea-920e-8d92b861090c.png)

But when I install [ZipkinExporter](https://www.nuget.org/packages/OpenTelemetry.Exporter.Zipkin/0.2.0-alpha.100), it works.

I found that in reference list: 
![image](https://user-images.githubusercontent.com/4708600/70601578-51d15200-1c2d-11ea-8e3e-074f58249f60.png)

Seems that JaegerExporter does that implement TracerBuilderExtensions like ZipkinExporter, so it cannot find a definition for `UseJaeger`.

Or I just missing configure something?

**Comment by lmolkova** [comment]
I believe this was addressed in https://github.com/open-telemetry/opentelemetry-dotnet/pull/347
which version of OTel you are using? Perhaps after we addressed it, we didn't ship a new nuget package.

Please try nightly build and check if addresses the issue: https://github.com/open-telemetry/opentelemetry-dotnet#nightly-builds

Also, if you absolutely have to install packages from nuget.org, you can still configure Jaeger without `Use` sugar

```csharp
var jaegerOptions = new JaegerExporterOptions()
{
    ServiceName = "jaeger-test",
    AgentHost = <jaeger server>
};
using (var tracerFactory = TracerFactory.Create(builder => builder
    .AddProcessorPipeline(c => c.SetExporter(new JaegerTraceExporter(jaegerOptions)))))
{
 ...
}
```

**Comment by keepgoing147** [comment]
Thanks for response, I'm using [OpenTelemetry 0.2.0-alpha.100](https://www.nuget.org/packages/OpenTelemetry) and [OpenTelemetry JaegerExporter 0.2.0-alpha.100](https://www.nuget.org/packages/OpenTelemetry.Exporter.Jaeger/0.2.0-alpha.100)

After configuring Jaeger without `Use` sugar, I was able to build and get trace data from my project, thanks!

**Comment by keepgoing147** [comment]
By the way, `UseJaeger` is supported in `0.2.0-alpha.137`

[OpenTelemetry 0.2.0-alpha.137](https://www.myget.org/feed/opentelemetry/package/nuget/OpenTelemetry/0.2.0-alpha.137)
[JaegerExporter 0.2.0-alpha.137](https://www.myget.org/feed/opentelemetry/package/nuget/OpenTelemetry.Exporter.Jaeger/0.2.0-alpha.137)
