### ISSUE TITLE
[Console Exporter] Partial output when Activity has a link without any tags due to NullReferenceException

### ISSUE THREAD

**Issue by spanglerco** [open-telemetry/opentelemetry-dotnet#3863]
# Bug Report

```xml
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0-beta.2" />
<TargetFramework>net6.0</TargetFramework>
```

## Symptom

With an `Activity` that includes an `ActivityLink` without any tags, the console exporter throws a `NullReferenceException` when stopping/disposing the `Activity`.

**What is the expected behavior?**

The console output shows all activity information including the "Resource associated with Activity".

**What is the actual behavior?**

The link is included in the output, but not the "Resource associated with Activity" afterwards. A `NullReferenceException` is thrown, which is caught by the SDK and included in the diagnostics log:

```txt
2022-11-03T15:44:00.6954123Z:Unknown error in SpanProcessor event '{0}': '{1}'.{OnExport}{System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenTelemetry.Exporter.ConsoleActivityExporter.Export(Batch`1& batch)
   at OpenTelemetry.SimpleExportProcessor`1.OnExport(T data)}
```

Visual Studio breaks for the exception by default, but execution can be resumed (this is configurable).

## Reproduce

```csharp
using System.Diagnostics;
using OpenTelemetry;
using OpenTelemetry.Trace;

var source = new ActivitySource("Testing");
using var tracerProvider = Sdk.CreateTracerProviderBuilder()
    .AddSource("Testing")
    .AddConsoleExporter()
    .Build();

ActivityContext context;
using (var first = source.StartActivity("first"))
{
    context = first!.Context;
}

var links = new[] { new ActivityLink(context) };
using var second = source.StartActivity(ActivityKind.Internal, links: links, name: "Second");
```

## Additional Context

The problem is in [ConsoleActivityExporter.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6c3beef649a43f6b995877d04891d764bc72995c/src/OpenTelemetry.Exporter.Console/ConsoleActivityExporter.cs#L119) where it has a `foreach` to enumerate the tags without first checking for `null`. In the same file, it looks like it may also have an issue with events that don't have any tags, but I haven't testing that case. The code should probably switch to using `activityLink.EnumerateTags()` (like in #3580).

**Comment by TimothyMothra** [comment]
I'm looking into this
