### ISSUE TITLE
System.TypeLoadException: 'Could not load type 'Microsoft.Extensions.DependencyInjection.TracerProviderBuilderServiceCollectionExtensions' from assembly 'OpenTelemetry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c'.'

### ISSUE THREAD

**Issue by Leela-SR** [open-telemetry/opentelemetry-dotnet#3866]
Hi,

Could you please let me know why I am getting this error?

System.TypeLoadException: 'Could not load type 'Microsoft.Extensions.DependencyInjection.TracerProviderBuilderServiceCollectionExtensions' from assembly 'OpenTelemetry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c'.'

**Comment by cijothomas** [comment]
You'll need to share a minimal repro or at the very least, share the versions of all OpenTelemetry packages to understand more.

**Comment by Leela-SR** [comment]
Hi,
Appreciate for getting back. We are trying to have tracing enabled for both OnPrem and Cloud using OpenTelemetry. Following are the OpenTelemetry packages used.

OpenTelemetry 1.4.0 -beta.2
OpenTelemetry.Api 1.3.1
OpenTelemetry.Exporter.Jaeger 1.3.1
OpenTelemetry.Extension.Hosting 1.0.0 rc9.8
OpenTelemetry.Instrumentation.AspNetCore 1.0.0- rc9.8
Opentelemetry.Contrib.Extensions.Awsxray 1.2.0
Opentelemetry.Exporter.Opentelemetryprotocol 1.4.0 beta-2

Thanks,
Leela

**Comment by pellared** [comment]
Check the dependencies of each package. For instance https://www.nuget.org/packages/OpenTelemetry/1.4.0-beta.2#dependencies-tab

**Comment by Leela-SR** [comment]
Issue Resolved. Many Thanks!!!

**Comment by pankajbirat** [comment]
@Leela-SR  how did you resolve this issue?
