### ISSUE TITLE
Could not load type 'Enumerator`1' from assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0'

### ISSUE THREAD

**Issue by QuangVinhTran** [open-telemetry/opentelemetry-dotnet#3872]
Currently, I'm using OpenTelemetry, OpenTelemetry.Exporter.Zipkin version 1.3.1  & OpenTelemetry.Instrumentation.Wcf version 1.0.0-rc.7 in my project .NET framework 4.8. I got the error :

System.TypeLoadException: Could not load type 'Enumerator`1' from assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at OpenTelemetry.Trace.ActivityHelperExtensions.GetTagValue(Activity activity, String tagName)
   at OpenTelemetry.Trace.ExceptionProcessor.OnEnd(Activity activity)
   at OpenTelemetry.CompositeProcessor`1.OnEnd(T data)
   at OpenTelemetry.Trace.TracerProviderSdk.<>c__DisplayClass8_0.<.ctor>b__1(Activity activity)
   at System.Diagnostics.SynchronizedList`1.EnumWithAction(Action`2 action, Object arg)
   at System.Diagnostics.ActivitySource.NotifyActivityStop(Activity activity)
   at System.Diagnostics.Activity.Stop()
   at System.Diagnostics.Activity.Dispose()

**Comment by pellared** [comment]
Could you list all references used in your project?

**Comment by QuangVinhTran** [comment]
<PackageReference Include="AutoMapper">
      <Version>10.1.1</Version>
    </PackageReference>
    <PackageReference Include="Iesi.Collections">
      <Version>4.0.4</Version>
    </PackageReference>
    <PackageReference Include="itext7">
      <Version>7.2.1</Version>
    </PackageReference>
    <PackageReference Include="log4net">
      <Version>2.0.14</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Win32.Registry">
      <Version>5.0.0</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.1</Version>
    </PackageReference>
    <PackageReference Include="NHibernate">
      <Version>5.3.11</Version>
    </PackageReference>
    <PackageReference Include="NHibernate.Validator">
      <Version>5.1.0</Version>
    </PackageReference>
    <PackageReference Include="Ninject">
      <Version>3.3.4</Version>
    </PackageReference>
    <PackageReference Include="Ninject.Extensions.Interception">
      <Version>3.3.5</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry">
      <Version>1.3.1</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Exporter.Zipkin">
      <Version>1.3.1</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient">
      <Version>1.0.0-rc9.6</Version>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Instrumentation.Wcf">
      <Version>1.0.0-rc.7</Version>
    </PackageReference>
    <PackageReference Include="System.Diagnostics.DiagnosticSource">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.AccessControl">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Algorithms">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Encoding">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Pkcs">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.X509Certificates">
      <Version>4.3.2</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Principal.Windows">
      <Version>5.0.0</Version>
    </PackageReference>
    <PackageReference Include="XMLDiffPatch">
      <Version>1.0.8.28</Version>
    </PackageReference>

**Comment by QuangVinhTran** [comment]
It seems that the method 'Enumerator' only existed in System.Diagnostics.DiagnosticSource version 7.0.0 instead

**Comment by Kielek** [comment]
OpenTelemetry.Instrumentation.SqlClient references indirectly DiagnosticSource 7.0.

Either downgrade OpenTelemetry.Instrumentation.SqlClient to 1.0.0-rc9.4.

Or upgrade DiagnosticSource to 7.0 together with OpenTelemetry package to 1.4.0-beta.x and other latest/beta/rc releases.

**Comment by QuangVinhTran** [comment]
Upgrading DiagnosticSource to 7.0 together with OpenTelemetry package to 1.4.0-beta.x and other latest/beta/rc releases seems not work because the last version of OpenTelemetry.Instrumentation.Wcf only support by OpenTelemetry  1.3.1.

**Comment by QuangVinhTran** [comment]
Let me try to downgrade OpenTelemetry.Instrumentation.SqlClient to 1.0.0-rc9.4 instead.

**Comment by QuangVinhTran** [comment]
downgrade OpenTelemetry.Instrumentation.SqlClient to 1.0.0-rc9.4 seems working now. Thanks for your help.
