### ISSUE TITLE
Log exporter time on netfx isn't very granular

### ISSUE THREAD

**Issue by cg110** [open-telemetry/opentelemetry-dotnet#3888]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):
* OpenTelemetry 1.3.1 (but same issue in 1.4)

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):
Net472

* Net472

## Symptom

Messages logged and exported with otpl logger don't have fine grained timestamps.

**What is the expected behavior?**

Log timestamps should allow sorting by time from the same machine/process, rather than all logs having similar timestamps.

**What is the actual behavior?**

Logs have the same timestamps, as netfx DateTime.UtcNow has a 15-16ms resolution (this was updated in net core by switching to GetSystemTimePreciseAsFileTime, I've a wrapper around it to produce higher res timestamps, but it's a definite pain point on netfx with sub-ms work)

If I could update the timestamp on logrecord in a processor that'd be fine, but right now LogRecord.Timestamp isn't publicly settable (and has no setter to reflect and use either)

I could reflect the datetime internal value but that feels unclean.

Note that activity handles this for start/end times (uses date time and a stopwatch, but that implementation worries me when the clock resyncs, I'd prefer to use the Precise time so override it in an activity listener.

## Reproduce

I don't have a repro to hand but logging on netfx shows the logs have the same timestamps making it hard to order logs by time.

## Additional Context

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/OpenTelemetryLogger.cs#L67

**Comment by cg110** [comment]
I thought I'd checked GitHub, I must have just been looking at source for 1.3.0.

That looks like I can override in 1.4.

Any eta for 1.4?  I assumed it was waiting on net 7, so guessing not long?

**Comment by cijothomas** [comment]
While you can override TimeStamp, I am keeping this issue open to see the SDK should take care of it automatically. 
(Activity API does handle this correctly for .NET FW., so it may be natural to handle w/o end users having to worry about it...)
