### ISSUE TITLE
The function UseOpenTelemetryPrometheusScrapingEndpoint throws System.TypeLoadException

### ISSUE THREAD

**Issue by rahulrai-in** [open-telemetry/opentelemetry-dotnet#3896]
# Bug Report

## Symptom

I created a Blazor server app using .NET 7 and referenced the following NuGet packages:

```
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0-beta.3" />
<PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.4.0-beta.3" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.4.0-beta.3" />
<PackageReference Include="OpenTelemetry.Exporter.Prometheus" Version="1.3.0-rc.2" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.9" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0-beta.3" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.9" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.9" />
```

I used the following code to add the instrumention:

```
builder.Services.AddOpenTelemetryMetrics(meterProviderBuilder =>
{
    meterProviderBuilder
        .SetResourceBuilder(resourceBuilder)
        // receive metrics from built-in sources
        .AddAspNetCoreInstrumentation()
        .AddHttpClientInstrumentation()
        // receive metrics from custom sources
        .AddMeter(GlobalData.SourceName)
        //// expose metrics in Prometheus exposition format
        .AddPrometheusExporter();
});
```

Finally, used the following function to create the `/metrics` endpoint:

`app.UseOpenTelemetryPrometheusScrapingEndpoint();`

When the function `UseOpenTelemetryPrometheusScrapingEndpoint` is executed, it throws the following exception:

```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.ServiceProviderExtensions' from assembly 'OpenTelemetry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c'.
  Source=OpenTelemetry.Exporter.Prometheus
  StackTrace:
   at Microsoft.AspNetCore.Builder.PrometheusExporterApplicationBuilderExtensions.UseOpenTelemetryPrometheusScrapingEndpoint(IApplicationBuilder app, MeterProvider meterProvider, Func`2 predicate, String path, Action`1 configureBranchedPipeline)
   at Microsoft.AspNetCore.Builder.PrometheusExporterApplicationBuilderExtensions.UseOpenTelemetryPrometheusScrapingEndpoint(IApplicationBuilder app)
   at Program.<Main>$(String[] args) in Program.cs:line 110
```

**Expected behavior**
The function invocation should not throw error and application should expose `/metrics` endpoint.

**Screenshots**
<img width="637" alt="image" src="https://user-images.githubusercontent.com/11886524/201451392-a1b2f173-02aa-4c0c-ba55-555f6e62d938.png">

**Runtime environment (please complete the following information):**

- OS: Windows 11 Pro
- .NET version: .NET 7

**Additional context**
Framework: Blazor server

## Reproduce

1. Create a Blazor server project.
2. Instrument the metrics and use the Prometheus exporter.
3. Invoke the UseOpenTelemetryPrometheusScrapingEndpoint function.

**Comment by rahulrai-in** [comment]
I was able to resolve this error by referencing the correct package, `OpenTelemetry.Exporter.Prometheus.AspNetCore`. 

It might be a good idea to add this information in the documentation.

**Comment by cijothomas** [comment]
> I was able to resolve this error by referencing the correct package, `OpenTelemetry.Exporter.Prometheus.AspNetCore`.
> 
> It might be a good idea to add this information in the documentation.

@utpilla to look at improving changelog wordings to better advice users about breaking changes like package renaming.

**Comment by cijothomas** [comment]
> (OpenTelemetry.Exporter.Prometheus.AspNetCore)Its not working with dot net core 3. any support for that.

Its not expected to. (None of the components are expected to work with .NET Core 3) https://github.com/open-telemetry/opentelemetry-dotnet#supported-net-versions

Please use a separate issue for further questions, if any.

**Comment by HarshalRajkotia** [comment]
still facing issue even though using latest version "A PrometheusExporter could not be found configured on the provided MeterProvider"
