### ISSUE TITLE
[SqlClient] Optimize diagnostic source event subscription

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#3898]
For SqlClient DiagnosticSourceListener, we are currently subscribing to all the events including the unwanted ones. We should include isEnabledFilter while [subscribing](https://github.com/open-telemetry/opentelemetry-dotnet/blob/c7aefab687a8b6b6e9391eb8701fa6909c9321b1/src/OpenTelemetry.Instrumentation.SqlClient/SqlClientInstrumentation.cs#L43) so that we only get notified for the events we are interested in. This will also prevent generation of unwanted events.

**Comment by hgaol** [comment]
Hi @vishweshbankwar , I want to have a try!
