### ISSUE TITLE
Is it possible to ignore/exclude paths from being sent to Jaeger

### ISSUE THREAD

**Issue by joacar** [open-telemetry/opentelemetry-dotnet#3904]
# Question

I'm using the packages Jaeger and OpenTracing.Contrib.NetCore to send data to Jaeger from an ASP.NET Core application. Now I'm looking into moving to OpenTelemetry and I got it working running in Docker. 

Previously I've been excluding calls to swagger, metrics, health checks and a few others not to clutter the Jaeger UI and making it harder than it is finding stuff. 

So my question is, is this functionality available in OpenTelemetry.Exporter.Jaeger 1.4.0-beta.3? 

Another question regarding the exporter. There was many failed calls in Jaeger to `http://localhost:4317/opentelemetry.proto.collector.trace.v1.TraceService/Export` and it took some time to find that it was controlled by the `OTEL_EXPORTER_OTLP_ENDPOINT=jaeger` environment variable. What data is sent over this gRPC endpoint? The spans where already visible correctly even before I changed above and got rid of the error.

Thirdly, probably wrong repository, is that using the ResourceBuilder to override the `service.name` doesn't work when using the default. Most likely because it is already added using the value from `IHostEnvironment.ApplicationName` which defaults to the assembly name.

Thanks

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).

**Comment by a-pedroso** [comment]
Hello @joacar!
Regarding your 1st question, I manage to filter those requests using an extension method with a filter from OpenTelemetry.Instrumentation.AspNetCore. 

```
private static TracerProviderBuilder AddAspNetCoreInstrumentationExtension(this TracerProviderBuilder builder)
    {
        return builder.AddAspNetCoreInstrumentation((options) =>
        {
            // https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore#filter
            // condition for allowable requests -> does not collect telemetry about the request if the Filter returns false or throws exception
            options.Filter = (httpContext) =>
            {
                bool isMetricsOrHealth = ValidateIsMetricsOrHealthRequest(httpContext.Request.Path);
                return !isMetricsOrHealth;
            };
        });

        static bool ValidateIsMetricsOrHealthRequest(PathString path) =>
            path.HasValue &&
            (path.Value.StartsWith("/metrics", StringComparison.InvariantCultureIgnoreCase) ||
             path.Value.StartsWith("/health", StringComparison.InvariantCultureIgnoreCase));
    }
```
usage:
```
        services.AddOpenTelemetryTracing(tracing =>
            tracing
                .SetResourceBuilder(serviceResource)
                .AddAspNetCoreInstrumentationExtension()
                .AddOtlpExporter(o =>
                {
                    o.Endpoint = new Uri(otlpExporterUrl);
                }));
```

The other 2 questions unfortunately I don't have an answer.
Cheers

**Comment by joacar** [comment]
Many thanks @a-pedroso! Works like a charm. The other questions seem to be issues with running the Docker compose from VS in that it doesn't take the latest binaries upon restart. Building the solution prior to launching it seem to have the desired affect.

## Setup
```
services.AddOpenTelemetryMetrics(metrics =>
        {
            metrics
                .AddAspNetCoreInstrumentation()
                .AddHttpClientInstrumentation()
                .AddPrometheusExporter();
        });

        services.AddOpenTelemetryTracing(tracing =>
        {
            tracing
                .AddJaegerExporter()
                .AddAspNetCoreInstrumentation(options => options.Filter = AspNetCoreRequestFilter)
                .AddHttpClientInstrumentation();
        });

        static bool AspNetCoreRequestFilter(HttpContext context)
        {
            var path = context.Request.Path;
            var shouldFilter = path.HasValue && (
                path.StartsWithSegments("/metrics", StringComparison.InvariantCultureIgnoreCase) ||
                path.StartsWithSegments("/health", StringComparison.InvariantCultureIgnoreCase)
            );
            // True means it should be collected and False filtered out
            // hence we need to negate here.
            return !shouldFilter;
        }
```

## Docker
For those interested, the Docker compose is as follows (omitted standard settings for brevity).
```
 app:
    environment:
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_SERVICE_NAME=<app_name>
jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686  # UI
      - 5778:5778      # Collect port
      - 14268:14268  # Traces API
    environment:
      - COLLECTOR_OTLP_ENABLED=true
```
I believe that the `OTEL_EXPORTER_OTLP_ENDPOINT` isn't needed when using `AddJaegerExporter`. What is the difference between `AddOtlpExporter` vs `AddJaegerExporter` since both seem to work?

**Comment by a-pedroso** [comment]
Anytime @joacar 👍 
Regarding your last question I believe this link will answer that one and other following questions you might have -> https://www.meziantou.net/monitoring-a-dotnet-application-using-opentelemetry.htm
Cheers
