### ISSUE TITLE
Implement metric aggregators

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#391]
Parent: #316
This issue is to track creation of all aggregators as required by spec.
Counter aggregator for counter instruments - basic implementation already done as part of SDK
Gauge aggregator for gauge instruments - basic implementation already done as part of SDK
MinMaxSumCount aggregator for measure instruments
Sketch aggregator for measure instruments
Histogram aggregator for measure instruments
Exact aggregator for measure instruments - basic implementation already done as part of SDK

The question of how aggregators are associated with instruments and their configuration is to be tracked separately.

**Comment by czs1993** [comment]
Are there any examples of Metrics（Counter、Gauge、Histogram、） usage in the new interface ？

**Comment by cijothomas** [comment]
The new API follows the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-metrics-user.md

The Metrics SDK is WIP, once we have fully working SDK ready, there will be examples on usage.

**Comment by czs1993** [comment]
@cijothomas  Thanks.
When I use the new metrics sdk to aggregator metric under the multiple thread will throw exceptions :"The key already existed in the dictionary".and the counter sum result is smaller than the actual value.(the old stats sdk also have the same problem)

**Comment by cijothomas** [comment]
Yes the aggregator is a quick and dirty implementation. I am submitting a PR with actual thread safe implementation tomorrow.
Will check key issue - it may have something to do with LabelSet being used as the key, instead of a string.

**Comment by czs1993** [comment]
@cijothomas  Thanks
When I use the thread safe of Counter aggregator under the multiple thread. the program will still throw an exception:' The key already existed in the dictionary" .
the exception was throw when use  GetHandle(LabelSet labelset)
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Metrics/CounterSdk.cs

      public override CounterHandle<T> GetHandle(LabelSet labelset)
         {
             if (!this.counterHandles.TryGetValue(labelset, out var handle))
             {
                 handle = new CounterHandleSdk<T>();
                 this.counterHandles.Add(labelset, handle);
             }
             return handle;
        }

but  **counterHandles**  was   implementation of **ConcurrentDictionary** .it should be thread safe

`private readonly IDictionary<LabelSet, CounterHandleSdk<T>> counterHandles = new ConcurrentDictionary<LabelSet, CounterHandleSdk<T>>();`

If I change as follows,it will be ok.

```
private readonly ConcurrentDictionary<LabelSet, CounterHandleSdk<T>> counterHandles = new ConcurrentDictionary<LabelSet, CounterHandleSdk<T>>();
  public override GaugeHandle<T> GetHandle(LabelSet labelset)
     {
           return this.counterHandles.GetOrAdd(labelset, new CounterHandleSdk<T>());;
      }
```
 My english is not well ,I don't know if have speak clear. I'm looking forward to your work, because I'm going to use new Metrics SDK to collect application metrics.
 
My test program as follows

```
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using OpenTelemetry.Metrics;
using OpenTelemetry.Metrics.Configuration;
using OpenTelemetry.Metrics.Export;
using OpenTelemetry.Metrics.Implementation;
using OpenTelemetry.Trace;

namespace OTDemo
{
    public class Program
    {
        public static UngroupedBatcher processor = new UngroupedBatcher(new ConsoleExporter(), TimeSpan.FromSeconds(5));
        public static Meter meter = MeterFactory.Create(processor).GetMeter("meterCount") as MeterSdk;
        public static Counter<long> counter = meter.CreateInt64Counter("Thread_Safe_Test_Counter");
        public static List<KeyValuePair<string, string>> labels = new List<KeyValuePair<string, string>> { new KeyValuePair<string, string>("dim1", "value1") };
        public static int ThreadCompleteCount = 0;

        public static void Main(string[] args)
        {
            Test();
            // Wait for all threads to complete.
            Thread.Sleep(4000);
            (meter as MeterSdk).Collect();
            Console.ReadLine();
        }

        public static void Test()
        {
            try
            {
                int threadNumber = 20;
                int count = 0;
                Thread[] counterThreads = new Thread[threadNumber];
                for (var i = 0; i < threadNumber; i++)
                {
                    counterThreads[i] = new Thread(RecordMetric)
                    {
                        Name = "counter" + i,
                        IsBackground = true,
                    };
                    counterThreads[i].Start();   
                    count++;
                }
                Console.WriteLine($"Thread all Start，total:{count}");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
               
            }
        }

        public static void RecordMetric()
        {
            var threadId = Thread.CurrentThread.ManagedThreadId;
            try
            {
                int count = 0;
                for (var i = 0; i < 1000; i++)
                {
                    counter.Add(SpanContext.BlankLocal, 1, meter.GetLabelSet(labels));
                    count++;
                }

                Console.WriteLine($"Counter:{count}");
            }
            catch (Exception e)
            {
                Console.WriteLine($"threadID:{threadId} , message:{e.Message}");
            }
        }
    }

    public class ConsoleExporter : MetricExporter
    {

        public override Task<ExportResult> ExportAsync(List<Metric> metrics, CancellationToken cancellationToken)
        {
            var ct = DateTimeOffset.Now.ToUnixTimeMilliseconds();
            foreach (var metric in metrics)
            {
                Console.WriteLine($"#HELP {metric.MetricName} {metric.MetricDescription}");
                bool isFirst = true;
                Console.Write($"{metric.MetricName}");
                Console.Write(@"{");
                foreach (var label in metric.Labels)
                {
                    if (isFirst)
                    {
                        Console.Write($"{label.Key}=\"{label.Value}\"");
                    }
                    else
                    {
                        Console.Write($",{label.Key}=\"{label.Value}\"");

                    }
                }
                Console.Write(@"} ");
                Console.WriteLine($"{metric.Value} {ct}");

            }
            return Task.FromResult(ExportResult.Success);
        }
    }
}

```

**Comment by czs1993** [comment]
@cijothomas when will the new metrics implementation be works?

**Comment by cijothomas** [comment]
@czs1993 I just came back to work after parental leave and will pick up/ continue metric work. Thanks for being patient.!

**Comment by czs1993** [comment]
@cijothomas that great, looking forward to your work !
