### ISSUE TITLE
filter out logs based on ActivityTraceFlags

### ISSUE THREAD

**Issue by cataggar** [open-telemetry/opentelemetry-dotnet#3918]
I want to prevent logs from being sent to Azure.Monitor. Based on the [filtering processor example](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#filtering-processor), I created:

``` fsharp
open System.Diagnostics
open OpenTelemetry
open OpenTelemetry.Logs

/// Remove Heartbeat from Host.Results
type HeartbeatLogFilter() =
    inherit BaseProcessor<LogRecord>()
    override _.OnEnd log =
        if log.CategoryName = "Host.Results" then
            let fullName =
                log.StateValues |> Seq.tryPick(fun kv ->
                    if kv.Key = "FullName" then
                        Some kv.Value
                    else
                        None
                )
            if fullName = Some "Heartbeat" then
                log.TraceFlags <- log.TraceFlags &&& ~~~ ActivityTraceFlags.Recorded
```

It removes `ActivityTraceFlags.Recorded` from the `LogRecord.TraceFlags`. 

### Expected behavior

I was expecting the log records with `ActivityTraceFlags.Recorded` removed to not be exported to Azure Monitor.

### Actual behavior

The log records still end up in Azure Monitor.

**Comment by cijothomas** [comment]
TraceFlags are part of LogRecord, but they are not used to make any decision about export vs not export for logs. (They are used for traces)

As of today, there is not easy mechanism to filter logs based on the log content itself. You can write own FilteringProcessor wrapping the exporting processor, but that'll only work if the Exporter being target has public ctor. 

https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/extending-the-sdk

**Comment by cijothomas** [comment]
Tagging @CodeBlanch to see if we can offer a doc/feature to filter logs easily.

**Comment by cataggar** [comment]
> As of today, there is not easy mechanism to filter logs based on the log content itself. You can write own FilteringProcessor wrapping the exporting processor, but that'll only work if the Exporter being target has public ctor.

@cijothomas, I see a public constructor, but the class is internal. 

``` csharp
    internal class AzureMonitorLogExporter : BaseExporter<LogRecord>
    {
        private readonly ITransmitter _transmitter;
        private readonly string _instrumentationKey;
        private readonly ResourceParser _resourceParser;
        private readonly AzureMonitorPersistentStorage _persistentStorage;

        public AzureMonitorLogExporter(AzureMonitorExporterOptions options, TokenCredential credential = null) : this(new AzureMonitorTransmitter(options, credential))
        {
        }
```

https://github.com/Azure/azure-sdk-for-net/blob/c3fc45c5d59afcadca84e49e291d33ff439751a0/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorLogExporter.cs#L15-L24

**Comment by cataggar** [comment]
@cijothomas, the possibility of making `AzureMonitorLogExporter` public was rejected. There is still no way to filter logs easily that I'm aware of. Our logs of full of "Heartbeat"s that we do not need to be logging and I'd like to filter out. https://github.com/Azure/azure-functions-host/issues/4742#issuecomment-1506439353

**Comment by cijothomas** [comment]
Are you not able to filter the logs using https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/customizing-the-sdk#log-filtering ?

**Comment by cataggar** [comment]
@cijothomas, unfortunately no. That is limited to filtering on `log.CategoryName`. The logic is shown in the issue description. For the category `Host.Results`, I want to filter out any logs that have a `FullName` of `HeartBeat`.

**Comment by cijothomas** [comment]
> @cijothomas, unfortunately no. That is limited to filtering on `log.CategoryName`. The logic is shown in the issue description. For the category `Host.Results`, I want to filter out any logs that have a `FullName` of `Heartbeat`.

Could you ask the log producer to use a different category for Heartbeats?

**Comment by cataggar** [comment]
That is the category that Azure Functions to log all requests. We need the other requests to be logged, just not certain ones like Heartbeat. I'm pursuing that angle [here,](https://github.com/Azure/azure-functions-host/issues/4742#issuecomment-1509486865) but no traction on it yet. Back to this angle, why can't we filter `LogRecord` in an an exporter? Why limit it to its `CategoryName`?

**Comment by cijothomas** [comment]
https://github.com/dotnet/runtime/issues/82465 - @cataggar Please check this too. ILogger is considering more filtering capabilities, which might solve the problem for all, not just OTel.

**Comment by CodeBlanch** [comment]
I have thought about how the SDK might provide some filtering mechanism(s) which would work across the board, but at this time I don't have anything super great 🤣 I feel like this should really be an OTel-spec thing. What I was noodling was something along the lines of...

1. Add a predicate for filtering records before they are handed to the exporter/batch on `BaseExportProcessor<T>` (would work for tracing & logs):

```csharp
public abstract class BaseExportProcessor<T>
{
        public Predicate<T>? InclusionPredicate { get; set; }

        public override void OnEnd(T data)
        {
            if (this.InclusionPredicate?.Invoke(data) ?? true)
            {
                this.OnExport(data);
            }
        }
}
```

That part is pretty simple. The hard part is most of the existing extensions don't expose the processor so there isn't a chance to set the predicate. Exporters could be updated to expose something on the extension or their options or whatever, but we could do something like this to allow it to be set externally...

```csharp
        public static TracerProvider SetExportProcessorInclusionPredicate<TExporter>(
            this TracerProvider tracerProvider,
            Predicate<Activity> predicate)
            where TExporter : BaseExporter<Activity>
        {
            if (tracerProvider is TracerProviderSdk tracerProviderSdk
                && tracerProviderSdk.Processor != null)
            {
                SetExportProcessorInclusionPredicate(tracerProviderSdk.Processor, predicate, typeof(TExporter));
            }

            return tracerProvider;
        }

        public static OpenTelemetryLoggerProvider SetExportProcessorInclusionPredicate<TExporter>(
            this OpenTelemetryLoggerProvider loggerProvider,
            Predicate<LogRecord> predicate)
            where TExporter : BaseExporter<LogRecord>
        {
            if (loggerProvider.Processor != null)
            {
                SetExportProcessorInclusionPredicate(loggerProvider.Processor, predicate, typeof(TExporter));
            }

            return loggerProvider;
        }

        private static void SetExportProcessorInclusionPredicate<T>(BaseProcessor<T> processor, Predicate<T> predicate, Type exporterType)
             where T : class
        {
            if (processor is CompositeProcessor<T> compositeProcessor)
            {
                var current = compositeProcessor.Head;
                while (current != null)
                {
                    if (current.Value is BaseExportProcessor<T> exportProcessor
                        && exportProcessor.Exporter.GetType() == exporterType)
                    {
                        exportProcessor.InclusionPredicate += predicate;
                    }

                    current = current.Next;
                }
            }
            else if (processor is BaseExportProcessor<T> exportProcessor
                && exportProcessor.Exporter.GetType() == exporterType)
            {
                exportProcessor.InclusionPredicate += predicate;
            }
        }
```

Kind of nasty which is why I haven't pursued it. Also it doesn't solve for users with multiple exporters of the same type sending records to different places. I think that is important for logs. Could maybe change up that API so it returns all the found `BaseExportProcessor<T>`s registered and then we let the user sort them out? 🤷 

/cc @alanwest

**Comment by cataggar** [comment]
I'm closing this and will subscribe to https://github.com/dotnet/runtime/issues/82465.
