### ISSUE TITLE
OpenTelemetry.Exporter.Geneva 1.4.0-beta.4 requires OpenTelemetry (= 1.4.0-beta.2)

### ISSUE THREAD

**Issue by abatishchev** [open-telemetry/opentelemetry-dotnet#3922]
# Bug Report

Given

  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.4.0-beta.3" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0-beta.3" />
    <PackageReference Include="OpenTelemetry.Exporter.Geneva" Version="1.4.0-beta.4" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.9" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.9" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.9" />
  </ItemGroup>

results in a warning:

```
 warning NU1608: Detected package version outside of dependency constraint: OpenTelemetry.Exporter.Geneva 1.4.0-beta.4 requires OpenTelemetry (= 1.4.0-beta.2) but version OpenTelemetry 1.4.0-beta.3 was resolved.
```
Because [according to NuGet](https://www.nuget.org/packages/OpenTelemetry.Exporter.Geneva/1.4.0-beta.4#dependencies-body-tab) it has strict requirement on the certain version:

```xml
<dependencies>
  <group targetFramework=".NETFramework4.6.2">
    <dependency id="OpenTelemetry" version="[1.4.0-beta.2]" exclude="Build,Analyzers" />
  </group>
  <group targetFramework=".NETStandard2.0">
    <dependency id="OpenTelemetry" version="[1.4.0-beta.2]" exclude="Build,Analyzers" />
  </group>
</dependencies>
```

Runtime information (which doesn't matter):

```
<PropertyGroup>
  <TargetFramework>net7.0</TargetFramework>
  <Platform>AnyCPU</Platform>
</PropertyGroup>
```
**What is the expected behavior?**

Please either:

- Release a version of `OpenTelemetry.Exporter.Geneva` built against the latest `OpenTelemetry` (=1.4.0-beta4)
- Relax the version requirements to `>=`

**Comment by cijothomas** [comment]
OpenTelemetry.Exporter.Geneva is not part of this repo. Its part of contrib repo (https://github.com/open-telemetry/opentelemetry-dotnet-contrib). You may open issue there, or contact owners directly.
