### ISSUE TITLE
Update Jaeger tutorial to use OTLP Exporter

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#3925]
The current [Jaeger tutorial](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/getting-started-jaeger) is using JaegerExporter, it is time to move to OTLP Exporter and align with https://github.com/open-telemetry/opentelemetry-specification/pull/2858.

**Comment by hgaol** [comment]
Hi @reyang , I want to have a try!

**Comment by utpilla** [comment]
Fixed in #3940
