### ISSUE TITLE
Processors can't use Baggage to enrich server ASP.NET activities

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#3926]
# Bug Report

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and versions that you are
using (e.g. `OpenTelemetry 1.0.2`):

```
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0-beta.3" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.9" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.9" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.9" />
<PackageReference Include="OpenTelemetry" Version="1.4.0-beta.3" />
```

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can find this information from the `*.csproj` file):

NET 6 and .NET 7 

## Symptom

I'm trying to make use of baggage to populate a tag on all activities
```csharp
class EnrichingProcessor : BaseProcessor<Activity>
{
    public override void OnEnd(Activity activity)
    {
        if (Baggage.Current.GetBaggage().TryGetValue("foo", out var foo))
        { 
            activity.SetTag("foo", foo);
        }
    }
}
```

The processor is added to the pipeline and I see it's being invoked.
Baggage comes with incoming HTTP headers.

**What is the expected behavior?**

I expect server activity created for HTTP incoming request to end in scope of Baggage with "foo" in it and as a result of `EnrichingProcessor` work. 

**What is the actual behavior?**

Baggage is empty for server activities and is only populated for nested activities.

## Reproduce

[baggage_repro.zip](https://github.com/open-telemetry/opentelemetry-dotnet/files/10047747/baggage_repro.zip)

Hit it with  `PS > curl http://localhost:5050/foo/123 -Headers @{'baggage'='foo=42'}`
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/2347409/202866952-8bbc675c-7145-40f9-932c-acf47096f804.png">

## Additional Context

The baggage is cleaned up here: https://github.com/open-telemetry/opentelemetry-dotnet/blob/a4df1453e25462ed4acf8670bc019a8e25d4d67d/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L295-L298

only if context propagator is **not** `TraceContextPropagator` (which I don't really understand, since if it is TraceContextPropagator, then there will be no baggage parsing in the first place).

I suggest that baggage clean up (if it's needed at all) should happen after processor pipeline completes, otherwise enrichment from baggage in not possible in processors and it's quite unfortunate.

Also, OnStart callback can't be used either since Baggage is not parsed at this point.

**Comment by lmolkova** [comment]
The workaround (on .NET 7) is to use Activity.Baggage

```charp
class EnrichingProcessor : BaseProcessor<Activity>
{
    public override void OnEnd(Activity activity)
    {
        if (Baggage.Current.GetBaggage().TryGetValue("foo", out var foo) || (foo = activity.GetBaggageItem("foo")) != null)
        { 
            activity.SetTag("foo", foo);
        }
    }
}
```

and then it works like a charm since ASP.NET Core would put the baggage they parse on Activity.

The docs actually discourage the usage of `Activity.Baggage`

https://github.com/open-telemetry/opentelemetry-dotnet/blame/main/src/OpenTelemetry.Api/README.md#L107-L108 

But I think it would be beneficial if either OTel baggage was integrated with `Activity. Baggage` under the cover, so people don't need to ever use `Activty.Baggage` or there was more clear guidance on when and how to use which.

Ideally, there should not be two types.

**Comment by vishweshbankwar** [comment]
Duplicate https://github.com/open-telemetry/opentelemetry-dotnet/issues/2992
