### ISSUE TITLE
Documentation and examples for DistributedContext

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#394]
I suggest having basic examples of how to use distributed context in README (or we may split readme for tracing/distributed context/metrics/configuration/etc) similar to hat we have for tracing.

**Comment by SergeyKanzhelev** [comment]
@MikeGoldsmith do you want me to assign it to you?

**Comment by cijothomas** [comment]
There is no distributed context anymore. so  closing this as not applicable now.
