### ISSUE TITLE
AddHttpClientInstrumentation with configuration lamda fails inside TraceProviderBuilder.ConfigureBuilder

### ISSUE THREAD

**Issue by pardahlman** [open-telemetry/opentelemetry-dotnet#3942]
# Bug Report

List of [all OpenTelemetry NuGetpackages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using:

* `OpenTelemetry.Instrumentation.Http` 1.0.0-rc9.9

Runtime version:

* `net7.0`

## Symptom

When calling `AddHttpClientInstrumentation` with a configuration lamda (`Action<HttpClientInstrumentationOptions> configureHttpClientInstrumentationOptions`) inside of `traceProviderBuilder.ConfigureBuilder` the registration fails with the following exception:

```
System.NotSupportedException: Services cannot be configured after ServiceProvider has been created.
   at OpenTelemetry.Trace.TracerProviderBuilderBase.ConfigureServices(Action`1 configure)
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.ConfigureServices(TracerProviderBuilder tracerProviderBuilder, Action`1 configure)
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.AddHttpClientInstrumentation(TracerProviderBuilder builder, String name, Action`1 configureHttpClientInstrumentationOptions)
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.AddHttpClientInstrumentation(TracerProviderBuilder builder, Action`1 configureHttpClientInstrumentationOptions)
```

*Note 1*: This is not the case if called without any configuration lambda.
*Note 2*: The same behavior happens for `AddSqlClientInstrumentation(o => { })`

## Reproduce

https://github.com/pardahlman/otel-repro

```csharp
[Test]
public async Task Repro()
{
    var services = new ServiceCollection();
    services.ConfigureOpenTelemetryTracing(traceProviderBuilder => traceProviderBuilder.ConfigureBuilder(
        (serviceProvider, builder) =>
        {
            builder.AddHttpClientInstrumentation(o => {});
        }));
    services.AddOpenTelemetryTracing();
    await using var serviceProvider = services.BuildServiceProvider();
    Assert.DoesNotThrow(() => serviceProvider.GetRequiredService<TracerProvider>()); //Fails
}
```

# Context

The (internal) library configures OpenTelemtry (instrumentation, exporters and sampler) with sensible defaults that can be overridden. A `IServiceProvider` is required to resolve `IOptions<T>` to evaluate properties like `EnableHttpClientInstrumentation`.

**Comment by TimothyMothra** [comment]
similar issue to #3753.

Can you try the workaround suggested there?

**Comment by pardahlman** [comment]
Thanks for pointing me to that issue, it looks very much like the same problem. The workaround is feasible for us, thanks. Closing this issue.
