### ISSUE TITLE
Instrumentation Configuration through Environment Variables

### ISSUE THREAD

**Issue by logamanig** [open-telemetry/opentelemetry-dotnet#3952]
I would like to enable options.SetDbStatementForText to true to capture sql statements in traces which is turned off by default in the sdk. SDK has the instructions to enable it (https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.SqlClient/README.md#capturing-database-statements). Is it possible to add configure it through env var which will be handy to configure it through auto-instrumentation just like java without making changes into application source code?

the plugin option might be an option to implement but it does require making changes into application source code.

**Comment by CodeBlanch** [comment]
@logamanig FYI this should be more or less possible now in 1.4.0-rc.1 and forward.

Set up your host something like this:

```csharp
var appBuilder = WebApplication.CreateBuilder(args);

appBuilder.Services.Configure<SqlClientInstrumentationOptions>(
  appBuilder.Configuration.GetSection("OpenTelemetry:Sql"));

appBuilder.Services.AddOpenTelemetry()
    .WithTracing(builder => builder.AddSqlClientInstrumentation())
    .StartWithHost();
```

What that does is bind `SqlClientInstrumentationOptions` to the "OpenTelemetry:Sql" `IConfiguration` path. You can then use the standard syntax for setting that via an environment variable. IIRC that would be: `OPENTELEMETRY__SQL__SETDBSTATEMENTFORTEXT=true`. Notes: 1) The double underscore ("__") is not a typo! That is a requirement. 2) All caps make it work for both *nix & Windows.

/cc @alanwest
