### ISSUE TITLE
dispose tracerFactory cause dead lock

### ISSUE THREAD

**Issue by HongChenTW** [open-telemetry/opentelemetry-dotnet#397]
[OpenTelemetry 0.2.0-alpha.137](https://www.myget.org/feed/opentelemetry/package/nuget/OpenTelemetry/0.2.0-alpha.137)
[JaegerExporter 0.2.0-alpha.137](https://www.myget.org/feed/opentelemetry/package/nuget/OpenTelemetry.Exporter.Jaeger/0.2.0-alpha.137)

I was trying to add Jaeger Exporter at `OnActionExecuting` method:

```csharp
public override void OnActionExecuting(ActionExecutingContext filterContext) {
    startTime = DateTime.UtcNow;
    if (UserHelper.User!=null)
        UserHelper.TransactionId = Guid.NewGuid().ToString();

    var tracerFactory = TracerFactory.Create(
        builder => builder.UseJaeger(o =>
        {
            o.ServiceName = "Jaeger-test";
            o.AgentHost = "localhost";
            o.AgentPort = 6831;
        }));

    var tracer = tracerFactory.GetTracer("Jaeger-test");

    // Create a scoped span. It will end automatically when using statement ends
    using (tracer.StartActiveSpan(filterContext.HttpContext.Request.Url.ToString(),
            out var span))
        {
            ...
        }

    tracerFactory.Dispose();

    base.OnActionExecuting(filterContext);
}
```

I removed tracerFactory `using` for debug, and discovered that `tracerFactory.Dispose();` seems cause deadlock and website cannot be loaded after more than 1 hours:

![image](https://user-images.githubusercontent.com/4708600/70771680-ef06c480-1dac-11ea-88fc-fd5cad3faeb9.png)

But in Jaeger UI, I can see the trace:

![image](https://user-images.githubusercontent.com/4708600/70772216-d4354f80-1dae-11ea-8f69-2fa9c72e9e76.png)

When I remove `tracerFactory.Dispose();`, the website loaded successfully, but didn't export any trace to Jaeger.

**Comment by keepgoing147** [comment]
After comment out:

```csharp
//using (tracer.StartActiveSpan(filterContext.HttpContext.Request.Url.ToString(),
//        out var span))
//    {
//        ...
//    }
```

The website successfully loaded, but Jaeger UI still no trace on it.

**Comment by keepgoing147** [comment]
After trying at osx, it works as expected!

I test with 2 types of package version:

[OpenTelemetry 0.2.0-alpha.137](https://www.myget.org/feed/opentelemetry/package/nuget/OpenTelemetry/0.2.0-alpha.137)
[JaegerExporter 0.2.0-alpha.137](https://www.myget.org/feed/opentelemetry/package/nuget/OpenTelemetry.Exporter.Jaeger/0.2.0-alpha.137)

[OpenTelemetry 0.2.0-alpha.100](https://www.nuget.org/packages/OpenTelemetry/0.2.0-alpha.100)
[JaegerExporter 0.2.0-alpha.100](https://www.nuget.org/packages/OpenTelemetry.Exporter.Jaeger/0.2.0-alpha.100)

And both with different implement, it all works.
[Implement 1](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/samples/Exporters/TestJaeger.cs)
[Implement 2](https://github.com/open-telemetry/opentelemetry-dotnet/issues/386#issuecomment-564781318)

Not sure why it executed differently on windows.

**Comment by heldergregorio** [comment]
Hi,

Any news on this? I'm having the exact same problem on a ASP.NET application. Is there a workaround for this? I still haven't figure out how to flush the events without disposing the TracerFactory

**Comment by MikeGoldsmith** [comment]
I think this was meant to be fixed in the Jaeger Exporter - @CodeBlanch do you remember something related?

**Comment by CodeBlanch** [comment]
@heldergregorio The JaegerExporter in the current version on NuGet (alpha.179) has a bug that causes it to deadlock. If you switch over to the newer MyGet version (alpha.243 right now) it should be resolved.

The fix is more or less on this commit: https://github.com/open-telemetry/opentelemetry-dotnet/pull/486/commits/2978200a3791b857c483ecad470254652a9034e8

**Comment by MikeGoldsmith** [comment]
Thanks @CodeBlanch. Instructions for using the MyGet feed are in the README.

I'll close this issue now - please reopen if you have any trouble.
