### ISSUE TITLE
Prometheus exporter: counters should have _total suffix

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-dotnet#3973]
From the [Prometheus spec for sums](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#sums):

> Monotonic Sum metric points MUST have _total added as a suffix to the metric name.

The [current implementation](https://github.com/open-telemetry/opentelemetry-dotnet/blob/804c448d2e5a8d53405624aecd4f315261a2f379/src/OpenTelemetry.Exporter.Prometheus.HttpListener/Internal/PrometheusSerializerExt.cs#L37) does not add this suffix to the metric name.

**Comment by marcinjahn** [comment]
Currently, the Prometheus Exporter adds `_total` to counters.

From the specs:
> Exporters SHOULD provide a configuration option to disable the addition of _total suffixes.

**Comment by reyang** [comment]
Covered by #4753.

**Comment by benjamin-diekerns** [comment]
Also interested in this, I still don't see an option to disable this?
