### ISSUE TITLE
EnrichWithHttpRequest - Changes to Activity DisplayName gets overridden with route template/path in AspNetCoreInstrumentation

### ISSUE THREAD

**Issue by chandramouleswaran** [open-telemetry/opentelemetry-dotnet#3977]
# Bug Report

Here is a small snippet to repro the issue
```
.AddAspNetCoreInstrumentation(options =>
{
    const string incomingSpanName = "IncomingSpanName";
    options.EnrichWithHttpRequest = (activity, httpRequest) =>
    {
        if (httpRequest.Headers.TryGetValue(Header.ClientActionName, out StringValues clientActionHeaders))
        {
            var displayName = $"{serviceRole}.Incoming.{clientActionHeaders}";
            activity.AddTag(incomingSpanName, displayName);

            // Ideally this should be sufficient - however, OT ends up resetting this value to the action's route template
            activity.DisplayName = displayName;
        }
    };

    options.EnrichWithHttpResponse = (activity, response) =>
    {
        // Hack to get the value added to the tag to setup the display name
        var incomingSpan = activity.GetTagItem(incomingSpanName);
        if (incomingSpan != null)
        {
            activity.DisplayName = incomingSpan.ToString();
        }
    };
});
```

## Symptom
We need the ability to setup DisplayName of the activity as part of the request flow - it looks like OT ends up changing the DisplayName based on the route template somewhere along the request lifecycle.

**What is the expected behavior?**

What did you expect to see?
![image](https://user-images.githubusercontent.com/2020447/206045704-b7513924-66ec-40f3-b61c-757250d4e6c5.png)

**What is the actual behavior?**

What did you see instead?
![image](https://user-images.githubusercontent.com/2020447/206046120-04c7a38d-c0a8-4195-972c-641299f3478a.png)

## Reproduce

See code snippet above with repro.

Packages used while reproducing
OpenTelemetry 1.4.0-beta.3
OpenTelemetry.Api 1.4.0-beta.3
OpenTelemetry.Exporter.CredScan 2.0.12
OpenTelemetry.Extensions.Hosting 1.0.0-rc9.9
OpenTelemetry.Exporter.Zipkin 1.4.0-beta.3
OpenTelemetry.Exporter.Geneva 1.4.0-beta.5
OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.9
OpenTelemetry.Instrumentation.GrpcNetClient 1.0.0-rc9.9
OpenTelemetry.Instrumentation.Http 1.0.0-rc9.9
OpenTelemetry.Instrumentation.Process 1.0.0-alpha.2
OpenTelemetry.Instrumentation.Runtime 1.1.0-beta.1

Runtime version: net7.0

**Comment by cijothomas** [comment]
@vishweshbankwar Can you check this?

**Comment by vishweshbankwar** [comment]
it happens due to this https://github.com/open-telemetry/opentelemetry-dotnet/blob/bb0c381478a5d6b6a3dd52cc9990d3582e908767/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L338. This is done to comply with spec. We need to find the alternate way of not overriding the DisplayName if it was changed using `enrich` options.

**Comment by vishweshbankwar** [comment]
@chandramouleswaran - Could you try the following. Try setting the DisplayName using `EnrichWithHttpResponse` 

```csharp
.AddAspNetCoreInstrumentation(o =>
{
  o.EnrichWithHttpResponse = (activity, response) =>
  {
      if (response.HttpContext.Request.Headers.TryGetValue(Header.ClientActionName, out StringValues clientActionHeaders))
      {
          var displayName = $"{serviceRole}.Incoming.{clientActionHeaders}";

          // Ideally this should be sufficient - however, OT ends up resetting this value to the action's route template
          activity.DisplayName = displayName;
      }
  };
});
```

**Comment by utpilla** [comment]
@chandramouleswaran Does the above-mentioned suggestion work?

**Comment by vishweshbankwar** [comment]
@chandramouleswaran Closing this issue. please re-open if the above shared workaround does not work for you.
