### ISSUE TITLE
AddAspNetCoreInstrumentation does not output traces when behind Ocelot proxy

### ISSUE THREAD

**Issue by aristotelos** [open-telemetry/opentelemetry-dotnet#4007]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry):

* `OpenTelemetry.Exporter.Console 1.4.0-rc.1`
* `OpenTelemetry.Exporter.OpenTelemetryProtocol 1.4.0-rc.1`
* `OpenTelemetry.Exporter.Prometheus.AspNetCore 1.4.0-rc.1`
* `OpenTelemetry.Extensions.Hosting 1.4.0-rc.1`
* `OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.10`
* `OpenTelemetry.Instrumentation.Http 1.0.0-rc9.10`
* `OpenTelemetry.Instrumentation.SqlClient 1.0.0-rc9.10`

Runtime version:

* `net6.0`

## Symptom

Using Ocelot as an API gateway to downstream services, and using `AddAspNetCoreInstrumentation` in the downstream services, the HTTP requests going to those downstream services do not produce trace output. If we call the downstream services directly, traces are logged. (Tested with both console exporter and OTLP exporter.)

**What is the expected behavior?**

Traces should be logged also when using an API gateway in front.

**What is the actual behavior?**

Traces are only logged for non-forwarded requests.

## Reproduce

Using the following set-up code for OpenTelemetry in the downstream service:
```
services.AddOpenTelemetry()
                .WithMetrics(
                    (builder) =>
                    {
                        builder.AddAspNetCoreInstrumentation();
                        builder.AddHttpClientInstrumentation();
                        builder.AddPrometheusExporter();
                    }
                )
                .WithTracing(
                    (builder) =>
                    {
                        builder.AddHttpClientInstrumentation();
                        builder.AddAspNetCoreInstrumentation();
                        builder.AddSqlClientInstrumentation(
                            options => options.SetDbStatementForText = true);
                        builder.AddHotChocolateInstrumentation();
                        builder.AddOtlpExporter(options =>
                            configuration.GetSection("Tracing:OpenTelemetry").Bind(options)
                        );
                    }
                )
                .StartWithHost();
```

No OpenTelemetry is added to the API gateway service.

## Additional Context

Using the following Ocelot configuration:
```
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "api",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "SwaggerKey": "MyService"
    }
  ]
}
```
Where `api` is the name of the downstream service running with docker-compose.

**Comment by vishweshbankwar** [comment]
Does it repro if you use AlwaysOnSampler ?

**Comment by aristotelos** [comment]
> Does it repro if you use AlwaysOnSampler ?

That solves my issue indeed! I then get all traces that I was expecting.

Is it expected in this scenario to turn it on this way? Or is this a bug in the default parent based sampler? Because I am not exporting or instrumenting any traces from my Ocelot service.

I cannot find a lot of documentation about `AlwaysOnSampler` or on how to configure the sampler using `.SetSampler<AlwaysOnSampler>()`. Could you point me to a place where the different samplers are documented and where it is very clearly described what should be used when? I did find it in the [Java manual](https://opentelemetry.io/docs/instrumentation/java/manual/#sampler), but not in the [.NET manual](https://opentelemetry.io/docs/instrumentation/net/manual/).

**Comment by Kielek** [comment]
Samplers should be  common features across all language implementations, See https://github.com/open-telemetry/opentelemetry-specification/blob/5b6d22512ef72214f7cbd52747a1fbfe49f8121f/specification/trace/sdk.md?plain=1#L230

AspNetCore is always creating [Activities](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=net-7.0) for each request. If you are not enable listener for such activities it will be dropped. As default value for sampler is [parentbase(always_on)](https://github.com/open-telemetry/opentelemetry-specification/blob/5b6d22512ef72214f7cbd52747a1fbfe49f8121f/specification/trace/sdk.md?plain=1#L281-L284) all child activities are also dropped.

**Comment by aristotelos** [comment]
> Samplers should be common features across all language implementations, See https://github.com/open-telemetry/opentelemetry-specification/blob/5b6d22512ef72214f7cbd52747a1fbfe49f8121f/specification/trace/sdk.md?plain=1#L230
> 
> AspNetCore is always creating [Activities](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=net-7.0) for each request. If you are not enable listener for such activities it will be dropped. As default value for sampler is [parentbase(always_on)](https://github.com/open-telemetry/opentelemetry-specification/blob/5b6d22512ef72214f7cbd52747a1fbfe49f8121f/specification/trace/sdk.md?plain=1#L281-L284) all child activities are also dropped.

But how does this work for cross-service traces? If my Ocelot service exports traces to OpenTelemetry, it will not export spans for my downstream services and their database calls, right? So something should be sampled from my downstream services by default, isn't it?

**Comment by vishweshbankwar** [comment]
@aristotelos - check this out https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#parentbased

**Comment by aristotelos** [comment]
> @aristotelos - check this out https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#parentbased.

For me, this documentation does not make clear in which cases the traces are sampled and which ones not. I guess it should sample the root span, and anything local which does not have the sampled flag set? So in my case, the Ocelot service I expect to be remote (although it runs on the same host, it is a different process). Is that assumption correct? Does that mean that the parent based sampler should also sample my local spans because they have a remote parent? 

> I am guessing your upstream service Ocelot is sending traceparent header to your downstream services.

It should, but that shouldn't stop my downstream services from collecting and exporting traces, isn't it?

**Comment by alanwest** [comment]
> It should, but that shouldn't stop my downstream services from collecting and exporting traces, isn't it?

Yes, this would stop your downstream services from collecting and exporting traces if the span created by Ocelot was not sampled. When the downstream service creates its span the parent-based sampler asks "Do I have a parent? If so, was it sampled? If it was, then sample me too. If not, then do not sample me."

I suspect the span created by Ocelot does not get sampled. I am not familiar with Ocelot, but you will probably want to figure out how to configure tracing for Ocelot.

**Comment by aristotelos** [comment]
OK, I think I get it. So any ASP.NET Core-based API gateway will probably create parent spans for each request, and this will stop my downstream service spans from being sampled, because the default sampling strategy is to skip traces that have parents that were not sampled. In my case, I will anyways add OpenTelemetry instrumentation and an OpenTelemetry exporter to the API gateway, which solves the problem for me.
