### ISSUE TITLE
OTLP Exporter does not set trace_state field

### ISSUE THREAD

**Issue by zacharycmontoya** [open-telemetry/opentelemetry-dotnet#4010]
# Feature Request

**Is your feature request related to a problem?**

I don't have an urgent issue, but I would like the OTLP exporter to set the span's [trace_state](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L104) field, to have the complete data represented in the OTLP trace.

**Describe the solution you'd like:**

I would like the OTLP exporter to set the `TraceState` property when converting the `System.Diagnostics.Activity` object to its corresponding `OpenTelemetry.Proto.Trace.V1.Span` object.

**Describe alternatives you've considered.**

None. The OTLP exporter alone is responsible for exporting the Activity in the form of an OTLP span.

## Additional Context

I'm happy to submit a PR to implement this, but I wanted to know if there was a previous decision to omit this, or if this was just missed.

**Comment by cijothomas** [comment]
Tagging for consideration in 1.5

**Comment by cijothomas** [comment]
@Yun-Ting Could you check and see if you can take this?
