### ISSUE TITLE
MissingMethodException Boolean OpenTelemetry.Metrics.MetricPoint.HasMinMax() atttempting to write metrics to app insights

### ISSUE THREAD

**Issue by nickeeex** [open-telemetry/opentelemetry-dotnet#4012]
# Packages

OpenTelemetry 1.4.0-rc.1
OpenTelemetry.Extensions.AzureMonitor 1.0.0-beta.2
OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.10
OpenTelemetry.Instrumentation.Http 1.0.0-rc9.10
OpenTelemetry.Instrumentation.Runtime 1.1.0-beta.2
OpenTelemetry.Instrumentation.SqlClient 1.0.0-rc9.10

* Runtime
`net7.0`

## Symptom

Unable to log metrics to app insights with OpenTelemetry.Extensions.AzureMonitor 

```
OpenTelemetry-AzureMonitor-Exporter - EventId: [2], EventName: [WriteError], Message: [FailedToExport - System.MissingMethodException: Method not found: 'Boolean OpenTelemetry.Metrics.MetricPoint.HasMinMax()'.
   at Azure.Monitor.OpenTelemetry.Exporter.Models.MetricDataPoint..ctor(Metric metric, MetricPoint metricPoint)
   at Azure.Monitor.OpenTelemetry.Exporter.Models.MetricsData..ctor(Int32 version, Metric metric, MetricPoint metricPoint)
   at Azure.Monitor.OpenTelemetry.Exporter.Internals.MetricHelper.OtelToAzureMonitorMetrics(Batch`1 batch, String roleName, String roleInstance, String instrumentationKey)
   at Azure.Monitor.OpenTelemetry.Exporter.AzureMonitorMetricExporter.Export(Batch`1& batch)]
```
I've tried older version of the instrumentation libraries mentioned in here https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-monitor/app/opentelemetry-enable.md#instrumentation-libraries but got the same error 
Traces are sent correctly to App insights
OpenTelemetry-AzureMonitor-Exporter - EventId: [4], EventName: [WriteInformational], Message: [TransmissionSuccess - Successfully transmitted a batch of telemetry Items.]

**Comment by Kielek** [comment]
The issue is under https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.Exporter/1.0.0-beta.5. This package is referencing OpenTelemetry-1.4.0-beta.2 which is not compatible with OpenTelemetry 1.4.0-beta.3 or 1.4.0-rc.1.

See : https://github.com/open-telemetry/opentelemetry-dotnet/blob/49d110ae0f15a6579e204d8fb158b1aae383e699/src/OpenTelemetry/CHANGELOG.md?plain=1#L41-L46

Please report issue under https://github.com/Azure/azure-sdk-for-net
