### ISSUE TITLE
Is their any reason for not using Microsoft.Extensions.ObjectPool library in the LogRecordPool implementation ?

### ISSUE THREAD

**Issue by madhub** [open-telemetry/opentelemetry-dotnet#4022]
# Question
Is their any reason for not using [Microsoft.Extensions.ObjectPool](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.objectpool.objectpool-1?view=dotnet-plat-ext-7.0) library in the [LogRecordPool](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/Pool/LogRecordSharedPool.cs) implementation ?

**Comment by utpilla** [comment]
The major reason is that OpenTelemetry SDK tries to have the least number of dependencies on other packages. This is to avoid having users run into potential versioning conflicts which they might run into in case their application also used some version of `Microsoft.Extensions.ObjectPool` package which was incompatible with what OpenTelemetry would have required.

**Comment by madhub** [comment]
Ok, understood. 
Is copying the code is an option ? code is MIT licensed.  Microsoft.Extensions.ObjectPool used in asp.net core , you will get **well tested code** in real production deployment.

**Comment by CodeBlanch** [comment]
@madhub Is there some issue with the LogRecordPool you encountered or are you trying to swap it out for a different implementation (or something)?

ObjectPool for me is a questionable thing. I was told it was an [infrastructure-only thing](https://github.com/dotnet/aspnetcore/issues/36586#issuecomment-922063322) and it wasn't brought into dotnet/runtime (as were many of the MSE libraries) which makes me suspect runtime didn't fully believe in either its purpose or implementation. I'm not opposed to changing the pool implementation, just don't know if ObjectPool is the gold standard 😄

**Comment by madhub** [comment]
@CodeBlanch  In general , I am in favor of reusing existing well tested implementation instead of writing from scratch ( unless existing implementation has performance issues ).
**I have no issue with the current implementation ,** 

My understanding is [Microsoft.Extensions.ObjectPool](https://www.nuget.org/packages/Microsoft.Extensions.ObjectPool/#dependencies-body-tab) is not tied to ASP.NET Core, in-dependent nuget package ,

**Comment by CodeBlanch** [comment]
@madhub I would 100% agree with you for anything shipped from dotnet/runtime! My read of ObjectPool is it isn't being supported. But if you can show there is a compelling reason to use it, be it better perf or other useful features, I would be open to switching as I'm sure the other maintainers would be too.

**Comment by Kielek** [comment]
From the AutoInstrumentation perspective - less dependencies - better. I would vote for current version if there is no direct benefits.

**Comment by cijothomas** [comment]
closing as no pending action.
