### ISSUE TITLE
When creating multiple OTel tracing pipelines, each of them subscribes to the sources and exports activities

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#4037]
# Bug Report

```xml
<ItemGroup>
   <PackageReference Include="OpenTelemetry" Version="1.4.0-rc.1" />
   <PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.4.0-rc.1" />
   <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.4.0-rc.1" />
   <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.10" />
</ItemGroup>

```

Runtime version: net7.0

## Symptom

When OTel is configured multiple times in the same app (inevitable with multiple integration tests that run in parallel), multiple instances of the same activity are exported - each pipeline listens to all activities. 

**What is the expected behavior?**

Listening to activities should be done once per process, and it should be possible to run integration tests and see exported (once) activities in the backend of choice. 

**What is the actual behavior?**

Multiple instances of activities are exported:
<img width="941" alt="image" src="https://user-images.githubusercontent.com/2347409/209210780-3f774ed9-b3e3-4ada-be31-fefe0bdb93c1.png">

## Reproduce

[testing.zip](https://github.com/open-telemetry/opentelemetry-dotnet/files/10289758/testing.zip)

1. Try running all tests. Tests expect that each activity is exported once. They fail as each activity is exported as many times as there are active pipelines in the app (test classes)
2. Run individual test classes - they pass.
3. Check out jaeger. Each activity is exported 3 times.

**Comment by utpilla** [comment]
> Listening to activities should be done once per process, and it should be possible to run integration tests and see exported (once) activities in the backend of choice.

This is not the expected behavior. Every instance of TracerProviderSdk that you add in the process is expected to receive the callbacks for the ActivitySources that they are subscribed to. This behavior is By-Design.

You would have to update your test setup to either run them sequentially or you could have them use a dedicated ActivitySource so that they don't interfere with each other.

**Comment by lmolkova** [comment]
@utpilla this behavior limits use the ability to test their instrumentation. 

If this is by-design, it conflicts with the way ASP.NET Core integration testing, where multiple pipelines exist at the same time. 
Since the instrumentation tested is part of the application code (and not a test code), it's impossible ti use different ActivitySources for the same thing.

Before suggesting it's by design, I encourage you to try and experiment with the sample I shared, and create and document a reasonable solution that would work along with ASP.NET Core testing and real-world usage.

**Comment by utpilla** [comment]
> You're saying users can only run integration tests sequentially, which is not a good design.

I never said this.

This is a By-Design behavior, and you will have to tweak your tests accordingly if you want to run them in parallel.

I can think of two things that you could do here:

1. You could explore the options provided by xUnit that would allow you to initialize shared data only once for all the tests. Some preliminary search on the xUnit repo returned some interesting results. It seems like this might be a common ask: https://github.com/xunit/xunit/issues/1947#issuecomment-921110917. You might want to look into [AssemblyFixture](https://github.com/xunit/samples.xunit/tree/main/AssemblyFixtureExample) which seems to solve that problem.
2. You could tweak your unit tests to differentiate between http requests from different test classes. One way to do that would be to add a unique `tracestate` to your http requests for each test class. Something like this:
```csharp
    [Fact]
    public async Task Get()
    {
        for (int  i = 0; i < 100; i ++)
        {
            _client.DefaultRequestHeaders.Add("tracestate", nameof(OtherTests)); // Use the name of the test class
            await _client.GetAsync("/foo");
            await Task.Delay(10);
        }

        var processedActivities = CountingProcessor.Processed;
        Assert.Equal(processedActivities.Where(activity => activity.TraceStateString == nameof(OtherTests)).Distinct().Count(),
            processedActivities.Count(activity => activity.TraceStateString == nameof(OtherTests)));
    }
```
