### ISSUE TITLE
SQL/SqlClient instrumentation not working on the new version of "opentelemetry-operator"

### ISSUE THREAD

**Issue by sr185436** [open-telemetry/opentelemetry-dotnet#4044]
Question
Today we upgrade to the latest version of opentelemetry-operator and we suddenly saw that all SqlClient trace disappear.

Hope to get some guidelines how to enable it in the new version.

thanks

**Comment by Kielek** [comment]
Hi @sr185436,

could you please open issue under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/ or https://github.com/open-telemetry/opentelemetry-operator and tag @open-telemetry/dotnet-instrumentation-approvers ?

What will be needed to help:
 - operator version
 - .NET version of instrumented applications
 - logs from the OpenTelemetry .NET Automatic Istrumentation. Typically stored by operator under `/var/log/opentelemetry/dotnet` 

BTW the latest operator is using OpenTelemetry .NET Automatic Istrumentation v0.5.0. Please check changelog if you are affected by this https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/CHANGELOG.md#050

**Comment by Kielek** [comment]
Can be closed: https://github.com/open-telemetry/opentelemetry-operator/issues/1343
