### ISSUE TITLE
Automate W3C trace-context test suite run 

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#405]
and run it in CI

**Comment by SergeyKanzhelev** [comment]
perhaps make it as a separate CI definition so main one will not slow down

**Comment by lmolkova** [comment]
I don't think this task make sense now as it fails on .NET side: https://github.com/open-telemetry/opentelemetry-dotnet/issues/404#issuecomment-569384877

**Comment by SergeyKanzhelev** [comment]
so this task a bit more involved as simply run the test suite. It also needs to exclude "expected" failures

**Comment by cijothomas** [comment]
@xiang17 is looking at this.

**Comment by xiang17** [comment]
Some test cases are still failing (other than the "expected" failures). Created another issue to track each failure test case: #1219
