### ISSUE TITLE
"Success" field returns "true" unexpectedly when resultCode is 4xx in Azure Monitor

### ISSUE THREAD

**Issue by hejingkan2005** [open-telemetry/opentelemetry-dotnet#4056]
# Bug Report

We're using instrumentation libraries to record http requests, and we notice "Success" field is "true" when http result code is 4xx in Azure Monitor, here is a sample:
![image](https://user-images.githubusercontent.com/14071136/210683009-98dba627-3dda-4d5e-92cb-6a3bc6c4ccc4.png)

**List of versions:**
```
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.9" />
<PackageReference Include="OpenTelemetry" Version="1.4.0-beta.3" />
<!--Exporter packages-->
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0-beta.3" />
<PackageReference Include="OpenTelemetry.Exporter.Geneva" Version="1.4.0-beta.3" />
<PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0-beta.3" />
<!--Instrumentation libraries-->
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.9" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.9" />
<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.0.0" />
```

Runtime version: net6.0

## Symptom

**What is the expected behavior?**

- For http status code >=200 and <= 399, "success" field should return true, while >= 400, "success" should return false.
- This issue caused AppInsights' "Failures" menu does not work in Azure portal.
![image](https://user-images.githubusercontent.com/14071136/210737886-ccedca7c-78ac-4840-ae90-4463774b5011.png)

**What is the actual behavior?**

- "Success" field unexpectedly returns true no matter what's the result code.

## Reproduce
It's duplicated to a bug opened earlier https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17352, please close anyone of it if it's not in the best support team.

**Comment by vishweshbankwar** [comment]
@hejingkan2005 ```<PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0-beta.3" />```. You need to upgrade to latest version beta.5 for this to work.

**Comment by hejingkan2005** [comment]
@vishweshbankwar , discussed offline, please help re-triage and dive deeper once you'er back.
