### ISSUE TITLE
Property Content of respose in method EnrichWithHttpResponseMessage is disposed

### ISSUE THREAD

**Issue by beatriz-alcantara** [open-telemetry/opentelemetry-dotnet#4073]
# Question

I'm trying to enrich my trace with EnrichWithHttpResponseMessage method. My code is like:

![image](https://user-images.githubusercontent.com/48103865/211879710-7772900e-395a-4a65-b7af-44fef68e00bb.png)

I want to get the content of the response to put in my trace, but when I try to access Content property the code throws ObjectDisposedException. Is there a way to get de response content inside the EnrichWithHttpResponseMessage method?

**Comment by rhwilburn** [comment]
You are missing an await or a .Result as the method is async so it returns a task.

Example of what you need to do below:

```response.Content.ReadAsStringAsync().Result``` //(because its async; and you don't have a task you can't use await as an alternative).

Note that the content can be GZipped so you may need something like this:

```
var isGZipped = message.Content.Headers.Any(h => h.Key.Equals("Content-Encoding", StringComparison.InvariantCultureIgnoreCase) && h.Value.Select(v => v.ToLowerInvariant()).Contains("gzip"));
string messageBody = "";

if (isGZipped)
{
    var compressedMessageBytes = message.Content.ReadAsByteArrayAsync().Result;
    var plainMessageBytes = Decompress(compressedMessageBytes);
    messageBody = Encoding.UTF8.GetString(plainMessageBytes);
}
else
{
    messageBody = message.Content.ReadAsStringAsync().Result;
}
```

```
activity.SetTag("Message", messageBody);
```

```
public static byte[] Decompress(byte[] data)
{
    using (var compressedStream = new MemoryStream(data))
    using (var zipStream = new GZipStream(compressedStream, CompressionMode.Decompress))
    using (var resultStream = new MemoryStream())
    {
        zipStream.CopyTo(resultStream);
        return resultStream.ToArray();
    }
}
```
