### ISSUE TITLE
Aspect-oriented programming support

### ISSUE THREAD

**Issue by cesarbmx** [open-telemetry/opentelemetry-dotnet#4078]
I would like to decorate with attributes my methods rather than polluting them with code and usings.
I mainly use OpenTelemetry to group spans under the same trace across multiple microservices.

Thanks

**Comment by reyang** [comment]
@cesarbmx thanks for the idea, do you have some code snippets which would show the expected experience?

**Comment by pellared** [comment]
> If we could just nest an active span by decorating the method, it would be great. The documentation shows how to do it with in-line code.
> 
> [Creating nested Spans](https://opentelemetry.io/docs/instrumentation/net/shim/#creating-nested-spans) ![image](https://user-images.githubusercontent.com/1844530/214596522-e7081e7e-e6a1-45f9-8291-1331b1472aa5.png)

How would you specify which methods should be decorated? How would you define the name? How would you add attributes?
