### ISSUE TITLE
How do I use propagation without semantic conventions? 

### ISSUE THREAD

**Issue by jamielennox** [open-telemetry/opentelemetry-dotnet#4088]
I'm setting up an internal library that just creates some defaults that we want turned on etc in our services. Specifically I need header propagation to work for tracing, regardless of whether i'm actually emitting traces for this service. 

To get context propagation to work i need to run the `OpenTelemetry.Instrumentation.AspNetCore` Instrumentation to extract the context out of incoming http requests and the `OpenTelemetry.Instrumentation.Http` instrumentation to inject it back into outgoing http requests. 

Both of these packages are dependant on Semantic Conventions and are therefore not published under a stable release.

My question - why do i need semantic conventions to do header propagation? It's annoying at the moment because the libraries aren't released as stable, but even long term in this case i don't care about any of the activity enrichment pieces, i just need to enable header and baggage propagation. Shouldn't I be able to do this without all the rest of the stuff?

PS: I do understand we're talking about tracing not metrics semantic conventions.

**Comment by cijothomas** [comment]
> My question - why do i need semantic conventions to do header propagation?

You do not need.

**Comment by cijothomas** [comment]
Asp.Net Core and HttpClient are 2 libraries that natively support context propagation. It does not automatically do the "Baggage" part , but the traceparent,tracestate headers are propagated/restored by these libraries automatically, even without opentelemetry.

**Comment by jamielennox** [comment]
That's really good to know as I do want to use this process to switch everyone to the w3c headers. However I'm not there yet.

What I'd really like here is to seperate the piece of [code that does propagation.extract](https://github.com/open-telemetry/opentelemetry-dotnet/blob/bb0c381478a5d6b6a3dd52cc9990d3582e908767/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L130-L164) and the piece of [code that does propagation.inject](https://github.com/open-telemetry/opentelemetry-dotnet/blob/bb0c381478a5d6b6a3dd52cc9990d3582e908767/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs#L214-L265) away from all the code that does activity enrichment with semantic conventions so that i can just consume that.

My goal is basically to do drop in header propagation using arbitrary OpenTelemetry Propagators without creating dependencies on unreleased libraries or messing with the current Activity enrichment that teams are doing. Even just turn on baggage would be a start.

**Comment by cijothomas** [comment]
Closing as no further action needed in this repo. Please re-open, if there are follow up questions or issues. Thank you!
