### ISSUE TITLE
Make MeterSdk internal

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-dotnet#409]
It seems some part of implementations are still missing and we need to call `MeterSdk.Collect()` until then.

MeterSdk should be made internal after implementation is finished and before beta

**Comment by cijothomas** [comment]
There are other classes which needs to be reviewed for access modifier. `Metric` is now the 'export record' i.e `Metric` represent the data structure passed on to the Exporters. Users should not be allowed to create `Metric` ever - they should always create metric using one of the metric instrument.
Adding this note here to make sure the public ctor for Metric is removed once all connecting pieces in Metric SDK are in.

**Comment by MikeGoldsmith** [comment]
We did something similar for Spans being passed to Exporters by creating a SpanData that only had public setter, we create something like `MetricData` that is used in the same way.

**Comment by cijothomas** [comment]
This is done. closing.
