### ISSUE TITLE
SemanticConventions attribute name constants differ from spec

### ISSUE THREAD

**Issue by tshowers-bt** [open-telemetry/opentelemetry-dotnet#4101]
# Bug Report

OpenTelemetry.SemanticConventions 1.0.0-rc9.9

## Symptom

I notice that some of the constants in the package don't match the values in the spec; for example [`public const string AttributeMessagingMessageId = "messaging.message_id";`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/bb0c381478a5d6b6a3dd52cc9990d3582e908767/src/OpenTelemetry.SemanticConventions/Trace/TraceSemanticConventions.cs#L695) but the spec refers to [`messaging.message.id`](https://github.com/open-telemetry/opentelemetry-specification/blob/3d594588815fa4564fe35984e8b1a714e54d48f2/specification/trace/semantic_conventions/messaging.md?plain=1#L203).

The [PR that introduced this](https://github.com/open-telemetry/opentelemetry-dotnet/pull/2069) says the values were autogenerated so maybe it's just out of date? I had a quick look at the [build-tools](https://github.com/open-telemetry/build-tools/tree/main/semantic-conventions) and it links to the java package which has a constant that [does match the spec](https://github.com/open-telemetry/opentelemetry-java/blob/6edba790d87782dd2d681ac90beaa51b74e95c78/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java#L800).

**Comment by tshowers-bt** [comment]
I'll certainly have a go at it. Probably later today.

**Comment by ttd2089** [comment]
I opened [a PR](https://github.com/open-telemetry/opentelemetry-dotnet/pull/4102) but simply updating the versions didn't work. I found [this issue](https://github.com/open-telemetry/build-tools/issues/122) and had to add a volume mount to the `docker run` command to fix the problem; but now I'm not sure whether the generated output is actually correct. As mentioned in the PR there are some properties in the generated code that I didn't see in the corresponding diff in the semconv changelog:
- code.column
- messaging.source.kind
- messaging.source.template
