### ISSUE TITLE
AddJaegerExporter - could not add custom tags .net 7

### ISSUE THREAD

**Issue by candrewtemenoscom** [open-telemetry/opentelemetry-dotnet#4110]
# Bug Report

List of [all OpenTelemetry NuGet:

using OpenTelemetry.Instrumentation.AspNetCore;
using OpenTelemetry.Logs;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;
using OpenTelemetry.Extensions.Hosting;

Runtime version: .net 7

* TBD

## Symptom

I am trying to export my trace with custom tags to Jaeger exporter with the following codes. However, it seems the particular JaegerExporterOptions does not the Tags definition any more.

**What is the expected behavior?**
I should be able to add custom tags to trace for JaegerExporter

What did you expect to see?
Could not add custom tags

**What is the actual behavior?**

What did you see instead?

## Reproduce

Here is the code I used to add JaegerExporter to the TraceProvider

providerBuilder.AddJaegerExporter(options =>
                        {
                            options.AgentHost = "localhost";
                            options.AgentPort = 6831;
                            // Additional attributes should be able to set it here but not
                            options.Tags = new Dictionary<string, string>(){
                                {"environment", "production"}
                            };
                        });

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by cijothomas** [comment]
// Additional attributes should be able to set it here but not
options.Tags = new Dictionary<string, string>(){
{"environment", "production"}
};

Not quite able to understand the issue/bug here.. JaegerExporter has no support for "Tags".

**Comment by candrewtemenoscom** [comment]
The issue is I want to add additional tags to a trace for Jaeger exporter. May I know if it is not possible to do that in .net?

**Comment by cijothomas** [comment]
No, there is no Jaeger specific tag support. Depending on what you what to add, you could model it as Resource, or Tags/Attributes on Activity (Span) itself.
