### ISSUE TITLE
Console Application example not functional for .NET Framework 4.7.2

### ISSUE THREAD

**Issue by noam-ronen** [open-telemetry/opentelemetry-dotnet#4116]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

OpenTelemetry 1.3.2
OpenTelemetry.API 1.3.2
OpenTelemetry.Exporter.Console 1.3.2

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

v4.7.2

## Symptom

Following along with the [getting started console application](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/getting-started-console/README.md):

1. Created a new "Console App (.NET Framework)" using Visual Studio 2022.
2. Installed OpenTelemetry.Exporter.Console from the Nuget package manager.
3. Copied the code from [Program.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/getting-started-console/Program.cs).
4. Made minor code modifications (required for this version of .NET):
 - Block scoped namespace - namespace GettingStarted{...
 - Specify type for: new ActivitySource(...
 - Block scoped using statement: using (var tracerProvider...)
5. Ran the application.

**What is the expected behavior?**

Expected to see the output written to the console.

**What is the actual behavior?**

Exception is thrown:
Method not found: 'OpenTelemetry.Trace.TracerProviderBuilder OpenTelemetry.Trace.ITracerProviderBuilder.ConfigureServices(System.Action`1<Microsoft.Extensions.DependencyInjection.IServiceCollection>)'.'

I also tried to install a newer version of Microsoft.Extensions.DependencyInjection (7.0.0) - This does not raise an exception, but no console output is created here either. In this case, the activity is null.

## Reproduce
Minimal console app:
[OpenTelemetrySampleApp.zip](https://github.com/open-telemetry/opentelemetry-dotnet/files/10529370/OpenTelemetrySampleApp.zip)

**Comment by cijothomas** [comment]
The attached repro works fine, and does not repro the issue for me:
![image](https://user-images.githubusercontent.com/5232798/215810786-892eff9a-aae9-4437-981f-51e0baf05e6a.png)

Updated packages to latest pre-release, and it still works for me:
![image](https://user-images.githubusercontent.com/5232798/215811390-c7203722-5e31-4b22-8023-81c82747757f.png)

Could you retry, and post back with the exact steps followed, so we can try to narrow down?

**Comment by CodeBlanch** [comment]
@noam-ronen 

`ITracerProviderBuilder.ConfigureServices`

That is part of the 1.4.0 API surface so just from the error it seems like you have some 1.4.0 bits mixed in with 1.3.2. Can you double-check the versions of the OpenTelemetry.* DLLs in the folder with your exe?

**Comment by noam-ronen** [comment]
Issue resolved! 

I had some issues with the pre-release packages. I think the issue was specifically from the package OpenTelemetry.Extensions.Hosting, but I'm not certain. 

The pre-release packages did not download by default (maybe missing the --pre-release flag?) and had to be manually installed from Nuget.

Thanks for your help!
