### ISSUE TITLE
Print Open telemetry logs to File (dot net framework 4.6.2)

### ISSUE THREAD

**Issue by Sgprasad** [open-telemetry/opentelemetry-dotnet#4131]
What i want to achive
1.Looking to write opentelemetry logs to file or OTPL (not able to export to otpl default port or any other exporter apart from Console)
2.Leverage existing implemented log4Net logs to write using open telemetry
3. write open telemetry logs to file 

i am able to write to console using exporter, however i am looking to write to a file.

Any help or reference is appreciated
Framework: dot net framework 4.6.2

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).
[OpentelemetrylogCode.txt](https://github.com/open-telemetry/opentelemetry-dotnet/files/10553838/OpentelemetrylogCode.txt)

**Comment by hkusulja** [comment]
I am using .NET 8 LTS and NuGet packages from Open Telemetry. 
I can confirm that logging to Console, and to Azure Application Insights works.
However, I do not see NuGet package to log to file. So, I am also interested in this.
Any roadmap or plan for Open Telemetry to support .NET logging to local file?

**Comment by cijothomas** [comment]
> Any roadmap or plan for Open Telemetry to support .NET logging to local file?

None. There is a file exporter in the collector, that could be checked out. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter
