### ISSUE TITLE
Add support for OTEL_SERVICE_VERSION environment variable

### ISSUE THREAD

**Issue by martincostello** [open-telemetry/opentelemetry-dotnet#4132]
# Feature Request

Support configuring the service version automatically from the `OTEL_SERVICE_VERSION` environment variable.

See open-telemetry/opentelemetry-specification#1901 for existing spec issue.

**Describe the solution you'd like:**

Support for reading the version from `OTEL_SERVICE_VERSION` as per #4081.

**Describe alternatives you've considered.**

None.

## Additional Context

Add any other context about the feature request here.

**Comment by Kielek** [comment]
Note: spec decided to not add this as separate env. var. Closing is fine.
