### ISSUE TITLE
Hello, advise how to use opentelemetry correctly net7 c#

### ISSUE THREAD

**Issue by SyntaxEvg** [open-telemetry/opentelemetry-dotnet#4147]
# Question

**Input**: 
There is a distributed microservice
  first comes nginx -> api.Gateway ->microservice 1 , microservice 2 microservice3, microservice 4
services communicate with each other via Grpc, there is also a RabbitMQ bus, from each microservice it is possible to send a message via AMQP,
**My question is this:**
I don't understand where to embed it in my .net7 c# application
Either only in a <startup> on Gateway, or register in each microservice 1,2,3,4
Please suggest the best practice
___
![image](https://user-images.githubusercontent.com/94603687/216756808-9174fe52-9b2b-42ca-98c4-aab6386b070c.png)

**Comment by trejjam** [comment]
You should have it in each microservice.

Each client should pass tracing properties to the message:
```cs
private readonly TextMapPropagator _propagator;

public void InjectTracingProperties(IDictionary<string, string> tracingProperties)
{
   if (Activity is null)
   {
        return;
    }

    _propagator.Inject(new PropagationContext(Activity.Context, Baggage.Current), tracingProperties, (props, key, value) =>
    {
        try
        {
            props[key] = value;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to inject trace context");
        }
    });
}
```

And each server should propagate these properties to an activity:
```cs
private readonly ActivitySource _activitySource;
private readonly TextMapPropagator _propagator;

var content = _propagator.Extract(default, properties, (props, key) =>
{
    try
    {
        if (props.TryGetValue(key, out var value))
        {
            return new[] { value };
        }
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "Failed to inject trace context");
    }

    return Enumerable.Empty<string>();
});

_activitySource.StartActivity(
    name,
    activityKind,
    content.ActivityContext
)
```

By doing this you connect each activity under same `TraceId`. Which allows to your viewer show related activities:
![image](https://user-images.githubusercontent.com/3594540/216759796-936a0ee8-e224-4b70-9f54-076b02fbd761.png)

**Comment by SyntaxEvg** [comment]
Thanks for your reply, you are a good person
please tell me what is the reason why I can't just add 1 time to Gateway ?
this is our only way to communicate with services, he will not understand the entire call chain himself? such opentelemetry is not able?

**Comment by trejjam** [comment]
The point with opentelemetry is, that each system is reporting it's own activities. The only think which pass between microservices (if it's separate services/executable) is traceId, and previous activity id (so the related system knows parent from different/calling subsystem/service/executable). The tracing data are not transferred, the microservices should report it directly to collector (or collecting agent).

If you do not configure oTel in each service, but only in gateway, you will see only activities from the gateway. Which is not useless, but it will not provide what oTel actually can.

**Comment by SyntaxEvg** [comment]
> Reference
THANK YOU

**Comment by trejjam** [comment]
If it's all, maybe you can close the issue so maintainers do not need to go through it.
