### ISSUE TITLE
OpenTelemetryCollector

### ISSUE THREAD

**Issue by SyntaxEvg** [open-telemetry/opentelemetry-dotnet#4149]
# Question
### Hello, please tell me how to create such a solution, I really liked it, but the documentation did not really help to implement
**.net7 docker-compose**
thanks in advance
--
![image](https://user-images.githubusercontent.com/94603687/216783329-096670fc-e22f-47fd-ab49-cbd7f4025771.png)

**Comment by cijothomas** [comment]
Please use https://github.com/open-telemetry/opentelemetry-collector for Collector questions. Thanks!

**Comment by SyntaxEvg** [comment]
> Please use https://github.com/open-telemetry/opentelemetry-collector for Collector questions. Thanks!
hello, thanks for the answer, unfortunately it's difficult and it's not clear where to start to do this for a developer, tell me, can there be manuals?
