### ISSUE TITLE
Metric name format in Grafana Prometheus

### ISSUE THREAD

**Issue by candrewtemenoscom** [open-telemetry/opentelemetry-dotnet#4150]
### Discussed in https://github.com/open-telemetry/opentelemetry-dotnet/discussions/4146

<div type='discussions-op-text'>

<sup>Originally posted by **candrewtemenoscom** February  3, 2023</sup>
I am currently using the .net 7 in asp.net core to export metrics to Prometheus for those well-known counters using those eventsource namespaces. I notice that the metric names in the dropdown from the Grafana Prometheus metrics are always prefixed with some weird names like "ec_Microsoft_AspNetCore_....", or "ec_System_Net...". Do you know why was that and if it is possible to change those name prefixes?</div>

**Comment by pellared** [comment]
Closing as there is already an open discussion.
