### ISSUE TITLE
 PrometheusCollectionManager and PrometheusExporter classes should be public

### ISSUE THREAD

**Issue by andreminelli** [open-telemetry/opentelemetry-dotnet#4162]
Those classes are internal at this time. 

Is there a strong reason for that? 

Making them public would allow an "official" generation process that could be used outside PrometheusExporterMiddleware. This should be useful for instance as a temporary step when migrating from a legacy Prometheus-instrumented code base, where metrics from both APIs should live side-side for some time.

**Comment by andreminelli** [comment]
Ok, I just discovered that `prometheus-net` also exports metrics from `System.Diagnostics.Metrics`, so the sample scenario above is already covered.

I won't close this issue just yet, since the maybe in another scenarios those classes could be still useful if they are public...

**Comment by cijothomas** [comment]
We do not want to make anything public unless there is a real need for it. In the absence of any such need now, I will close the issue. Please reopen/new issue, if there are scenarios which are not working right now.
