### ISSUE TITLE
HTTP Server Duration Histogram description does not follow specification

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-dotnet#4169]
Line in question: https://github.com/open-telemetry/opentelemetry-dotnet/blob/b549e12148aa76e447a76c5c77701727e30a6c7d/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs#L42

Spec reference: https://github.com/open-telemetry/opentelemetry-specification/blob/84a5fa3d1ef42caae8f99f1b431504d7cdb9fffe/specification/metrics/semantic_conventions/http-metrics.md?plain=1#L24

This impacts the OpenTelemetry Demo (https://github.com/open-telemetry/opentelemetry-demo/issues/737) as we are emitting this metric from multiple languages. When the description differs between the same metric name, the prometheus exporter on the collector can't merge the points.

**Comment by cijothomas** [comment]
Typo. @vishweshbankwar can you fix? (also double check if there are others as well for metrics)
