### ISSUE TITLE
How to stop the ObservableGauge callback function keeps invoking

### ISSUE THREAD

**Issue by candrewtemenoscom** [open-telemetry/opentelemetry-dotnet#4175]
Hello, I am using the following code on my actionfilter onResultExecuted function to send metric to my opentelemetry endpoints. I noticed that the callback function kept invoking when I set a breakpoint on it. May I know if it is normal even though there is no more request to the action decorated with the actionfilter attribute after the initial call? If it is not normal, how to stop the observable gauge callback from invoking? Thank you for your help.

meter.CreateObservableGauge(requestProcessingMetricName, () => {
return new Measurement(_requestProcessingTime, tags);
});

**Comment by cijothomas** [comment]
Not clear what is the end goal. The observable callbacks will be kept on called during every collect/export cycle. If you do not have anything to report in a particular invocation, return `return Array.Empty<Measurement<long>>();`.

**Comment by stevejgordon** [comment]
@cijothomas / @martinjt - Traige note: This was answered and can probably be closed.
