### ISSUE TITLE
opentelemetry remove information  logs c#

### ISSUE THREAD

**Issue by SyntaxEvg** [open-telemetry/opentelemetry-dotnet#4185]
# Question
#### preferably in c#
==================
![image](https://user-images.githubusercontent.com/94603687/218741605-28b8f619-fecd-41fe-8fc8-5fe878d3e68f.png)
![image](https://user-images.githubusercontent.com/94603687/218741669-27733081-67b6-455e-9768-11ac96cce6d8.png)
![image](https://user-images.githubusercontent.com/94603687/218741896-a0004bdd-104a-4825-bee3-490cc3b49f7a.png)

**Comment by cijothomas** [comment]
`logOpt.IncludeScope=false` would remove the scopes. From the screenshot, it looks like this is the information you are trying to avoid.

**Comment by SyntaxEvg** [comment]
> 



> `logOpt.IncludeScope=false` would remove the scopes. From the screenshot, it looks like this is the information you are trying to avoid.
thanks, friend, I wanted a lot more... if you have the ability to adjust the margins (remove, add) Custom

**Comment by cijothomas** [comment]
see https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/redaction too
