### ISSUE TITLE
Plan for System.Diagnostics.DiagnosticSource 7.0.1

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet#4194]
# Question

[System.Diagnostics.DiagnosticSource 7.0.1](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/7.0.1) was released yesterday.

What is the plan for this version in context of 1.4.0 and 1.5.0?

**Comment by cijothomas** [comment]
Do we need to do anything at all? OTel 1.4 has >=7.0.0 already.

**Comment by Kielek** [comment]
No. I just need a confirmation that there is no plan to update.
Based on this, we can prepare some changes on auto-instrumentation side.

Thanks.
