### ISSUE TITLE
Docs missing for metrics in instrumentaions

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#4197]
1.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore
The above supports metrics, but the doc is not showing how to enable them.

2. Along with the above, consider documenting the metric names, similar to: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Process

**Comment by vishweshbankwar** [comment]
This is completed.
