### ISSUE TITLE
Metrics don't work on .NET Core 3.1

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet#4204]
# Bug Report

Metrics don't work on .NET Core 3.1 with latest OpenTelemetry RC builds
Version: [1.4.0-rc.4](https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/core-1.4.0-rc.4) 

Runtime version (e.g. `netcoreapp3.1`

## Symptom
Using OpenTelemetry SDK to record metrics throws exception
![image](https://user-images.githubusercontent.com/33643312/219811998-de58cca8-8280-4ac5-ab29-47a969e1f69b.png)

![image](https://user-images.githubusercontent.com/33643312/219812015-ca71ac53-f1c5-4e9a-a613-30f3d4a00f5f.png)

**What is the expected behavior?**
This document https://github.com/open-telemetry/opentelemetry-dotnet/discussions/3767 mentions that it can technically be consumed on Net core 3.1 but that's not true.
![image](https://user-images.githubusercontent.com/33643312/219812169-324f0473-0929-496b-8cbf-063967d4888c.png)

What did you expect to see?
We still a bunch of services which are on 3.1 and the plan to upgrade to NET6 and higher is still an year away due to various factors. We expected OpenTelemetry to support 3.1 for one more year.

**What is the actual behavior?**
It completely breaks on 3.1

## Reproduce

Repro is straightforward, just create a self-contained project to emit metrics running on .NET core 3.1

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by reyang** [comment]
I don't think OpenTelemetry should continue to support .NET Core 3.1 since that's a deprecated version of runtime which will not even receive security hotfix. https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

The supported runtime versions and the strategy is clearly captured here https://github.com/open-telemetry/opentelemetry-dotnet#supported-net-versions.

**Comment by dpk83** [comment]
The document/annoucement then should be updated clearly to reflect the same. Currently it has wrong information

> OpenTelemetry .NET can technically be consumed by projects targeting out-of-support frameworks like .NET Core 3.1 and even as far back as .NET Core 2.0.

**Comment by reyang** [comment]
I agree that the document should be clear. Where is the document?

**Comment by dpk83** [comment]
#3767

**Comment by alanwest** [comment]
We still do not plan to support .NET Core 3.1. We do not run tests against any out-of-support frameworks.

> I agree that the document should be clear. Where is the document?

We will update the document to make this more clear.

**Comment by GeoK** [comment]
@alanwest @reyang  What is the recommendation for library authors who ship multi-target SDKs (including netstandard2.0)?
Is there a way to ensure that metrics would get recorded in case that developers are using netcoreapp3.1?

**Comment by cijothomas** [comment]
@GeoK Not sure how is this any different for library authors who ship multi-target sdks.... If your app is ultimately run on unsupported .NET runtime, then Otel will not work.

**Comment by cijothomas** [comment]
> Is there a way to ensure that metrics would get recorded in case that developers are using netcoreapp3.1?

No, we dont test in .NET Core 3.1, and this issue already proves we dont work in .NET Core 3.1
