### ISSUE TITLE
Request duration calculation error

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#421]
Here is report that the first request duration is calculated incorrectly:

https://github.com/fbeltrao/dotnet-observability-sample/blob/master/opentelemetry-ai-state.md#4-difference-in-first-request-duration

**Comment by SergeyKanzhelev** [comment]
CC: @fbeltrao

We definitely are not calculating duration as "self-time". Perhaps some issue with the conversion of timestamps?

**Comment by fbeltrao** [comment]
It turns out to be an error on my side, sorry.

Analyzing again (and running with docker-compose) actually shows that only the self-time (+local dependencies) are computed as duration.

**Comment by SergeyKanzhelev** [comment]
thank you for validation!
