### ISSUE TITLE
AddJaegerExporter makes services crash on startup run if host is unknown.

### ISSUE THREAD

**Issue by phamtri2996** [open-telemetry/opentelemetry-dotnet#4210]
# Bug Report

`opentelemetry 1.4.0-rc.3`
`opentelemetry.exporter.jaeger 1.3.2`
`opentelemetry.extensions.hosting 1.4.0-rc.3`
`opentelemetry.instrumentation.aspnetcore 1.0.0-rc9.12`
`opentelemetry.instrumentation.http 1.0.0-rc9.12`

Runtime version:  `netcoreapp3.1`

## Symptom

https://github.com/open-telemetry/opentelemetry-dotnet/blob/7139c7a656ad43baff471ef0641c7dc828902c48/src/OpenTelemetry.Exporter.Jaeger/Implementation/JaegerUdpClient.cs#L39

On runtime, if jaeger hostname was unmapped, this method in constructor make the service crash.

**What is the expected behavior?**

JaegerExporter ignore whether the host name was mapped or not, allow the service to start up and handle requests.

## Reproduce

Here's the simplified version of our OpenTelemetry implementation:
```
services.AddOpenTelemetry()
.WithTracing(
    tracerBuilder => 
    {
        tracerBuilder.Build(Configuration);
    })
.StartWithHost();
```

```
public static class OpenTelemetryExtension
{
    /// <summary>
    /// 
    /// </summary>
    /// <param name="builder"></param>
    public static void Build(this TracerProviderBuilder builder, IConfiguration Configuration)
    {
        builder
        .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(
            Configuration.GetValue<string>("ServiceName")
            , serviceVersion:  Configuration.GetValue<string>("ServiceVersion")))
        .AddAspNetCoreInstrumentation()
        .AddHttpClientInstrumentation()
        .AddSqlClientInstrumentation();

        switch (Configuration.GetValue<string>("Exporter").ToLower())
        {
            case "jaeger":
                builder.AddJaegerExporter(o =>
                 {
                     o.AgentHost = Configuration.GetValue<string>("AgentHost");
                     o.AgentPort = Configuration.GetValue<int>("AgentPort");
                 });
                break;
            default:
                builder.AddConsoleExporter();
                break;
        }
    }
}
```

This is a library project that shared across our services. 
The problem here is:
* Not all of our services need monitoring. 
* Our system architecture is managed by another team
I can manually disable OpenTelemetry in settings for services that need monitoring but if the host mapping is down due to system maintenance or something else or when k8s build more pods, we can't start our services unless we manually disable it in settings.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by alanwest** [comment]
This was a recent change from #4006. We now fail on startup if a component cannot be initialized. Previously, this error was swallowed when using the OpenTelemetry.Extensions.Hosting package.
