### ISSUE TITLE
CA2000 alerts when creating custom log exporter

### ISSUE THREAD

**Issue by zhifzhan** [open-telemetry/opentelemetry-dotnet#4211]
Hi,

I'm adding a custom log exporter in my ASP.NET project, following this guide https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/extending-the-sdk/README.md

When adding the exporter with extension method,
Analyzer warns me in this line
```
return options.AddProcessor(new BatchLogRecordExportProcessor(new MyExporter()));
```

```
warning CA2000: Call System.IDisposable.Dispose on object created by 'new BatchLogRecordExportProcessor(new MyExporter())' before all references to it are out of scope
warning CA2000: Call System.IDisposable.Dispose on object created by 'new MyExporter()' before all references to it are out of scope
```

What's the recommended way to dispose them? or can I suppress the warnings?

In my case I need to flush and shut down the custom logging channel inside the exporter.
It seems they can be put into `OnForceFlush()` and `OnShutDown()`?

Thanks!

**Comment by alanwest** [comment]
This can be safely suppressed.

TODO: Add documentation suggesting that custom components should dispose components it owns. Will continue discussion on docs PR.

**Comment by CodeBlanch** [comment]
CA2000 is a tough one. Lots of guesses in its design, lots of false positives. I think for now suppress this. In 1.4. for logs and metrics we added some factory pattern overloads for AddInstrumentation that don't trigger CA2000 (IIRC). I'm hoping to apply those to logs soon and then there will be a nicer way to get around this.

**Comment by zhifzhan** [comment]
Thanks guys! I'll suppress it in our code.

Another question is: if I add something in `MyExporter.Dispose()`, when will it be executed?

**Comment by CodeBlanch** [comment]
@zhifzhan For logging your exporter will be disposed when the parent `LoggerFactory` is disposed. It will (more or less) go LoggerFactory.Dispose() -> OpenTelemetryLoggerProvider.Dispose() -> Processor.Dispose() -> Exporter.Dispose().

How the `LoggerFactory` dispose is triggered may vary. Typically in an ASP.NET Core app the factory is disposed when the host is shutting down. But if you are self-managing using something like `LoggerFactory.Create` than it is up to you to dispose it.

**Comment by zhifzhan** [comment]
@CodeBlanch Thank you!
