### ISSUE TITLE
Default value for `ParseStateValues` on OpenTelemetryLoggerOptions

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#4213]
OTLP [exporter](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7139c7a656ad43baff471ef0641c7dc828902c48/src/OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs/OtlpLogExporterHelperExtensions.cs#L56) sets this to `true` by default. Should we consider updating the default value on options to `true`? Any user who wants to disable it can do so by setting it `false`.

**Comment by CodeBlanch** [comment]
I did some redesign on #3677 to try and make it more user friendly but it didn't end up making 1.4. I'm hoping to bring it back when we do the upcoming log updates. Specifically regarding `ParseStateValues` this is what I was planning:

> State + StateValues + ParseStateValues
> 
> These things evolved to be strange. Exporters are having to check StateValues & State and some are forcing ParseStateValues = true. State itself is not safe to access beyond the log lifecycle. I tweaked things so there is a more deterministic behavior. If TState is IReadOnlyList<KeyValuePair<string, object>> (or IEnumerable<> equivalent) than LogRecord.Attributes will now always be populated. That will cover most messages written through ILogger using the source generator or the extensions. The only way to pass something that doesn't meet that requirement is calling ILogger.Log<T>(...) directly. In that case if ParseStateValues = true than we will build Attributes dynamically using reflection.
>
> This allows for the deprecation of LogRecord.State. Exporters should now be able to look at LogRecord.Attributes for everything and get a nice and consistent behavior.
>
> If users don't care for export of attributes at all there is now an option IncludeState to turn off all operations against TState.

**Comment by vishweshbankwar** [comment]
@CodeBlanch Can we close this one as part of https://github.com/open-telemetry/opentelemetry-dotnet/pull/4334
