### ISSUE TITLE
Pass the IServiceProvider in ConfigureResource, WithTracing & WithMetrics

### ISSUE THREAD

**Issue by megla-tlanghorst** [open-telemetry/opentelemetry-dotnet#4228]
# Feature Request

**Is your feature request related to a problem?**

We need an `IServiceProvider` in `ConfigureResource` and `WithTracing` (and `WithMetrics` if we'd use it) for stuff like the options pattern.

**Describe the solution you'd like:**

A service provider being provided (as an option) to the respective callbacks.

**Describe alternatives you've considered.**

For `ConfigureResource` you could maybe get it done with an extension method, but you're basically rewriting library code at that point. For `WithTracing` I don't see a solution, without accessing private stuff via reflection.

**Comment by CodeBlanch** [comment]
Just for anyone landing on this issue see https://github.com/open-telemetry/opentelemetry-dotnet/issues/4139#issuecomment-1414229507 for some code you can use to accomplish these tasks today using the 1.4 API.

**Comment by antmeehan** [comment]
@cijothomas Can we please re-open this as #4261 doesn't appear to fix this issue (in the way #4228 attempted)?

**Comment by CodeBlanch** [comment]
We won't be adding top-level extensions which expose `IServiceProvider` for now because [they are dangerous](https://github.com/open-telemetry/opentelemetry-dotnet/pull/5038#issuecomment-1804769873).

If you want to use `IServiceProvider` to do resource detection we support stuff like this:

```csharp
appBuilder.Services.AddOpenTelemetry()
    .ConfigureResource(b => b.AddDetector(sp => new MyResourceDetector(sp)));

internal sealed class MyResourceDetector : IResourceDetector
{
    private readonly IServiceProvider serviceProvider;

    public MyResourceDetector(IServiceProvider serviceProvider)
    {
        this.serviceProvider = serviceProvider;
    }

    public Resource Detect()
    {
        var options = this.serviceProvider.GetRequiredService<IOptions<MyOptions>>().Value;

        Dictionary<string, object> values = new();

        if (options.AddSomeResourceInfo)
        {
            // add keys
        }

        if (options.AddSomeOtherResourceStuff)
        {
            // add keys
        }

        return new(values);
    }
}
```

If you want to access `IServiceProvider` to configure logging/tracing/metrics we have this shape:

```csharp
services.AddOpenTelemetry().WithTracing();
services.ConfigureOpenTelemetryTracerProvider((sp, builder) => { 
   // Configure TracerProviderBuilder using IServiceProvider but watch out IServiceCollection is no longer available...
});
```

Do those work for your use case?

**Comment by antmeehan** [comment]
Thanks @CodeBlanch for the detailed response. I was actually already using `ConfigureOpenTelemetryTracerProvider` to add attributes which is working except they aren't being applied to log traces (it seems to only be applying the default server role etc). I'm observing the same behaviour using the `AddDetector` you've suggested so I'm guessing I'm doing something wrong on my side.
