### ISSUE TITLE
Could not load file or assembly 'OpenTelemetry.Audit.Geneva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by sarthakk-27** [open-telemetry/opentelemetry-dotnet#4239]
Why I am getting this issue when I have loaded this package and even did assembly binding for it?

**Comment by cijothomas** [comment]
OpenTelemetry.Audit.Geneva is not a component from this repo. I'd suggest to follow up with that component's owners to get help.
