### ISSUE TITLE
Metrics are not exported if they have a space in the name

### ISSUE THREAD

**Issue by danelson** [open-telemetry/opentelemetry-dotnet#4252]
# Bug Report

List of all OpenTelemetry packages:

* OpenTelemetry 1.4.0
* OpenTelemetry.Exporter.Console 1.4.0
* OpenTelemetry.Exporter.InMemory 1.4.0
* OpenTelemetry.Exporter.OpenTelemetryProtocol 1.4.0

Runtime version:

* net6.0

## Symptom

Metrics that have spaces in the name are not exported.

This appears to be consistent with at least the following exporters:

- Console
- InMemory
- OTLP

This appears to be consistent with at least the following instruments:

- Counter
- Histogram

**What is the expected behavior?**

Metric is exported

**What is the actual behavior?**

Metric is not exported

## Reproduce

The following test fails: https://github.com/open-telemetry/opentelemetry-dotnet/commit/82e2f7b869becb49a40d1b3ac4de4a1ed213d18a

Simple example code
```csharp
using var meter = new Meter("TestMeter");

var exportedItems = new List<Metric>();
var provider = Sdk.CreateMeterProviderBuilder()
	.AddMeter(meter.Name)
	.AddInMemoryExporter(exportedItems)
	.Build();

var counter = meter.CreateCounter<int>("with space");
counter.Add(1);
provider.Dispose();
Console.WriteLine(exportedItems.Count); // prints 0 instead of 1
```

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-name-syntax

Spaces are disallowed. (and lot more restrictions like not allowing / etc.)

The troubleshooting doc should have captured why metrics were dropped.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#troubleshooting

**Comment by danelson** [comment]
@cijothomas thank you. For completeness it will appear in the diagnostics logs if a level of `Warning` is set.
