### ISSUE TITLE
Consider a better project name

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#4265]
Currently it is called "stratified-sampling-example" https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/advanced/stratified-sampling-example:
1. "sampling example" is very mouthful
2. all other projects under `/docs` folder do not follow this pattern (and there is another folder `/examples` which makes it ever more confusing)

**Comment by cijothomas** [comment]
A rename to "stratified-sampling" will suffice?
