### ISSUE TITLE
Http client metric add http route to label

### ISSUE THREAD

**Issue by aygalinc** [open-telemetry/opentelemetry-dotnet#4268]
Hi,

In the trace example it is possible to configure an enrich function.
When adding http client metric i do not find a way to add http_route label to my http client metrics.
Why their is no configuration option in http client metric instrumentation ?

**Comment by vishweshbankwar** [comment]
@aygalinc httproute is generally not available on client side. [spec](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#:~:text=HTTP%20client%20spans%20have%20no%20http.route%20attribute%20since%20client%2Dside%20instrumentation%20is%20not%20generally%20aware%20of%20the%20%22route%22%2C%20and%20therefore%20HTTP%20client%20span%20names%20SHOULD%20be%20%7Bmethod%7D)

The ability to enrich will be available in `.NET8.0` onwards. See discussions on https://github.com/open-telemetry/opentelemetry-dotnet/issues/4932
