### ISSUE TITLE
StartActivity null when using .Net framework API

### ISSUE THREAD

**Issue by Steve887** [open-telemetry/opentelemetry-dotnet#4276]
# Bug Report

![image](https://user-images.githubusercontent.com/129719/223396863-a1d96d89-b0db-43f9-bc44-1af9adeb1c16.png)

Runtime version: Net48, Netstandard2.0

## Symptom

I have a .Net Framework 4.8 API in which I am trying to use OpenTelemetry to send traces and metrics to an Azure monitor exporter.

I have configured OpenTelemetry and per the documentation, and several other resources I found including [Activity is null when using Microsoft Hosting Extensions and net472](https://stackoverflow.com/questions/75323899/activity-is-null-when-using-microsoft-hosting-extensions-and-net472) but every time I try to create a new Activity it returns null.

**What is the expected behavior?**

Populated Activity that logs tracers to configured exporters

**What is the actual behavior?**

Activity is null

## Reproduce

My services setup (using an autofac module):

```
protected override void Load(ContainerBuilder builder)
{
    builder.Register(x => new ActivitySource(TelemetryConfig.TelemetryServiceName)).SingleInstance();
    var services = new ServiceCollection();
    services.AddOpenTelemetry().WithTracing(traceBuilder => TelemetryConfig.Configure(traceBuilder));
    builder.Populate(services);
}
```
TelemetryConfig.Configure:

```
public static TracerProviderBuilder Configure(TracerProviderBuilder traceBuilder)
{
    traceBuilder
        .AddHttpClientInstrumentation()
        .AddAspNetInstrumentation()
        .AddSqlClientInstrumentation(opts =>
        {
            opts.SetDbStatementForText = true;
            opts.SetDbStatementForStoredProcedure = true;
        })
        .AddConsoleExporter()
        .AddAzureMonitorTraceExporter(o =>
        {
            o.ConnectionString = "<ConnectionString>";
        })
        .AddSource("Api")
        .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(serviceName: "Api"));
    return traceBuilder;
}
```
How I am using the trace:

```
using (var activitySource = new ActivitySource("Api"))
using (var activity = activitySource.StartActivity("Test")) <-- activity is always null
{
    activity?.SetTag("Test", "123");
    Thread.Sleep(1000);
}
```

**Comment by CodeBlanch** [comment]
Hey @Steve887!

I suppose my first question is why are you using hosting with a net472 application? :smile: We expect most users on .NET Framework to use the "Sdk.Create*" style to build their providers.

If you really want to use hosting for some reason, you **need to use a host**. The code above is showing a `ServiceCollection` that is **NOT** to be confused with a host. Host examples: [generic host](https://learn.microsoft.com/dotnet/core/extensions/generic-host), [web host](https://learn.microsoft.com/aspnet/core/fundamentals/host/web-host).

All the `OpenTelemetry.Extensions.Hosting` `AddOpenTelemetry` extension does is register an [IHostedService](https://learn.microsoft.com/dotnet/api/microsoft.extensions.hosting.ihostedservice) into the `IServiceCollection` to access the `TracerProvider` and/or `MeterProvider` to start up the SDK. Nothing will happen with that unless there is a host in play to start the service.

I just tried this on `net472` and everything worked fine:

* program.cs

  ```csharp
   using Microsoft.Extensions.DependencyInjection;
   using Microsoft.Extensions.Hosting;
   using OpenTelemetry.Resources;
   using OpenTelemetry.Trace;
   
   var host = Host.CreateDefaultBuilder()
       .ConfigureServices((hostContext, services) =>
       {
           services.AddOpenTelemetry().WithTracing(tracerProviderBuilder =>
           {
               tracerProviderBuilder
                   .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("MySample"))
                   .AddConsoleExporter()
                   .AddSource("MySource");
           });
       })
       .Build();
   
   host.Run(); // <- IHostedServices are started here
   ```

* csproj

   ```xml
   <Project Sdk="Microsoft.NET.Sdk">
   
     <PropertyGroup>
       <OutputType>Exe</OutputType>
       <TargetFramework>net472</TargetFramework>
       <ImplicitUsings>enable</ImplicitUsings>
       <Nullable>enable</Nullable>
       <LangVersion>11</LangVersion>
     </PropertyGroup>
   
     <ItemGroup>
       <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.32" />
     </ItemGroup>
   
     <ItemGroup>
       <ProjectReference Include="..\src\OpenTelemetry.Exporter.Console\OpenTelemetry.Exporter.Console.csproj" />
       <ProjectReference Include="..\src\OpenTelemetry.Extensions.Hosting\OpenTelemetry.Extensions.Hosting.csproj" />
     </ItemGroup>
   
   </Project>
   ```

If you want to use `AddOpenTelemetry` with a `ServiceCollection` WITHOUT a host, it is perfectly acceptable to just start the providers yourself:

```csharp
var services = new ServiceCollection();
services.AddOpenTelemetr().WithTracing().WithMetrics();

using var serviceProvider = services.BuildServiceProvider();

// Start OTel SDK
var tracerProvider = serviceProvider.GetRequiredService<TracerProvider>();
var meterProvider = serviceProvider.GetRequiredService<MeterProvider>();
```

> My services setup (using an autofac module):

Not familiar with autofac at all but my guess would be your issue is really because it isn't doing the job of a host (doesn't start up `IHostedService`s registered into the collection).

**Comment by Steve887** [comment]
I did try the SDK.Create style with the same result. Annoyingly I setup a new .Net framework API project to provide an example and it worked, typical!

I dug a little deeper and with some use of symbols found the reason Activity is returning as null is because the ActivityCreationOptions ParentContext property has TraceFlags set to None, which is causing the AlwaysOffSampler to be used.

These seem to be set from the Activity.Current.Context property, which also has TraceFlags set to None. Any ideas from here?
![image](https://user-images.githubusercontent.com/129719/223887549-69b4c93f-7b4a-414a-a576-1d3919dc8a52.png)

**Comment by CodeBlanch** [comment]
@Steve887 

The default sampler the SDK uses (if you don't call `SetSampler` anywhere) is `new ParentBasedSampler(new AlwaysOnSampler())`.

The `ParentBasedSampler` bit is key. What that will do is respect the parent sampling decision, if there is a parent.

So my question would be, when you call `activitySource.StartActivity` what is `Activity.Current`? Is it `null` or is there a current activity (which will become the parent of the new one)? If there is a current activity, what kind is it and what are its trace flags?

**Comment by Steve887** [comment]
There is an `Activity.Current` but it also has TraceFlags set to None.
![image](https://user-images.githubusercontent.com/129719/224188289-49be6fb3-bf75-4436-bc7b-57d2ec9ad4aa.png)

It's feeling like this is some weirdo consequence of my (admittedly complicated) setup. So happy to close this with the solution, use `SetSampler<AlwaysOnSampler>`. I wasn't planning on using sampling anyway so always on is fine.
