### ISSUE TITLE
Setting Endpoint during AddOtlpExporter does not work

### ISSUE THREAD

**Issue by BenasB** [open-telemetry/opentelemetry-dotnet#4297]
# Bug Report

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.0.2`):

Latest where it's possible
```xml
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.4.0" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.4.0" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.14" />
```

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

Tested with `net6.0`

## Symptom

Setting `Endpoint` in `AddOtlpExporter`  to some value does not work = nothing gets exported, but no runtime exception (using `HttpProtobuf`)

**What is the expected behavior?**

I expect that when I set the `Endpoint` on `AddOtlpExporter` options, the traces get exported using that endpoint.

**What is the actual behavior?**

When the `Endpoint` is set, it does not send anything to the specified endpoint. Instead, I think it falls back to some default value (?)

## Reproduce

1. Have [jaegertracing/all-in-one](https://hub.docker.com/r/jaegertracing/all-in-one) running to collect and show the traces through docker compose:

```yaml
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4318:4318
```

2. In `Program.cs` set the `Endpoint`

```csharp
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var serviceName = typeof(Program).Assembly.GetName().Name ?? "Unknown service";
builder.Services.AddOpenTelemetry().WithTracing(builder =>
{
    builder
        .AddConsoleExporter()
        .AddOtlpExporter(options =>
        {
            options.Protocol = OpenTelemetry.Exporter.OtlpExportProtocol.HttpProtobuf;
            // Set the Endpoint to the default HttpProtobuf value explicitly (in theory should not have any impact as it's the same default value)
            options.Endpoint = new Uri("http://localhost:4318/"); // If you comment out this line, it works correctly
        })
        .ConfigureResource(builder => builder.AddService(serviceName))
        .AddAspNetCoreInstrumentation();
});

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();

app.MapGet("/hello", () =>
{
    return Results.Ok();
});

app.Run();
```

3. Visit `localhost:16686` to see if jaeger received any traces

## Additional Context

In the end, I found that setting `OTEL_EXPORTER_OTLP_ENDPOINT` works correctly

**Comment by Kielek** [comment]
If you manually set the endpoint, you have to put there full URL. In this case, it should be `http://localhost:4318/v1/traces` for traces.

**Comment by BenasB** [comment]
Ahh, sorry then. It was not clear from the docomentation as the comment for `Endpoint` notes the default value without the `v1/traces` (unless this is Jaeger specifc (I'm quite new to this), then it would make sense not to include in the OTEL docs)
