### ISSUE TITLE
Tracer.StartActiveSpanFromActivity does not copy Activity.Tags

### ISSUE THREAD

**Issue by fbeltrao** [open-telemetry/opentelemetry-dotnet#430]
When creating a Span from an activity the tags are not copied. Application Insights, copies it (Tracer.StartActiveSpanFromActivity vs TelemetryClient.StartOperation)

**Comment by brunomasantos** [comment]
I would like to make contributions to this project. Wondering if I can pick this up? 

Just to be clear, the objective is to copy the Activity.Tags for the Span.Attributes?

**Comment by tarekgh** [comment]
Just a small note, Span.Attributes internally defined as [EvictingQueue](https://github.com/open-telemetry/opentelemetry-dotnet/blob/79828a209e573248913182dcef56be411d09be18/src/OpenTelemetry/Trace/Internal/EvictingQueue.cs#L24). Would be nice if we can add a constructor to EvictingQueue which takes IEnumerable returned from Activity.Tags so we don't have to call Span.SetAttribute for each item in the tags.

**Comment by brunomasantos** [comment]
Can you take a look at https://github.com/open-telemetry/opentelemetry-dotnet/pull/572 to see if it is the desired approach to solve the issue?

**Comment by tarekgh** [comment]
I added a minor comment there. 

Also, I added a question to @SergeyKanzhelev https://github.com/open-telemetry/opentelemetry-dotnet/pull/572#discussion_r404423390
