### ISSUE TITLE
AddSqlClientInstrumentation throws MethodAccessException

### ISSUE THREAD

**Issue by christophearg** [open-telemetry/opentelemetry-dotnet#4300]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

Installed packages:

"OpenTelemetry" Version="1.4.0"
"OpenTelemetry.Exporter.Console" Version="1.4.0"
"OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0"
"OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.4.0-rc.2"
"OpenTelemetry.Extensions.Hosting" Version="1.4.0"
"OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.10"
"OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.0.0-rc9.10"
"OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.10"
"OpenTelemetry.Instrumentation.Runtime" Version="1.0.0"
"OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc9.10"

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

net7.0

## Symptom

Unhandled exception. System.MethodAccessException: Attempt by method 'OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracerProviderBuilderExtensions.AddInstrumentation(OpenTelemetry.Trace.TracerProviderBuilder, System.Func`2<System.IServiceProvider,!!0>)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracerProviderBuilderExtensions.AddInstrumentation[T](TracerProviderBuilder tracerProviderBuilder, Func`2 instrumentationFactory)
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.AddSqlClientInstrumentation(TracerProviderBuilder builder, String name, Action`1 configureSqlClientInstrumentationOptions)
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.AddSqlClientInstrumentation(TracerProviderBuilder builder, Action`1 configureSqlClientInstrumentationOptions)

**What is the expected behavior?**
No exception^^

Just call AddSqlClientInstrumentation

**Comment by vishweshbankwar** [comment]
@christophearg Could you please share the following information?

List of all OpenTelemetry NuGet
packages and version that you are
using (e.g. OpenTelemetry 1.0.2):

**Comment by christophearg** [comment]
Sure, I added it in the message

**Comment by vishweshbankwar** [comment]
@christophearg Try updating the following packages to latest rc version.

"OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.10"
"OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.0.0-rc9.10"
"OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.10"
"OpenTelemetry.Instrumentation.Runtime" Version="1.0.0"
"OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc9.10"

**Comment by MeaningOfLights** [comment]
I get the same error message ONLY when I add this line:

`app.UseOpenTelemetryPrometheusScrapingEndpoint();`

As it needs a reference to: OpenTelemetry.Exporter.Prometheus.AspNetCore - I tried rolling back a few versions and same issue.

**Comment by azurecorner** [comment]
I have same issue using dotnet8 

System.MethodAccessException
  HResult=0x80131510
  Message=Attempt by method 'Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(Microsoft.Extensions.DependencyInjection.IServiceCollection)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.
  Source=OpenTelemetry.Extensions.Hosting
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(IServiceCollection services)
   at Program.<Main>$(String[] args) in ..src\WebApi\Program.cs:line 15

`builder.Services.AddOpenTelemetry()
    .ConfigureResource(resource => resource
        .AddService(serviceName: "builder.Environment.ApplicationName"))
    //.WithTracing(tracing => tracing
    //    .AddAspNetCoreInstrumentation()
    //    .AddConsoleExporter())
     .WithMetrics(builder => builder
     .AddMeter("Microsoft.AspNetCore.Hosting")
     .AddMeter("Microsoft.AspNetCore.Server.Kestrel")
     .AddMeter("System.Net.Http")
      .AddPrometheusExporter().
      AddOtlpExporter()
    //.AddAspNetCoreInstrumentation()
    //.AddConsoleExporter((exporterOptions, metricReaderOptions) =>
    //{
    //    metricReaderOptions.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = 1000;
    //})
    );

builder.Logging.AddOpenTelemetry(options =>
{
    options.AddOtlpExporter();
});
.........................

app.MapPrometheusScrapingEndpoint();
`

**Comment by bitbonk** [comment]
I also have a similar issue in NET 8:

> System.MethodAccessException: Attempt by method 'Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(Microsoft.Extensions.DependencyInjection.IServiceCollection)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.
   at Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(IServiceCollection services)
   at Program.<Main>$(String[] args) in /Users/bitbonk/source/LogDemo/LogDemo.SimpleWorker/Program.cs:line 18

here is the list of my referenced packages:

```csproj
<PackageReference Include="Grafana.OpenTelemetry" Version="0.6.0-beta.2" />
<PackageReference Include="Microsoft.Extensions.Compliance.Redaction" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0"/>
<PackageReference Include="Microsoft.Extensions.Telemetry" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Telemetry.Abstractions" Version="8.0.0" />
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.7.0-alpha.1" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.7.0-alpha.1" />
<PackageReference Include="Seq.Extensions.Logging" Version="6.1.0" />
```

@vishweshbankwar Since you closed the issue, how did you solve it?

**Comment by emouawad** [comment]
Same issue

**Comment by willvelida** [comment]
Just adding a workaround (for now), I had both **OpenTelemetry.Exporter.Prometheus.AspNetCore** and **OpenTelemetry.Extensions.Hosting** versions set to *1.7.0-rc.1* and the error resolved.

```
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.7.0-rc.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.7.0-rc.1" />
  </ItemGroup>
```

**Comment by matteocontrini** [comment]
Same issue here simply by following Microsoft's getting started: https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?view=aspnetcore-8.0#create-the-starter-app

@willvelida's solution works!
