### ISSUE TITLE
OpenTelemetry.Instrumentation.AspNetCore didn't export Exception metrics with value

### ISSUE THREAD

**Issue by fkpwolf** [open-telemetry/opentelemetry-dotnet#4309]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):
```
<PackageReference Update="Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0-beta.7" />
<PackageReference Update="OpenTelemetry" Version="1.4.0-rc.3" />
<PackageReference Update="OpenTelemetry.Exporter.Console" Version="1.4.0-rc.3" />
<PackageReference Update="OpenTelemetry.Exporter.Geneva" Version="1.4.0-rc.3" />
<PackageReference Update="OpenTelemetry.Extensions.Hosting" Version="1.4.0-rc.3" />
<PackageReference Update="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.12" />
<PackageReference Update="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.12" />
```
* TBD

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):
`net6.0`

## Symptom

We utlize Exception metrics to monitor Azure application status before we migrate to OpenTelemetry. But now it doesn't work anymore.

**What is the expected behavior?**
I can see Exception Metrics is exported and has real value when Exception happened.

**What is the actual behavior?**
Exception Metrics is exposed but has no value (always =0)

## Reproduce

It is a simaple App service:
```csharp
public void ConfigureServices(IServiceCollection services)
{
  services.AddOpenTelemetry().WithMetrics(builder =>
  {
      builder
      .SetResourceBuilder(OpenTelemetryResourceBuilder)
      .AddAspNetCoreInstrumentation()
      .AddHttpClientInstrumentation()
      .AddMeter(Metrics.MetricsMeterId)
      .AddConsoleExporter()
      .AddGenevaMetricExporter(options =>
      {
          options.ConnectionString = $"Account={this.Configuration["GenevaMetricAccountName"]};Namespace={this.Configuration["GenevaMetricNamespace"]}";
      });
  }).StartWithHost();
}
```

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

cc @OsmondJiang

**Comment by cijothomas** [comment]
What is "Exception Metrics"? AspNetCore instrumentaion has no such metric

**Comment by fkpwolf** [comment]
@cijothomas it is about Exception count. Before we migrated to OTel, we can see the metric and other like "\Memory\Available MBytes"

**Comment by OsmondJiang** [comment]
Hi @cijothomas, thanks for the replying.

Our ask is whether OpenTelemetry DotNet SDK supports Application Insight Standard Exception Metrics: [Exceptions(exceptions/count)](https://learn.microsoft.com/en-us/azure/azure-monitor/app/standard-metrics#exceptions-exceptionscount), because we are trying to replace our Geneva Agent Channel with OpenTelemetry DotNet SDK but found some 1DS's standard metrics are not supported, which are heavily used in our alert rules.

**Comment by cijothomas** [comment]
> Our ask is whether OpenTelemetry DotNet SDK supports Application Insight Standard Exception Metric

No. OpenTelemetry supports metrics from OpenTelemetry specification/conventions only and won't support vendor specific metrics. You should ask in Application Insights/Azure Monitor repos if there is any recommendations/alternates to unblock your needs.

**Comment by OsmondJiang** [comment]
@cijothomas, thanks for the explanation. Then we will not migrate our 1DS SDK to OpenTelemetry SDK.
