### ISSUE TITLE
Span started from Activity seems to requires it to have been started

### ISSUE THREAD

**Issue by fbeltrao** [open-telemetry/opentelemetry-dotnet#431]
Based on a few tests I have made, when starting a span from an Activity, the same requires the Activity to have been started (Activity.Start()).

In comparison, the same does not apply to ApplicationInsights SDK (TelemetryClient.StartOperation).

Is my assumption correct?

**Comment by lmolkova** [comment]
Yes, you are correct. Starting span from Activity is used to listen to instrumentation in .NET libraries (e.g. HttpClient, ASP.NET Core and some SDKs) which start activity and notify about it.

If you need to start span from not-started Activity, you can construct SpanContext out of the Activity and pass it to StartSpan overload.

We are working on better integration story between Span and Activity in .NET 5.0 timeframe.

StartOperation in AI SDK expects not-started activity, but should work with started one as well.  
Please reopen if you need more info.

**Comment by fbeltrao** [comment]
@lmolkova thanks for the clarification
