### ISSUE TITLE
Metric cardinality limited

### ISSUE THREAD

**Issue by gballigand** [open-telemetry/opentelemetry-dotnet#4315]
Hi, 
I'm implementing metrics into my C# application. I would like to use some high cardinality metrics but it seems that when a cardinality reach 2000, otlp stop the metric collection.
However, I didn't find anything related to an existing cardinality limit in otlp and no way to get more than 2000.

Thank you

**Comment by vishweshbankwar** [comment]
check https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk#changing-maximum-metricpoints-per-metricstream

**Comment by gballigand** [comment]
Thank you so much, my bad I didn't search correctly 

> check https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk#changing-maximum-metricpoints-per-metricstream
