### ISSUE TITLE
Setting TraceContextPropagator as default propagator results in different traceIds in chained requests

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet#4326]
# Bug Report

OpenTelemetry AspNetCore instrumentation 1.4.0
OpenTelemetry Http instrumentation 1.4.0

Tried on net6.0

## Symptom

When setting TraceContextProvider as the default propagator, connected requests activities have different traceIds. 

`Sdk.SetDefaultTextMapPropagator(new TraceContextPropagator());` is used to set the propagator.

**What is the expected behavior?**
All activities across distributed services in a request chain has the same traceId. 

What did you expect to see?
Traces for all of these requests have the same traceId.

**What is the actual behavior?**
Traces have different traceIds

What did you see instead?

## Reproduce
Just use `Sdk.SetDefaultTextMapPropagator(new TraceContextPropagator());` to set the propagator and you should see the issue in your existing working system.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

Works as expected without explicitly setting the propagator, but setting it breaks the experience

**Comment by dpk83** [comment]
I am calling the same service in a loop. Currently it’s in an application that has a lot of stuff. I will recreate this in an isolated sample and share it with you.

**Comment by dpk83** [comment]
@vishweshbankwar Found the problem. It breaks if I explicitly add the following sources on the tracerProviderBuilder
`_ = builder.AddSource("Microsoft.AspNetCore").AddSource("System.Net.Http");` 

```csharp
            _ = services.AddOpenTelemetry().WithTracing(builder =>
            {
                builder.AddAspNetCoreInstrumentation();
                builder.AddHttpClientInstrumentation();
                builder
                    .AddSource("Microsoft.AspNetCore")
                    .AddSource("System.Net.Http");
            });
```

**Comment by dpk83** [comment]
> In general if you are using instrumentation library, you don't need to add sources explicitly. Instrumentation library will do that in net7.0 onwards.

Yes, but if someone accidently end up doing that or do it for a different purpose then it just breaks the tracing completely

**Comment by vishweshbankwar** [comment]
> > In general if you are using instrumentation library, you don't need to add sources explicitly. Instrumentation library will do that in net7.0 onwards.
> 
> Yes, but if someone accidently end up doing that or do it for a different purpose then it just breaks the tracing completely.
> 
> E.g. There are high chances some services would just want to enable all activities and use wildcard `builder.AddSources("*")` and tracing will just not work correctly

Makes sense, I am not sure if we can do anything on sdk/instrumentation library side though. The issue is with ASP.NET Core itself.
