### ISSUE TITLE
Custom Sampler doesn't seem to drop traces

### ISSUE THREAD

**Issue by navin-rai** [open-telemetry/opentelemetry-dotnet#4330]
## If I set probability as 0, then it should have dropped entire health traces.
```
 internal class CustomHeadSampler : Sampler
	{
		private readonly long _idUpperBound;
		private readonly double _probability;
		public CustomHeadSampler(double probability)
		{
			_probability = probability;

			// The expected description is like CustomHeadSampler{0.000100}
			Description = "CustomHeadSampler{" + _probability.ToString("F6", CultureInfo.InvariantCulture) + "}";
			if (_probability == 0.0)
			{
				_idUpperBound = Int64.MinValue;
			}
			else if (_probability == 1.0)
			{
				_idUpperBound = Int64.MaxValue;
			}
			else
			{
				_idUpperBound = (long)(probability * Int64.MaxValue);
			}
		}
		public override SamplingResult ShouldSample(in SamplingParameters samplingParameters)
		{
			Activity currentActivity = Activity.Current;
			if (currentActivity is not null && currentActivity.Parent is not null)
			{
				Console.WriteLine("custom : " + currentActivity.Parent.DisplayName ?? "nothing");
				if (currentActivity.Parent.DisplayName.Contains("health", StringComparison.OrdinalIgnoreCase))
				{
					Span<byte> traceIdBytes = stackalloc byte[16];
					samplingParameters.TraceId.CopyTo(traceIdBytes);
					return new SamplingResult(Math.Abs(GetLowerLong(traceIdBytes)) < _idUpperBound);
				}
			}

			return new SamplingResult(SamplingDecision.RecordAndSample);
		}

		private long GetLowerLong(ReadOnlySpan<byte> bytes)
		{
			long result = 0;
			for (int i = 0; i < 8; i++)
			{
				result <<= 8;

				result |= bytes[i] & 0xff;
			}
			return result;
		}
	} 
```

**Comment by vishweshbankwar** [comment]
@navin-rai Simplest way would be to debug this and check what `ShouldSample` is returning when you set probability to 0.

**Comment by navin-rai** [comment]
@vishweshbankwar 
While debugging, I found that it comes to below bold code in TraceProviderSdk.cs file , after that it jumps to 3rd case , don't know why it jumps to just one line from 3rd case -

var samplingResult = this.sampler.ShouldSample(samplingParameters);

            switch (samplingResult.Decision)
            {
                **case SamplingDecision.Drop:
                    activity.IsAllDataRequested = false;
                    activity.ActivityTraceFlags &= ~ActivityTraceFlags.Recorded;**
                    break;
                case SamplingDecision.RecordOnly:
                    activity.IsAllDataRequested = true;
                    activity.ActivityTraceFlags &= ~ActivityTraceFlags.Recorded;
                    break;
                case SamplingDecision.RecordAndSample:
                    activity.IsAllDataRequested = true;
                    **activity.ActivityTraceFlags |= ActivityTraceFlags.Recorded;**
                    break;
            }
