### ISSUE TITLE
`SetErrorStatusOnException` doesn't set `Activity.Status`

### ISSUE THREAD

**Issue by MatisseHack** [open-telemetry/opentelemetry-dotnet#4333]
# Bug Report

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry 1.4.0

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can find this information from the `*.csproj` file):

* net7.0

## Symptom

`SetErrorStatusOnException` doesn't set `Activity.Status`. If I'm reading correctly, it looks like the exception processor calls into an extension method that sets tags on the activity instead:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/094124e9ee61466a5bbf182d923658cde2c2dcf5/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L42-L48

**What is the expected behavior?**

Spans that contained an exception should be marked as failed.

**What is the actual behavior?**

Some exporters (e.g. Jaeger via OTLP) recognize these tags and properly display the spans as failed. However, some exporters (e.g. [Azure.Monitor.OpenTelemetry.Exporter](https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.Exporter)) only look at `Activity.Status` and don't display the spans as failed.

## Reproduce

The following program exhibits this issue where failed spans do not show up as such in Azure:

```csharp
public class Program
{
    private static readonly ActivitySource MyActivitySource = new("MyCompany.MyProduct.MyLibrary");

    public static void Main()
    {
        using var tracerProvider = Sdk.CreateTracerProviderBuilder()
            .AddSource("MyCompany.MyProduct.MyLibrary")
            .SetErrorStatusOnException()
            .AddAzureMonitorTraceExporter()
            .Build();

        try
        {
            using (MyActivitySource.StartActivity("Foo"))
            {
                throw new Exception("Oops!");
            }
        }
        catch (Exception)
        {
            // swallow the exception
        }
    }
}
```

## Additional Context

Is there any reason to avoid setting `Activity.Status` for uncaught exceptions or is this implementation just a historical artifact from earlier versions of .NET?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#exporting-activity-status Removing bug tag, as this is not a bug.
