### ISSUE TITLE
Enable Nullable in OpenTelemetry.Api project

### ISSUE THREAD

**Issue by TimothyMothra** [open-telemetry/opentelemetry-dotnet#4338]
This is a breakout task of #3958, focusing on enabling Nullables for the entire OpenTelemetry.Api project.

This will be broken up into a few parts:

1. Consolidate NullableAttributes. #4293
    All projects will need access to more nullable attributes to resolve issues. 
2. Enable Nullables in csproj, Enable Nullables in PublicApi, Disable Nullable in remaining errant files, fully update PublicApi. #4339
    Working on any class in the public api will require the entire PublicApi files to also be updated and distract from the files within a PR.
    Instead, I want to disable nullables for any offending files in this project, and then follow up to address individual files.
3. Clean up individual files, removing all `nullable disable`.

**Comment by CodeBlanch** [comment]
#5801
