### ISSUE TITLE
[Question] Do we have in a Roadmap - export ExceptionTelemetry objects in ApplicationInsights

### ISSUE THREAD

**Issue by SychevIgor** [open-telemetry/opentelemetry-dotnet#434]
In ApplicationInsightsTraceExporter.cs class I see export of TraceTelemetry, RequestTelemetry and DependencyTelemetry types, but Azure Application Insights support also ExceptionTelemetry and AvailabilityTelemetry types. Also exceptions not list in SpanKind.cs enum

Will exporter support ExceptionTelemetry and AvailabilityTelemetry  or it's not on a roadmap (or even not part of opentelemetry specification)? 

We are working on a scenario when will use Hybrid deployment of some product. For Hybrid deployment customer requested an option to export application telemetry to different monitoring systems (Azure Application Insights, Prometeus and etc). We are looking on opentelemetry as a solution, but looks like it uses least common denominator.

**Comment by SychevIgor** [comment]
The same for pageviews and other tables/methods of native ApplicationInsights SDK 
![image](https://user-images.githubusercontent.com/578954/72141996-d9cd8780-33a4-11ea-8dd3-2f30d24eb1ff.png)

**Comment by cijothomas** [comment]
OpenTelemetry only will have Traces(Request/Dependency in applicationinsights), Logs(Traces in applicationinsights), Metrics(Metric in applicationinsights). 

Its possible we'll get Exception. But not likely for TrackAvailability/Event/Pageview. 

(Additional note: This repo no longer has ApplicationInsights exporter - it'll be hosted in github.com/microsoft/somewherenotyetfinalized)
