### ISSUE TITLE
[Question] Correct Target .Net Framework version

### ISSUE THREAD

**Issue by SychevIgor** [open-telemetry/opentelemetry-dotnet#435]
After some research I see some mismatch of .net framework versions across different libraries. 

Almost all project use .net46 and .standard
Like this exporter
![image](https://user-images.githubusercontent.com/578954/72146046-bad2f380-33ac-11ea-9ac2-4d14a6c49866.png)
In another hand, some other exporters use only .netstandard like this
![image](https://user-images.githubusercontent.com/578954/72146127-dfc76680-33ac-11ea-857d-c1a7d4d45bc2.png)

In the sametime - redis collector uses .net461
![image](https://user-images.githubusercontent.com/578954/72146173-f79eea80-33ac-11ea-9915-f96f73546739.png)

Some packages support net4.5
![image](https://user-images.githubusercontent.com/578954/72146606-dee30480-33ad-11ea-8cc1-eecb4d19bc4b.png)

and finally, some packages use .netstandard framework only, but in properties checking .net46 version like here
![image](https://user-images.githubusercontent.com/578954/72146242-18ffd680-33ad-11ea-96bc-35d53a80f99d.png)

So my question is - what is the minimum version of .net framework that all packages (at least all exporters) should support?

I'm ready to create PR, but don't know right direction.

**Comment by MikeGoldsmith** [comment]
Hi @SychevIgor 

We should have consistent target frameworks defined for the core OpenTelemetry projects (OpenTelemetry.Api & OpenTelemetry), which I believe should be `net46;netstandard2.0`.

Implementations of the APIs are not required to target a particular framework but I do agree we should have guidelines to try and target as close to the Core project frameworks as possible to have the widest compatibility.

**Comment by SychevIgor** [comment]
As of now- .net461 is a requirement only for RedisCollector due to https://www.nuget.org/packages/StackExchange.Redis/

**Comment by SychevIgor** [comment]
@MikeGoldsmith added PR to address it

**Comment by SychevIgor** [comment]
.net framework 4.5 is out of support and we should not use it https://support.microsoft.com/en-us/lifecycle/search/548

https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework
.NET Framework 4.5: .NET Framework 4.5 shipped both in Windows 8, Windows Server 2012 and as a stand-alone redistributable package. Support for .NET Framework 4.5 on all operating systems ended on January 12, 2016.

**Comment by MikeGoldsmith** [comment]
Looks good, thanks for the contribution @SychevIgor :+1:

**Comment by SergeyKanzhelev** [comment]
One reason we have `net45` in API package is that some libraries are still targeting it. Even though the final app will never run on it. Thus if we want to allow those libraries to reference OpenTelemetry we needed net45 support in `Api` package. `Sdk` package should not be referenced by libraries and typically only referenced by the app itself. Thus it doesn't need to support `net45`.


Also from meeting notes https://docs.google.com/document/d/1yjjD6aBcLxlRazYrawukDgrhZMObwHARJbB9glWdHj8/edit#:

Sergey: Filed: https://github.com/dotnet/corefx/issues/42305 for better context support by .NET
Switching OpenTelemetry.Api - switch to net46 from net45.

@austinlparker : there are OTracing dependencies on net45. Personal feeling should target net46+
Support for bridge for OpenTracing may be a problem.
OpenTracing NET45/46 switch

**Comment by SychevIgor** [comment]
benchmark is even 462
![image](https://user-images.githubusercontent.com/578954/72182047-b8e45100-33fb-11ea-8a6b-5a63733fa8a8.png)
