### ISSUE TITLE
Version upgrade to 1.4.0 and higher stops writing APM metrics to Elastic

### ISSUE THREAD

**Issue by brismonis** [open-telemetry/opentelemetry-dotnet#4350]
# Bug Report

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using:
Bug occurring for this version and higher:
* "OpenTelemetry" Version="1.4.0"
* "OpenTelemetry.Api" Version="1.4.0"
* "OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0"
* "OpenTelemetry.Extensions.Hosting" Version="1.4.0"

Runtime version: net7.0

## Symptom

Problem: No apm metrics are logged anymore after version upgrades. We changed nothing else on our side - same settings, configs etc. but Elastic is not getting APM metrics, although they worked perfectly fine before. 
Before we used it like that to register it into our ServiceCollection:
`services.AddOpenTelemetryMetrics(builder =>
        {
            builder.AddMeter(serviceName);
            builder.AddOtlpExporter();
});`

And we adjusted this code accordingly to the upgrade to this:
`services.AddOpenTelemetry().WithMetrics(builder =>
        {
            builder.AddMeter(serviceName);
            builder.AddOtlpExporter();
});`

It's **working** with these versions:
* "OpenTelemetry" Version="1.3.2"
* "OpenTelemetry.Api" Version="1.3.2"
* "OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.3.2"
* "OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.4"

It's **NOT working** with these versions:
* "OpenTelemetry" Version="1.4.0"
* "OpenTelemetry.Api" Version="1.4.0"
* "OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.4.0"
* "OpenTelemetry.Extensions.Hosting" Version="1.4.0"

And also **NOT** with the newest Version:
* "OpenTelemetry" Version="1.5.0-alpha.1"
* "OpenTelemetry.Api" Version="1.5.0-alpha.1"
* "OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.5.0-alpha.1"
* "OpenTelemetry.Extensions.Hosting" Version="1.5.0-alpha.1"

**What is the expected behavior?**
We are expecting that a version upgrade is not breaking functionality. We're using it as described in https://opentelemetry.io/docs/instrumentation/net/getting-started/

**What is the actual behavior?**
Changing nothing but the version to the mentioned above breaks our elastic logging. Elastic is not getting any APM metrics anymore - the sender side seems broken? It stops us from monitoring our deployment enviroments.

## Reproduce

Since this is used in a complex customer project, I cannot provide a code example. But I can surely give more information and code snippets if needed.

**Comment by utpilla** [comment]
Could you try the [self-diagnostics](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry#self-diagnostics) troubleshooting feature and provide us the generated log file?

You can start with using a `LogLevel` of `Warning` in the json configuration file as shown below. This would capture the any events with a level of `Warning` and above that were logged when the application ran.
```json
{
    "LogDirectory": ".",
    "FileSize": 1024,
    "LogLevel": "Warning"
}
```

If the generated file does not contain any entries then, you could try it again with a `LogLevel` of `Verbose`.

**Comment by brismonis** [comment]
Hello @utpilla, thanks for your suggestion. I did accordingly to your answer and generated some log files. 
To have a comprison I attached two logs with the working and non-working versions:

It's **working** with these versions, everything succeeded in the logs:
[WorkingVersion-Bff.exe.18584.log](https://github.com/open-telemetry/opentelemetry-dotnet/files/11137722/WorkingVersion-Bff.exe.18584.log)
* "OpenTelemetry" Version="1.3.2"
* "OpenTelemetry.Api" Version="1.3.2"
* "OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.3.2"
* "OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.4"

Then I did nothing but upgrading the OpenTelemetry Versions.
It's **NOT working** with these versions and there are indeed some issues in the logs:
[NotWorking-Bff.exe.9148.log](https://github.com/open-telemetry/opentelemetry-dotnet/files/11137767/NotWorking-Bff.exe.9148.log)
* "OpenTelemetry" Version="1.5.0-alpha.1"
* "OpenTelemetry.Api" Version="1.5.0-alpha.1"
* "OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.5.0-alpha.1"
* "OpenTelemetry.Extensions.Hosting" Version="1.5.0-alpha.1"

I found following issues in the log:
* `2023-04-03T10:52:17.9811209Z:OpenTelemetry TracerProvider was not found in application services. Tracing will remain disabled.`
* `2023-04-03T10:53:23.0455534Z:Exporter failed send data to collector to {0} endpoint. Data will not be sent. Exception: {1}{http://localhost:4317/}{Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. (localhost:4317) SocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.", DebugException="System.Net.Http.HttpRequestException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. (localhost:4317)`

I'm open to suggestions for changes!

**Comment by alanwest** [comment]
@brismonis I suspect there's more to the config than just what you've shared:

```csharp
services.AddOpenTelemetry().WithMetrics(builder => { builder.AddMeter(serviceName); builder.AddOtlpExporter(); });
```

I created a simple application that might help you generate a repro of your issue https://github.com/alanwest/otlp-dotnet-example. As you can see from this example, I'm [configuring metrics](https://github.com/alanwest/otlp-dotnet-example/blob/fce9b62481cbb7d4efe8a229d70e94f358087bec/app/Program.cs#L6-L13) almost exactly in the same way you are.

The issue could be a number of things, maybe you're using `meterProvider.ConfigureServices` or the likes somewhere in your code to register dependent services?

**Comment by brismonis** [comment]
Is there any update on this? Can anyone answer the question from my last comment?
