### ISSUE TITLE
Link to Exemplar documentation broken in Release note for 1.5.0-alpha.1

### ISSUE THREAD

**Issue by jvmdc** [open-telemetry/opentelemetry-dotnet#4351]
It points to: https://github.com/open-telemetry/opentelemetry-dotnet/docs/metrics/customizing-the-sdk/README.md#exemplars

Probably should point to https://github.com/open-telemetry/opentelemetry-dotnet/tree/core-1.5.0-alpha.1/docs/metrics/customizing-the-sdk#exemplars for now until documentation is in place in the main branch

**Comment by jvmdc** [comment]
Oops, accidentally created it as a question.

**Comment by utpilla** [comment]
Thanks for reporting this! It's fixed now.
