### ISSUE TITLE
Consider using GetHashCode in TraceIdRatioBasedSampler?

### ISSUE THREAD

**Issue by pbiggar** [open-telemetry/opentelemetry-dotnet#4365]
I've been looking at a TraceIdRatioSampler, which has some [bitwise operations to try and get a ratio from the traceID](https://github.com/open-telemetry/opentelemetry-dotnet/blob/a61711d0c37346acfe0f3b096c6ac5a919c9c155/src/OpenTelemetry/Trace/TraceIdRatioBasedSampler.cs#L78). It copies the TraceID into a span, then iterates over its lower 8 bits to get an int64.

It seems like calling [GetHashCode](https://github.com/dotnet/runtime/blob/da7fbb7668d3cba3f2995675c6e8f0ad38caa8cd/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L889) would have the same probability distribution, and be faster?

**Comment by cijothomas** [comment]
See this: https://github.com/open-telemetry/opentelemetry-specification/issues/1413

I believe the current implementation is aligned with other languages, though not formally spec-ed, and changes this could have significant impact.
