### ISSUE TITLE
No feature available to disable SqlClient instrumentation

### ISSUE THREAD

**Issue by harshchaurasia2020** [open-telemetry/opentelemetry-dotnet#4372]
# Bug Report

There is no feature available to disable SqlClient instrumentation.
We have AddSqlClientInstrumentation() method to enable SqlClient instrumentation, but I have a requirement to enable/disable sqlclient instrumentation dynamically.

**Comment by cijothomas** [comment]
You can chose to *not* call AddSqlClientInstrumentation if you do not desire that capability. There is no ability to change (i.e add/remove) instrumentaion after the tracer provider is built. This is the same for all instrumentations, not just sqlclient.
