### ISSUE TITLE
Flaky unit test OpenTelemetry.Internal.Tests.SelfDiagnosticsConfigRefresherTest.SelfDiagnosticsConfigRefresher_OmitAsConfigured

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#4387]
# Bug Report

Test stability issue https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/4684112970/jobs/8299905100?pr=4381.

![image](https://user-images.githubusercontent.com/17327289/231829476-18c94f50-a378-4536-a9e9-4a394aed09c1.png)

@xiang17

**Comment by xiang17** [comment]
Seems like this test case read the output file from the other test case. I'll fix the dependency of the two test cases. However it happens very seldomly, so it might not be easy to actually verify the fix other than waiting to see if it happens in future.
