### ISSUE TITLE
Add receiver implementations

### ISSUE THREAD

**Issue by Jmorjsm** [open-telemetry/opentelemetry-dotnet#4398]
# Feature Request

**Is your feature request related to a problem?**

- I need to implement a .NET program which can receive OpenTelemetry signals over HTTP or by reading a log file.

**Describe the solution you'd like:**

- I could see value in a receiver class library written in c# (at least an abstract contract which other libraries can implement). I could see this being useful for other developers who would like to implement tooling in the OpenTelemetry ecosystem.
- Looking to gauge interest on this, and wondering if this is the correct place for it to end up, or if I should instead consider creating a separate repo if this project intends to focus on instrumentation and exporting from .NET applications.

**Describe alternatives you've considered.**
- N/A

## Additional Context

I have built a WIP example adding both:
- A file receiver, following the format the OpenTelemtry collector's file exporter uses to write to a file.
- An OTLP/HTTP receiver which could quickly be extended to also receive OTLP/GRPC.

**Comment by Jmorjsm** [comment]
Apologies if this isn't the best place for this. If I'd like to build an analytics platform, in .NET that can receive signals over gRPC or HTTP, I don't believe there's any libraries that would help with that?

Maybe I misunderstood and there should instead be an instance of the go collector which then puts the signals onto a queue or something which my platform could then read?

**Comment by cijothomas** [comment]
> Apologies if this isn't the best place for this. If I'd like to build an analytics platform, in .NET that can receive signals over gRPC or HTTP, I don't believe there's any libraries that would help with that?

The components shipped from this repo will not help with that. This repo only has libraries that help you instrument code, export code following the OpenTelemetry specification.

> Maybe I misunderstood and there should instead be an instance of the go collector which then puts the signals onto a queue or something which my platform could then read?

Collector already has several capabilities, including "exporters" to queues. I suggest to ask this qn in the Collector repo.

It may also be a good idea to ask in OpenTelemetry community slack channel, to get some leads.
