### ISSUE TITLE
[Question] Reason for not using BinaryReader in binary serializer

### ISSUE THREAD

**Issue by alexeyzimarev** [open-telemetry/opentelemetry-dotnet#440]
I read through the binary serializer code, including the VarInt story and string encoding/decoding. Seems like it uses the standard 7-byte int for the string length and then the char bytes for the string itself. The `BinaryReader` does the same job in `ReadString` but better (at least in my opinion). For example, it tries to return the whole string from chars if the length matches and I would expect it to happen most of the time. It lets the reader avoid using `StringBuilder`, which needs allocation and also can get tricky when it comes to the internal buffer expansion because the builder will create a new instance of itself when `Append` is called and the chunk buffer is exhausted. Overall, the reader is already there from the framework, why not just use it?

**Comment by lmolkova** [comment]
This code was first translated from Java and there is no reason to believe `BinaryReader` cannot be used. At the same time, AFAIK binary format is not standardized by the OTel community and optimizing the implementation is likely premature.

**Comment by alexeyzimarev** [comment]
I think 7 bit string encoding is pretty standard and cross-platform, otherwise it won’t be the same across Java and .NET implementation.

**Comment by lmolkova** [comment]
This is not string encoding https://github.com/w3c/trace-context-binary (e.g. trace-id is 16 bytes or two longs). also Java is big-endian, while .net depends on processor, so there certainly are concerns here.

**Comment by alexeyzimarev** [comment]
I see. Then, I think it would make sense to inspect the BinaryReader.ReasString closer to get some ideas about avoiding using an unbounded StringBuilder. For the sake of interoperability it would make sense to share plain and serialised values that comply with the standard to have some seed dataset to run tests against. Otherwise  I am not sure how interoperability and compliance to the standard can be tested.

**Comment by alexeyzimarev** [comment]
@lmolkova just figured out that I indeed wrote nonsense by trying to make "7-byte int for the string length and then the char bytes for the string itself" shorter :) From the spec you referred to, this issue is about parsing the `tracestate` only.

**Comment by alexeyzimarev** [comment]
I wrote a small test using the example `tracestate` from the spec and those two methods return identical results:

```csharp
        static string DecodeStringWithReader(Stream buffer)
        {
            return new BinaryReader(buffer, Encoding.ASCII).ReadString();
        }

        private static string DecodeString(Stream buffer)
        {
            var length = VarInt.GetVarInt(buffer);
            var builder = new StringBuilder();
            for (var i = 0; i < length; i++)
            {
                builder.Append((char)buffer.ReadByte());
            }

            return builder.ToString();
        }
```

**Comment by alexeyzimarev** [comment]
Ok, I benchmarked it and apparently using the `BinaryReader` is a bit slower.

**Comment by SergeyKanzhelev** [comment]
BinaryReader was temporarily taken out of the specification of OpenTelemetry. Need to remove it from the codebase or move to "misc" project for now.

**Comment by SergeyKanzhelev** [comment]
We deleted the BinarySerializer for now
