### ISSUE TITLE
Tests and benchmarks for OpenTelemetry.Api

### ISSUE THREAD

**Issue by alexeyzimarev** [open-telemetry/opentelemetry-dotnet#441]
I can't find any tests and benchmarking for the API project. In particular, I am interested to see tests and benchmarks for the remote context propagation and serialization. Lack of tests creates impediments for suggesting improvements. For example, I am eager to propose something for #407 but it's not easy, I can't be sure if my changes would work.

If there's no particular reason for those tests to be missing, I can add some. If that's ok, shall I create a new project like `OpenTelemetry.Api.Tests`?

Related question - I am not quite sure why all the tests for the `OpenTelemetry.Tests` project are in the `Impl` directory, is there a guideline I should follow when placing the test files?

**Comment by MikeGoldsmith** [comment]
Hi @alexeyzimarev 

We plan on adding additional testing and benchmark projects over the coming weeks. We see these as a prerequisite to a beta release. We actively encourage contributions, so if you feel you want to help, we'd be very happy for you to help.

**Comment by alexeyzimarev** [comment]
@MikeGoldsmith it would be great if you can give me some initial guidance in regards to my other questions, so I can put things in the right place.

**Comment by lmolkova** [comment]
@alexeyzimarev here are the [benchmarks for API](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/benchmarks/OpenTelemetrySdkBenchmarks.cs#L71). You can  expand this as you wish. 

Note that context propagation (if you mean context propagation over the wire) is done by .NET and hard to test without making real outgoing HTTP requests.

**Comment by alexeyzimarev** [comment]
I meant tests for Extract and Inject. Both methods are reasonably complex and I believe it’s possible to test those methods in isolation.

**Comment by lmolkova** [comment]
sure, but the will not be used in typical HTTP .NET app as serialization (for traceparent) is done by .NET [Activity](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L356)  in [HttpClient](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L254) and [ASP.NET Core](https://github.com/dotnet/aspnetcore/blob/master/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L253)

**Comment by lmolkova** [comment]
check OTel listener code [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/3905e7818947c9a1746e067f201dc45220822669/src/OpenTelemetry.Collector.Dependencies/Implementation/HttpHandlerDiagnosticListener.cs#L87). there is very similar check for Http-in listener

**Comment by alexeyzimarev** [comment]
Well, I would argue about the meaning of “typical” because we have tons of microservices and almost none of them use http. 

I get the point but I am very much interested in having a fast binary context serialiser. I could also refer to the OpenTracing .NET client that uses BinaryReader. I assume it complies with the standard, which OpenTelemetry is based upon for obvious reasons. 

That’s why I got curious, I don’t know the internals so we’ll to suggest the implementation but I spent some time looking around and it’s exactly the same but better as I mentioned. I believe it’s worth benchmarking both serialisers even for the sake of having a baseline and add tests to ensure the compliance. Unfortunately, there’s not many details about binary serialisation in Open Telemetry docs. But it might be a good sign since not specifying such details could mean that’s it’s already specified and doesn’t need more details...

**Comment by SergeyKanzhelev** [comment]
It is a good idea to create a benchmarks in 0.4 milestone to address potential fundamental issues before the 1.0.

@TimothyMothra can you take a look?

**Comment by alexeyzimarev** [comment]
Btw, I had to upgrade the `BenchmarkDotNet` package to 0.12, otherwise, I wasn't able to run it on .NET Core 3.1 runtime.

**Comment by SergeyKanzhelev** [comment]
CC: @TimothyMothra
