### ISSUE TITLE
Hide Exemplar support in advance of 1.5.0 release

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#4413]
It is not likely the specification for exemplars will be stable in time for our 1.5.0 release. Therefore, we will need to mark our support internal prior to the release. We can either choose to re-expose any public API with a 1.6.0-alpha release, or perhaps seek a better way to ship experimental features without the need to juggle changes to public API (e.g., hiding features behind experimental environment variables and/or requiring the use of reflection to access not yet exposed APIs).

**Comment by utpilla** [comment]
Completed in #4533
