### ISSUE TITLE
Make UseOpenTelemetryPrometheusScrapingEndpoint a real endpoint

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#4449]
# Feature Request

`UseOpenTelemetryPrometheusScrapingEndpoint` is middleware that provides an endpoint for Prometheus scraping.

This kind of feature is usually provided by an endpoint using ASP.NET Core endpoint routing. For example, `MapHealthChecks` configures the health probe endpoint. See https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-7.0#basic-health-probe.

An endpoint allows the feature to more easily hook into other endpoint-aware middleware and routing features. Also, routing is very fast, and the check for the scraping path can happen at the same time as routing instead of extra overhead.

**Describe the solution you'd like:**

Add a `MapPrometheusScraping` extension method for this task.

**Comment by CodeBlanch** [comment]
@JamesNK We also have these extensions: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.Prometheus.AspNetCore/PrometheusExporterEndpointRouteBuilderExtensions.cs

Is what you are asking for something different?

**Comment by klinki** [comment]
Oh, it is there I just didn't notice.

But I have found it now - https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.Prometheus.AspNetCore/PrometheusExporterEndpointRouteBuilderExtensions.cs

So you can ignore my previous comment :)

**Comment by JamesNK** [comment]
I think this is already done with `MapPrometheusScrapingEndpoint`. I didn't see this before creating the issue.

**Comment by rmannibucau** [comment]
Hi,

AFAIK there is a gap between use and map flavors: the use enables to not enable the endpoint when on a different URL (very important for kubernetes where you rarely - never? - want to bind the endpoint on the main URL which is forwarded to services+ingresses for ex.

However the coming feature to disable http metrics (https://github.com/dotnet/aspnetcore/pull/56036) will not be available to the middleware directly and will need a hack to be enabled.

So overall I think it would be great to merge both API in terms of capabilities - in particular when the impl is pretty close.

Goals (to get by default using the minimal api):

1. Be able to expose the endpoint only on some url/server and not globally
2. Be able to ignore the metrics related to the opentelemetry endpoints/pipelines

Side note: this can be related to other endpoints - health, tracing, ... - didn't review them all.

Is it possible to reopen and fix even if it requires v9 to be fully functional?
