### ISSUE TITLE
Is it possible to read metrics from prometheus endpoint and export to OTEL agent in OTLP format?

### ISSUE THREAD

**Issue by yesmarket** [open-telemetry/opentelemetry-dotnet#4457]
# Question

I'm intending to use the OpenTelemetry dotnet package to push metrics to an OTEL collector agent.

Some of our existing dotnet apps already expose Prometheus metrics (using the [prometheus-net](https://github.com/prometheus-net/prometheus-net) package). Is there a way to read metrics from Prometheus and export to the OTEL collector agent in OTLP format? I noticed you can do this in Java using a Micrometer shim - see [here](https://github.com/open-telemetry/opentelemetry-java-docs/blob/367b31d59dffb20dec2009bd96e5c58cd8516ff1/micrometer-shim/src/main/java/io/opentelemetry/example/micrometer/Application.java#L26)

Cheers.

**Comment by cijothomas** [comment]
OTEL Collector can scrape for Prometheus Metrics. You do not need any .NET package for achieving this....

**Comment by yesmarket** [comment]
can you please give me an example about how to do this... or point me to some documentation...

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
