### ISSUE TITLE
How to properly deal with tracing exporter exceptions?

### ISSUE THREAD

**Issue by JoeMarkov** [open-telemetry/opentelemetry-dotnet#4459]
# Question

when I add the Jaeger exporter, then everything works fine:

```
                    o.AddJaegerExporter(o =>
                    {
                        o.AgentHost = configuration["JaegerHost"];
                        o.AgentPort = 6831;
                    });

```
But, when I start up my application and the jaeger host is not reachable or available, then my application crashes (won't start).

```
[15:36:34 FTL] Application terminated unexpectedly
System.Net.Sockets.SocketException (0x00002AF9): No such host is known.
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)
   at System.Net.Sockets.UdpClient.Connect(String hostname, Int32 port)
   at OpenTelemetry.Exporter.Jaeger.Implementation.JaegerUdpClient.Connect()
   at OpenTelemetry.Exporter.JaegerExporter..ctor(JaegerExporterOptions options, TProtocolFactory protocolFactory, IJaegerClient client)
   at OpenTelemetry.Exporter.JaegerExporter..ctor(JaegerExporterOptions options)
...

```

I rather have that my application won't start, if Jaeger is not reachable, instead of just crashing.

so, my question (to the documentation) is how should I properly deal with this type of issue? to prevent that trace exporting crashes my application.

**Comment by JoeMarkov** [comment]
I have two issues here.

Now I got some uncertainty here, will it also crash if the Jaeger instance goes down when it is up and running? Now I am unsure and I need to test that?

The second is that there is no guidance/example in the Readme here:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.Jaeger/README.md
about what the best practice is to handle exceptions? In the sample there should be some Try/catch, so I use your recommended way to catch these exceptions. 

Also, if Jaeger is temporary down at startup, but I want keep trying to use Jaeger? How do I make it to do a "best effort" if I don't care that I loose traces? 

But, I will try to follow your recommendation to use the OTLPExporter exporter instead. 

Thanks for replying :-)

**Comment by cijothomas** [comment]
> Now I got some uncertainty here, will it also crash if the Jaeger instance goes down when it is up and running? Now I am unsure and I need to test that?

No. OpenTelemetry components are allowed to fail at startup only, not ever after. If Jaeger goes down in the middle, the telemetry will be lost, but Exporters won't throw unhandled exception.

**Comment by cijothomas** [comment]
> > > Also, if Jaeger is temporary down at startup, but I want keep trying to use Jaeger? How do I make it to do a "best effort" if I don't care that I loose traces?
> > 
> > 
> > Not possible today with Jaeger Exporter, and unlikely to ever fix that in JaegerExporter, given its imminent deprecation.
> 
> Why are you talking about ending support for Jaeger?

I am not talking about end support for Jaeger. I am referring to deprecating the Jaeger dedicated exporter (which got deprecated already - https://www.nuget.org/packages/opentelemetry.exporter.jaeger).
