### ISSUE TITLE
Recorded flag not correctly propagated when using parent context

### ISSUE THREAD

**Issue by jwreford99** [open-telemetry/opentelemetry-dotnet#4474]
# Bug Report

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):
 - `OpenTelemetry.Exporter.InMemory` v1.4.0
 - `OpenTelemetry.Api`  v1.4.0
 - `OpenTelemetry` v1.4.0

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):
 - .NET 7.0

## Symptom
We are seeing child spans of non-recorded parents being recorded when initialised via a parent context.

**What is the expected behavior?**
We expected all children of non-recorded parents to not be recorded, **even** if in initialised via a parent context rather than nesting.

**What is the actual behavior?**
Parent span set to non-recorded
Child span created via parent context from parent ID is not created and is set to null
Grandchild span is created via normal nesting and because the child span was set to null this span is initialised as a new trace with the recording set to true

This leads to the grandchild spans being recorded.

## Reproduce
An Nunit test reproducing the same thing using the in memory exporter:
```
internal class OpenTelemetryTests
{
    [Test]
    public void OTelShouldDealWithRecordedProperly()
    {
        const string dontRecordActivityName = "DONT RECORD";
        const string activitySourceName = "ActivitySource";
        
        var exportedItems = new List<Activity>();
        using var tracerProvider = Sdk.CreateTracerProviderBuilder()
            .AddSource(activitySourceName)
            .AddInMemoryExporter(exportedItems)
            .SetSampler(new ParentBasedSampler(new SampleBasedOnName(neverSample: dontRecordActivityName)))
            .Build();

        var source = new ActivitySource(activitySourceName);

        bool? wasRootRecorded;
        bool? wasChildRecorded;
        bool? wasGrandChildRecorded;
        string? rootId;
        
        using (var root = source.StartActivity(dontRecordActivityName))
        {
            wasRootRecorded = root?.ActivityTraceFlags.HasFlag(ActivityTraceFlags.Recorded);
            rootId = root?.Id;
        }

        // Re-create a parent context from the root ID as though it had been transmitted between services
        var parentContext = ActivityContext.Parse(rootId!, null);
        using (var child = source.StartActivity("CHILD ACTIVITY", ActivityKind.Internal, parentContext))
        {
            wasChildRecorded = child?.ActivityTraceFlags.HasFlag(ActivityTraceFlags.Recorded);
            using (var grandchild = source.StartActivity("GRANDCHILD ACTIVITY"))
            {
                wasGrandChildRecorded = grandchild?.ActivityTraceFlags.HasFlag(ActivityTraceFlags.Recorded);
            }
        }
        
        // Root should not be recorded as it is a "DONT RECORD"
        Assert.That(wasRootRecorded, Is.False); // Is correct
        
        // Child should not be recorded
        Assert.That(wasChildRecorded, Is.False); // Is null but should be false
        
        // Grandchild should not be recorded
        Assert.That(wasGrandChildRecorded, Is.False); // Is true but should be false
        
        // No items should be exported
        Assert.That(exportedItems.Count, Is.EqualTo(0)); // Has one item (the grandchild), but should be empty
    }

    private class SampleBasedOnName: Sampler
    {
        private readonly string m_NeverSample;

        public SampleBasedOnName(string neverSample)
        {
            m_NeverSample = neverSample;
        }
        
        public override SamplingResult ShouldSample(in SamplingParameters samplingParameters)
        {
            return samplingParameters.Name.Equals(m_NeverSample) ? new SamplingResult(SamplingDecision.Drop) : new SamplingResult(SamplingDecision.RecordAndSample);
        }
    }
}
```

## Additional Context
This is the first issue I have raised against this repo, so if I have done something not quite right please let me know!

**Comment by vishweshbankwar** [comment]
> Re-create a parent context from the root ID as though it had been transmitted between services

For this, parentContext `IsRemote` should be set to `true` as your parent will be a remote parent.

> Grandchild should not be recorded
 Assert.That(wasGrandChildRecorded, Is.False); // Is true but should be false

It is expected with your current change as the "Grandchild" span is getting created as root .
