### ISSUE TITLE
Support UriPrefixes with wildcard

### ISSUE THREAD

**Issue by mayafit** [open-telemetry/opentelemetry-dotnet#4477]
# Bug Report
using OpenTelemetry.Exporter.Prometheus.HttpListener version 1.5.0-alpha.1   
with .net 7.0

## Symptom
I would like to use a wildcard when defining the URIPrefixes . 
i am doing so using the following code : 
```
        using MeterProvider meterProvider = Sdk.CreateMeterProviderBuilder()
                .AddMeter("MyAppMeter")
                .AddPrometheusHttpListener(opt =>
                {
                  opt.UriPrefixes = new string[] { "http://*:5000/" };
                })
                .Build();
```
**What is the expected behavior?**

I would expect the endpoint to be available on port 5000 

**What is the actual behavior?**
the endpoint is down

**Comment by cijothomas** [comment]
@Yun-Ting Do you recall if this was addressed?
