### ISSUE TITLE
No Trace information after deployed to AKS

### ISSUE THREAD

**Issue by sathoril** [open-telemetry/opentelemetry-dotnet#4488]
Hello all!

I'm having this issue on my .NET app. Whenever I deploy my app on k8s, my app seems to not send any trace to anywhere.

I have already tried sending manually a trace request using following curl from inside my app pod and I can see that trace reaching the collector (by looking at collectors logs). I tried the solution on that discuss, but apparently `StartWithHost` is not present on the version I'm using.

Does anyone know what happens?

`curl --location 'http://opentelemetry-collector:4318/v1/traces' \
--header 'Content-Type: application/json' \
--data '{
 "resourceSpans": [
   {
     "resource": {
       "attributes": [
         {
           "key": "service.name",
           "value": {
             "stringValue": "test-with-curl"
           }
         }
       ]
     },
     "scopeSpans": [
       {
         "scope": {
           "name": "manual-test"
         },
         "spans": [
           {
             "traceId": "71699b6fe85982c7c8995ea3d9c95df2",
             "spanId": "3c191d03fa8be065",
             "name": "spanitron",
             "kind": 2,
             "droppedAttributesCount": 0,
             "events": [],
             "droppedEventsCount": 0,
             "status": {
               "code": 1
             }
           }
         ]
       }
     ]
   }
 ]
}'`

### Discussed in https://github.com/open-telemetry/opentelemetry-dotnet/discussions/3209

<div type='discussions-op-text'>

<sup>Originally posted by **bardagadvergur** April 20, 2022</sup>
Hi ... I am completely lost as to what my issue can be so reaching out for help. I've added OpenTelemetry tracing to my .net core 6.0 application and in my local dev environment running in docker everything works as expected and traces are being exported. This is my tracing config:

`
       public static IServiceCollection AddTracing(this IServiceCollection services, string appName, IConfiguration configuration)
        {

            services.AddOpenTelemetryTracing(builder =>
            {
                builder
                    .AddAspNetCoreInstrumentation()
                    .AddMassTransitInstrumentation()
                    .AddSource(appName)
                    .AddSqlClientInstrumentation(opt => opt.SetDbStatementForText = true)
                    .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(appName))
                    .AddJaegerExporter(opts =>
                    {
                        opts.AgentHost = configuration.GetValue("Telemetry:Host", "jaeger");
                        opts.AgentPort = int.Parse(configuration.GetValue("Telemetry:Port", "6831"));
                        opts.Protocol = OpenTelemetry.Exporter.JaegerExportProtocol.UdpCompactThrift;
                        opts.ExportProcessorType = ExportProcessorType.Simple;
                    })
                    .AddConsoleExporter(opt =>
                    {
                        opt.Targets = OpenTelemetry.Exporter.ConsoleExporterOutputTargets.Console;
                    });
            });
            return services;
        }
    }
`
So locally I can see my traces in Jaeger as well as in the console. But when I deploy this application to my AKS kubernetes cluster no traces seem to be exported. I've validated the connection between tempo & my service using netcat & tcpdump so connectivity should not be an issue. I've also exposed the jaeger port of tempo in my cluster and have sent traces from my local environment into tempo running in the cluster so tempo is accepting traces just fine. After I was certain network connectivity was not an issue I added the console exporter and to my surprise no traces are visible in the logs on AKS.

These are the OpenTelemetry packages I am using:

`

		 "OpenTelemetry" Version="1.2.0-rc4"
		 
		 "OpenTelemetry.Exporter.Console" Version="1.2.0-rc4"
		 
		 "OpenTelemetry.Exporter.Jaeger" Version="1.2.0-rc4"
		 
		 "OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.1"
		 
		 "OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.1"
		 
		 "OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc9.1
		 
		 "OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.1"
		 
		 "OpenTelemetry.Contrib.Instrumentation.MassTransit" Version="1.0.0-beta2"
`</div>

**Comment by luizfbicalho** [comment]
> Could you update to the latest versions of all the packages, and if that did not help, collect sdk troubleshooting logs, so we can get more hints as to what might be going on.

How do I get the sdk troubleshoooting logs? 

I have a problem that everything works fine, but the SqlClient doesn't generate the trace information

**Comment by sathoril** [comment]
Sorry guys for the really really late reply.

I'm closing this, I managed to fix it, just by redoing everything, my guess is that some step was missing from the beginning. 

At the end, we didnt use OpenTelemetry, since we moved to DataDog later on and added DataDog injection on our AKS Pods.
