### ISSUE TITLE
Support dropping/start listening specific instruments/Meters dynamically

### ISSUE THREAD

**Issue by xakep139** [open-telemetry/opentelemetry-dotnet#4499]
# Feature Request

**Is your feature request related to a problem?**

Our services currently don't have an ability to stop sending or to start listening to specific instruments/Meters.
Consider the next scenario:
An incident has occurred - due to a high cardinality attribute or the presence of sensitive information in a metric data. To address the incident promptly, it is necessary to prevent the emission of that specific instrument/Meter. The goal is to quickly drop the problematic instrument/Meter using a configuration update.
We can't use [Views](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk#view) or [ExemplarFilters](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/metrics/extending-the-sdk/README.md#exemplarfilter). The former doesn't allow reconfiguring a View once [MeterProvider](https://github.com/open-telemetry/opentelemetry-dotnet/blob/3884bee5f244aec4da6aa5b961b0495583f7831d/src/OpenTelemetry/Metrics/MeterProviderSdk.cs#L162) is built, the latter doesn't provide us with the `Meter` or instrument related to the measurement.

**Describe the solution you'd like:**

Support of `IOptionsMonitor<T>` either in `MeterProviderBuiler` or in Views would be very helpful in that scenario.

**Describe alternatives you've considered.**

The only alternative that we have right now is to stop emitting all metrics by calling a `Shutdown()`/`Dispose()` on a `MeterProvider`, which would lead to loosing all metrics from a service.

## Additional Context

This issue is partially related to #4427

**Comment by cijothomas** [comment]
> The only alternative that we have right now is to stop emitting all metrics by calling a Shutdown()/Dispose() on a MeterProvider

You can dispose just the `Meter` instead of the whole MeterProvider. Would that be feasible?

Dynamically adding/modifying Views require lot of re-architecting, and will cause performance issues, so there are no immediate plans to make Views dynamic (i.e allow add/modify after provider is being built)

ExemplarFilter is *not* the solution for this, as it'll only influence if a measurement will be considered for Exemplar purposes, and wont influence the general metric pipeleine. There were requests to add the concept of MeasurementProcessor (similar to ActivityProcessor), but those are pending specification.

**Comment by xakep139** [comment]
That could be possible if the `Meter` was created by our code, in case of a third-party library that exposes its metrics it doesn't seem to be possible, unfortunately.
I understand that it's not straightforward to support rebuilding the `MeterListener` as it's not really designed to support that scenario, my hope was that there's another way of how we can workaround that.

**Comment by cijothomas** [comment]
The concept of MeasurementProcessor (once it lands in spec) would be one way to help with this issue. Unfortunately, that would require some support from the spec. I'd suggest to open an issue in the spec repo, as this is not just a .NET specific issue.
