### ISSUE TITLE
Missing Traces and Metrics via Open Telemetry

### ISSUE THREAD

**Issue by nasa-par** [open-telemetry/opentelemetry-dotnet#4543]
# Question

Created multiple .net 6 Rest API Solution (using open telemetry for collecting trace and metric data and send it to OtelCollector via HttpProtobuf) which is deployed over different  pods on AWS EKS cluster. Also, running OTel Collector as separate pod within same cluster which is responsible for sending data to Datadog.
While performing some load test on one of the application it is been observed that trace and metric data is no longer received on Datadog for application under load test after first few minutes, but the same is consistently being received of other applications running under normal conditions at same time.

On first impression, looking as per above situation it seems OpenTelemetry SDK blocks sending data on high rate usage of application. If we look into one direction it seems perfectly fine to have such behaviour but on the flip side if we can't see traces and metrics data on high load even for a single record, such Telemetry tools to be less useful. We should have some way to provide sampling rate like 5% for data will be sent.

So, wanted to check with Telemetry team, Is this is something intentionally been done or is this the bug? 
Also, let me know in case u feel I miss something related to configuration to enable traces in such situation.

**Comment by cijothomas** [comment]
Could you collect logs (https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#troubleshooting) and see if it hints at whats going on?

**Comment by cijothomas** [comment]
> We should have some way to provide sampling rate like 5% for data will be sent.

There is no such built-in sampler which can take "5% of data". There is [TraceIdRatioBasedSampler](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Trace/TraceIdRatioBasedSampler.cs), but that keeps X% of traceids, and that doesn't necessarily mean 5% of overall data.

**Comment by nasa-par** [comment]
Can't see it's occurrence since update to version 1.5.*
