### ISSUE TITLE
Not seeing root span with Stackdriver exporter

### ISSUE THREAD

**Issue by provegard** [open-telemetry/opentelemetry-dotnet#455]
Maybe related to #442 - because I don't see the method either.

In the Stackdriver Trace UI, the URL column contains the name of a child span:

![image](https://user-images.githubusercontent.com/795010/72668250-38d67080-3a25-11ea-93fd-321dd31964cb.png)

The name in the URL column belongs to a span that is a descendant of the root span.

I create the root span as follows in a custom ASP.NET Core middleware:

    var method = ctx.Request.Method;
    var routeName = ExtractRouteName(ctx);
    using (_tracer.StartActiveSpanFromActivity($"{method}:{routeName}", Activity.Current, out var span))
    {
        SetHttpAttributes(span, ctx, routeName);

Each time I create a new span, I use `StartActiveSpan` - i.e. I rely on "Implicit parent propagation". The root span never shows up in the URL column, nor does the parent span of the span that actually does show up. I have verified that the span that shows has a parent span ID.

If I use the Zipkin exporter and send traces to Jaeger, all spans show up correctly with the expected parent/child relationships - so this appears to be a Stackdriver exporter/Stackdriver Trace issue.

I'm using 0.2.0-alpha.100.

**Comment by provegard** [comment]
I just realized that I'm on an "old" version. I will try the MyGet feed and see what happens.

**Comment by provegard** [comment]
Same behavior with 164.

**Comment by MikeGoldsmith** [comment]
Hi @provegard - I think the recently merged #453 should also address this issue. If you could pull a recently MyGet feed build and test that would be really appreciated.

**Comment by provegard** [comment]
Thanks, I'll give it a shot!

**Comment by nmbro** [comment]
did it help?

**Comment by provegard** [comment]
Apologies, other things came in the way. :( I will try to test it during this week

**Comment by MikeGoldsmith** [comment]
@provegard have you been able to confirm if the changes in #453 helped?

**Comment by provegard** [comment]
I'm trying 195 now, but I'm not seeing anything at all in GCP. Something must be misconfigured - I'll see if I can get log messages from OT. I'll keep you posted.

**Comment by provegard** [comment]
I'm getting this in the event log in PerfView:

    ERROR: Exception in Command Processing for EventSource OpenTelemetry-Sdk: Unsupported type ReadOnlySpan`1 in event source." FormattedMessage="ERROR: Exception in Command Processing for EventSource OpenTelemetry-Sdk: Unsupported type ReadOnlySpan`1 in event source.

**Comment by provegard** [comment]
Same error with 179.

**Comment by reyang** [comment]
#665
