### ISSUE TITLE
Update OTLP to 0.20.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-dotnet#4557]
OTLP 0.20.0 was released: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.20.0

It is also the release candidate for upcoming 1.0.0.

Please update the OTLP exporter to use OTLP 0.20.0.

**Comment by Kielek** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/4554
