### ISSUE TITLE
Make SpanData thinner again

### ISSUE THREAD

**Issue by tarekgh** [open-telemetry/opentelemetry-dotnet#456]
Initially, SpanData was intended to be a thin wrapper around the Span object. with the change https://github.com/open-telemetry/opentelemetry-dotnet/pull/454 it started to support another scenario that needs creating the SpanData not from Span but other different fields. We initially made the SpanData a struct because it was a small size but now it is not. We should do one of the following:

- Either we make it a class instead of struct. This, not a good choice for the scenario when creating it as a wrapper to a span object because we'll have to allocate extra object for every span we handle.
- Or keep SpanData struct with all fields but ensure we always pass it by reference to the methods required it. This is risky for using bigger data on the stack and also any assignments operation can require big data copy.
- Create a Span object in the SpanData constructor and keep SpanData just a thin wrapper around the span object. This will require having a private span constructor for this scenario but that is ok as it is not public. I am inclining to this option as it will keep all the optimization we had before. We'll need to modify the following constructor to be like the following:

```C#
        public SpanData(
            string name,
            in SpanContext context,
            in ActivitySpanId parentSpanId,
            SpanKind kind,
            DateTimeOffset startTimestamp,
            IEnumerable<KeyValuePair<string, object>> attributes,
            IEnumerable<Event> events,
            IEnumerable<Link> links,
            Resource resource,
            Status status,
            DateTimeOffset endTimestamp)
        {
            this.span = new SpanSdk(name, context....);
        }
```

**Comment by tarekgh** [comment]
CC @lmolkova

**Comment by MikeGoldsmith** [comment]
Yeah, I agree option 3 feels the best and will allow us to remove the additional fields and simply the property getters too which us null coalescing `??` to switch between using the span or discrete property.
