### ISSUE TITLE
OpenTelemetry SqlClient Instrumentation - Filter not suppressing activities 

### ISSUE THREAD

**Issue by darshankumarparekh** [open-telemetry/opentelemetry-dotnet#4579]
# Bug Report

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that we are using:

OpenTelemetry 1.4.0
OpenTelemetry.Exporter.OpenTelemetryProtocol 1.4.0
OpenTelemetry.Instrumentation.Http 1.0.0-rc9.14
OpenTelemetry.Instrumentation.Wcf 1.0.0-rc.9
OpenTelemetry.Instrumentation.SqlClient 1.0.0-rc9.14

Runtime version: net472

## Symptom

We have Filter option available (in [SqlClientInstrumentationOptions.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.SqlClient/SqlClientInstrumentationOptions.cs)) to determine whether or not to collect telemetry about a command. The same is not working for net472 applications. I went through code for OpenTelemetry.Instrumentation.SqlClient.csproj also and I don't see Filter property is used anywhere for .NetFramework class (refer - [SqlEventSourceListener.netfx.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs)). So whether or not you set Filter property it's not at all suppressing sql activities. It always records activities.

**What is the expected behavior?**
It should determine whether or not to collect telemetry about a command based on Filter property.

What did you expect to see?
If Filter returns "false" or throws an exception than command telemetry data should not be collected for netframework applications.

**What is the actual behavior?**
If Filter returns "false" or throws an exception than also the command telemetry data is collected.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.SqlClient/README.md#filter Filter is not supported on .NET Framework.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.SqlClient/SqlClientInstrumentationOptions.cs#L158-L159

**Comment by darshankumarparekh** [comment]
@cijothomas I know Filter property is exposed. But it is not filtering activities and data is collected even though Filter returns "false". Ideally if Filter returns "false" telemetry data should not be collected.
