### ISSUE TITLE
SetStatus will overwrite OK with Error, which it should not do according to the spec

### ISSUE THREAD

**Issue by BenHewins** [open-telemetry/opentelemetry-dotnet#4582]
# Feature Request

The [specification of SetStatus](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status) says this:

> These values form a total order: Ok > Error > Unset. This means that setting Status with StatusCode=Ok will override any prior or future attempts to set span Status with StatusCode=Error or StatusCode=Unset.

The current `opentelemetry-dotnet` library does not do this - code like:
```
            activity.SetStatus(Status.Ok);
            activity.SetStatus(Status.Error);
```
will result in the final result being an error status. 

**Is your feature request related to a problem?**

This is quite annoying when trying to mark a span as OK in cases like a request being cancelled - the instrumentation see the exception and automatically overrides a manually set status of OK. There was some discussion of [similar issues here](https://github.com/open-telemetry/opentelemetry-specification/issues/1584).

**Describe the solution you'd like:**

The library to behave in accordance with the spec.

**Describe alternatives you've considered.**

Turning off automatic exception handling.

**Comment by jcauv4** [comment]
Just want to double click on this one since it is affecting my team as well.
In addition to the logic specified above, the spec also says "When span status is set to Ok it SHOULD be considered final and any further attempts to change it SHOULD be ignored."

We're trying to override 499s to be successful, but they often result in task canceled exceptions and get marked as error after we marked them as OK. 

We've investigated using an exception enricher to stop this, but the enricher is not hit in some of the cases for some reason.

**Comment by BenHewins** [comment]
> Just want to double click on this one since it is affecting my team as well. In addition to the logic specified above, the spec also says "When span status is set to Ok it SHOULD be considered final and any further attempts to change it SHOULD be ignored."
> 
> We're trying to override 499s (status code 0 in the instrumentation by default) to be successful, but they often result in task canceled exceptions and get marked as error after we marked them as OK.
> 
> We've investigated using an exception enricher to stop this, but the enricher is not hit in some of the cases for some reason.

In the end we stopped using the standard `SetErrorStatusOnException()` and instead added a custom implementation of [ExceptionProcessor](https://github.com/open-telemetry/opentelemetry-dotnet/blob/a09b6239929106b8073aaf2ce74215bacbd20ec7/src/OpenTelemetry/Trace/ExceptionProcessor.cs#L26) which had the logic that we wanted. Is in theory pretty flexible as you can then inspect all the `Activity`'s properties when making the OK/Error decision

**Comment by jcauv4** [comment]
That's a great idea - thanks for sharing! We'll take a look.
