### ISSUE TITLE
Custom metric disappears when adding package OpenTelemetry.Instrumentation.Http

### ISSUE THREAD

**Issue by rassmate** [open-telemetry/opentelemetry-dotnet#4589]
# Bug Report

See 
https://github.com/rassmate/dotnetmetrics

* TBD

net7.0, mac m2 air

* TBD

## Symptom

Custom metric disappears when open telemetry instrumentation is added

**What is the expected behavior?**

My custom metric still present

**What is the actual behavior?**

My custom metric disappears

## Reproduce

https://github.com/rassmate/dotnetmetrics

**Comment by vishweshbankwar** [comment]
@rassmate Could you upgrade your packages to latest version available and retest?

**Comment by rassmate** [comment]
@vishweshbankwar shame on me but thanks for spotting the obvious. I updated dependencies before but it got reverted and I didnt notice. It works now
