### ISSUE TITLE
Include System.Web.Http ActivitySource in net framework. 

### ISSUE THREAD

**Issue by wjy19890411** [open-telemetry/opentelemetry-dotnet#4599]
# Feature Request
Currently it's not included. https://github.com/open-telemetry/opentelemetry-dotnet/blob/3274c43bc1031e5b25cfa7a146d428b91abc5032/src/OpenTelemetry.Instrumentation.Http/TracerProviderBuilderExtensions.cs#L99-L109 System.Web.Http is also used quite often in net framework. Please include it so that users write less code.

**Is your feature request related to a problem?**

If so, provide a concise description of the problem.

**Describe the solution you'd like:**

What do you want to happen instead? What is the expected behavior?

**Describe alternatives you've considered.**

Which alternative solutions or features have you considered?

## Additional Context

Add any other context about the feature request here.

**Comment by cijothomas** [comment]
OpenTelemetry.Instrumentation.Http already supports both .NET/.NET Core **and** .NET Framework.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http

> Is your feature request related to a problem?
> 
> If so, provide a concise description of the problem.

^ If you are reporting a different issue, please fill the above template in full, so we can know what is the issue.
