### ISSUE TITLE
HTTP client metrics do not match semantic conventions

### ISSUE THREAD

**Issue by kmcclellan** [open-telemetry/opentelemetry-dotnet#4602]
The documentation for `OpenTelemetry.Instrumentation.Http` claims to uphold the [semantic conventions for the `http.client.duration` metric](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/metrics/semantic_conventions/http-metrics.md#metric-httpclientduration). However, I've noted the following discrepancies in [the implementation](https://github.com/open-telemetry/opentelemetry-dotnet/blob/2916b2de80522d4b1cafe353b3fda3fd629ddb00/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerMetricsDiagnosticListener.cs).

- Unit should be seconds but milliseconds are used.
- Attribute `network.protocol.name` is missing (should be `http`).
- Attribute `network.protocol.version` is missing (present as `http.flavor`).
- Attribute `server.address` is missing (present as `net.peer.name`).
- Attribute `server.port` is missing (present as `net.peer.port`).
- Attribute `http.request.method` is missing (present as `http.method`).
- Attribute `http.response.status_code` is missing (present as `http.status_code`).

**Comment by vishweshbankwar** [comment]
Please follow https://github.com/open-telemetry/opentelemetry-dotnet/issues/4484 issue for the changes.
