### ISSUE TITLE
Separate Context propagation (OTEP-66)

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#461]
Following [OTEP-66](https://github.com/open-telemetry/oteps/blob/master/text/0066-separate-context-propagation.md) correlation context, span context and metric context should have a generic top-level grouping.

This is a fairly large change, so I want to break it into a number of chunks.

- [ ] - Rename DistributedContext to CorrelationContext (#462)
- [ ] - Add new DistributedContext that contains span, correlation and metric contexts
(I'll add more soon)
- [ ] - Remove propagators from Tracing API (#466)

@SergeyKanzhelev I've tagged this as milestone v0.3 as the spec is targeted to that milestone. Let me know if we need to change it.

@tarekgh your recently merged #444 will likely be affected by this, and wanted to give you a heads up.

**Comment by cijothomas** [comment]
Context propagation is done now, along with GlobalPropagators. Closing.
