### ISSUE TITLE
In-memory statistical analysis

### ISSUE THREAD

**Issue by nullpainter** [open-telemetry/opentelemetry-dotnet#4628]
I am investigating the effort required to migrate our existing code which is using the abandoned [App Metrics](https://github.com/AppMetrics/AppMetrics) library.

One of the App Metrics measurement types maintains a sliding window collection of in-memory data which is flushed when reported/exported. It uses this to provide mean, median and other fixed percentile values for the reporting window. 

I am very green with OpenTelemetry, but it appears that the instruments don't provide this functionality.

If we have a instrument and we are wishing to capture median values of all captured data points with a sliding window, is this something that needs to be built from scratch? Or is there similar functionality out of the box that I just haven't found yet?

**Comment by cijothomas** [comment]
OpenTelemetry does not calculate percentiles in-process by-design. It bucketizes the measurements and exports them. It is upto the backend to use the buckets and derive percentile from it.
(Based on my understanding, AzureMonitor/ApplicationInsights does not support percentiles today)

Closing, as there is no change/fix required in OpenTelemetry. Feel free to reopen if you are have follow ups.
