### ISSUE TITLE
No telemetry from .net client

### ISSUE THREAD

**Issue by jsndk** [open-telemetry/opentelemetry-dotnet#4631]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/9006617/503535f7-e954-46d5-b2af-9470f7ba4894)

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

.net 6.0

## Symptom

The telemetry is not active when calling from .net application to a API with open telemetry. 

**What is the expected behavior?**
The telemetry is working with whatever client is calling. 

What did you expect to see?

Telemetry from the API. 

**What is the actual behavior?**
Calling a API from browser, swagger or postman, everything works. When calling from a .net API there is no telemetry. 

What did you see instead?
No telemetry from .net client. 

## Reproduce
Create a self-contained project using the template of your choice, apply the
minimum required code to result in the issue you're observing.
Zip with the complete solution. 
Call the api directly it works. (browser, postman, swagger)
Calling from a API .net with no openTelemetry, to the API with openTelemetry, it produces no telemetry. 
Check with break points, (no hit if called from .net client)

https://1drv.ms/u/s!AgA8qIpa_fswjfxZW2rMB51ag9iTGw?e=BTdnlk

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by jsndk** [comment]
If we use fiddler to remove the "traceparrent" from the call to the API, the telemetry works. So If a client sends a "traceparrent" in the header, the telemetry fails on the client. (unless the caller have implemented the openTelemetry), then it works.

**Comment by jsndk** [comment]
ok, more info. 
If the "traceparent" is set but the id ends with a -01 (instead of -00) the trace works. 
Also there are more differences in the activity between working and non working. 

Working 
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/9006617/b5115b59-28cf-4711-8fc7-d3364007aa4e)
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/9006617/debbf7f3-2515-4734-9cbb-f15d28f90cbb)
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/9006617/b1406736-a546-488f-ad30-bec204160ea4)


Not working 
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/9006617/0ba7e90c-87e5-4ccb-9a9f-73185949344b)
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/9006617/e8d3c993-2510-4f2d-8c0e-69c97ac64dae)
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/9006617/3be40519-1c21-4552-9ec8-7627d1217c1c)

Hope it helps in locating the issue / work around. 

Possible solution concept: A config / bool / something in the Telemetry setup (in program.cs) that forces the openTelemetry to kick in. (in the case it's deliberate that the trace is not working) 
As of now it's possible to bomb a api with openTelemetry, with out any one seeing it, if you add a traceparent with a -00 in the id.

**Comment by cijothomas** [comment]
The default sampler is the ParentBased, so if there is an incoming traceparent header with "00" sampling bit, then the trace will not be sampled. This is by design. 
If you do not want to make sampling decision based on incoming traceparent, then change the sampler from default to something else, like AlwaysOn or TraceIdRatioBased etc.

**Comment by jsndk** [comment]
Sounds good. 
I have looked at different implementations to do what you suggest. But nothing works. (environment var etc.) 
Can you show how to implement "Always on" in the code I provided?

```
            builder.Services.AddOpenTelemetry()
                .ConfigureResource(openTelemetryBuilder => openTelemetryBuilder
                    .AddService(serviceName: AppDomain.CurrentDomain.FriendlyName, serviceInstanceId: Environment.MachineName))
                    .WithTracing(tracingBuilder => tracingBuilder
                    .AddHttpClientInstrumentation(options =>
                    {
                    })

                    .AddAspNetCoreInstrumentation(options =>
                    {
                        // Note: Only called on .NET & .NET Core runtimes.
                        options.EnrichWithHttpRequest = (activity, httpRequestMessage) =>
                        {

                            activity.SetTag("JSN_Host" + DateTime.Now.Ticks, httpRequestMessage.Host);
                        };

                        // Note: Only called on .NET & .NET Core runtimes.
                        options.EnrichWithHttpResponse = (activity, httpResponseMessage) =>
                        {
                            activity.SetTag("responseServer1", httpResponseMessage.Body);
                        };

                        // Note: Called for all runtimes.v
                        options.EnrichWithException = (activity, exception) =>
                        {
                            //Helper.Helper.DebugLog("Stacktrace", exception.StackTrace);
                        };
                        options.RecordException = true;
                    })

                    .AddOtlpExporter(options =>
                    {
                        options.Endpoint = new Uri(connectToOtlp);
                    }));
```
Regards
Jesper

**Comment by jsndk** [comment]
Thanks for clarifying the innerworkings. :-) 
For others, this is my implementation that works.  .SetSampler statement...
`builder.Services.AddOpenTelemetry()
                .ConfigureResource(openTelemetryBuilder => openTelemetryBuilder
                    .AddService(serviceName: AppDomain.CurrentDomain.FriendlyName, serviceInstanceId: Environment.MachineName))
                    .WithTracing(tracingBuilder => tracingBuilder
                    **.SetSampler(new AlwaysOnSampler())**
                    .AddHttpClientInstrumentation(options =>
                    {
                    })
                    .AddAspNetCoreInstrumentation(options =>
                    {
                        // Note: Only called on .NET & .NET Core runtimes.
                        options.EnrichWithHttpRequest = (activity, httpRequestMessage) =>
                        {

                            activity.SetTag("JSN_Host" + DateTime.Now.Ticks, httpRequestMessage.Host);
                        };

                        // Note: Only called on .NET & .NET Core runtimes.
                        options.EnrichWithHttpResponse = (activity, httpResponseMessage) =>
                        {
                            activity.SetTag("responseServer1", httpResponseMessage.Body);
                        };

                        // Note: Called for all runtimes.v
                        options.EnrichWithException = (activity, exception) =>
                        {
                            //Helper.Helper.DebugLog("Stacktrace", exception.StackTrace);
                        };
                        options.RecordException = true;
                    })

                    .AddOtlpExporter(options =>
                    {
                        options.Endpoint = new Uri(connectToOtlp);
                    }));`

Regards
Jesper
