### ISSUE TITLE
No OTEL Traces/Metrics for Outgoing HTTP API Calls for .Net Windows Server Service

### ISSUE THREAD

**Issue by ritesh-harry** [open-telemetry/opentelemetry-dotnet#4633]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

opentelemetry-dotnet-instrumentation v0.7.0

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

OS Version:
Windows Server 2019/2022

Runtimes:
Microsoft ASP.NET Core 6.0.19 - Shared Framework (x84)
Microsoft ASP.NET Core 6.0.19 - Shared Framework (x64)
Microsoft .NET Runtime - 6.0.19 (x86)
Microsoft .NET Runtime - 6.0.19 (x64)
Microsoft .NET Runtime 6.0.19 - Windows Server Hosting

## Symptom

Hello,

I have instrumented our .NET applications automatically (applications are on Windows Server running as a Windows service) by implementing the solution coming from OpenTelemetry-dotNet. I believe all the libraries shipped with the OpenTelemetry-dotNet (https://github.com/open-telemetry/opentelemetry-dotnet) repository support all the officially supported versions of .NET Core and .NET framework with an except for .NET Framework 3.5 SP1.

The process I have used to implement this solution is as per below,

1. Download and import the PowerShell module on Windows Server which has the .Net application Windows service running (https://raw.githubusercontent.com/open-telemetry/opentelemetry-dotnet-instrumentation/v0.7.0/OpenTelemetry.DotNet.Auto.psm1")

2. Run the PowerShell command to install core files: 
Install-OpenTelemetryCore

3. Add the OTEL environment variables to the .Net Windows service application configuration file. The only OTEL environment variables defined in the configuration file is as per below:

add key="OTEL_SERVICE_NAME" value="API.Service"
add key="OTEL_EXPORTER_OTLP_ENDPOINT" value="https://collectors.au.sumologic.com/receiver/v1/trace/<id_here>"
add key="OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED" value="true"
add key="OTEL_EXPORTER_OTLP_PROTOCOL" value="http/protobuf"
add key="OTEL_RESOURCE_ATTRIBUTES" value="application=services,deployment.environment=test"

5. Run the PowerShell command to register the .Net application Windows service for OTEL: 
Register-OpenTelemetryForWindowsService -WindowsServiceName ""API.Service" -OTelServiceName "API.Service"

The above process seems to be working well for most of our .Net application Windows services. However, we do not seem to be getting any telemetry data for our services that make outbound HTTP API calls, I would have thought we would have been able to see this data.

I wanted to confirm the below,
1. Are there any additional application settings that need to be added in order to see this kind of data (outgoing HTTP API call traces/metrics)? 
2. Can OTEL get metrics from OWIN webserver on .Net? 
3. Are there any dependencies that need to be installed on Windows Server to get this to work?

Any help in trying to sort out this issue would be greatly appreciated.

Thank you.

**What is the expected behavior?**

What did you expect to see?

I expect to see traces for API calls.

**What is the actual behavior?**

What did you see instead?

Don't see anything. Over 1 week of testing no data whatsoever is seen.

## Reproduce

Create a self-contained project using the template of your choice, apply the
minimum required code to result in the issue you're observing.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by vishweshbankwar** [comment]
@ritesh-harry Looks like you are using https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation? Please open an issue in that repo. Thanks!

**Comment by ritesh-harry** [comment]
Hi @vishweshbankwar, 

Apologies and thank you for that. I'll open the issue in the correct repo.

Thank you.
