### ISSUE TITLE
OpenTelemetry.Instrumentation.MySqlData stopped working at MySql.Data@8.0.31

### ISSUE THREAD

**Issue by t03apt** [open-telemetry/opentelemetry-dotnet#4643]
# Bug Report
	<PackageReference Include="OpenTelemetry" Version="1.5.1" />
	<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.5.1" />
	<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.5.1" />
	<PackageReference Include="OpenTelemetry.Instrumentation.MySqlData" Version="1.0.0-beta.7" />

Runtime version: net7.0

## Symptom

Tracing works with OpenTelemetry.Instrumentation.MySqlData@1.0.0-beta.7 and MySql.Data@8.0.30.
When I upgrade MySql.Data to any newer version then MySql tracing stops working because MySqlDataInstrumentation.TraceEvent is not getting fired.

## Reproduce
See: https://github.com/t03apt/MySqlDataInstrumentationIssues

**Comment by vishweshbankwar** [comment]
@t03apt Please open your issue here https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues

**Comment by t03apt** [comment]
Related: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1157
