### ISSUE TITLE
AOT: Make serialization of JSON arrays AOT compatible

### ISSUE THREAD

**Issue by vitek-karas** [open-telemetry/opentelemetry-dotnet#4648]
# Feature Request

Several exporters use `System.Text.Json.JsonSerializer.Serialize(array)` in their implementation of `TagTransformer`. This API is not AOT compatible because it uses reflection at runtime to write the array values into JSON.

There are 3 options how to solve this. Note that all of them rely on the fact that `TagTransformer` will only try to serialize arrays of primitive types as listed here: https://github.com/open-telemetry/opentelemetry-dotnet/blob/b23b1460e96efb5ecd78d1b36c2e00e84de7086b/src/OpenTelemetry/Internal/TagTransformer.cs#L112-L131

## Option 1 - Source generator

The best solution (by the book solution) is to use the `System.Text.Json` source generator. This feature was introduced in version 6.0 of the package. This solution would require upgrading the `System.Text.Json` dependency to 6.0 (and also `System.Text.Encodings.Web` to 6.0).

After the upgrade the code change is relatively simple: https://github.com/open-telemetry/opentelemetry-dotnet/compare/main...vitek-karas:opentelemetry-dotnet:JsonFix_SourceGenerator?expand=1

The change introduces a helper which can serialize all of the array types from `TagTransformer` to JSON and it uses the source generator to do so.

The pros of this approach are that it's the recommended solution and thus fully supported and tested by the owners of `System.Text.Json`.
The cons is the need to upgrade the package reference to 6.0.

## Option 2 - Using low lever JSON writer

If upgrading the package reference is not an option, then an alternative solution is to manually implement serialization of the several primitive array types. The solution still uses `System.Text.Json` but only the low-level `Utf8JsonWriter` API which is fully AOT compatible.

I prepared another branch which shows how such a modification could look: https://github.com/open-telemetry/opentelemetry-dotnet/compare/main...vitek-karas:opentelemetry-dotnet:JsonFix_RawWriter?expand=1

The change is similar to the source generator in that it introduces a helper but the helper is manually implemented to support serialization of the limitted set of primitive array types necessary.

The pros of this is the fact that there's no need to upgrade package references.
The cons is that it's more code and it's not as easily extensible if there are more JSON serialization needs in the future.

## Option 3 - Use suppressions and hint to make it AOT compatible

This would mean keep using the `JsonSerializer.Serialize` API as-is and suppress the warnings. Then make sure that everything works in AOT and if it doesn't use other hints (like `DynamicDependencyAttribute`) to make it work.

The pros is that this is the least amount of code.
The cons is that this is fragile - changes to `System.Text.Json` could easily break the hints and make it fail. Also of note is that in .NET 8 there's a new feature switch which would disable this functionality by default. It would mean that apps using this would need to set `JsonSerializerIsReflectionEnabledByDefault=true` in their project files (or OTel would have to introduce MSBuild integration and modify this itself).
This would also degrade the size of the application after trimming since this requires the system to keep the reflection based serialization code in `System.Text.Json`, which the other two solutions don't use.

## Conclusion

I think option 1 (source generator) is the best. It solves the problem the recommended way and can be easily extended in the future if there are more places which need JSON serialization.

While upgrading a package reference to a new major version can introduce breaking changes I think in this case the risk is very low.
For one the package is part of the .NET runtime framework and thus follows the rather strict compatibility guidelines of .NET. This doesn't preclude breaking changes from occuring, but it makes it much less likely.
Also, the usage of `System.Text.Json` in OTel source code is currently very limitted. There are only two places, the JSON array serialization in `TagTransformer` and its derived classes and then in Zipkin exporter, which uses just `Utf8JsonWriter` which is the lowest level JSON API and thus very unlike to introduce breaking changes.

If this is too risky for OTel, then I would recommend option 2.

I would strongly advice against option 3 as the risks are just too big.

This is part of https://github.com/open-telemetry/opentelemetry-dotnet/issues/3429.

@Yun-Ting @eerhardt

**Comment by alanwest** [comment]
I vote option 2 because I think leaves the least in the way of uncertainty. I too suspect there may be low risk in upgrading System.Text.Json though I'm not completely certain of this without further due diligence.

**Comment by eerhardt** [comment]
Another advantage of option 2 is that it should perform better with lower overhead than using the JsonSerializer (assuming you pool the `byte[]` buffer to reduce allocations).

**Comment by Yun-Ting** [comment]
We discussed this in 7/18 SIG meeting. 
Here are the things we would like to discuss more about:

1. For option 3, if it is very unlikely that we expand the supported type list: https://github.com/open-telemetry/opentelemetry-dotnet/blob/b23b1460e96efb5ecd78d1b36c2e00e84de7086b/src/OpenTelemetry/Internal/TagTransformer.cs#L112-L131 in the future (we are already covering more types than the [spec](https://github.com/open-telemetry/opentelemetry-dotnet/blob/b23b1460e96efb5ecd78d1b36c2e00e84de7086b/src/OpenTelemetry/Internal/TagTransformer.cs#L112-L131) required). And, worst case, we will have this fallback `ConvertToStringArrayThenTransformArrayTag`, what other concerns would we have with option 3? I know there's similar discussion here: https://github.com/open-telemetry/opentelemetry-dotnet/pull/4656#discussion_r1266649995. But I don't fully get which parts are would be fragile.

2. Regarding option 1, is it possible that we do a conditional compilation that brings in System.Text.Json 6.0 version for TFMs that support AOT, i.e. net6.0 and above as an interim solution?

**Comment by vitek-karas** [comment]
Option 3 inherently relies on internal implementation details of `System.Text.Json`. Whatever we do there (even the solution with custom converters as suggested in https://github.com/open-telemetry/opentelemetry-dotnet/pull/4656#discussion_r1266642573) would all rely on a "promise": "`System.Text.Json` will not perform any additional reflection anywhere in its implementation of this functionality.". The problem with that is two fold:
* A year from now, people working on `System.Text.Json` will not know about this and could easily break that promise
* There's no good way to validate that the promise is true in code - that's what the trimming warnings are for, and they are already active in this case, option 3 would basically disable the trim warnings in this area.

The risk of breaking things if we need to serialize more types is secondary to this honestly. I also don't like adding code which makes very specific assumptions - it's just too easy to copy/reuse the code somewhere else and break those assumptions unknowingly.

(This is why we strongly discourage suppressing trim analysis warnings if at all possible)

As for option 1 - yes we could use source gen in conditional compilation for net6+ (and conditionally upgrade the `System.Text.Json` package reference there as well, or maybe nuget will be clever enough so that we don't need to do that... not sure). It just introduces more differences between the TFMs - so more complexity to think about. Personally, I don't have a strong opinion either way.

**Comment by utpilla** [comment]
I would be in favor of following option 1 with conditionally using source gen for net6+. This option brings in the simplest and least intrusive changes.

**Comment by utpilla** [comment]
@vishweshbankwar pointed out that we already do conditionally package reference in the Jaeger project already. We could do the same for Zipkin and Console exporter to be clearer in our intent: https://github.com/open-telemetry/opentelemetry-dotnet/blob/e7f7cd68759d81aa3a34cb88d1b2590e09c21e89/src/OpenTelemetry.Exporter.Jaeger/OpenTelemetry.Exporter.Jaeger.csproj#L35-L36

**Comment by vitek-karas** [comment]
This was fixed with https://github.com/open-telemetry/opentelemetry-dotnet/pull/4679.
