### ISSUE TITLE
Get the current `MetricPoint` count

### ISSUE THREAD

**Issue by aelij** [open-telemetry/opentelemetry-dotnet#4670]
# Feature Request

**Is your feature request related to a problem?**

We would like to be able to export data according to a threshold value of the current `MetricPoint` count.

**Describe the solution you'd like:**

Add a `int GetBatchMetricPointCount()` method to `MetricReader`, which will calculate the data point count of a snapshot but without actually creating one.

**Describe alternatives you've considered.**

Using the periodic reader, but that could yield inaccurate results.

## Additional Context

This could be implemented in `AggregatorStore` like so:

```cs
    internal int GetSnapshotMetricPointCount()
    {
        var metricPointCount = 0;
        var indexSnapshot = Math.Min(this.metricPointIndex, this.maxMetricPoints - 1);
        for (int i = 0; i <= indexSnapshot; i++)
        {
            ref var metricPoint = ref this.metricPoints[i];
            if (this.outputDelta)
            {
                if (metricPoint.MetricPointStatus == MetricPointStatus.NoCollectPending)
                {
                    continue;
                }
            }
            else if (!metricPoint.IsInitialized)
            {
                continue;
            }

            metricPointCount++;
        }

        return metricPointCount;
    }
```

Test:

```cs
    [Theory]
    [InlineData(3, MetricReaderTemporalityPreference.Cumulative)]
    [InlineData(2, MetricReaderTemporalityPreference.Delta)]
    public void VerifySnapshotMetricCount(int expectedMetricCount, MetricReaderTemporalityPreference temporality)
    {
        var exportedMetrics = new List<Metric>();

        using var meter = new Meter(Utils.GetCurrentMethodName());
        var counter = meter.CreateCounter<long>("meter");
        var reader = new BaseExportingMetricReader(new InMemoryExporter<Metric>(exportedMetrics))
        {
            TemporalityPreference = temporality,
        };
        using var meterProvider = Sdk.CreateMeterProviderBuilder()
            .AddMeter(meter.Name)
            .AddReader(reader)
            .Build();

        // FIRST EXPORT
        counter.Add(10);
        var count = reader.GetBatchMetricPointCount();
        meterProvider.ForceFlush();

        // Verify Metric
        Assert.Equal(1, count);
        Assert.Equal(1, CountMetricPoints(exportedMetrics));

        exportedMetrics.Clear();

        // SECOND EXPORT
        counter.Add(5, new TagList { { "A", 1 } });
        counter.Add(5, new TagList { { "A", 2 } });
        count = reader.GetBatchMetricPointCount();
        meterProvider.ForceFlush();

        // Verify Metric, after second export
        Assert.Equal(expectedMetricCount, count);
        Assert.Equal(expectedMetricCount, CountMetricPoints(exportedMetrics));
    }
```

**Comment by cijothomas** [comment]
Can you elaborate what you are trying to achieve?

**Comment by aelij** [comment]
@cijothomas We would like to be able to export data when the metric point count hits a certain threshold. Because we have a tag of an unknown cardinality, we'd like to limit the amount of memory used during processing. Using a time-based approach (periodic reader) is not good enough since the data we're processing can vary widely and exporting too often is inefficient for our scenario.

**Comment by aelij** [comment]
I see your point. So the current implementation won't support a high cardinality of tags, even after a delta snapshot? I see there's a TODO for this:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/0f9f507ed6aa960acbcd58e79b9e45330f6432a1/src/OpenTelemetry/Metrics/AggregatorStore.cs#L223-L226

From what I gather the point count is not an implementation detail - it's a preview of what will be included in the next snapshot.
If we'd like to reduce the chances of a measurement getting dropped, I think this is a reasonable metric to have.

**Comment by cijothomas** [comment]
The TODO is tracked separately in this issue : https://github.com/open-telemetry/opentelemetry-dotnet/issues/2360

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/3880 tracks exposing internal state via some metrics as well.

**Comment by aelij** [comment]
An instrument for the metric point count could work. I'll add a comment there and close this issue.
