### ISSUE TITLE
Create new CI leg for AOT/trim compatibility tests

### ISSUE THREAD

**Issue by vitek-karas** [open-telemetry/opentelemetry-dotnet#4690]
The recently added test https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/test/OpenTelemetry.AotCompatibility.Tests is relatively slow, it can take several minutes to run (depending on the hardware). Since currently it's part of the main test CI leg it makes the entire CI run much longer than before. It would be better to create a new CI leg to run just this test.

Once this is separated it would be good to also add a trimming test. Basically the same test but run the publish with `PublishAot=false` and `PublishTrimmed=true` instead and maybe target net6.0 in that case. This would validate that OTel can be used in trimmed apps (non-AOT) as well.

Eventually it would also be great if this leg could include net8.0 sdk (maybe RC1 once it's available) and run the AOT test targeting net8.0 instead. This is because:
* There are known bugs in the net7.0 AOT compiler which are fixed in net8.0 and which have effect on OTel (for example: https://github.com/open-telemetry/opentelemetry-dotnet/pull/4688)
* OTel includes ASP.NET dependencies which were only made AOT compatible in net8.0

@Yun-Ting

**Comment by Yun-Ting** [comment]
@open-telemetry/dotnet-approvers this issue can be closed.
