### ISSUE TITLE
Replace CodeCoverage.exe by dotnet-coverage global tool or Microsoft.CodeCoverage.Console

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet#4745]
# Feature Request

replace the way how code coverage is executed.

**Is your feature request related to a problem?**

From CodeCoverage execution with Microsoft.CodeCoverage 17.7.0

```log
CodeCoverage.exe is deprecated. Use dotnet-coverage global tool or Microsoft.CodeCoverage.Console instead. Some features of CodeCoverage.exe will be removed in next release of Visual Studio.
```

## Additional Context

While working on this, propagate solution to https://github.com/open-telemetry/opentelemetry-dotnet-contrib repository

**Comment by utpilla** [comment]
This is caused when upgrading to `17.6.3` as well. Check the `Process code coverage` step of this build: https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/5793302017/job/15700864017?pr=4744

**Comment by Kielek** [comment]
Description uodated
