### ISSUE TITLE
Unable to find a version of 'System.Buffers' that is compatible with 'System.IO.Pipelines 4.6.0 constraint: System.Buffers (>= 4.5.0)'.

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#475]
Getting error messages:

```
opentelemetry> .\nuget.exe install OpenTelemetry.Collector.StackExchangeRedis -Version 0.2.0-alpha.179 -Source https://www.myget.org/F/opentelemetry/api/v3/index.json
Feeds used:
  C:\Users\sergkanz\.nuget\packages\
  https://www.myget.org/F/opentelemetry/api/v3/index.json



Attempting to gather dependency information for package 'OpenTelemetry.Collector.StackExchangeRedis.0.2.0-alpha.179' with respect to project 'C:\temp\opentelemetry', targeting 'Any,Version=v0.0'
Gathering dependency information took 2.03 sec
Attempting to resolve dependencies for package 'OpenTelemetry.Collector.StackExchangeRedis.0.2.0-alpha.179' with DependencyBehavior 'Lowest'
Unable to find a version of 'System.Buffers' that is compatible with 'System.IO.Pipelines 4.6.0 constraint: System.Buffers (>= 4.5.0)'.



opentelemetry> .\nuget.exe install OpenTelemetry.Exporter.Console -Version 0.2.0-alpha.179 -Source https://www.myget.org/F/opentelemetry/api/v3/index.json
Feeds used:
  C:\Users\sergkanz\.nuget\packages\
  https://www.myget.org/F/opentelemetry/api/v3/index.json



Attempting to gather dependency information for package 'OpenTelemetry.Exporter.Console.0.2.0-alpha.179' with respect to project 'C:\temp\opentelemetry', targeting 'Any,Version=v0.0'
Gathering dependency information took 1.83 sec
Attempting to resolve dependencies for package 'OpenTelemetry.Exporter.Console.0.2.0-alpha.179' with DependencyBehavior 'Lowest'
Unable to find a version of 'System.Buffers' that is compatible with 'System.Text.Json 4.7.0 constraint: System.Buffers (>= 4.5.0)'.
C:\temp\opentelemetry>
```

**Comment by eddynaka** [comment]
Hi all,

Write now, we have 3 versions of System.Buffers: 4.3, 4.4, 4.5

Projects that contains more than one version:
- OpenTelemetry.Exporter.Zipkin.csproj
- OpenTelemetry.Exporter.Console.csproj
  - System.Text.Json (nuget) -> System.Buffers (4.5)
  - OpenTelemetry.Api (project) -> System.Buffers (4.4)

The same happen for OpenTelemetry.Collector.StackExchangeRedis.csproj, the only difference is that  somehow in that case you had a scenario, you were using system.io.pipelines 4.6, but looking at the project, we dont have that.

My first suggestion would be install manually add system.buffers in all projects that have that reference and consolidate it, so we won't have different versions.

what do you think?


Thanks!

**Comment by SergeyKanzhelev** [comment]
I don't see reference to System.Buffers from here: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/OpenTelemetry.Api.csproj. Is it a reference from the System.Diagnostics?

**Comment by eddynaka** [comment]
Hi @SergeyKanzhelev ,

yes. System.Diagnostics -> System.Memory -> System.Buffer 4.4

**Comment by SergeyKanzhelev** [comment]
oh, What would be the proposed solution than? Can we downgrade the version of `System.Text.Json`? If not - will adding an explicit reference to System.Buffers from Zipkin solve the issue?

**Comment by eddynaka** [comment]
Hi @SergeyKanzhelev ,

Downgrading wouldn't solve because text.json always depended from buffers.4.5

We could install manually in those projects that have multiple versions and test.

How did you generate those versions to test?

**Comment by SergeyKanzhelev** [comment]
just `pack` them. Wither from command line: "dotnet pack foo.csproj" or right click on project in VS and select "pack" (or publish), not sure which

**Comment by eddynaka** [comment]
Hi @SergeyKanzhelev , just tried the same command and the it worked fine. Below the files that were downloaded:
![image](https://user-images.githubusercontent.com/16199012/76364864-b1123180-6304-11ea-9ff8-32c8b0517f36.png)

I saw that the version of `System.IO.Pipelines` is different from the version that you have an issue (4.5.1 vs 4.6).

The same happened with the other command as well:
![image](https://user-images.githubusercontent.com/16199012/76364981-fdf60800-6304-11ea-87cf-6bc8b8614dee.png)

**Comment by cijothomas** [comment]
Dont think this is an issue with DS 5.0. Closing old issues.
