### ISSUE TITLE
Mark `ActivityExtensions.SetStatus` obsolete

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#4755]
[ActivityExtensions.SetStatus](https://github.com/open-telemetry/opentelemetry-dotnet/blob/b0ab8d5fe7c012f93ee6d0bb92af4cf5742255fc/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L42) was added as a workaround before System.Diagnostics.DiagnosticSource supported [setting](https://learn.microsoft.com/dotnet/api/system.diagnostics.activity.setstatus?view=net-7.0) activity status starting version 6.0. Having two APIs to set the activity status is confusing for users. Proposing to mark extensions method `obsolete`

Documentation needs to be updated with recommended way of setting status. https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api#setting-status

Reference issue: https://github.com/open-telemetry/opentelemetry-dotnet/discussions/4703

**Comment by pegasas** [comment]
Hi, Team, 

I created a PR to mark `SetTag` as `obsolete`.
Feel free to comments if any concerns.
