### ISSUE TITLE
Shared library for creating http server

### ISSUE THREAD

**Issue by n1dtec** [open-telemetry/opentelemetry-dotnet#476]

**Comment by SergeyKanzhelev** [comment]
right now Prometheus and zPages implements the server that allows to serve additional endpoint from the app process to expose telemetry. The suggestion here is whether we want to share the code.

Generally speaking this work is not OpenTelemetry specific. So naming of this NuGet may be more generic. Also it may be a good idea to suggest this NuGet to be a part of .NET.
