### ISSUE TITLE
Implement support for metrics in HttpClient for .NET framework

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-dotnet#4764]
# Feature Request

**Is your feature request related to a problem?**

Currently, HttpClient instrumentation supports metrics for .NET (Core), but not for .NET framework. This is mentioned in a [warning in the documentation](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http#metrics).

This is unexpected and seen as a bug by users I've interacted with. Users of e. g. the auto-instrumentation packages or other instrumentation that packages that use HttpClient under the hood will likely not find the warning.

**Describe the solution you'd like:**

Adding support for metrics also for .NET framework would be a desired solution.

**Describe alternatives you've considered.**

Users who currently face this issue have to either provide their own instrumentation library, add manual instrumentation, or create metrics from fully sampled traces.

## Additional Context

[Related Slack discussion](https://cloud-native.slack.com/archives/C01N3BC2W7Q/p1678833977411999)
[Warning in the documentation](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http#metrics)

**Comment by matt-hensley** [comment]
I've started on a proposed PR for this and will have a draft ready next week.

**Comment by alejandrocarrasquilla** [comment]
@matt-hensley Any updates on this change? 
We are interested in this functionality. We are specially interested in the implementation that does not rely on having traces enabled. 
Thanks

**Comment by Jazaret** [comment]
Is there any update on this? Our team is depending on HttpClient metrics for .NET Framework.

**Comment by matt-hensley** [comment]
After feedback from maintainers on #4768 I am taking a different approach for the metrics implementation.

This should allow for generation of traces and metrics independently, as opposed to the previous PR that required tracing to be enabled, and for a particular trace to be sampled and recorded.

Currently iterating on this new approach and working through the tests as the current instrumentation is only trace focused.
