### ISSUE TITLE
Instrument name limited to length of 62 instead of 255

### ISSUE THREAD

**Issue by oeaoaueaa** [open-telemetry/opentelemetry-dotnet#4774]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/031ed48714e16ba4a5b099b6e14647994a0b9c1b/src/OpenTelemetry/Metrics/Builder/MeterProviderBuilderSdk.cs#L51

Instrument name is being limited to a length of 62 but the specification cited in the comments says that the maximum length should be 255 and then a limit of 63 for the unit.

**Comment by cijothomas** [comment]
The spec just relaxed the limit from 63 to 255 couple of days back! It'd be good to get this relaxed in code as well.
@oeaoaueaa do you have interest/time to send a PR for the same?
