### ISSUE TITLE
MyGet feed not updating

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#4778]
The last package update I see on the MyGet feed - https://www.myget.org/F/opentelemetry/api/v3/index.json - was 8 days ago.

For example, `OpenTelemetry.Instrumentation.SqlClient` was [changed a couple of days ago](https://github.com/open-telemetry/opentelemetry-dotnet/pull/4751) but the feed doesn't have a new build:

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/303201/336fae1f-15bf-48ec-92e4-17282b224ab1)

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/5885185006/job/15961228073 the daily run is failing, that explains why myget is not updated daily.

**Comment by JamesNK** [comment]
Fix is merged. Manually trigger the daily run to test?

**Comment by utpilla** [comment]
This should be fixed now.
