### ISSUE TITLE
How can I get the traceparent from query param not header

### ISSUE THREAD

**Issue by OmniaSalehSaad** [open-telemetry/opentelemetry-dotnet#4789]
# Question
I need to send the traceparent info throw the query param not header and span created from AspNET core auto instrument get the same traceId and parent spanId sent into query param request. is this applicable in open telemetry .NET

**Comment by vishweshbankwar** [comment]
@OmniaSalehSaad You would need to write your own custom propagator in order to achieve that
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api#context-propagation

**Comment by OmniaSalehSaad** [comment]
@vishweshbankwar so as I understand i should use Sdk.SetDefaultTextMapPropagator and pass for it overriding TextMapPropagator but I just can override extrace and inject but I think i should override getter and setter functions which is input for inject and extract so i can override them in auto instrument library or what do you think should i do?

**Comment by vishweshbankwar** [comment]
@OmniaSalehSaad All you need to do is override the default propagator. https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api#context-propagation:~:text=Note%20on%20instrumentation,of%20your%20choice

**Comment by Mart-Bogdan** [comment]
Why was it closed? The problem is, that dotnet's `DistributedContextPropagator` don't expose HTTP request vie it's API for user to implement, and only Headers are available.
