### ISSUE TITLE
Add ServiceName or ApplicationName to all log traces

### ISSUE THREAD

**Issue by AntonioJDios** [open-telemetry/opentelemetry-dotnet#4790]
# Question
Hello, I am triying to use OpenTelemetry with application insights using the pre release nuget package. I'd like to add the same tag or custom property or general property to all the traces or activity  in the application. But I am not able to do it.

I am using this for activities:

```
  .ConfigureResource(resource => resource.AddService(appOptions.ApplicationName + "Activity").AddAttributes(new[]
           {
               new KeyValuePair<string, object>("ApplicationName",appOptions.ApplicationName)
           })).AddAzureMonitorTraceExporter()
```
or this for traces

```
       services.ConfigureOpenTelemetryTracerProvider((sp, builder) =>
        {
            builder.AddProcessor(new ActivityFilteringProcessor());
            builder.ConfigureResource(resourceBuilder =>
                resourceBuilder.AddAttributes(new[]
                {
                    new KeyValuePair<string, object>("ApplicationName",appOptions.ApplicationName)
                }));
        });
```

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).

**Comment by cijothomas** [comment]
Please use application insights repo for this as this is specific to it.
The general OpenTelemetry way is via Resource as you are already doing it correctly.
