### ISSUE TITLE
Support .NET 9 Synchronous Gauge

### ISSUE THREAD

**Issue by tommaybe** [open-telemetry/opentelemetry-dotnet#4805]
# Feature Request
It would be great for synchronous gauge support to be added, now that it has been added to Experimental spec.

# Is your feature request related to a problem?
Use cases are described here: https://github.com/open-telemetry/opentelemetry-specification/issues/2318.

# Describe the solution you'd like
I would expect to have a method in the class Meter called CreateObservableGauge<T>() along with the class Gauge<T>. They should behave like the ObservableGauge instrument, but being synchronous instead of asynchronous.

This is described as an experimental feature in the OpenTelemetry specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#gauge

# Describe alternatives you've considered
Both UpDownCounter and ObservableGauge do not work for my usecases.

# Additional context
-

**Comment by cijothomas** [comment]
Added the runtime-change needed label, as the instruments must be added in .NET Runtime and then OTel .NET (this repo) need to add support. This will come in .NET 9 timeframe only as .NET 8 train already left. Will open tracking issue in runtime repo, and link to this.

**Comment by cijothomas** [comment]
.NET Runtime proposal is here : https://github.com/dotnet/runtime/issues/92625#issue-1912726479
