### ISSUE TITLE
After updating Opentelemerty version 1.5.1 having issue with redis traces 

### ISSUE THREAD

**Issue by ankitpanwar174** [open-telemetry/opentelemetry-dotnet#4811]
# I recently updated opentelemetry to version 1.5.1, and TracerProviderBuilder no longer has a Configure method. I was using the code below to record the redis traces, and it was successful.

_ = TracerProviderBuilder.Configure((provider, b) =>
				{
					IConnectionMultiplexer connection = provider.GetRequiredService<RedisConnectionProvider>().Redis;
					if (connection != null)
					{
						_ = services.AddSingleton<IConnectionMultiplexer>(connection);
						_ = b.AddRedisInstrumentation(connection, options =>
							 options.Enrich = (activity, httpWebResponse) => activity.DisplayName = "Redis Trace");
					}
				}); 

can someone suggest what to use now instead of the above code?

**Comment by utpilla** [comment]
Please go through this PR description which talks about the new way of configuring `TracerProvider`: https://github.com/open-telemetry/opentelemetry-dotnet/pull/4071

**Comment by ankitpanwar174** [comment]
> Please go through this PR description which talks about the new way of configuring `TracerProvider`: #4071

Thanks for your help.
