### ISSUE TITLE
Grpc exporter doesn't follow dns change.

### ISSUE THREAD

**Issue by pengweiqhca** [open-telemetry/opentelemetry-dotnet#4813]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry.Exporter.OpenTelemetryProtocol 1.5.1

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net6.0

## Symptom

When i changed dns ip, grpc exporter still connected the old ip.

**What is the expected behavior?**

Grpc connect to new ip.

**What is the actual behavior?**

Grpc still connected the old ip long after i change dns.

## Reproduce

``` C#
var builder = WebApplication.CreateBuilder(args);

var meter = new Meter("Test");

var counter = meter.CreateObservableUpDownCounter("test.counter", () =>
{
    Console.WriteLine(DateTimeOffset.Now);

    return DateTimeOffset.Now.ToUnixTimeMilliseconds();
});

builder.Services
    .Configure<MetricReaderOptions>(options => options.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = 10000)
    .AddOpenTelemetry()
    .WithMetrics(mpb => mpb.AddMeter(meter.Name)
        .AddOtlpExporter(options => options.Endpoint = new Uri("http://collector.foo.com:4317")));

var app = builder.Build();

app.Run();
```

1. Set collector.foo.com = ip1 in local host file.
2. Open wireshark 1, start capturing TCP packet, set filter `ip.addr == ip1 && tcp.port = 4317`.
3. Open wireshark 2, start capturing TCP packet, set filter `ip.addr == ip2 && tcp.port = 4317`.
4. Run test code.
5. TCP data will appear in wireshark 1.
6. Modify collector.foo.com = ip2 in local host file.
7. TCP data still in wireshark 1 rather than wireshark 2.

## Additional Context

Grpc.Net use `SocketsHttpHandler` in .net6.0 and SocketsHttpHandler.PooledConnectionLifetime is [InfiniteTimeSpan](https://github.com/dotnet/runtime/blob/08b66559ed06d4d97fb09dfa0d20163f0865deef/src/libraries/Common/src/System/Net/Http/HttpHandlerDefaults.cs#L26C1-L26C1).

[GrpcChannel.ForAddress(options.Endpoint)](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs#L46) have no any options, so `SocketsHttpHandler` will use default settings. If grpc exporter is used every [1 minute](https://github.com/dotnet/runtime/blob/08b66559ed06d4d97fb09dfa0d20163f0865deef/src/libraries/Common/src/System/Net/Http/HttpHandlerDefaults.cs#L27), the http connection will never be disposed and always use the old connection, so there need to use the `GrpcClientFactory` instead.

> Http exporter already uses [HttpClientFactory](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs#L114).

**Comment by vishweshbankwar** [comment]
@pengweiqhca I am not able to repro this behavior you are noticing (I do not see any interruption). looking at the [doc](https://learn.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-7.0#:~:text=Addresses%20are%20automatically%20refreshed%20if%20a%20connection%20is%20interrupted.%20Refreshing%20is%20important%20in%20scenarios%20where%20addresses%20change%20at%20runtime.%20For%20example%2C%20in%20Kubernetes%20a%20restarted%20pod%20triggers%20the%20DNS%20resolver%20to%20refresh%20and%20get%20the%20pod%27s%20new%20address.) as well, it should continue to work.

@JamesNK Could you please confirm? Reference: [Grpc Channel Config](https://github.com/open-telemetry/opentelemetry-dotnet/blob/c97a233a9a9d9656b8c431f69f5697f90554b3bb/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs#L46) for otlp exporter.

**Comment by JamesNK** [comment]
I'm not an expert at reacting to DNS changes.

Changing the code to use Grpc.Net.Client.ClientFactory is one option.

A simpler change would be to specify a `SocketsHttpHandler` with `GrpcChannelOptions.HttpHandler`. Then you can specify `SocketsHttpHandler.PooledConnectionLifetime`

**Comment by vishweshbankwar** [comment]
@JamesNK Thanks! The behavior I am noticing is there is no interruption in connection during ip changes with this [Grpc Channel Config](https://github.com/open-telemetry/opentelemetry-dotnet/blob/c97a233a9a9d9656b8c431f69f5697f90554b3bb/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptionsExtensions.cs#L46) (different than what reported on this issue). If I interpret this [doc](https://learn.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-7.0#:~:text=Addresses%20are%20automatically%20refreshed%20if%20a%20connection%20is%20interrupted.%20Refreshing%20is%20important%20in%20scenarios%20where%20addresses%20change%20at%20runtime.%20For%20example%2C%20in%20Kubernetes%20a%20restarted%20pod%20triggers%20the%20DNS%20resolver%20to%20refresh%20and%20get%20the%20pod%27s%20new%20address.) correctly, we dont have to do anything and it should automatically refresh. is that correct?

**Comment by JamesNK** [comment]
Once a connection is up and running, SocketsHttpHandler controls the connection lifetime. You can use its properties (pooled connection lifetime, connection lifetime)
