### ISSUE TITLE
Create RPC spans for gRPC

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#482]
Spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/rpc.md

grpc-dotnet adds metadata to an activity in ASP.NET Core and provides its own activity for the client. There should be enough information on it, and in the types passed to the diagnostic source events to create the spans in the OT spec.

**Comment by alanwest** [comment]
Has this been picked up yet? If not, I'm interested.

**Comment by cijothomas** [comment]
@alanwest No one is working on this feature, so its available for pickup.

**Comment by alanwest** [comment]
Instrumentation for Grpc.Net.Client has been merged. I aim to get the ASP.NET Core functionality in place this week.

**Comment by JamesNK** [comment]
I tried out the Grpc.Net.Client telemetry, and recording the correct status is a good improvement 👍 

One change I wonder about: Should the original custom activity tags be removed? Highlighted in red below. That information is now in the green metadata.

![image](https://user-images.githubusercontent.com/303201/86969610-295d0680-c1c2-11ea-8852-d66d1b537154.png)

**Comment by alanwest** [comment]
> One change I wonder about: Should the original custom activity tags be removed? Highlighted in red below. That information is now in the green metadata.

Interesting thought. I can make this change. Though, is there any concern that anything other than OTel may depend on the tags generated from the library?

**Comment by cijothomas** [comment]
@alanwest can we close this item? I guess we have both client and server side functionality merged in now.

**Comment by alanwest** [comment]
@cijothomas Yes, I think we should close this. #687 and #803 cover things here. I will create a new issue to track the idea of removing the library generated tags: https://github.com/open-telemetry/opentelemetry-dotnet/issues/482#issuecomment-655753756. Though to my knowledge, removing tags is not possible on an Activity.

**Comment by cijothomas** [comment]
Use settag with value as null. It'll remove the tag.
