### ISSUE TITLE
Prometheus exporter writes boolean values as "True" and "False"

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#4822]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

```xml
<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.6.0-rc.1" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0-rc.1" />
```

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

`net7.0`

## Symptom

Prometheus exporter writes boolean values as `"True"` and `"False"`:

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/303201/948fda6e-be7b-4001-abcf-bc45696d7f7d)

**What is the expected behavior?**

I see the go exporter writes lower case values, e.g. `"true"` at https://github.com/open-telemetry/opentelemetry-go/blob/02616a25c68e674a04df01a1b7ba185a2db8cd5a/exporters/prometheus/testdata/counter.txt#L3 that is generated from https://github.com/open-telemetry/opentelemetry-go/blob/02616a25c68e674a04df01a1b7ba185a2db8cd5a/exporters/prometheus/exporter_test.go#L51. That seems like a more idiomatic behavior.

**What is the actual behavior?**

The written value appears to be `bool.TrueString` and `bool.FalseString`. Are these the right values?

## Reproduce

Create a self-contained project using the template of your choice, apply the
minimum required code to result in the issue you're observing.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by reyang** [comment]
> The written value appears to be `bool.TrueString` and `bool.FalseString`. Are these the right values?

1. They should be `"true"` and `"false"`.
2. Note that the spec is Experimental and could have break changes.

More info:
* The [Experimental Prometheus and OpenMetrics Compatibility specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#metric-attributes) says: _"non-string Attribute values MUST be converted to string attributes following the [attribute specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute)"_
* The [Stable specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute) says _"For protocols that do not natively support non-string values, non-string values SHOULD be represented as JSON-encoded strings"_
