### ISSUE TITLE
Export LogRecord.Exception data when using otlp exporter

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#4831]
Opening this issue to track progress on exporting attributes corresponding to `LogRecord.Exception` in OTLP exporter. The semantic conventions for these attributes are not yet stable and hence the attributes are not part of stable OTLP log exporter. The attributes will be available in only the pre-release versions of the exporter.

https://github.com/open-telemetry/semantic-conventions/blob/main/docs/exceptions/exceptions-logs.md#attributes

**Comment by cijothomas** [comment]
> Does this mean when using `LogError` the exception that is passed as parameter its stacktrace is currently not send?

Correct : https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/CHANGELOG.md#160-rc1

**Comment by vishweshbankwar** [comment]
Following up on this: The ability to export these attributes are available on https://www.nuget.org/packages/OpenTelemetry/1.7.0-alpha.1

https://github.com/open-telemetry/opentelemetry-dotnet/discussions/4955

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/semantic-conventions/pull/619 Once this is done, we can make the exception part as default without experimental feature.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/exceptions/exceptions-logs.md#semantic-conventions-for-exceptions-in-logs is stable now., and OTLP Logexporter can bring back this functionality now.
