### ISSUE TITLE
Grpc exporter is not compatible with insecure requests on port 80.

### ISSUE THREAD

**Issue by pengweiqhca** [open-telemetry/opentelemetry-dotnet#4837]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry.Exporter.OpenTelemetryProtocol 1.5.1

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net48

## Symptom

``` C#
var endpoint = new Uri("http://172.17.12.73");
#if NETFRAMEWORK
// If replace `endpoint.Authority` with `endpoint.Host, endpoint.Port`, will not get a failure.
var channel = new Channel(endpoint.Authority, endpoint.Scheme == Uri.UriSchemeHttps ? ChannelCredentials.SecureSsl : ChannelCredentials.Insecure);
#else
var channel = GrpcChannel.ForAddress(endpoint);
#endif

var client = new Greeter.GreeterClient(channel);

try
{
    await client.SayHelloAsync(new());
}
catch (RpcException ex)
{
    Console.WriteLine(ex.Status);
}

Console.WriteLine(channel.State);
```

**What is the expected behavior?**

`ChannelState: Ready`

**What is the actual behavior?**

```
Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1694568219.677000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1694568219.677000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}]}")
ChannelState: TransientFailure
```

> Use wireshark,  I didn't see any TCP connections while the code was running.

## Additional Context
.net 6.0+ have no error.

**Comment by vishweshbankwar** [comment]
@pengweiqhca 
`But Grpc.Core package default port is 443`

Could you elaborate on this bit more? 

Default port depends on the configured channel. 

https://grpc.github.io/grpc/csharp/api/Grpc.Core.Channel.html#Grpc_Core_Channel__ctor_System_String_Grpc_Core_ChannelCredentials:~:text=Creates%20a%20channel%20that%20connects%20to%20a%20specific%20host.%20Port%20will%20default%20to%2080%20for%20an%20unsecure%20channel%20and%20to%20443%20for%20a%20secure%20channel.

**Comment by pengweiqhca** [comment]
Using the Wireshark to capture tcp packets, the port number is 443.

**Comment by pengweiqhca** [comment]
Sorray, I got a wrong reason, but the symptom is not wrong, I have modified the symptom description.

The solution is replace `endpoint.Authority` with `endpoint.Host, endpoint.Port`.

**Comment by vishweshbankwar** [comment]
Thanks! - I am now able to repro this issue, looking into it further.
