### ISSUE TITLE
[repo] Replace outdated tool dotnet-format by the built-in dotnet format

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#4839]
Today we have a CI [workflow](https://github.com/open-telemetry/opentelemetry-dotnet/blob/459783f700b87325e057493d0715338d93e2de63/.github/workflows/dotnet-format.yml#L26-L30) which uses a .NET tool called `dotnet-format` to do (essentially) style checks on any code being added to the repo.

`dotnet-format` is now part of the .NET SDK and can be invoked as `dotnet format` from the CLI.

We want to switch our CI workflow to the new style because the old one doesn't work for some of the newer things like raw string literals.

I already did this in the contrib repo: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1339

Throwing this issue up in case anyone wants to take it on.

It should hopefully be simpler in the main repo because there aren't any legacy AspNet projects. I would suggest to start with updating the workflow with what contrib has (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1339/files#diff-ca8c2611c79b991c0fbe04fec3c97c14dc83419f5efb1e8a7a96dd51e7df3e2a) and go from there.

**Comment by SaumyaBhushan** [comment]
Hi I woud like to work on this one .

**Comment by CodeBlanch** [comment]
Assigned to you @SaumyaBhushan thanks! Feel free to reach out to me on Slack if you need any help.

**Comment by tombiddulph** [comment]
It looks like the PR for this has gone stale, can I take it over?

**Comment by tombiddulph** [comment]
@CodeBlanch I created a PR to sort this out. What do I need to do to get it merged?

**Comment by tombiddulph** [comment]
Sorry for the repeated ping @CodeBlanch, can you help get this merged?
