### ISSUE TITLE
oltp vs zipkin: not the same result

### ISSUE THREAD

**Issue by BartNetJS** [open-telemetry/opentelemetry-dotnet#4849]
I have enabled oltp and zipkin exporter:

```
    builder.AddOtlpExporter(opt=>
    {
        opt.Protocol = OtlpExportProtocol.HttpProtobuf;
        opt.Endpoint = new Uri(....);
    });
    builder.AddZipkinExporter(o =>
    {
        o.Endpoint = new Uri(.....);
    });
```

In zipkin the traces are correctly connected:

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/4865355/84015358-9bfd-446f-b539-2a99f4790909)

But in jaeger (otlp) i got this:
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/4865355/2ae75ddf-5a43-42b3-a20e-c944446eb404)

What can be wrong?

**Comment by cijothomas** [comment]
Its not easy to tell what is the incorrect thing that Jaeger is showing... Could you use consoleexporter or otlp+logging, and share some sample spans which has incorrect values for any fields? If the values are correct, but UI shows diff. then its something we need to follow up with jaeger/zipkin repos.
