### ISSUE TITLE
Autogenerated resource service.instance.id is different between telemetry types

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#4871]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/303201/23811eae-a03b-4195-878f-257697bd1865)

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* .NET 8 RC2

## Symptom

If OTel is configured without specifying a resource service instance id then a different value is generated for each telemetry type.

For example, metrics has its own service.instance.id, logging has its own service.instance.id, etc. I see this result when collecting OTLP that is sent by opentelemetry-dotnet

**What is the expected behavior?**

Telemetry types share the same autogenerated service.instance.id.

**What is the actual behavior?**

Different service.instance.id

## Reproduce

```cs
// Note, no serviceInstanceId specified
builder.Services.AddOpenTelemetry()
            .ConfigureResource(resourceBuilder => resourceBuilder.AddService(builder.Environment.ApplicationName));

builder.Services.Configure<OpenTelemetryLoggerOptions>(logging => logging.AddOtlpExporter());
builder.Services.ConfigureOpenTelemetryMeterProvider(metrics => metrics.AddOtlpExporter());
builder.Services.ConfigureOpenTelemetryTracerProvider(tracing => tracing.AddOtlpExporter());
```

Work around:

```cs
var serviceInstanceId = Guid.NewGuid().ToString();

builder.Services.AddOpenTelemetry()
    .ConfigureResource(resourceBuilder => resourceBuilder.AddService(builder.Environment.ApplicationName, serviceInstanceId: serviceInstanceId));
```

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by pyohannes** [comment]
It seems to work when making sure each provider builder shares the same resource:
```csharp
var resourceBuilder = ResourceBuilder
    .CreateDefault()
    .AddService(builder.Environment.ApplicationName);

builder.Services.Configure<OpenTelemetryLoggerOptions>(logging => logging.AddOtlpExporter().SetResourceBuilder(resourceBuilder));
builder.Services.ConfigureOpenTelemetryMeterProvider(metrics => metrics.AddOtlpExporter().SetResourceBuilder(resourceBuilder));
builder.Services.ConfigureOpenTelemetryTracerProvider(tracing => tracing.AddOtlpExporter().SetResourceBuilder(resourceBuilder));
```

However, it's still a bug that it doesn't work with `ConfigureResource`.

As a side note, there's [a proposal](https://github.com/open-telemetry/semantic-conventions/issues/311) under discussion that tangentially relates to this problem. It aims to define a common and more deterministic algorithm for generating the instance id.

**Comment by kvenkatrajan** [comment]
@CodeBlanch we are still seeing reports of instability in instanceIDs : https://github.com/dotnet/aspire/issues/4103. Is there anything alternate we can advise the user in this case?

**Comment by CodeBlanch** [comment]
@kvenkatrajan The linked issue seems to be something different.

Let's say I have an application. MyService.exe. It uses OTel SDK. I deploy it somewhere and let's say two instances get run. It will look something like this:

MyService.exe Instance 1
Traces - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304
Metrics - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304
Logs - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304

MyService.exe Instance 2
Traces - service.instance.id = bc749055-c7d1-49a6-8d77-af6be9654f4b
Metrics - service.instance.id = bc749055-c7d1-49a6-8d77-af6be9654f4b
Logs - service.instance.id = bc749055-c7d1-49a6-8d77-af6be9654f4b

Each instance gets a different auto-generated GUID for `service.instance.id` but they are consistent for the different signals inside each instance.

The user seems to want...

MyService.exe Instance 1
Traces - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304
Metrics - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304
Logs - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304

MyService.exe Instance 2
Traces - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304
Metrics - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304
Logs - service.instance.id = ea4b60de-d664-43de-aad3-ca48806b9304

Which is just not what service.instance.id does or was intended to do. It is unique per instance, essentially.
