### ISSUE TITLE
Unable to send logs to OpenTelemetry backend (using Serilog in .Net framework 4.8)

### ISSUE THREAD

**Issue by pvsunilkumar** [open-telemetry/opentelemetry-dotnet#4880]
I am using Serilog in .Net Framework 4.8 to send logs to Opentelemetry. I am using Elastic as OpenTelemetry backend . I am able to send traces and but not logs. Please find my below code where it writes the log to the file but not sending logs to opentelemetry. Can somebody help?

        // TRACES ----- WORKING 
        _tracerProvider = Sdk.CreateTracerProviderBuilder()
       .AddAspNetInstrumentation()
       .AddHttpClientInstrumentation()
       .AddOtlpExporter(config =>
       {
           config.Endpoint = new Uri("https://abcd.es.io:443");
           config.Headers = "Authorization=ApiKey xyz";
       })
       .AddSource("SK")
       .SetResourceBuilder(
           ResourceBuilder.CreateDefault()
               .AddService(serviceName: "NLogger", serviceVersion: "1.0.0")
               .AddAttributes(resourceAttributes))
       .Build();

       var endpoint = "https://abcd.es.io:443/v1/logs";
       var protocol = OtlpProtocol.HttpProtobuf;

       // LOGGING --- NOT WORKING
       Log.Logger = new LoggerConfiguration()
       .MinimumLevel.Error()
       .WriteTo.Console()
       .WriteTo.File(@"c:\tt\1.txt")
       .WriteTo.OpenTelemetry(
       options => {
            options.Endpoint = endpoint;
            options.Protocol = protocol;
            options.IncludedData =
                    IncludedData.SpanIdField
                    | IncludedData.TraceIdField
                    | IncludedData.MessageTemplateTextAttribute
                    | IncludedData.MessageTemplateMD5HashAttribute;
            options.ResourceAttributes = new Dictionary<string, object>
            {
                ["service.name"] = "NLogger",
                ["index"] = 10,
                ["flag"] = true,
                ["pi"] = 3.14
             };
             options.Headers = new Dictionary<string, string>
             {
             	["Authorization"] = "Basic xyz", // user:abc123
             };
             options.BatchingOptions.BatchSizeLimit = 2;
             options.BatchingOptions.Period = TimeSpan.FromSeconds(2);
             options.BatchingOptions.QueueLimit = 10;
         })
         .CreateLogger();

I tried "ApiKey" instead of "Basic" in the authorization header, but still it doesn't work. It writes the log successfully to the text file though.  Please help.

Followed this page [https://github.com/serilog/serilog-sinks-opentelemetry/blob/dev/example/Example/Program.cs](url) as reference.

**Comment by cijothomas** [comment]
I don't think this is using the OTLP Exporter from this repo. If you are using Serilog OpenTelemtry sink, could you ask in that repo first?

**Comment by pvsunilkumar** [comment]
> I don't think this is using the OTLP Exporter from this repo. If you are using Serilog OpenTelemtry sink, could you ask in that repo first?

The tooltip for "WriteTo.OpenTelemetry" is saying "Send log events to an OTLPExporter".  "WriteTo.Sink" is another option available but I am not using that option in the above code.  Please help if i am missing something.

**Comment by Kielek** [comment]
@pvsunilkumar. Serilog team decided to implement own OTLP exporter in the https://github.com/serilog/serilog-sinks-opentelemetr code.
This repository hosts https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol
Serilog implementation is under https://github.com/serilog/serilog-sinks-opentelemetry/blob/dev/src/Serilog.Sinks.OpenTelemetry/Sinks/OpenTelemetry/OpenTelemetrySink.cs with some other helper classes in the same folder.

Please continue your investigation under https://github.com/serilog/serilog-sinks-opentelemetry/issues/109.

BTW Based on this, you should `Bearer` set token: https://www.elastic.co/guide/en/apm/guide/current/open-telemetry-direct.html
