### ISSUE TITLE
Test stability - DiagnosticSourceExceptionCallBackIsNotReceivedForExceptionsHandledInMiddleware

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#4884]
@vishweshbankwar FYI

https://github.com/open-telemetry/opentelemetry-dotnet/pull/4878#issuecomment-1734125522

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/17327289/46314e77-60f2-4fc7-8857-48cc84c38058)

**Comment by reyang** [comment]
Failed again https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/6499900758/job/17654193107?pr=4933

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/17327289/1615f9aa-5d1d-43f6-a0e3-f1ee315955c0)

**Comment by vishweshbankwar** [comment]
I looked at this briefly and it looks like another test is interfering with this one. I will send a PR to disable this one for now until I get chance to take a look more deeply.

**Comment by reyang** [comment]
Failed again https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/6504589733/job/17666762874?pr=4933.

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/17327289/86090a1c-48e0-4f9f-8524-d37d50ce7503)

**Comment by ngruson** [comment]
In PR #5040, we refactored a couple of unit tests and decided to enable `DiagnosticSourceExceptionCallBackIsNotReceivedForExceptionsHandledInMiddleware` again.
This unit test is passing for each TFM now.
Can this issue be closed or leave it open?
