### ISSUE TITLE
Add release notes and change log to NuGet

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#4895]
# Feature Request

**Is your feature request related to a problem?**

The current NuGet packages published from this repo and opentelemetry-dotnet-contrib repo look like 
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/17327289/21bca3bb-eb10-44f2-84a5-d6ff66b8774b)

**Describe the solution you'd like:**

Provide reasonable docs and change history.

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/17327289/c5e62f65-4c9c-491a-b793-44b33f639c49)

## Additional Context

This is how .NET team has solved it https://github.com/dotnet/sdk/blob/c54cc3c8af8d8a7fb182efc080c00baf2765fc8d/src/Containers/packaging/package.csproj#L42-L47.

**Comment by Kielek** [comment]
In AutoInstrumentation we have had similar issue. You can check PRs linked to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2717

Especially it is worth to execute nuget check (even locally). Commands can be found in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2817/files

**Comment by TimothyMothra** [comment]
I found some more resources:
- https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#readme
- https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile

**Comment by phillipsj** [comment]
@reyang @cijothomas I would like to work on this issue if you would like to assign it to me. I'm trying to get more involved and this looked like a good place to get familiar with the project.

**Comment by stevejgordon** [comment]
@phillipsj Are you still working on this? I took a quick look this afternoon. Readme is straightforward. Release notes are more involved, but it could be done with an MSBuild task that parses the changelog in the same way as during the release process. I'd be happy to pick this up if you no longer have the capacity to do it.

**Comment by CodeBlanch** [comment]
Some updates on recent changes...

* We added a top-level `RELEASENOTES.md` which is curated and may be more appropriate for NuGet: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/RELEASENOTES.md

* We also have improved release process/automation to combine `CHANGELOG.md` entries for a given release/tag. Example: https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/core-1.9.0-rc.1.

Perhaps we could just link to curated announcements and release details for version/tag from NuGet?

**Comment by cijothomas** [comment]
> Perhaps we could just link to curated announcements and release details for version/tag from NuGet?

+1

**Comment by RichardChukwu** [comment]
I guess this can be closed to right? @cijothomas

**Comment by cijothomas** [comment]
> I guess this can be closed to right? @cijothomas

No. This still needs to be done. Nuget readme is still blank
![image](https://github.com/user-attachments/assets/efd3ab11-743b-461a-8316-29cc9caf20f4)

**Comment by RichardChukwu** [comment]
Is someone on it already or can I work on it? @cijothomas

**Comment by cijothomas** [comment]
Nobody is actively looking at this from what I can tell. Feel free to take it up! You can work with @TimothyMothra to get some guidance.
