### ISSUE TITLE
Show all status codes using AddAspNetCoreInstrumentation

### ISSUE THREAD

**Issue by mskidavid** [open-telemetry/opentelemetry-dotnet#4898]
We're trying to instrument metrics to Geneva on HTTP-triggered Azure Functions.  We want to emit metrics on successful/failed http requests per API endpoint.
 
Using the following, we are able to get this metric to show: http.server.duration
**AddAspNetCoreInstrumentation()**

However, we can see only the successful requests (200).  How can we modify this to send metrics for all status codes?

**Comment by vishweshbankwar** [comment]
@mskidavid The instrumentation should record metrics for all status codes. Please share a minimal repro if you are seeing a different behavior

**Comment by cijothomas** [comment]
No known issues exist with asp.net core instrumentation. Closing this issue for now - feel free to reopen if you have a repro. Thanks!
