### ISSUE TITLE
Simplify the copyright disclaimer in C# source

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#4900]
# Feature Request

Currently all `*.cs` files have very long copyright disclaimer, e.g. https://github.com/open-telemetry/opentelemetry-dotnet/blob/aeca53949a742aa270e9c94d5a53c6a1821a6802/src/Shared/Guard.cs#L1C1-L15C1.

This is the common practice from other OpenTelemetry projects:

https://github.com/open-telemetry/opentelemetry-demo/blob/f44860602656e2313f3cfe6f7e42a464a341786b/src/cartservice/src/Program.cs#L1C1-L2C39

https://github.com/open-telemetry/opentelemetry-cpp/blob/ad626cec4598165e0d297b0bdb3880968c5dfe88/api/include/opentelemetry/config.h#L1-L2

We should consider simplifying copyright info to:

```text
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0
```

**Comment by reyang** [comment]
Related to https://github.com/open-telemetry/opentelemetry-cpp/pull/754#pullrequestreview-660151937

**Comment by MeenuyD** [comment]
Hello @reyang I would like to work on this issue can you please tell me if should I change the copyrights of all the .cs files to the https://github.com/open-telemetry/opentelemetry-demo/blob/f44860602656e2313f3cfe6f7e42a464a341786b/src/cartservice/src/Program.cs#L1C1-L2C39

**Comment by reyang** [comment]
> Hello @reyang I would like to work on this issue can you please tell me if should I change the copyrights of all the .cs files to the https://github.com/open-telemetry/opentelemetry-demo/blob/f44860602656e2313f3cfe6f7e42a464a341786b/src/cartservice/src/Program.cs#L1C1-L2C39

I think YES, and it's okay to send one giant PR.
However, I suggest that we get feedback from @open-telemetry/dotnet-maintainers to see if they are okay with this approach.

**Comment by Kielek** [comment]
@MeenuyD,  would you like to handle also https://github.com/open-telemetry/opentelemetry-dotnet-contrib/ and https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation ?

Similar changes, both form OTel .NET _family_.

**Comment by MeenuyD** [comment]
Ok I will do
