### ISSUE TITLE
Histogram buckets for connection metrics should be longer than request buckets

### ISSUE THREAD

**Issue by samsp-msft** [open-telemetry/opentelemetry-dotnet#4922]
# Specific bucket definitions for request and connection duration based metrics

The OTel instrumentation libraries are adding a histogram bucket to the view for metrics. The bucket sizes are good for requests which should be very quick - it maxes out at 10s. With Http/1.1 and Http/2, a well behaved system will typically use a connection for multiple requests - and the longer the connection the better. So the histogram buckets used for requests don't scale up well for connections.

The proposal is to have a different bucket definition for connection metrics that tops out at a higher size, such as
[0, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2, 5, 10, 30, 60, 120, 300] based on a unit of seconds.

Which gives an upper bound of 5 mins. It could potentially be scaled higher, but if the goal is to measure http connection durations, then it should give a much better range. The primary concern for Http connections is to reduce the number of short-lived connections that are reestablished, rather than keeping a single one open and re-using it.

This bucketing should be applied to
* System.Net.Http  
  * [http.client.connection.duration](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/dotnet/dotnet-http-metrics.md#metric-httpclientconnectionduration)
* Microsoft.AspNetCore.Server.Kestrel
  * [kestrel.connection.duration](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/dotnet/dotnet-kestrel-metrics.md#metric-kestrelconnectionduration)
* Microsoft.AspNetCore.Http.Connections
  *  [signalr.server.connection.duration](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/dotnet/dotnet-signalr-metrics.md#metric-signalrserverconnectionduration)

**Comment by utpilla** [comment]
@samsp-msft Could you please also update the description of these metrics on the semantic conventions repo to include the histogram bucket information? You could refer to [this](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/http/http-metrics.md#:~:text=server%20span%20duration.-,This%20metric%20SHOULD%20be%20specified%20with%20ExplicitBucketBoundaries%20of%20%5B%200.005%2C%200.01%2C%200.025%2C%200.05%2C%200.075%2C%200.1%2C%200.25%2C%200.5%2C%200.75%2C%201%2C%202.5%2C%205%2C%207.5%2C%2010%20%5D.,-Name)as an example.

**Comment by samsp-msft** [comment]
See [#336](https://github.com/open-telemetry/semantic-conventions/issues/336)

**Comment by samsp-msft** [comment]
> @samsp-msft Could you please also update the description of these metrics on the semantic conventions repo to include the histogram bucket information? You could refer to [this](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/http/http-metrics.md#metric-httpserverrequestduration:~:text=server%20span%20duration.-,This%20metric%20SHOULD%20be%20specified%20with%20ExplicitBucketBoundaries%20of%20%5B%200.005%2C%200.01%2C%200.025%2C%200.05%2C%200.075%2C%200.1%2C%200.25%2C%200.5%2C%200.75%2C%201%2C%202.5%2C%205%2C%207.5%2C%2010%20%5D.,-Name) as an example.

I would suggest that rather than having specific bucket definitions for each histogram, that there are standardized bucket definitions that should be used based on the expected behavior of the metric. That should probably include:
* Single request: used for HTTP requests, DNS lookup, [database](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/database/database-metrics.md#metric-dbclientconnectionscreate_time), [RPC](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/rpc/rpc-metrics.md#metric-rpcserverduration) where the typical results will be in low ms, but could in extreme cases be seconds.
* Semi-durable connection: used for [Http](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/dotnet/dotnet-kestrel-metrics.md#metric-kestrelconnectionduration) & [signalr](https://github.com/open-telemetry/semantic-conventions/blob/d777d26cc14126147bb80e966fea845a27189183/docs/dotnet/dotnet-signalr-metrics.md#metric-signalrserverconnectionduration) connections, which can last from miliseconds through to several minutes or even hours.

**Comment by utpilla** [comment]
> I would suggest that rather than having specific bucket definitions for each histogram, that there are standardized bucket definitions that should be used based on the expected behavior of the metric. 

@samsp-msft If you're proposing that this guidance should come from a more central place in the spec than `docs/dotnet` as proposed in this [PR](https://github.com/open-telemetry/semantic-conventions/pull/283), then please open up an issue on the spec repo for that.

**Comment by utpilla** [comment]
Here are the documentation related PRs:
- https://github.com/open-telemetry/semantic-conventions/pull/283
- https://github.com/dotnet/docs/pull/37811

**Comment by JamesNK** [comment]
@utpilla What is the branch for 1.7.0? Is it main, or is there a 1.7.0 branch that the change needs to be ported to?

**Comment by utpilla** [comment]
> @utpilla What is the branch for 1.7.0? Is it main, or is there a 1.7.0 branch that the change needs to be ported to?

It's the main branch. The tentative date for `1.7.0` stable release is November 30.
