### ISSUE TITLE
OTEL_SEMCONV_STABILITY_OPT_IN=http doesn't enable new metric convention

### ISSUE THREAD

**Issue by karataliu** [open-telemetry/opentelemetry-dotnet#4951]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):
```
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.1-beta.1" />
```
Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):
`net7.0`

## Symptom

Setting OTEL_SEMCONV_STABILITY_OPT_IN=http doesn't turn on `http.server.request.duration`

See repro below.

**What is the expected behavior?**

`filter:'http.server.request.duration'`

**What is the actual behavior?**

`filter:'http.server.duration'`

## Reproduce

Repro code:
```csharp
using System.Reflection;
using OpenTelemetry.Instrumentation.AspNetCore;
using OpenTelemetry.Metrics;

Environment.SetEnvironmentVariable("OTEL_SEMCONV_STABILITY_OPT_IN", "http");
var hscField = typeof(AspNetCoreMetricsInstrumentationOptions)
    .GetField("HttpSemanticConvention", BindingFlags.NonPublic | BindingFlags.Instance);
var builder = WebApplication.CreateBuilder(args);
builder.Services
    .AddOpenTelemetry()
        .WithMetrics(b =>
        {
            b.AddAspNetCoreInstrumentation(o1 => {
                Console.WriteLine("convention:'{0}'", hscField.GetValue(o1));
                o1.Filter = (a, _) =>
                {
                    Console.WriteLine("filter:'{0}'", a);
                    return true;
                };
            });
        });
builder.Build().Run();

```

output:
```
convention:'New'
filter:'http.server.duration' # upon any request, should be 'http.server.request.duration' since convention is new?
```

**Comment by vishweshbankwar** [comment]
@karataliu This change is not yet released. if you `set  OTEL_SEMCONV_STABILITY_OPT_IN=http` then you should get new tags with metric name as `http.server.duration`. Next release should include the change you are expecting i.e. the metric will be emitted as `http.server.request.duration`.

Also, I notice you are using filter. FYI https://github.com/open-telemetry/opentelemetry-dotnet/issues/4932

**Comment by karataliu** [comment]
Thanks @vishweshbankwar for the info.

i'm using filter to repro the issue only for now, thanks for the heads up.

I thought https://github.com/open-telemetry/opentelemetry-dotnet/tree/1.5.1-beta.1 has the change but actually not. Looks like it's in https://github.com/open-telemetry/opentelemetry-dotnet/pull/4802

Looking forward for the new release.
