### ISSUE TITLE
OTEL do not add Exception event if Error handler is configured. 

### ISSUE THREAD

**Issue by aygalinc** [open-telemetry/opentelemetry-dotnet#4961]
# Bug Report

List of [all OpenTelemetry NuGet
Open Telemetry 1.6.0
OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.0-beta.1" 

Runtime dotnet 7 

## Symptom

I configure the dotnet Aspnet instrumentation to record exception : 
```
                    .AddAspNetCoreInstrumentation(it =>
                    {
                        it.RecordException = true;
                        it.Filter = NoHealthCheckFilter;
                    })

```
I expect to have an event in span that contains the exception stack trace. 

Bu If I configure an error handler in aspnet : 
```
app.UseExceptionHandler("/error");
app.Map("/error", ErrorHandler.Handle);
```

I do not retrieve the information (I test without the error handler and it works). 
Is there a workaround or it is mandatory to record the exception in the error handler function ? 

previously i use AppInsight lib to push event and it works without any modification in the error handler.

**Comment by vishweshbankwar** [comment]
@aygalinc exceptions handled in middleware are not recorded via RecordException option. only *unhandledException* is recorded.
