### ISSUE TITLE
Inconsistent EnrichWithHttpResponse when using ExceptionController

### ISSUE THREAD

**Issue by xinyi-joffre** [open-telemetry/opentelemetry-dotnet#4975]
# Bug Report

List of [all OpenTelemetry NuGet
packages:
OpenTelemetry 1.4.0
OpenTelemetry.Instrumentation.Runtime 1.0.0-rc9.14
OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.14
OpenTelemetry.Exporter.Geneva 1.4.1

Runtime version: net7.0

## Symptom

We use EnrichWithHttpResponse to add user properties from HttpContext (such as ObjectId, TenantId) via Activity.SetTag. This works consistently during successful requests.

However, during non-successful requests, we use an ExceptionController to return consistent error messages. For the same type of error (such as message validation error), the EnrichWithHttpResponse is only sometimes called. It seems to be a race condition, where it is sometimes able to set the tags and sometimes not--we know from other logs that the user was authenticated, and the same exception will sometimes have the right tags and sometimes have null tags. This results in incomplete telemetry.

**What is the expected behavior?**

EnrichWithHttpResponse works the same way even when we have non-successful requests through ExceptionController.

What did you expect to see?

Tags being set consistently.

**What is the actual behavior?**

Tags being set consistently for successful requests, but not consistently for requests where exception happened.

**Comment by vishweshbankwar** [comment]
@xinyi-joffre Do you have repro steps for the issue? `EnrichWithHttpResponse` should be called each time.

**Comment by xinyi-joffre** [comment]
Closing this issue! Sorry, I tracked down the issue was that EnrichWithHttpResponse was called, but the issue is that dotnet ExceptionController wasn't populating all identity fields, so logic wasn't triggered.
