### ISSUE TITLE
AspNetCore instrumention sets Span's StatusDescription to Exception message

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#4983]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L422 Is storing Exception.Message as Status.Description. 

The [semantic convention for http](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#status) does not prescribe such a behavior. Neither does the [Tracing API.](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status)

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs#L184 similar for asp.net 

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs#L335 for httpclient. Maybe better to track separately.

**Comment by vishweshbankwar** [comment]
completed in #5025
