### ISSUE TITLE
Can InstrumentationLibrary offer RecordException?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#4984]
Related to https://github.com/open-telemetry/opentelemetry-dotnet/issues/4983, Instrumentation.AspNetCore also stores [Exception via SpanEvents](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L419), (on a opt-in basis). 

Given the spec for [reporting exception as SpanEvent is still experimental](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/exceptions.md), opening an issue to track potentially remove this feature from the instrumentation for stable release.

**Comment by vishweshbankwar** [comment]
Instrumentation libraries can offer additional configuration options not listed in spec. I think it is ok to keep this. We would need to ensure we get the same experience in `NET9.0` when trace instrumentation is natively in ASP.NET Core and HttpClient.

@open-telemetry/dotnet-maintainers FYI
