### ISSUE TITLE
Create a docker image with the aspnet + the collector

### ISSUE THREAD

**Issue by luizfbicalho** [open-telemetry/opentelemetry-dotnet#4997]
**Is your feature request related to a problem?**

In azure web apps for example it's better to use just a container with a image than a container composed, the compose is preview this day.

**Describe the solution you'd like:**

I would like an docker image that would have the collector running side by side with the aspnet application

**Describe alternatives you've considered.**

The alternative is the compose but I think this would be a simpler one

**Comment by cijothomas** [comment]
Not clear what is the ask from this repo? We publish our components as nuget packages only.... The otel-collector publishes docker images, so maybe you wanted to ask in the collector repo?

**Comment by luizfbicalho** [comment]
yeah, sorry, wrong repo
