### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by gregkalapos** [open-telemetry/opentelemetry-dotnet#5]
I think it'd make sense to agree on what namespaces the project should use.

#1 seems to be the way to go, and if #3 gets merged we'll end up with `OpenCensus` in the repo. 

Suggestion 1: 
- We just rename every `OpenCencus` namespace to `OpenTelemetry`.

Any other ideas?

**Comment by austinlparker** [comment]
I'd say use `OpenTelemetry` as the root namespace, yeah, then `OpenTelemetry.API` for the API and `OpenTelemetry.SDK` for the implementation?

**Comment by SergeyKanzhelev** [comment]
We can make `OpenTelemetry.Abstractions` and `OpenTelemetry` for SDK. This will be aligned with the general pattern in C#.

**Comment by austinlparker** [comment]
Works for me.

**Comment by gregkalapos** [comment]
> We can make `OpenTelemetry.Abstractions` and `OpenTelemetry` for SDK. This will be aligned with the general pattern in C#.

Sounds good. I guess this is already the case, except it's called `OpenCensus` and not `OpenTelemetry`. Is there any strategy? Do we wanna bulk rename everything, or only rename certain things? I can go on and adjust the namespaces and the project files.

**Comment by SergeyKanzhelev** [comment]
closing than. We can revisit names if those would not work in an OpenTelemetry world.
