### ISSUE TITLE
Do not validate tracestate

### ISSUE THREAD

**Issue by justinfoote** [open-telemetry/opentelemetry-dotnet#501]
Right now, the opentelemetry-dotnet implementation of W3C TraceContext is validating every tracestate entry (See [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/Context/Propagation/TraceContextFormat.cs#L249-L251)), and if any invalid entries exist, the entire tracestate is dropped.  
The W3C Spec allows for validation, with this text:
> The vendor MAY validate the tracestate header. If the tracestate header cannot be parsed the vendor MAY discard the entire header. Invalid tracestate entries MAY also be discarded.

But there is an open issue (https://github.com/w3c/trace-context/issues/384) to change that to a _SHOULD NOT_, rather than a _MAY_.

But if OpenTelemetry drops tracestate if any invalid entries are found, it will force every other tracing vendor to also validate every tracestate entry, or risk OpenTelemetry dropping the whole tracestate.  

I propose that this project remove all validation of tracestate entries.  

Or, at the very least, I propose that this project drop only invalid tracestate entries, rather than the entire tracestate payload.

**Comment by SergeyKanzhelev** [comment]
Tracestate is not validated by .NET (native implementation). Tracestate parsing in this repository is strict as there are no clear guidance on which non-compliant `tracestate`s are acceptable and which are not. Unless this guidance is documented I suggest we keep the current behavior. Please re-open if disagree.
