### ISSUE TITLE
How to replace the call options.Enrich  using the latest version?

### ISSUE THREAD

**Issue by ZedZipDev** [open-telemetry/opentelemetry-dotnet#5018]
I have updated NuGets and now have an error:

How to replace this piece of code?

options.Enrich = (activity, eventName, rawObject) =>
{
    if (eventName != "OnStartActivity") return;
    if (rawObject is not HttpRequest context) return;
    if (!context.Headers.TryGetValue("SOAPAction", out var soapAction)) return;
    var trimmedAction = soapAction.FirstOrDefault()
        ?.Replace("\"", "")
        .Replace("http://tempuri.org/IWCFDataSvc/", "");
    activity?.SetTag("WCF.action", trimmedAction);
};

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md#100-rc99

Please check the changelog.
