### ISSUE TITLE
What is the plan and ETA to release stable versions of OpenTelemetry beta libraries?

### ISSUE THREAD

**Issue by vaibhavjainTM** [open-telemetry/opentelemetry-dotnet#5027]
# Question

Some of the OTel libraries are still in beta version. 

1) OpenTelemetry.Instrumentation.AspNet
2) OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule
3) OpenTelemetry.Instrumentation.AspNetCore
4) OpenTelemetry.Instrumentation.Http
5) OpenTelemetry.Instrumentation.Process
6) OpenTelemetry.Instrumentation.SqlClient
7) OpenTelemetry.PersistentStorage.Abstractions
8) OpenTelemetry.PersistentStorage.FileSystem

All above libraries are beta only. When you are planning to release stable versions of these libraries?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet#release-schedule Check this for components released from this repo.
