### ISSUE TITLE
Coerce invalid span attribute values to strings

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#503]
If an invalid data type is used for a span attribute value, currently an empty string is used. It may be useful to try to coerce the value into a string representation to for better debugging and to support lazily loaded values.

Also note, an attribute value can be an `IEnumerable`, which complicates the process of converting the value into a useable string.

**Comment by cijothomas** [comment]
No longer applicable, as span is replaced with activity, and wrapper allow only spec allowed value types.
