### ISSUE TITLE
Broken links due to semantic conventions move

### ISSUE THREAD

**Issue by danelson** [open-telemetry/opentelemetry-dotnet#5030]
The semantic conventions moved from https://github.com/open-telemetry/opentelemetry-specification to https://github.com/open-telemetry/semantic-conventions. As a result there are many broken links in this repository, in READMEs, xml docs, etc. Should we put some effort into updating these? I assume the current location is not going to change again.

If so, I don't mind helping here. Would there be a preference on splitting up PRs?

**Comment by vishweshbankwar** [comment]
@danelson Thanks for reporting this and offering for help. We need to definitely update the links. If the changes are simple enough, then a single PR is good enough.

**Comment by danelson** [comment]
I believe the changes are simple, it just might be a large PR. I will whip up something
