### ISSUE TITLE
Not seeing TraceId in outgoing requests from a service

### ISSUE THREAD

**Issue by joebeernink** [open-telemetry/opentelemetry-dotnet#5035]
# Question

I am using OpenTelemetry.Instrumentation.Http to log my http calls to LogAnalytics via the Azure.Monitor.OpenTelemetry.Exporter. I don't see a traceId for outgoing requests. I do see them for incoming requests (logged by OpenTelemetry.Instrumentation.AspNetCore). 

Is this a known issue? Do I need to set something else up to have all traces in the OpenTelemetry.Instrumentation.Http create and log a traceid?

Here are the versions I'm currently using... will be updating shortly.

		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.6.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.6.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.1-beta.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.5.1-beta.1" />
		<PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0" />

**Comment by vishweshbankwar** [comment]
@joebeernink Do you have a repro that you can share? This is not a known issue.

**Comment by cijothomas** [comment]
For AzureMonitor specifics - I'd suggest to raise this in AzureMonitor repo/support channels.

Are you seeing the same behavior in the ConsoleExporter?

**Comment by joebeernink** [comment]
A little more data:

Here is an incoming call to my service (healthz endpoint)
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/3885965/0506537a-19fe-4275-ac4b-cd773010c35a)

And here is an outgoing call:
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/3885965/1aeeb3c5-0141-4465-9453-3264e05f88a3)

I'll see if I can get a console trace. I think we removed all the console trace libs a while ago. Will have to move some dlls around.

**Comment by joebeernink** [comment]
Confirmed... I am seeing the TraceId in the Console logs... so this must be an issue for the AzureMonitorTraceExporter.

With .net 8 coming in a few days, I'll wait and test against that before opening a ticket. From what I hear, everything changes with .net 8... 

Thanks for the suggestion
