### ISSUE TITLE
OpenTelemetryBuilder IServiceProvider overloads

### ISSUE THREAD

**Issue by cmeyertons** [open-telemetry/opentelemetry-dotnet#5037]
# Feature Request

**Is your feature request related to a problem?**

Yes, it is currently opaque on how to configure the Tracing/Meter/Logging providers inside the DI pipeline (not very discoverable)

You have to invoke `WithX()`  then `ConfigureXProvider` and have to dig to figure out how to do it properly.

If you just invoke the `ConfigureXProvider` method, it creates a bug where telemetry is not produced (first hand pain here 😄 )

**Describe the solution you'd like:**

I would like to see an overload of `WithX((IServiceProvider services, XProviderBuilder) = { })` so that its easily discoverable as an overload while configure the `OpenTelemetryBuilder`

## Additional Context

Please see my referenced PR below 😄

**Comment by utpilla** [comment]
Please check this comment: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5038#issuecomment-1804769873

**Comment by cmeyertons** [comment]
@utpilla  thank you for the reply, this clears things up for me, appreciate it!
