### ISSUE TITLE
No output in Grafana from .NET Using OpenTelemetry, despite no errors

### ISSUE THREAD

**Issue by cilerler** [open-telemetry/opentelemetry-dotnet#5059]
I'm aiming to integrate OpenTelemetry with the .NET and Grafana stack, including Loki, Tempo, and Prometheus, to manage logs, traces, and metrics. Despite no error messages being shown, no data appears.

Currently, none of the provided examples are functioning for my setup. To address this, I've established [a streamlined repository](https://github.com/cilerler/dog-stack) containing a docker-compose file which orchestrates the following services:

- otel-collector
- grafana
- prometheus
- tempo
- loki
- minIO

The configuration is derived from the referenced links. The repository also includes a .NET project that produces logs, traces, and metrics when the API endpoints are invoked. Detailed reproduction steps are available in the repository's README.

### Logging

While tracing data is visible in the OTEL-COLLECTOR logs, it does not appear in the Grafana Loki datasource.

```logs
2023-11-16 19:48:55 2023-11-17T00:48:55.513Z    info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "debug", "resource logs": 1, "log records": 1}
2023-11-16 19:48:55 2023-11-17T00:48:55.513Z    info    ResourceLog #0
2023-11-16 19:48:55 Resource SchemaURL: 
2023-11-16 19:48:55 Resource attributes:
2023-11-16 19:48:55      -> telemetry.sdk.name: Str(opentelemetry)
2023-11-16 19:48:55      -> telemetry.sdk.language: Str(dotnet)
2023-11-16 19:48:55      -> telemetry.sdk.version: Str(1.7.0-alpha.1)
2023-11-16 19:48:55      -> service.name: Str(unknown_service:MyCompany.MyApp)
2023-11-16 19:48:55 ScopeLogs #0
2023-11-16 19:48:55 ScopeLogs SchemaURL: 
2023-11-16 19:48:55 InstrumentationScope MyCompany.MyApp.Controllers.MyTestClassController 
2023-11-16 19:48:55 LogRecord #0
2023-11-16 19:48:55 ObservedTimestamp: 2023-11-17 00:48:52.8481467 +0000 UTC
2023-11-16 19:48:55 Timestamp: 2023-11-17 00:48:52.8481467 +0000 UTC
2023-11-16 19:48:55 SeverityText: Information
2023-11-16 19:48:55 SeverityNumber: Info(9)
2023-11-16 19:48:55 Body: Str(Doing something)
2023-11-16 19:48:55 Attributes:
2023-11-16 19:48:55      -> {OriginalFormat}: Str(Doing something)
2023-11-16 19:48:55      -> SpanId: Str(34e2ad309272d41e)
2023-11-16 19:48:55      -> TraceId: Str(bb94de9bfa5a2a0988d7ea387d19d0c8)
2023-11-16 19:48:55      -> ParentId: Str(0000000000000000)
2023-11-16 19:48:55      -> ConnectionId: Str(0HMV70R8AI1V9)
2023-11-16 19:48:55      -> RequestId: Str(0HMV70R8AI1V9:00000001)
2023-11-16 19:48:55      -> RequestPath: Str(/MyTestClass)
2023-11-16 19:48:55      -> ActionId: Str(5394ecfc-4b3c-4c68-aa19-0fdefd5d0b99)
2023-11-16 19:48:55      -> ActionName: Str(MyCompany.MyApp.Controllers.MyTestClassController.DoSomething (MyCompany.MyApp))
2023-11-16 19:48:55      -> MyScopeId: Str(1672c9df-5271-4fec-8167-1e632cf0a031)
2023-11-16 19:48:55 Trace ID: bb94de9bfa5a2a0988d7ea387d19d0c8
2023-11-16 19:48:55 Span ID: 34e2ad309272d41e
2023-11-16 19:48:55 Flags: 1
2023-11-16 19:48:55     {"kind": "exporter", "data_type": "logs", "name": "debug"}
```

### Tracing

Tracing data is absent from both the OTEL-COLLECTOR logs and the Grafana Tempo datasource.

### Metrics

Metrics data is not present in the OTEL-COLLECTOR logs, the metrics endpoint (ports 8888 or 8889), or the Grafana Prometheus datasource. However, Prometheus successfully scrapes port 8888, and as a result, OTEL metrics are viewable in Prometheus, but not the application's.

### References

1. https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/metrics/exemplars/docker-compose.yaml
2. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/demo/docker-compose.yaml
3. https://github.com/open-telemetry/opentelemetry-demo/blob/main/docker-compose.yml
4. https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/docker-compose.yaml
   

### Additional Content

1. [LokiExporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter)
2. [otlp-exporter-configuration](https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/)
3. [exporters](https://opentelemetry.io/docs/collector/configuration/#exporters)
4. [Grafana Cloud OpenTelemetry DotNet](https://github.com/grafana/grafana-opentelemetry-dotnet)
5. [Aspire](https://github.com/dotnet/aspire/tree/main/src/Grafana)

CC: @reyang @pyohannes @matt-hensley

**Comment by cijothomas** [comment]
https://github.com/grafana/opentelemetry-demo The grafana fork of opentelemetry-demo is here. Is that not working? 

> While tracing data is visible in the OTEL-COLLECTOR logs, it does not appear in the Grafana Loki datasource.

I think this is a question for collector/loki repos!

**Comment by cijothomas** [comment]
For traces and metrics, use the example from this repo https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/AspNetCore and modify[ appsettings.json to use "otlp"](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/AspNetCore/appsettings.json#L14-L16) as exporter.

You can run collector with
`docker run --rm -it -p 4317:4317 -p 4318:4318 -v "%cd%":/cfg otel/opentelemetry-collector:0.48.0 --config=/cfg/otlp-collector-example/config.yaml` from [the console examples](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/Console). 

If this does not work, let us know and we can figure out why.

**Comment by cilerler** [comment]
@cijothomas, thank you for the reply. From the answers you provided, it seems you don't fully grasp the struggle I'm facing. The examples are too broad, containing many unrelated cases, and I've distilled them down to the bare minimum for the simplest use case: exposing logs, tracing, and metrics to OTLP, and the OTEL-COLLECTOR should receive these and export them to the selected apps. It's nothing fancy—think of it as a HelloWorld—and it's placed at https://github.com/cilerler/dog-stack. However, it's not working, there is no error message at all, and I'm simply asking for help to identify the issue.

**Comment by martinjt** [comment]
I would suggest a few different debugging paths here.

First would be to add the console exporter to the project, and see if you see metrics/traces/logs coming from the application. If you do, then the issue is likely at the collector end, I'd then simplify the configuration to remove all the ifs/extensions and then build it up to where you have it now.

For the connection between the collector and loki, I'd suggest talking to Grafana labs in their forums etc. as that's more of a Grafana issue than Otel, or Otel.NET.

This does work, I've had this running myself, I can assure you that the data should make it to the collector. Keep in mind for metrics, it may take some time to see it though.

Since your solution is also running on .NET 8.0, you could also try my Aspire extension that will add Logging/Metrics/Tracing dashboards local to the App, so you'll know whether the signals are working. https://nuget.org/packages/AspireDashboard.Extensions

**Comment by pyohannes** [comment]
Thanks @cilerler for trying out the Grafana stack with OpenTelemetry!

Debugging issues like the one you're facing is hard, and I can only echo the advice @martinjt gave:

1. Add a console exporter to your application. If telemetry is missing, it's likely related to problems with the OTel initialization in your .NET application, you will be able to get help in the CNCF [#otel-dotnet](https://cloud-native.slack.com/archives/C01N3BC2W7Q) slack channel.
2. If telemetry data is produced by your application but doesn't make it to the collector (you can check it with the [debug exporter in the collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#local-exporters)), there might be an issue with the OTLP setup in your application or with the receivers set up in your collector. Follow [OTel .NET troubleshooting instructions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#troubleshooting) or ask for help on the CNCF [#otel-collector](https://cloud-native.slack.com/archives/C01N6P7KR6W) slack channel.
3. If this all works and you still don't see logs in Loki, there's something wrong with the exporter setup in the collector or with the Loki setup. Reach out to the Grafana [#opentelemetry](https://grafana.slack.com/archives/C038S86TZGF) slack channel. You will receive help there. Also, any feedback you give there is highly welcome.

Also,  I'd suggest you have a look at [this project](https://github.com/grafana/docker-otel-lgtm/tree/main), which provides the whole Grafana LGTM stack including an OTel collector in a single Dockerfile. You could try to use this instead, or compare its configuration with yours.
