### ISSUE TITLE
No access to span name?

### ISSUE THREAD

**Issue by jacostro** [open-telemetry/opentelemetry-dotnet#507]
Hi,
I'm updating code based on early version of OpenTelemetry. I've just discovered that I can't read current span's name anymore. `TelemetrySpan` no longer has `Name` property. It exists in `SpanSdk`, which is an internal implementation, so inaccessible. `TelemetrySpan` contains `UpdateName` method, so the notion of name does exist on this level.
Is there some deeper thought in not allowing to read span's name?

**Comment by SergeyKanzhelev** [comment]
The idea is that Span must not be used to exchange information so there are setters, but no getters. In Java it is strictly enforced. We are not as strict in .NET. 

What is your scenario so you need access to `Name`?

**Comment by jacostro** [comment]
Thank you for the response. The code I'm referring to is a collector for MVC Core events - a kind of extension for `AspNetCore` collector (more precisely, to the code in `HttpInListener.OnCustom`). In case of some events I was checking current span's name in addition to incoming operation name. 

Reading current span's name seems to me analogous to reading `Activity.Current.OperationName`, which is perfectly available and possibly useful in code like collectors.

**Comment by SergeyKanzhelev** [comment]
So you are listening for callbacks, what are you checking the current span's name for? I wonder what is the scenario here.

**Comment by jacostro** [comment]
Yes, I'm listening for callbacks from `Microsoft.AspNetCore` diagnostic source to get some additional insight into internal stages of MVC processing of a request. As there were some significant gaps in our traces between the start of incoming request and the beginning of our own processing, I thought it might have been interesting to see what MVC is doing in that time. `OpenCensus.Collector.AspNetCore` listens to one MVC event - `Microsoft.AspNetCore.Mvc.BeforeAction` - which is being processed in `HttpInListener.OnCustom` method. I needed to add processing of more MVC events in this place. I'm not quite sure where I am in my trace when event comes in, so I'm checking current span's name before I end it.

By the way, option to plug some additional processing into `OnCustom` by providing a delegate or an interface would be very convenient for this purpose.

The code looks like this:
```csharp
public override void OnCustom(string name, Activity activity, object payload)
{
    if (!name.StartsWith("Microsoft.AspNetCore.Mvc."))
        return;

    var span = Tracer.CurrentSpan as Span;
    if (span is null)
    {
        CollectorEventSource.Log.NullOrBlankSpan(name);
        return;
    }
    if (!span.IsRecording)
        return;

    if (span.Name == "Mvc.Authorization" && 
        name != "Microsoft.AspNetCore.Mvc.BeforeOnAuthorization" && name != "Microsoft.AspNetCore.Mvc.AfterOnAuthorization")
        span.End();

    switch (name) {
        case "Microsoft.AspNetCore.Mvc.BeforeAction": 
            StartSpan("Mvc.Action", span);
            break;
        case "Microsoft.AspNetCore.Mvc.AfterAction":
            if (span.Name == "Mvc.Action") span.End();
            break;
        case "Microsoft.AspNetCore.Mvc.BeforeOnAuthorization":
            if (span.Name != "Mvc.Authorization") StartSpan("Mvc.Authorization", span);
            break;
        case "Microsoft.AspNetCore.Mvc.BeforeOnActionExecution":
            if (span.Name != "Mvc.ActionFilters") StartSpan("Mvc.ActionFilters", span);
            break;
        case "Microsoft.AspNetCore.Mvc.BeforeActionMethod":
            if (span.Name == "Mvc.ActionFilters") span.End();
            StartSpan("Mvc.ActionMethod", span);
            break;
        case "Microsoft.AspNetCore.Mvc.AfterActionMethod":
            if (span.Name == "Mvc.ActionMethod") span.End();
            break;
        case "Microsoft.AspNetCore.Mvc.BeforeOnResultExecuting":
            StartSpan("Mvc.ResultFilters", span);
            break;
        case "Microsoft.AspNetCore.Mvc.AfterOnResultExecuted":
            if (span.Name == "Mvc.ResultFilters") span.End();
            break;
    }
}

private void StartSpan(string name, ISpan parentSpan)
{
    var span = Tracer.StartSpan(name, parentSpan, SpanKind.Internal);
    Tracer.WithSpan(span);
}
```
(This code is based on older version of OpenTelemetry, which you can see from type names.)
I'm checking current span here because I

**Comment by cijothomas** [comment]
No longer relevant with the switch to Activity, which allows read/write freely.
