### ISSUE TITLE
DataDog exporter

### ISSUE THREAD

**Issue by erick-thompson** [open-telemetry/opentelemetry-dotnet#508]
Is anyone aware of a planned Data Dog exporter? I use both App Insights and Data Dog, and using OpenTelemetry seems like a great way to integrate the two.

**Comment by SergeyKanzhelev** [comment]
DataDog is working with OpenTelemetry. So I would expect the exporter will be implemented at some point.

We plan to "evict" vendor specific exporters from this repository https://github.com/open-telemetry/opentelemetry-dotnet/issues/138. So even if implemented, it likely will be in DataDog-specific GitHub account

That's said if you will ask DataDog and somebody will decide to contribute DataDog exporter - happy to help with reviews.

I'm closing the issue as there is no specific steps required from maintainers of this project at this moment.
