### ISSUE TITLE
SpanProcessors input data type

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#509]
SpanProcessors takes `SpanData` as an [input](https://github.com/open-telemetry/opentelemetry-dotnet/blob/ddd13c3eed07819cd1d87e1b9f5c45313b5cd76d/src/OpenTelemetry/Trace/Export/SpanProcessor.cs#L24-L43) which is read only. 

This change breaks the important scenario described here: https://medium.com/opentelemetry/opentelemetry-beyond-getting-started-5ac43cd0fe26

```
public class FlightIDProperties : SpanProcessor
{
  public override void OnStart(Span span)
  {
    foreach( var entry in DistributedContext.Current.Entries)
    {
      span.SetAttribute(entry.Key, entry.Value);
    }
  }
  public override void OnEnd(Span span)
  {
  }

  public override Task ShutdownAsync(CancellationToken token)
  {
    return Task.CompletedTask;
  }
}
```

Need to re-think this API

**Comment by cijothomas** [comment]
Closing as this is no longer relevant. Processors take activity which is read and write allowed.
