### ISSUE TITLE
Documentation - method UseZipkin() doesn't exist

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [open-telemetry/opentelemetry-dotnet#511]
I'm going through readme and in some places, there are calls to the method `UseZipkin`, like

```csharp
services.AddOpenTelemetry(builder =>
{
    builder
        .SetSampler(new AlwaysSampleSampler())
        .UseZipkin()

        // you may also configure request and dependencies collectors
        .AddRequestCollector()
        .AddDependencyCollector()
        .SetResource(Resources.CreateServiceResource("my-service"))
});
```

Unfortunately, method `UseZipkin` without arguments doesn't exist. `TracerBuilderExtensions` has only `UseZipkin(this TracerBuilder builder, Action<ZipkinTraceExporterOptions> configure)` and `Action<ZipkinTraceExporterOptions> zipkinConfigure, Action<
            SpanProcessorPipelineBuilder> processorConfigure)`.

**Comment by MikeGoldsmith** [comment]
Hi @lukasz-pyrzyk - you are correct that none of `UseZipkin`s overloads are paremeterless.

This is a bug in the docs and I've put it into the v0.4 milestone.
