### ISSUE TITLE
Incompatible TraceParent

### ISSUE THREAD

**Issue by federicobarera** [open-telemetry/opentelemetry-dotnet#5141]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry 1.6.0
* OpenTelemetry.Exporter.Console  1.6.0
* OpenTelemetry.Extensions.Hosting 1.6.0
* OpenTelemetry.Instrumentation.AspNetCore 1.6.0-rc.1

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net8

## Symptom

Traces don't get created when a `traceparent` header is sent to the API. The header and format is generated and propagated by a system running application insights

```
traceparent: 00-4ce102de67628f2f0602e4af01ec45ec-622d5b6fc414deb4-00
```

**What is the expected behavior?**

A trace is created nonetheless, otherwise we are losing visibility or requests entering the system at all.

**What is the actual behavior?**

No traces are created. Requests entering the system are not tracked at all.

## Reproduce

https://github.com/federicobarera/otel-repro-2

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by Kielek** [comment]
Your `traceflags` are set to `00`. It means no sampling.
Default sampler is `parentbased_always_on`. It means that the decision is preserved.

Please check with: 
```
traceparent: 00-4ce102de67628f2f0602e4af01ec45ec-622d5b6fc414deb4-01
```

and/or switch you sampler to `always_on` by `builder.SetSampler(new AlwaysOnSampler())`

Ref. https://www.w3.org/TR/trace-context/#trace-flags
