### ISSUE TITLE
How to read W3C trace-context?

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [open-telemetry/opentelemetry-dotnet#516]
Readme in section https://github.com/open-telemetry/opentelemetry-dotnet#context-propagation-out-of-process says that I can read the context from the incoming request. However, I cannot find this API in the code.

There is no field/property on `Tracer` class called `TextFormat` and I don't see any method with signature `Extract(headers, [..])`. Am I missing something?

**Comment by SergeyKanzhelev** [comment]
Are you looking for w3c implementation specifically? Or the way to call into extract? See this:

https://github.com/open-telemetry/opentelemetry-dotnet/blob/cfd198429c3f09fe049805603bc1255d448b34f1/src/OpenTelemetry.Collector.AspNetCore/Implementation/HttpInListener.cs#L68-L80

**Comment by lukasz-pyrzyk** [comment]
For learning purposes, I was following the readme. It gave me the thoughts that I can extract `SpanContext` from the request headers and read `TraceId` / `SpanId` when I want, for example for a quick log message. 

It looks like readme is a little bit out of date when it comes to API call to the `tracer.TextFormat.Extract`, right? `TextFormat` fiedl is not available at the `Tracer` level

**Comment by MikeGoldsmith** [comment]
Currently, span context propagation is broken because Propagators was was removed from `Tracer`. This is because propagators should exist outside of the tracer.

Adding the Propagators API is tracked in #467 and will be required for beta. I've added a comment to the issue to ensure the docs are updated too.

**Comment by SergeyKanzhelev** [comment]
seems like a dup. Closing. Please reopen if you have a question
