### ISSUE TITLE
Clarify license model

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#5187]
## Problem statement

Most parts of this project are under Apache-2.0 license, however, there are few exceptions:

* #4093 introduced [DelegatingOptionsFactory.cs](https://github.com/CodeBlanch/opentelemetry-dotnet/blob/765d1654a0620f3d7ccfa238170ec9339df684f0/src/OpenTelemetry/Internal/Options/DelegatingOptionsFactory.cs#L1-L3) which is under MIT license.
* #4092 introduced three files under MIT license to handle environment variables.

Here is the query https://github.com/search?q=repo%3ACodeBlanch%2Fopentelemetry-dotnet%20%22under%20the%20MIT%20license%22&type=code.

## The asks

1. Follow up and handle MIT license properly (e.g. confirm if we need to include MIT license in README/NuGet/etc.).
2. Check if there are any other license concerns/issues.
3. Update the CONTRIBUTING.md doc and perhaps ISSUE_TEMPLATE to clarify what should be the process for future PRs.

**Comment by reyang** [comment]
@CodeBlanch are there remaining issues?

**Comment by CodeBlanch** [comment]
@reyang I think we're good. I'll close this.
