### ISSUE TITLE
Prometheus Exporer Dupplicate Tag error_type

### ISSUE THREAD

**Issue by vinh3c** [open-telemetry/opentelemetry-dotnet#5199]
# Bug Report

- OpenTelemetry.Exporter.Prometheus.AspNetCore 1.7.0-rc.1
- net8.0

## Symptom

=> Prometheus Pull Agent
label name "error_type" is not unique: invalid sample

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/111959633/86ca79e4-7623-4d4e-a908-cdb38e494087)

When aspnetcore host nginx, Request has a Application Exception, after that the request connection is closed => aspnet core add more than one error tag

## Reproduce

```csharp
var tagsFeature = context
      .Features
      .Get<IHttpMetricsTagsFeature>();
tagsFeature.Tags.Add("error.type", "System.InvalidOperationException")
tagsFeature.Tags.Add("error.type", "MysqlConnector.MySqlException")
```

**Comment by madyar0v** [comment]
+1

**Comment by cijothomas** [comment]
Neither the OTel Metrics API (i.e Meter/instruments from DS), nor the OTel Metrics SDK performs de-duplication, as that will cause perf issues. However, exporters can do de-dup, if the backend it is exporting to cannot deal with duplicates.
We can treat this as a bug in Prometheus Exporter, and fix it. 
Also need to check if OTLP exporter should also provide a feature to dedup on export.

**Comment by AlexBAV** [comment]
I've experienced the same problem.

For a web application running under IIS on Windows Server, after adding a second HTTPS binding, HTTPS redirection middleware starts generating exceptions for HTTP requests which results in duplicate `error_type="System.InvalidOperationException", error_type="System.InvalidOperationException"` items.

**Comment by hacst** [comment]
At first glance this looks very similar to a problem I have been encountering in conjunction with websockets. Imo the fact that AspNetCore itself duplicates this tag is something that should be fixed upstream, so I reported it there.

Now if a user themselves introduced tag duplication that would be a different story.

**Comment by reyang** [comment]
> Imo the fact that AspNetCore itself duplicates this tag is something that should be fixed upstream, so I reported it there.
> 
> Now if a user themselves introduced tag duplication that would be a different story.

Closing this issue as there is no action item for OpenTelemetry.Exporter.Prometheus.AspNetCore.

**Comment by imclint21** [comment]
I got this error too

**Comment by imclint21** [comment]
> > Imo the fact that AspNetCore itself duplicates this tag is something that should be fixed upstream, so I reported it there.
> > Now if a user themselves introduced tag duplication that would be a different story.
> 
> Closing this issue as there is no action item for OpenTelemetry.Exporter.Prometheus.AspNetCore.

@reyang your exporter is not valid for Prometheus, so why close this issue?
<img width="530" alt="image" src="https://github.com/open-telemetry/opentelemetry-dotnet/assets/5221349/c83e35d3-2f6d-4cad-a330-640d7c9cbb73">
