### ISSUE TITLE
Metrics Overflow not reset after export

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#5200]
# Bug Report

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry 1.7.1-alpha.0.30

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can find this information from the `*.csproj` file):

* net8.0

## Symptom

**What is the expected behavior?**

The 2nd export should output:

```text
(T1, T2] color: yellow name: lemon LongSum
Value: 4
```
instead of "otel.metric.overflow"

**What is the actual behavior?**

The 1st export:
```text
Metric Name: MyFruitCounter, Meter: MyCompany.MyProduct.MyLibrary/1.0
(2023-12-28T21:18:29.6586783Z, 2023-12-28T21:18:29.6692484Z] otel.metric.overflow: true LongSum
Value: 5
(2023-12-28T21:18:29.6586783Z, 2023-12-28T21:18:29.6692484Z] color: red name: apple LongSum
Value: 6
```

The 2nd export (which shows "otel.metric.overflow"):
```text
Metric Name: MyFruitCounter, Meter: MyCompany.MyProduct.MyLibrary/1.0
(2023-12-28T21:18:29.6692484Z, 2023-12-28T21:18:29.6878882Z] otel.metric.overflow: true LongSum
Value: 4
```

## Reproduce

Set the following environment variables:

* OTEL_DOTNET_EXPERIMENTAL_METRICS_EMIT_OVERFLOW_ATTRIBUTE=true
* OTEL_DOTNET_EXPERIMENTAL_METRICS_RECLAIM_UNUSED_METRIC_POINTS=true

Run the following program:

```csharp
using System.Diagnostics.Metrics;
using OpenTelemetry;
using OpenTelemetry.Metrics;

public class Program
{
    private static readonly Meter MyMeter = new("MyCompany.MyProduct.MyLibrary", "1.0");
    private static readonly Counter<long> MyFruitCounter = MyMeter.CreateCounter<long>("MyFruitCounter");

    public static void Main()
    {
        using var meterProvider = Sdk.CreateMeterProviderBuilder()
            .AddMeter("MyCompany.MyProduct.MyLibrary")
            .SetMaxMetricPointsPerMetricStream(3)
            .AddConsoleExporter((_, metricReaderOptions) =>
            {
                metricReaderOptions.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = Timeout.Infinite;
                metricReaderOptions.TemporalityPreference = MetricReaderTemporalityPreference.Delta;
            })
            .Build();

        MyFruitCounter.Add(1, new("name", "apple"), new("color", "red"));
        MyFruitCounter.Add(2, new("name", "lemon"), new("color", "yellow"));
        MyFruitCounter.Add(1, new("name", "lemon"), new("color", "yellow"));
        MyFruitCounter.Add(2, new("name", "apple"), new("color", "green"));
        MyFruitCounter.Add(5, new("name", "apple"), new("color", "red"));

        meterProvider.ForceFlush();

        MyFruitCounter.Add(4, new("name", "lemon"), new("color", "yellow"));
    }
}
```

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by samueljrz** [comment]
I'm facing the same issue, but I've started to wonder if this is really a problem. Does the flush function really need to clear memory after flushing data points, or just flushing data point measurement ahead? Because of this first way, the previously created MetricStream would be dereferenced and if there were no measurements from the same previous MetricStream, we would see a metrics gap in the data viewer, unless there is some function in a horizontal TSDB to replicate data points regarding metrics without measurement. That makes sense?
