### ISSUE TITLE
Digital signature is required for all Open Telemetry Instrumentation  dlls

### ISSUE THREAD

**Issue by SanDeshpande** [open-telemetry/opentelemetry-dotnet#5201]
# Feature Request - All the dlls should be digitally signed.

**Is your feature request related to a problem?**

Prove authenticity and maintain tamper resistance.

**Describe the solution you'd like:**
- Digitally sign the managed assembly. for following dlls.
- OpenTelemetry.Instrumentation.AspNetCore.dll
- OpenTelemetry.Instrumentation.Http.dll

**Comment by reyang** [comment]
Related to #1302.

**Comment by reyang** [comment]
Closing as dup #1302.
