### ISSUE TITLE
Add support for GRPC RPC Metrics

### ISSUE THREAD

**Issue by lindeberg** [open-telemetry/opentelemetry-dotnet#5202]
# Feature Request

I want to be able to instrument [RPC Metrics](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-metrics.md) from `Grpc.AspNetCore`.

**Describe the solution you'd like:**
`.AddGrpcInstrumentation()`

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2555 Closing as duplicate of this.
