### ISSUE TITLE
Looking for Clarification on HTTP Stable Semantic Convention support.

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-dotnet#5205]
I'm trying to understand exactly which packages are submitting stable HTTP semantic conventions.  Is this table accurate?

| Instrumentation                                            | OTEL_SEMCONV_STABILITY_OPT_IN supported | `http/dup` supported | Only Stable HTTP SemConv Emitted |
|------------------------------------------------------------|-----------------------------------------|----------------------|----------------------------------|
| [OpenTelemetry.Instrumentation.AspNetCore]                 | [1.5.1-beta.1] - [1.6.0-beta.3]         | YES                  | [1.6.0-rc.1]/[1.6.0]             |
| [OpenTelemetry.Instrumentation.Http]                       | [1.5.1-beta.1] - [1.6.0-beta.3]         | YES                  | [1.6.0-rc.1]/[1.6.0]             |
| [OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule] | NO                                      | NO                   | NO                               |
| [OpenTelemetry.Instrumentation.AspNet]                     | NO                                      | NO                   | [1.7.0-beta.1]                   |
| [OpenTelemetry .NET Automatic Instrumentation Agent]       | [v1.0.0-rc.1] - Latest                  | YES                  | NO                               |

[OpenTelemetry.Instrumentation.AspNetCore]: (https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore)
[OpenTelemetry.Instrumentation.Http]: (https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http)
[OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule]: (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule)
[OpenTelemetry.Instrumentation.AspNet]: (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AspNet)
[OpenTelemetry .NET Automatic Instrumentation Agent]: (https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation)
[1.5.1-beta.1]: (https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/1.5.1-beta.1)
[1.6.0-beta.3]: (https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/1.6.0-beta.3)
[1.6.0-rc.1]: (https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/1.6.0-rc.1)
[1.6.0]: (https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/Instrumentation.AspNetCore-1.6.0)
[1.7.0-beta.1]: (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/releases/tag/Instrumentation.AspNet-1.7.0-beta.1)
[v1.0.0-rc.1]: (https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v1.0.0-rc.1)

**Comment by vishweshbankwar** [comment]
@TylerHelmuth `OpenTelemetry.Instrumentation.AspNetCore` and `OpenTelemetry.Instrumentation.Http` details are correct in the table.

For `OpenTelemetry.Instrumentation.AspNet` - Please ask the question on https://github.com/open-telemetry/opentelemetry-dotnet-contrib since it is part of that repo.

For `OpenTelemetry .NET Automatic Instrumentation Agent` - Reach out to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation

**Comment by Kielek** [comment]
@TylerHelmuth, OpenTelemetry .NET Automatic Instrumentation ~~Agent~~ - please check list of dependencies related to the OpenTelemetry.Instrumentation.* packages. Http sem. conv. i mostly related to these libraries.

Versions can be found in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/CHANGELOG.md
