### ISSUE TITLE
Integrate retry with OTLP exporter

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#5226]
# Feature Request

**Is your feature request related to a problem?**

We have a solution where the OTLP collector and apps that are exporting OTLP data are started at the same time. Also, we have configured a low internal between exporting of OTLP to keep data current.

Because the OTLP senders and receives are starting at the same time, it is possible that OTLP data could be sent to the collector before it is ready to read it. That could cause data to be lost.

**Describe the solution you'd like:**

https://github.com/open-telemetry/opentelemetry-dotnet/pull/4616 added a mechanism for retries, but currently nothing uses it. I'd like the OTLP exporter to start using it for retrying transient failures. If the OTLP collector is unavailable, then the exporter waits a short period and then tries again.

Retries are [part of the OTLP spec](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#retry), and not implementing them is a gap in the OTEL .NET SDK.

In our scenario both apps start up quickly so the time-period where the OTLP collector is unavailable will be small (a few seconds max).

**Describe alternatives you've considered.**

Which alternative solutions or features have you considered?

## Additional Context

Add any other context about the feature request here.

**Comment by cijothomas** [comment]
Thanks! 
Closing in favor of existing issue: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1779
