### ISSUE TITLE
OpenTelemetry Protocol File Exporter

### ISSUE THREAD

**Issue by nagachinni** [open-telemetry/opentelemetry-dotnet#5231]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).

I want to export open telemetry traces to a file rather pushing to an endpoint. As per the [documentation ](https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/#file-storage-requirements:~:text=OpenTelemetry%20Protocol%20File%20Exporter ) the feature is in Experimental stage. But I couldn't find any references how I can make use of this in my dev env. Can someone please help me with the github documentation?

**Comment by cijothomas** [comment]
File exporter is not implemented in OTel .NET. You can use Otel Collector and have it export to file.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter
