### ISSUE TITLE
OpenTelemetry.Instrumentation.AspNetCore Does Not Work as Expected in Azure Function Isolated-Worker Mode

### ISSUE THREAD

**Issue by lsl-2020** [open-telemetry/opentelemetry-dotnet#5232]
# Question

## Descriptions
Hi experts, as title mentioned. `OpenTelemetry.Instrumentation.AspNetCore` is not work as expected. Detailed behaviors: There are indeed `Activity`s generated by .NET framework, but none of them are sampled/recorded. Therefore, child activity has valid `ParentId` but null `Parent`, as is shown in screenshot below.
![1705542845817](https://github.com/open-telemetry/opentelemetry-dotnet/assets/68244035/cdd05fa7-f30a-4399-a480-3e726e71a214)

I have been debugging inside package `OpenTelemetry.Instrumentation.AspNetCore` and found that when Http request comes in, `HttpInListener` does not capture the event at all. My best guess is that Azure Function isolated-worker mode does not rely on internal ActivitySource "Microsoft.AspNetCore", which is the instrumentation package relying on.
Currently I am using a function middleware pipeline as a replacement of the AspNetCore instrumentation package. But I really do hope to get some hints on what's going on here. Thanks!

## Reproduce
- Target Framework: **.NET 6.**
- Platform: **Azure Function isolated-worker mode (LTS)**
- Version of `OpenTelemetry.Instrumentation.AspNetCore`: **1.6.0**
- Debug Code link: https://github.com/lsl-2020/opentelemetry-dotnet-forked/tree/shilei/instrumentation-aspnetcore-1.6.0/examples/MicroserviceExample/FunctionApp
- Azure Function Isolated-worker Repo: https://github.com/Azure/azure-functions-dotnet-worker

**Comment by cijothomas** [comment]
@martinjt Was discussing this exact issue in slack as well!

**Comment by cijothomas** [comment]
Adding @RohitRanjanMS from Azure Functions.

**Comment by cijothomas** [comment]
@lsl-2020 There is no expectation that AspNetCore instrumentation would work in Azure Functions or any other specific frameworks other than regular AspNetCore apps. 
I'll close this issue, given there is no issue with regular AspNetCore apps. 

For the Azure Functions - its a feature request to Azure Functions to provide a native instrumentation support or an instrumentation library. It is entirely possible than OTel's contrib repo will host the instrumentation library, so you may create a feature request there (or directly in Azure Functions repo).

**Comment by RohitRanjanMS** [comment]
Hi @lsl-2020 , Functions host is the right place to add ASPNetCore instrumentation. It's not possible as of now but we are actively working on a feature to enable OpenTelemetry support, ETA April/May. Here's our [roadmap](https://github.com/Azure/azure-functions-host/issues/9273).

**Comment by martinjt** [comment]
@RohitRanjanMS For clarity on the solution you're proposing, it will allow custom samplers for head sampling, full config of the exporters, processors, resource attribute customisation etc.?

The reason I ask is if you'll have all that in April/May, it may not be worth the otel team working on the instrumentation package, however, from what I've been told the solution being worked on wouldn't allow that, only configuring the export?

**Comment by lsl-2020** [comment]
Thank you @cijothomas for the reply.
Thank you @RohitRanjanMS for the kind direction! One last quick question under this thread, the April/May ETA is for private preview or public preview? (I'll move to the azure-functions-host repo for the rest of questions.)

**Comment by RohitRanjanMS** [comment]
May likely for public preview.
