### ISSUE TITLE
Provide option to filter scope attributes from LogRecord in OpenTelemetryLogger ILogger implementation 

### ISSUE THREAD

**Issue by madhub** [open-telemetry/opentelemetry-dotnet#5239]
# Feature Request
Provide option to filter scope attributes from LogRecord in OpenTelemetryLogger ILogger implementation. 

**Is your feature request related to a problem?**
Yes

If so, provide a concise description of the problem.

At present when you enable `OpenTelemetryLoggerOptions.IncludeScopes` flag many **duplicate ( traceid,spanceid etc) & non relevant attributes( ActionId .etc)** are added to LogRecord and their is no option to filter these attributes . Some of these attributes are already part of the LogRecord,  See Refer  #5184 

To **enrich logs with application specific attributes** via logger scope ,  enabling `OpenTelemetryLoggerOptions.IncludeScopes` is the only option, hence need to have some **extensibility** to filter out the attributes that are not relevant for application . 

Below examples shows use case of adding application specific attributes to logger scope
```csharp

List<KeyValuePair<string,object?>> logContext= new List<KeyValuePair<string,object?> 
{
    new KeyValuePair<string, object?>( "CustomerId","1234"),
    new KeyValuePair<string, object?>( "OrderId","768"),
}

using (logger.BeginScope( logContext ))
{
    logger.LogInformation("Processing credit card payment");
}

```

**Describe the solution you'd like:**
Request is to provide some option in `OpenTelemetryLoggerOptions` that takes Scope filter as an option to retain or remove items ? Or some way by installing custom export processor

simple **pseudo code** here, 
```csharp
public class OpenTelemetryLoggerOptions
{
      public Fun<bool ,...> ScopeFilter { get;set;}
}
```

What do you want to happen instead? What is the expected behavior?
A extensible option for the user to filter scope attributes 

**Describe alternatives you've considered.**

Which alternative solutions or features have you considered?

## Additional Context

See Refer  #5184 
Add any other context about the feature request here.

**Comment by cijothomas** [comment]
@rajkumar-rangaraj Could you check what options can be provided here? I think we have discussed long ago to provide some option to limit scope depth. Something like scopedepth = 1 means only the immediate scope (inner most) to the actual log is exported. scopedepth=2 means inner plus one more, and so on. Such control is probably what a lot of users needs, if their intention is to get scopes from their own scopes only, not the ones added by framework itself (which is where most duplicate information is coming from).

**Comment by madhub** [comment]
@cijothomas How does the user know which scope is added by the framework and which is added by the user?.

**Comment by cijothomas** [comment]
> @cijothomas How does the user know which scope is added by the framework and which is added by the user?.

There is no way to make that distinction. (Of course one can look at the contents itself, and make some guesses, but that is pretty much it)

**Comment by cijothomas** [comment]
@madhub We won't be adding a feature to support scope based filtering here.
Here are some mitigations:

1. TraceId/Spanid/ParentId are added to logger scopes by the Asp.Net Core host's default setting. The following can be used to turn them off.
```
   appBuilder.Logging.Configure(o => o.ActivityTrackingOptions = ActivityTrackingOptions.None) // Turn off runtime scope adding TraceId/SpanId/ParentId
    .AddOpenTelemetry(...);
```
2.  https://github.com/dotnet/aspnetcore/blob/ef5aae5a98540c2b3177d27c44cfe4ea5bb7e3b6/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelConnection.cs#L174 is adding another set of scopes. The following filter can disable some logger categories, and get rid of scopes/logs completely:
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/5232798/b7d15f40-1ee6-47ab-a74a-328021fee308)

Thanks @CodeBlanch for digging into the asp.net core and helping.

There may be other places where we can ask asp.net core to stop adding things to scopes, that'll also mitigate more and more of these issues.

A lot of use cases for users manually adding scopes and enabling ILogger scopes in Otel was to achieve some sort of enrichment. There is alternate mechanisms now available to achieve the same. This is already shipped, but not yet documented. We expect to get some docs for this, and then OTel .NET repo will share some best practices around it. If you are eager to try them now, https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.Extensions.Telemetry.Abstractions#log-enrichment is the place to look for.

Additionally, we are removing scopes from the getting started examples - https://github.com/open-telemetry/opentelemetry-dotnet/pull/5254 
Scopes feature is not being removed, just not showing it the getting started examples anymore.

**Comment by madhub** [comment]
> @madhub We won't be adding a feature to support scope based filtering here. Here are some mitigations:
> 
>     1. TraceId/Spanid/ParentId are added to logger scopes by the Asp.Net Core host's default setting. The following can be used to turn them off.
>
> 
> ```
>    appBuilder.Logging.Configure(o => o.ActivityTrackingOptions = ActivityTrackingOptions.None) // Turn off runtime scope adding TraceId/SpanId/ParentId
>     .AddOpenTelemetry(...);
> ```
> 
>     2. https://github.com/dotnet/aspnetcore/blob/ef5aae5a98540c2b3177d27c44cfe4ea5bb7e3b6/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelConnection.cs#L174 is adding another set of scopes. The following filter can disable some logger categories, and get rid of scopes/logs completely:
>        ![image](https://private-user-images.githubusercontent.com/5232798/299510028-b7d15f40-1ee6-47ab-a74a-328021fee308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTg2MTksIm5iZiI6MTcwNjM1ODMxOSwicGF0aCI6Ii81MjMyNzk4LzI5OTUxMDAyOC1iN2QxNWY0MC0xZWU2LTQ3YWItYTc0YS0zMjgwMjFmZWUzMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMTIyNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFjOTcwOTUyNWRjZDBmYjIwMGFjNWI5MWFjMTg5ODBjNGQ1ZTVkNWQ4N2JmZWY1ZjFmMzJhYzIzNWMzOTRlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2Djp97p8SI6GioBLxVl4fSKO-z-ZUGqz1cvKXq7gLMc)
> 
> 
> Thanks @CodeBlanch for digging into the asp.net core and helping.
>
  **I will check the suggested options**
> There may be other places where we can ask asp.net core to stop adding things to scopes, that'll also mitigate more and more of these issues.
> 
> A lot of use cases for users manually adding scopes and enabling ILogger scopes in Otel was to achieve some sort of enrichment. There is alternate mechanisms now available to achieve the same. This is already shipped, but not yet documented. We expect to get some docs for this, and then OTel .NET repo will share some best practices around it. If you are eager to try them now, https://github.com/dotnet/extensions/tree/main/src/Libraries/Microsoft.Extensions.Telemetry.Abstractions#log-enrichment is the place to look for.
> 

**This requires updating to .NET 8 or I need to pull many of the .NET 8 packages . Not an option for at this point**
> Additionally, we are removing scopes from the getting started examples - #5254 Scopes feature is not being removed, just not showing it the getting started examples anymore.

**Comment by madhub** [comment]
@CodeBlanch This is not a generics solution , setting the suggested logger flags also remove other useful debugging information needed during the debugging. 
Also it is not possible to remove "ActionId" and "ActionName" which coming from "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker" logger, setting this logger to none has no effect.
https://github.com/dotnet/aspnetcore/blob/bd016947b6928159814950c06a6e2278be7a256f/src/Mvc/Mvc.Core/src/MvcCoreLoggerExtensions.cs#L22

**Comment by cijothomas** [comment]
> This is not a generics solution

Yes. Its just workarounds/mitigations only.

**Comment by madhub** [comment]
> > This is not a generics solution
> 
> Yes. Its just workarounds/mitigations only.


Is their any discussion to address this issue ?
Also what do you suggest option to remove "ActionId" and "ActionName" which are coming from "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker" logger. Setting this logger to **none** has no effect.
https://github.com/dotnet/aspnetcore/blob/bd016947b6928159814950c06a6e2278be7a256f/src/Mvc/Mvc.Core/src/MvcCoreLoggerExtensions.cs#L22

**Comment by cijothomas** [comment]
> > > This is not a generics solution
> > 
> > 
> > Yes. Its just workarounds/mitigations only.
> 
> Is their any discussion to address this issue ? Also what do you suggest option to remove "ActionId" and "ActionName" which are coming from "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker" logger. Setting this logger to **none** has no effect. https://github.com/dotnet/aspnetcore/blob/bd016947b6928159814950c06a6e2278be7a256f/src/Mvc/Mvc.Core/src/MvcCoreLoggerExtensions.cs#L22

No discussion apart from what I shared above. Here's a summary:
1. There won't be a feature to support Scope filtering in OTel .NET.
2. We share some mitigation tricks to avoid producing the scope in the first place - this is better followed up with the asp.net core as they control producing the scopes. There are some in-progress PRs as well https://github.com/dotnet/aspnetcore/pull/44873
3. ILogger already has other mechanisms to enrich, will be documenting it here as an alternate to scopes. (Scopes are already removed from the getting started docs to avoid users hitting this accidentally.)
