### ISSUE TITLE
Collectors using a different service name and version

### ISSUE THREAD

**Issue by tomstreet** [open-telemetry/opentelemetry-dotnet#526]
I'm using the HttpClientCollector and AspNetCoreCollector and they both appear to be using the wrong service name and version in the spans they create.

I'm using Jaeger to view the traces and they both appear to be using the value of `http.host` as the service name and `semver:0.0.0.0` as the service version.  This causes Jaeger to display the spans as though they are from a different service which is a bit odd. Is this by design or a bug?

**Comment by SergeyKanzhelev** [comment]
bug.

**Comment by longility** [comment]
This may be related to #589

**Comment by longility** [comment]
@tomstreet can you see if the latest version fixes the issue you found?

**Comment by tomstreet** [comment]
Sure. Just need to fix some of the breaking changes and I'll let you know.

**Comment by tomstreet** [comment]
@longility the AspNetCoreCollector is fixed but this is still happening for the HttpClientCollector.

**Comment by tomstreet** [comment]
I think using the host name as the service name is the correct thing for the HttpClientCollector to do isn't it, as this is also what the SqlClientCollector does which makes sense?

I think the problem I'm seeing is Service A has a bunch of spans with the service name set as "Service A", then it sends a request to "Service B" but this has a URL like "serviceb.mynamespace". The Jaeger UI uses different colours for spans in different services, so I'm seeing some green spans for "Service A", then I see a single red span for "serviceb.mynamespace" then I see a bunch of blue spans for "Service B".

**Comment by longility** [comment]
Tom, thanks for taking your time to test the original issue again.

> I think the problem I'm seeing is Service A has a bunch of spans with the service name set as "Service A", then it sends a request to "Service B" but this has a URL like "serviceb.mynamespace". The Jaeger UI uses different colours for spans in different services, so I'm seeing some green spans for "Service A", then I see a single red span for "serviceb.mynamespace" then I see a bunch of blue spans for "Service B".

I also experience and that makes sense to me and I'm okay with it I think. However, I'm no expert. Can someone else verify? @SergeyKanzhelev ?

This is my thought process. When calling service B from service A, I would expect service A to not have service B's service name as that is defined in service B so using the hostname makes sense.

If all this is good, will we be good to close this issue @tomstreet as I assume the original issue has improved, or did I misinterpret what you are saying?

**Comment by SergeyKanzhelev** [comment]
I think it's a dup for #589. Closing, please re-open if this is still a problem
