### ISSUE TITLE
Add links after activity (span) creation

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-dotnet#5273]
# Feature Request

A recent [experimental addition to the OTel specification](https://github.com/open-telemetry/opentelemetry-specification/pull/3678) introduces a new required `AddLink` operation on spans, which allows adding span links after a span was created.

This addition is expected to be declared stable soon (@carlosalberto is driving this), there already exist prototypes for [C++](https://github.com/open-telemetry/opentelemetry-cpp/pull/2380), [Java](https://github.com/open-telemetry/opentelemetry-java/pull/6084), and [Python](https://github.com/open-telemetry/opentelemetry-python/pull/3618). Messaging semantic conventions, which aim at stabilization this year, require this feature.

It should be decided how to make this feature available for .NET users.

**Is your feature request related to a problem?**

As soon as this feature is declared stable, OTel .NET will need to implement it in order to conform to the specification.

**Describe the solution you'd like:**

Ideally, there would be an `Activity.AddLink` method, similar to [`Activity.AddEvent`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.addevent?view=net-8.0) or [`Activity.AddTag`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.addtag?view=net-8.0).

**Describe alternatives you've considered.**

A workaround would be to create a dedicated child span for each link to be added after a span was created. This is cumbersome, as it will drastically increase the number of spans in some cases and obfuscate resulting traces.

**Comment by cijothomas** [comment]
Thanks @pyohannes for raising this. The actual change needs to be done in the .NET runtime repo.

@vishweshbankwar This needs to have a corresponding issue in Runtime repo for consideration in .NET 9 timeframe. Could you open that, and link back here?

**Comment by vishweshbankwar** [comment]
https://github.com/dotnet/runtime/issues/97680

**Comment by cijothomas** [comment]
I'll check if there is anything required here in next 1-2 hours.
