### ISSUE TITLE
Track Cancelled/Aborted Request

### ISSUE THREAD

**Issue by cliedeman** [open-telemetry/opentelemetry-dotnet#5302]
# Feature Request

I would like to track the percentage of aborted/cancelled http server requests

**Describe the solution you'd like:**

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestaborted?view=aspnetcore-8.0

**Describe alternatives you've considered.**

Custom Enrichment

## Additional Context

Add any other context about the feature request here.

**Comment by cijothomas** [comment]
Can you clarify the ask some more?

**Comment by cliedeman** [comment]
Sure.

Here is an example of how we could do it with enrich.

```csharp
                    .AddAspNetCoreInstrumentation(opts =>
                    {
                        opts.Enrich = (string _, HttpContext context, ref TagList tags) =>
                        {
                            tags.Add("cancelled", context.RequestAborted.IsCancellationRequested);
                        };
                    })
```

**Comment by cijothomas** [comment]
I see you are asking if the asp.net core instrumentation should do this by default, without having to write the Enrich? Then the answer is generally no, as the instrumentation follows otel conventions, and there isn't anything about "cancellation requested". It is possible to propose something to the Otel Semantic Conventions group, but its usually accepted for very common things. Your best bet would likely be to do such customizations via Enrich itself.

**Comment by cliedeman** [comment]
thanks @cijothomas  that makes sense.

I looked around in the semantic conventions and this [PR](https://github.com/open-telemetry/semantic-conventions/pull/205) and this open [issue](https://github.com/open-telemetry/semantic-conventions/issues/560)

https://opentelemetry.io/docs/specs/semconv/http/http-spans/#common-attributes

According to the docs for error.type we could stipulate timeout or requestAborted in the error.type.

Currently a request display as successful in the traces/metrics but actually be aborted (aka failed)?

**Comment by cliedeman** [comment]
@cijothomas is this possible now? The linked pull request isn't very clear
