### ISSUE TITLE
Exemplar - remove ExemplarFilter API

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#5333]
Recent spec changes removed the notion of custom ExemplarFilter and only allows 3 built-in values (on/off/tracebased).
We need to remove ExemplarFilter and adhere to this new spec. (ExemplarFilter was only public in experimental builds, but this is breaking change for those releases)

https://github.com/open-telemetry/opentelemetry-specification/pull/3820/files

**Comment by rajkumar-rangaraj** [comment]
The [OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exemplarfilter) doesn't explicitly prohibit the creation of custom exemplar filters, while it mandates support for standard filters like AlwaysOn, AlwaysOff, and TraceBased. Given this, should we still consider the removal of the ExemplarFilter API?

Should we drive clarity in the spec to call out that custom exemplar filters are not supported?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/3820/files 
It does not prohibit, but does not support either. I don't see a need for keeping Filter - it is not particularly useful, as it does not have access even to meter.name or instrument.name, so can't use it for customizing filter based on the meter/instrument.

**Comment by CodeBlanch** [comment]
Work completed: #5404 and #5408
