### ISSUE TITLE
Exemplar - expose ExemplarReservoir and enable View based config

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#5334]
https://github.com/open-telemetry/opentelemetry-specification/pull/3820/files has clarified the config story for Reservoirs.
Though we have Reservoirs, it was neither public nor configurable via View. This issue is opened to track these changes.

(There is non-trivial amount of work, especially for Histogram case, where we want to avoid finding bucket twice, and there is no easy way to achieve that without help from spec... While implementing this, see if spec needs alternation, or spec is not prohibiting what we do.)

**Comment by CodeBlanch** [comment]
We have `internal` support now for setting reservoir via view added on: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5393

More work needs to be done before we can expose things as `public` just capturing this for tracking.

**Comment by CodeBlanch** [comment]
Resolved by #5542
