### ISSUE TITLE
Should `RecordException(this Activity activity, Exception? ex, in TagList tags)` set the attributes `error.type` and `otel.status_code`?

### ISSUE THREAD

**Issue by joegoldman2** [open-telemetry/opentelemetry-dotnet#5346]
# Feature Request

When an exception is thrown but not properly caught, `HttpInListener` records it and sets the attributes `error.type` and `otel.status_code`:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/303ab7a25a81d7804ac7414134366e61a9501114/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L312-L319

When the exception is caught and manually recorded using `activity.RecordException(ex)`, the attributes `error.type` and `otel.status_code` are not set:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/303ab7a25a81d7804ac7414134366e61a9501114/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L81-L104

Should they also be set in this case?

**Comment by vishweshbankwar** [comment]
`RecordException` follows [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#record-exception) and only records exceptions as an event. 

It looks like whether RecordException should also set the Span Status is still an open question (https://github.com/open-telemetry/opentelemetry-specification/issues/1008). 

Regarding `error.type` - this attribute is specific to http conventions https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#common-attributes and that is why its only used with http instrumentations.

**Comment by joegoldman2** [comment]
Thank you for your feedback, it's clear.

`error.type` is also available for messaging convention https://opentelemetry.io/docs/specs/semconv/messaging/messaging-spans/ and maybe others.

**Comment by vishweshbankwar** [comment]
> error.type is also available for messaging convention https://opentelemetry.io/docs/specs/semconv/messaging/messaging-spans/ and maybe others.

I see. Was not up to date with messaging conventions. Thanks for letting me know.

Since there is no action need right now on this from .NET. I am closing this issue.
