### ISSUE TITLE
Ability to add prefixes for exported metrics

### ISSUE THREAD

**Issue by ezhdn** [open-telemetry/opentelemetry-dotnet#5348]
Hi folks!

Is it possible for the exporter to specify a prefix with which metrics can be exported? Or the ability to customize for instrumentation

As example, exists prefix `acme.service`

```
request.duration                               // before prefix

acme.service.request.duration             // after prefix
```

Maybe, according to concepts, this should be done using tags or tags should be added on Prometheus server during on scraping?

**Comment by vishweshbankwar** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk#rename-an-instrument

**Comment by cijothomas** [comment]
> acme.service.

This sounds like something better fitted as Resource or Meter tags.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics#metrics-enrichment

If you backend does not support Resource/Meter tags, then [renaming metrics](https://github.com/open-telemetry/opentelemetry-dotnet/issues/5348#issuecomment-1939162087) would be a workaround.

**Comment by ezhdn** [comment]
But tags may not be a very good solution if there are many values for one tag, which make there will be many dimensions in timeseries.

In docs on Prometheus it is written: https://prometheus.io/docs/practices/naming/

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

**Comment by ezhdn** [comment]
> > acme.service.
> 
> This sounds like something better fitted as Resource or Meter tags. https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics#metrics-enrichment
> 
> If you backend does not support Resource/Meter tags, then [renaming metrics](https://github.com/open-telemetry/opentelemetry-dotnet/issues/5348#issuecomment-1939162087) would be a workaround.

CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

**Comment by cijothomas** [comment]
> But tags may not be a very good solution if there are many values for one tag

That depends. But I guess that is not the question for this issue!
Closing as no further action needed.
