### ISSUE TITLE
Adding duplicate attributes to span

### ISSUE THREAD

**Issue by tomstreet** [open-telemetry/opentelemetry-dotnet#535]
Version: 0.2.0-alpha.197

The `SetAttribute` method name implies that the value for a key is set, implying the key is unique and any additional attempts to set a given key will result in the previous value being overwritten and the last one winning. Currently this is not the case and it behaves like an `AddAttribute` where you are able to add many attributes with the same key.

I feel either this should be renamed to `AddAttribute` - although I'm not sure adding many attributes with the same key makes any sense (unless this is a way of representing arrays maybe?) - or it should behave as the name implies.

**Comment by MikeGoldsmith** [comment]
Spec indicates we should replace existing keys if possible
https://github.com/open-telemetry/opentelemetry-specification/blob/23dbc05986eec68741f82c79174df85a4379836e/specification/api-tracing.md#span-creation.

@SergeyKanzhelev you happy for this to be marked as a bug?

**Comment by eddynaka** [comment]
Hi @tomstreet , can you share a sample? What collector were you using? Thanks!
Hi @MikeGoldsmith , I will try to look at that issue, ok?

**Comment by MikeGoldsmith** [comment]
Hi @eddynaka - I've assigned to you, thanks.
