### ISSUE TITLE
Array tags have newline character when serialized

### ISSUE THREAD

**Issue by MonocleKelso** [open-telemetry/opentelemetry-dotnet#5352]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

```
<PackageReference Include="Honeycomb.OpenTelemetry" Version="1.3.1" />
<PackageReference Include="OpenTelemetry.Contrib.Instrumentation.AWS" Version="1.0.2" />
<PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.5.1" />
<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.4.0-alpha.2" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.7.0" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.7.0" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.7.0" />
<PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.0.0-rc9.4" />
```

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

net6.0 and net7.0

## Symptom

I had originally filed a support issue with Honeycomb because we thought we were seeing behavior where 2 queries that appeared to be identical were returning different results. In reality, the behavior was being caused by either hand keying the WHERE clause in the query versus picking from the auto-complete their UI provides. This was happening because tags with array values were being sent with newline characters at the end. 

Here are images from Honeycomb's engineering team:
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/39304429/b8012144-27f8-44fa-8473-148d73537438)

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/39304429/cf65f340-2dc8-41ce-8b13-7fcadd55d4f2)

This is an example of how we're setting the tag in code:
```csharp
// extension method
public static void SetAttribute(this Activity? activity, string key, object? value)
{
    if (activity is { IsAllDataRequested: true })
        activity.SetTag(key, value);
}

// caller
Activity.Current.SetAttribute("ids", items.Select(m => m.Id).Distinct().ToArray());
```

**Comment by cijothomas** [comment]
> This was happening because tags with array values were being sent with newline characters at the end.

Can you help us by point which component in this repo has the issue? I can see you shared screenshot from a particular vendor, so its not clear if you are facing issues in the particular backend or in with OpenTelemetry components shipped from this repo.

**Comment by MonocleKelso** [comment]
@cijothomas I'm not familiar enough with this repo to pinpoint where the issue is. The Honeycomb service registration doesn't look to be doing anything custom from what I can tell. This is the method that registers the exporter

```csharp
public static TracerProviderBuilder AddHoneycombOtlpExporter(this TracerProviderBuilder builder, string apikey, string dataset = null, string endpoint = null)
{
    return builder.AddOtlpExporter(otlpOptions =>
    {
        otlpOptions.Endpoint = new Uri(endpoint);
        otlpOptions.Headers = HoneycombOptions.GetTraceHeaders(apikey, dataset);
    });
}
```

**Comment by cijothomas** [comment]
Sorry I didn't mean to say find where the issue is in this repo, but help with confirming that the issue is in the OTLP Exporter, and not in your particular backend.

We need to confirm that the SDK or Exporter from is working correctly or not - Please run OTLP Exporter and run OTel Collector with debug output, so we can confirm what is being sent from the OTLP Exporter. If it has any newline characters added by OTLP, then it is a bug and we can fix it. If the Collector is showing no such new line characters, then you need to consult the vendor for further help. Hope that helps!

You may use this example to run OTLP Exporter with Collector:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/Console/TestOtlpExporter.cs#L16
