### ISSUE TITLE
Discuss a new API in .NET

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#540]
See https://github.com/dotnet/runtime/issues/31373 for the discussion on a new API proposal in .NET

**Comment by SergeyKanzhelev** [comment]
Proposal here: https://github.com/dotnet/designs/pull/98

**Comment by cijothomas** [comment]
Closing as the proposals are approved and are shipped/or coming with preview 8 of .NET 5
