### ISSUE TITLE
OTLP Exporter Default impl doesn't match docs

### ISSUE THREAD

**Issue by brandonh-msft** [open-telemetry/opentelemetry-dotnet#5411]
Not sure if this should go against docs or code, so starting here.

In the docs on otel.io we [say](https://opentelemetry.io/docs/languages/net/automatic/config/#otlp):

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/20270743/2f37bd4b-ed7f-4243-8720-061f4ae0e604)

but in main I am [seeing](https://github.com/open-telemetry/opentelemetry-dotnet/blob/fc17a5a33d6e89360db52627f293ab1997d3ed47/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L39)

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/20270743/9df3a2b6-2905-48ee-ab32-67cbbd4892f8)

**Comment by brandonh-msft** [comment]
cc #2959

**Comment by cijothomas** [comment]
https://opentelemetry.io/docs/languages/net/automatic/config/#otlp is not the doc for this repo, it is for auto-instrumentation. 
OTel .NET (components from this repo) uses GRPC as the default only.

**Comment by brandonh-msft** [comment]
> https://opentelemetry.io/docs/languages/net/automatic/config/#otlp is not the doc for this repo, it is for auto-instrumentation. OTel .NET (components from this repo) uses GRPC as the default only.

So does that mean otel.io should update their docs? that is under the .NET section 🤔

**Comment by cijothomas** [comment]
> > https://opentelemetry.io/docs/languages/net/automatic/config/#otlp is not the doc for this repo, it is for auto-instrumentation. OTel .NET (components from this repo) uses GRPC as the default only.
> 
> So does that mean otel.io should update their docs? that is under the .NET section 🤔

I don't think there is any need of an update as the docs are correct only. I think you got confused because it is under .NET, but it is specifically under "automatic", which is our sister-repo https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation!

Of course there are plenty of open issues in website already to clarify "automatic" vs "manual".
