### ISSUE TITLE
Metric Observer callback - enforce timeout?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#542]
Background: https://github.com/open-telemetry/opentelemetry-dotnet/issues/531

This issue is opened for addressing the issue of enforcing a timeout in Observer callbacks. Callbacks are user-defined, and are called during `Meter.Collect()` phase. 
Current implementation does not enforce any timeout. 

1. We need to decide if a timeout should be enforced.
2. If yes, what would be a reasonable timeout.
3. Should we allow user to override it.

**Comment by MikeGoldsmith** [comment]
I don't believe this is covered in [OpenTelemetry-Specification](https://github.com/open-telemetry/opentelemetry-specification), so would probably warrant opening an issue there to make sure we're implement consistently.

My preference would be some sort of overridable configuration set in the Meter SDK builder.
