### ISSUE TITLE
Promote MetricPoint reclaim feature for delta aggregation from experimental to stable

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#5443]
For the experimental feature see: #2360

This issue is for tracking making this a stable feature.

**Comment by vchirikov** [comment]
we have a 17.4 MB endpoint "/metrics" (prometheus exporter) because of the old metrics, waiting for this feature. Is there any news about this?

**Comment by cijothomas** [comment]
> we have a 17.4 MB endpoint "/metrics" (prometheus exporter) because of the old metrics, waiting for this feature. Is there any news about this?
> 
> p.s. ~I will try to use `OTEL_DOTNET_EXPERIMENTAL_METRICS_RECLAIM_UNUSED_METRIC_POINTS` and send the results~ looks like #5546 should be released first

The feature tracked by this is only for DELTA... If you are using Prometheus, then this won't help you, as prometheus only accepts Cumulative.

**Comment by yoziv** [comment]
When is this expected ?

**Comment by cijothomas** [comment]
> When is this expected ?

There is no ETA for this. If you are using the experimental feature, we'd love to get any feedback you have on the feature. We don't have enough feedback to confidently promote this feature to stable. It is also possible that the current approach could be revisited to make it less complex.

**Comment by CodeBlanch** [comment]
We discussed this on the SIG meeting today. We're doing a final review and some testing of the feature but the plan is to remove the envvar and turn it on by default for 1.10.0.
