### ISSUE TITLE
Unintentional breaking changes? `MethodAccessException` when attempting to migrate from v1.7.0 to v1.8.0-beta.1

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-dotnet#5477]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

- OpenTelemetry 1.8.0-beta.1
- OpenTelemetry.Exporter.OpenTelemetryProtocol 1.7.0
- OpenTelemetry.Extensions.Hosting 1.7.0

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

`net472`

## Symptom

**What is the expected behavior?**

Since we are not talking about major version bumps on these packages, I'd expect v1.7.0 dependencies to be fully compatible with 1.8.0 ones, but apparently 1.8.0 introduced breaking changes by removing/changing public methods that are being used by the other dependencies.

**What is the actual behavior?**

`MissingMethodException` is thrown when running the application while bumping `OpenTelemetry` NuGet from v1.7.0 to v1.8.0-beta.1 while using v1.7.0 of `OpenTelemetry.Extensions.Hosting` and `OpenTelemetry.Exporter.OpenTelemetryProtocol`

> System.MethodAccessException: 'Attempt by method 'Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(Microsoft.Extensions.DependencyInjection.IServiceCollection)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.'

And after upgrading `OpenTelemetry.Extensions.Hosting`:
> System.MethodAccessException: 'Attempt by method 'OpenTelemetry.Metrics.OtlpMetricExporterExtensions.AddOtlpExporter(OpenTelemetry.Metrics.MeterProviderBuilder, System.String, System.Action`1<OpenTelemetry.Exporter.OtlpExporterOptions>)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.'

## Reproduce

Create a self-contained project using the template of your choice, apply the
minimum required code to result in the issue you're observing.

https://github.com/julealgon/OtelBreakingChangesRepro

## Additional Context

I wanted to bump `OpenTelemetry` to v1.8.0 to leverage the new envvar-based sampler configuration without affecting anything else in our solution.

I've now updated the other 2 offending packages to 1.8.0 as well to workaround this temporarily.

Yes, I understand 1.8.0 is still a prerelease package, but figured I'd warn the team early for when the final release is published.

**Comment by Mpdreamz** [comment]
I hit this too and it peaked my interest: 

The internal `Guard` class actually had no changes between `1.7.0` and `1.8.0-beta.1` and the assembly identity did not change 

https://nuget.info/packages/OpenTelemetry/1.7.0
https://nuget.info/packages/OpenTelemetry/1.8.0-beta.1

Both still list correctly as:

```
Full Name:OpenTelemetry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c
Strong Name:Yes, version 1.0.0.0
```

**Comment by cijothomas** [comment]
> Since we are not talking about major version bumps on these packages, I'd expect v1.7.0 dependencies to be fully compatible with 1.8.0 ones,

Yes. that is correct! We do have some guards in place to catch such issues... so need to see why it was not caught..

**Comment by CodeBlanch** [comment]
I haven't had time to dig into this completely. But my guess would be the issue is mixing prerelease and non-prerelease packages. We currently have some ~hacks~ features for exposing experimental APIs in prerelease packages which change some of the bits either internal/public/linked into projects.

Is anyone able to verify that it starts to work if you switch all your OTel packages to the 1.8.0-beta.1 versions?

**Comment by Mpdreamz** [comment]
Can confirm the exception goes away if you update all the packages to latest.

**Comment by cijothomas** [comment]
Thanks!
OTLPExporter 1.7 with OTELSDK 1.7 works well
OTLPExporter 1.7 with OTELSDK 1.8 or 1.9 or 1.10  should work well
OTLPExporter 1.8 with OTELSDK 1.8 should work well
OTLPExporter 1.7 with OTELSDK 1.8-prerelease is failing.
