### ISSUE TITLE
envvar-based sampler configuration capability should not be mentioned as part of `1.8.0-beta.1` changelog

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-dotnet#5480]
The recently added feature, to be able to configure trace samplers using environment variables:
- https://github.com/open-telemetry/opentelemetry-dotnet/pull/5448

Was added to the changelog for the `OpenTelemetry` project as if it was part of the 1.8.0-beta.1 release:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/af57de2b017a09a85b3bd4323d7b01b0174b5742/src/OpenTelemetry/CHANGELOG.md?plain=1#L84-L92

This is however incorrect: the feature was merged _after_ v1.8.0-beta.1 had already released. This should've instead been added to the "Unreleased" section.

Note the dates:
Merge on March 19th
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/461579/6f1f421c-6135-4abb-9ac2-687656c3eee3)

Release on March 14th:
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/461579/392c4534-9f1d-4f5f-8a6f-bb0bbe7ead18)

This particular issue caused me to waste a couple hours yesterday testing the functionality. I had found the environment variables in the OTEL Spec documentation, searched for them in the repo, and found out "it was added as part of v1.8.0-beta.1". So I proceeded to upgrade the library on our project and try to make it work.

I'm aware this was _not_ mentioned in the actual release notes however, but I didn't look at that until much later, and that's when I noticed the 'CHANGELOG.md' had more changes in it than the release notes and everything clicked for me.

This is more of a documentation change request so I felt it made sense to open an issue vs a discussion.

Related:
- https://github.com/open-telemetry/opentelemetry-dotnet/issues/5477

**Comment by Kielek** [comment]
@julealgon, could you please create PR and move the entry to unreleased section?

**Comment by Kielek** [comment]
Can be closed by #5483
