### ISSUE TITLE
Unable to build sln on non-Windows

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#549]
There is a build error when building on a machine without Visual Studio installed. This is because the newly added ASP.NET collector #543 included a new sample project that has a project import with a `VSToolsPath` prefix which is not available:
[OpenTelemetry.Exporter.AspNet.Win.csproj#L109](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/samples/Exporters/AspNet/OpenTelemetry.Exporter.AspNet.Win.csproj#L109)

The error message I see locally is:
```bash
/Users/mgoldsmith/code/opentelemetry-dotnet/samples/Exporters/AspNet/OpenTelemetry.Exporter.AspNet.Win.csproj(109,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/3.1.101/Microsoft/VisualStudio/v16.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/3.1.101/Microsoft/VisualStudio/v16.0/WebApplications/Microsoft.WebApplication.targets" is correct, and that the file exists on disk.
```

@CodeBlanch

**Comment by CodeBlanch** [comment]
@MikeGoldsmith I'll mess with it and try to come up with a way to have the old-style projects ignored when VS isn't available. What are you using to build? Win, Mac, Linux? VS Code, MSBuild, dotnet CLI? Might be a few days out I have a bunch of work in the pipe.
