### ISSUE TITLE
Some code samples are incorrect

### ISSUE THREAD

**Issue by TimothyMothra** [open-telemetry/opentelemetry-dotnet#550]
Several code samples in the [Readme](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/README.md) have a reference to `tracer.SpanBuilder("incoming request")` but this method does not exist.

I see `SpanBuilderShim : ISpanBuilder` in the Shims.OpenTracing project, but that's the only reference I could find.

**Is this meant to be a future deliverable or is this a mistake?**

Both Zipkin and ApplicationInsights reference this method in the Readme doc, but their sample apps have very different examples.

**Comment by MikeGoldsmith** [comment]
This is an old API pattern that we've moved away from. The example docs need to be updated to use `tracer.StartActiveSpan`.

**Comment by eddynaka** [comment]
@MikeGoldsmith / @TimothyMothra , just updated the samples in README. Let me know if those are alright! Thanks.

**Comment by MikeGoldsmith** [comment]
Thanks @eddynaka - I'll review your PR shortly.
