### ISSUE TITLE
Move remaining instrumentation libraries to the opentelemetry-dotnet-contrib repo

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet#5526]
The repo currently maintains the following instrumentation libraries:

* `OpenTelemetry.instrumentation.AspNetCore`
* `OpenTelemetry.instrumentation.HttpClient`
* `OpenTelemetry.instrumentation.SqlClient`
* `OpenTelemetry.instrumentation.GrpcNetClient`

We should consider them moving all to the [contrib repo](https://github.com/open-telemetry/opentelemetry-dotnet-contrib) and keep this repo focused mainly on core components.

**Comment by cijothomas** [comment]
We'll miss some _extra_ test coverage by doing this, but that is okay, since all signals/instrumentations are stable already!

**Comment by vishweshbankwar** [comment]
@cijothomas - Thats a good point. I think that can be managed by upgrading the dependencies on instrumentation libraries in timely manner.

**Comment by Kielek** [comment]
Labels on contrib side:

* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/labels/comp%3Ainstrumentation.grpcnetclient
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/labels/comp%3Ainstrumentation.sqlclient
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/labels/comp%3Ainstrumentation.httpclient
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/labels/comp%3Ainstrumentation.aspnetcore

**Comment by reyang** [comment]
Also, migrate the existing GitHub issues that are related to these components.

**Comment by reyang** [comment]
I think this is done.
