### ISSUE TITLE
Release changes for unstable core components

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#5530]
The following components are considered part of core (defined by the spec) but have not been released stable:

* `OpenTelemetry.Exporter.Prometheus.AspNetCore`
* `OpenTelemetry.Exporter.Prometheus.HttpListener`
* `OpenTelemetry.SemanticConventions`
* `OpenTelemetry.Shims.OpenTracing`

As discussed on the SIG meeting 4/9/2024, we're going to change how these packages are released to make things more consistent and have a defined process for packages which previously had no official process.

* We will only release `alpha` & `beta` versions of these packages. We have in the past released `rc` packages of the Prometheus projects but it was decided it doesn't make sense to have a "release candidate" for something we have no intention of releasing.

* These packages will now depend only on the stable versions of the core packages (API, SDK, etc.). Today they always depend on prerelease versions.

* `OpenTelemetry.Exporter.Prometheus.AspNetCore`, `OpenTelemetry.Exporter.Prometheus.HttpListener`, & `OpenTelemetry.Shims.OpenTracing` will be released at a minimum once after a stable release of core packages. `OpenTelemetry.SemanticConventions` is rarely changed and has no dependencies so it will only be released after a stable release of core packages if changes were actually made.

**Comment by Kielek** [comment]
I like overall concept. The semantic convention should be reconsidered and released separately from core packages. It should be strictly related to sen conv. releases. 

As I remember @lmolkova was working on tool sem conv. generation which should make this package more usable.

**Comment by CodeBlanch** [comment]
Update. #5539 removed `OpenTelemetry.SemanticConventions` and @alanwest unlisted the package. We should probably resurrect it over in contrib if anyone wants to take on turning it into something useful.

**Comment by klinki** [comment]
Hi, sorry for commenting on closed issue but what is the reason for not releasing stable packages? Is it still waiting for the OpenTelemetry specification?

We were considering using `OpenTelemetry.Exporter.Prometheus.AspNetCore` some time ago, but used `prometheus-net.AspNetCore` instead as it is stable. But I keep monitoring OpenTelemetry status, as it seems to be more modern and actively developed.

**Comment by cijothomas** [comment]
@klinki 
You are right, there is not stable spec for OTel to Prometheus mapping. The main readme for prometheus exporter also call it out.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.Prometheus.AspNetCore#prometheus-exporter-aspnetcore-for-opentelemetry-net
