### ISSUE TITLE
System.TypeLoadException:“Could not load type 'OpenTelemetry.Internal.ConfigurationExtensions' from assembly 'OpenTelemetry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c'.”

### ISSUE THREAD

**Issue by PSC-F** [open-telemetry/opentelemetry-dotnet#5564]
need  upgrade to 1.8.1

**Comment by CodeBlanch** [comment]
@PSC-F What OTel package versions are you using? Are you mixing prerelease & stable versions? My guess is this is the same as #5477 which should be fixed in the next release cycle.

**Comment by Watertight-skaat** [comment]
getting this with version 1.10 when trying to use the console exporter on .net9
