### ISSUE TITLE
Metrics Processor

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [open-telemetry/opentelemetry-dotnet#5583]
# Feature Request

**Is your feature request related to a problem?**

Yes, I would like to filter metrics. For example, I would like to FILTER OUT metrics that are zero-ed, like "You received zero http requests" or "Your Http queue is zero"

**Describe the solution you'd like:**
```
builder.Services.AddOpenTelemetry()
     .ConfigureResource(cfg => cfg.AddAttributes(resourceAttributes))
     .WithMetrics(builder => builder.AddAspNetCoreInstrumentation()
          .AddRuntimeInstrumentation()
          .AddProcessInstrumentation()
       ***.AddPROCESSOR<MyCustomProcessor>()***
```
## Additional Context

Having fine grain control over metric beings reported is very useful, specially if you are using solutions that charge you based on the volume of data you report

**Comment by cijothomas** [comment]
As mentioned in [this doc](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics#metrics-enrichment), the notion of Metrics/MeasurementProcessor does not exist in OpenTelemetry specification. However, a new concept for [Filtering is now an experimental spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricfilter). This repo has not implemented that capability yet, but hopefully that is what you are looking for.

**Comment by Leonardo-Ferreira** [comment]
yeah, that's close to what im looking for... I don't think that spec allows for filtering based on the value of the metric

**Comment by Leonardo-Ferreira** [comment]
I created a PR: https://github.com/open-telemetry/opentelemetry-specification/pull/4025

**Comment by cijothomas** [comment]
> yeah, that's close to what im looking for... I don't think that spec allows for filtering based on the value of the metric

I don't think that is what you need. I left comments in the spec PR asking for more clarification.
