### ISSUE TITLE
Replace Austin with Mike as maintainer

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#559]
I'd like to suggest myself replacing Austin (@austinlparker) as a maintainer as he is no longer actively engaged with the OpenTelemetry .NET project due to other commitments and taking on a more general role within OpenTelemetry.

I've been a member of OpenTelemetry org since November 27th 2019 and an active approver since January 7th 2020. I attend the .NET SIG regularly, help coordinate & plan work and encourage contributions.

@open-telemetry/dotnet-approvers

**Comment by austinlparker** [comment]
+1 It doesn't appear that I'll have time for any contributions to this SIG going forward and I believe Mike will do a great job.

**Comment by SergeyKanzhelev** [comment]
Let's not call it replace =). I'm supportive of appointing @MikeGoldsmith as maintainer. I'm also OK removing @austinlparker
