### ISSUE TITLE
Is the new metrics sdk  available?

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#562]
Is the new metrics sdk available and where have any basic examples of how to use new metric sdk to Collector different metrics (Counter/Gauge/Histogram/Summary)

**Comment by cijothomas** [comment]
Counter, Observer, Measure - are the only instruments with Sum, LastValue, MinMaxSumCount being corresponding aggregator.

I am implementing a Controller now, which is a must have before we can have a usable metric sdk - will be posting E2E examples along with that.

**Comment by czs1993** [comment]
awesome, thanks @cijothomas ! Keep up with the great work you are doing.
