### ISSUE TITLE
OpenTracing shim usage

### ISSUE THREAD

**Issue by geofflamrock** [open-telemetry/opentelemetry-dotnet#564]
Hi,

I'm wondering if there are any samples or guidance that could be given on how to configure the OpenTracing shim? I'm having trouble working out how to configure it up inside an Asp.Net Core app.

Thanks.

**Comment by geofflamrock** [comment]
I've just realised I'm looking at it the wrong way, I thought it was a shim that exported OpenTelemetry traces to OpenTracing, but it appears to be the other way OpenTracing -> OpenTelemetry. 

Some samples or docs would be helpful still I expect, but doesn't hit the use case I was trying to test at the moment.

**Comment by MikeGoldsmith** [comment]
Thanks for the update @geofflamrock. I agree additional docs describing what exactly the shim can do and how to configure it would be good.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/examples/Console/TestOpenTracingWithConsoleExporter.cs - Sample for OpenTracing shim is added now.
