### ISSUE TITLE
Promote overflow attribute from experimental to stable

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#5641]
We have an experimental envvar now (`OTEL_DOTNET_EXPERIMENTAL_METRICS_EMIT_OVERFLOW_ATTRIBUTE`) for turning on a feature to emit a metric anytime cardinality limit/overflow is encountered.

This issue is for tracking making this a stable feature.

**Comment by reyang** [comment]
Related to https://github.com/open-telemetry/opentelemetry-specification/issues/3904.
