### ISSUE TITLE
Remove polyfill packages

### ISSUE THREAD

**Issue by thompson-tomo** [open-telemetry/opentelemetry-dotnet#5658]
### Package

OpenTelemetry.Exporter.Console

### Is your feature request related to a problem?

I have run into issue with System.Text.Json conflicting in the past due to being an explicit dependency

### What is the expected behavior?

Only dependencies of the packages are those which can be provided by the framework ie no System.Text.Json on the newer TFM's

### Which alternative solutions or features have you considered?

Accept the additional dependencies

**Comment by vishweshbankwar** [comment]
@thompson-tomo - Would you be interested in sending the PR for this?

**Comment by thompson-tomo** [comment]
@vishweshbankwar Sure I can do it in the next couple of days
