### ISSUE TITLE
Prometheus exporter produces zero-byte HTTP response

### ISSUE THREAD

**Issue by Abrynos** [open-telemetry/opentelemetry-dotnet#5661]
### Package

OpenTelemetry.Exporter.Prometheus.AspNetCore

### Package Version

| Package Name                                  | Version       |
| --------------------------------------------- | ------------- |
| OpenTelemetry.Exporter.Prometheus.AspNetCore  | 1.9.0-alpha.1 |
| OpenTelemetry.Extensions.Hosting              | 1.9.0-alpha.1 |
| OpenTelemetry.Instrumentation.AspNetCore      | 1.8.1         |
| OpenTelemetry.Instrumentation.Http            | 1.8.1         |
| OpenTelemetry.Instrumentation.Runtime         | 1.8.1         |

### Runtime Version

net8.0

### Description

Using Prometheus exporter `1.9.0-alpha.1` I'm getting a bunch of zero-byte responses from the metrics endpoint; status code is `200` and `Content-Length` header is `0`.

This issue has been verified by another user as well:
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/6608231/dc2af5ee-5229-498f-810a-bfd3ec9026a6)

It does not make a difference whether I access directly/behind nginx, via http/https, via hostname/IP-address or even with/without password configured in the application.

Here are corresponding TRACE logs (I've replaced my actual password of course 😉):
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/6608231/2a48471a-b5b5-40bf-9bd5-0b725765f869)

### Steps to Reproduce

Two possibilities:

- Copy the example source code from the sources linked below into separate project.
  - [Asp.Net startup](https://github.com/JustArchiNET/ArchiSteamFarm/blob/d25883ff1bb25d2a589551396b3a3fb3317cc8ad/ArchiSteamFarm/IPC/ArchiKestrel.cs) (plugin is loaded at lines 249 and 404)
  - [Plugin](https://github.com/JustArchiNET/ArchiSteamFarm/blob/d25883ff1bb25d2a589551396b3a3fb3317cc8ad/ArchiSteamFarm.OfficialPlugins.Monitoring/MonitoringPlugin.cs) (lines 101 to 129)
  
- Set up [ArchiSteamFarm](https://github.com/JustArchiNET/ArchiSteamFarm/) in "generic" configuration and install it's "monitoring plugin". The application release is still tracking version `1.7.0-rc.1` so you either need to manually build or grab it from the build pipeline where we originally wanted to upgrade to the newest version [over here](https://github.com/JustArchiNET/ArchiSteamFarm/actions/runs/9181369538).

Until now I was not yet able to reproduce it using only localhost but only on a remote host so keep in mind that you might need to have a phone or raspberry pi at hand.

### Expected Result

Response from prometheus metrics endpoint contains metrics.

### Actual Result

Response status code is `200` and `Content-Length` header is `0`.

### Additional Context

Thank you in advance for looking into this. If I can be of any assistance, please let me know.

**Comment by JustArchi** [comment]
It's important to add that version `1.7.0-rc.1` works properly. It's not the last version where it did work properly, however, we skipped higher ones due to another bug (https://github.com/open-telemetry/opentelemetry-dotnet/issues/5506).

**Comment by miniduikboot** [comment]
We're seeing similar issues after around 12 to 18 hours of uptime, although this depends on server load, with less loaded servers surviving for longer. We're also using a plugin to hook into a larger (ASP).Net application in a similar way as JustArchi.

**Comment by raphaelquati** [comment]
Here, the same error occurs too. The metrics endpoint suddenly stop responding.

I reverted  to 1.7.0-rc.1, and it's working again

**Comment by tai-yi** [comment]
👁️Sice 1.8.x `OpenTelemetry.Exporter.Prometheus.AspNetCore` became...
Every new version tried then have to revert to `1.7.0-rc.1`(●'◡'●)
