### ISSUE TITLE
How does OTel semver conention work?

### ISSUE THREAD

**Issue by smoms** [open-telemetry/opentelemetry-dotnet#5666]
### What is the question?

Hi,

I am not sure I understand correctly but how does OTel semantic version work?
[Here ](https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/Instrumentation.AspNetCore-1.7.1) is an example of patch number increase containing a **breaking changes**!?
It is not in line with dotnet packages semver convention..?!

please advice.

thanks

**Comment by vishweshbankwar** [comment]
@smoms - Please see https://github.com/open-telemetry/opentelemetry-dotnet/blob/c38cc273bcd03949897d1585e9bc083962cb5f22/VERSIONING.md#versioning-details

**Comment by vishweshbankwar** [comment]
Answered the ques above
