### ISSUE TITLE
Could not load file or assembly Thrift, Version=0.13.0.0

### ISSUE THREAD

**Issue by longility** [open-telemetry/opentelemetry-dotnet#568]
I think it is related to this PR change #545 

Unless I install `ApacheThrift` nuget pkg `0.13.0.1`, I get the following error:
![image](https://user-images.githubusercontent.com/720635/78394522-6b6a2100-75b1-11ea-9496-d837342a3c95.png)

**Comment by CodeBlanch** [comment]
@longility I just tested with the Thrift package fix (#545)(https://www.myget.org/feed/opentelemetry/package/nuget/OpenTelemetry.Exporter.Jaeger/0.2.0-alpha.231) and everything seems good now. Can you confirm the same?

**Comment by longility** [comment]
@CodeBlanch Seems to work for me too. Thanks!
