### ISSUE TITLE
Tutorial of `getting-started-aspnetcore` is not working as it refers un-released API

### ISSUE THREAD

**Issue by konjac** [open-telemetry/opentelemetry-dotnet#5686]
### What is the question?

The sample in [README](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/README.md) is actually not working now.

The code(https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/getting-started-aspnetcore/Program.cs) is using the API of `OpenTelemetryBuilder.WithLogging`,  which is newly introduced in #5648  and not released yet. If users follow the document to install packages from public nuget feeds, they will hit compile error.

**Comment by cijothomas** [comment]
1.9.0.-rc.1 should have this. Can you update to that and see?

**Comment by vishweshbankwar** [comment]
1.9.0 is released.
