### ISSUE TITLE
[Question] Trace attribute http.route vs url.path

### ISSUE THREAD

**Issue by g3david405** [open-telemetry/opentelemetry-dotnet#5692]
### What is the question?

I am currently using OpenTelemetry + Tempo to monitor my C# application. 
I am curious about the difference between **url.path** and **http.route** in the attributes.
In some applications' traces, http.route does not appear, while in others, url.path is missing. 
If the **http.route** attribute is missing, the trace name only displays HTTP methods, making it very difficult for me to troubleshoot issues.
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/75260884/1bb31e49-5546-4228-a7a2-d3048bc67dc8)

In some application, I don't know why it only shows POST in trace_name, and missing http.route and url.path in attributes.
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/75260884/7e16b360-a2fb-4002-bf2c-6239ddc959d0)
 

Could you please explain the difference between the two and the logic behind their usage? Also, how can I ensure that both attributes appear simultaneously? 
Thanks!

<img width="750" alt="image" src="https://github.com/open-telemetry/opentelemetry-dotnet/assets/75260884/8e8e8974-7fa8-4b85-8422-b41ca436ef67">

**Comment by Kielek** [comment]
@g3david405, I think you should look into https://github.com/open-telemetry/semantic-conventions/blob/v1.26.0/docs/http/http-spans.md as instrumentations from https://github.com/open-telemetry/opentelemetry-dotnet-contrib should follow this specification (without experimental and opt-in attributes).

I assume that your application is working on the server side, so links are leading to server sections. On the same page you can find also related to the  client side:

- [Span naming section](https://github.com/open-telemetry/semantic-conventions/blob/v1.26.0/docs/http/http-spans.md#name), (low cardinality!)
- [lack of http.route](https://github.com/open-telemetry/semantic-conventions/blob/v1.26.0/docs/http/http-spans.md#http-server) - please check table, It is not always available. Details can be found in contrib repository.

Please let me know if it helps you to understand current shape of instrumentation.

**Comment by g3david405** [comment]
@Kielek I found the problem.
If the application use Elastic.Apm.NetCoreAll this package, the trace data will not collect properly.

**Comment by Kielek** [comment]
I recommend to report issue under https://github.com/elastic/apm-agent-dotnet.

Closing this one, please let us know if we help you more.

**Comment by g3david405** [comment]
@Kielek thx~
