### ISSUE TITLE
Support .NET 9 ActivitySource Tags

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#5701]
.NET 9 is adding support for setting static tags on an `ActivitySource`: https://github.com/dotnet/runtime/issues/93795

This issue is for tracking support for sending those as instrumentation scope tags when exported via Otlp, Console, & Zipkin (need to figure out if there is a good spot for them).

**Comment by Kielek** [comment]
@CodeBlanch, whats about other exporters?
It wil lbe great to cover at least Console (and zipkin if possible). Should I create separate issue for this or we can track everything here?

**Comment by CodeBlanch** [comment]
@Kielek I updated the description. But feel free to create individual issues if you want. This was more for just tracking things being added in .NET 9 we need to look at.

**Comment by CodeBlanch** [comment]
We discussed this on the SIG today. Opened #5935 for Console. Some questions about what to do for Zipkin, opened a dedicated issue to track that: #5936
