### ISSUE TITLE
Is it possible to dinamically inject resourceLogs's resource attributes?

### ISSUE THREAD

**Issue by smoms** [open-telemetry/opentelemetry-dotnet#5721]
### What is the question?

Hi,

I would need to understand if possible to dinamically add attributes in the structure below while logs are being generated, i.e. not only at build time:

```
"resourceLogs": [
		{
			"resource": {
				"attributes": [
					{
						"key": "service.name",
						"value": {
							"stringValue": "my name"
						}
					},
					{
						"key": "service.namespace",
						"value": {
							"stringValue": "my namespace"
						}
					},
					{
						**"key": "my custom attributes",
						"value": {
							"stringValue": "xyz"
						}**
					},
```

Maybe extending the _BaseProcessor\<Resource\>_ ?

thanks

**Comment by TimothyMothra** [comment]
Hi @smoms,
No, the resource attribute is immutable and cannot be modified after initializing the sdk.
This is defined in OpenTelemetry's spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md

**Comment by cijothomas** [comment]
Adding this too : https://github.com/open-telemetry/opentelemetry-dotnet/discussions/5691#discussioncomment-9765219
