### ISSUE TITLE
Wrong doc information regarding http.url

### ISSUE THREAD

**Issue by paulomorgado** [open-telemetry/opentelemetry-dotnet#5739]
### Package

OpenTelemetry

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry.Exporter.Console  | 1.9.0   |
| OpenTelemetry.Extensions.Hosting | 1.9.0   |
| OpenTelemetry.Instrumentation.AspNetCore | 1.9.0  |

### Runtime Version

net8.0

### Description

According to https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/getting-started-aspnetcore/README.md, the activity should include the following activity tags:

- net.host.name
- net.host.port
- http.method
- http.scheme
- http.target
- http.url
- http.flavor
- http.user_agent
- http.status_code

However, the activity includes the following tags:

- server.address
- server.port
- http.request.method
- url.schem
- url.path
- network.protocol.version
- user_agent.original
- http.response.status_code

### Steps to Reproduce

Follow example instructions at https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/getting-started-aspnetcore/README.md

### Expected Result

The activity has the **http.url** tag.

### Actual Result

The activity does not have the **http.url** tag.

**Comment by paulomorgado** [comment]
The request activity tags is set [here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/Instrumentation.AspNetCore-1.9.0/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L89) and it doesn't include [`"http.url"`](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/Instrumentation.AspNetCore-1.9.0/src/Shared/SemanticConventions.cs#L31).

**Comment by Kielek** [comment]
@paulomorgado, http semantic convention was changed during the semantic convention stabilization process. The final step is here: https://github.com/open-telemetry/semantic-conventions/pull/377

The latest stable semantic convention version is described here: https://github.com/open-telemetry/semantic-conventions/blob/v1.26.0/docs/http/http-spans.md#http-server-semantic-conventions

I do not see any obvious issues.

Documentation will be updated in #5740
