### ISSUE TITLE
Move SamplerResult to SDK

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#574]
Samplers and associated classes / structs are meant part of the SDK, not the API. SamplerResult is currently in OpenTelemetry.Api/Trace.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#sampling

**Comment by eddynaka** [comment]
@MikeGoldsmith , can I take this issue? If yes, the idea is to move the file OpenTelemetry.API/Trace/SamplingResult.cs to OpenTelemetry/Trace/SamplingResult.cs and the classes that that struct uses? What other classes should i move?
Thanks

**Comment by cijothomas** [comment]
Other classes using `SamplingResult` are already in the SDK itself, so only `SamplingResult` would require movement.

**Comment by eddynaka** [comment]
Ok.

I'll move and open a pr
