### ISSUE TITLE
Milliseconds bucket

### ISSUE THREAD

**Issue by joaoluizalbuquerque** [open-telemetry/opentelemetry-dotnet#5742]
### What is the question?

Hey guys.

Recently I updated OpenTelemetry.Exporter.OpenTelemetryProtocol and OpenTelemetry libraries from 1.7.0 to 1.9.0 and I can no longer see http_server_request_duration_milliseconds_bucket on prometheus, I can only see http_server_request_duration_seconds_bucket. Was it removed? Is there anyway to set it back?

### Additional context

I'm using .Net 7

**Comment by Kielek** [comment]
Never version of semantic convention was implemented. For HTTP, It is now stable, so there should be no breaking changes. See changes https://github.com/open-telemetry/opentelemetry-specification/pull/3390.

Closing this issue. Feel free to reopen if you need more help.
