### ISSUE TITLE
[docs] [metrics] Return the old exemplars sample

### ISSUE THREAD

**Issue by ImoutoChan** [open-telemetry/opentelemetry-dotnet#5747]
### Package

None

### What is the expected behavior?

Right now the sample in `/docs/metrics/exemplars` is unusable, it requires you to install and run locally all dependencies and too verbose.

The old version https://github.com/open-telemetry/opentelemetry-dotnet/tree/b0c95307dd4bb0cab17f07c177773592816ddc09/docs/metrics/exemplars was much better and simpler. It also had sample working otel-collector configuration which is usually used in production envs.

### Which alternative solutions or features have you considered?

If you want to retain this new version, at least return the old one to the separate folder, for example: `/docs/metrics/exemplars-using-docker-compose`. I spent a lot of time trying to find the old tutorial.

**Comment by cijothomas** [comment]
I am closing this, as I believe we now have working docker compose and minimal instructions as well.
