### ISSUE TITLE
Compiling code

### ISSUE THREAD

**Issue by djgrech** [open-telemetry/opentelemetry-dotnet#5757]
### What is the question?

I need a feature, and was going to open a PR, but when I tried to build the project `Examples.AspNetCore` (or any project), the build fails with the below error:

CSC: Error CS1705 : Assembly 'OpenTelemetry.Instrumentation.Http' with identity 'OpenTelemetry.Instrumentation.Http, Version=1.9.0.41, uses 'OpenTelemetry.Api, Version=1.0.0.0 which has a higher version than referenced assembly 'OpenTelemetry.Api' with identity 'OpenTelemetry.Api, Version=0.0.0.0'

CSC: Error CS1705 : Assembly 'OpenTelemetry.Instrumentation.Runtime' with identity 'OpenTelemetry.Instrumentation.Runtime, Version=1.9.0.57 uses 'OpenTelemetry.Api, Version=1.0.0.0 which has a higher version than referenced assembly 'OpenTelemetry.Api' with identity 'OpenTelemetry.Api, Version=0.0.0.0

The master cloned version builds successfully

Both repos are identical, what could be the cause?

Thanks

**Comment by Kielek** [comment]
Could you please describe steps to download the source code?
I suppose that it is outside the Github, and MinVer'sioning is not working correctly.

**Comment by djgrech** [comment]
Basically i cloned the repo: https://github.com/open-telemetry/opentelemetry-dotnet.git, this works
I forked the repo, and cloned the repo and it does not build

Tried it with Visual Studio and Rider, same result

Anything i need to setup on my machine?
Thanks

**Comment by Kielek** [comment]
Please fetch tags from the upstream (forked repository). It should solve the calculation issue with MinVer.

```
git remote add upstream https://github.com/open-telemetry/opentelemetry-dotnet.git
git fetch -p upstream
```

**Comment by djgrech** [comment]
Thanks seems it solved the problem, thanks for your time and help

**Comment by Kielek** [comment]
Looking for your contribution here. If you think that it is worth, feel free to update documentation with contributing to this repository. Closing for now.
