### ISSUE TITLE
Allow Exporter to export a protobuf service request directly

### ISSUE THREAD

**Issue by nduong-ol** [open-telemetry/opentelemetry-dotnet#5763]
### Package

OpenTelemetry.Exporter.OpenTelemetryProtocol

### Is your feature request related to a problem?

Hi, I'm having a use case where I would need to proxy OpenTelemetry service requests through our dotnet server while enriching their metadata. To do so I would be to be able to export directly the protobuf service request that I received from client application exporter. The current Exporter of OpenTelemetry SDK doesn't support this behavior.

Would I develop this feature and make a PR to this repo?

### What is the expected behavior?

OpenTelemetry Exporter can export directly protobuf service requests

### Which alternative solutions or features have you considered?

The alternative would be implement a opentelemetry transmission handler similar to the one implemented by the SDK to export message as grpc or http client

**Comment by martinjt** [comment]
If what you're building is a proxy service to take inbound Protobuf ExportServiceRequest objects amend them, then send them back out, then the otel SDK is not the right place for that.

You're essentially building a gRPC/http proxy, so you should send them using a gRPC service/http client. This is a lot simpler than involving the otel exporters.

Take a look at this example.

https://github.com/martinjt/dotnet-otel-proxy
