### ISSUE TITLE
Log message is not formatted

### ISSUE THREAD

**Issue by mkeymolen** [open-telemetry/opentelemetry-dotnet#5773]
### What is the question?

Hi, i have a small issue with using OTEL to send my logs from a dotnet(8.0) application to ELK . Everything works fine, the traces and the logs are correlated, but the message is not formatted correctly.. however, the attributes are added correctly, it is only the string of the message which is not correctly formatted and still shows the attribute names instead of the values:
Example of the message value: 

[Information] Request starting {Protocol} {Method} {Scheme}://{Host}{PathBase}{Path}{QueryString} - {ContentType} {ContentLength} 

Any ideas?

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/customizing-the-sdk#includeformattedmessage Can you enable this and see if that is what you are looking for?

**Comment by mkeymolen** [comment]
This works! Thanks

**Comment by mkeymolen** [comment]
This works, thanks!
