### ISSUE TITLE
[zipkin\otlp] Call SendAsync on mobile

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#5775]
I worked through this issue with `OneCollectorExporter` over on contrib: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1992

Batch exporter maintains its own background thread. As such we typically call the synchronous `HttpClient.Send` operation (where it is available):

* Zipkin: https://github.com/open-telemetry/opentelemetry-dotnet/blob/32c64d04defb5c92d056fd8817638151168b10da/src/OpenTelemetry.Exporter.Zipkin/ZipkinExporter.cs#L65
* Otlp: https://github.com/open-telemetry/opentelemetry-dotnet/blob/32c64d04defb5c92d056fd8817638151168b10da/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ExportClient/BaseOtlpHttpExportClient.cs#L92

Problem is on "mobile" and browser platforms this leads to a [PlatformNotSupportedException](https://github.com/dotnet/runtime/blob/280f2a0c60ce0378b8db49adc0eecc463d00fe5d/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.AnyMobile.cs#L767).

We should probably apply the same logic added to `OneCollectorExporter` inside our core exporters.

**Comment by lukyamuziB** [comment]
Hey @CodeBlanch I would like to pick this up
