### ISSUE TITLE
Proposal for Stale issue automation

### ISSUE THREAD

**Issue by TimothyMothra** [open-telemetry/opentelemetry-dotnet#5776]
This repo has had automation to close stale PRs for a few years now.
I'm opening this issue to discuss managing issues with the same stale automation.

### What is the expected behavior?

I'm proposing expanding the existing Stale automation to also manage Issues in this repo.

1. Issues older than X days will be marked `Stale`. 

    - Currently 349 open issues (Aug 2024).
    - older than 300 days (Oct 2023) = ~200 issues
    - older than 600 days (Dec 2022) = ~120 issues
    - older than 900 days (Feb 2022) = ~50 issues
    - older than 1000 days (Nov 2021) = ~40 issues
    - older than 1100 days (Aug 2021) = ~25 issues
    - older than 1200 days (Apr 2021) = ~15 issues

    I would work with maintainers to gradually lower this to 300 days. As this is a new process, we want to avoid being too aggressive while we work through the backlog and fine tune the automation.
    First priority is getting through the oldest issues.

2. Exempt specific issues.

    The automation gives us multiple options to control which issues are marked as stale. These are the two that I think are most applicable for this repo:

    - `exempt-all-issues-milestones` Any issue assigned to a milestone would be exempt.
    - `exempt-issue-labels` Any issues assigned to a set of labels would be exempt.
        I'll need some input from maintainers to capture this list. 
        The short list I would start with is; `need-runtime-change,await-spec,help wanted`

4. `Stale` issues with no additional activity will be closed after 7 days.
This is the same policy we use for PRs.

### Additional context

Current Stale automation:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/.github/workflows/stale.yml

Stale workflow api:
https://github.com/actions/stale?tab=readme-ov-file#all-options

**Comment by vishweshbankwar** [comment]
Thanks @TimothyMothra!. This looks good to me. One additional thing I think we need to do is to remove the questions tag from issues, we should direct users to discussion section for that.

**Comment by CodeBlanch** [comment]
I like this! One suggestion. I think it would be a bad look for us to close things as stale which never had a response or anyone looking at them at all. Not sure if it is possible to do that OOB?

One idea to make it work...

* Create a label like `needs-triage`
* Have templates automatically assign that ([bug_report](https://github.com/open-telemetry/opentelemetry-dotnet/blob/32c64d04defb5c92d056fd8817638151168b10da/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L3), [feature_request](https://github.com/open-telemetry/opentelemetry-dotnet/blob/32c64d04defb5c92d056fd8817638151168b10da/.github/ISSUE_TEMPLATE/feature_request.yml?plain=1#L3))
* Exclude anything marked as `needs-triage` from stale job

The idea would be someone would need to at least look at the thing once and remove `needs-triage` before it becomes eligible to become stale.

**Comment by TimothyMothra** [comment]
- There are currently 125 issues without any comments: https://github.com/open-telemetry/opentelemetry-dotnet/issues?q=is%3Aissue+is%3Aopen+comments%3A0
- There are 17 issues without any labels: https://github.com/open-telemetry/opentelemetry-dotnet/issues?q=is%3Aissue+is%3Aopen+no%3Alabel+
- There are 4 issues without any comments AND no labels: https://github.com/open-telemetry/opentelemetry-dotnet/issues?q=is%3Aissue+is%3Aopen+comments%3A0+no%3Alabel


@CodeBlanch, It looks like there are only 4 issues that have never been triaged.
I think your proposal is fair, but I'm reluctant to add extra processes.
Also note that adding a "needs-triage" label today will count as activity and reset the clock on all those issues.


Would it be sufficient to increase the time period that stale issues are closed (2-3 weeks)?
That would give maintainers extra time to triage those issues and possibly respond.

**Comment by vishweshbankwar** [comment]
is it possible to only set the `needs-triage` label for the new ones?

**Comment by TimothyMothra** [comment]
> Ya sorry for the confusion. What I meant was we would edit the templates to add "needs-triage" only on new issues going forward. For everything that already exists we could just implement the stale rules as proposed. Essentially everything out there would go stale. But new stuff we would have this new process where it wouldn't go stale until someone "triages" it at least once.

I'm good with this!
