### ISSUE TITLE
How to send logs to Otel Collector with Content-Type JSON

### ISSUE THREAD

**Issue by smoms** [open-telemetry/opentelemetry-dotnet#5793]
### How to send logs using Content-Type _application/json_ ?

Hi,

I am using OTel dotnet libraries (1.7.0) to export logs to OpenTelemetry Collector Contrib.
All fine but I would like to send logs in JSON instead of protobuf.
I see that all work as expected when the _Content-Type_ is set to _application/x-protobuf_ (default behaviour). Is there a way to sent also as _application/json_? If yes, where is configuration change?

Edit:
Am I correct that the dotnetcore SDK does not support JSON protocol option?

`
 options.AddOtlpExporter(o =>
 {
     o.Protocol = OtlpExportProtocol.HttpProtobuf;
 ........
}
`

thanks.

**Comment by vishweshbankwar** [comment]
@smoms - Your understanding is correct; it is not supported in .NET.

**Comment by cijothomas** [comment]
duplicate https://github.com/open-telemetry/opentelemetry-dotnet/issues/5764
