### ISSUE TITLE
[feature request] Log sampling

### ISSUE THREAD

**Issue by alrz** [open-telemetry/opentelemetry-dotnet#5813]
### Package

OpenTelemetry

### Is your feature request related to a problem?

dotnet is currently exploring adding log sampling at https://github.com/dotnet/extensions/issues/5123 but since sampling mechanism is already present in otel (only for traces afaik) I think it makes sense to have feature parity between the two.

### What is the expected behavior?

I think on the surface this would look like just what we have for traces, ie SetSampler on the logger options.

### Which alternative solutions or features have you considered?

-

**Comment by cijothomas** [comment]
OTel Logs have no concept of sampling. We will add one here, once it is introduced in the OTel spec. I am not aware of any work occurring in OTel spec world to support this.

Users can still write FilteringLogRecordProcessors to achieve the same goals and this is not prohibited by the spec.

`ILogger` can add sampling/advanced-filtering, and that is independent of OTel spec. It'll work for any providers, not just OTel. For example, Iloggers sampling/filtering will work with any providers like the ConsoleLogProvider. 
On the other hand, anything added in OTel will only work for OpenTelemetryProviders, not others like ConsoleLogProviders.

If you elaborate more on "feature parity" part, I can comment on it. I'll close the issue now, as there is no action for this repo. Happy to reopen, if there are things this repo should be doing.
