### ISSUE TITLE
Fix CA2022 - Avoid inexact read with 'System.IO.FileStream.Read(byte[], int, int)

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet#5845]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/5832/files#r1765766226

Updating to .NET 9.0 RC1 introduced this new CA2022 error, and it needs to be fixed.

**Comment by Kielek** [comment]
Adding to 1.10.0 as it is part if upgrading to .NET9.
