### ISSUE TITLE
32bit correctness/support

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet#585]
This issue came via code inspection, not a problem that I encountered directly (I'm not using 32bit).

While the project builds for `AnyCPU` I noticed concurrent access to a 64bit size value type that is treating the read/write as atomic, the calls below can be concurrent and `T` is in practice a `double` or `long`: 
https://github.com/open-telemetry/opentelemetry-dotnet/blob/3f43c5aaf1e65f047599d5be5537db9537c6f6ac/src/OpenTelemetry/Metrics/Aggregators/LastValueAggregator.cs#L40-L43 
https://github.com/open-telemetry/opentelemetry-dotnet/blob/3f43c5aaf1e65f047599d5be5537db9537c6f6ac/src/OpenTelemetry/Metrics/Aggregators/LastValueAggregator.cs#L65-L68

This is a potential problem on 32bit since those reads/writes are not atomic (see [SO answer](https://stackoverflow.com/questions/3676808/is-reading-a-double-not-thread-safe/3677373#3677373) for instance). I'm not sure if this was a deliberate decision, ie.: the project is not intended to be used on 32bit, or simply a (very minor) bug. 

/cc @cijothomas

**Comment by cijothomas** [comment]
Thanks. We can convert them to use `Interlocked`.

**Comment by pjanotti** [comment]
I was going to pick this up but noticed this pending PR #560 - will comment there instead.

**Comment by alexeyzimarev** [comment]
Ok, I'll do that too.

**Comment by cijothomas** [comment]
560 is merged, so we can close this
