### ISSUE TITLE
Application Insights exporter not working with AWS lambdas

### ISSUE THREAD

**Issue by albertocorrales** [open-telemetry/opentelemetry-dotnet#586]
I'm trying to use OpenTelemetry to implement observability in my AWS lambda functions and I'm having a strange behaviour.

I've configured exporters Console and Application Insights. For console exporter, it is working fine, I can see my traces on Amazon CloudWatch perfectly. However, for Applicaiton Insights most of the time I don't see any traces on Azure. 

Having a look at the code, it might be related with the fact that console exporter uses SimpleSpanProcessor, which exports each trace when it ends. On the other hand, Application Insights uses BatchingSpanProcessor, which exports each 5 seconds. 

I guess AWS lambda kills the function process when it finishes and BatchingSpanProcessor wasn't able to call ExportBatchAsync. If that is the issue, potentially this problem might happen with other exporters that use BatchingSpanProcessor.

From local, it is working fine as I'm running it as dotnet core app.

Maybe a solution might be giving the possibility to somehow make a explicit call to ExportBatchAsync from TracerBuilder, so we can save our traces before lambda function kills the process.

**Comment by SergeyKanzhelev** [comment]
Is there any way on AWS lambda to notify SDK when it is about to be unloaded? So `Flush` can be called?

Alternatively, we will need to expose a setting that will make timeouts and batches to be ultra short so telemetry will be sent immediately

**Comment by albertocorrales** [comment]
> Is there any way on AWS lambda to notify SDK when it is about to be unloaded? So `Flush` can be called?
> 
> Alternatively, we will need to expose a setting that will make timeouts and batches to be ultra short so telemetry will be sent immediately

I guess for simple lambdas you will have to call that explicitly to that Flush. If you are working with dotnet core, you could build a filter

For example, I tried to initialise UseApplicationInsights with a custom TelemetryChannel, in particular I used InMemoryChannel (https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.channel.inmemorychannel?view=azure-dotnet), so I could call Flush from a dotnet resource filter after each request. 

However, it didn't work well. Looking at the implementation, I think it is because the pending traces are not in InMemoryChannel yet, they are in BatchingSpanProcessor, pending to be processed. So when I Flush my InMemoryChannel, there is nothing to flush.

That is the reason why I think calling `ExportBatchAsync `might help to send the pending traces.

**Comment by MikeGoldsmith** [comment]
I believe there are some clean-up hooks apps can listen on for the shutdown signal from Lambda. I've use them previously in Node, but not for .NET.

`UseApplicationInsights` does have an overload that lets you configure the SpanProcessorPipeline and you could use the `SimpleSpanProcessor` instead. There is still a chance some spans won't be exported if the process is just killed though.

```csharp
TracerFactory.Create(builder => 
    builder
        .UseApplicationInsights(telemetryConfiguration =>
        {
            telemetryConfiguration.InstrumentationKey = "your instrumentation key";
        },
        spanProcessorPipelineBuilder =>
        {
            spanProcessorPipelineBuilder.AddProcessor(new SimpleSpanProcessor());
        })
```

**Comment by reyang** [comment]
#645
