### ISSUE TITLE
Update documentation for .NET 9 Synchronous Gauge

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet#5868]
NA

**Comment by RichardChukwu** [comment]
Hello @CodeBlanch Please what exactly is to be done here and are you actively working on it?

I'm open to contributing

**Comment by cijothomas** [comment]
@RichardChukwu Please feel free to look at other issues and I am sure you can find many more to help.

**Comment by RichardChukwu** [comment]
Alright, thank you @cijothomas
