### ISSUE TITLE
[bug] Misleading result codes in Application Insights UI

### ISSUE THREAD

**Issue by mikocot** [open-telemetry/opentelemetry-dotnet#5892]
### Package

OpenTelemetry

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry                         | 1.9.0   |

### Runtime Version

net8.0

### Description

Once we've switched from directly sending traces to Application Insights to OTEL collector forwarding traces there we've noticed the loss in usability of the Failure screen in Application Insights.

Originally traces originating from e.g. http requests had result code set to http response codes and therefore App Insights was able to break it down nicely making it easy to identify unusual responses. Now, with otel, all traces have status codes ranging from 0 to 2, with all errors reported as 2. Http status codes are only visible in the logs.

![image](https://github.com/user-attachments/assets/89f87bc9-0f51-468d-bd6f-cb08a7fffd56)

### Steps to Reproduce

Instrument asp / http client, trace failing http requests.

### Expected Result

Application Insights aware of http code responses of failed requests and listing them e.g. in `Top 10 response codes`

### Actual Result

All failing requests (or any other failing traces) grouped under `response code: 2`. Http response status code hidden in Custom Dimensions.

### Additional Context

I understand this is outside the direct scope of this repository and library, but we don't see any way to report it otherwise and it feels like a huge loss for the OTEL+AppInsights pair.

**Comment by cijothomas** [comment]
> I understand this is outside the direct scope of this repository and library, **but we don't see any way to report it otherwise**

Here's some ways to report this to get better attention:

If you are using official Azure Monitor/Application Insights nugets - then report it in this repo: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor
If you are using the OTel Collector AzMonExporter - then report it here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter

Closing as there is no issue with components maintained in this repo.
