### ISSUE TITLE
[bug] System.OutOfMemoryException From OpenTelemetry in Azure Function running with C# code

### ISSUE THREAD

**Issue by agrawalamit31** [open-telemetry/opentelemetry-dotnet#5895]
### Package

OpenTelemetry

### Package Version

| Package Name                                             | Version |
| ---------------------------------------------- | ------- |
| OpenTelemetry.Exporter.Geneva                 | 1.9.0   |
| OpenTelemetry.Audit.Geneva                      | 2.2.5 |

### Runtime Version

net 8.0

### Description

Full Exception :
 System.OutOfMemoryException 
 /Exception of type 'System.OutOfMemoryException' was thrown.
System.Threading.Thread.StartCore()OpenTelemetry.Metrics.PeriodicExportingMetricReader..ctor(BaseExporter`1 exporter,Int32 exportIntervalMilliseconds,Int32 exportTimeoutMilliseconds)
OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.BuildGenevaMetricExporter(GenevaMetricExporterOptions options,Action`1 configure)  
 OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.<>c__DisplayClass2_0.<AddGenevaMetricExporter>b__1(IServiceProvider sp)   
OpenTelemetry.Metrics.MeterProviderBuilderExtensions.<>c__DisplayClass2_0.<AddReader>b__0(IServiceProvider sp,MeterProviderBuilder builder)   
OpenTelemetry.Metrics.OpenTelemetryDependencyInjectionMetricsServiceCollectionExtensions.ConfigureMeterProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider,MeterProviderBuilder meterProviderBuilder)
OpenTelemetry.Metrics.MeterProviderSdk..ctor(IServiceProvider serviceProvider,Boolean ownsServiceProvider)   
OpenTelemetry.Metrics.MeterProviderBuilderBase.Build()
OpenTelemetry.Metrics.MeterProviderBuilderExtensions.Build(MeterProviderBuilder meterProviderBuilder)

**Impact**
Azure function is restarting regularly.
we are getting - An unhandled exception has occurred. Host is shutting down

### Steps to Reproduce

```
 public MetricLogger(string metricAccountName, string metricAccountNamespace, string roleName)
 {
     var defaultDimensions = new Dictionary<string, object>()
           {
              { "cloud.role", roleName }
           };
     this.automationInstrumention = new Meter(roleName);

     this.automationMeterProvider = Sdk.CreateMeterProviderBuilder()
         .AddMeter(roleName)
         .AddView(
             instrumentName: "MyHistogram",
             new ExplicitBucketHistogramConfiguration { Boundaries = new double[] { 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 } })
         .AddGenevaMetricExporter(options =>
         {
             options.PrepopulatedMetricDimensions = defaultDimensions;

             if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
             {
                 options.ConnectionString = $"Account={metricAccountName};Namespace={metricAccountNamespace}";
             }
             else
             {
                 options.ConnectionString = "Endpoint=unix:/var/run/mdsd/default_fluent.socket";
             }
         }).Build();
     this.counterObjectCollection = new ConcurrentDictionary<string, Counter<int>>();
     this.histogramObjectCollection = new ConcurrentDictionary<string, Histogram<long>>();
 }

```

Once we call above constructor of MetricLogger class it throws System.OutOfMemoryException 

### Expected Result

Ideally azure function should run without shut down and no exception should come.

### Actual Result

Full Exception :
 System.OutOfMemoryException 
 /Exception of type 'System.OutOfMemoryException' was thrown.
System.Threading.Thread.StartCore()OpenTelemetry.Metrics.PeriodicExportingMetricReader..ctor(BaseExporter`1 exporter,Int32 exportIntervalMilliseconds,Int32 exportTimeoutMilliseconds)
OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.BuildGenevaMetricExporter(GenevaMetricExporterOptions options,Action`1 configure)  
 OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.<>c__DisplayClass2_0.<AddGenevaMetricExporter>b__1(IServiceProvider sp)   
OpenTelemetry.Metrics.MeterProviderBuilderExtensions.<>c__DisplayClass2_0.<AddReader>b__0(IServiceProvider sp,MeterProviderBuilder builder)   
OpenTelemetry.Metrics.OpenTelemetryDependencyInjectionMetricsServiceCollectionExtensions.ConfigureMeterProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider,MeterProviderBuilder meterProviderBuilder)
OpenTelemetry.Metrics.MeterProviderSdk..ctor(IServiceProvider serviceProvider,Boolean ownsServiceProvider)   
OpenTelemetry.Metrics.MeterProviderBuilderBase.Build()
OpenTelemetry.Metrics.MeterProviderBuilderExtensions.Build(MeterProviderBuilder meterProviderBuilder)

### Additional Context

We checked function memory and CPU usage but no spike.
We are using P3 plan for Azure function with Event Hub Trigger
Avg memory usage was 35 % and Avg CPU usage was 25 % during issue.

**Comment by cijothomas** [comment]
If OutOfMemoryException is throw, I dont think OTel sdk should try to handle it. Simple failing/crashing is reasonable. Are you expecting a different behavior from OpenTelemetry in this case?

The `MetricLogger` you shared looks suspicious. Is that method repeatedly called? `MeterProvider` is expected to be created only once, and not with every metric emission. See https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics#meterprovider-management 
Also, I am not sure of the ConcurrentDictionaries created in that method. OTel examples in this repo should show how to correct manage Instruments. (I am assuming that those dictionaries were meant to cache instruments, but that is not required.)

Closing, as there is no bug in OpenTelemetry to investigate or fix. Feel free to re-open, if you think there is a bug/issue with OpenTelemetry components.

**Comment by agrawalamit31** [comment]
Thanks @cijothomas , 
yes The MetricLogger  method called in each function call. I will do the changes and test it.
