### ISSUE TITLE
[feature request] Remove JaegerPropagator

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet#5898]
### Package

OpenTelemetry.Extensions.Propagators

### Is your feature request related to a problem?

Remove [JaegerPropagator.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Extensions.Propagators/JaegerPropagator.cs) since Jaeger exporter is gone.

### What is the expected behavior?

N/A

### Which alternative solutions or features have you considered?

N/A

**Comment by cijothomas** [comment]
I am not sure I understand the reasoning.. Exporter is gone, but why would that affect the propagator?
Has the spec for jaeger propagator removed?

**Comment by xiang17** [comment]
> I am not sure I understand the reasoning.. Exporter is gone, but why would that affect the propagator? Has the spec for jaeger propagator removed?

I had incorrect understanding of this propagator. Closing this issue.
