### ISSUE TITLE
API: Use TraceId and SpanId from System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#59]
Use ActivityTraceId and ActivitySpanId instead of the library-own definition of TraceId and SpanId. https://github.com/dotnet/corefx/blob/5f9f2e57e668fccbc68e8f9c77852b2befef7712/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L881-L1197

The only complication will be the need to take dependeny on DiagnosticsSource package that will only become stable in September. But it is aligned reasonably well with our schedule

**Comment by austinlparker** [comment]
Seems fine to me, since DiagnosticSource supports NET45+.
