### ISSUE TITLE
Build warnings for Assert.NotNull on KeyValuePair in TracerTests

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#590]
We see build warnings for the test case `Tracer_StartSpanFromActivity_ValidArguments_ReturnsSpanWithActivityAttributesAsSpanTags`.

The warning it not to use `Assert.NotNull` on KeyValuePair<K, V>. Instead we should use `Assert.Single`.

**Comment by eddynaka** [comment]
Hi @MikeGoldsmith , I will open a pr solving this :)

**Comment by eddynaka** [comment]
The only change that i will make, instead of verifying for null, i will check the value of the returned object to be the same as the one that we created. Something like this:
```csharp
Assert.Equal("value1", span.Attributes.FirstOrDefault(k => k.Key == "key1").Value);
Assert.Equal("value2", span.Attributes.FirstOrDefault(k => k.Key == "key2").Value);
```

Assert.Single just work for IEnumerables. So, checking for the value itself would be a better check, right?

**Comment by eddynaka** [comment]
Is it ok to create a PR solving the Message errors as well? I would start with the IDE0009 first. What do you think?
