### ISSUE TITLE
Remove OtlpExporter resource modification code

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#5927]
We have some code in OtlpExporter which will add service name if it isn't found on the resource:

* https://github.com/open-telemetry/opentelemetry-dotnet/blob/9f41eadf03f3dcc5e76c686b61fb39849f046312/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ResourceExtensions.cs#L23-L32

* https://github.com/open-telemetry/opentelemetry-dotnet/blob/9f41eadf03f3dcc5e76c686b61fb39849f046312/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/Serializer/ProtobufOtlpResourceSerializer.cs#L59

Discussed with @alanwest and neither of us feel this should be done. The OtlpExporter should just respect what the SDK resource has.

What needs to be done...

* Remove this logic
* Call it out as a breaking change on CHANGELOG

**Comment by rajkumar-rangaraj** [comment]
@CodeBlanch  / @alanwest  Could you please check if this logic also needs to be removed? There is similar code in the OTLP tag parser to populate `peer.service`. I don't see this as part of the semantic specification.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/9f41eadf03f3dcc5e76c686b61fb39849f046312/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/ActivityExtensions.cs#L338

Test: https://github.com/open-telemetry/opentelemetry-dotnet/blob/9f41eadf03f3dcc5e76c686b61fb39849f046312/test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/OtlpTraceExporterTests.cs#L721

**Comment by alanwest** [comment]
> There is similar code in the OTLP tag parser to populate peer.service.

Agreed that this should also be removed.

In conversation with @rajkumar-rangaraj he also raised the point that these changes are breaking. My opinion is that while these changes are breaking, I'd really just consider them bugs. Bug fixes usually change behavior, so much of the time they're "breaking", but I'd just call them out as bug fixes and not a breaking change.
