### ISSUE TITLE
[feature request] Global metric specific enrichment

### ISSUE THREAD

**Issue by amadeuszl** [open-telemetry/opentelemetry-dotnet#5942]
### Package

OpenTelemetry

### Is your feature request related to a problem?

1. We don't have possibility of adding metric specific enricher
2. Right now we rely on own abstractions (eg. Http/HttpClient middleware) to enhance TagList, although we can't enrich metrics with dynamic values eg. injected with DI that could be applied to all metrics, whatever the source of emission is, that relies only on Meter name or instrument type.

### What is the expected behavior?

Option I
Metric can be emitted by different sources building layer enrichers for all sources may result into many different enricher versions. We look for an option to enable enrichment in a centralized manner.

Example usage: (APIs are just placeholders)
```csharp
Sdk.CreateMeterProviderBuilder()
    .AddMeter("MeterName1")
    .AddMeterEnricher<MyMeterEnricher>("MeterName1");


class MyMeterEnricher : IMetricEnricher 
{
    public void Enrich();
}
```

`MyMeterEnricher.Enrich()` method will run only for `MeterName1` meter. 

Most likely enrichment would happen in MeterListener if we would like to avoid introducing more components to the processing pipeline.

---
Option II
Other option could be giving possibility of implementation of own MeterListeners.

### Which alternative solutions or features have you considered?

1. In all of the Open Telemetry processing pipeline stages TagList is immutable, so we failed to find any place where enrichment could happen, eg. Resorces, Views, Exporters, MeterReader. We assume that TagList should not be changed.
2. MeterListener as interceptor - as OTel relies on MeterListener, we could create own MeterListener that subscribes to metrics emitted by application and that emits enriched metrics that would end up in Open Telemetry MeterListener.
So it looks like that, although it brings latency and it's small performance hit as it introduces one more MeterListener until it gets to Open Telemetry pipeline:
```csharp
// Define the original meter and counter. Emit as always using generated meters
var meter = new Meter("MeterName1");
var counter = meter.CreateCounter<long>("CounterName1");

var initialTags = new TagList
{
    new KeyValuePair<string, object>("key1", "value1")
};
counter.Add(1, initialTags);


// -- //
// Set up OTel to exclude "MeterName1" and "CounterName2". It should listen to "Enriched" metrics only
var meterProvider = Sdk.CreateMeterProviderBuilder()
    .AddMeter("MeterName1Enriched")
    .AddConsoleExporter()
    .Build();

// -- //
// Custom MeterListener to capture and enrich tags before OTel
var listener = new MeterListener();

listener.InstrumentPublished = (instrument, listener) =>
{
    if (instrument.Meter.Name == "MeterName1" && instrument.Name == "CounterName1")
    {
        listener.EnableMeasurementEvents(instrument);
    }
};

listener.SetMeasurementEventCallback<long>((instrument, measurement, tags, state) =>
{
    var enrichedMeter = new Meter("MeterName1Enriched");
    var enrichedCounter = enrichedMeter.CreateCounter<long>("CounterName1Enriched");

    var enrichedTags = new TagList(tags);
    enrichedTags.Add("additionalTag", "additionalValue");
    enrichedCounter.Add(measurement, enrichedTags);
});

listener.Start();
```

### Additional context

We build library that's abstraction layer between application and Open Telemetry.

**Comment by alanwest** [comment]
Hey @amadeuszl, I complete agree that OpenTelemetry has a gap in that it provides no means to enrich metrics. However, because this would require a change to the SDK, this ask needs to be driven through the [specification repo](https://github.com/open-telemetry/opentelemetry-specification/issues). Depending on how the spec shakes out determines what language SDKs need to implement.

I'm going to close this issue as there is no immediate action we can take at this time. You may want to follow up with this similar proposal: https://github.com/open-telemetry/opentelemetry-specification/issues/1116.
