### ISSUE TITLE
[feature request] Please add example for how it should be used inside of a "Unity" environment  (https://unity.com/)

### ISSUE THREAD

**Issue by asafMasa** [open-telemetry/opentelemetry-dotnet#5964]
### Package

None

### Is your feature request related to a problem?

I need to add logs to my game and Open Telemetry seemed to be the way

### What is the expected behavior?

Easy integration with the default Unity logs system
* Will keep original API while formatting the output to Opentelemtry format
* Multiple appenders such as rolling file and HTTP appenders

### Which alternative solutions or features have you considered?

Adding log4net and customizing it's output

**Comment by martinjt** [comment]
I think this is beyond the scope of what we'll be supporting as part of OpenTelemetry. Unity does support Activity, but theres different threading models to consider and the startup behaviour etc.

OpenTelemetry is the output mechanism, you should use Microsoft.Extensions.Logging in your code, and connect OpenTelemetry to output that. Then you'd send the data using OTLP, not to a file, these are called Exporters.

**Comment by asafMasa** [comment]
@martinjt thanks for your reply, can you please add a request to create a "getting started in 5 minutes - Unity guide" with the solution you described?
it will be beneficial and will give me some reference on how the openTelemetry package should be used inside unity

**Comment by martinjt** [comment]
@asafMasa to be clear, that's not something that we'd be considering doing as we don't actively support Unity. It should work, but it's something where you'll be working through issues yourself. I'd love to see a blogpost if you get it working though, but I can't see this being in the official documentation.
