### ISSUE TITLE
span.End throwing NullReferenceException using StartSpanFromActivity

### ISSUE THREAD

**Issue by longility** [open-telemetry/opentelemetry-dotnet#597]
I followed this: https://github.com/open-telemetry/opentelemetry-dotnet#auto-collector-implementation-for-activitydiagnosticsource

This is my current configuration:
```csharp
services.AddOpenTelemetry(builder =>
            {
                builder
                .SetSampler(new OpenTelemetry.Trace.Samplers.AlwaysOnSampler())
                .UseJaeger(o =>
                {

                    o.ServiceName = serviceName;
                    o.AgentHost = jaegerAgentHost;
                    o.AgentPort = 6831;
                })
                .SetResource(Resources.CreateServiceResource(serviceName))
                .AddRequestCollector()
                .AddDependencyCollector();
            });
```

I'm running this inside a hosted service and the error is at `span.End()` with a `NullReferenceException`:
```csharp
var tracerFactory = scopedProvider.GetRequiredService<TracerFactory>();
var activity = new Activity("operation");
activity.SetParentId(traceParent);
var tracer = tracerFactory.GetTracer("access-control-api");
try
{
    var span = tracer.StartSpanFromActivity($"Handle {nameof(AddHouseholdRole)}", activity);
    // ..stuff
}
finally
{
    var span = tracer.CurrentSpan;

    span.End(); // NullReferenceException with no other details
    if (span is IDisposable disposableSpan)
    {
        disposableSpan.Dispose();
    }
}
```

I'm not sure how to debug further to provide more information to help narrow down issue. Hopefully, what is shared is sufficient.

**Comment by cijothomas** [comment]
@longility The nullref is being fixed in #622 

But the real issue you are facing is different.
`StartSpanFromActivity` - starts your span, but doesn't make it active. When you later retrieve the `CurrentSpan`, you are not getting the span you created, but the original active span (which happened to be invalid in this case)

Most likely, you'd want to use `StartActiveSpanFromActivity` to start the span and make it active one in one go.

**Comment by longility** [comment]
Thanks for the guidance @cijothomas . That got me passed the exception. I don't see the trace, but that is a separate problem for me to investigate later.

I'm trying to understand, the use cases or the differences:
1. Is there meaning to _start_ a span in contrast to creating a span?  Intuitively, when we _start_ a span, I think something would be going. Is there something happening when _starting_ a span?
2. Whats the difference between _starting_ a span that is not active, and _starting_ a span and making it active? I would think that _starting_ in a sense is "alive" or "active".

**Comment by cijothomas** [comment]
> Thanks for the guidance @cijothomas . That got me passed the exception. I don't see the trace, but that is a separate problem for me to investigate later.
> 
> I'm trying to understand, the use cases or the differences:
> 
> 1. Is there meaning to _start_ a span in contrast to creating a span?  Intuitively, when we _start_ a span, I think something would be going. Is there something happening when _starting_ a span?
> 2. Whats the difference between _starting_ a span that is not active, and _starting_ a span and making it active? I would think that _starting_ in a sense is "alive" or "active".

The tracing spec is clear about Creating the span should not make it active. (https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#span-creation)

But I also have same question as you have - whats the deal with starting a span, vs starting a active span. I plan to get answers from experts and modify readme docs accordingly.

**Comment by cijothomas** [comment]
StartSpanFromActivity(string operationName, Activity activity, SpanKind kind, IEnumerable<Link> links);

The above ignores activity if its not in w3c format or if its not started. Can you also ensure you call activity.Start(). ? 
This sure is confusing and will try to get clarity around this - but to unblock your experiments, you can try with started activity.

**Comment by longility** [comment]
@cijothomas starting the activity did the trick! Thanks! I'm still new to all of this.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/469
https://github.com/open-telemetry/opentelemetry-specification/issues/238

@longility the above are good pointers to read about "starting a span" and "making span active" being separate things.
In dotnet, the most common one would be - start and activate span in one go, not separate.

**Comment by longility** [comment]
Solution that is working for documentation:
```csharp
var tracerFactory = scopedProvider.GetRequiredService<TracerFactory>();
var activity = new Activity("operation");
activity.SetParentId(traceParent);
activity.Start();
var tracer = tracerFactory.GetTracer("access-control-api");
try
{
    var span = tracer.StartSpanFromActivity($"Handle {nameof(AddHouseholdRole)}", activity);
    // ..stuff
}
finally
{
    var span = tracer.CurrentSpan;

    span.End(); // NullReferenceException with no other details
    if (span is IDisposable disposableSpan)
    {
        disposableSpan.Dispose();
    }
    activity.Stop();
}
```
I don't like the activity + span combo, but minor.
