### ISSUE TITLE
 I cannot directly create the .cs files  as this requires local file generation using protoc

### ISSUE THREAD

**Issue by AnkitThoi** [open-telemetry/opentelemetry-dotnet#5978]
### Package

OpenTelemetry

### Is your feature request related to a problem?

 I cannot directly create the .cs files  as this requires local file generation using protoc as i tried to do i am not able to find protoc.exe and seems i am doing lot of mistakes while running this command which will generate the .cs files which i have to use.
 protoc --csharp_out=C:\OutputDirectory --proto_path=C:\PathToOpenTelemetryProto --proto_path=C:\PathToProtobufCore C:\PathToOpenTelemetryProto\*.proto

is it possible to keep these .cs files which can be ready to use

### What is the expected behavior?

is it possible to keep  .cs files which can be ready to use

/my-protos
    ├── opentelemetry-proto/collector/trace/v1/trace_service.proto
    ├── opentelemetry-proto/collector/metrics/v1/metrics_service.proto
    ├── opentelemetry-proto/common/v1/common.proto
    ├── opentelemetry-proto/resource/v1/resource.proto
    └── google/protobuf/timestamp.proto

### Which alternative solutions or features have you considered?

we can have folders where we can keep these files and it will be easy to download

**Comment by martinjt** [comment]
We have talked about making models available, but ultimately that's extra maintenance we don't want to take on.

The proto files are from here: https://github.com/open-telemetry/opentelemetry-proto and therefore if you'd looking to build something that works with the protobuf schema directly, so you compile them yourself from there.

If we did provide something on the OpenTelemetry .NET side, it would, at most, likely only by the models for the data, not the services.
