### ISSUE TITLE
[bug] Duplicated Attribute Values in Metrics

### ISSUE THREAD

**Issue by Coelho04** [open-telemetry/opentelemetry-dotnet#5979]
### Package

OpenTelemetry

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry                     | 1.9.0   |
| OpenTelemetry.Exporter.Console                         | 1.9.0   |
| OpenTelemetry.Exporter.OpenTelemetryProtocol                                   | 1.9.0     |
| OpenTelemetry.Extensions.Hosting                                   | 1.9.0     |
| OpenTelemetry.Extensions.Propagators                                   | 1.9.0     |
| OpenTelemetry.Instrumentation.AspNetCore                                   | 1.9.0     |
| OpenTelemetry.Instrumentation.Http                                   | 1.9.0     |
| OpenTelemetry.Instrumentation.Process                                   | 0.5.0-beta.6     |
| OpenTelemetry.Instrumentation.Runtime                                   | 1.9.0     |

### Runtime Version

net8.0

### Description

We are seeing the http_client_request_duration_(sum,count,bucket) attributes with multiple values for instance:  
`http_client_request_duration_count{environment="prd", error_type="400;400", http_request_method="POST;POST", http_response_status_code="400;400", instance="instance_x", job="application_x",  network_protocol_version="1.1;1.1", server_address="web_api1;web_api1", url_scheme="https;https"}`  

We have several applications with the same configurations regarding OpenTelemetry, but for some reason, only a few have this problem, and we can't understand why.   

The applications receive high throughput around 100k rpm.

Only this metric seems to be affected.

We believe that the issue might be when in a custom HttpHandler we perform another call to another API to get an authorization token but we have yet to validate this.

Can someone take a look at this?

### Steps to Reproduce

We don't have the certainty that this can reproduce the issue but might help investigate the issue.

- Create an application that needs to connect to some API
- Create and handler that will fetch a token or make another call to the same or other API.
- After receiving the call from that the other API let the handler continue with the other request.

### Expected Result

`http_client_request_duration_count{environment="prd", error_type="400", http_request_method="POST", http_response_status_code="400", instance="instance_x", job="application_x",  network_protocol_version="1.1", server_address="web_api1", url_scheme="https"}` 

### Actual Result

`http_client_request_duration_count{environment="prd", error_type="400;400", http_request_method="POST;POST", http_response_status_code="400;400", instance="instance_x", job="application_x",  network_protocol_version="1.1;1.1", server_address="web_api1;web_api1", url_scheme="https;https"}`

**Comment by cijothomas** [comment]
What is the .NET version used? In newer ones, the metrics are produced by the httpclient library itself, but in older ones the instrumentation library in OTel does that. Once we know who is adding duplicate tags, we can decide next steps on the fix.

**Comment by Coelho04** [comment]
Hi @cijothomas it seems that the problem is on the dotnet runtime, an issue already exists https://github.com/dotnet/runtime/issues/108284.

I believe we can close this issue.

**Comment by Kielek** [comment]
Closing. See previous comment.
