### ISSUE TITLE
[bug] Percentiles not being reported on metrics

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [open-telemetry/opentelemetry-dotnet#6017]
### Package

OpenTelemetry

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry.Api                     | 1.8.0   |
| OpenTelemetry                         | 1.8.0   |
| TBD                                   | TBD     |

### Runtime Version

net9.0

### Description

Metrics such as response times are being reported without percentiles, with only max, min and sum.  
sample:
```
Metric Name: myMetric.send.duration, Description: Duration of sending., Unit: ms
(2024-12-10T19:12:48.7490577Z, 2024-12-10T19:18:48.7465950Z] Histogram
Value: Sum: 158095,26879999993 Count: 1041 Min: 134,2115 Max: 2155,8156
(-Infinity,0]:0
(0,5]:0
(5,10]:0
(10,25]:0
(25,50]:0
(50,75]:0
(75,100]:0
(100,250]:1026
(250,500]:13
(500,750]:1
(750,1000]:0
(1000,2500]:1
(2500,5000]:0
(5000,7500]:0
(7500,10000]:0
(10000,+Infinity]:0
```

### Steps to Reproduce

1. Create .Net 9 app
2. Add OpenTelemetry pack
3. Push metrics using the .Net SDK (`System.Diagnostics.Metrics` + `Meter.CreateHistogram<double>`)
4. wait for the 1 min reporting period

### Expected Result

Metric Name, Min, Max, Sum, Std Dev, and p50/75/95/99/99.9

### Actual Result

Metric Name, Min, Max, Sum

**Comment by cijothomas** [comment]
> Std Dev, and p50/75/95/99/99.9

Percentiles are never supported at OTel SDK side as this will make it not mergeable. Instead they calculate buckets, and pass it over to backends, which can use the bucket information to calculate percentiles.

Not sure which backend are you using, but Prometheus is a well known backend that can do percentiles from OTel histograms!

Some OTel hosted blogs on the topic.
https://opentelemetry.io/blog/2023/why-histograms/
https://opentelemetry.io/blog/2023/histograms-vs-summaries/

**Comment by Leonardo-Ferreira** [comment]
can I configure the buckets @cijothomas? 
like, I know for a fact that I will never take less than 100ms to reply, so those buckets will always be empty, and I have a hard timeout at 5 sec, whereas I would like buckets like `(100,125]`,`(125,150]`,`(150,175]` to give me a better precision on those ranges where most of my response times are

**Comment by cijothomas** [comment]
Yes. https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk#explicit-bucket-histogram-aggregation
