### ISSUE TITLE
Move all span "stores" logic to the SDK out of API

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#61]
Types like `ISampledSpanStoreSummary`, needs to be moved out of API. For now - at least to move them to SDK. Later we may decide to move them to the specific packages like zPages or alike

**Comment by SergeyKanzhelev** [comment]
@trwegner can you please start working on this?

**Comment by trwegner** [comment]
@SergeyKanzhelev I'll start on this today.

**Comment by SergeyKanzhelev** [comment]
i think this is done
