### ISSUE TITLE
StartSpanFromActivity is confusing as OperationName can be specified in two ways.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#619]
The following API to create Span from Activity is confusing as it takes an explicit `operationName` and `activity` also has operation name. Current SDK implementation uses the `operationName` and ignores the one from Activity.
`public abstract TelemetrySpan StartSpanFromActivity(string operationName, Activity activity, SpanKind kind, IEnumerable<Link> links);`

Would it be better to change this API to NOT take `operationName` parameter., and rely on Activity alone? 
OR advertise the priority order. Take `operationName` only if `Activity` is ununsable (being null, non-w3c, not started)

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Api/Trace/Tracer.cs#L80

**Comment by longility** [comment]
Is there a use case where the relationship of Activity to Span is 1 to many respectively? If so, then I think advertise the priority order is necessary.

If we don't know then I think I might lean towards going with Activity operation name alone to keep it simple until there is a need.

**Comment by cijothomas** [comment]
We'll be replacing Span with Activity completely in near term once the new System.Diag.DiagnosticSource package is shipped. (https://github.com/dotnet/designs/pull/98/files)

At which point, this confusion shouldn't arise as Span and Activity will be the same.

**Comment by cijothomas** [comment]
With new Activity changes, this API simply dont exist. Closing.
