### ISSUE TITLE
API review: IList sometimes is used in API surface where IEnumerable will suffice

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#62]
See original issue: https://github.com/census-instrumentation/opencensus-csharp/issues/64

Reviewing API surface - IList is used when IEnumerable will suffice. For instance in Exporter handler and other places. IList allows manipulating elements - add, remove, etc. when this is absolutely not the intent.

**Comment by austinlparker** [comment]
This appears to have been closed by #151
