### ISSUE TITLE
How to connect StackExchangeRedisCallsCollector to ConnectionMultiplexer via DI?

### ISSUE THREAD

**Issue by AlexeiScherbakov** [open-telemetry/opentelemetry-dotnet#624]
Currently when creating StackExchangeRedisCallsCollector ConnectionMultiplexer must be initialized.
How I can get connect it to StackExchangeRedisCallsCollector via IServiceProvider/DI?

**Comment by cijothomas** [comment]
There are no extension methods in RedisCollector, so the collector is configured manually as shown in this example.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/samples/Exporters/Console/TestRedis.cs#L42

(Sorry if this is not what you were looking for. I dont have any knowledge of Redis client.)

**Comment by AlexeiScherbakov** [comment]
Yes, I saw this sample. In this sample we need to create ConnectionMultiplexer **before** creating StackExchangeRedisCallsCollector. And it comes from other scope, not from DI.

**Comment by SergeyKanzhelev** [comment]
Related: https://github.com/StackExchange/StackExchange.Redis/issues/1044

**Comment by SergeyKanzhelev** [comment]
I'm open for suggestions on what would be the best way to initialize Redis connections with the configured profiler

**Comment by AlexeiScherbakov** [comment]
We wrap ConnectionMultiplexer inside our own object, which provide cache interfaces and make ConnectionMultiplexer recreation, something like "No connection is avaliable" happens (This is a group of linked issues. One of the latests - https://github.com/StackExchange/StackExchange.Redis/issues/1387). On hi-load StackExchange.Redis is unstable, when Redis cluster has some kind of 'physical' problems. I write code which 'pings' Redis cluster with simple LUA-script which increments counter per service instance. This approach give us chance to distinguish Redis physical problems, because script execution gives more specific error than "No connection is avaliable" - for example "READONLY You can't write against a read-only replica". When error is detected It retry 10 times in 1s intervals and recreate ConnectionMultiplexer.

So I only need to know:
1. How to get StackExchangeRedisCallsCollector instance via IServiceProvider
2. How to filter 'ping' LUA-scripts executions from OpenTelemetry

Now I made ugly workaround for storing StackExchangeRedisCallsCollector between DI Startup steps
```
    internal sealed class RedisProfiler
    {
        private StackExchangeRedisCallsCollector _collector;
        public RedisProfiler()
        {
        }

        public void AddCollector(StackExchangeRedisCallsCollector collector)
        {
            _collector = collector;
        }

        public StackExchangeRedisCallsCollector Collector
        {
            get { return _collector; }
        }
    }

    public static class TelemetryRedisExtension
    {
        public static void AddRedisTelemetry(this IServiceCollection services)
        {
            var profilerService = new RedisProfiler();
            services.AddOpenTelemetry(builder =>
            {
                builder.AddCollector(x =>
                {
                    var ret = new StackExchangeRedisCallsCollector(x);
                    profilerService.AddCollector(ret);
                    return ret;
                }
                );
            });
            services.AddSingleton<RedisProfiler>(profilerService);
        }


        public static void UseRedisTelemetry(this IApplicationBuilder app)
        {
            var redisService = app.ApplicationServices.GetRequiredService<IRedisConnectionService>();
            var redisProfiler = app.ApplicationServices.GetRequiredService<RedisProfiler>();
            redisService.RegisterProfiler(redisProfiler.Collector.GetProfilerSessionsFactory());
        }
    }
```

**Comment by martinjt** [comment]
This can now be achieved with 

```csharp

builder.Services.ConfigureOpenTelemetryTracerProvider((serviceProvider, tracerProviderBuilder) =>
{
    var serviceName = serviceProvider.GetRequiredService<MyService>();
    tracerProviderBuilder.AddInstrumentation(...);
});
```

Where you can specifically grab the IConnectionMultiplexer and add the instrumentation.
