### ISSUE TITLE
Proposal: introduce a nuget meta package

### ISSUE THREAD

**Issue by longility** [open-telemetry/opentelemetry-dotnet#625]
> One thought I have had in this area...
>
> There's a lot of packages under the OT umbrella. To get up and running in an aspnetcore project most people are probably going to need OpenTelemetry.Collector.AspNetCore, OpenTelemetry.Collector.Dependencies, OpenTelemetry.Hosting, and then their exporter of choice.
>
> It might be nice to have a meta package that combines OpenTelemetry.Collector.AspNetCore, OpenTelemetry.Collector.Dependencies, & OpenTelemetry.Hosting into something like OpenTelemetry.AspNetCore? Basically so you only have to consume 2: the meta & your exporter. I think it would help resolve the naming weirdness because people wouldn't need to care, just grab the meta package and off you go.
>
> How's that for controversy :)

_Originally posted by @CodeBlanch in https://github.com/open-telemetry/opentelemetry-dotnet/pull/623#issuecomment-617895745_

I'm trying to gather additional buy-in, opinions and thoughts. I believe @cijothomas and @CodeBlanch are on board with this current proposal:

# Motivation
There is a common set of nuget packages (`OpenTelemetry.Adapter.AspNetCore`, `OpenTelemetry.Adapter.Dependencies`, and `OpenTelemetry.Hosting`) that are needed for a common way of consuming (for an AspNetCore project). We are currently burdening the user who is building an AspNetCore project to need to know the different packages.

# Proposal
A nuget meta-package `OpenTelemetry.AspNetCore` with the following nuget packages as dependencies:
- `OpenTelemetry.Adapter.AspNetCore`
- `OpenTelemetry.Adapter.Dependencies`
- `OpenTelemetry.Hosting`

Exporters continue to stay separate as it is not common.

**Comment by cijothomas** [comment]
Adding to the list:

OpenTelemetry.AspNet with the following nuget packages as dependencies:
OpenTelemetry.Adapter.AspNet.Win
OpenTelemetry.Adapter.Dependencies

OpenTelemetry.Worker (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#worker-service-template) with the following nuget packages as dependencies:
OpenTelemetry.Adapter.Dependencies
OpenTelemetry.Hosting

**Comment by martinjt** [comment]
Since we're revamped the APIs and packages here, I don't think this is something we're going to be working on any time in the near future. There are various Meta packages available from vendors.

This could be a future goal once everything is stable though.
