### ISSUE TITLE
Libraries referring OT.API gets NoOpTracer only even if SDK is installed.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#630]
Libraries who wish to emit OT traces are expected to depend on the OT.API only. They would do the following to get `Tracer` instance to start/stop spans.
`var tracer = TracerFactoryBase.Default.GetTracer("LibName");`

If this library is used in an application which do not install OT SDK, then the above code will return a "no-op" `Tracer`, and there will be near zero perf impact as no traces/spans will be generated.

If the library is used in an application which uses OT SDK, then the expectation is that "someone" will replace the "no-op" `Tracer` with the actual one, and spans will be generated and sent to processors/exporters.

Currently no SDK code is automatically replacing this no-op Tracer, hence, libraries continue to get "no-op" `Tracer`, and their spans will not be generated.

Proposals:

1. Users can manually call `TracerFactoryBase.SetDefault(tracerFactory)` with the `TracerFactory`, in their application. 

2. SDK can automatically do this. Need to design the best place in SDK to do this.
One potential option is to do this in `TelemetryFactoryHostedService`
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Hosting/Implementation/TelemetryFactoryHostedService.cs#L39

```
var tracerFactory = this.serviceProvider.GetRequiredService<TracerFactoryBase>();
TracerFactoryBase.SetDefault(tracerFactory);
```

This only works for projects using .Hosting package.

(Opening an issue for awareness. The actual fix is to be designed/discussed)

**Comment by CodeBlanch** [comment]
@longility I just noticed you mention this issue on gitter. Basically I ran into this the other day working on #620. To resolve I updated the factory to set the default instance. Sharing here for consideration.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/a391a48f0ab01e085843b78c5a0b6efa544bc6de/src/OpenTelemetry/Trace/Configuration/TracerFactory.cs#L107-L110

**Comment by cijothomas** [comment]
> @longility I just noticed you mention this issue on gitter. Basically I ran into this the other day working on #620. To resolve I updated the factory to set the default instance. Sharing here for consideration.
> 
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/a391a48f0ab01e085843b78c5a0b6efa544bc6de/src/OpenTelemetry/Trace/Configuration/TracerFactory.cs#L107-L110

Thanks. I also thought of modifying `TracerFactory.Create` to `SetDefault`. But if user creates multiple `TracerFactory` (with different processing pipelines, exporter - a valid OT scenario), then we cannot decide which one is the default. User has to tell which factory should be default.

**Comment by CodeBlanch** [comment]
My thinking with the `useAsDefaultFactory` ctor parameter was that for the common case where the user only has one pipeline we'll just use the first factory spun up as the default. If they are building more than one pipeline, which is the more advanced case, they'll have to use the param. It's not great ::shrug::

**Comment by longility** [comment]
Assuming #641 is good, I can think of two options that could solve this issue:

**1. `TracerProvider` has the new default instead of `TracerFactory`**
```csharp
public abstract class TracerProvider
    {
        private static ProxyTracer proxy = new ProxyTracer(new NoOpTracer());

        protected TracerProvider()
        {
            // any instantiation of `TracerProvider` would set the default
            if (!(this is ProxyTracerProvider)) // not pretty...but will avoid ProxyTracerProvider to be set again
            {
                Default = this;
                proxy.UpdateTracer(this.GetTracer(null));
            }
        }
        public static TracerProvider Default { get; private set; } = new ProxyTracerProvider(proxy);
        public abstract Tracer GetTracer(string name, string version = null);
    }
```
**2. `TracerProvider` sets the new default to `TracerFactory`**
```csharp
public abstract class TracerProvider
    {
        protected TracerProvider()
        {
            // any instantiation of `TracerProvider` would set the default
            if (!(this is ProxyTracerProvider)) // not pretty...but will avoid ProxyTracerProvider to be set again
            {
                TracerFactory.SetDefault(this);
            }
        }
        public abstract Tracer GetTracer(string name, string version = null);
    }
```

**Comment by cijothomas** [comment]
This issue no longer exist in the new model. CLosing.
