### ISSUE TITLE
Reusing Adaptors for Traces and Metrics.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#632]
**Background**:
We have several Adapters (called Collectors earlier) which emits OT spans corresponding to http outbound/inbound calls, sqlclient calls, azure sdk calls etc. All these adapters require a `Tracer` instance so as to start/stop spans. The adapters currently receive `Tracer` by virtue of `AddAdapter` method in `TracerBuilder`.  In other words, adapters knows about, and depends on OT SDK concept of `TracerBuilder`. Ideally adapters should just depend on OT API, and not OT SDK.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Configuration/TracerBuilder.cs#L93

The `TracerFactory` construction takes the responsibility of providing `Tracer` to all the registered adapters.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Configuration/TracerFactory.cs#L102

**Issue**:
We want to re-use the same adapter for emitting OT metrics as well. i.e we don't want to add another adapter for emitting OT Metrics from httpclient, when there is already an adapter listening to `DiagnosticSource` calls backs, and emitting OT Spans.

In order to achieve this, the adapters must have a `Meter` instance as well along with `Tracer` instance. Currently the adapter creation is tied to `TracerFactory`, and hence there is no easy to construct an adapter using both `Tracer` and `Meter`.

**Proposals**:
1. Don't re-use adapters. Have separate Adapters for OT Spans and OT Metrics. This may be inefficient in terms of performance.

2. We need someone to provide adapters with both `Meter` and `Tracer`. (In future we may have `Logger` as well) Currently adapters knows too much about the `TracerBuilder` (and it will need to know about `MeterBuilder` too). Modify adapters to depend only on OT API.
This means adapters would simply accept `TracerFactory` and `MeterFactory` and create tracer and meter from the factory themselves. This solution may be easier to integrate with existing OT.Ext.Hosting, as we can simply register `TracerFactory` (and soon `MeterFactory`) in DI, and let adapters get it from DI.

This issue requires design/discussion. I haven't researched fully all the different ways to solve this. Opening an issue here to get feedback early and for awareness.

Related #630

**Comment by longility** [comment]
> Ideally adapters should just depend on OT API, and not OT SDK.

**Comment by cijothomas** [comment]
> > Ideally adapters should just depend on OT API, and not OT SDK.
> 
> Does this apply to exporters as well? Meaning, should exporters ideally depend on OT API?

The concept of SpanProcessor, SpanExporter is part of SDK, so naturally Exporters need SDK.

(Below is purely my interpretation or my mental model)
Adapters are needed because libraries didn't emit spans in the way we expect. So adapters simply convert the telemetry emitted by libraries, into OT API format. 
If libraries are using OT API, and emitting OT Spans, then there would be no need of adapters.

For example, the SQLClient adapter takes the `DiagnosticSource` callbacks, and converts them into OT Spans. If SQLClient was already emitting OT spans, then we wouldn't have needed adapter.

Because of this, Adapters are just enhancing the job done by libraries - and just like libraries it should not need to know anything about SDK. All it needs is the API to emit spans.

**Comment by czs1993** [comment]
when will the “Reusing Adaptors for Traces and Metrics” be works ？

**Comment by cijothomas** [comment]
There is no ETA on this, but this item most likely will become irrelevant once Span->Activity work is complete.

**Comment by czs1993** [comment]
@cijothomas  thanks, the beta version need how  long  time will be work?

**Comment by cijothomas** [comment]
If you can tell me what specific part you want to try, I can try to give a better estimate.

Trace part is very likely ready in 2 weeks or less. But instrumentationadapter for HttpClient, AspNetCore etc may take more as we are likely going to ask more fixes from .NET platform.

Noone is actively working on metrics now, as the goal is to focus on tracing.

**Comment by czs1993** [comment]
@cijothomas  thanks, In  the current project, I used OpenTelemetry version 0.2.0-alpha.100 SDK to Collect Metrics and Tracing. there have many problems,So I want to upgrade the sdk(version 0.2.0-alpha.100) to beta version. when the beta version is completed.

**Comment by czs1993** [comment]
@cijothomas The beta version is worked, Whether it has the feature of reusing adaptors for traces and metrics?

**Comment by cijothomas** [comment]
Closing as this is not relevant now. There is a WIP PR for metrics, and the PR is leaning towards separate subscription and separate instrumentation for trace and metric.
