### ISSUE TITLE
Remove ApplicationInsights exporter from this repo

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#645]
Following https://github.com/open-telemetry/opentelemetry-specification/pull/277#discussion_r330265935, we need to move vendor specific exporters away from this repo.
Need to make sure the exporter is registered under https://opentelemetry.io/registry/?s=net.

This needs to go somewhere else: https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Exporter.ApplicationInsights.

The end result would be having only these exporters in the repo:
* Console
* Jaeger
* Noop
* OpenTelemetryProtocol
* Prometheus
* Zipkin

**Comment by reyang** [comment]
@cijothomas

**Comment by SergeyKanzhelev** [comment]
There is an issue https://github.com/open-telemetry/opentelemetry-dotnet/issues/138. I think this will be a single action of branching code out as a backup and remove all exporters from the master. I don't think we need to track those tasks separately unless you want to move specific exporters proactively.

In any case, I was delaying with this to make sure we concentrate an effort on running to a beta release.

**Comment by yhvicey** [comment]
When will there be the repo for AI exporters available? Looks like the latest version of AI exporter package is `179`, which is far behind current opentelemetry api package version `286`.

**Comment by SergeyKanzhelev** [comment]
CC: @cijothomas and @reyang 

@yhvicey one alternative for you is to run a collector with Azure Monitor exporter. It has a few flaws though
