### ISSUE TITLE
Remove Lightstep/Stackdriver exporter from this repo

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#646]
Following https://github.com/open-telemetry/opentelemetry-specification/pull/277#discussion_r330265935, we need to move vendor specific exporters away from this repo.
Need to make sure the exporter is registered under https://opentelemetry.io/registry/?s=net.

This needs to go somewhere else: https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Exporter.LightStep.

The end result would be having only these exporters in the repo:
* Console
* Jaeger
* Noop
* OpenTelemetryProtocol
* Prometheus
* Zipkin

**Comment by bruno-garcia** [comment]
We've discussed this on Gitter and the following proposal arrived:

1. Create a repo: https://github.com/open-telemetry/opentelemetry-dotnet-contrib which @MikeGoldsmith is raising an issue for.
2. Move all vendor-specific exporters to it.
3. Depend on `OpenTelemetry` packages via NuGet dependency.

**Comment by MikeGoldsmith** [comment]
PR to move StackDriver to contrib project: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/3
