### ISSUE TITLE
Remove Stackdriver exporter from this repo

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#647]
Following https://github.com/open-telemetry/opentelemetry-specification/pull/277#discussion_r330265935, we need to move vendor specific exporters away from this repo.
Need to make sure the exporter is registered under https://opentelemetry.io/registry/?s=net.

This needs to go somewhere else: https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Exporter.Stackdriver.

The end result would be having only these exporters in the repo:
* Console
* Jaeger
* Noop
* OpenTelemetryProtocol
* Prometheus
* Zipkin

**Comment by MikeGoldsmith** [comment]
Requested contrib project for any exporters that are not reassigned to owning organisations: https://github.com/open-telemetry/community/issues/340

We can also push other non-core code here. Utilities, helpers, etc.

**Comment by reyang** [comment]
#646
