### ISSUE TITLE
Expose "dropped counts" for span attributes, events, and links

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet#650]
**Is your feature request related to a problem?**
Spans have limited capacity for attributes, events, and links these when any of these are dropped due to capacity being exceeded it is necessary to provide some visibility to this information.

**Describe the solution you'd like.**
OTel Java and Go and offer ways to track the number of dropped items for attributes, events, and links. .NET should have the same to give visibility to these types of data drops.

**Describe alternatives you've considered.**
Dropped information without some accountability makes harder for users to understand why certain parts of the data are not available.

**Comment by cijothomas** [comment]
Would logging to EventSource be sufficient here?

**Comment by cijothomas** [comment]
The .NET Actiivty API does not enforce these limits. So no work item here .
If there is a spec which limits thee, we need to enforce it in the API shim. Closing this until then.
