### ISSUE TITLE
Add support to arrays of primitive types for Span Attributes

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet#651]
Per [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/e0bd41739a92304c0be5d68840f434e281b5f8b2/specification/trace/api.md#set-attributes) span attributes should support array of primitive types.

**Comment by cijothomas** [comment]
Will make this to API Shim as part of upgrading to preview 8 of Activity.
