### ISSUE TITLE
Allow the description of Span Status to be set.

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet#653]
Currently, there is no way to set the description of a span status.

**Comment by eddynaka** [comment]
@pjanotti , what are your suggestions to solve this? Are we talking about the `struct Status` from `OpenTelemetry.Api`?

**Comment by cijothomas** [comment]
Closing this as we currently have Status.Ok.WithDescription("my description").
(Also Status is likely move out of API spec)
