### ISSUE TITLE
OpenTelemetry.Exporter.Console 0.2.0-alpha.179 missing

### ISSUE THREAD

**Issue by mmisztal1980** [open-telemetry/opentelemetry-dotnet#661]
It would appear that `OpenTelemetry.Exporter.Console` 0.2.0-alpha.179 was not released along with the remaining packages.

Was this intentional?

**Comment by MikeGoldsmith** [comment]
Hi @mmisztal1980 

You are correct the console package has not been released to nuget.org yet. It was added after the last nuget publish, ~3 months ago. We're currently working on our package organisation and publishing strategies. Not publishing to nuget.org for so long is not good.

The package is available on our MyGet feed, and you can add a reference to it like this:

```bash
dotnet add package OpenTelemetry.Exporter.Console -v '0.2.0-*' -s https://www.myget.org/F/opentelemetry/api/v3/index.json
```

Please re-open the issue if you have any further queries.
