### ISSUE TITLE
New naming convention for packages affecting older packages

### ISSUE THREAD

**Issue by xontab** [open-telemetry/opentelemetry-dotnet#670]
The NuGet packages have been changed and the old packages were also renamed in MyGet. Although I agree with the new naming convention and I understand that this project is still not stable, I still believe that the old packages should still be available using the old convention for backwards compatibility. Only the new ones should use the new naming convention.  This is causing the following errors during build time for projects that use the older packages.

```
Unable to find package OpenTelemetry.* with version (>= 0.2.0-alpha.*)
```

**Comment by MikeGoldsmith** [comment]
Hi @xontab - yes, I don't believe old packages have been removed. Can you elaborate more on your setup? eg what package(s) with what references?

As we've moved some packages to owning organisations (eg LightStep, StackDriver) / contrib, we had to update the project reference to a package reference. However, as the most recent release of the API / SDK on nuget.org is from 3 months ago, we set the package version to 0.2.0-*, which is only available from the MyGet feed.

More information on what exactly you're trying to do would be useful. eg if you want to add the StackDriver exporter to your application, you'd need to do something like this:

```bash
dotnet add package OpenTelemetry.Exporter.StackDriver -v '0.2.0-*' -s https://www.myget.org/F/opentelemetry/api/v3/index.json
```

**Comment by xontab** [comment]
Just to give an example, all the following packages are no longer available due to the naming refactoring.

```
    <PackageReference Include="OpenTelemetry.Collector.AspNetCore" Version="0.2.0-alpha.246" />
    <PackageReference Include="OpenTelemetry.Collector.Dependencies" Version="0.2.0-alpha.246" />
```

Only the new packages `OpenTelemetry.Adapter.AspNetCore` from `0.2.0-alpha.254` onwards are available on MyGet.  On the other hand, packages that were not renamed, such as `OpenTelemetry.Api` are still available (starting from `0.2.0-alpha.215` onwards)

**Comment by cijothomas** [comment]
The package are indeed removed per : https://github.com/open-telemetry/opentelemetry-dotnet/issues/664#issuecomment-624896961

**Comment by cijothomas** [comment]
Myget feed automatically removes older package due to size limitations. Though we try to avoid it, its still possible to have packages renamed and gone from myget.
