### ISSUE TITLE
Record stats in HttpClient listener

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#68]
Copy from https://github.com/census-instrumentation/opencensus-csharp/issues/141

see how it's done in [Java](https://github.com/census-instrumentation/opencensus-java/blob/master/contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java#L155) and [specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/HTTP.md)

**Comment by cijothomas** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry-dotnet/issues/1269
