### ISSUE TITLE
How to expose PrometheusExporterMetricsHttpServer to other container?

### ISSUE THREAD

**Issue by guitarrapc** [open-telemetry/opentelemetry-dotnet#690]
**Describe your environment.** Describe any aspect of your environment relevant to the question:

* docker/kubernetes

**What are you trying to achieve?**
What did you expect to see?

Expose endpoint for Prometheus server to collect metrics from PrometheusExporterMetricsHttpServer.

Current PrometheusExporterMetricsHttpServer implementation is collecting endpoint url from exporter. Therefore it expected to be **localhost** and won't be `http://+:9181` to expose HttpListener.

> https://github.com/open-telemetry/opentelemetry-dotnet/blob/30f841b2eff8e47a3e680a7afbea3ab528faa5d2/src/OpenTelemetry.Exporter.Prometheus/PrometheusExporterMetricsHttpServer.cs#L46

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

PrometheusExporterMetricsHttpServer seems expected to be running on local machine and prometheus server also in same machine.

Seems like I should make my own PrometheusExporterMetricsHttpServer to accept my listener endpoint. [PrometheusMetricBuilder](https://github.com/open-telemetry/opentelemetry-dotnet/blob/30f841b2eff8e47a3e680a7afbea3ab528faa5d2/src/OpenTelemetry.Exporter.Prometheus/Implementation/PrometheusMetricBuilder.cs) is internal, so blocking to refer ContentType though.

**Comment by guitarrapc** [comment]
workaround and usecase sample on docker-compose. (kubernetes is similar to this.)
> https://github.com/guitarrapc/dotnet-lab/tree/master/opentelemetry

**Comment by SergeyKanzhelev** [comment]
I'm not sure what's the question here. Can you please elaborate?

One option to simplify set up is to use the middleware implemented in this PR: https://github.com/open-telemetry/opentelemetry-dotnet/issues/65
