### ISSUE TITLE
BatchingProcessor should export when max size is reached

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet#704]
Both [`BatchingSpanProcessor`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Export/BatchingSpanProcessor.cs#L77) and [`BatchingActivityProcessor`](https://github.com/open-telemetry/opentelemetry-dotnet/pull/697/files#diff-75dfb0dfff9526c2f665dfb296b28b6dR78) just return when trying to add a span / activity and the queued items are equal or greater than the configured max queue size.

A configuration option could be considered to trigger an export when the queue max is reached instead only relying on interval flushing.

Raised by @pjanotti in #697.

**Comment by cijothomas** [comment]
This was already fixed.
