### ISSUE TITLE
Add Fluent / Builder Interface to TelemetrySpan

### ISSUE THREAD

**Issue by Aaronontheweb** [open-telemetry/opentelemetry-dotnet#705]
When I'm creating `TelemetrySpan` instances inside our library it's common for us to see code like:

```csharp
var faultSpan = Tracer.StartSpan(ActorCrashOperationName, ActiveSpan, SpanKind.Internal);
                faultSpan.AddEvent(ex.Message);
                faultSpan.AddEvent(ex.StackTrace);
                faultSpan.End();
```

I would love to have a fluent "builder" interface for doing this:

```csharp
Tracer.StartSpan(ActorCrashOperationName, ActiveSpan, SpanKind.Internal)
.AddEvent(ex.Message)
.AddEvent(ex.StackTrace)
.SetAttribute("actorPath", Self.Path.ToString());
```

**Comment by MikeGoldsmith** [comment]
Thanks for the suggestion @Aaronontheweb. I think it a good idea and something we had in OpenTracing. We can review this once we've completed our spike on whether the new Activity implementation can be used.

**Comment by Aaronontheweb** [comment]
Makes sense - was also contemplating opening an issue on making `TelemetrySpan` / `Activity` implement `IDisposable` too - that way I could use scoping and `using` statements succinctly inside our applications. Another idea from the original OpenTracing `IScope` implementation that may be worth replicating.

**Comment by MikeGoldsmith** [comment]
We've run into scoping issues with activity / telemetryspan when doing some unit tests and I believe @CodeBlanch added IDisposeable to the object returned during setup. 

You're very welcome to create a PR to add it, I'd appreciate it if you could do it for both so we don't lose it during the current work.

**Comment by CodeBlanch** [comment]
@MikeGoldsmith This is different than the IDisposable thing I did. That is on the global scope, this is per-span. The ask is to change the `TelemetrySpan` class to:
```csharp
    public abstract class TelemetrySpan : IDisposable
    {
        public abstract SpanContext Context { get; }
        public abstract bool IsRecording { get; }
        public abstract Status Status { set; }
        public abstract TelemetrySpan UpdateName(string name);
        public abstract TelemetrySpan SetAttribute(string key, object value);
        public abstract TelemetrySpan SetAttribute(string key, long value);
        public abstract TelemetrySpan SetAttribute(string key, bool value);
        public abstract TelemetrySpan SetAttribute(string key, double value);
        public abstract TelemetrySpan AddEvent(string name);
        public abstract TelemetrySpan AddEvent(Event newEvent);
        public abstract void End();
        public abstract void End(DateTimeOffset endTimestamp);
    }
```

* Added IDisposable, which will call Stop. `SpanSdk` is already built that way.
* Added `TelemetrySpan` return type on most methods. That's the fluent/chaining part. Would require a bit of refactoring, but easy to do.

I think it's a great change.

If we're going to carry through with removing `TelemetrySpan`/`SpanSdk` in favor of `ActivitySource`/`Activity`, it already uses this pattern so we don't have to do anything.

**Comment by Aaronontheweb** [comment]
That looks right on to me.

**Comment by MikeGoldsmith** [comment]
Thanks for the clarification @CodeBlanch. Yes, I agree the above proposal looks good.

Even if the Activity/ActivitySource migration happens, the shim would also benefit from this change.

**Comment by CodeBlanch** [comment]
This will be part of the beta. Thanks for the suggestion @Aaronontheweb!
