### ISSUE TITLE
Consistent namespace use for Zipkin, Jaeger, and otlp TracerBuilderExtensions

### ISSUE THREAD

**Issue by janaka** [open-telemetry/opentelemetry-dotnet#712]
**Is your feature request related to a problem?**
The Zipkin and Jaeger TracerBuilderExtensions are in one namespace but the otlp TracerBuilderExtensions is in a different namespace. This is confusing and not intuitive. Is it intentional? method names are similarly inconsistent. 

`namespace OpenTelemetry.Exporter.OpenTelemetryProtocol`
[OpenTelemetry.Exporter.OpenTelemetryProtocol/TracerBuilderExtensions.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/296e0ff3a74ce86541af799410e230927ed63d05/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/TracerBuilderExtensions.cs#L21)

`namespace OpenTelemetry.Trace.Configuration`
[OpenTelemetry.Exporter.Zipkin/TracerBuilderExtensions.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/30f841b2eff8e47a3e680a7afbea3ab528faa5d2/src/OpenTelemetry.Exporter.Zipkin/TracerBuilderExtensions.cs#L21)

`namespace OpenTelemetry.Trace.Configuration`
[OpenTelemetry.Exporter.Jaeger/TracerBuilderExtensions.cs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/30f841b2eff8e47a3e680a7afbea3ab528faa5d2/src/OpenTelemetry.Exporter.Jaeger/TracerBuilderExtensions.cs#L21_)

**Describe the solution you'd like.**
The otlp TracerBuilderExtensions is in `namespace OpenTelemetry.Trace.Configuration`

`UseOpenTelemetryProtocol` or `UseOtlp` rather than`UseOpenTelemetryProtocolExporter`

**Comment by eddynaka** [comment]
With the PR https://github.com/open-telemetry/opentelemetry-dotnet/pull/794, we solved this.
@cijothomas , i think we can close this issue as well.

**Comment by cijothomas** [comment]
> With the PR #794, we solved this.
> @cijothomas , i think we can close this issue as well.

Not yet. The namespaces are not fixed to be consistent.
