### ISSUE TITLE
Consistent exporter configuration between Zipkin and otlp

### ISSUE THREAD

**Issue by janaka** [open-telemetry/opentelemetry-dotnet#713]
**Is your feature request related to a problem?**
Otlp `ExporterOptions` doesn't have a `ServiceName` property like the Zipkin and Jaeger ones. Without this property the OTel collector "panics" and crashes.

One needs to add `.SetResource(Resources.CreateServiceResource("hello-world-api"))`

Otel
```c-sharp
            services.AddOpenTelemetry((sp, builder) =>
            {
                builder
                    .SetResource(Resources.CreateServiceResource("hello-world-api"))
                    .UseOpenTelemetryProtocolExporter (options =>
                    {
                        options.Credentials = ChannelCredentials.Insecure;
                        options.Endpoint = otlpEndpoint;
                    })
                    .AddRequestAdapter()
                    .AddDependencyAdapter(); 
            });
```

Zipkin
```c-sharp
            services.AddOpenTelemetry((sp, builder) =>
            {
                builder
                    //.SetSampler(Samplers.AlwaysSample)
                    
                    .UseZipkin(options =>
                    {
                        options.ServiceName = "hello-world-api";
                        options.Endpoint = new Uri(otlpEndpoint);
                    })
                    .AddRequestAdapter()
                    .AddDependencyAdapter(); 
            });
```

**Describe the solution you'd like.**
Be able to set the service name as an exporter option so the code looks like the following

```c-sharp
            services.AddOpenTelemetry((sp, builder) =>
            {
                builder
                    .UseOpenTelemetryProtocolExporter (options =>
                    {
                        options.Credentials = ChannelCredentials.Insecure;
                        options.Endpoint = otlpEndpoint;
                        options.ServiceName = "hello-world-api"
                    })
                    .AddRequestAdapter()
                    .AddDependencyAdapter(); 
            });
```

**Describe alternatives you've considered.**
Which alternative solutions or features have you considered?

**Additional context.**
I filed #712 earlier which is another example of inconsistency in this area of the code. It seems to be a general issue.

**Comment by janaka** [comment]
Yeah, IMO inconsistency is the problem. I was considering submitting a PR but it then seemed like it was really about broader design hence better for somebody with more context. Thanks.

**Comment by eddynaka** [comment]
@pjanotti , should we rename from `UseOpenTelemetryProtocolExporter` to `UseOpenTelemetryProtocol` or something like that?
