### ISSUE TITLE
Tracing multiple applications

### ISSUE THREAD

**Issue by francisminu** [open-telemetry/opentelemetry-dotnet#729]
Hi,

I am trying to implement Tracing using OpenTelemetry. I am relatively new to OpenTelemetry and have been trying to figure out the same since a week. I am able to get it working in my Hosted service on its own. I am able to see the traces in Jaeger. Our use case is as follows:
1. We have an API which then has a hosted service started from it.
2. We need to trace the request starting from API all the way until the hosted service. 

Could someone let me know if there is any way to create the hosted service spans as the child of span created in API?

**Comment by cijothomas** [comment]
I am not sure if I understood the question correctly, so here's my interpretation:
You have an asp.net core application which has a web component (reacting to http requests) and then there is a hostedservice as well. And you are trying to correlate telemetry from the hostedservice with the one from webcomponent.

Is my understanding of your question correct?

If yes, could you tell how is the communication between web and hosted service? Do you use some queue mechanism?

**Comment by francisminu** [comment]
Hi Cijo,

Yes, what you have explained correctly. We have rabbitmq as the middle piece. The API will be publishing the messages to a queue and the hosted service subscribes to the same queue. In this case, how do I get the hosted service to act as a child of the span that was created for the message (just before publish). I am looking for a functionality similar to the one OpenTracing provides where we can extract the details from the header (for api's).
Please let me know if this clarifies my question or if you need any more information.

Thanks!

**Comment by cijothomas** [comment]
RabbitMQ is not supported out-of-the-box.
You'll need to manually propagate context (from Activity) into the messages and later extract it at the receiving end, and start activity based off it.

**Comment by francisminu** [comment]
The extract part is the one I am struggling with. Do you have some sample on how this can be done?

**Comment by cijothomas** [comment]
**High level:**

For injection: `Activity.Current.Context` would have the TraceId, SpanID, etc.  Put this into the RabbitMQMessage.

Extraction & Restore:
Retrieve the context from the RabbitMQ message.
Then start a new activity with parentid = the one extracted from rabbitmq message.

I'll see if there are examples doing this.

**Comment by francisminu** [comment]
Thanks Cijo. I will take a look at this approach. @cijothomas

**Comment by cijothomas** [comment]
Closing as no further action needed. Please reopen or open new issue, if there are followups.
