### ISSUE TITLE
Default Listening model for ActivitySource

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#736]
The current SDK behavior is to listen to only those ActivitySources which are explicitly configured by the user.

https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Configuration/OpenTelemetrySdk.cs#L89

Adding a ActivitySource is done using builder.AddActivitySource()
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry/Trace/Configuration/OpenTelemetryBuilder.cs#L74

Opening this issue here to gather feedback on this approach. Alternate approach is to listen to *every* ActivitySource in the process, except those explicitly disabled. This may be too much noise, but can be controlled by selectively disabling.

(We can also explore if we want to do filtering similar to Ilogger (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-filtering).  Something like "collect all activities from sources starting with "System.Data.Sql" etc.)

The immediate goal is to seek opinion on the current model - nothing is listened by default. Users must add ActivitySources they are interested in.

**Comment by CodeBlanch** [comment]
I like the idea of using filtering akin to ILogger. A simple `Filter<string, bool>` callback we invoke during `ShouldListenTo` would probably go a long way too; easy to pass when building up the SDK, and users can make it config-driven if they want.

**Comment by cijothomas** [comment]
Added this as required-for-ga. This is a critical portion of OTel enablement experience, so need to ensure this is correctly handled before GA.

**Comment by cijothomas** [comment]
The general consensus from several SIG meeting was that, its best to opt-in to each ActivitySources of interest, rather than subscribing to all by default. This will be made clear in the instrumentation doc as well.
Additionally, the AddSource() api supports wildcard (*) now, so it must be easy to subscribe to multiple source. For eg: AddSource("CompanyName.Product.*") will listen to all ActivitySources starting with "CompanyName.Product."

**Comment by christopher-taormina-zocdoc** [comment]
@cijothomas sorry to comment on this issue, but does the AddSource() call support wildcards? I tried adding a source as "Zocdoc." but that didn't seem to capture a source of "Zocdoc.Http".

**Comment by cijothomas** [comment]
"Zocdoc.*" should cover it

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry#activity-source

**Comment by christopher-taormina-zocdoc** [comment]
Oh sorry I missed the example entirely. Thanks for the help!
