### ISSUE TITLE
Allow to implement specific component listeners leveraging ListenerHandler

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#74]
From: https://github.com/census-instrumentation/opencensus-csharp/issues/129

When someone wants to implement a new listener for the component we don't support out of the box, they should be able to leverage DiagnosticListener subscription, and perhaps property fetching.

The first step could be making OpenCensus.Collector.Dependencies.Common.ListenerHandler public.

One scenario for this feature: I'm implementing DiagnosticSource instrumentation for my component and want to test out how it will work with OpenCensus.

**Comment by lmolkova** [comment]
ListenerHandler is public and it is possible to implement extra listeners on top of it
