### ISSUE TITLE
Strong-name signing

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#746]
The current assemblies seem to be signed use a debug/test cert.
1. Do we need strong-name signing? (I think yes but would like to get perspectives from others).
2. What should be the signing certificate? (e.g. creating an OpenTelemetry one?)

**Comment by SergeyKanzhelev** [comment]
many enterprises and lib authors sign their assemblies and .NET forbid non-signed references from the signed assembly. We are signing with publicly available cert. This seems to be the common practice for many OSS libraries. Creating a private key will likely require to create a process to grant this key to vendors to build hotfixes to simplify customer support and critical security bug fixes (which must be released non-publicly).

**Comment by SergeyKanzhelev** [comment]
Please re-open if this is an issue and we need more discussion.
