### ISSUE TITLE
Closing spans in diagnostic listeners

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#75]
Hi,

I'm recently implementing OpenCensus in the CMS-type application our company is developing. Beside using listeners for incoming and outgoing HTTP connections, provided in OpenCensus.Collector.AspNetCore and OpenCensus.Collector.Dependencies packages, I've reused the same pattern for DiagnosticSources our code is instrumented with.

I have some doubts with regards to my understanding of the way in which collectors/listeners plug into span hierarchy.  In these two files:

https://github.com/census-instrumentation/opencensus-csharp/blob/develop/src/OpenCensus.Collector.AspNetCore/Implementation/HttpInListener.cs
https://githhub.com/census-instrumentation/opencensus-csharp/blob/develop/src/OpenCensus.Collector.Dependencies/Implementation/HttpHandlerDiagnosticListener.cs

`OnStopActivity` handler closes active span by calling its `End` method. This however does not change `Tracer.CurrentSpan`, and therefore next started span becomes a child span of the closed one, instead of a following. Current span is correctly reset when `IScope` instance produced by `SpanBuilder.StartScopedSpan` is disposed (which I did in my own listener, adding an async local stack of scopes).

Is here some thought I don't understand or mechanism I don't see? I can understand that for incoming HTTP requests  resetting `Tracer.CurrentSpan` may be not important, because they are top level in a (local) trace, but for outgoing connections correct setting of `CurrentSpan` seems to me important.

Cheers,
Jacek

**Comment by SergeyKanzhelev** [comment]
Moved from https://github.com/census-instrumentation/opencensus-csharp/issues/126

**Comment by lmolkova** [comment]
Closing in favor of #163 and discussion in it
