### ISSUE TITLE
GitHub Actions vs Azure Pipeline

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/opentelemetry-dotnet#750]
Today, we are using Azure Pipeline to build/test/publish everything.

Since we are including more and more frameworks, the tests will start to take more and more time.

My proposal is to change to GitHub Actions and use the parallel job that they offer:
Steps:
1. restore -> build -> archive
2. tests (download archive)
2.a) test.net452
2.b) test.netcoreappxx
...

with that, we could achieve a better performance and tests in parallel.

Below some docs:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds

**Comment by Brandon-Kimberly** [comment]
There is a [related proposal](https://github.com/open-telemetry/community/issues/398) on the community repository to switch all CI/CD pipelines to GitHub Actions. Feel free to reach out to me, @alolita , or @trask (who is the mentor for this proposal) if you'd like.

**Comment by cijothomas** [comment]
My #1 reason of switching from Azure pipeline to GH Action is the ability for anyone to see the CI logs right inside Github without navigating to another website (azure devops). Its already captured in the proposal @Brandon-Kimberly shared!

@eddynaka I think all the perf boosts we get via GH Actions (via parallelization) can be achieved in Azure pipeline as well. But anyways, for this and all other reasons mentioned in the related proposal, I vote to move to GH Actions.

**Comment by eddynaka** [comment]
@Brandon-Kimberly / @alolita / @trask , don't know if u know, but i didn't find a reliable code-coverage report to be published. Do u have a guidance for that? Besides that, i have already created a PR. Let me know what do you think about that strategy as well! Thank you!
