### ISSUE TITLE
OpenTelemetry + Jaeger span overlapping

### ISSUE THREAD

**Issue by yallie** [open-telemetry/opentelemetry-dotnet#756]
I'm observing strange behavior when my telemetry spans overlap, 
so that a parent span is closed earlier than its child span, like this:

```txt
parent |---------|
child      |--------|
```

When this happens, parent-child relationships between spans are broken.
Also, spans don't seem to be properly aligned to the time axis.

**Environment**

* SDK version: 0.2.0-alpha.275 (built from master)
* .NET runtime version: 4.62 
* Platform and OS version: Windows 10
* Jaeger version: v1.18.0 (commit 0fe3e758e61852b753682197f40e2eb05b526811)

**Steps to reproduce.**

My code performs database operations, like `ExecuteNonQuery` and `ExecuteReader`.
`ExecuteReader` runs a query, creates a `DataReader` that reads the data.
DataReader opens its span when created and closes the span when disposed,
so that it captures all data fetching:

```c#
static void DatabaseDemo()
{
	ExecuteNonQuery("init_session");
	ExecuteNonQuery("create_temp_table");

    // execute reader   |---|
    // datareader read     |-----------|
	using (var reader = ExecuteReader("select * from temp_table"))
	{
		while (reader.Read())
			WriteLine(reader["Name"]);
	}

	ExecuteNonQuery("load_data");
	ExecuteNonQuery("calculate_report");

	using (var reader = ExecuteReader("select * from report"))
	{
		while (reader.Read())
			WriteLine(reader["Name"]);
	}
}
```

**What is the expected behavior?**

I'm expecting to see something like this in Jaeger:

![image](https://user-images.githubusercontent.com/672878/86188559-b01d3e00-bb47-11ea-8b02-11018fc4a6b9.png)

**What is the actual behavior?**

![image](https://user-images.githubusercontent.com/672878/86188803-74cf3f00-bb48-11ea-9be4-a7b7b92d3851.png)

**Additional context.**

Full source code of the demo: https://gist.github.com/yallie/a59ad0a7a59ca4a395260369b0142c22

**Comment by cijothomas** [comment]
Closing inactive old issues. Please re-open if this is an issue in the latest package versions.
