### ISSUE TITLE
Revise dispose pattern in SpanProcessor/ActivityProcessor

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet#769]
`Dispose` pattern in `SimpleSpanProcessor`, `SimpleActivityProcessor`, `BatchingSpanProcessor` and `BatchingActivityProcessor` needs to be revised. As @reyang mentioned `ShutdownAsync` is not thread safe, race condition could happen for this.stopping, and it would re-enter to re-execute the same code. 

Raised as a part of PR: https://github.com/open-telemetry/opentelemetry-dotnet/pull/755#discussion_r448119691

**Comment by eddynaka** [comment]
@reyang , for this, do you think a simple lock in a variable in the dispose method would work? Or do you have something else in your mind?

**Comment by reyang** [comment]
Yes, a simple lock should solve the problem.
