### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/opentelemetry-dotnet#778]
After we merged the PR https://github.com/open-telemetry/opentelemetry-dotnet/pull/768, we started to face some issues for the users who tried to build using VS2019.

The issue is related to a tag that we added to solve the MinVer Version:
```xml
<Target Name="AssemblyVersionTarget" AfterTargets="MinVer">
    <PropertyGroup>
      <RevisionNumber>$(MinVerVersion.Split(`.`)[3])</RevisionNumber>
      <AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).$(RevisionNumber)</AssemblyVersion>      
    </PropertyGroup>
  </Target>
```

**Comment by CodeBlanch** [comment]
Are we sure this is fixed? I'm trying to run the benchmarks, so I have to build in release. When I do, the block above generates an error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4184	The expression ""System.String[]".GetValue(3)" cannot be evaluated. Index was outside the bounds of the array.	OpenTelemetry.Exporter.Jaeger	C:\...\opentelemetry\build\Common.prod.props	27	
```

I did some debugging. With `MinVer` you can see the output of the variables if you add...
```xml
  <PropertyGroup>
    <MinVerVerbosity>detailed</MinVerVerbosity>
  </PropertyGroup>
```
Which gives me this...
```
3>MinVer: Calculated version 0.2.0-alpha.368.
3>MinVer: [output] MinVerVersion=0.2.0-alpha.368
3>MinVer: [output] MinVerMajor=0
3>MinVer: [output] MinVerMinor=2
3>MinVer: [output] MinVerPatch=0
3>MinVer: [output] MinVerPreRelease=alpha.368
3>MinVer: [output] MinVerBuildMetadata=
3>MinVer: [output] AssemblyVersion=0.0.0.0
3>MinVer: [output] FileVersion=0.2.0.0
3>MinVer: [output] PackageVersion=0.2.0-alpha.368
3>MinVer: [output] Version=0.2.0-alpha.368
```
Everything looks fine. So I suspect the issue is with our syntax and not `MinVer`? Maybe the target order?

**Comment by eddynaka** [comment]
@CodeBlanch , The problem is: the version is invalid with the `-alpha` string. It's why I added the substring and create the version manually. So, what I did to test if the props worked:
`dotnet build --configuration Release`

Right now, i saw that doing inside VS, it's showing the error, as if the values didn't exist and isn't respecting the order of things. Let me try some stuff.

**Comment by eddynaka** [comment]
@CodeBlanch , can you try this:

```xml
  <Target Name="AssemblyVersionTarget" AfterTargets="MinVer" Condition="'$(Configuration)'=='Release'">
    <PropertyGroup Condition="'$(MinVerVersion)'!=''">
      <RevisionNumber>$(MinVerVersion.Split(`.`)[3])</RevisionNumber>
      <AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).$(RevisionNumber)</AssemblyVersion>      
    </PropertyGroup>
  </Target>
```

**Comment by CodeBlanch** [comment]
@eddynaka Thanks. I tested it, seems to work fine (in that the version stuff is skipped). FYI you can combine the conditions into one statement like this:

```xml
  <Target Name="AssemblyVersionTarget" AfterTargets="MinVer" Condition="'$(Configuration)'=='Release' and '$(MinVerVersion)'!=''">
    <PropertyGroup>
      <RevisionNumber>$(MinVerVersion.Split(`.`)[3])</RevisionNumber>
      <AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).$(RevisionNumber)</AssemblyVersion>
    </PropertyGroup>
  </Target>
```
