### ISSUE TITLE
Support for distributed tracing when calls are made over message systems like NServiceBus, Rabbit MQ etc

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#78]
from: @jacostro

I have a problem with a queuing scenario:
* web application queues a request for offline processing (trace A),
* pub/sub subscriber picks up a request and processes it (trace B).

These processes take place at different time and processing part (B) is usually longer. Both have separate traces, but top level span of trace B has a link (`LinkType.ParentLinkedSpan`) to originating span in trace A. I can see the link in Stackdriver. But it is not obvious how to find trace B from trace A view. So I would also like to have `LinkType.ChildLinkedSpan`-type link in trace A. For this purpose I need trace context of trace B, which does not exist yet. I can pre-generate and queue it, but API doesn't seem to contain functionality to start trace from specified context (trace and span ids). Closest to that is `ITracer.SpanBuilderWithRemoteParent` which at least will produce a trace with a given id.

What I miss for this scenario is something like:
```csharp
ITracer.SpanBuilderWithExplicitContext(string spanName, ISpanContext spanContext);
```

**Comment by iron9light** [comment]
Support [CloudEvents](https://github.com/cloudevents/sdk-csharp)

**Comment by cijothomas** [comment]
I believe this is an issue copied from Census world and may not be relevant anymore in this repo.
Closing this for now. If this is still relevant, please feel free to reopen.
