### ISSUE TITLE
OpenTracing.Api requires private dependency 

### ISSUE THREAD

**Issue by kirillta** [open-telemetry/opentelemetry-dotnet#784]
All available OpenTracing.Api packages require a private dependency on `System.Diagnostics.DiagnosticSource 5.0.0-preview.7.20308.13` but the last public version is `5.0.0-preview.6.20305.6`.
Older versions are removed from MyGet and in result I can't build my projects. 
Could you give me any advice about that situation?

**Comment by cijothomas** [comment]
Can you add the following nuget source as well?
<add key="Dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />

@MikeGoldsmith can you help with publishing that version from myget before updating to diagnosticsource preview7, to nuget.org?

**Comment by cijothomas** [comment]
> Can you add the following nuget source as well?
> @MikeGoldsmith can you help with publishing that version from myget before updating to diagnosticsource preview7, to nuget.org?

**Comment by kirillta** [comment]
Yes, that helped, thanks
