### ISSUE TITLE
Updated to latest OpenTelemetry and ASP.NET Core requests are no longer recorded

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet#785]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 0.2.0-alpha.352 (from myget)
* .NET runtime version .NET Core 3.1
* Platform and OS version: Windows 10

**Steps to reproduce.**
1. Clone https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/update-opentelemetry-grpc-instrumentation
2. Run Aggregator server sample (instructions https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/update-opentelemetry-grpc-instrumentation/examples#aggregator) with parameter to enable OpenTelemetry
3. Run Aggregator client

For reference, this is what the Startup.cs configuration looked like after I had updated it to use the latest methods: https://github.com/JamesNK/grpc-dotnet/blob/0eb2b9376cde637ff0d058befebdb16bf8052885/examples/Aggregator/Server/Startup.cs#L51-L57

**What is the expected behavior?**
I expected to see incoming HTTP request telemetry to ASP.NET Core logged to Zipkin. This worked before I updated to a newer version of OpenTelemetry.

**What is the actual behavior?**
Only gRPC and HttpClient telemetry is logged

![image](https://user-images.githubusercontent.com/303201/86904551-fdf7fe80-c164-11ea-935e-f7227ac3521d.png)

Here you can see the gRPC request being made, but it was made inside an ASP.NET Core server, and there is no telemetry for the incoming HTTP request. The parent ID eab772560269264b (which I assume is the activity created by ASP.NET Core for the incoming HTTP request) is not logged.

**Comment by cijothomas** [comment]
Checking this..

**Comment by cijothomas** [comment]
![image](https://user-images.githubusercontent.com/5232798/86932987-e41bd480-c0ee-11ea-9a87-f63b16b418aa.png)
Asp.Net Core instrumentation is sending null tag value and Zipkin is rejecting. 
1. need to fix instrumentation & add tests (with upcoming changes to Activity, setting null value will be ignored as spec warrants it)
2. fix zipkin exporter to sanitize & not send null tags.

**Comment by JamesNK** [comment]
I retried with the latest packages and it is fixed.

**Comment by CodeBlanch** [comment]
Fixed on #832.
