### ISSUE TITLE
EF Core support

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#79]
Moved from https://github.com/census-instrumentation/opencensus-csharp/issues/114

**Comment by lizthegrey** [comment]
Might be easier to just take https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/EntityFrameworkCore/EntityFrameworkCoreDiagnostics.cs and s/OpenTracing/OpenTelemetry/. Will see if someone here can do it this month.

**Comment by cijothomas** [comment]
Active PR: https://github.com/open-telemetry/opentelemetry-dotnet/pull/929
Closing this in favor of: https://github.com/open-telemetry/opentelemetry-dotnet/issues/928
