### ISSUE TITLE
Add new span kinds: producer and consumer

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#8]

**Comment by trwegner** [comment]
I'd like to take this issue.  Want to confirm that this is to introduce new LinkType in ExportComponent.cs.

**Comment by SergeyKanzhelev** [comment]
@trwegner it's about these two new kinds:

https://github.com/open-telemetry/opentelemetry-java/blob/3cc0af53af6a50837cb4ffdc880ce56f837c8538/api/src/main/java/io/opentelemetry/trace/Span.java#L60-L76

**Comment by SergeyKanzhelev** [comment]
closed via #36
