### ISSUE TITLE
zPages: rpcz support

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#81]
zPages is a great practice many organizations and SRE uses for  the last line of defence while troubleshooting application issues. zPages aggregate telemetry in-process in a memory buffer and allow to query this  informaiton directly from the app. It will be great to design and implement zPages 

See some info on zPages: https://opencensus.io/zpages/

Also features in SRE book.

**Comment by Masquerade0097** [comment]
Hello @SergeyKanzhelev, I find the project idea interesting and would love to work on it in the community bridge program. Please let me know if I can get started with it.

**Comment by SergeyKanzhelev** [comment]
@Masquerade0097 thank you for interest!

I'd suggest the following steps to approach it:

- [ ] Basic project set up. 
   - [ ] Create a separate project. Zipkin can be used as an example.
   - [ ] Implement TelemetryProcessor that will receive all span's creation/finish events.
   - [ ] Make sure you can configure processor to receive all spans
- [ ] Basic zPage
   - [ ] Implement HttpListener (as in Prometheus package) that will return an empty html
   - [ ] Hook up telemetry processor and this httpListener. As a prove that those are connected - write the current number of active spans and the "last seen" span information in html output.
- [ ] Specification on zPage output
   - [ ] Take the zPage [implemented in OpenCensus](https://github.com/census-instrumentation/opencensus-java/blob/c960b19889de5e4a7b25f90919d28b066590d4f0/contrib/zpages/README.md) as a baseline.
   - [ ] Write down very basic specification on zPage output
- [ ] Iterate on zPage output. Update specs, implement it in C#.
- [ ] Perf benchmarking.
   - [ ] Benchmark individual zPage methods
   - [ ] Benchmark zPage with the multiple simultaneous connections

**Comment by Masquerade0097** [comment]
@SergeyKanzhelev Thanks for providing the details. I have started working on the project.

**Comment by VineethReddy02** [comment]
Hi! @SergeyKanzhelev 
Thanks for putting the projects for the community bridge on my request in Otel community. I am already contributing Otel golang client library & Jaegar. As discussed earlier with you. I will be taking up the zpages for Otel go-client.

**Comment by Masquerade0097** [comment]
Hi @SergeyKanzhelev, I have completed the basic setup for the project. Also, I have applied on the community bridge platform to this project. Can you please let me know the next steps ?

**Comment by SergeyKanzhelev** [comment]
@Masquerade0097 unfortunately this time we only have 1 spot for CommunityBridge and it's already taken.

I'll be happy to work with you outside of CommunityBridge program if you are interested. Or stay tuned for GSoC and other opportunities where we plan to participate.

Thank you for your interest!

**Comment by cijothomas** [comment]
Closing zpages is deprecated/removed.

**Comment by schickling** [comment]
Is there any "spiritual successor" to this? i.e. is there a way to query in-progress spans?
