### ISSUE TITLE
Old nuget packages still available

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/opentelemetry-dotnet#811]
I think we should remove the following package from nuget.org:
- https://www.nuget.org/packages/OpenTelemetry.Hosting/0.2.0-alpha.220

Update this packages for the new namespace package (`Instrumentation`):
- https://www.nuget.org/packages/OpenTelemetry.Adapter.AspNet/0.2.0-alpha.275
- https://www.nuget.org/packages/OpenTelemetry.Adapter.AspNetCore/0.2.0-alpha.275
- https://www.nuget.org/packages/OpenTelemetry.Adapter.Dependencies/0.2.0-alpha.275
- https://www.nuget.org/packages/OpenTelemetry.Adapter.StackExchangeRedis/0.2.0-alpha.275

**Comment by pjanotti** [comment]
IIRC we can't delete a package at nuget.org, but delisting seems a good idea. That said I don't think it is worth updating the old packages to the new namespace

**Comment by felpasl** [comment]
OpenCensus Exporter still listed, but we are not able to use it anymore because of changes in structure. I'm trying to use Linkerd with OpenCensus Collector but I'm stuck in without options to talk with Linked mesh trace structure.

**Comment by cijothomas** [comment]
Unsupported packages are "unlisted" from nuget.org now. Closing this.
