### ISSUE TITLE
exporter/stackdriver: distribution range is not allowed

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#82]
From https://github.com/census-instrumentation/opencensus-csharp/issues/110

I've tried using distribution aggregation with stackdriver exporter, but it does not work.
It looks like the same issue as in GO package - https://github.com/census-instrumentation/opencensus-go/issues/143

**Comment by jacostro** [comment]
I encountered the same problem. Exception from Stackdriver client explicitly said that `range` is not supported yet, and this section in documentation:
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#Distribution
says for `range`:
> If specified, contains the range of the population values. The field must not be present if the count is zero. This field is presently ignored by the Stackdriver Monitoring API v3.

**Comment by cijothomas** [comment]
Closing as StackDriver exporter is not part of this repo, and the previous metrics api is removed.
