### ISSUE TITLE
ActivityKind set using reflection

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#829]
ActivityKind is set using reflection now.
https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.Dependencies/Implementation/HttpHandlerDiagnosticListener.cs#L78-L79

This is because Activity for old DiagnosticSource based instrumentation will have Kind set to Internal always and that needs to be updated to the correct Kind. It was originally assumed that .NET Activity.Kind was not settable by mistake, but turns out it is by design. We don't want to allow one to change the Kind after creation. (We can change DisplayName, add Events, add Tags, but *not* change Kind after creation).

This leaves only Reflection approach for the InstrumentationAdapter. This issue is opened to track converting the reflection calls to be more perf optimized, similar to the approach taken here: https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.Dependencies/Implementation/PropertyFetcher.cs

**Comment by eddynaka** [comment]
Hello,

I did some tests using two options:
- Reflection
- Expression

Reflection (the same that we have right now):
```csharp
[Benchmark]
public Activity ActivityWithReflection()
{
    Activity activity = new Activity("activity-with-reflection");
    activity.GetType().GetProperty("Kind").SetValue(activity, ActivityKind.Client);

    return activity;
}
```

Expression:
```csharp
static Action<Activity, ActivityKind> setterNameProperty = CreateSetter("Kind");

public static Action<Activity, ActivityKind> CreateSetter(string name)
{
    ParameterExpression instance = Expression.Parameter(typeof(Activity), "instance");
    ParameterExpression propertyValue = Expression.Parameter(typeof(ActivityKind), "propertyValue");

    var body = Expression.Assign(Expression.Property(instance, name), propertyValue);

    return Expression.Lambda<Action<Activity, ActivityKind>>(body, instance, propertyValue).Compile();
}

[Benchmark]
public Activity ActivityWithExpression()
{
    var activity = new Activity("activity-with-expression");

    setterNameProperty(activity, ActivityKind.Client);

    return activity;
}
```

With that, I achieved using BenchmarkDotNet:
|                 Method |      Mean |    Error |    StdDev |
|----------------------- |----------:|---------:|----------:|
| ActivityWithReflection | 254.23 ns | 5.175 ns | 11.994 ns |
| ActivityWithExpression |  17.84 ns | 0.355 ns |  0.349 ns |

I did some other tests like doing a for from 0 to 1_000_000 and execute each method
reflection: 192ms
expression: 43ms

```csharp
public static void ActivityWithReflectionVoid()
{
    for (int i = 0; i < 1_000_000; i++)
    {
        Activity activity = new Activity("activity-with-reflection");
        activity.GetType().GetProperty("Kind").SetValue(activity, ActivityKind.Client);
    }
}

public static void ActivityWithExpressionVoid()
{
    for (int i = 0; i < 1_000_000; i++)
    {
        var activity = new Activity("activity-with-expression");

        setterNameProperty(activity, ActivityKind.Client);
    }
}
```
