### ISSUE TITLE
Collections util methods may be unnecessary

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#83]
See comments here: 

https://github.com/census-instrumentation/opencensus-csharp/pull/41#pullrequestreview-153438383

![image](https://user-images.githubusercontent.com/9950081/49106866-2efa1880-f239-11e8-979d-6b2e37769670.png)

**Comment by trwegner** [comment]
Please assign this issue to me.

**Comment by austinlparker** [comment]
@trwegner done, enjoy!

**Comment by trwegner** [comment]
thanks @austinlparker.  wondering if there are objections to also converting to use nameof() in these methods to eliminate literal string for class and member names:

        public override string ToString()
        {
            return "Status{"
                    + "canonicalCode=" + this.CanonicalCode + ", "
                    + "description=" + this.Description
                    + "}";
        }

would change to 

        public override string ToString()
        {
            return nameof(Status) + "{"
                    + nameof(this.CanonicalCode) + "=" + this.CanonicalCode + ", "
                    + nameof(this.Description) + "=" + this.Description
                    + "}";
        }

**Comment by austinlparker** [comment]
works for me

**Comment by lmolkova** [comment]
I believe this was fixed in some clean up round. There are no more Collections utils
