### ISSUE TITLE
How to simplify the usage of OT and Instrumentation

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/opentelemetry-dotnet#831]
Right now, if we want to use OT and Instrumentation for aspnetcore we would have to:
```csharp
services.AddOpenTelemetry((builder) => builder
    .AddRequestInstrumentation()
    .AddDependencyInstrumentation()
    .UseZipkinExporter(o =>
    {
        o.ServiceName = this.Configuration.GetValue<string>("Zipkin:ServiceName");
        o.Endpoint = new Uri(this.Configuration.GetValue<string>("Zipkin:Endpoint"));
    }));
```

So, the idea was to simplify this..the user wouldn't need to add all this lines.

When we started the idea of the "metapackages", it would work like: `services.AddOpenTelemetryWithInstrumentation`, but, that had a problem, because i wasn't exposing the OpenTelemetryBuilder, with that, I couldn't add the `Exporter`.

What can we do to achieve something like that and simplify the usage of OT?

**Comment by AndyPook** [comment]
I would suggest that the OTel api needs to be "granular" in this way. It needs to be "unopinionated" about what a system requires.
Maybe my app does not want the same "defaults" that some other app does ? Or I have several different "types" of service (API, message subscriber...) that each need different things.

If a given app use case needs a certain set of "instrumentation" enabled, then it is simple to create an extension that sets them up. Use that extension where appropriate.

But leave the OTel api should remain granular

**Comment by rjgotten** [comment]
> I would suggest that the OTel api needs to be "granular" in this way. It needs to be "unopinionated" about what a system requires.

It should be unopinionated to the point where `.AddOpenTelemetry(builder => { /*... */ })` doesn't actually do anything at all, unless you explicitly add things to `builder`.

This facilitates scenarios where telemetry is conditionalized based on some application-level `IOptions<>` instance that is pulled from a service provider. E.g. in its simplest form where there is a master switch to turn everything on or off:

```cs
services.AddOpenTelemetry((serviceProvider, builder) =>
{
  var options = serviceProvider.GetRequiredService<AppTelemetryOptions>().Value;
  if (!options.Enabled) return;
  
  builder
    .AddRequestInstrumentation()
    .AddDependencyInstrumentation()
   // ...
}
```

**Comment by cijothomas** [comment]
> It should be unopinionated to the point where .AddOpenTelemetry(builder => { /*... */ }) doesn't actually do anything at all, unless you explicitly add things to builder.

Isn't that the current behavior already?

**Comment by rjgotten** [comment]
> 
> 
> > It should be unopinionated to the point where .AddOpenTelemetry(builder => { /*... */ }) doesn't actually do anything at all, unless you explicitly add things to builder.
> 
> Isn't that the current behavior already?

Afaik, yes. This was meant as an emphasized: "and please keep it that way, because..."

**Comment by cijothomas** [comment]
Closing old issues. A lot has changed (ext.hosting is stable now), since the original issue was discussed!
