### ISSUE TITLE
Performance and benchmarking

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#84]
1. we should understand the performance of OC and fix bottlenecks if any
2. we should make it easy to run and experiment (e.g. opencensus-java allows to run benchmarking as unit tests) - can we do it?

I'd suggest to use https://benchmarkdotnet.org/

**Comment by lmolkova** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/262 provides a way to test certain isolated APIs or very small scenarios and helps during development - you can run it for master vs your branch and see the difference. Or use it as a way to find bad (in terms of perf) implementation or API choice.

We still need to have integration perf-test for typical web-service:

- Enable default instrumentation: incoming requests (manual instrumentation or auto-collected) + outgoing requests, standard metrics.
- Compare service perf with and without instrumentation.

BenchmarkDotNet doesn't seem to be the right tool for it but we might be able to reuse parts of ASP.NET Core benchmarking infra for this: https://github.com/aspnet/Benchmarks.

**Comment by cijothomas** [comment]
benchmarking is ready. Atleast basic version. We can improve in future.
