### ISSUE TITLE
Should we move Benchmark to test folder before beta release?

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#872]
Technically benchmark / integration test / stress test are all tests (which we don't ship as part of the final bits).
We might want to move the benchmark project under `test` folder in order to have less top level folders.

**Comment by cijothomas** [comment]
Agree.

**Comment by eddynaka** [comment]
I can move that.

**Comment by eddynaka** [comment]
@cijothomas / @reyang , should we change to test/benchmarks or should we just copy the projects from benchmarks and add to test folders? What do you think?

**Comment by reyang** [comment]
> @cijothomas / @reyang , should we change to test/benchmarks or should we just copy the projects from benchmarks and add to test folders? What do you think?

No strong opinion here. I guess just move the project? For example https://github.com/JamesNK/Newtonsoft.Json/tree/master/Src/Newtonsoft.Json.Tests/Benchmarks.
