### ISSUE TITLE
Should we continue to use sample or change to example before beta release?

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#873]
Something I always wanted to ask but forgot due to lower priority...

Other OpenTelemetry projects use `example` other than `sample`, .NET is the strange one here:
* C++ https://github.com/open-telemetry/opentelemetry-cpp/tree/master/examples
* Python https://github.com/open-telemetry/opentelemetry-python/tree/master/docs/examples
* Go https://github.com/open-telemetry/opentelemetry-go/tree/master/example
`sample` and `sampler` have special meaning related to sampling, having examples called samples makes searching harder.

**Comment by eddynaka** [comment]
Looking at the other repositories, C++ / Go / Java have the example(s) folder. For python, its inside docs, and that docs is the generated one...

I think we can change to Examples folder/namespace as well.

Let me know. I can submit a PR.

**Comment by cijothomas** [comment]
Okay to rename sample to example.

**Comment by eddynaka** [comment]
Let's use **Examples**, since we will have more than one.
