### ISSUE TITLE
Establish release cycles in both this and contrib repo

### ISSUE THREAD

**Issue by dbarbashov** [open-telemetry/opentelemetry-dotnet#882]
Right now there is no formal release cycle and no actual information about planned features/milestones and overall project status. There is no way for contributors to know when to expect next release.
From gitter: as @CodeBlanch said right now packages are pushed on demand. So we need to establish release cycles with milestones. About after beta as @cijothomas said.

**Comment by cijothomas** [comment]
I'll cleanup milestones in this repo first, then do the contrib repo. Both will happen after the current beta release.

**Comment by cijothomas** [comment]
This repo is cleaned up and milestones are currently set. Issues for next beta is assigned as well. Closing this.
Will need something similar for -contrib repo.
