### ISSUE TITLE
Separate OpenTelemetry.Instrumentation.Dependencies into individual projects

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#888]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.Dependencies current has HttpClient, SqlClient, GrpcClient.
Proposing to split them into separate own package, rather than the "bundle" :)

**Comment by CodeBlanch** [comment]
Personally, I like them together. I feel like we have too many packages already 🤣 Is this what the other SIGs do?

**Comment by cijothomas** [comment]
> Personally, I like them together. I feel like we have too many packages already 🤣 Is this what the other SIGs do?

This is necessary. I don't see any strong reason to keep them together. See python:
https://github.com/open-telemetry/opentelemetry-python/tree/master/ext
