### ISSUE TITLE
Re-shape samples

### ISSUE THREAD

**Issue by discostu105** [open-telemetry/opentelemetry-dotnet#89]
Currently, there is just one project called "Samples", which contains examples of exporters. Then there is a solution folder called "testdata" with an ASP.Net Core project as example for how to use OpenTelemetry in ASP.NET Core.

What I am missing is an example of how to implement your own Tracer. I tried to add one, but then was not sure where to put it. "samples" vs. "testdata"? Should we combine them?

Suggestion:
 * Create a solution folder called "Samples"
 * Add samples, as separate projects for:
   * Exporter-implementations
   * ASP.NET Core sample
   * Tracer-Implementors (e.g. a simple logging-tracer), along with Sample-usage projects (e.g. simple console app, asp.net core app)
 * Each sample project should have a readme.md that explains what the sample project is supposed to show.

What do you think about that?

**Comment by discostu105** [comment]
More specifically, I would just

 * move `Samples` project to `samples\Exporters`
 * move `testdata\TestApp.AspNetCore.2.0` to `samples\TestApp.AspNetCore.2.0`
 * add `samples\LoggingTracer\LoggingTracer`
 * add `samples\LoggingTracer\ConsoleApp`
 * add `samples\LoggingTracer\AspNetCore.2.0`

**Comment by SergeyKanzhelev** [comment]
`testdata\TestApp.AspNetCore.2.0` is used in tests. Do you want to make a copy instead?

**Comment by SergeyKanzhelev** [comment]
one additional example - how library must be instrumented with an API.

**Comment by discostu105** [comment]
You're right, `testdata\TestApp.AspNetCore.2.0` is actually used in unit-tests, so I believe it is ok to keep it in `testdata` folder as it is for now.

**Comment by discostu105** [comment]
Closing this issue now. Sample folder has been created and LoggingTracer is on its way (#92).
