### ISSUE TITLE
Review all public APIs before GA

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#898]
We should review all the public APIs line by line before GA to make sure we don't ship APIs by accident.

Related to:
* #806
* https://github.com/open-telemetry/opentelemetry-dotnet/pull/892#issuecomment-662812470
* https://github.com/open-telemetry/opentelemetry-dotnet/pull/1083#discussion_r471010474
* Also need to check if cctor and static members would throw and trigger TypeInitializationException.

**Comment by cijothomas** [comment]
Closing as public api for 1.0.0 components are complete.
