### ISSUE TITLE
Is there have any use example for metrics sdk?

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#910]
**Describe your environment.** Describe any aspect of your environment relevant to the question:

**What are you trying to achieve?**
What did you expect to see?
The otlp is reach beta, Is there have any use example for metrics sdk? thanks.
**Additional context.**
Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by eddynaka** [comment]
Hi @czs1993 , from the home page, we have a section that redirects to the exporters. There you can find how to use. Or, you can look in `samples/Console` folder to see some samples.

**Comment by czs1993** [comment]
@eddynaka  thanks.
