### ISSUE TITLE
Known issues with 0.4.0-beta2 release

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#925]
(Will keep updating this for initial few days, so its easy to know what known issues exist in this version)

Correlation-context and Context is not documented. Its possible that Activity.Baggage already covers this, but this must be verified against the spec and documented.
No support for Compose-Propagation or Global-Propagator. 
The Tracer shim API  exposes subset of methods from spec - like there is StartSpan (which makes the span active),

**Comment by reyang** [comment]
Could we merge this into #506?
