### ISSUE TITLE
Npgsql Postgresql client instrumentation

### ISSUE THREAD

**Issue by Place1** [open-telemetry/opentelemetry-dotnet#928]
The current `OpenTelemetry.Instrumentation.SqlClient` package can be used to instrument MSSQL clients; could a new package be added for Postgresql (Npgsql.EntityFrameworkCore.PostgreSQL) or perhaps a more general Entity Framework Core instrumentation library?

Locally i've refactored the current SqlClient instrumentation to make it work more generally with Microsoft.EntityFrameworkCore diagnostics and I can now trace my postgres client calls. I don't have a windows machine to do the same on .NET Framework. Would anyone like me to submit a PR with the code to have a look?

**Comment by cijothomas** [comment]
Love to see what modifications you made to support EFCore. Please submit a PR. We may make it part of -contrib repo : https://github.com/open-telemetry/opentelemetry-dotnet-contrib
But we can decide that later.

**Comment by Place1** [comment]
hey @cijothomas you can see the changes in the related PR above (#929)

**Comment by roji** [comment]
For anybody landing here, native OpenTelemetry support is going into Npgsql itself, without needing any external instrumentation library: https://github.com/npgsql/npgsql/pull/4037

**Comment by cijothomas** [comment]
> For anybody landing here, native OpenTelemetry support is going into Npgsql itself, without needing any external instrumentation library: [npgsql/npgsql#4037](https://github.com/npgsql/npgsql/pull/4037)

Thanks for sharing!

Do take a look here: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#writing-own-instrumentation-library

In this case, only thing that needs to publicly available is the name of the ActivitySource used by npgsql.
(Optionally extension method AddNpgSql() may be offered, which internally does AddSource())

**Comment by roji** [comment]
> (Optionally extension method AddNpgSql() may be offered, which internally does AddSource())

That's a nice idea, is that standard practice? If so, I'll definitely add it.

**Comment by roji** [comment]
I'm thinking this would become more interesting if we want to expose an API to allow people to tweak the tracing config. I'll think about this a bit.
