### ISSUE TITLE
The Metrics Sdk of "LabelSetSdk" SortAndDedup could base on Configs?

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#949]
**Describe your environment.** Describe any aspect of your environment relevant to the question:
When I use the metrics Sdk to collector metrics, the emitting Metrics labels is Sorted.  however ,In some time ,we create a labelset not hope to sorted .
eg:
```

  var labels1 = new List<KeyValuePair<string, string>>(); 
            labels1.Add(new KeyValuePair<string, string>("url", "testurl"));
            labels1.Add(new KeyValuePair<string, string>("method", "POST"));
            labels1.Add(new KeyValuePair<string, string>("status", "200"));
meter.GetLabelSet(labels1);
```
the emitting  was :  {method="POST", status="200", url="testurl"}
however, I expect emitting   was {url="testurl",method="POST",status="200"}
**What are you trying to achieve?**
What did you expect to see?
the Meter.GetLabelSet(IEnumerable<KeyValuePair<string, string>> labels) could Provides a configuration parameter to set whether sorting is required?
eg: Meter.GetLabelSet(IEnumerable<KeyValuePair<string, string>> labels, bool sorted=true),the default is need sorted,

**Comment by cijothomas** [comment]
Thanks for reporting the issue. Since our implementation, LabelSet as a concept has been removed from the Metric specs. We need to re-evaluate the alternates, and address concerns at that time.
Don't think the spec has anything about ordering.

I am curious to see why you want a particular order retained for dimensions? Does it impact Prometheus in any way?

**Comment by czs1993** [comment]
it has no impact for Prometheus.But when I develop a custom Exporter and Metrics receivers,It might have the following effect:
1、A collection of Tags normally defines a hierarchy
eg:
 {servicehost = “www.xx.xx.com”, "servicename ="fileuploadservice", serviceport =“8080”, path = "/imageupload“, method="POST", status ="200"}.
If the default sort is done, the metric labels shown cannot show the hierarchical relationship of the dimensions after the indicators are received by the receiving end. Although developers can tell, the default ordered hierarchy is friendlier.
2、When I use the MetricSdk to collect metrics, I use the following samples:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using OpenTelemetry;
using OpenTelemetry.Instrumentation;
using OpenTelemetry.Metrics;
using OpenTelemetry.Metrics.Export;
using OpenTelemetry.Trace;

namespace TraceDemo
{
    public class MetricListenerhandler : ListenerHandler
    {
        private static MeterProvider _meterProvicer;

        public static MeterProvider meterProvicer
        {
            get
            {
                if (_meterProvicer == null)
                {
                    _meterProvicer = Sdk.CreateMeterProvider(mb=>
                    {
                        mb.SetMetricExporter(null);
                        mb.SetMetricProcessor(new UngroupedBatcher());
                        mb.SetMetricPushInterval(TimeSpan.FromSeconds(1));
                    });
                }
                return _meterProvicer;

            }
        }

        private static Meter meter = meterProvicer.GetMeter("Record the request count of http in");

        private static CounterMetric<long> counterMetric = meter.CreateInt64Counter("http_response_count");

        private static void ResponseCountStats(string path, string method, string statusCode)
        {
            // 
            var labels = new List<KeyValuePair<string, string>>()
            {
                new KeyValuePair<string, string>("service_host", "www.xx.xx.com"),
                new KeyValuePair<string, string>("service_name", "fileuploadservice"),
                new KeyValuePair<string, string>("path", path),
                new KeyValuePair<string, string>("method", method),
                new KeyValuePair<string, string>("status", statusCode)
            };
            var defaultContext = default(SpanContext);
            // add counter
            counterMetric.Add(defaultContext, 1, meter.GetLabelSet(labels));
        }
        public MetricListenerhandler(string name) : base(name)
        {
        }
       
        public override void OnStopActivity(Activity activity, object payload)
        {
            var result = payload.GetType().GetProperty("HttpContext");
            if (result == null || !(result.GetValue(payload) is HttpContext context))
            {
                return;
            }

            var path = context.Request.Path;
            var method = context.Request.Method;
            var statusCode = context.Response.StatusCode.ToString();

            // Record number of requests
            ResponseCountStats(path, method, statusCode);
        }
    }
}
```
Labels need to create new objects when you count indicators, because the label value is dynamic.If it have 1000 requests per second, sort the same labels 1000 times. It will have an impact on performance. So, it makes sense to provide  a configuration to set whether sorting is required, And we could put the sorting of labels in PushMetricController,I only decide if I want to sort Labels when the metrics are submitted.

**Comment by cijothomas** [comment]
Closing old metrics issues.
