### ISSUE TITLE
When will the opentelemetry instrumentation libraries support to entityframeworkcore trace collect?

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#950]
**Describe your environment.** Describe any aspect of your environment relevant to the question:

**What are you trying to achieve?**
Collect the trace of EntityFrameworkcore.
What did you expect to see?
The Instrumentation of SQLClient in the Beta version of OTLP cannot collect trace information for an EntityFrameworkcore,Will support be provided in a later version? thanks.
**Additional context.**
Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by cijothomas** [comment]
There is a open PR to add EF support. Once that is merged and released, we'll have the ability for the same.
