### ISSUE TITLE
Whether the MeasureMetricSdk in the Metrics Sdk supports the collection of the distribution of values？

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet#951]
**What are you trying to achieve?**
The [metrics of opentelemetry-specification ](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#valuerecorder) Introduce that the data distribution  information can be recorded by ValeRecorde, but the MeasureMetricSdk did not provide quantile boundary setting. There are only quantiles of 0 and 1 in the output information. the P99、P95、P90 will not be record.

**Comment by cijothomas** [comment]
This is true now - Histogram or Qualitile type aggregations are not implemented for .NET Metrics. We'll be adding more features as metrics specs are ready.
(This is not planned for next beta)
