### ISSUE TITLE
Detect unused using statements during CI

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#957]
It looks like we're lacking some nice protection from CI:

1. Better format (if you run `dotnet-format --folder .` under the root folder today, you will find several files being reformatted).
2. Unused `using`.

It would be great if we can automatically enforce this for the pull requests.

**Comment by eddynaka** [comment]
@reyang , thanks for the suggestion. Just created a new workflow which will validate our files.

And, in the same PR i'm already solving our current issues.

**Comment by eddynaka** [comment]
@reyang @cijothomas , we can close this. With the "dotnet format", we will receive a warning.
