### ISSUE TITLE
Need to rename BroadcastActivityProcessor

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#979]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/735#discussion_r441630390

**Comment by eddynaka** [comment]
Are we going to change to FanOutActivityProcessor ?

**Comment by reyang** [comment]
I'm fine with either `AggregatedActivityProcessor`, `FanOutActivityProcessor` or `MultiActivityProcessor`, as long as it is not misleading / having `broadcast`.
Let's see what @alanwest @cijothomas @CodeBlanch would recommend.

**Comment by CodeBlanch** [comment]
For some reason, I feel strongly against `AggregatedActivityProcessor`. Seems to suggest we are aggregating activity/spans somehow?

Either `FanOutActivityProcessor` or `MultiActivityProcessor` I'm good with. I think technically "fan out" reflects what is going on the best. But `MultiActivityProcessor` is used by other repos (more or less) and there is some value in sharing names/concepts.

If I had 3 points to assign: 2 FanOutActivityProcessor, 1 MultiActivityProcessor, 0 AggregatedActivityProcessor.

**Comment by alanwest** [comment]
> For some reason, I feel strongly against `AggregatedActivityProcessor`. Seems to suggest we are aggregating activity/spans somehow?

Agreed that `Aggregated` does not inspire the correct meaning in my mind.

> But MultiActivityProcessor is used by other repos (more or less) and there is some value in sharing names/concepts.

I'd lean more towards this argument that `Mutli` is a good way to go. I do see the appeal of `FanOut`, though the only context I've seen this in is messaging systems (that said, there may be other contexts I'm not thinking of, so I could be swayed)

**Comment by cijothomas** [comment]
The functionality done by the BroadCastActivityProcessor is *not* covered in spec. Spec currently has Simple/batching, and does not mention anything about "fan out or broadcast". Spec also talks about multiple pipelines - but I am guessing we can achieve multiple pipelines by instantiating multiple TracerProviders, each with own config. If we do that, then we would no longer need the equivalent of BroadCastProcessor.

**Comment by reyang** [comment]
#923 is using the word `Composite` 😄

**Comment by eddynaka** [comment]
> #923 is using the word `Composite` 😄

Took from the spec.

**Comment by eddynaka** [comment]
@reyang @cijothomas , we can close this.
