### ISSUE TITLE
Option for custom tagging in instrumentation libraries

### ISSUE THREAD

**Issue by christopher-taormina-zocdoc** [open-telemetry/opentelemetry-dotnet#981]
**Describe your environment.** Describe any aspect of your environment relevant to the question: Using aspnetcore 2.1 

**What are you trying to achieve?**
I'm setting up an aspnetcore server with both the aspnetcore and redis instrumentations. I'm looking to add a bunch of relevant tags to spans. For example, I want the span created by the aspnetcore instrumentation to have a tag with a value set based on the value of a specific header, while I want the redis spans to have additional information about keys used in the call to redis. Currently Im resorting to using a custom middleware for the additional http tags, while for redis I'm just manually instrumenting the spans around my calls so I can add the additional tags.

Is there an instrumentation specific option to set to allow me to set additional tags from the original context? Or is the recommended way using the `TracerProvider` the to try to get the current relevant span?

**Additional context.**
Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by cijothomas** [comment]
I think https://github.com/open-telemetry/opentelemetry-dotnet/issues/73 is covering this. There is a proposal to solve this, we haven't finalized yet. But issue #73 is already covering this right?

**Comment by christopher-taormina-zocdoc** [comment]
Ah yeah I think that would cover it, assuming whatever solution is extended to each of instrumentation libraries.
